### ISSUE TITLE
Suggestion: Message verification from URL

### ISSUE THREAD

**Issue by blha303** [keybase/keybase-issues#1019]
It would be cool to be able to paste a [reddit URL](https://www.reddit.com/r/KeybaseProofs/comments/2gqoj0/my_keybase_proof_redditsuudo_keybaseblha303/cklmzl4) (for example) and have keybase retrieve the relevant text and pipe it to gpg for verification. Especially since copy-pasting from a reddit comment doesn't work, because reddit [screws up PGP signed messages](https://github.com/keybase/keybase-issues/issues/1016#issuecomment-56006724).

**Comment by patcon** [comment]
You might want to :+1: this issue and subscribe :)
https://github.com/keybase/keybase-issues/issues/2170
