### ISSUE TITLE
"error: Index timed out" when running keybase-installer

### ISSUE THREAD

**Issue by dustmop** [keybase/keybase-issues#104]
$  sudo keybase-installer
info: Made temporary directory: /tmp/keybase_install_Aijp60yK-XQVXBONFxB9PQ
info: Creating permanent keyring dir: /root/.keybase-installer/keyring
warn: No code-signing key (code@keybase.io) in GPG keychain
info: Fetching URL https://dist.keybase.io/sig/files/1/keyset.json
info: Installing keyset version 1
info: Using keyset version v1
info: Fetching URL https://dist.keybase.io/sig/files/1/index.asc
info: cleaning up tmpdir /tmp/keybase_install_Aijp60yK-XQVXBONFxB9PQ
error: Index timed out: 373 > 300

$ sudo keybase-installer
info: Made temporary directory: /tmp/keybase_install_6HQGaukziBCRxHUj5L0VLg
info: Using keyset version v1
info: Fetching URL https://dist.keybase.io/sig/files/1/index.asc
info: cleaning up tmpdir /tmp/keybase_install_6HQGaukziBCRxHUj5L0VLg
error: Index timed out: 374 > 300

$ sudo keybase-installer
info: Made temporary directory: /tmp/keybase_install_tJjLMMc_SHRdKAUtRHKHiQ
info: Using keyset version v1
info: Fetching URL https://dist.keybase.io/sig/files/1/index.asc
info: cleaning up tmpdir /tmp/keybase_install_tJjLMMc_SHRdKAUtRHKHiQ
error: Index timed out: 379 > 300

---

Afterwards keybase command does not work; installation was incomplete. Running on Archlinux 3.12.1-1

**Comment by felirami** [comment]
The timezone on the server-side of microsoft hasnt updated to the current time of my country (Chile), so I had to change the time one hour earlier for this to work (and through the microsoft update feature on windows 7).
