### ISSUE TITLE
Error: Cannot find a public key for ''

### ISSUE THREAD

**Issue by amingilani** [keybase/keybase-issues#1114]
![bug screenshot](https://cloud.githubusercontent.com/assets/1188552/4521245/b63df5ba-4d0a-11e4-92da-72020d133b99.png)

Tested on Firefox and Chrome in Ubuntu. Steps to recreate:
1. Open a user profile & click `Encrypt`
2. Type message & `Encrypt`
3. `Done - Nuke the plaintext`
4.  Type message & `Encrypt`
5. `Error: Cannot find a public key for ''`

**Comment by gwpl** [comment]
After setting up Keybase on Linux, and Two Android devices (and confirming myself via services like github), 
I've tried to encrypt message to myself using:
https://keybase.io/encrypt

However I received error:

`Error: Cannot find a public key for 'gwpl'`

Unfortunately neither webapp, neither desktop app give me a clue how to upload my Keybase public key.
Additionally, I see on https://keybase.io/encrypt option to decrypt, it makes me worried -> does it mean that my private key will be also stored not on my devices?
I would which to keep private key only on my devices of choice (preferably subset of devices where I installed Keybase) and than upload only public key.

Therefore:

* How to do achieve this?
* Where is it placed in documentation? Shouldn't apps ( or https://keybase.io/encrypt ) point to such documentation (especially on error like one I received) ?
