### ISSUE TITLE
Suggestions (Soundcloud, Tumblr)

### ISSUE THREAD

**Issue by kuka** [keybase/keybase-issues#1142]
Hi guys,

it seems like major amount of users at the moment are devs or similar. What about adding more user-friendly services like Tumblr/Soundcloud? Less IT-savvy folks are critical.

**Comment by robertodealmeida** [comment]
Bumping this since I would also love to see Soundcloud supported.

Maybe we could post a song with the key encoded in it?

**Comment by jimeh** [comment]
:+1: I'd like to see SoundCloud support too :)
