### ISSUE TITLE
installer wants a too new nodejs

### ISSUE THREAD

**Issue by abonillasuse** [keybase/keybase-issues#1166]
The installer wants a way too new nodejs version. Why, which are the requirements for such a new version?

abonilla:~ # keybase-installer
error: Your version of node (0.10.5) is out of date; please upgrade to 0.10.32 or better

OpenSUSE provides 0.10.5 and 0.10.26
Ubuntu provides 0.10.25
Architecture: amd64
Version: 0.10.25~dfsg2-2ubuntu1

**Comment by aspiers** [comment]
I think this installation route is now obsolete, so presumably this can be closed?

**Comment by maxtaco** [comment]
Yeah, agreed, this is obsolete.
