### ISSUE TITLE
API: No way to tell keybase to check for a proof after posting a signature (e.g. twitter)?

### ISSUE THREAD

**Issue by gabriel** [keybase/keybase-issues#1202]
I generated a signature for twitter account gbrltest: https://twitter.com/gbrltest

It would be nice if I could tell keybase API the client posted a proof to twitter (after generating the web_service_binding.twitter signature) and that it should try to validate it. Then I'd like to update the user on the client right after it gets validated so the photo comes up etc.

It would be cool if this call blocked while it was checked but if not, or I can poll for updates.

**Comment by kirelagin** [comment]
Does `sig/retry` still work? Whatever I try to do with it, I get:

~~~~
{'desc': 'no proof matching inputs', 'name': 'DB_UPDATE_ERROR', 'code': 504}
~~~~

(And `sig/posted` with this same `proof_id` works fine.)

**Comment by maxtaco** [comment]
It does still work, but only once your proof is marked "permanent failure."  Before then, we're checking in the background once every minute or so.

**Comment by kirelagin** [comment]
Oh, right I see it now. And what do `LOOKING`, `SUPERSEDED` and `POSTED` states mean? And is `proof_status` documented somewhere?

**Comment by maxtaco** [comment]
The initial state is `POSTED` when the front-end inserts a row into the database.  When the backend proof-checker process picks up the new entry, it flips the state to `LOOKING`.  If you were to post a new twitter/github/reddit, etc proof with an old one still active, the old ones will be flipped to `SUPERSEDED`.

No, this isn't documented anywhere.  We need to do a better job documenting.  We'll discuss #1451 today.  Many thanks!
