### ISSUE TITLE
Export private key from keybase.io

### ISSUE THREAD

**Issue by milosgajdos** [keybase/keybase-issues#1264]
Is it possible to export the private key from keybase.io ?

I'd like to import it into my keychain on my laptop.

Thanks

**Comment by gautiermichelin** [comment]
Did this move ?

<img width="428" alt="capture d ecran 2015-09-27 a 17 02 46" src="https://cloud.githubusercontent.com/assets/314697/10123431/9f38b6be-6539-11e5-8eca-5937ee28056a.png">

**Comment by maxtaco** [comment]
it's now a per-key option. click on the menu next to your key.

**Comment by fvanderbiest** [comment]
@maxtaco could you post a screenshot please, I must be blind ...

**Comment by maxtaco** [comment]
<img width="827" alt="screen shot 2015-11-16 at 8 42 45 am" src="https://cloud.githubusercontent.com/assets/866815/11183136/0beba32c-8c3e-11e5-8af1-15ad2c84bc56.png">

See the last item on that menu.

**Comment by fvanderbiest** [comment]
It appears that I don't have this menu
![capture du 2015-11-16 14 45 27](https://cloud.githubusercontent.com/assets/265319/11183243/fa27a5ea-8c70-11e5-8ea1-2be98e48cce5.png)

**Comment by maxtaco** [comment]
You have this menu, it's right there.

**Comment by fvanderbiest** [comment]
Strange. Now it works... 
Thanks max

**Comment by joelklee** [comment]
Thanks for the tip. I would not have found that in the UI without the pointer. The UI could use an upgrade in this regard IMO.

**Comment by jkingsman** [comment]
Has this option been moved/removed?

**Comment by wwarlock** [comment]
Having installed keybase for a long time and didn't open it for a long too.
So, today I found I'm having the same problem.
But I haven't export options even near the key.
Am I missed something?

![keybase_export_problem](https://cloud.githubusercontent.com/assets/478413/19019722/8402600a-8899-11e6-846e-0343807f6b80.png)

**Comment by malgorithms** [comment]
@wwarlock  - in your case it means you never hosted an encrypted copy of your private key on keybase. either (a) you brought in a key from the outside, or (b) you generated one with keybase, but opted out of keybase hosting the private key.   (Since the comment on the public key mentions keybase, it seems the latter is more likely.

 If you've lost your private key, you'll need to reset your account and start over. You can do that by clicking the gear in the top right corner of that page.

**Comment by wwarlock** [comment]
@malgorithms - Thanks for the answer.
But I must to say I've always did only that keybase have been sugests.
So, now I've did reset and regenerated that key.
It looks exactly as the last time.
But at first time the key didn't saved on the server.
I don't know the reason why.

Ok, the problem solved.
For others with the similar symptoms I can say, do not reset setting until you try the other options (look at screenshot).
You loose your connections. Please look at the sample below.
How looks the connection at another side.
![keybase_export_problem_3](https://cloud.githubusercontent.com/assets/478413/19039958/a0da0c36-898a-11e6-9286-dc337853097c.png)

And on my site.
![keybase_export_problem_2](https://cloud.githubusercontent.com/assets/478413/19039959/a0dc8556-898a-11e6-81b5-d61ce7768281.png)

**Comment by NicsTr** [comment]
This is most likely to be the first result of the Google search, so for the people still wondering how to export unhosted private key: see last comment of #1912.

**Comment by omarryhan** [comment]
If you're on a terminal where you have the Keybase CLI installed, you can export your private key by executing: `keybase pgp export`

**Comment by gtmtech** [comment]
`keybase pgp export` exports a `PUBLIC KEY BLOCK` for me, not a private one

**Comment by mihotan** [comment]
is it possible to export the secret if we have forgotten the passphrase ? or reset the passphrase on the account without resetting the account ? I guess I should just create a new GPG key at this point, but I'd like to know if there is another solution.

**Comment by Engelberg** [comment]
My PGP key, which was generated in keybase and stored in keybase a long time ago, no longer is listed under my profile on the website. Perhaps this has something to do with keybase's expired security certificate earlier this year? The public key does show up in the PC client, but the client doesn't appear to have a menu for downloading the private key.

I'm interested in changing my password, but I see a warning that this will delete the pgp key, so I'm trying to figure out how to download the pgp private key, so I can upload it again after changing the password. I think I can figure out how to do it via the command line if need be, but I'm not certain how secure/insecure that process is.

**Comment by dlamblin** [comment]
> `keybase pgp export` exports a `PUBLIC KEY BLOCK` for me, not a private one. Needs to be `keybase pgp export -s`

Might be worth noting that the apparent infinite hang on the command line is due to the Keybase app throwing up a dialog for the passphrase, with a checkbox that seems unclear in purpose. For a multi-monitor setup it was not on the same monitor as the Terminal and Keybase app itself (MacOS). It also prompted twice in succession before printing the key instead of once.
