### ISSUE TITLE
No valid primary key self-signature

### ISSUE THREAD

**Issue by TonyHoyle** [keybase/keybase-issues#1270]
Same issue as #745 and #304 

See http://pgp.mit.edu/pks/lookup?op=vindex&search=0x9D6A090E9E3C20D4 - the last selfsig has no expiry date and all the other signatures are either in-date or superceded.  To be certain, I re-signed it and the error remained.

**Comment by camponez** [comment]
I also got the 

error: Could not open key: no valid primary key self-signature (error #905)

when I try to track someone

**Comment by maxtaco** [comment]
paste in a copy of your public key?

**Comment by camponez** [comment]
https://keybase.io/camponez/key.asc

**Comment by maxtaco** [comment]
Looks like your key expired about a month ago (on 2015-01-17).  If you're hosting with GPG you can update it via the web form.

**Comment by maxtaco** [comment]
(To see this, you can `curl https://keybase.io/camponez/key.asc | gpg --list-packets`)

**Comment by camponez** [comment]
@maxtaco Actually I have changed the expired date of my key. Is there a way to update that information in keybase?

**Comment by maxtaco** [comment]
Yes, you can upload via the settings page.  Click the gear -> update my key

**Comment by camponez** [comment]
@maxtaco sorry for the newbies questions. But when I try "update my key" (gpg --export --armor -r.... )   and paste the output there. I get: "cannot have 2 primary keys"

Why 2 primary keys? I'm updating my public key

I host my key on GPG

**Comment by maxtaco** [comment]
Try `gpg --export --armor D9BE388D55278C05` ?

**Comment by camponez** [comment]
@maxtaco This worked! Thank you! :)

**Comment by maxtaco** [comment]
Sure thing.  If you run just `gpg --export` it will export your whole keyring.  You probably have several keys in there by now.  So my fix was to just export the one key that matters.  Glad this fixed your bug.

**Comment by camponez** [comment]
After your comment I noticed that, and learn this at the same time! cheers

**Comment by TonyHoyle** [comment]
This is still a fault.  Why was this closed?

**Comment by cjb** [comment]
@tonyhoyle The original problem here was that Keybase only had a copy of the expired key, not the key that had been edited to not expire.

**Comment by TonyHoyle** [comment]
Not true.  I reported the original problem (see post #1) and the key was nonexpiring from the start.

**Comment by rodrigograca31** [comment]
still having this bug: `Error: no valid primary key self-signature or key(s) have expired`

cat key | gpg --list-packets | grep expires
```
	version 4, algo 1, created 1442346154, expires 0
	version 4, algo 1, created 1442346154, expires 0
	hashed subpkt 9 len 4 (key expires after 8y0d0h0m)
	version 4, algo 1, created 1442346154, expires 0
	hashed subpkt 9 len 4 (key expires after 8y0d0h0m)

```

**Comment by maxtaco** [comment]
@rodrigograca31 please provide more details about reproducing the issue if you want someone to take a look. thanks

**Comment by kiamlaluno** [comment]
I am getting the following error when importing in keybase the GPG key I generated.

> ERROR key generation error: no valid primary key self-signature or key(s) have expired (Signature failure in packet 1: rejecting insecure hash SHA1 (9cd6028c49c0ebfe95858807cef2ff1f7d40e308)) (error 905)

I generated the key with `gpg --full-gen-key` selecting _DSA and Elgamal_, 1024 as keysize, and 4 years as validity of the key. 
When I use `keybase pgp import` I get that error message.

**Comment by shawnshifflett** [comment]
> I am getting the following error when importing in keybase the GPG key I generated.
> 
> > ERROR key generation error: no valid primary key self-signature or key(s) have expired (Signature failure in packet 1: rejecting insecure hash SHA1 (9cd6028c49c0ebfe95858807cef2ff1f7d40e308)) (error 905)
> 
> I generated the key with `gpg --full-gen-key` selecting _DSA and Elgamal_, 1024 as keysize, and 4 years as validity of the key.
> When I use `keybase pgp select` I get that error message.

I am getting this same error message following the same steps.

**Comment by yujiri8** [comment]
I'm also getting this error with key [8D8E70D0BBD08947](https://pgp.mit.edu/pks/lookup?op=get&search=0x8D8E70D0BBD08947).

**Comment by perrin4869** [comment]
Getting this error on `keybase 5.5.1` and `5.4.2`. My keys are still valid and self signed.

```bash
$ gpg2 --list-key --keyid-format long julian@dotcore.co.il
pub   rsa4096/FA44A7452FEDC17B 2020-05-21 [SC]
      906D175B6DA39409E49507CFFA44A7452FEDC17B
uid                 [ultimate] Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sub   rsa4096/75A99057A2B7F3DB 2020-05-21 [E] [expires: 2021-05-21]
sub   rsa4096/F62351FE33674180 2020-05-31 [E] [expires: 2021-05-31]
sub   rsa4096/DF8A9145C75A2605 2020-06-01 [A] [expires: 2021-06-01]
sub   rsa4096/11D4D7E68EAB77E1 2020-06-01 [S] [expires: 2021-06-01]
$ gpg2 --list-sigs julian@dotcore.co.il
pub   rsa4096 2020-05-21 [SC]
      906D175B6DA39409E49507CFFA44A7452FEDC17B
uid           [ultimate] Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sig 3        FA44A7452FEDC17B 2020-05-31  Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sub   rsa4096 2020-05-21 [E] [expires: 2021-05-21]
sig          FA44A7452FEDC17B 2020-05-21  Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sub   rsa4096 2020-05-31 [E] [expires: 2021-05-31]
sig          FA44A7452FEDC17B 2020-05-31  Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sub   rsa4096 2020-06-01 [A] [expires: 2021-06-01]
sig          FA44A7452FEDC17B 2020-06-01  Julian Grinblat (Vae victis) <julian@dotcore.co.il>
sub   rsa4096 2020-06-01 [S] [expires: 2021-06-01]
sig          FA44A7452FEDC17B 2020-06-01  Julian Grinblat (Vae victis) <julian@dotcore.co.il>
```

**Comment by kiamlaluno** [comment]
I had to use `keybase pgp gen` to have a PGP key that was usable from Keybase.

**Comment by yujiri8** [comment]
I was able to upload a different key, which also has a valid self-signature and no expirartion date (it's a protonmail key), and I'm not sure what the difference is between it and my main one I'm trying to use. The only one I can spot is that the protonmail key (which worked) has only a subkey for encryption and the main for signing and certification, while my main one has the primary key for signing and certification, a subkey for encryption, but also a subkey for signing.

**Comment by perrin4869** [comment]
I actually failed to upload my key when it only had a single subkey, which is the same setup @yujiri8 used to upload (successfully) to keybase... Would be great to have this reopened and investigated. I can post my key in a keyserver if it helps

**Comment by benhabrams** [comment]
> I am getting the following error when importing in keybase the GPG key I generated.
> 
> > ERROR key generation error: no valid primary key self-signature or key(s) have expired (Signature failure in packet 1: rejecting insecure hash SHA1 (9cd6028c49c0ebfe95858807cef2ff1f7d40e308)) (error 905)
> 
> I generated the key with `gpg --full-gen-key` selecting _DSA and Elgamal_, 1024 as keysize, and 4 years as validity of the key.
> When I use `keybase pgp select` I get that error message.

Getting the exact same error. My key has not been revoked. Everything is up to date.

**Comment by maltfield** [comment]
I also encounter this error when attempting to update my public key in Debian 10 using the keybase app

```
user@disp1931:~$ gpg --list-sigs E0AFFF57DC00FBE0563587614AE21E1936CE786A
pub   rsa4096 2020-07-07 [SC] [expires: 2025-07-06]
      E0AFFF57DC00FBE0563587614AE21E1936CE786A
uid           [ unknown] BusKill Releases Signing Key 2020.07 <releases@buskill.in>
sig 3        4AE21E1936CE786A 2020-07-07  BusKill Releases Signing Key 2020.07 <releases@buskill.in>
sig          7881A036F21C15F8 2020-07-07  BusKill Releases Signing Key 2020.02 <releases@buskill.in>
sig          FE1B84494E640D41 2020-07-07  [User ID not found]
sub   rsa4096 2020-07-07 [E] [expires: 2025-07-06]
sig          4AE21E1936CE786A 2020-07-07  BusKill Releases Signing Key 2020.07 <releases@buskill.in>
sub   rsa4096 2020-07-07 [S] [expires: 2025-07-06]
sig          4AE21E1936CE786A 2020-07-07  BusKill Releases Signing Key 2020.07 <releases@buskill.in>
user@disp1931:~$ 

user@disp1931:~$ keybase pgp select --multi
You are selecting a PGP key from your local GnuPG keychain, and
will publish a statement signed with this key to make it part of
your Keybase.io identity.

Note that GnuPG will prompt you to perform this signature.

You can also import the secret key to *local*, *encrypted* Keybase
keyring, enabling decryption and signing with the Keybase client.
To do that, use "--import" flag.

Learn more: keybase pgp help select

#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    3072R   2CBE53D941B3AB16             BusKill Security Team <security@buskill.in>, BusKill Team <info@buskill.in>
2    4096R   4AE21E1936CE786A             BusKill Releases Signing Key 2020.07 <releases@buskill.in>
3    4096R   BE75DB07E34AFBC1             BusKill Pre-Releases Signing Key 2020.07 <pre-releases@buskill.in>
4    3072R   7881A036F21C15F8             BusKill Releases Signing Key 2020.02 <releases@buskill.in>
Choose a key: 2
▶ ERROR key generation error: no valid primary key self-signature or key(s) have expired (Signature failure in packet 1: rejecting insecure hash SHA1 (4ae21e1936ce786a)) (error 905)
user@disp1931:~$ 
```

@maxtaco Can you please re-open this outstanding issue?

**Comment by SlySven** [comment]
I too am getting these sort of problems, I have two personal keys on my keyring which are mutually signed:
* a 2048 bit RSA primary `EBD68ADBCAB4E556` (Signing, Certification, Authorisation) with a 2048 bit RSA sub-key (Encryption) which is around eight years old and which is stored as a file on the hard-drive
* a recently generated 4096 bit RSA primary `7C23BD6009A577EE` (Certification) with three 3072 bit RSA sub-keys (Signing; Encryption; Authorisation) - the primary is *securely stored **off-line*** and the sub-keys are stored on an OpenGPG smartcard - as such they are only accessible via that card and they cannot be read from it:
```sh
c:\Program Files>gpg -K
C:/Users/stephen/AppData/Roaming/gnupg/pubring.kbx
--------------------------------------------------
sec   rsa2048 2012-04-02 [SCA]
      060B18C73148CC1E2362A991EBD68ADBCAB4E556
uid           [ultimate] Stephen Lyons <slysven@virginmedia.com>
uid           [ultimate] [jpeg image of size 23645]
ssb   rsa2048 2012-04-02 [E] [expires: 2021-08-24]

sec#  rsa4096 2020-09-28 [C]
      AF4F799268DF118D9F2867697C23BD6009A577EE
uid           [ultimate] Stephen Lyons <slysven@virginmedia.com>
ssb>  rsa3072 2020-09-28 [S] [expires: 2021-03-27]
ssb>  rsa3072 2020-09-28 [E] [expires: 2021-03-27]
ssb>  rsa3072 2020-09-28 [A] [expires: 2021-03-27]

c:\Program Files>
```

I too am unable to get keybase to accept either keypair - being aware of the inaccessibility of the newer smart-card secret keys I most recently tried to select the older hard-disk stored one:
```sh
c:\Program Files>keybase pgp select --import
You are selecting a PGP key to publish in your profile, and
importing secret key to *local*, *encrypted* Keybase keyring.

If your GnuPG key is encrypted, you will be asked for passphrase
to unlock it. You may be asked *twice* - first by GnuPG, to export
encrypted key bundle, and then by Keybase, to unlock the secret key.

Please note that this will not work if your secret key lives on a
hardware device (like a smart card or a Yubikey).

#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   7C23BD6009A577EE             Stephen Lyons <slysven@virginmedia.com>
2    2048R   EBD68ADBCAB4E556             Stephen Lyons <slysven@virginmedia.com>
Choose a key: 2
- ERROR key generation error: no valid primary key self-signature or key(s) have expired (Signature failure in packet 1: rejecting insecure hash SHA1 (ebd68adbcab4e556)) (error 905)

c:\Program Files>
```
Now my understanding is that the use of the SHA1 hash is the problem - however as I understand it SHA1 is the required hashing algorithm for some (signing?) operations https://security.stackexchange.com/q/68105/236562 and that it is possible to modify `(open)gpg`'s behaviour with some `personal-xxxx-preferences` settings (where `xxxx` is one of `cipher`, `digest` and `compress`) in one's `gpg.conf` file. However it seems to me that those only set some defaults and do not modify the preferences for existing keys. There are also explicit `xxxx-algo` options that force a particular value. However I have not been able to do anything with these that prevent the use of the SHA1 - at least as far as causing that error message to change - even by ensuring I kill the `gpg-agent` between attempts...

Maybe it is the fact that this is Windows and I am using the latest GPG4Win - or perhaps the keybase client is not behaving properly but there seems something fundamentally wrong here and a more detailed explanation of the problem - and of the potential solutions for those of us with existing key-pairs is needed.
