### ISSUE TITLE
Menu on the website is hard to read

### ISSUE THREAD

**Issue by kgraefe** [keybase/keybase-issues#1271]
Using Opera 26 the text in the mouse-over bubble in the menu on the top-right of the website is dark-grey on black on dark-grey:

![keybase_menu_issue](https://cloud.githubusercontent.com/assets/3797324/5487292/6be61f44-86b0-11e4-9b3d-cc36fda7e6ca.png)

The text "invites" is hard to read, too.

**Comment by mralext20** [comment]
this issue has been around for almost a year, any fix in the works?

**Comment by kgraefe** [comment]
Seems to be fixed with the new(?) brighter design.
