### ISSUE TITLE
Should emails contain auto-login links?

### ISSUE THREAD

**Issue by grant-olson** [keybase/keybase-issues#1281]
1. I run my broswer in incognito mode.

2. I got an email saying my web proof failed because I had some dns problems.

3. I followed the link to re-prove, and opened my password manager expecting to have to login.

I was already logged in and could submit all kinds of proofs to an existing account, use invites etc. In addition, this wasn't a one-time login that expired after I use it.

I'm not sure what the security implications are, if any, but I expected I would have to use my password to sign in to the site.

**Comment by erAck** [comment]
This is the biggest bullshit I have encountered so far in keybase. Also the proof succeded mails contain such auto-login link. So anyone who has access to the email, be it during transport or in the inbox, can login and alter the profile and if I was insane enough to host a private key at keybase (bad idea anyway) could sign and decrypt on my behalf. STOP THAT NONSENSE! Do not send auto-login links or other credentials in mails!

**Comment by AdrianLamo** [comment]
This should be done away with ASAP. It makes me hesitant to endorse keybase to new users, and I've been a relatively enthusiastic evangelist of it up to this point (and hope to continue to be once this 'feature' is dead and buried). 

If anything, emails should contain a "We have results for your verification attempt, login to see what they are" style content rather than making compromise semi-trivial for any well-situated intruder.

**Comment by malgorithms** [comment]
Hi all - the TLDR is that these are now off.

For the background, if you're curious: this was always a point of internal discussion. The security argument for allowing them was that an autologin keybase session was soft:  you couldn't prove anything, revoke anything, even track anyone.  You could see account information about yourself (email address for example) and take clobbering actions (nuke your account and start a fresh one) but never sign a statement.

More succinct: your keybase identity really is a "sig chain", which is the series of public signed statements, each referencing the last. If you click an autologin link, you can't modify an existing sig chain in any way without logging in for real.

Anyway, you could do *some* damage, as discussed above. And it certainly rubs you guys the wrong way, so just letting you know we're listening...autologins are off now.
