### ISSUE TITLE
Error: cannot encrypt with the given KeyManager (i=0)

### ISSUE THREAD

**Issue by NfNitLoop** [keybase/keybase-issues#1282]
To reproduce, visit https://keybase.io/encrypt#nfnitloop and try clicking the "encrypt" button.

Expected: 
* An encrypted message!
* Or, failing that, a bit more useful error message.  (Does it not like something about my public key?)

**Comment by kived** [comment]
I have the same issue trying to encrypt a message to my friend. I thought Keybase sounded pretty cool when my friend offered an invite, but it doesn't look like this is really that useful since it doesn't work, and this issue has received absolutely no attention after almost a year.

**Comment by maxtaco** [comment]
Which user produces the problem? A screenshot would help.  Thanks.

**Comment by kived** [comment]
![screenshot from 2015-09-25 12 55 31](https://cloud.githubusercontent.com/assets/1126441/10108155/fc90ea86-6384-11e5-8095-cb546840a2bb.png)

This happens on both the normal and staging servers.

**Comment by maxtaco** [comment]
Thanks, reproduced.  Likely it's due to a key expiration problem, but we'll take a look. Thanks!

**Comment by ofus** [comment]
Ofus here. I believe my key is set to expire in 2018 https://keybase.io/ofus/key.asc

**Comment by maxtaco** [comment]
thanks @ofus; I'll take a look.

**Comment by maxtaco** [comment]
Your main key expires in December, and your encryption subkey expired earlier this year:

```
pub  4096R/862A09D1  created: 2014-01-22  expires: 2015-12-17  usage: SC  
                     trust: unknown       validity: unknown
sub  4096R/C3466535  created: 2014-01-22  expired: 2015-01-22  usage: E   
[ unknown] (1). Andrew L. Joseph <andrew@aljweb.com>
```

**Comment by NfNitLoop** [comment]
> Which user produces the problem? A screenshot would help.  Thanks.

Uh....

> To reproduce, visit https://keybase.io/encrypt#nfnitloop and try clicking the "encrypt" button.

<img width="552" alt="screen shot 2015-09-26 at 2 50 19 pm" src="https://cloud.githubusercontent.com/assets/339075/10118083/05dcfcc2-645e-11e5-978b-d3aee06331c2.png">

**Comment by maxtaco** [comment]
Sorry @NfNitLoop, the request for username/screenshot was for @kived.

**Comment by maxtaco** [comment]
Ok, nfnitloop's key looks fine, it's a bug on our side. Thanks for the report.

**Comment by maxtaco** [comment]
@NfNitLoop you might want to follow progress in keybase/kbpgp#102

**Comment by maxtaco** [comment]
@NfNitLoop can you decrypt this message?

```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.46
Comment: https://keybase.io/crypto

wcFOA+PuNjec3l9dEAf+K8mVOsa54sRC6IBygrB8bwuO3U+xYSBAmJDrCP9jyb2Z
cWFkKxWJCYq/WQTNUYqLTyObZGd0rzOZTZcJ9/mq6MTBNLJb2dFw0tIhosL737Ra
G8ub0BmUx3lm4uNPrjqoegbCHATC0f0vb2cVWZe5pV/3OdPeXuw+uMjeVPiElSel
RuLB3mN4xam6KrE/P4n36501YoCLysDYXrsBsyT2Z5qr392mRRl8btHR7oPkvDyB
2KENY4LdSnXzLIVta2hR0eyqbysfb+LwbLaKp0yQSEaL147wJjCG65Y7SDAexRtA
IZgOsnxAd8w49w1Vq7QDgRn9xWAscvxz88XOsGYusQf/XWRdERXKgi1gKpbQ3viJ
gQvsIjK6t0WdnHUgDFMUeTLT97OjaNpAN6ZtjKYlKJxlf+0Aq4RQ52TBP9Wtu6U6
mTWHMJ3/+oZ/yChSBs/5wsPOFd+CogsJSLy1Qc5GRA2t6/p/Y5XNv4ykpevMEfuk
k+A4eWumOeodMv/nFK6MZCFLLG1spZRYZdl8YnMS5jT052OEMdEOSvelKPrbDdja
AF69syQJIHw8oUx+TjN2xbXzJIa7GikGkEkt+MbHKkRuojCPTlbOO6j7pLTEYnXP
KoEpr2Smr4lmVEOKU5FrmaUHIin4ftFXGqQBl9XhDL5jclBN/G+WdgthwdisdIfH
qdJrASS2Io2igOFQ8xU+en19XHsuT1H/4RzwPHht7uEimJXDq5WnJf3O8pmwHdgZ
Y/981jBddZD0fpTYGkNHmcHpfAtTRihV04rLLRk3lDseKv8S7nKo/4rwE6Rap49H
0m3vJNYK7cq04QynnJk=
=mgF7
-----END PGP MESSAGE-----
```

**Comment by maxtaco** [comment]
Well, I think it's fixed in our branch.  We have a PR open at keybase/kbpgp#103.  It's in line behind another PR though.

**Comment by NfNitLoop** [comment]
Yep, I'm able to decrypt it.   And https://keybase.io/encrypt#nfnitloop works for me now.  I guess we can close this issue.

Thanks, @maxtaco!

**Comment by jb55** [comment]
I ran into this today, perhaps we can get a better error message? Such as: "Could not encrypt, key has expired".
