### ISSUE TITLE
Copying an encrypted message doesn't work on iOS (iPhone)

### ISSUE THREAD

**Issue by johnnydecimal** [keybase/keybase-issues#1285]
When I "encrypt a message" to myself from my home page, the encrypted text isn't selectable on iOS 8.1.2 on an iPhone 6.

Long-holding to select doesn't bring up the iOS Cut/Copy dialog.

I tried a bunch of different tap/hold combinations and couldn't successfully get hold of the text. It's therefore impossible to extract to, say, email.

**Comment by davidglidden** [comment]
+1 on this one—iPhone 6+, iOS 8.1.3

**Comment by Spencevail** [comment]
Same experience here as @jen729w. Tried a bunch of different ways to get it to work.

**Comment by Parthas-Menethil** [comment]
I got the exact same experience on my iPhone6+ running iOS 8.3
