### ISSUE TITLE
Docs: First example for the lookup call is bad

### ISSUE THREAD

**Issue by msfeldstein** [keybase/keybase-issues#1287]
On the page: https://keybase.io/docs/api/1.0/call/user/lookup
The first example is 
`https://keybase.io/_/api/1.0/user/lookup.json?usernames=chris,maxtaco`

maxtaco doesn't exist it should be

`https://keybase.io/_/api/1.0/user/lookup.json?usernames=chris,max`

**Comment by malgorithms** [comment]
thanks, this is fixed.
