### ISSUE TITLE
Repeatedly failing Reddit proof

### ISSUE THREAD

**Issue by laserlemon** [keybase/keybase-issues#1293]
As instructed in the Keybase email notification of my proof failure, I'm opening this issue with the link to my proof: https://www.reddit.com/r/KeybaseProofs/comments/2r0j3p/my_keybase_proof_redditlaserlemon/

Thank you!

**Comment by maxtaco** [comment]
Should work now, you were shadow-banned or some such, but I approved your post via moderator tools.  I don't totally understand Reddit, but you probably did something to run afoul of their anti-spam/abuse system.

**Comment by laserlemon** [comment]
Thank you but I'm not seeing that it's verified on my profile. Is that expected?

**Comment by maxtaco** [comment]
Works now, I poked our proof checker, looks good.
