### ISSUE TITLE
Reddit and Twitter icons disappeared

### ISSUE THREAD

**Issue by Fale** [keybase/keybase-issues#1295]
Hi,

Loading the profiles, the twitter and reddit icons do not show any more

**Comment by dtiersch** [comment]
I can not confirm this, for me everything shows up as it should.

Try clearing your Cache and reload the page (`Strg` + `F5`). If this doesn't help another issue could be if you use a too restricitve AdBlock filter list. You can see in the sidebar for blockable elements which elements on the opened site are currently blocked and not displayed.
For example, "Fanboy's Social Blocking List" has an entry `.fa-twitter` which results on keybase.io in the Twitter icon not being displayed.

**Comment by Fale** [comment]
Thanks for the help.

I had adblock blocking those two icons... weird stuff adblock sometimes
does.

Thanks a lot again :)

Il giorno Sat Jan 03 2015 at 17:25:24 David Tiersch <
notifications@github.com> ha scritto:
