### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by bortzmeyer** [keybase/keybase-issues#1297]
When following the link in emails "@XXX on twitter (your friend) just signed their account", I get "Error 500. Something is not right. We will look into it."

**Comment by malgorithms** [comment]
ok, we'll have a fix for this soon. out of curiosity, how old is the email?

**Comment by bortzmeyer** [comment]
On Sat, Jan 03, 2015 at 04:51:20PM -0800,
 Chris Coyne <notifications@github.com> wrote 
 a message of 27 lines which said:

> ok, we'll have a fix for this soon. out of curiosity, how old is the email?

31 december

**Comment by malgorithms** [comment]
fixed, thanks.
