### ISSUE TITLE
'tracking'

### ISSUE THREAD

**Issue by straytaoist** [keybase/keybase-issues#1302]
Well, not a big issue, more a...perception thing.

Given the whole Snowden/NSA business (which hopefully will make people at least think about encryption), the word 'tracking' (in relation to others) is a bit....overloaded.

Probably too late to change it, but thought I'd mention it, is all. Do I want to feel 'tracked'? I don't want to feel 'followed', either. Naming is hard. It doesn't have to be a single word, I guess...I dunno.

/me wanders off, having wasted enough bits on this, yours and mine.

**Comment by malgorithms** [comment]
This is discussed pretty heavily in #100, so I'll close this as a duplicate. Thanks!
