### ISSUE TITLE
[Feature Request] Link with Gravatar

### ISSUE THREAD

**Issue by maplebed** [keybase/keybase-issues#1306]
Gravatar provides a nice way to manage all the profile pics used by sites around the internet. It'd be nice to use them to provide profile pics for Keybase. I can understand if that might be difficult if there's no way to validate a gravatar account. Maybe with an email address, since Keybase already has email verification?

**Comment by maplebed** [comment]
(note - not a duplicate of #518 because this request is for using gravatar's service to provite your avatar rather than proving your account on their service. The latter may be a prerequisite though...)

**Comment by mirimir** [comment]
I second this request. I don't use Twitter, and would (in any case) never share a cellphone number with it. So GitHub was the only route to an avatar. Gravatar's been around for a while, and arguably appeals to a broader audience.

**Comment by malgorithms** [comment]
This is discussed in #107 . thanks!
