### ISSUE TITLE
Reissue invitation once "cancelled & reclaimed"

### ISSUE THREAD

**Issue by dclobato** [keybase/keybase-issues#1316]
Sometime ago I invited a friend to use Keybase. Set him an invitation from the system.

One month after sending the invitation, I cancelled and reclaimed the invitation as he did not answered to it.

Today, he asked me for an invitation. When I tried to send the invitation, Keybase told me I "already invited him, once upon a time".

Can't I invite someone again? Why?

Cheers

![screen shot 2015-01-08 at 16 16 04](https://cloud.githubusercontent.com/assets/4229987/5667892/77d6fd34-9752-11e4-9b45-7eb032c43c9e.png)

**Comment by malgorithms** [comment]
This is to prevent people from being spammed. Our conservative stance is a non-user should never get emailed by Keybase more than once...if they ignore an invitation it shouldn't be possible to generate them another. 

I know this is annoying when you have legit interest, but keep in mind he/she can sign up under that email address if you give them an invite code or send it to a different address. It's just a question of generating the invitation emails. You could even send it to jwfiojifwejifewjifwjifeow@wfejifweijfewo.com , take the invitation code (it'll show it to you) and email them yourself.

**Comment by dclobato** [comment]
Ok, thanks for the clarification.  As he has a gmail address, I just added some dots on the email and, voila! ;)

**Comment by malgorithms** [comment]
I do that all the time :-) Often something like theirname+attempt2@gmail.com
