### ISSUE TITLE
[Feature Request] Allow more than one public key

### ISSUE THREAD

**Issue by LordVan** [keybase/keybase-issues#1318]
I have more than one GPG key, since I use a different one for my @gentoo.org address and would like to also add that public key to my profile somehow - the key is signed by my primary key, so "trust" shouldn't be an issue.

Since i can see it becoming difficult/confusing if I use both to track/sign with more than one key I guess it would be ok if - at first at least - a 2nd key could be added (maybe even only if it is signed by the main one ?) so that it is visible to others - preferrably would probably be to also sign/verify with it of course but that might be more complex to implement.

**Comment by dtiersch** [comment]
examples out of the open issues: #1201 #178 #381

**Comment by LordVan** [comment]
Point taken. I should've spent more time searching. closing this myself.
