### ISSUE TITLE
[Question] Changing my username?

### ISSUE THREAD

**Issue by ewiner** [keybase/keybase-issues#1321]
I just got my invite to Keybase (thanks!) and got set up, but I just realized I had picked a different username than the one I'm already using on your mortal enemy's site, onename.io.  For consistency, I'd like to switch usernames on Keybase to match onename.io.

What's the best way to do so?  Is there something you guys can do?  Should I delete my account and reinvite myself?

Thanks!

**Comment by malgorithms** [comment]
delete your account. then yeah, use this, quick, before someone else does :-)

96b947207c199a7342f1a30d

**Comment by ewiner** [comment]
Got it, thanks!
