### ISSUE TITLE
unable to enter passphrase in command line v 0.7.3

### ISSUE THREAD

**Issue by tonydewan** [keybase/keybase-issues#1323]
I just tried to use the keybase command line tool for the first time in months, and it told me to upgrade, which I did. I am now unable to enter my passphrase. Given that it's stored in password manager, I first attempted to copy/paste it. When that didn't work, I typed it manually. Either way, it just hangs and never completes.

**Comment by maxtaco** [comment]
Was this issue fixed for you in v0.7.5? Thanks

**Comment by tonydewan** [comment]
updating to 0.7.5 fixes the issue. Thanks!
