### ISSUE TITLE
Convention in Valencia, Spain: March 2015

### ISSUE THREAD

**Issue by rjhansen** [keybase/keybase-issues#1327]
There's a privacy technologies conference in Valencia, Spain running from March 1-6, 2015.  OpenPGP is a major technology of interest to the organizers, and I'm going to be attending to represent Enigmail.  The attendees will include human-rights organizations, journalists, and people representing dissidents in hostile regimes.  They might be able to benefit from keybase.  As such, you may want to consider sending a representative to Circumvention, or talking with the conference organizers and arranging to distribute some keybase invites at Circumvention.  (I'd of course be happy to help as well, but if you want to be officially affiliated with the con you should probably talk to the con.)

The Circumvention website: https://openitp.org/festival/circumvention-tech-festival.html

**Comment by malgorithms** [comment]
hi @rjhansen  - that conference seems great!

@maxtaco and I aren't really traveling right now (we both have too many little family obligations)...but if someone reaches out to me I can make sure there are adequate invitations for people there. Let me know via email.
