### ISSUE TITLE
Exposure of email addresses to spammers

### ISSUE THREAD

**Issue by briantopping** [keybase/keybase-issues#1331]
In https://github.com/keybase/keybase-issues/issues/1299#issuecomment-70459504, I believe I present solid requirements regarding email addresses in certificates. As writable endpoints for the user that the certificate represents, they belong in the key, and even though they are in the key, an attacker cannot decrypt messages sent to a compromised endpoint without the private key. Further, MUAs will often not encrypt a message to a recipient unless a cert exists locally that contains the email address of the recipient as an attribute. 

It seems unavoidable that a key must have all email addresses for a user if the user wishes to enjoy the pervasive encryption that a site like this would hope to engender on a global scale.

**Thus, if keys are public and keys contain all email addresses a user wishes to be contacted on with a given private key, current email addresses are public and can be harvested.** I believe this warrants close attention before the workflows of the site are too deeply codified. The negative publicity after the site gains traction could be fatal and a lot of good work lost with it.

**Comment by dtiersch** [comment]
This is nothing new and implied by the design of PGP. Other Keyservers face the same problem.

As written [here](http://ubuntuforums.org/showthread.php?t=2165275) the costs to load the keys and extract the addresses is relative high compared to other sources (etc. googling Impressums). Addressing this the API is rate limited: If a search returns too much results you don't get an answer. (Try entering `@gmail.com` [here](https://sks-keyservers.net/i/))

**Comment by briantopping** [comment]
I think what's new is Keybase has a chance of reaching mass adoption. Not a problem PGP ever had... :)
