### ISSUE TITLE
Reddit proofs use unnecessary markup

### ISSUE THREAD

**Issue by teh-maxh** [keybase/keybase-issues#1332]
Currently, reddit proof messages state that they are being posted to /r/KeybaseProofs using a Markdown link (`[KeybaseProofs](https://www.reddit.com/r/KeybaseProofs)`). However, reddit allows for automatic linking to a subreddit by giving its name with the /r/ prefix. I would suggest that it would be better to allow the automatic link instead of manually creating a link.

This change should not (and, I've confirmed, does not) affect proof verification.

**Comment by malgorithms** [comment]
this would be an easy change. Are you saying we'd change this:

```
[KeybaseProofs](https://www.reddit.com/r/KeybaseProofs)
```

to this simple thing:

```
/r/KeybaseProofs
```
?
thanks!

**Comment by teh-maxh** [comment]
Yes, exactly. I hadn't noticed that the reddit username is also linked; it has a similar shortcut (`/u/username` instead of `[username](https://www.reddit.com/user/username)`). In both cases, using the shortcut not only allows for cleaner markdown, but will automatically maintain the reddit subdomain. (For example, if I'm on cs.reddit.com, the shortcut link will stay there, whereas the manual link will put me back on English reddit.) I've manually made the edits on [my proof](https://www.reddit.com/r/KeybaseProofs/comments/2swswl/) as an example, and checked that `keybase id` still confirms the proof.

**Comment by malgorithms** [comment]
ok this change is live, thanks
