### ISSUE TITLE
ECC key error

### ISSUE THREAD

**Issue by jonnybarnes** [keybase/keybase-issues#1333]
I can't upload this public key. I get this error `Whoa: Error: Unknown curve OID: 2b240303020801010b`

Public key:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mHMEVLAKNRMJKyQDAwIIAQELAwMEXwZt3GCBMfYdy4E6SYBlhI5OWB5KLWDJIszb
rHVk1lFzuCh8v9vO3TMJipved89lKdsqc8xa1rtUhDUSyk3DN6G9EA8CaZzPAI0W
3rIIjKr/6XdsrCbr4uBm8pfxojlrtCNKb25ueSBCYXJuZXMgPGpvbm55QGpvbm55
YmFybmVzLnVrPoifBBMTCgAnBQJUsAo1AhsDBQkB4TOABQsJCAcDBRUKCQgLBRYD
AgEAAh4BAheAAAoJEE6N3A7eXSOm2MoBf1muzbbm7gw1Iu+pb+uJlAW0zjo9OvF1
l+CkTno/2OSUUbgNL3PPu0rOT60VAP9G7gF+LfWqLatBQklcM7VmHeQuvyRS5IkB
okuBeOPiYe1sln7088I/yOEbDB5XpfACfZ0FuHcEVLAKNRIJKyQDAwIIAQELAwME
MyNUNRiVoPuUZHkZmoR2fP0j2d6ukPxSyIwE1i0SOokPgh2ho9az2i1JuEJnAJdC
Jk7anTWqVIVDqY24BPdCAq3Tevvw6ZxYTX5syhQ06rP5fmA9qRvaJMj96bUk2I7U
AwEJCYiHBBgTCgAPBQJUsAo1AhsMBQkB4TOAAAoJEE6N3A7eXSOm/A4Bf1ZnVww+
jcE7oYhoUHJfU1MoyDSagcMDRlo1wRPtGgPgkbOWUfx1dCQ79YSJgJ05TAF9Fwky
HdZ7NJu0PhNQvvsk4Ga7cfya6Ik3MQzU+afbxzBQpVn4QbRTTUQlzIVpnKjOuDME
VLBHDxYJKwYBBAHaRw8BAQdAN3zPDRahp3XZ2Q6SJcE4s36GziDIEOLq+jYZVTjG
mQ6I5wQYEwoADwUCVLBHDwIbAgUJAeEzgABqCRBOjdwO3l0jpl8gBBkWCgAGBQJU
sEcPAAoJEM3oRBjzbH97ftsBAOGQ9hacPaGbg1SylH2Nv+1rxvTBUyZoTu4+jdgv
K3WIAQCJteXs5ANg1AsQyprn7GK5Ke958gf+Y6tPvqnRVyNqDPH/AXwIzP4ptJWR
b4aIyHcQevcMiKmsSwmdStjKBAJQ0GBRtGLaSEpamEfW8fRpl4B/Q7QBewXnQfpd
S2kuT3OryIwasva4+vrcYW9aS/naDhn1S04NEOha+oZyg4JNJTFL44BQ7A==
=0oPs
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by maxtaco** [comment]
yeah, we don't support brainpool curves yet.  I would guess most clients
don't either.

**Comment by jonnybarnes** [comment]
Any idea when you might?

**Comment by maxtaco** [comment]
It's not a top priority for us right now, but if someone wants to add it,
the code is all open source in kbpgp, and we'll accept PRs if they have
good test cases.

**Comment by jkolo** [comment]
I created PR (https://github.com/keybase/kbpgp/pull/84) for brainpool keys

**Comment by maxtaco** [comment]
Thanks @jkolo.  Will merge once there are tests!

**Comment by alkar** [comment]
Thanks @jkolo !

**Comment by jkolo** [comment]
@maxtaco Any info when could we expect this feature on keybase.io?

**Comment by maxtaco** [comment]
We'll have to cut a new release of the client too.  @oconnor663 any ideas?

**Comment by oconnor663** [comment]
Just pushed a new release. @jonnybarnes, can you confirm your key works now?

**Comment by alkar** [comment]
I tried inserting my Brainpool P-512 key on the website only to get a `Server failure: failed to insert into database`

The response looks like:
	{
	  "status": {
	    "code": 501,
	    "desc": "failed to insert into database",
	    "name": "DB_INSERT_ERROR"
	  },
	  "csrf_token": "xxxxxxxxxxxxxxxxxx"
	}

**Comment by Sidnicious** [comment]
Looks like I may have forgotten to push a schema change to the database. @alkar, could you try now?

**Comment by alkar** [comment]
@Sidnicious: it works, thanks!

**Comment by Sidnicious** [comment]
:sparkles: Awesome! :sparkles:

Let us know if you run into any more issues.

**Comment by alkar** [comment]
Awesome indeed! :octopus:

(I did run into a minor issue while trying to sign my key but I suspect it has to do with my environment - I will try to figure out what's wrong and may submit a separate issue. The brainpool key is parsed just fine!)

**Comment by Sidnicious** [comment]
Great. If it turns out to be on our end, don't hesitate to open a bug.

**Comment by alkar** [comment]
@jkolo thanks a lot for the PR!

**Comment by jonnybarnes** [comment]
A long time since trying again, but I still can’t upload my key, same key as in the first comment but now I get the error: `Error! The public key matching that id was not found. `

**Comment by Sidnicious** [comment]
@jonnybarnes I think we pushed out a fix for this today. Could you give it another try?

**Comment by jonnybarnes** [comment]
@Sidnicious huh? It kept telling me yesterday it had failed, went to look at my profile to upload a new key but there it is waiting for me. Still have to verify its my key though.

**Comment by Sidnicious** [comment]
@jonnybarnes This was a frontend bug, and I think we fixed it today. The key upload succeeded, but loading the next screen (which would've given you the option to verify it) failed. If you verify the key, everything should be in a good state.

**Comment by jonnybarnes** [comment]
It all seems to be working now :)

**Comment by Sidnicious** [comment]
Great! Let us know if you run into anything else.
