### ISSUE TITLE
Profile Picture put in Twitter (Facebook cross posted) is incorrect profile picture.

### ISSUE THREAD

**Issue by andyrj** [keybase/keybase-issues#1334]
I am not certain why this is happening, but my twitter proof wound up pulling in some random persons profile picture instead of my own.  I am attaching a screenshot of my facebook post that is from a twitter->facebook post integration.

![screenshot from 2015-01-19 13 37 46](https://cloud.githubusercontent.com/assets/5376837/5808302/d5b3f48e-9fe0-11e4-92b9-7df08374096f.png)

The shortened url link does however pull up my profile on keybase.io.  I don't know why this photo was posted to my proof.

If any other info would be useful in debugging this I will gladly provide it.

**Comment by zQueal** [comment]
Interesting error! As per the Facebook Open Graph documentation, the graph API will pull the information from the `og:image` property embedded in the requested page for the image. It would seem like there is either an error, miscommunication, or the open graph simply doesn't like something that keybase is using. I tried this on myself, too: [here](https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fkeybase.io%2Fzqueal) It does not use the curret image for my keybase account.

Good find!

**Comment by malgorithms** [comment]
User pages on Keybase have the og:image set correctly, but I think this problem happens if you end up linking to a page other than your profile page. Then facebook might scrape a random user pic (we show a random set of users to guests...)

can you tell me what the link is that ended up inside the facebook post? where is it going to on keybase, exactly?

**Comment by malgorithms** [comment]
@zQueal  I am confused why it grabbed the wrong one for your profile. Here's what we have in `<head>`

```
    <meta property="og:image"        content="https://s3.amazonaws.com/keybase_processed_uploads/1507bc553066f96c3a12b20d5e2d9505_200_200_square_200.png">
    <meta property="og:image:width"  content="200">
    <meta property="og:image:height" content="200">
```

That looks right, right? And this is something that hasn't changed in a while...

**Comment by malgorithms** [comment]
oh @zQueal  - yours is updated now. Facebook chose that image on June 10, 2014, likely from someone you track (I'm guessing), before we added og:image tags. I clicked "refresh" on the facebook page and it fixed it.

back to @andryj - I would love to know what the link is to, exactly, in your post. thanks all.

**Comment by zQueal** [comment]
Just checked, fixed for me too. I think its safe to assume that this was a cache issue on either my behalf of Facebooks.

A bit off topic, but the Facebook URL debugger actually returns two warnings: 

* The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
* The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.

Just an FYI.

**Comment by andyrj** [comment]
the link that is on Twitter is from the keybase proof: https://t.co/zqv6sGTUM7

which does appear to go to my keybase.io profile

https://keybase.io/andyrj/sigs/zt7LvxUnZp-TD4qE9gt8ulo7PDzz90_G-z1H

I did just expire my original key pair and after creating a new key pair and twitter posted on my behalf to facebook, when this profile image mismatch occurred.

**Comment by andyrj** [comment]
let me know if I can get any other info that might help explain this.  I apologize if my last was not the info you were asking for.  I will have access to a desktop in the morning where I can look closer at the html on Twitter and FB if needed.
