### ISSUE TITLE
Romanian diacritics are not working properly

### ISSUE THREAD

**Issue by AndreiTelteu** [keybase/keybase-issues#1337]
Hi.

Ș ș Ț ț Ă ă -> these characters are not supported by the font you are using.

Take a look at this screenshot: http://pbrd.co/1GvcOpG

Priority: Low

**Comment by waldyrious** [comment]
I'd point out the [Noto fonts](https://en.wikipedia.org/wiki/Noto_fonts) project, which I believe solves this problem in a really nice way.

**Comment by malgorithms** [comment]
I am giving Noto a try (on all but header and code regions). @AndreiTelteu care to take a look?

@waldyrious thanks for the suggestion.

**Comment by malgorithms** [comment]
also, hard to ignore the most 1337 of all issues.

**Comment by AndreiTelteu** [comment]
As long as users can insert text just on the bio and location fields, i think this font is only necessary there, right ?
And yes i can take a look.

**Comment by malgorithms** [comment]
yeah, that's really it, now. There will be some other places where user text get displayed (soon), but I'm keeping both fonts available so we can mix it up if we want. A designer would cringe...

**Comment by AndreiTelteu** [comment]
It works fine, i like the font, it's easy to read.
BTW, great job with the whole website/service/software (how can we call it) ! :)

**Comment by malgorithms** [comment]
thanks! closing...
