### ISSUE TITLE
Javascript error thrown to user when upload button clicked while textbox is empty.

### ISSUE THREAD

**Issue by cakoronkowski** [keybase/keybase-issues#1339]
I clicked the upload button in the upload key menu expecting to open a .asc file from my machine, but was unaware that this meant to PASTE the key. when you hit upload with the text box empty it throws a javascript error to the user "cannot call method split() of undefined" which usually means it didn't check if the box was empty before calling the method.

**Comment by malgorithms** [comment]
fixed thanks.
