### ISSUE TITLE
Twitter proof string longer than 140

### ISSUE THREAD

**Issue by Mosesofmason** [keybase/keybase-issues#1345]
Can not proof my twitter id since the generated proof string is longer than 140. Please check and fix. Thanks.

**Comment by maxtaco** [comment]
impossible.  Likely you've made a copy-paste mistake that brook the URL shortener.

**Comment by Mosesofmason** [comment]
Ok, I was using Silver Bird on Chrome, seems the URL shortener of Silver Bird has some problem with keybase.io, after try to post on the web directly, it works :-)
