### ISSUE TITLE
Weird behavior of the public keybase github proof

### ISSUE THREAD

**Issue by Scatchell** [keybase/keybase-issues#1348]
The keybase proof it asks me to publicly post as a gist has the following included in it:

"* I have a public key whose fingerprint is RETU RN T HIS. PGP. GET_  FING ERPR INT( );
     }"

and later...

"with the PGP key whose fingerprint is
[RETU RN T HIS. PGP. GET_  FING ERPR INT( );
     }](https://keybase.io/scatchell)
(captured above as `body.key.fingerprint`), yielding the PGP signature:"

I'm relatively new to this stuff but, this seems like it may not be the expected behavior.

**Comment by bxm156** [comment]
I'm seeing this in the web based authentication too.

http://www.bryanmarty.com/keybase.txt

**Comment by maxtaco** [comment]
Thanks for the bug report.  The fix should be live!

The bug didn't affect the validity of the proof, it just looked kind of ugly.
