### ISSUE TITLE
How do I add someone's pubkey to my gnupg chain?

### ISSUE THREAD

**Issue by thams** [keybase/keybase-issues#1352]
Presuming I'm using gpg for other purposes and want to encrypt something to someone, is there a way to get a keybase user's key into my chain?

**Comment by malgorithms** [comment]
tracking them pulls in their key and puts it in your local GPG.

```
> keybase track someuser
```

you can also just do this:

```
> curl https://keybase.io/someuser/key.asc | gpg --import
```

the advantage of the former is that it will verify their identity (actually scrape the tweets, etc., and check the signatures on them, never trusting Keybase.). The advantage of the latter is you don't have to install keybase at all. But you are trusting the server's claim that the identities are verified.
