### ISSUE TITLE
Cannot remove a social media account

### ISSUE THREAD

**Issue by rory** [keybase/keybase-issues#1353]
I have associated a reddit account with my keybase identity. However I'd like to undo that. I'd like to remove the link between my reddit account and my (say) twitter account. I can't see how to do this on the website, is this possible?

**Comment by malgorithms** [comment]
If you click the link called "post" next to it, a list of options will pop up for you. Choose "revoke" or "replace":

![image](https://cloud.githubusercontent.com/assets/614943/5940826/429b27d8-a6db-11e4-844a-5693004d3ace.png)

You can remove whichever one you prefer not to leave on your profile (the twitter or reddit one).

**Comment by rory** [comment]
Thank you, that solved my problem. :)

I saw that, and thought it might revoke my entire GPG key, and I'd mess everything up. Maybe change the text to "Revoke this profile" (or "Revoke this reddit account"?)

**Comment by dwrz** [comment]
I'm not able to remove my twitter account. I can't find the keybase command to abandon twitter, and the cURL command also fails.

**Comment by scarolan** [comment]
Same problem as @dwrz - my account is still attached to a non-existent twitter account (I closed the account).  Can you help me remove it?

**Comment by mlsteele** [comment]
@dwrz @scarolan Does the twitter account have a row like in the app (similar to the screenshot above)? What about in the website _when logged in_?
