### ISSUE TITLE
Security Issue~

### ISSUE THREAD

**Issue by MTK911** [keybase/keybase-issues#1357]
Hi,
 I have located a security issue on your site and more detail on it is as follow:

Issue:
non Expiring Token

Tested on:
Windows/Firefox, Chrome

P.O.C:
Reset Passowd
https://keybase.io/_/user/reset-pw?l=*

Description:
When i requested my password to be reset i received the token from which i was able to reset my password, but after resetting it the token did not expired as it should be so i tried it 3 more times and i was able to reset my password all the time.

This can be a security issue when an attacker can access the user history and accessing the token again will allow to reset the password and takeover the account.
Please let me know if there is more information required on this.
Regards,
<a href="http://keybase.io/mtk911">MTK</a>

**Comment by logankoester** [comment]
Really, no response at all on this?

**Comment by maxtaco** [comment]
Links expire 20 minutes after they're sent.  We tried shorter but some people have mailer delays.

Also, having access to someone's session doesn't allow an attacker to access to the victim's unencrypted private key.  If the compromised user is storing their encrypted PGP public key on the server, the attacker still needs to brute force it. If not, then the attacker can at worse delete the victim's account.  Inconvenient, but way safer than letting the attacker commandeer the victim's identity.

**Comment by MTK911** [comment]
Thank you for taking a look into this. Should have tested it later on which i didn't do but one time session token is much secure as compared to Time based expiration but it depends on what fits on your side.
Regards,
<a href="http://keybase.io/mtk911">MTK</a>

**Comment by logankoester** [comment]
Thanks
