### ISSUE TITLE
Decouple private key passphrase from Keybase.io shared secret passphrase

### ISSUE THREAD

**Issue by jzila** [keybase/keybase-issues#1358]
Right now, it seems that the two passphrases must be the same, but I can't see a reason that they need to be. It would be great to be able to specify a separate passphrase for my private key and my keybase shared secret. This way, if (god forbid) one passphrase is breached, the other is still safe.

**Comment by zQueal** [comment]
> Right now, it seems that the two passphrases must be the same

It might be that way because you generated your key on Keybase? If that's the case then you can make a backup of your private key, change the password and import it into your keyring, then push it via the CLI `keybase push`. 

If not, it seems to be a weird bug. Most others opt to have two separate passwords for their key and Keybase account. (hopefully) Myself included.

**Comment by jzila** [comment]
K thanks I'll give that a shot.

**Comment by jzila** [comment]
I don't see an API in the keybase CLI that makes changing the passphrase on a private key (in your keyring) easy. Do I have to manually use PGP (or P3SKB) to decrypt with my existing passphrase and then re-encrypt?

**Comment by zQueal** [comment]
> I don't see an API in the keybase CLI that makes changing the passphrase on a private key (in your keyring) easy.

Correct.

> Do I have to manually use PGP (or P3SKB) to decrypt with my existing passphrase and then re-encrypt?

No. You need to use other PGP tools, such as GPG to change your password:

(my key ID: B73E8516)

> gpg --edit-key B73E8516
> passwd
> save

The `passwd` prompt will allow you to change the key's passphrase. Once you `save` and successfully exit gpg, you can then execute `keybase push` which should push your new passphrase to Keybase. I'm sure there are easier ways of doing this, but I'm not too sure. This is the way I've always done it, anyhow.

**Comment by jzila** [comment]
Worked perfectly. Thanks for your help!
