### ISSUE TITLE
Twitter verification: start with a mention?

### ISSUE THREAD

**Issue by nclm** [keybase/keybase-issues#1360]
Hi,
I understand the need to post a tweet to verify a Twitter account, but it sort of spams followers’ timelines just for this. What about prefixing the tweet with a mention to a dedicated account, like @KeybaseProofs, the same way Reddit verification is done, so the tweet is still public but not as noticeable?

**Comment by dtiersch** [comment]
duplicate of #929 
tl;dr starting Tweet with `@keybaseIO` works as well

Also: promotion #334

**Comment by nclm** [comment]
Ok, thanks!
