### ISSUE TITLE
Changing Github username in Keybase.io

### ISSUE THREAD

**Issue by mikegehard** [keybase/keybase-issues#1361]
Hello and thanks for Keybase.io!

I have recently changed my GitHub username and am trying to figure out how to change it on Keybase.io, if it is possible.

Thanks,
Mike

**Comment by zQueal** [comment]
You can't change it, but you can drop your current authorization and reauthor under your new name, as far as I know.

**Comment by malgorithms** [comment]
if you make a new proof it revokes the old (in fact there's a revocation statement posted along the addition of the new one, automatically.)

follow instructions by clicking the word "gist" on your profile on the site.

![image](https://cloud.githubusercontent.com/assets/614943/6001701/7acb23fa-aaba-11e4-9fb8-43935399e15c.png)

**Comment by mikegehard** [comment]
Perfect. Thank you!
