### ISSUE TITLE
Cannot revoke my public key

### ISSUE THREAD

**Issue by awilisch** [keybase/keybase-issues#1367]
I wanted to replace my key with one I generated myself. When I try to revoke my key from either the web or the cli I get the following error:

{"code":501,"desc":"Failed to perform revocation","name":"DB_INSERT_ERROR"}

My private key has already been removed, so I'm kind of in a bind until I can get the public key revoked and upload my new key.

**Comment by maxtaco** [comment]
Sorry 'bout that.  Should be fixed now...

**Comment by awilisch** [comment]
Thanks, it’s working now!

**Comment by wwkeyboard** [comment]
I'm seeing this error as well.

**Comment by maxtaco** [comment]
have you retried recently?

**Comment by wwkeyboard** [comment]
Yes, it's failing for the wwkeyboard@keybase.io user.

**Comment by maxtaco** [comment]
Can you send me a screenshot? Thanks

**Comment by maxtaco** [comment]
nevermind, i see the issue.

sorry, fixing it now.

**Comment by wwkeyboard** [comment]
Awesome, thanks!

**Comment by maxtaco** [comment]
Sorry 'bout that, try it now?

**Comment by wwkeyboard** [comment]
`info: success!` :boom: thanks!

**Comment by maxtaco** [comment]
Cool thanks
