### ISSUE TITLE
cli `keybase login` without passphrase (feature request)

### ISSUE THREAD

**Issue by shazow** [keybase/keybase-issues#1369]
Probably a v2 thing, but it'd be nice to not have to enter my keybase.io passphrase to auth against the keybase cli tool.

A few ways this could be achieved:
- Use the PGP privkey on my machine to auth against the pubkey already verified on my keybase.io account.
- Use a one-time auth URL that the cli spits out, then I can open in my browser to that URL (or even open it automatically) and it connects against my logged-in session.
- Use a standard OAuth2 flow (related #831).

Reasons why this is a good idea:
- People rely on their browsers remembering their passwords, it can be hard to pull out a website's password outside the context of the browser.
- It's a bad habit to be putting passwords in the command-line that people should avoid learning. (I can expand if necessary.)
- Authenticating against the key is more hands-off and congruent with the spirit of keybase.

**Comment by maxtaco** [comment]
This is really the right idea.  Just implemented over in Go land! https://github.com/keybase/go/issues/128

**Comment by shazow** [comment]
Very nice! I should switch over. :)

**Comment by maxtaco** [comment]
You can't yet, it's not ready!  We should back-port it to node-client, you're right.

**Comment by shazow** [comment]
TRY AND STOP ME!! (Okay, will wait patiently. :P)
