### ISSUE TITLE
Confusing and frustrating command-line 'prove' interaction

### ISSUE THREAD

**Issue by PhilHudson** [keybase/keybase-issues#1377]
I get repeated failure-to-prove messages for my website, but the file http://hudson-it.ddns.net/.well-known/keybase.txt exists and has been retrieved from multiple locations on multiple networks, yet I get this:

```
(~) 2166% keybase prove web http://hudson-it.ddns.net                                              
info: Updated file: /home/phil/.cache/keybase/session.json
You already have claimed ownership of http://hudson-it.ddns.net; overwrite?  [y/N] 
error: Proof already exists
(~) 2167% keybase prove web http://hudson-it.ddns.net                                             
You already have claimed ownership of http://hudson-it.ddns.net; overwrite?  [y/N] y
warn: You'll be asked to post a file available at
warn:      http://hudson-it.ddns.net/.well-known/keybase.txt
warn:   or http://hudson-it.ddns.net/keybase.txt
Proceed? [y/N] y

You need a passphrase to unlock the secret key for
user: "Phil Hudson (Be free) <phil.hudson@iname.com>"
4096-bit RSA key, ID 1A366FB64E482F85, created 2014-09-15

error: A live proof for http://hudson-it.ddns.net already exists (error #230)
```

AFAICT neither the CLI tool nor the website provide a way of resolving this.

**Comment by maxtaco** [comment]
Agreed, not great usability here.  But try `keybase list-sigs` to find the signature and `keybase revoke-sig` to revoke it.  Cheers.

**Comment by PhilHudson** [comment]
What is "it" in the foregoing sentence?

**Comment by maxtaco** [comment]
The signature if `ddns.net` that you previous signed

So first get the signature ID:

```bash
keybase list-sigs | grep ddns.net
```

Extract column 2, that's the signature ID of  your previous proof.  And then run:

```bash
keybase revoke-sig <id>
```

You could try it as one ugly pipeline:

```bash
keybase list-sigs | grep ddns.net | awk ' { print $2 }'  | xargs keybase revoke-sig
```

**Comment by PhilHudson** [comment]
The id includes three trailing dots. Can that be right? keybase revoke-sig barfs on it.

**Comment by maxtaco** [comment]
Ah, you're right. The "..." means that there's more to the sigId, but we've just abbreviated the sigId for the purposes of display. I've updated the previous instructions, using the `-v` flag to `list-sigs` which prints the full sigId.  Thanks for your feedback.

**Comment by PhilHudson** [comment]
And back to this again:

```
Check http://hudson-it.ddns.net/.well-known/keybase.txt OR http://hudson-it.ddns.net/keybase.txt now? [Y/n] 
warn: Didn't find the posted proof.
```

Endless times, yet a remote site from where I am now is able to retrieve the file.

**Comment by maxtaco** [comment]
ok, don't touch anything, let me check it

are you sure you're not rejecting User-Agents that you don't recognize?

**Comment by PhilHudson** [comment]
Just retrieved it with elinks... so I don't think so.

**Comment by maxtaco** [comment]
I get a 404 with node.js request, but i can see it fine with Chrome

```javascript
var request = require('request');
request("http://hudson-it.ddns.net/.well-known/keybase.txt", function(err, res) {
  console.log(res.statusCode)
})
```
Outputs
```
404
```

**Comment by PhilHudson** [comment]
Also works with curl

**Comment by PhilHudson** [comment]
Will check my errlog

**Comment by PhilHudson** [comment]
Weird:

```
2015-02-10-15:15:16: 200     3264 GET /.well-known/keybase.txt
2015-02-10-15:28:38: 404       20 GET                    /
2015-02-10-15:30:38: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:30:39: 404       20 GET         /keybase.txt
2015-02-10-15:30:48: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:30:49: 404       20 GET         /keybase.txt
2015-02-10-15:31:25: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:32:21: 404       20 GET         /keybase.txt
2015-02-10-15:32:22: 404       20 GET         /favicon.ico
2015-02-10-15:32:22: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:32:23: 404       20 GET         /keybase.txt
2015-02-10-15:32:27: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:33:24: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:33:55: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:33:56: 404       20 GET         /keybase.txt
2015-02-10-15:34:55: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:35:28: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:35:29: 404       20 GET         /keybase.txt
2015-02-10-15:35:37: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:35:41: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:36:31: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:36:49: 200     3238 GET /.well-known/keybase.txt
2015-02-10-15:37:00: 404       20 GET /.well-known/keybase.txt
2015-02-10-15:37:01: 404       20 GET         /keybase.txt
2015-02-10-15:37:58: 200     3238 GET /.well-known/keybase.txt
```

IDK what the 404's have in common yet.

**Comment by maxtaco** [comment]
I share your confusion.  It works with `curl -A foo` without a problem too. Weird.

**Comment by PhilHudson** [comment]
What I do know is that UAs including Firefox, Conkeror, Opera on Android, MSIE on Windows, elinks and curl have all accessed the file no problem. The only one erroring seems to be node.

**Comment by PhilHudson** [comment]
Talking to the server's developer on IRC now

**Comment by maxtaco** [comment]
I think the problem is that node's request module is (weirdly) sending:

```
host: hudson-it.ddns.net
```

note the lowercase 'h'

**Comment by malgorithms** [comment]
This works in Node.js, getting a 200 and printing the body fine:

```javascript
var http  = require('http');

var options = {
  hostname: 'hudson-it.ddns.net',
  path: '/.well-known/keybase.txt',
  method: 'GET'
};

var req = http.request(options, function(res) {
  console.log("" + options.hostname + " res.statusCode=" + res.statusCode);
  res.on('data', function (chunk) {
      console.log('BODY: ' + chunk);
    });
});

req.end();
```

Max points out that the only difference between this `http` based call and the call from the common node library `request` is the "Host:" being capitalized in one case and not the other.

**Comment by PhilHudson** [comment]
Server dev accepts that this should not happen and has asked me to raise a bug.

**Comment by PhilHudson** [comment]
Thanks guys, sorry for the hassle.

**Comment by maxtaco** [comment]
Glad we got to the bottom of it!  Ideally, `request` would get their act together too.
