### ISSUE TITLE
'keybase' CLI is not able to verify websites which were verified using DNS record.

### ISSUE THREAD

**Issue by shantanoo** [keybase/keybase-issues#1385]
'track' keybase CLI (version 0.7.4), verifies the website of the user which will be tracked. For websites
verified by DNS TXT record, CLI searches for '_keybase.DOMAIN'.
e.g.

<snip>
✖ admin of the DNS zone for chriscoyne.com (failed with code 107: queryTxt ENOTFOUND _keybase.chriscoyne.com)
Some remote proofs failed!
</snip>

But there is no such record in DNS.

<snip>
$ host -t txt _keybase.chriscoyne.com
Host _keybase.chriscoyne.com not found: 3(NXDOMAIN)

$ host -t txt chriscoyne.com
chriscoyne.com descriptive text "keybase-site-verification=xKdYzPMen7ulhZd_UHr8QkfQ-H-fM81pdrIvlVZFU-U"
chriscoyne.com descriptive text "keybase-site-verification=hnxZXDScfBEkUCFCE-PTVIN1V62YRzBniSxneeNCirY"
chriscoyne.com descriptive text "keybase-site-verification=2_UwxonS869gxbETQdXrKtIpmV1u8539FmGWLQiKdew"
</snip>

**Comment by maxtaco** [comment]
upgrade to v0.7.5

**Comment by shantanoo** [comment]
Fixed in v0.7.5.
