### ISSUE TITLE
Reddit verification is broken

### ISSUE THREAD

**Issue by OJ** [keybase/keybase-issues#1387]
Trying to verify Reddit accounts currently doesn't work. The command line client errors out saying that it can't find the post, yet it's definitely there.

**Comment by Alenonimo** [comment]
Verifying reddit is tricky but it's possible. The post is supposed to be
really big, so it generates a giant URL that some programs can't handle.

Make sure to get that immense URL and paste it directly on your browser,
with no line breaks. You may have to paste on a text editor to edit it
properly.

2015-02-12 19:43 GMT-02:00 OJ Reeves <notifications@github.com>:

**Comment by malgorithms** [comment]
can you verify:
  1. the full post got posted (it doesn't seem weirdly cut off, especially in the middle of the PGP)?
  2. you're not shadowbanned? (http://nullprogram.com/am-i-shadowbanned/)

**Comment by OJ** [comment]
Hi all. Thanks for that.

Yes the URL was being truncated. Very odd, because I just tried it again, exactly the same way, but it wasn't.

Clearly a user issue ;)

OJ
