### ISSUE TITLE
Obtrusive error message preventing webui usage: "twitter_interests_bar.toffee: Cannot read property 'profile' of undefined" 

### ISSUE THREAD

**Issue by k3ypad** [keybase/keybase-issues#1393]
Howdy folks,

Each time I login I get a horrendous error message about a twitter picture. I can't close/move around the error message box, and it sits on top of most of the functions I want to use.
![screen shot 2015-02-16 at 10 09 54](https://cloud.githubusercontent.com/assets/2953023/6210088/055da344-b5c4-11e4-85ab-8b7f0f777c98.png)

This happens on:
- OSX Yosemite(10.10.1) in Chrome 40.0.2214.111 (64-bit), Safari Version 8.0.2 (10600.2.5), Firefox 35 (64bit), Firefox 36 (64bit).
- and on Windows 7 SP1 64bit, IE 11 (11.0.9600.16428), Firefox 34.0.5

Other OS's not tested, and I have confirmed that this appears to be just me.

**Comment by malgorithms** [comment]
fixed, I believe. Let me know (reopen) if not.
