### ISSUE TITLE
Mistake deleted account invitation code no longer valid

### ISSUE THREAD

**Issue by rikkotec** [keybase/keybase-issues#1407]
Hello, I followed advice from this post here:

https://github.com/keybase/keybase-issues/issues/803

Thinking (perhaps reading too quickly) that I could delete the account (freeing the email address used by the system), and then reuse the invitation code....but this did not work -> I get error that invitation code is no longer valid...

I finally have a signed key pair to use with keybase.io (that I actually use almost daily in development) and was very interested in testing it out for syncing my private/public keypair between my devices.  I wanted to change the account username from 'mmod' (which is a potential trademark for my company, and moreover represent my *company*) to 'rik' which is my name; or to 'rikkotec' or 'devrikx' - which are handles I use for myself personally between many services.

Could I request that if one deletes their account that perhaps somehow the email and invitation code can be linked still within the system so that they still work to create a new account (which would offer a means to change username?)

I hope by your mercy at the least I can get another invitation code, the email I'd prefer is rik@mmogp.com (I did push another invitation request...but it said I'm 9k in queue - and last time it was MONTHS before I got the invite :)  I hope you understand!

Thanks in advanced!

**Comment by malgorithms** [comment]
here, use this. Closing so you notice the code first :-)

b4fa61a632a6b04cdda34c0d

You can still use the email address you joined under before.

**Comment by rikkotec** [comment]
Thank you so much malgorithms - I'm all set up again, full bio and everything. I'll test aggressively over the next few weeks :)
