### ISSUE TITLE
Replacing Twitter proof doesn't seem to work

### ISSUE THREAD

**Issue by VonAdler** [keybase/keybase-issues#1408]
-Claimed twitter identity (https://twitter.com/mikkoheikkinen) for the first time via command line, worked fine
-Removed verification tweet before I knew I shouldn't
-Tried to claim identity again using command line, posted new verification tweet but keybase doesn't detect it.
-I got two emails from keybase, saying that my twitter identity checks are failing, I assume this refers to the original removed verification tweet
-retried again to verify twitter account, still no success

I now have two verification tweets on my public profile but keybase still doesn't detect either one of them. I'm guessing that abandoning the original verification before retrying might work, but I thought I 'd file this report first if it is a genuine bug. Thanks!

**Comment by maxtaco** [comment]
The issue is that you left out "Verifying myself."

You can prefix the post with `@keybase` if you don't want to broadcast the tweet a 3rd time.
