### ISSUE TITLE
Expired Self-sig on UID leaves account in a broken state

### ISSUE THREAD

**Issue by maxtaco** [keybase/keybase-issues#1410]
For the user `feld`:

```
Your public key appears corrupted (no valid primary key self-signature)
```

https://pgp.mit.edu/pks/lookup?op=vindex&search=0x983B64501F13E252

**Comment by maxtaco** [comment]
Try `keybase push --update` BTW?

**Comment by feld** [comment]
I've never installed the keybase client.... mostly because of the node requirement.

**Comment by maxtaco** [comment]
That's no problem.  Just upload your new public key to the site.  That should solve the problem. Let me know if not.

In your profile, there's a gear.  Click on the gear and click "Update my key"

![image](https://cloud.githubusercontent.com/assets/866815/6379089/91920234-bcfd-11e4-8cd7-d442ea0c0370.png)

**Comment by feld** [comment]
I get that same error when I try to replace it with the pub key from the mit.edu key server

**Comment by maxtaco** [comment]
ok, i'll take a deeper look.  thanks.

**Comment by maxtaco** [comment]
Do you get the error on initial upload, or after you've run the gpg/perl/curl command line?

**Comment by feld** [comment]
The error started after I tried to update my public key. I can't recall why; it's been this way since like... November?

**Comment by maxtaco** [comment]
Right, I'm just trying to understand at which point in the process you get that error. Something like a screenshot would greatly help. I'm so far not able to reproduce the bug.

My next move is to try to create a key with a UID that's valid today and expired tomorrow.  I'll hopefully get to that soon, but I'm pretty busy today with other stuff.

**Comment by maxtaco** [comment]
(And BTW, the November date makes sense, that was the expiration date on your UID in the key you originally uploaded).

**Comment by feld** [comment]
Here's the screenshot:

![screenshot](http://i.imgur.com/VWJUPWh.png)

**Comment by maxtaco** [comment]
Perfect, thank you.

**Comment by maxtaco** [comment]
Ok, I see the issue.  We're loading up your old public key to compare fingerprints to the new public key, but the loading of the old is failing because of the expired UID.  I should have a fix in about 30 minutes or so.  Thanks for you help debugging this.  I'll let you know when to try again.

**Comment by maxtaco** [comment]
There's only so much I could test on my end, but it might now work.  Give it another shot?  Many thanks!

**Comment by feld** [comment]
Hey, no more errors! It let me upload it and it's not going to error when I fix my github identity verification -- thanks!

**Comment by maxtaco** [comment]
Phew.  Ok to close? Thanks for your help.

**Comment by feld** [comment]
yes, go ahead :+1:
