### ISSUE TITLE
Failed Twitter verification

### ISSUE THREAD

**Issue by dkocher** [keybase/keybase-issues#1411]
> Hi, dkocher, your attempted twitter identity proof of @davidkocher never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

The tweet is https://twitter.com/davidkocher/status/570660064098430977 and the proof was initiated using keybase `0.7.7` on 10.10.3.

**Comment by dkocher** [comment]
As an additional note, my public profile https://keybase.io/dkocher shows the verification complete whereas https://keybase.io/dkocher/sigs/XjYoSnfnnpWGwDv4PfGMPKQGuM3fD8JbQG53 claims the identity is not proven.

**Comment by maxtaco** [comment]
You left out "Verifying myself: "
