### ISSUE TITLE
Segmentation fault during tracking

### ISSUE THREAD

**Issue by mrooding** [keybase/keybase-issues#1413]
Hi guys

First of all: thanks for accepting my alpha request. I've already enjoyed using the service so far but ran into a problem trying to track my brother (whom I've invited) using the command line utility on OS X. 

For some reason I'm getting a segmentation fault without any more information:

➜  ~  keybase track rrooding
info: ...checking identity proofs
✔ public key fingerprint: 3FE9 4CE4 E55A 8F04 95C7 53B3 7586 46CA 8091 0CB3
✔ "rrooding" on twitter: https://twitter.com/rrooding/status/570679590093512709
✔ "rrooding" on github: https://gist.github.com/ed2bc05aebdc09f21166
[1]    20154 segmentation fault  keybase track rrooding

I checked the github issues list but I only noticed users reporting segmentation problems while logging in. Is anyone aware of this issue? I was in the end able to track him using the web UI.

Kind regards

Marc

**Comment by maxtaco** [comment]
On broken versions of node.  Which one are you using?

**Comment by mrooding** [comment]
Should be the latest:

➜  ~  npm -v
2.5.1

**Comment by maxtaco** [comment]
And what does `node --version` show?

**Comment by mrooding** [comment]
Oops my apologies, I recently updated everything using brew so node is at 0.12.0:

➜  ~  node --version
v0.12.0

**Comment by maxtaco** [comment]
Yeah, I can repro that.  Looks like a Bug in Node's DNS resolver.  Sigh.  Thanks for pointing this out.  I'll report it to the node folks.  Here's the script to break it.  Looks like your brother(?)'s DNS server is replying with some data Node can't parse.  A bad thing for sure.

```javascript

var dns = require('dns');

dns.resolveTxt('www.ralphrooding.com', function(err, res) {
   console.log(err);
   console.log(res);
});

```

**Comment by mrooding** [comment]
I'll give your script a try tomorrow. Feels like time for bed. Glad I could be of help!

**Comment by maxtaco** [comment]
No reason to run the script, all it does is crashes node!  It's just an isolated way to reproduce the bug you found.  I reported it to Node, I didn't see it open already.

**Comment by mrooding** [comment]
That's the fun part right? ;) I've seen your bug report, I'll also keep an eye on it
