### ISSUE TITLE
Hardcore mode: Avoid polluting bash history

### ISSUE THREAD

**Issue by shazow** [keybase/keybase-issues#1417]
**Problem**: I use ctrl+r in my shell fairly often to look up old commands, and because Keybase hardcode mode is a big blob of common words, it tends to come up way more often than I'd like. I'm basically never looking to run a keybase copypasta command a second time, so it's unfortunate to have it sitting in my history and coming up too often.

**Solution**: Put a space in front of the command copypasta.

Putting a space in front of a bash command will omit it from being written in your bash history. I do this manually if I remember to do so, but I'm sure other users will appreciate it as a default.

Also great for avoiding writing commands with sensitive arg values into your history, in case it's compromised at a later date.

**Comment by maxtaco** [comment]
Live, thanks!

**Comment by shazow** [comment]
Yay, thanks @maxtaco! :confetti_ball:
