### ISSUE TITLE
Invites granted twice

### ISSUE THREAD

**Issue by guillaumebreton** [keybase/keybase-issues#1418]
I proved my Github account with a gist and my Twitter account with a tweet. I get 4 invites and I deleted the tweet and the gist.

I get a mail asking me to "prove" them again. Once I did it, I received a new mail granting me 4 invites and I now get 8 invites. Might not be a bug ... but should'nt I have 4 invites instead of 8 ?

**Comment by malgorithms** [comment]
I think the timing just made it look that way.  The formula for default invitation power includes some other things (not just proofs), and I just confirmed yours should add up to 8.

thanks!

**Comment by guillaumebreton** [comment]
Great thx! :)
