### ISSUE TITLE
Mistyped username, need to change it

### ISSUE THREAD

**Issue by ArchimedesPi** [keybase/keybase-issues#1420]
I accidentally mistyped my username when using my invite.
I've deleted my account - can anyone give me a new invite?

> Liam

**Comment by Alenonimo** [comment]
I have some, but I need an e-mail address to send.

**Comment by ArchimedesPi** [comment]
Thanks! My email is archimedespi3141@gmail.com :D

**Comment by malgorithms** [comment]
Make sure to delete the old account.

While you can reuse an email address during signup (if you deleted the old account), the invitation system won't allow sending more invitations to the same address (to avoid accidental harassment), so @Alenonimo  , you might send it to archimedespi3141+2@gmail.com if it says he/she is already invited.

**Comment by ArchimedesPi** [comment]
I've deleted the old account @malgorithms @Alenonimo :smiley:
Sorry about this - I should have double-checked before hitting submit :)

**Comment by ArchimedesPi** [comment]
But then won't @Alenonimo have to manually email me the invite key, because the email will be bad?

**Comment by ArchimedesPi** [comment]
Thanks so much @Alenonimo!
