### ISSUE TITLE
Proving Twitter fails with permission denied.

### ISSUE THREAD

**Issue by sfrehse** [keybase/keybase-issues#1421]
I just wanted to prove my twitter account.

I typed the following commands into CLI as described on the keybase.io page:

> keybase prove twitter

and I just put those printed text into a public tweet.

However, once keybase checks for validity it tells me:
   _warn: Permission denied! We can't support private feeds._
However, the tweet is readlabe on my timeline.

keybase (keybase.io CLI) v0.7.7
- node.js v0.12.0
- gpg (GnuPG) 2.0.25
- libgcrypt 1.5.3
Identifies as: 'keybase.io node.js client v0.7.7 linux'

**Comment by sfrehse** [comment]
My proof: https://twitter.com/sfrehse/status/571252355427123200

**Comment by jomo** [comment]
They aren't readable on your timeline:
![screenshot](https://i.imgur.com/xsJ9XOS.png)

**Comment by sfrehse** [comment]
@jomo Thanks a lot! That works now.
