### ISSUE TITLE
Still no safe and easy ways to verify key.

### ISSUE THREAD

**Issue by Morthawt** [keybase/keybase-issues#1425]
After all this time, I still see the two linux genius options and then the option which has you upload your private key. I do not care if I am told by the site that it is encrypted locally or not... Having users upload their private key is only going to breed bad security practices. You should never upload your key to any website. Every few months/weeks what ever I bring keybase up to see if they have added some sane method of verification. Each time they have not. Implement a random 256bit string and have the user either copy and sign the text and paste the signed text back or download a file containing the string and sign and upload the signed file, which ever the user prefers. That is the perfect, easy and SAFE way to verify the person really has the key.

**Comment by maxtaco** [comment]
We're working on it.  Turns out to be a hard problem :)

**Comment by Morthawt** [comment]
That is indeed very good  news! Last time I heard anything about this I got all doom and gloom about me not wanting to upload my key or not being a linux guru to do the other options. This is very very good news. Thanks.

**Comment by Jagermo** [comment]
Are there any updates on this topic? Non-linux genius here...

**Comment by Morthawt** [comment]
This was mentioned yesterday on the Security Now podcast. I mentioned in the IRC chat about this verification problem and that they are working on it. I really hope this gets resolved soon.

But as good as this service gets, the same limitations of PGP still exist :( I recently ran into a problem of wanting to quote part of an email I received from someone to someone else but I could not because the entire email conversations were PGP encrypted so I would have had to go one, by, one, and, decrypt, and check, each, one... Really annoying. I never thought about it from that perspective. Not to mention the issue of people using client plugins to do PGP and they accidentally reply to an email and the quote is decrypted!?!?!?! Man that is a dangerous thing.

Any way I digress.
