### ISSUE TITLE
Twitter Verification

### ISSUE THREAD

**Issue by arkbg1** [keybase/keybase-issues#1427]
How do protected tweeters verify?

https://twitter.com/AnonForecast/status/571803923507503104
Aaron Bale ‏@AnonForecast

Verifying myself: I am aaronbale on Keybase.io. lwk92a-klp_UrcfhG_ZFQbGAeumKB6iK6rXk / https://keybase.io/aaronbale/sigs/lwk92a-klp_UrcfhG_ZFQbGAeumKB6iK6rXk …
0 replies 0 retweets 0 favorites
5:47 PM - 28 Feb 2015

**Comment by malgorithms** [comment]
They can't - the tweet isn't just for Keybase's servers or your personal friends - it's for anyone who wishes to verify Keybase's directory. ( It's a directory of publicly verifiable proofs. )

You can still tweet/post your fingerprint and Keybase id to your protected followers, but it won't show up on Keybase. So hopefully keybase can still be useful to you.
