### ISSUE TITLE
Twitter proof not working

### ISSUE THREAD

**Issue by bcgallaher** [keybase/keybase-issues#1442]
I have been trying to prove my twitter account via popup window. I have tried a number of times but no success. I deleted the older tweets and have just tried the newest one. This is the page the the tweet takes me to. 

Oy!
That identity proof for bcgallaher is pending, revoked, or non-existent.

Practically speaking, don't trust whatever linked to this page, until this page loads correctly and concurs with the source. If you came here from an old link, please check out bcgallaher's profile for the latest key and valid identity proofs.

I have read through previous issues but haven't found a solution. 
Any help would be appreciated.

**Comment by dtiersch** [comment]
[Link to the tweet in question](https://twitter.com/BenGallaher/status/573206373992947712)
But I guess since the proof is hosted on keybase.io that debugging this requires FS access to the server

**Comment by maxtaco** [comment]
You entered the wrong username.  You asked our servers to scrape `@bcgallaher` but you're `@BenGallaher` on twitter

**Comment by bcgallaher** [comment]
Seriously! I'm so stupid. First time that has happened. 
Thanks.

**Comment by exsortis** [comment]
I'm having the same problem. Changed my username on Twitter, and it's not finding the new proof tweet (https://twitter.com/brickdm/status/574260892990226432).

**Comment by bcgallaher** [comment]
Once I put in the correct username it worked straight away.

**Comment by zQueal** [comment]
@exsortis if you changed your twitter username, then you'll have to redo the proof--since the URI schema changes to reflect your new username, the preexisting proof will be invalidated because it 404s.
