### ISSUE TITLE
Account recovery after deletion

### ISSUE THREAD

**Issue by franckuestein** [keybase/keybase-issues#1460]
Hi guys! I've been using Keybase since long time ago but today I've decided to sign a new message and I've had some problems..
1st of all: I always write down all the passwords that I use on Internet but I've lost the one that I use to sign messages when GPG Keychain asks for it.

I've decided to log-in on keybase and delete my account to recover It later (after ten minutes I've recovered the paper with my password - sad :-1: ), but now... I can't recover/register another time my account because It says that my account is deleted/my nickname is already in use (account is closed and deleted because I can't log-in & the URL doesn't work). Maybe there's a problem with the database or verification.

Can you please restore the account? Thanks!
If you need further information or something, I'm here :+1: (Hope to solve it soon because I'm desperate trying to recover the account). I have both private and public keys.

- I know that my responsibly is to save all the passwords, but... keep in mind that if someone deletes their account by an error, it has to be able to recover it signing up another time, don't you think so? I mean... my nick is not available and I need it to certify all the work or movements that I make on forums like bitcointalk or so :)

-------
PS: I've seen a solution here: https://github.com/keybase/keybase-issues/issues/1274 . I've tried to send an invite code to another email, use that code registering another time with my "original" email but I can't register it :/ maybe you have to do something and I'm going to be able to re-activate my account.

Now, I'm temporary using GnuPG without Keybase.

Thanks another time!

**Comment by malgorithms** [comment]
Hi @franckuestein  - yeah, the answer is that you can't re-use a username, even after it's been deleted. It gets locked out. this prevents confusion. Sorry!

You should be able to re-use your original email to signup. While you can't send an invitation email directly to that address, you can send it to another address and then still sign up with your original address.
