### ISSUE TITLE
Firefox Nightly (39.0a1 2015-03-20) fails logon while Chrome succeeds

### ISSUE THREAD

**Issue by Froosh** [keybase/keybase-issues#1469]
Login from keybase command line (v0.7.7) succeeds, and pulls private key correctly.
Login from Chrome (41.0.2272.89 m 64-bit) succeeds, and can access my private key.
Login from Internet Explorer 11 (11.0.9800.0) succeeds, and can access my private key.
Login from Firefox Nightly (39.0a1 2015-03-20 64-bit) fails, reporting "Incorrect Password".

I wish I could provide further detail, happy to be contacted about it, or will post further if the situation changes.

**Comment by dtiersch** [comment]
Seeing other problems here I guess it would help the developers to know what the JS-console prints when the error occurs.

**Comment by Froosh** [comment]
Sitewide-js.js throws these errors when the page is loading, but nothing during actual logon attempts:

TypeError: asm.js type error: module import needs initializer [sitewide-js.js:48:15835]
TypeError: asm.js type error: asm.js modules takes at most 3 argument [sitewide-js.js:48:21572]
TypeError: asm.js type error: asm.js modules takes at most 3 argument [sitewide-js.js:48:21908]

**Comment by Froosh** [comment]
Now works in Firefox Nightly 40a1 (2015-03-30)
