### ISSUE TITLE
Install Error on 64 bit Ubuntu 14.04 

### ISSUE THREAD

**Issue by sidtechnical** [keybase/keybase-issues#1473]
*Hello I am using 64 bit Ubuntu 14.04, created a Keybase account, installe the pre-requisits, and when I try to run the following two commands ( install keybase-installer and run it), I am copy pasting the messages from my  terminal.*

__ ~$ sudo npm install -g keybase-installer __
/usr/local/bin/keybase-installer -> /usr/local/lib/node_modules/keybase-installer/bin/main.js
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/pullstream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/match-stream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/pullstream/node_modules/slice-stream requires readable-stream@'~1.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/bower/node_modules/unzip/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/steroids/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
keybase-installer@1.0.1 /usr/local/lib/node_modules/keybase-installer

** ~$ keybase-installer **
error: Your version of node (0.11.11-pre) is not recommended; please upgrade to 0.10.32 or better

**Comment by zQueal** [comment]
> error: Your version of node (0.11.11-pre) is not recommended; please upgrade to 0.10.32 or better

**Comment by frank-borkin** [comment]
Out of curiosity, have you tried using the PPA?
sudo add-apt-repository ppa:borkinfr/keybase

**Comment by sidtechnical** [comment]
Upgraded the node version. And worked now.

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
