### ISSUE TITLE
API - CORS works for some API calls but not others

### ISSUE THREAD

**Issue by anthonyc0603** [keybase/keybase-issues#1479]
I am using the keybase.io API. Some cross site ajax requests work fine. Others do not. This one works and returns a json object, data

    $.get('https://keybase.io/_/api/1.0/user/autocomplete.json?q=john',function(data) {

    });

This one also works

    $.get('https://keybase.io/_/api/1.0/user/lookup.json?username=johnsmith', function( data ) {

    })

This one fails

    $.get('https://keybase.io/_/api/1.0/getsalt.json?email_or_username=johnsmith', function(data){

    });

I can see that the response headers of the first to contain the CORS Access-Control-Allow-Origin *.  The getsalt call does not.

I tried adding csrf_token as a parameter and it is rejected by the browser as an invalid cross site request.  I tried requesting as jsonp - this returns a json object which, of course, does not parse as a valid jsonp request.

Any help appreciated.

**Comment by argakiig** [comment]
If you look at the documentation for the API calls the first two you reference allow CORS but the second one does not.
See [API Docs](https://keybase.io/docs/api/1.0)
A work around would be to curl the api call and then work with the results from the curl. There could be another way to implement this but other than the quick and dirty I wouldn't know what else to do

**Comment by malgorithms** [comment]
closing this one since answered by @argakiig and we don't currently intend on supporting login CORS calls.
