### ISSUE TITLE
Password/account recovery not working

### ISSUE THREAD

**Issue by ianonavy** [keybase/keybase-issues#1480]
Steps to reproduce:

1. Visit https://keybase.io/
2. Click login
3. Click recover account
4. Enter username
5. Wait 30 minutes
6. Email not received, so I go back and enter my email instead
7. "user not found"

Expected:
- receive email with recovery account

Actual: 
- "user not found"

I signed up by clicking an email with an invitation, and I remember verifying my GitHub. When I visit https://keybase.io/ianonavy I no longer see the link for GitHub, and I don't have any other way to verify that I created this account apart from the fact that my PGP public key is there. What do?

**Comment by malgorithms** [comment]
Hey - email me.. chris@keybase.io - I want to confirm first of all that we have the correct email address on file for you. Then if so figure out why you're not getting the email. We can definitely get the account back for you, but you'll have to redo the proofs.
