### ISSUE TITLE
one webspace multiple domains - proof

### ISSUE THREAD

**Issue by nilsology** [keybase/keybase-issues#1483]
Hi, I was wondering if it is possible to proof multiple domains with only one proof-file?
I got multiple domains pointing to the same webspace. I provided proof for all those domains in my DNS-conf, and for one of those via a proof-file. Now I am wondering if it is possible to proof multiple domains with only one or multiple files.
Thanks in advance!

**Comment by zQueal** [comment]
You can accomplish this by using both of Keybases' website proofing methods. Simply add to your `keybase.txt` file (assuming multiple domains point to the same location) to proof multiple domains, or simply add an A record for both domains via DNS.

Here is [an example](https://keybase.io/.well-known/keybase.txt) that both Max and Chris both use to author themselves and the Keybase.io domain. As you can see, they just stacked the proofs.

**Comment by nilsology** [comment]
That works. Thanks!
