### ISSUE TITLE
Put keybase.io on browser HSTS preload lists

### ISSUE THREAD

**Issue by akalin** [keybase/keybase-issues#1488]
...as described in https://hstspreload.appspot.com/

https://keybase.io currently has the following HSTS header:

    Strict-Transport-Security: max-age=31536000; includeSubdomains;

So I think we hit all but having the "preload" token.

**Comment by maxtaco** [comment]
the `preload` token is now done

**Comment by maxtaco** [comment]
(and i submitted the site, thanks...)

**Comment by maxtaco** [comment]
[Done!](https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json)

**Comment by akalin** [comment]
BTW, I don't think this has made it to stable yet. The commit that adds keybase.io is https://chromium.googlesource.com/chromium/src/+/fc7f871fb2219fbe8ff0856a0ac0a2fa3e5b90f2 (#323985) and according to https://omahaproxy.appspot.com/ M43 (stable) is on 323860 (6/22/15). But it should roll out to everyone for M44, which should be ~6 weeks from now.

**Comment by maxtaco** [comment]
:+1:
