### ISSUE TITLE
HTML comes through escaped in some warnings

### ISSUE THREAD

**Issue by sixlettervariables** [keybase/keybase-issues#1489]
Steps:

1. https://keybase.io/verify
2. Paste encrypted text into field
3. Click 'Verify'
4. Warning message underneath includes escaped HTML:

```
You've pasted an encrypted message. <a href="/decrypt">Decrypt it</a>.
```

Present in `1c9ade56/sitewide-js.js`. Looks like the _error_alert function ends up sanitizing the message passed via `pub_fns.escape_user_content`.

**Comment by rishabhsagar** [comment]
I can confirm this issue.  Screenshot here: http://snag.gy/tmTZu.jpg

**Comment by malgorithms** [comment]
fixed, thank you both

**Comment by rishabhsagar** [comment]
The HTML is no longer escaped.  :+1:  
From UI point of view, it'd be great to see the text in the message box being copied across to the message box in the decrypt tab when the 'Decrypt it' link is clicked.  Wondering if it's a simple fix...
