### ISSUE TITLE
Proof Problems

### ISSUE THREAD

**Issue by dstinebaugh** [keybase/keybase-issues#1492]
Having issues with both twitter and my personal domain.

For twitter I've actually posted 2 separate tweets
https://twitter.com/danstinebaugh/status/583515567149031427
https://twitter.com/danstinebaugh/status/583518245589655552
And even got one reply... so I know they're visible.

As for my personal domain, I have done both, hosting a keybase.txt file as well as adding a txt record.
My site is behind a load balancer, not sure if that's causing some confusion, as well as I use Amazon's Route 53 for DNS, 
screenshot for txt record: https://db.tt/GcB38CfY
screenshot of .txt file: https://db.tt/NcZTB49o

**Comment by dstinebaugh** [comment]
I think that the dns record might be failing due to the @ as I have several txt records, perhaps prepending keybase. to the txt record instead of @. would be a better solution.

**Comment by dtiersch** [comment]
As for your twitter proof: Your tweets are protected. Twitter proofs require that tweets are visible so that keybase.io can detect them and so that everybody else can verify them as well. And they need to stay that way, since the proofs are regularly rechecked.

what happens when you try to fetch the website proof with `curl`, e.g. what is the content of the received file?

**Comment by dstinebaugh** [comment]
There is no text in the .txt file so curl just returns without an error, 
I totally forgot I had made my tweets private! My Bad!!!

------ Original Message ------

**Comment by dstinebaugh** [comment]
So twitter's fixed, and yea, totally my fault on that one, but if the .txt file is supposed to have some data in it, then that might be a bug.
If I choose to use a text file following the example given: "example.com/keybase.txt" and I choose that option, I'm then asked to enter in my domain name. At no point does it generate any data to enter into this text file.

**Comment by dtiersch** [comment]
After you entered your domain name you should see the following window:
![file](https://cloud.githubusercontent.com/assets/1278210/6972981/ac9ecb06-d987-11e4-91c7-0e3eb0439474.PNG)
The first one is available if you host your private key on keybase.io. Then you will be asked for your passphrase, the other two options generate the content for the text file on the command line and output them on `stdout`.
Both ways you have to copy the content into the text file you're going to upload to your server.

**Comment by dstinebaugh** [comment]
Ok, so I do host my private key on keybase, so I was just trying to use the first option in the browser, as I was already there and it seemed the easy way to go. 
I have successfully gotten the txt file created and uploaded to my site and it has been verified, however the first 2 options never output the data as expected.
All in all it's working so THANK YOU David!
