### ISSUE TITLE
Public key outside keybase

### ISSUE THREAD

**Issue by diksm8** [keybase/keybase-issues#1501]
How do I encrypt a message to someone outside keybase?
Is there any way to to this with a command like "keybase encrypt --file <publickey.asc goes here> -m 'test'"

**Comment by zQueal** [comment]
Using the keybase client you can only encrypt to other keybase users. For this, you would use `gpg` directly:

    gpg --import name_of_pub_key_file
    gpg --encrypt --sign --armor -r name_of_pub_key_file name_of_file

To decrypt you'd simply

    gpg filename
