### ISSUE TITLE
Specifying gpg command via config.json?

### ISSUE THREAD

**Issue by larseggert** [keybase/keybase-issues#1506]
Is it possible to specify the location of the gpg command in `config.json`? (I know I can pass it with `-g`, but I often forget.)

I have both homebrew's gpg and gpgtools.org's gpg2 installed, and keybase needs to use the former on my system, but default to the latter.

**Comment by dtiersch** [comment]
The better approach is to let keybase handle editing the config file by using the command `keybase config gpg <value>` where `<value>` is either the programm name directly if it is in the `$PATH` or the path to your binary.

But for documentations sake, my `config.json` looks like this:
```json
{
    "user": {
        [...]
    },
    "gpg": "gpg2"
}
```

**Comment by larseggert** [comment]
Thanks, that works.
