### ISSUE TITLE
Some characters are decrypted wrong

### ISSUE THREAD

**Issue by schweinekrippe** [keybase/keybase-issues#1507]
"ö" becomes "Ã¶"
and "ü" becomes "Ã¼"

It seems, by leaving the ASCII range, some  encoding/decoding problems occur. 
The resulting characters are interpreted as 2 characters.

**Comment by j15e** [comment]
+1 I have problems with french accents in the web UI to be specific

![capture d ecran 2015-11-12 a 11 50 39](https://cloud.githubusercontent.com/assets/143380/11124602/eac1fcc6-8933-11e5-9ab2-9c527c307d34.png)

Merci beaucoup!

**Comment by malgorithms** [comment]
I am pretty sure we fixed this a while ago, which makes me think @j15e  - your problem could be coming from the encoding step, not the decrypting/verifying page of the website.

For example, I just pasted @schweinekrippe 's ö and ü with umlauts into a message, encrypted + signed it, and decrypted it back safely with the website. All the characters survived fine.

Even Emojis are surviving:

![image](https://cloud.githubusercontent.com/assets/614943/11153886/dd1ff2b8-8a09-11e5-8e13-8cf69dcc8e12.png)

@j15e - can you walk us through the generation of the PGP message in the first place? Is it something someone else sent you? How did they generate it? etc.

**Comment by malgorithms** [comment]
oh, just saw this:

>  I did the original signing withe command line tool.

was it using keybase or GPG?

**Comment by malgorithms** [comment]
I think the answer here is going to relate to a terminal client setting. For example, in OSX's terminal there is a setting for character encoding:

![image](https://cloud.githubusercontent.com/assets/614943/11154090/44a1756e-8a0b-11e5-8cab-962d8dfe9ae8.png)

do you have an equivalent setting in your software, and are you using UTF-8? 

Are you typing the chars in or pasting them in from some other source? I have no idea what happens to text getting moved cross-application via the clipboard. Is there an automatic attempt at converting, somehow? Is the encoding info included in the clipboard? Hmm.

**Comment by j15e** [comment]
I wrote the original text in an email in gmail (web/chrome) then I pasted it into [iTerm](https://www.iterm2.com/) (with utf8 set) then encoded using `keybase sign -m`.

![capture d ecran 2015-11-13 a 13 47 17](https://cloud.githubusercontent.com/assets/143380/11154434/48d0adba-8a0d-11e5-81fa-c44bb3e94cf2.png)

**Comment by malgorithms** [comment]
ok, reproduced! Thanks for the info.

**Comment by maxtaco** [comment]
Should be fixed, try again?

**Comment by j15e** [comment]
Yep fixed! Thanks

**Comment by maxtaco** [comment]
The issue BTW is that browserify's `toString()` method doesn't seem to be  `utf8` by default, whereas it seems like on modern versions of node.js, it is.
