### ISSUE TITLE
Web identity proof issue

### ISSUE THREAD

**Issue by dataflake** [keybase/keybase-issues#1512]
Hi,

Trying to use the "Host a file" option for my website and then entering the correct domain "zetwork.com" into the domain name field results in "could not query zetwork.com". The site works fine in all browsers and using curl.

**Comment by dataflake** [comment]
By the way, any access to straight HTTP at http://zetwork.com will result in a 301 redirect to https://zetwork.com. Maybe that's an issue for your verification code.

**Comment by zQueal** [comment]
From what I can tell, your `keybase.txt` isn't located in the correct place.

```
λ curl -k -i https://zetwork.com/keybase.txt
HTTP/1.1 404 Not Found
Date: Sun, 12 Apr 2015 19:40:40 GMT
Server: Apache
X-Frame-Options: sameorigin
Content-Length: 209
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /keybase.txt was not found on this server.</p>
</body></html>

λ curl -k -i https://zetwork.com/.well-known/keybase.txt
HTTP/1.1 404 Not Found
Date: Sun, 12 Apr 2015 19:41:27 GMT
Server: Apache
X-Frame-Options: sameorigin
Content-Length: 221
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.well-known/keybase.txt was not found on this server.</p>
</body></html>
```

**Comment by dataflake** [comment]
I was expecting the system to just do a check for the existence of the given web address and then provide me with instructions and content for the keybase.txt text file in step 2.  Is this a documentation or web page instructions issue?

**Comment by dtiersch** [comment]
@dataflake is right, there seems to be indeed an issue with `zetwork.com`.
If I enter on the web validation a valid domain like `github.com`, keybase.io shows the instructions on how to prove it, if I enter on the other hand `zetwork.com` keybase.io shows the above mentioned error message.

Trying this via the command line results in:
```
$ keybase prove web zetwork.com
error: Failed to find a connection to zetwork.com (error #229)
```

A DNS lookup looks fine:
```
$ host zetwork.com 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

zetwork.com has address 78.46.126.94
zetwork.com has IPv6 address 2a01:4f8:d16:290a::2
zetwork.com mail is handled by 10 mail.zetwork.com.
zetwork.com mail is handled by 20 mail3.zetwork.com.
```

**Comment by dataflake** [comment]
I don't know what you changed, but I was just able to do the web proof via command line on a different system where I had just installed the keybase client via Homebrew.

Thanks guys!
