### ISSUE TITLE
Reddit proof posted as authored, keybase doesn't see it

### ISSUE THREAD

**Issue by idan** [keybase/keybase-issues#1519]
Per the instructions in the failure email:

http://www.reddit.com/r/KeybaseProofs/comments/32jki8/my_keybase_proof_redditidangazit_keybaseidan/

I created it via the keybase commandline.

Help?

**Comment by NotTheEconomist** [comment]
You didn't copy the whole text. There's a whole section below with the signed PGP message that doesn't appear in your post.

**Comment by idan** [comment]
Roger, apparently iterm2's link-detection truncates the URL that `keybase prove reddit` spits out. Clicking on it doesn't populate the text of the post with the PGP sig; I never noticed that some chunk of the really, really long URL was missing from the post text.

Might be worth altering the instruction from the CLI to read "Copy and paste the following link into your browser" so this doesn't happen to other iterm users.

Cheers — and thanks!
