### ISSUE TITLE
Twitter proof created, keybase not verifying it.

### ISSUE THREAD

**Issue by n2468txd** [keybase/keybase-issues#1520]
I used the command line to generate a proof for twitter. https://keybase.io/n2468txd and https://twitter.com/n2468txd/status/588125441728233472 are the two profiles. Keybase still isn't picking up my tweet and verifying it.

**Comment by SkoteiniKampia** [comment]
Same here

**Comment by maxtaco** [comment]
@n2468txd there's a linebreak in your tweet in the hex string
