### ISSUE TITLE
Twitter proof does not work

### ISSUE THREAD

**Issue by lustigo** [keybase/keybase-issues#1529]
Hi,
i tried multiple times to get my twitter account connected to Keybase, but it failed every time.

Here´s the tweet: https://twitter.com/Lustigo/status/588769995473215488

Maybe keybase does not recognice the Link, because it is shortened?

Greetings

**Comment by zQueal** [comment]
Your post is as follows:

```
Verifying myself: I am lustigo on Keybase.io. DXRS3K2tQ6Us-cSGLsTN1kgaraWfTHxRgQ
pE / https://keybase.io/lustigo/sigs/DXRS3K2tQ6Us-cSGLsTN1kgaraWfTHxRgQpE
```

You have an extra line in there breaking the hash:

```
Verifying myself: I am lustigo on Keybase.io. DXRS3K2tQ6Us-cSGLsTN1kgaraWfTHxRgQpE / https://keybase.io/lustigo/sigs/DXRS3K2tQ6Us-cSGLsTN1kgaraWfTHxRgQpE
```

**Comment by lustigo** [comment]
Ok, thank you. I´ve copied it directly from the keybase command prompt, probably windows messed sth up.
Thanks!
