### ISSUE TITLE
Website verification fails with keybase tool and command-line

### ISSUE THREAD

**Issue by abompard** [keybase/keybase-issues#1534]
I tried the website verification several times and it always fails for me, be it using bash & curl or with the keybase tool. Keybase.io replies that it does not find my verification proof here: http://aurelien.bompard.org/keybase.txt, but this file is available using curl on another machine.
Maybe a formatting problem?
I tried using DOS or UNIX line endings, it always fails.

**Comment by zQueal** [comment]
Keybase only supports one subdomain, which is `_keybase.hostname.tld` (I'm pretty sure that's correct). The methodology here is that proving you have access to a subdomain does not prove that you actually own a domain. Keybase is looking for your `keybase.txt` file under `bompard.org/keybase.txt` and `bompard.org/.well-known/keybase.txt` only. If you own the box that it's hosted on, you _may_ be able to get this to work with system links.

If your web hosted directory is `/var/www` and your sub domains are hosted under `/home/{subdomain` you could try:
    sudo ln -s /home/aurelien/keybase.txt /var/www/keybase.txt

I have no idea if this will actually work. If it doesn't it's really not possible based on Keybases' design.

**Comment by abompard** [comment]
Oh OK. I have access to the toplevel domain so it's not going to be a
problem.
Thanks for your explanation, but both the website and the command line
client told me that I should put the file at the root of the subdomain, not
the TLD.

**Comment by abompard** [comment]
Alright, found the issue. Keybase was first looking for .well-known/keybase.txt, which returned a failure (a misconfigured owncloud instance was grabbing all the .well-known subfolder). And since this failed, it did not go look for the keybase.txt file in the root folder.
Fixed that, now it works.
