### ISSUE TITLE
User unknown in virtual alias table

### ISSUE THREAD

**Issue by peterkahl** [keybase/keybase-issues#1544]
There IS a user in your system, but when trying to send mail to your server, it bounces back:
```
Final-Recipient: rfc822; XXXXX@keybase.io
Original-Recipient: rfc822;XXXXX@keybase.io
Action: failed
Status: 5.1.1
Remote-MTA: dns; mail1.keybase.io
Diagnostic-Code: smtp; 550 5.1.1 <madvillain@keybase.io>: Recipient address
    rejected: User unknown in virtual alias table
```

**Comment by malgorithms** [comment]
Yeah, they haven't verified they own the email address to us by clicking a link in their email. We don't do mail forwarding unless they prove ownership of their outside address.

**Comment by peterkahl** [comment]
Oh. Thanks.
