### ISSUE TITLE
Reproducing twitter hash

### ISSUE THREAD

**Issue by jodersky** [keybase/keybase-issues#1546]
Hi,
I'm trying to recreate the hash displayed on twitter from a signed statement using standard unix tools.

The description given [here](https://keybase.io/jodersky/sigs/OpNJk9cvR8uc-OvbONntbUwRaEpVgDIgyujX), says:

> #### Tweet-sized hash
> the first 27 bytes, web safe, of
> base64(SHA-256(binary(contents))) 

So my first attempt was to copy the statement contents into statement.txt and then run

    cat statement.txt | openssl dgst -binary -sha256 | openssl base64 | head -c 27

However, I get a different hash from the one displayed on keybase and twitter. I also tried various combinations of newlines and headers in the statement, however with no success.

Any pointers on the exact procedure to reproduce the hash?

**Comment by zQueal** [comment]
To the best of my knowledge you'd need to implement [TripleSec](https://keybase.io/triplesec) to recreate the hash.

**Comment by maxtaco** [comment]
See [here](https://github.com/keybase/keybase-issues/issues/174) and [here](https://github.com/keybase/keybase-issues/issues/1388)

**Comment by jodersky** [comment]
cat statement.txt | openssl base64 -d | openssl dgst -sha256 | awk '{ print $2 } ' | xxd -r -p | openssl base64 -e
did the trick.
Thanks!
