### ISSUE TITLE
Cannot complete login after failed attempt

### ISSUE THREAD

**Issue by kgleason** [keybase/keybase-issues#1550]
I have a new linux install, and I was attempting to set up keybase. Everything installed relatively smoothly, but when I went to login, I couldn't remember the 2nd passphrase that needs to be entered, so I killed the login.

I since remembered the passphrase, so I attempted to login again. I did my best to clean up beforehand with an `rm -rf .cache/keybase .config/keybase`. Now it hangs at the step shown below:

    kirk@kirk-antergos:~$ keybase login
    warn: No config file found; tried '/home/kirk/.config/keybase/config.json'
    Your keybase username or email: kgleason
    Your keybase login passphrase: 
    Your keybase login passphrase (password cannot be empty):     ****************************************************************************************************
    - run scrypt [==================================] 100%
    info: Made directory '/home/kirk/.cache/keybase'
    info: Updated file: /home/kirk/.cache/keybase/session.json
    info: Made directory '/home/kirk/.config/keybase'
    info: Updated file: /home/kirk/.config/keybase/config.json
    info: Creating temporary keyring dir: /home/kirk/.cache/keybase/tmp_keyrings

I'm not sure where to go from here. Here are the details on the system:

  * Linux 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:24:22 CEST 2015 i686 GNU/Linux
  * npm 2.8.3
  * node v0.12.2
  * keybase 0.7.7
  * gpg (GnuPG) 2.1.3

Please let me know if there is anything else I can provide.

**Comment by maxtaco** [comment]
Can you post some debug info? Run with `keybase login -d`.  Be sure to scrape any sensitive data.  I'm 99% certain that debug logging doesn't show sensitive data, but always pays to make sure. Thanks!

**Comment by kgleason** [comment]
Lots of output.

For the sake of transparency, I did:

  * rm -rf .cache/keybase .config/keybase
  * keybase -d login |& tee keybase_debug

The output is what you will see in my [gist](https://gist.github.com/kgleason/256ddf3387fc019cb998)

**Comment by kgleason** [comment]
FYI, `keybase login -d` doesn't work, for any future readers who may want to try it. The `-d`  needs to be passed to `keybase` prior to the `login` command.

Also for any future readers who may try my commands above, the `|& tee` causes your passphrase to be printed in all of it's glory on your console. The output does not show up in the resulting file. I was admittedly nervous for a second.

**Comment by kgleason** [comment]
Closing this issue. Doubt it is still a problem. Keybase has been working flawless for me for some time. Keep up the great work.
