### ISSUE TITLE
Dribbble account validation

### ISSUE THREAD

**Issue by benlake** [keybase/keybase-issues#1560]
It would be possible to use the Bio field on a Dribbble profile (160 characters) to perform similar account validation/linkage as is done with Twitter. The profiles are publicly accessible: https://dribbble.com/benlake

**Comment by zQueal** [comment]
Added to #518

**Comment by benlake** [comment]
I see you added it, but spelled it "Dribble", not "Dri*bbb*le"; three b's. Thanks!

**Comment by zQueal** [comment]
Well that's embarrassing. Fixed!

**Comment by benlake** [comment]
No worries mate! Thanks.
