### ISSUE TITLE
Tracking multiple users in different tabs at the same time fails

### ISSUE THREAD

**Issue by leto** [keybase/keybase-issues#1565]
I have noticed that if I quickly pop open multiple tabs and then start tracking people, the different requests conflict with each other (during "Generating Signature...") and the subsequent tracking requests will fail with an error about an invalid hash.

**Comment by dtiersch** [comment]
full explanations in #1446 and #1561

**Comment by leto** [comment]
This is tracked elsewhere and is potentially not a supported operation, closing.
