### ISSUE TITLE
https://keybase.io/<user>/key.asc is not CORS-friendly

### ISSUE THREAD

**Issue by vovayartsev** [keybase/keybase-issues#1566]
According to the [docs](https://keybase.io/docs/api/1.0/call/user/key.asc), this API should be CORS-friendly: `https://keybase.io/<user>/key.asc`

However I've got this error when trying this API in the browser:

`XMLHttpRequest cannot load https://keybase.io/vovayartsev/key.asc. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

Here are JS console logs: http://take.ms/tZD5r

**Comment by BlackthornYugen** [comment]
From your screenshot it looks like the request was made with the "OPTIONS" method but the CORS response headers appear to only allow the "GET" method in the "Access-Control-Allow-Methods" header. 

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Allow-Headers: Content-Type, Authorization, Content-Length, X-Requested-With
```

**Comment by vovayartsev** [comment]
Ups... Sorry for confusion . I didn't realise that my implementation (`$http.get` in AngularJS) sends an OPTION request first when debugging on localhost. 

I confirm that when running the similar request using jQuery's `$.get("https://keybase.io/vovayartsev/key.asc")`, the response is OK.

**Comment by vovayartsev** [comment]
More info on this topic for those who have a similar issue: http://stackoverflow.com/questions/12111936/angularjs-performs-an-options-http-request-for-a-cross-origin-resource/12112294#12112294
