### ISSUE TITLE
Why is Keybase.io domiciliated in the Delaware corporate heaven?

### ISSUE THREAD

**Issue by ametaireau** [keybase/keybase-issues#1569]
[The terms of service](https://keybase.io/docs/terms) displayed on the website state that keybase.io is located in the [Delaware](https://en.wikipedia.org/wiki/Delaware) which is considered [a corporate heaven](https://en.wikipedia.org/wiki/Delaware_General_Corporation_Law).

Since Keybase offices are located in San Francisco and NYC, it is legitimate to ask why is the service located in Delaware. Does it bring to the table interesting properties in regard to the privacy of our data?

Without further explanation, it's hard to understand the reason of this choice, since nothing is currently done to bring money to the table, because if I understand it correctly, [there is no current business model](https://github.com/keybase/keybase-issues/issues/788).

**Comment by malgorithms** [comment]
There are a variety of reasons to incorporate, even before having what you call a business model.

As for Delaware, there is nothing specific I'm aware of, in regards to privacy/security law.  

You can Google this for more helpful info than just the Wikipedia page, and find out why companies go for Delaware. Put simply: we'd rather focus on the Keybase software than spend *extra* time and money navigating the corporate laws of a state other than Delaware.
