### ISSUE TITLE
Problem creating a new public key due to ambiguous passphrase.

### ISSUE THREAD

**Issue by sam-falvo** [keybase/keybase-issues#1577]
Tried signing up via an invite, then tried creating a new public key, and was asked to "confirm" my passphrase.  However, I never received one, nor have I taken steps to create one.  No visible indication that I should have, and certainly no obvious way to do so.

**Comment by malgorithms** [comment]
it's required to enter a passphrase during joining. perhaps you used your invite code *as* your passphrase? Here's the bottom half of the signup form, if it rings any bells:

![image](https://cloud.githubusercontent.com/assets/614943/7713045/0764bad4-fe43-11e4-83c9-5e426dbfc384.png)

If that's what you did, and you're still logged in, go to your account page and change it to something else:

https://keybase.io/_/user/account

If that's not it, then (1) logout, and (2) request a password reset at the login screen.

**Comment by sam-falvo** [comment]
Sorry!  I know what I did wrong.  When I looked at that form, I thought it read "passWORD".  I just wasn't paying attention.  Thanks!!

**Comment by malgorithms** [comment]
well, it's possible you saw it somewhere.  there may be places around the site where I accidentally use the word "password"...but mostly we say "passphrase."
