### ISSUE TITLE
Web authentication of domain fails

### ISSUE THREAD

**Issue by martensms** [keybase/keybase-issues#1586]
I have no clue what's wrong. It's available in the web browser, an up-to-date file, can be downloaded via wget, but not working on keybase.io.

Why does this keybase auth not work?
URL is http://lycheejs.org/keybase.txt

**Comment by maxtaco** [comment]
looks like the proof is for https but that page is only available via http

On Mon, May 25, 2015 at 9:01 PM, Christoph Martens <notifications@github.com

**Comment by martensms** [comment]
Well, yeah. Both websites in my profile were http only. Do I need to upgrade now both to serving via https? I didn't change anything for like the last 3 months until this error didn't go away. Never got a notification and never changed it.

So my question is now (I guess): How to do a proof for http?
Even when revoking and recreating a plain new proof, it keeps not working.

**Comment by maxtaco** [comment]
Actually, I take it back, it's not an  https/http issue.  Let me take a look.

**Comment by maxtaco** [comment]
Sorry, the issue is that you've configured your Webserver to send a 404 when our User-Agent tries to visit.  The page loads fine in Chrome or Curl, but sends a 404 when the User-Agent is the npm `request` module.  Here's some node code to see for yourself:

```javascript
var request = require('request')

request('http://lycheejs.org/keybase.txt', function (err, res) {
	console.log(res.statusCode);
})
```

This will echo "404".

**Comment by martensms** [comment]
No, this is still not working. I get an email stating that it was tried to get it, but there was no single request made within the time from your servers.

**Comment by martensms** [comment]
No. This has nothing to do with a 404. Your algorithmetics behind assume some non-standard HTTP behaviour. If I naildown the server to always reply to the URL with the given parameters that your script offers, the reply headers are all HTTP spec conform.

Any source for this request bot? What do you expect in return as headers?
Content-Type is set to "text/plain; charset=utf-8"

Screenshot of returned headers, analyzed by my debugger that sends identical headers as sniffed ones from wireshark: http://i.imgur.com/jdDKsPX.png

Note that HTTP headers are [case-insensitive](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2). As I have no access to the relevant code, the headers sent back are all camelized and parsed (seemingly) by the request library or node http parser implementation (c++ binding) to lowercase.

```bash
dev@c2de:~/Software/request-test$ node index.js 
null 200 2772 { 'e-tag': '"2772-1432601947000"',
  'last-modified': 'Tue, 26 May 2015 00:59:07 GMT',
  'content-control': 'no-transform',
  'content-type': 'text/plain; charset=utf-8',
  expires: 'Tue, 02 Jun 2015 18:31:49 GMT',
  vary: 'Accept-Encoding',
  'content-length': '2772' }
```

```javascript
var request = require('request');

request({
	url: 'http://lycheejs.org/keybase.txt',
	headers: {
		'user-agent': 'keybase-proofs/2.0.23'
	}
}, function(error, response, body) {

	console.log(error, response.statusCode, body.length, response.headers);

});
```

I have also prepared two different wireshark pcap dumps, one for chrome and one for the request library with identical headers as yours. https://www.dropbox.com/sh/df3nzg1yzz4z12w/AABFMf7aWAR8o7xzcuCp2RGPa?dl=0

Please reopen this issue.

**Comment by maxtaco** [comment]
Did you change your server?  Our server is now able to read the posted file and get a 200.  So from our perspective, it looks like you changed something and now it works.

However, the proof that you've posted (`seqno : 15`) is old, since you've generated a new proof (`seqno : 17`) that supersedes it.  Can you update `keybase.txt` to show the new proof? Thanks.

**Comment by martensms** [comment]
I'd suggest to not increment the seqno if the proof is identical.

```
if (proof.isIdentical()) {
// proof.seq++ // Don't do this anymore, nobody will find this out
}
```

I mean, it's pain and will probably be overlooked by anybody using your service. Also, if a seqno increments by trying to fix issues - is never an expected behaviour of any kind of public key laying around in the internet. As you don't offer an automatized API for that (I assume), people like me just don't care anymore and are too lazy to upload the identical key with a new sequence number every time the service fails.
