### ISSUE TITLE
User suggestions overflow their container div ("twitter-interests-bar")

### ISSUE THREAD

**Issue by pkirkovsky** [keybase/keybase-issues#1600]
![screen shot 2015-05-28 at 12 36 45 am](https://cloud.githubusercontent.com/assets/8731045/7854867/0396e1f8-04d2-11e5-950b-4331053370bd.png)
![screen shot 2015-05-28 at 12 36 30 am](https://cloud.githubusercontent.com/assets/8731045/7854869/03b94b62-04d2-11e5-8426-246ec662453e.png)
![screen shot 2015-05-28 at 12 35 44 am](https://cloud.githubusercontent.com/assets/8731045/7854868/03b6f1f0-04d2-11e5-9030-72c5f4b0c396.png)

**Comment by malgorithms** [comment]
q's: (1) are you seeing 5 people in the bar, or some other number? (2) does it happen at all window sizes or certain ones?

For question 2, it might be helpful if you tell me what classes you're seeing on the grid:
```
# note the "grid-monitor" also has "lg" for large; this class changes when you resize the window
> $('.grid-monitor')
[<div class=​"grid-monitor grid-monitor-lg">​…​</div>​]
```

**Comment by pkirkovsky** [comment]
I see 10 suggestions in the top bar, either as "Surf Keybase" when logged out or "Consider Tracking" when logged in. It happens in all window sizes, but it's worse at smaller ones (and also depends on the length of usernames shown). Issue appears in Firefox, Chrome, and Safari.

Grid is `grid-monitor grid-monitor-lg`
Resolution is 1920x1200, but the site still requires horizontal scrolling.

![screen shot 2015-05-28 at 1 39 01 pm](https://cloud.githubusercontent.com/assets/8731045/7870869/eb766b42-0540-11e5-80a6-494e15afed34.png)
![screen shot 2015-05-28 at 1 39 05 pm](https://cloud.githubusercontent.com/assets/8731045/7870872/eb7a0928-0540-11e5-9633-3948c2c12295.png)
![screen shot 2015-05-28 at 1 39 09 pm](https://cloud.githubusercontent.com/assets/8731045/7870870/eb77f61a-0540-11e5-8bef-348992d6d754.png)
![screen shot 2015-05-28 at 1 39 13 pm](https://cloud.githubusercontent.com/assets/8731045/7870871/eb78358a-0540-11e5-9030-ddaa0fe46e28.png)

**Comment by malgorithms** [comment]
thanks!
