### ISSUE TITLE
segmentation fault using dns proof

### ISSUE THREAD

**Issue by aeonblue3** [keybase/keybase-issues#1607]
Hello!
When I do keybase id on myself (```keybase id cneitzer```), I get a ```Segmentation Fault: 11 ```.

The proof succeeded and shows up as good when I log in to keybase.io.

This is the output from debug mode.
```
warn: gpg: Signature made Mon Jun  1 11:47:57 2015 EDT using RSA key ID 3C52ED9D
warn: gpg: Good signature from "Chris Neitzer <chris@neitzer.com>" [ultimate]
debug: ------ Quarantined / oneshot verify -> ok! (fp=17B0207BF563D8A459771E676CF0B32F3C52ED9D)
debug: ----- GpgKey::verify_sig cneitzer@dns -> null
debug: |||| remote service desc is {"domain":"chrisneitzer.com","protocol":"dns"}
debug: +++++ Calling into scraper -> {"domain":"chrisneitzer.com","protocol":"dns"}@dns -> dns://chrisneitzer.com
debug: ++++++ DNS check for chrisneitzer.com
Segmentation fault: 11
```

I am using node version 0.12.4, if it helps.

Thanks!

**Comment by maxtaco** [comment]
The DNS txt resolver in broken in your version of node, unfortunately. The last time I looked, it was fixed in io.js but node seems to be slow to fixing it.  Thanks for your feedback.

**Comment by aeonblue3** [comment]
Thanks, good to know!

**Comment by maxtaco** [comment]
Here's the issue BTW: https://github.com/joyent/node/issues/9285
