### ISSUE TITLE
Twitter proof has failed twice for @cpbotha

### ISSUE THREAD

**Issue by cpbotha** [keybase/keybase-issues#1609]
I'm using the keybase command line utility on OSX 10.10.3 to try to prove my twitter identity. So far it has failed twice.

Last night (my time) I posted this: https://twitter.com/cpbotha/status/605488764484468736

I tried again this morning (replacing the previous proof): https://twitter.com/cpbotha/status/605636982958649344

Why can keybase not see my proof?

**Comment by maxtaco** [comment]
Left out "verifying myself"

**Comment by cpbotha** [comment]
Wow, now that's embarrassing! Somehow I managed to start copy and pasting from the keybase tool output *after* the "verifying myself:".

Thank you very much for the help! I feel all verified!
