### ISSUE TITLE
After deleting proofs its not possible to re-prove, fails with "error: A live proof for ... already exists (error #230)"

### ISSUE THREAD

**Issue by thinkberg** [keybase/keybase-issues#1613]
Even saying yes to keybase prove web .... questions for overwriting doesn't help.

**Comment by maxtaco** [comment]
Try `keybase list-signatures` and then `keybase revoke <sig-id>`

**Comment by thinkberg** [comment]
it turned out to only happen on web signatures. I revoked and added new.
