### ISSUE TITLE
Reddit won't verify

### ISSUE THREAD

**Issue by ThomasdenH** [keybase/keybase-issues#1630]
I think it is an issue to do with capital letters in my user name, but my Reddit account won't verify.

My Keybase: https://keybase.io/thomasdh
My Reddit: https://www.reddit.com/r/KeybaseProofs/comments/38xp8i/my_keybase_proof_redditthomasdh_keybasethomasdh/

**Comment by politicalcustard** [comment]
I have the same problem, but I don't have any caps in my Reddit u/n.

https://keybase.io/politicalcustard
https://www.reddit.com/r/KeybaseProofs/comments/39shqj/my_keybase_proof_redditpoliticalcustard/

**Comment by ThomasdenH** [comment]
My account has been verified since.
