### ISSUE TITLE
Some warning/documentation about gpg1 and gpg2 not sharing a secret keyring

### ISSUE THREAD

**Issue by wjt** [keybase/keybase-issues#1639]
I created a new 4096-bit key to replace my old 1024-bit key (using `gpg` by hand, because I am a luddite). When I came to try to push my new key to Keybase, I couldn't: `keybase push` could only see my old key (which I still have in my secret keyring of course), and `keybase push NEWKEYID` complained that GPG can't find the secret part of the key.

I pulled out a lot of hair before noticing that keybase uses `gpg2`, while I had used `gpg` 1.x to create the new key. Apparently gpg2 does a [one time import](https://www.gnupg.org/faq/whats-new-in-2.1.html#nosecring) of secret keys from the separate location used by gpg1; since I created the new key after that migration, gpg2 (and by extension keybase) could not see it.

I don't know if this is a common issue, but if so it might be nice to document it.

**Comment by steko** [comment]
Yes, I confirm that this is indeed a source of confusion and that documentation would help. As I understand it, keybase is entirely based on gpg 1.x.

Also, did you really mean

> gpg2 (and by extension keybase) could not see it.

or

> gpg (and by extension keybase) could not see it.

?

**Comment by wjt** [comment]
Back when I debugged this, I thought I found that keybase used `gpg2` not `gpg`. But it's possible that I had the whole bug report backwards and used `gpg2` by hand.

**Comment by steko** [comment]
On the other hand, [this comment](https://github.com/keybase/keybase-issues/issues/1968#issuecomment-174272101) seems to imply that `gpg` is used, since a broken `secring.gpg` is the culprit and `gpg2` doesn't use that file, but that's just my understanding.

**Comment by wjt** [comment]
Well, the client has been rewritten since I filed this bug (I was using the Node client back then) so who knows whether the behaviour is the same.
