### ISSUE TITLE
error: Unexpected token <SOH>

### ISSUE THREAD

**Issue by kyrias** [keybase/keybase-issues#1643]
I just installed keybase on my new OS install, and after running a login I get

    error: Unexpected token <SOH>

from every command, where `<SOH>` is the ASCII 1 character.

Debug log:
```
debug: + KeyPull::run
debug: ++ KeyPull::load_user
debug: +++ johannes: load user
debug: ++++ johannes: load user from local storage
debug: ---- johannes: loaded user from local storage -> DecodeError: Unexpected token  / undefined
error: Unexpected token 
```

**Comment by maxtaco** [comment]
Hmm, never seen that one before.  If you delete your local cache database, does the problem recur?  Try:

```bash
rm -rf ~/.local/share/keybase/keybase.idb
```

**Comment by kyrias** [comment]
Ah, didn't know about that, yeah that worked. Wonder if some file in there got corrupted.
