### ISSUE TITLE
Can't encrypt to self without copy of secret key

### ISSUE THREAD

**Issue by RyanMarcus** [keybase/keybase-issues#1651]
I did my best to search for duplicates. I'm fairly sure this hasn't been reported.

Encryption to self fails from CLI when you don't have a copy of your private key. Steps to reproduce:

    > brew install keybase # not sure if this is officially supported or even a good idea...
    > keybase login 
    > keybase encrypt -m "test" rmarcus # use your username instead of rmarcus
    error: You don't have a local secret key!

I can encrypt to other people, just not to myself. Sometime next week I'll attempt to reproduce this on a fresh Arch VM and provide more detailed logs.

**Comment by pkirkovsky** [comment]
My secret keys are stored on Yubikey Neo so they are unavailable unless the card is present. This should lead to the same error that you're seeing, but I can't reproduce it.
I performed the following without the card plugged in (as evidenced by the ``No secret key`` error):

```
$ keybase encrypt -m "test" pkirkovsky > self_encrypt_test.txt
$ cat self_encrypt_test.txt
-----BEGIN PGP MESSAGE-----

hQEMA5yxi2t+ShrDAQf/fGIppfnboI52MAxNRl/6M6sPyjo8it5aK8c4scag/h3h
jNlE21XSttXEQHV7PbbGZnCyZN+V8yvOBDYWx5pytBiptUIfYHy14mZ9uPWF28O9
wDRmjABCSlZUS3Ubld/H98iE+4EY6YCn38A8diuZTwBEtsvsQiLxh7RX+sFkQMdX
d7+glpPqM+GSvvaH/iovUrPUAve1gQCB8L4S+zgIOqymJcQ6FjzTcYM0VUfMft4A
AlAD2S4mSIKBx4z1uLe52jLEQ1zKoIghINHgY/0fO6Zy1q0vmrlzQ3mKXhQV8heW
uVMBfidwSbmGekSF0Sxwi0mOivQgMGme/nQS7hop3dI/AT8FT1qQXLig8JZ2vI7m
G9rlrMHxcnOVlD/r3zpZ56vFKodex1U2mopwFxSpZ4kcsoIDkBD8zjUz0yAEYeoe
=eaMp
-----END PGP MESSAGE-----
$ cat self_encrypt_test.txt | gpg --list-packets
:pubkey enc packet: version 3, algo 1, keyid 9CB18B6B7E4A1AC3
	data: [2047 bits]
gpg: selecting openpgp failed: Card error
:encrypted data packet:
	length: 63
	mdc_method: 2
gpg: encrypted with 2048-bit RSA key, ID 0x9CB18B6B7E4A1AC3, created 2015-05-31
      "Pavel Kirkovsky <pavel@kirkovsky.com>"
gpg: public key decryption failed: Card error
gpg: decryption failed: No secret key
```
After inserting the card I can decrypt the ciphertext:
```
$ cat self_encrypt_test.txt | gpg
gpg: encrypted with 2048-bit RSA key, ID 0x9CB18B6B7E4A1AC3, created 2015-05-31
      "Pavel Kirkovsky <pavel@kirkovsky.com>"
test
$
```

>brew install keybase # not sure if this is officially supported or even a good idea...

If you installed recently, the version available through Homebrew should be the latest one:
```
$ keybase --version
0.8.22
$ brew info keybase
keybase: stable 0.8.22, HEAD
```
However your best bet is to use the native installer (`npm install -g keybase-installer`) and use it to keep keybase up to date.

**Comment by zQueal** [comment]
Not really sure if this is a bug. If anything, you're simply not meeting the requirements to decrypt an encrypted message. All software involved __needs__ your key to be able to decrypt.

To fix this via Keybase (assuming you've uploaded your private key to Keybase) you can simply `keybase pull` if you haven't uploaded your private key to Keybase it will only pull what it has (your public key) and you will still be unable to decrypt your message.

**Comment by pkirkovsky** [comment]
>All software involved needs your key to be able to decrypt.

@RyanMarcus is trying to encrypt, not decrypt. I think this is a bug similar to #693

**Comment by zQueal** [comment]
> is trying to encrypt, not decrypt. 

I'm really off the ball today. Thanks for noticing.

**Comment by RyanMarcus** [comment]
I can confirm that in `keybase version 1.0.16`, I can now encrypt to myself without *unlocking* my private key via:

```
keybase pgp encrypt -m "test" rmarcus
```

With a fresh keybase install that I've logged in with, I can also do a PGP encrypt to myself without a password.

However, if I just do plain `keybase encrypt -m "test" rmarcus`, I am prompted to unlock my "device key". Back when Keybase just made using GPG easier, I knew what was going on. Now I've got to do a lot of reading (and mostly of source code -- I can't find any technical documentation on what's going on) about device keys and the encryption model to know if this is an error.

**Why do I need to unlock my device key to encrypt a message to myself?**

**Comment by maxtaco** [comment]
I am Afk and forget: are we signing the message by default? If so then we
need your private key to sign your message.

**Comment by maxtaco** [comment]
Oh, so we're not signing by default.  This might be a regression, let me look into it.

**Comment by maxtaco** [comment]
What if you do a `keybase logout` and then try the same?

My guess is in that case, it won't prompt you.  My further guess is that you started in a state in which you still want to be "logged in" to keybase, but your secret keys are locked.  The default for `keybase encrypt` is that if you are logged in, we want your encryption to be authenticated, which in Diffie-Hellman, requires your private key.  Think of this as something like encrypt+sign in GPG, but better.

If you're logged all the way out, we'll fallback to "anonymous sender mode" in which we'll generate a one-time random public/private key pair and use that.  In this case the receiver won't be able to authenticate the sender, but private is still preserved.

There's a lot going on here, sorry for any confusion!

**Comment by RyanMarcus** [comment]
If I do a `keybase logout`, I can indeed encrypt to users via `keybase encrypt rmarcus` (for example) without unlocking any kind of key.

I'm familiar(ish) with the Diffie-Hellman algorithm for establishing a shared secret between two parties using a few back-and-forths. Is there anything I can read to learn about the non-PGP algorithms that keybase is using?

From my possibly old-hat understanding, **encrypt and sign seems like a very dangerous default**. "Make it so only this person can read this message" and (assuming you sign and then encrypt ) "give this person an irrevocable proof that I sent them an encrypted message" are very different things!

**Comment by RyanMarcus** [comment]
Since "encrypt + sign" seems to be the default, I now understand why `keybase encrypt` requires my key, although I think this is a crazy default.

**Comment by maxtaco** [comment]
https://saltpack.org for our new encryption system (without PGP).

**Comment by maxtaco** [comment]
Agreed 100% about "encrypt and sign" being dangerous. Saltpack does the right thing here which is repudiable signing, so it's OK to have it on by default.

**Comment by RyanMarcus** [comment]
Ah! A little knowledge goes a long way. I just learned that the saltpack "authentication" isn't really a signature, in that once you decrypt a message you can verify it's authenticity, but you've also demonstrated the ability to create arbitrary messages with that same "authentication". I believe this is what is meant by "repudiable signing."

**Comment by maxtaco** [comment]
👍 !!
