### ISSUE TITLE
error: invalid sibkey

### ISSUE THREAD

**Issue by rillian** [keybase/keybase-issues#1653]
I installed keybase on a linux system which already had my gpg key on it, but it fails talking to the server with ```error: invalid sibkey```. So I can login, but not track, etc.

I don't know what a sibkey is, but gpg has been working fine on that machine.

This is a Fedora 22 system, after (from memory)
```bash
sudo yum install npm
sudo npm install -g keybase-installer
keybase-installer --prefix=$HOME/.local
```

**Comment by oconnor663** [comment]
"Sibkeys" is short for "sibling keys", which is the future of how Keybase is going to work. You'll have a separate key for each device that's logged in as you, which are all tied to the same identity. We just rolled out some code for handling this in the Node client, and it looks like you've found a bug in it.

I'm able to repro it with `keybase id rillian`, so hopefully I can figure out what's happening real quick...

**Comment by rillian** [comment]
yay bug! :)

**Comment by oconnor663** [comment]
Ok, it looks like the issue is how some of our new code figures out PGP key expiration times. Your key has a...large number of signature packets :) Some of those have already expired, and we were being too conservative and calling the whole key expired. Fix out shortly.

**Comment by oconnor663** [comment]
Just pushed version 0.8.4. See if rerunning `keybase-installer` fixes everything for you.
