### ISSUE TITLE
Error, Bad UID

### ISSUE THREAD

**Issue by Mitchou** [keybase/keybase-issues#1655]
Hi all,

I don't why, but I did all the install procedure and it didn't work
error: bad UID: e1a7f3c597848c6b6563f2dd48f1d019 != 6027f000d1690e425f2e34a7390e0419 for username antoinemichard

Try several times, no luck :(

Debian 8.1
Gpg 2.0.27

**Comment by maxtaco** [comment]
What's your username? What sequence of steps did you take?

Thanks, and sorry for the bug...

**Comment by maxtaco** [comment]
And did you capitalize your name in anyway?  Sorry about this bug...

**Comment by maxtaco** [comment]
Hmm, looks like you signed up with the camel-case "AntoineMichard"..  Take a look....

**Comment by Mitchou** [comment]
I can't see it... But maybe you're right. Sooo, what can I do ?

**Comment by maxtaco** [comment]
Should be closed in v0.8.7.  Reopen if not.  Thanks.
