### ISSUE TITLE
Some icons don't show up in Safari

### ISSUE THREAD

**Issue by yegortimoshenko** [keybase/keybase-issues#1657]
Reddit and Twitter icons don't show up in Safari.

Compare Safari rendering:

![Safari screenshot](https://cloud.githubusercontent.com/assets/1643293/8519811/6ea55546-23e6-11e5-91ad-788f68cd756c.png)

to Firefox rendering:

![Firefox screenshot](https://cloud.githubusercontent.com/assets/1643293/8519823/8455c4ca-23e6-11e5-9314-3f844d864f60.png)

**Comment by zQueal** [comment]
I had this issue in chrome a while back. Turns out Privacy Badger was blocking them from loading for whatever reason. Check your extensions to make sure they aren't blocking them from loading.

**Comment by yegortimoshenko** [comment]
Wow, thanks a bundle @zQueal! It was Fanboy's Annoyances filter list in AdBlock.
After I've turned it off, the icons are back.
