### ISSUE TITLE
Coinbase proofs broken and not able to revalidate

### ISSUE THREAD

**Issue by jeremydk** [keybase/keybase-issues#1658]
Got an email notification that my coinbase proof has broken.  I've directly verified that the coinbase page is still displaying my proof, and everything matches.

Is the coinbase scraper having issues currently?

**Comment by karanlyons** [comment]
Coinbase’s site, at least on my end, seems to be having some pretty bad loading issues right now, which could be the cause.

**Comment by dgcoffman** [comment]
I can't verify my coinbase account right now even though the page loads instantly and shows correct data: https://www.coinbase.com/coffman/public-key

**Comment by karanlyons** [comment]
There also seems to be a difference between https://www.coinbase.com/username and https://coinbase.com/username, and keybase seems to be currently checking the latter, which doesn’t redirect to www.* but just returns no response.

**Comment by oconnor663** [comment]
Coinbase had a CloudFlare-related outage today, which probably caused all this: https://blog.cloudflare.com/the-internet-is-a-cooperative-system-dns-outage-of-6-july-2015/

**Comment by oconnor663** [comment]
@dgcoffman I'm able to `keybase id` you just fine right now. I'm also getting a good redirect from the non-www https://coinbase.com/coffman/public-key. @maxtaco, will the server just fix everything on its own now that Coinbase is back up?

**Comment by karanlyons** [comment]
If it’s DNS issues (which it appears to be?) I’d wager we’re just going to have to wait for the bade caches to expire.

**Comment by bbbbanjax** [comment]
it does appear to be a dns propagation issue. should be working again soon. I got the same broken proof email.

**Comment by fastest963** [comment]
I'm trying to prove Coinbase now and I just keep getting:
```
Check coinbase again now? [y/n] y
warn: Didn't find the posted proof.
```

**Comment by maxtaco** [comment]
Sorry for the bug all!  We had a busted DNS entry cached in our local DNS server, which hosed everyone proofs.  I've since cleared the DNS cache and reran everyone's broken proofs.  No further actions are needed.  Thanks for the bug report!
