### ISSUE TITLE
Don't use unique keybase usernames as identifiers

### ISSUE THREAD

**Issue by tildelowengrimm** [keybase/keybase-issues#166]
As y'all know, the biggest problem with using public-key crypto (like GPG) is knowing that a particular key _really_ belongs to who it says it belongs to. That's the problem Keybase is working to mitigate.

With Keybase's design, it looks like every user gets a unique username. Others identify them by this username, the user identifies themselves with this username when authenticating to Keybase, and so on. This is a dangerous way to play, and a way to introduce problems.
## Why this is a problem

By handing out unique human-readable names to people, you've made Keybase into an authority on names. This function can't be redundant or distributed, and everyone needs to rely on Keybase not to mess up, or be a jerk, or get attacked, or so on. 

You've basically taken one thing that folks _can't_ independently verify, and made it a critical function of the system. Now all kinds of clients can get tripped up if you change a name, or if someone changes a name for you, or if an account gets compromised, or if you lose your passwords database and didn't use enough scrypt, or…
## What to do instead

There already exists an unique identifier for each user: the fingerprint of their GPG master key. This is the identifier that should be used for user accounts, not an unique and memorable username. It's not memorable, but you literally cannot have it both ways because of [Zooko's triangle](https://en.wikipedia.org/wiki/Zooko%27s_triangle).

User profiles shouldn't be `https://keybase.io/<username>`, they should be `https://keybase.io/<gpg-fingerprint>`. When users want to edit their account info, they shouldn't have to log in or authenticate with a secret known only to Keybase. Instead, they can just use their GPG key.

If someone wants to update their profile on Keybase, they can just update the GPG subpacket (issue #165) with that metadata and upload it to Keybase. Keybase verifies that the information is indeed correctly signed, and displays it. Everyone else can verify this for themselves.
## How to use nicknames

Nicknames are fine; there's no reason not to use them, just don't force them to be unique and use them as primary identifiers. When someone identifies themself as `maria` or `max`, there's no problem with putting that on their profile and letting others find them by that name. Just don't expect or force uniqueness.

If another user searches for `maria` they should find _all_ the people who think their own name is `maria`, and be able to pick the one which corresponds to the Maria then know and love by checking that the constellation of social media accounts is the same as for their beloved Maria.

**Comment by JEM-Mosig** [comment]
I created a discussion on Kialo to make the arguments more transparent: https://www.kialo.com/should-keybase-team-names-be-locked-29494
