### ISSUE TITLE
Autocomplete API: nbits and algo missing

### ISSUE THREAD

**Issue by dschuermann** [keybase/keybase-issues#1661]
OpenKeychain's keybase search is currently not working: https://github.com/open-keychain/open-keychain/issues/1361

Looks like automcomplete currently misses nbits and algo.
Please compare an old result such as the one from https://github.com/keybase/keybase-issues/issues/1029 with https://keybase.io/_/api/1.0/user/autocomplete.json?q=dominik

**Comment by malgorithms** [comment]
this bug is fixed - thanks for reporting!

**Comment by dschuermann** [comment]
:+1:
