### ISSUE TITLE
TXT at apex is ugly

### ISSUE THREAD

**Issue by weaselp** [keybase/keybase-issues#1663]
requiring a DNS record at the zone apex is not pretty, in particular since you don't just need it short-term but want users to keep it around.

Maybe allow having the record at a label like _keybase.example.com or some other prefix in example.com as an alternative.

**Comment by maxtaco** [comment]
this already works.

**Comment by weaselp** [comment]
Then there is no indication of that in the web UI.  It tells me to add the entry at the zone apex.

**Comment by chigh** [comment]
Yeah, this issue, https://github.com/keybase/keybase-issues/issues/750, isn't documented on the main web UI.
