### ISSUE TITLE
Keybase is down

### ISSUE THREAD

**Issue by yegortimoshenko** [keybase/keybase-issues#1667]
![screen shot 2015-07-13 at 04 53 56](https://cloud.githubusercontent.com/assets/1643293/8640967/433bcc5c-291b-11e5-9aa9-b7dbe9beacdd.png)

As of Mon Jul 13 00:54:50 UTC 2015. Would be nice to have http://status.keybase.io.

**Comment by zQueal** [comment]
Either it was a momentary issue and it's back up, or it could have been on your end of the spectrum. Either way, it seems that it's back online now.

![widhiwb](https://cloud.githubusercontent.com/assets/239193/8641824/d386211e-28e8-11e5-946d-f4aa8e350222.png)

`status.keybase.io` would be awesome.

**Comment by yegortimoshenko** [comment]
Sure, it was momentary. Their nginx was returning 5xx error codes, so the error was on their side.

**Comment by maxtaco** [comment]
email me, i can tell you what was going on.  max@keybase.io
