### ISSUE TITLE
reddit misverification

### ISSUE THREAD

**Issue by coderwill** [keybase/keybase-issues#1668]
hello, i tried to post to the subreddit on two different occasions, however both times verification failed.

**Comment by zQueal** [comment]
Could you post the verification threads?

**Comment by coderwill** [comment]
Sure, most recent: https://www.reddit.com/r/KeybaseProofs/comments/3d6u7z/my_keybase_proof_redditcoderwill_keybasecoderwill/

And initial:
https://www.reddit.com/r/KeybaseProofs/comments/3d6sp8/my_keybase_proof_redditcoderwill_keybasecoderwill/

**Comment by dtiersch** [comment]
Sorry, you"re shadowbanned. This means that only you can see your posts, but nobody else.
(You can verify this yourself by logging out and trying to acces [your user page](https://www.reddit.com/user/coderwill))

**Comment by coderwill** [comment]
Ah! Interesting, thanks for the insight, @dtiersch - guess I'll have to look into why that is.
