### ISSUE TITLE
proof request: airbnb

### ISSUE THREAD

**Issue by privong** [keybase/keybase-issues#1669]
It might be useful for people to prove ownership of airbnb accounts. I suspect his could operate in a similar fashion to the HN proof, with a short bit inserted into the "Describe yourself" section of the profile.

However, I gather there is not a public API, so I guess it would need to be verified using web scraping and that might be fragile.

**Comment by pfarikrispy** [comment]
Since airbnb already verifies many ID forms, couldn't you just piggyback on that and somehow import their cerfication? Ie look for their "proof accepted" or "verified ID" marker?

**Comment by zQueal** [comment]
A note on this;

this is a pretty valid usage of PGP, IMO. While Airbnb does their own verification, you're required to trust that they're using due diligence. With PGP you don't.

Pretty spot on use case for PGP if I ever saw one.

**Comment by privong** [comment]
@zQueal Agreed. I'm happy to reopen it (or have someone else reopen) if there's a possibility of this being implemented. I figured 2.5 years without a even a comment was a sign though.
