### ISSUE TITLE
Move font hosting off Google

### ISSUE THREAD

**Issue by malgorithms** [keybase/keybase-issues#1672]
As discussed on HN:

https://news.ycombinator.com/item?id=9891705

While we don't trust Google JS, we shouldn't need them to host other resources..

**Comment by zQueal** [comment]
Congratulations on Series A funding!

> Keybase is the wrong way to do a PKI directory.

Glad to know there are still those drinking the Haterade. 

As for Google hosting the web fonts--I don't claim to be an expert in all things tech, but this seems to me a case where Keybase would benefit from hosting these files directly, correct? Or is it the library itself that you have the issue with?

**Comment by malgorithms** [comment]
I have to review how it works, exactly. I don't really know how fonts are delivered, so it'll take some exploration. With Google fonts you just drop in their CSS and it works, but embedded in there are font URL's too.

**Comment by malgorithms** [comment]
this is done.
