### ISSUE TITLE
Want to change username

### ISSUE THREAD

**Issue by jorge-3** [keybase/keybase-issues#1673]
And I know it can't be done for various reasons. However, I'd really appreciate if you can send me an invitation code and close my existing one. Thanks and congrats on the funding!

**Comment by zQueal** [comment]
Change your current account's primary email to something other than your primary email address. Then post here with your primary email address ([encrypt it!](https://keybase.io/encrypt#zqueal)\) and I should be able to send you a new invite. Then just simply remove your old account through the options.

**Comment by jorge-3** [comment]
Thanks zQueal, here you go:

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.20
Comment: https://keybase.io/crypto

wcFMA7HaVty3PoUWAQ/9GexbNmWfsYgzxwMEKQYnnpLBjH15hR5QmcGI2kVVMKNT
G/zi3QYU8lFMM+WvRS3RVzwdpTztN1jgtbO9kGDXf3+sVIl1TfDF0qDEfIthnjqS
KlnS4YOR8ve5ceeSGW7WJIgIzTJdB3t6tXFYNuI+SY46V89p0pbzqoumo/oDGvAq
Koe0RgxqfXcFpbssR0r1IcySOCwxggDjo8lCptbU6Xh1QL2jBAp7Imkbf8+OXXe0
nNMAifl+pdfq/hwXcxr6SMXS//imE1QE4l3/kKhvK2YzE9Mm11/yP5uiREkik7CO
8kEILdUnvW5cZLNcRR9Wh/7IN/KpoI0h17LXc14mfiKZIaxBF/y2xQszwWORideC
RBcOZIC061b0987sNtf72r5UD4yomnxU01xgbtvt9+mIdka3PNOab/JTtYCXC+zH
ckn4gaQcoPT3XL3WRd6+BsaTcSFm4aFUUCJRR1HIlrtE8KM+kd1O9HDFJIEFNKr7
qVnTNXeMd0tesmcoFbwMngHFM+7EUfkt+GvJZU7sIn0hpVrSwMeQ2empejPmuKZy
mE9gIHPhgoMGS3ca3RBt9qlgouX0wnjpriupJzpK0gEH4TPjpZnDIMo1s0NEO3qs
LspmXRikMug5hFD7aOd9U81N9/PAvKLXUoan4r6upJ7aApoeKW+KcFUXL/plBBPB
wEsDcwxlChMgNhoBB/d5jrnL2NAsAcN7cWMvofoGj0ej2Heoh2HOPb0PL1zYenJa
Nyty0YJ5QJHDAFwslm1POwJV8Kn+rnHkc+LszmoPi2Qtwrr7i2o9b4dfR43qBp5m
e74y4HKQJKeebbvSu6IJvilvpnUCOaQpDRnH/LnOzLOhWvBLfumezn/fVhfBcFXw
qYndd/bhNPTGbg5Ji2itrf7/8SGT3GhNwTfXBu7Bj0110q/EVX9SER3dNA+wPOOQ
VvxArpxsTSBt1LBq4fCEa3tldAqsGgEjbXZbcfympmICzcg3ARQy3CEt8mVy3D8X
Qq0KdxfQOfK04NkzXZau/KOfkosFMhCxwNW5xGvSwLoBHUC/6l6AJNwW/0YFWr2g
i2lg2vrrn8Ote28d23IaPYgbbbOeDRF0qjTQLg6b1RPrVTFt+9vjStP6hK1wVcuV
VpLjC/33mQsA989XgucesO+fgIv5vSNYBNMMJsqIIVYLWu5Yd7Qd3Dfz3SIxhrYX
gv9RNf7tBLlL/QzcyIQ+A2gwzaJjK6lDsuIs7323ATYyItJ+HFqgxN0MMSK/FMZN
dZXIfU6fVH3+tJHmbI27bdLsGpT0zPA4oFmvYMJ6urEQ6m8F/2KHAf5JVlq3yWso
biHRZ53xnbZ5vBSZkKAriUoXM5uaU546jmo7v9X5a7l5OrYSuWTyKcGZfhjDrH9G
Xn94xXxRMdINfGyO238R6ofztR/bgic1sGS/1bTHbxgIWdha7UpfYGJzbJmsYzCj
rVlgV5wM7pR2vZVmyCi8gxLLCkfceHhVVHiQCRIPtS294xN1ZC8Z+cUvyM43CPDi
Pa3MCAGEOoxC1NogVyt4XJUJMx7PP74JZo0=
=vT65
-----END PGP MESSAGE-----

**Comment by zQueal** [comment]
OK. Assuming your mail server is setup to accept proxy emails you should be all set. If not, send me your PGP key and I'll post the direct hash for you to register here via encryption.

**Comment by jorge-3** [comment]
All set. Thanks for your help!
