### ISSUE TITLE
Logo sends the wrong message

### ISSUE THREAD

**Issue by PaulMakepeace** [keybase/keybase-issues#1676]
I feel that your logo of a shifty character with turned up lapels & thick rimmed glasses reminiscent of a P.I. or spy works against the idea that public key cryptography is the purview of, and accessible to, anyone, not just the shady and sketchy, something that's dogged cryptography and hindered at some (psychological) level its wider adoption.

The front page illustrations however do a great job of that.

**Comment by zQueal** [comment]
This has already been extensively discussed. Although I'm not sure if others have put it quite as delicately as yourself. Simple fact of the matter--the current logo is a placeholder. 

Lets not forget that the software is still in alpha and only as of today received series a funding....

**Comment by tehbmar** [comment]
While looking for a KeyBase.io SVG logo I came across this discussion and noticed that it took place almost a year ago.

I agree with the idea that the KeyBase.io character being a shifty weasel(?) isn't helping the image of cryptography and what it could be used for, but it really does seem like the logo has stuck.

Has KeyBase or a16z put anymore thought into a possible logo update?

**Comment by oconnor663** [comment]
Internally the "sneaky dog" interpretation remains strong, but "thieving ferret" is gaining a lot of ground...

We promise we'll get to this eventually, even if you're reading this thread in 2017 and we still haven't.

**Comment by malgorithms** [comment]
every day there's precisely a 1-in-250 chance we change the logo that day.

**Comment by cptroot** [comment]
I noticed the logo in the mac app changed recently to a key hairpin. What inspired the change?

**Comment by Quentin-M** [comment]
The logo changed everywhere: twitter, website, macOS icon.. 👍

**Comment by cjb** [comment]
@cptroot The d250 die that @malgorithms mentioned above finally rolled a 250.  :)

I wasn't involved in the change, but the comments in the description for this bug seemed very reasonable to me.
