### ISSUE TITLE
Update to install instructions

### ISSUE THREAD

**Issue by pianowow** [keybase/keybase-issues#1681]
It would be useful to add that npm should be updated after node is installed and before installing keybase. I had to figure that out when the "npm install -g keybse-installer" failed at first. I recommend adding "npm install npm -g" before that command in the install instructions.

**Comment by oconnor663** [comment]
Could you please add some details about what versions of node/npm you had initially? I've never run into that problem myself.

**Comment by pianowow** [comment]
This is what I did (copied from command window).  I hope the versions here are helpful.

C:\Users\Irwin>npm

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, upgrade,
    v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Irwin\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.11.3 C:\Program Files\nodejs\node_modules\npm

C:\Users\Irwin>npm install -g keybse-installer
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "keybse-installer"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 Not Found: keybse-installer
npm ERR! 404
npm ERR! 404 'keybse-installer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Irwin\npm-debug.log

C:\Users\Irwin>npm install npm -g
C:\Users\Irwin\AppData\Roaming\npm\npm -> C:\Users\Irwin\AppData\Roaming\npm\nod
e_modules\npm\bin\npm-cli.js
npm@2.13.0 C:\Users\Irwin\AppData\Roaming\npm\node_modules\npm

C:\Users\Irwin>npm install -g keybase-installer
C:\Users\Irwin\AppData\Roaming\npm\keybase-installer -> C:\Users\Irwin\AppData\R
oaming\npm\node_modules\keybase-installer\bin\main.js
keybase-installer@1.0.2 C:\Users\Irwin\AppData\Roaming\npm\node_modules\keybase-
installer

C:\Users\Irwin>keybase-installer
info: Made temporary directory: C:\Users\Irwin\AppData\Local\Temp\keybase_instal
l_j8Yg41nDse8_gLc29Y7Jjw
info: Creating permanent keyring dir: C:\Users\Irwin\AppData\Roaming\.keybase-in
staller\keyring
warn: No code-signing key (code@keybase.io) in GPG keychain
info: Fetching URL https://dist.keybase.io/sig/files/1/keyset.json
info: Installing keyset version 1
info: Using keyset version v1
info: Fetching URL https://dist.keybase.io/sig/files/1/index.asc
info: Fetching URL https://dist.keybase.io/pkg/stable
Download /pkg/files/keybase-0.8.9.tgz [=========================================
========] 100% 0.0s (4189552 bytes total)
info: Fetching URL https://dist.keybase.io/sig/files/1/keybase-0.8.9.tgz.asc
info: verified signature of keybase-0.8.9.tgz against keybase-0.8.9.tgz.asc
info: Running npm install keybase-0.8.9.tgz: this may take a minute, please be p
atient
=====================================================================

Welcome to keybase.io!

You have successfully installed the command-line client to

====>    C:\Users\Irwin\AppData\Roaming\npm\bin\keybase    <=======

Please make sure C:\Users\Irwin\AppData\Roaming\npm\bin is in your PATH.

If you're new to the service run:

     $ keybase signup        # signup for a new account
     $ keybase push          # to push your public key to the server
         -- or --
     $ keybase gen           # generate a new key and push it

If you already signed up via the Web or another keybase client, try:

     $ keybase login         # establish a session with the server, and pull dow
n keys

Once you're configured, you can:

     $ keybase prove twitter # prove your twitter identity
     $ keybase id max        # to identify a friend
     $ keybase track max     # to track them and write a proof to the server

And then attempt crypto actions like enc/dec/verify/sign.  See `keybase --help`
for
more details.

info: cleaning up tmpdir C:\Users\Irwin\AppData\Local\Temp\keybase_install_j8Yg4
1nDse8_gLc29Y7Jjw

C:\Users\Irwin>keybase version
warn: No config file found; tried 'C:\Users\Irwin\AppData\Roaming\keybase\config
.json'
keybase (keybase.io CLI) v0.8.9
- node.js v0.12.7
- gpg (GnuPG) 2.0.28 (Gpg4win 2.2.5)
- libgcrypt 1.6.3
Identifies as: 'keybase.io node.js client v0.8.9 win32'
