### ISSUE TITLE
Cannot revoke first/eldest keypair globally.

### ISSUE THREAD

**Issue by dconnolly** [keybase/keybase-issues#1683]
I've tried this every which way, and it never seems to propagate the key revocation through the entire ecosystem such that I am allow to generate new keys from the command line. It does let me generate new keys from the web app. Keybase username: dconnolly

- Generate keys on webapp.
- Login with cli client, pull down keypair.
- Revoke keypair successfully. Revocation persists in the webapp UI.
- Try to generate new keypair with cli, throws `You already have a key registered; either revoke or run 'keybase push --update'`

```
$ keybase version
keybase (keybase.io CLI) v0.8.9
- node.js v0.12.6
- gpg (GnuPG) 1.4.19
- Copyright (C) 2015 Free Software Foundation, Inc.
Identifies as: 'keybase.io node.js client v0.8.9 darwin'
```

I've done `keybase reset` several times, blown away and reinstalled gpg/keybase a few times, no dice. Help? Debug logs available.

**Comment by maxtaco** [comment]
So sorry! Maybe it's a bug, we'll take a look.

**Comment by dconnolly** [comment]
I wouldn't be surprised if I just got my account into a weird state. I don't know if it matters, but I started generating and revoking keys before I had verified my account by email. Thanks for looking into this. :+1:

**Comment by oconnor663** [comment]
@maxtaco I think the issue here is that when a user runs `keybase revoke` (which -- correct me if I'm wrong -- causes a total account reset) we don't take their eldest KID out of the Merkle tree. So the node client continues to believe they have one. and refuses to generate another.

**Comment by dconnolly** [comment]
Interesting? Would this be reflected in the debug output at all, that revoking the oldest/first KID is a special case and getting skipped?

**Comment by maxtaco** [comment]
@oconnor663 This seems plausible and likely is a new bug as a function of the new Merkle tree structure and your recent upgrades.  I'm not sure offhand what the proper state transition out to be.  We could require an intermediate Merkle tree configuration with a `null` eldest key.  Or we can just take the server's word for it that the user has done a reset.  There seems to be little security downside of the latter approach, since the server always has the ability to reset user sigchains as it pleases.  

@dconnolly Not sure, I'll leave the answer up to Jack, but it looks like he has the issue reproduced in our testing environment.

**Comment by dconnolly** [comment]
@oconnor663 do I have to do anything on my end to take advantage of the fix in `20b66ed`, which I'm assuming is to a private/closed backend repo?

**Comment by oconnor663** [comment]
Ok, we just pushed version 0.8.11 of the command line client, along with a server change. Users should not hit this issue in the future. @dconnolly to get out of your current state, you'll need to add a key to your account using the website. Once you do that, everything should work fine from then on. Please let me know if anything goes wrong.

**Comment by oconnor663** [comment]
Looks like I closed this a few hours before I meant to -- I should stop writing "Closes X" in my commit messages...

**Comment by dconnolly** [comment]
I am all set! Fresh, locally-generated key up and verified. Thanks very much! :+1:

**Comment by oconnor663** [comment]
Woo!
