### ISSUE TITLE
Keynes error #908

### ISSUE THREAD

**Issue by russmanov** [keybase/keybase-issues#1688]
I've forgotten my GPG passphrase. So I deleted it and created a new pair of keys with a new one.
I am trying to set up my keybase account through keybase push.
I am getting this message:
error: You need to delete your active key before uploading a new one (error #908)

how can I solve this?

Cheers!

**Comment by oconnor663** [comment]
Sorry for not getting back to you more quickly. The (WARNING VERY DESTRUCTIVE) `keybase revoke` command resets your account, so that you can then push a new key. Note that you'll lose any existing proofs and tracking statements -- it's almost like nuking your whole account. You can also do this on your profile page on keybase.io, in the gear menu on the right.

**Comment by russmanov** [comment]
![screen shot 2015-07-27 at 21 01 31](https://cloud.githubusercontent.com/assets/4017222/8916348/c1f1346e-34a2-11e5-8fa1-073f9b6ed5cb.png)

How can I delete my keys and do the keybase revoke?

**Comment by oconnor663** [comment]
Oh shoot, this is definitely a bug. I'm able to repro it myself. `keybase revoke` should be working in this case.

**Comment by oconnor663** [comment]
Ok, I just pushed version 0.8.15 which should fix the issue you were seeing with `keybase revoke`. Please run `keybase-installer` and let me know if the new version doesn't fix the problem for you.

Another workaround, just in case, is to go to your profile page on keybase.io and choose "Replace or revoke my public key" from the dropdown there. That should have the same effect, and it shouldn't be subject to this bug.

**Comment by lulezi** [comment]
I'm experiencing the same issue (keybase v0.8.18). 

```
lucius at mblh in ~
$ keybase revoke
error: No local key to revoke!

lucius at mblh in ~
$ keybase push
error: You need to delete your active key before uploading a new one (error #908)
```

**Comment by pnelsen** [comment]
+1

**Comment by maxtaco** [comment]
Sorry @lulezi, I fixed a bug, care to try it again?  Thanks for your bug report and your patience.

**Comment by lulezi** [comment]
works like a charm! thank you.

**Comment by jmorais** [comment]
Getting same error:

````
λ Desktop > keybase revoke
error: No local key to revoke!
λ Desktop > keybase push
error: You need to delete your active key before uploading a new one (error #908)
````

**Comment by maxtaco** [comment]
Try to push now?

**Comment by jmorais** [comment]
Success! Thanks

**Comment by knowncitizen** [comment]
I'm getting the same error as @jmorais and @lulezi, @maxtaco - 
```
jrist@hokuto:/Users/jrist $
#keybase version
keybase (keybase.io CLI) v0.8.23
- node.js v5.0.0
- gpg (GnuPG) 1.4.19
- Copyright (C) 2015 Free Software Foundation, Inc.
Identifies as: 'keybase.io node.js client v0.8.23 darwin'
jrist@hokuto:/Users/jrist $
#keybase revoke
Your keybase login passphrase: ****************
- run scrypt [==================================] 100%
error: No local key to revoke!
jrist@hokuto:/Users/jrist $
#keybase push
error: You need to delete your active key before uploading a new one (error #908)
jrist@hokuto:/Users/jrist $
#
```

**Comment by maxtaco** [comment]
This is likely a new problem, but a problem nonetheless.  We can take a look, can you paste the output from `keybase -d revoke` for me?   Thank you...  It's safe to post, there is no private data there, just publicly-viewable public key data.

**Comment by knowncitizen** [comment]
@maxtaco http://fpaste.org/292372/47947770/ - I'd rather not delete my key entirely so I don't lose tracking

**Comment by oconnor663** [comment]
@knowncitizen sorry this is so confusing. What's happening is your PGP key is expired, so the part of the code that figures out your "default PGP key" decides you don't have one. This is part of a long list of bugs that's making us consider not respecting key expiration times at all. (@maxtaco: We could hardcode `now=0` in this case if we wanted to support it. What do you think?)

The immediate workaround for you would be to submit an updated, unexpired version of your PGP key using the edit-key menu on your profile page. *However!* I think there's some confusion about what `keybase revoke` does. If you run that command, it will reset your account, and you will lose all your tracking statements. Maybe you could tell me more about what you're trying to accomplish, and I could suggest a different command?

**Comment by knowncitizen** [comment]
boom, @oconnor663! thanks, I had no idea it was expired. I like your idea of yelling about expired :+1: I'll update a new one on the site. thanks

**Comment by oconnor663** [comment]
Awesome.

A note to future readers: If you're seeing this error and your problem isn't the same as @knowncitizen's [above](https://github.com/keybase/keybase-issues/issues/1688#issuecomment-158105837), please file a new issue.

**Comment by knowncitizen** [comment]
A handy article on renewing, for those looking...
http://oduinn.com/blog/2011/07/22/howto-renewing-a-gpg-key/
