### ISSUE TITLE
Can't revoke keybase proofs

### ISSUE THREAD

**Issue by jaapz** [keybase/keybase-issues#1691]
I'd like to revoke a keybase proof for my website, as I thought I could delete it. Apparently I shouldn't have done that. I now want to re-prove my website, but I can't revoke the old proof.

Looks like there used to be a command to revoke the proof (`keybase revoke-proof`), but that does not work in my version of keybase (0.8.10). Has it been removed?

How can i revoke the proof for my website and re-prove it?

**Comment by jaapz** [comment]
I am sorry, just missed the `keybase revoke-sig` command. Not very user friendly though...

**Comment by oconnor663** [comment]
There's also a `-f` force flag to `keybase prove` that might make it easier to overwrite. I know this works for BTC addresses, but I haven't tried it for web proofs.

**Comment by jaapz** [comment]
@oconnor663 I think I did try the `-f` option but it failed for some reason. I don't know why exactly anymore though.
