### ISSUE TITLE
I want to generate my own key pair - instructions please?

### ISSUE THREAD

**Issue by zakf** [keybase/keybase-issues#1696]
I want to generate my public-private key pair using something I really really trust, such as `ssh-keygen` or `gpg` running on my own personal Mac OS X machine or Ubuntu machine. I could just do this:

`ssh-keygen -t dsa`

But I want to use exactly the same settings that Keybase would use by default. What are those settings? Please tell me exactly what commands to issue in order to generate a key pair that resembles one that would be created by the web-based wizard.

Also, am I correct in understanding that the web-based wizard on Keybase.IO is doing the math in JavaScript?

Thanks,

Zak F.

**Comment by oconnor663** [comment]
The way to generate a key on your own is `gpg --gen-key`. It'll prompt you with some questions, and there are a lot of options there, but generally stick to the defaults. If you want exactly what you would've gotten on the website, tell it to generate a "4096 bit" key when it asks. To upload your key, click through "Add or create a public key" and "I have one already". There will be instructions there for how to export the key from gpg. (SSH keys are conceptually similar, but a different format. We only work with PGP keys.)

You're right: What happens on keybase.io is a JavaScript version of the same thing that gpg is doing. This raises valid concerns about trusting Keybase too much (who knows what JS we're giving you?!), and in the future this isn't how we'll have people generate keys. But for now the alternative is having people use the command line, which is great for people like you who are interested in learning it, but really unacceptable for most folks.
