### ISSUE TITLE
error importing SSH2 public key

### ISSUE THREAD

**Issue by pfarikrispy** [keybase/keybase-issues#1699]
While my SSH2 public key may not be the same as a PGP public key, mine is also 4096 bit long, generated using Putty and used with openSSL all the time so I fail to see why I couldn't import it.

The text file kept generating an error "missing header" although the text started with 
> ---- BEGIN SSH2 PUBLIC KEY ----

Am I missing something? If so, please enlighten me. I've already generated a new key now, but still... I'd like to understand... :)

**Comment by oconnor663** [comment]
Even though some SSH keys use a similar ASCII armor format to PGP keys, and so look visually similar, they're a totally different format under the covers. Not compatible.

**Comment by pfarikrispy** [comment]
Ah! I thought so, my bad. Wasn't sure coz I couldn't easily find anything
on the issue. But perhaps an idea to mention that it must be a GPG/PGP key,
not SSH2. I can see more people getting confused between the two :)

On Wed, Jul 22, 2015 at 4:34 PM oconnor663 <notifications@github.com> wrote:

> Even though some SSH keys use a similar ASCII armor format to PGP keys,
> and so look visually similar, they're a totally different format under the
> covers. Not compatible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keybase/keybase-issues/issues/1699#issuecomment-123742822>
> .
>
-- 

Christian.
