### ISSUE TITLE
invites via networks other than email

### ISSUE THREAD

**Issue by dthorpe** [keybase/keybase-issues#1714]
It'd be great if I could send Keybase.io invites to folks I know via social media but I don't know their email address.  Invites via Twitter direct message, for example.

**Comment by oconnor663** [comment]
One workaround you can do right now is to send an invite to a garbage email address. Then you can look at your own invitations page, copy the code, and send it however you like. It's not actually tied to the email address that the invite went out to.

**Comment by zQueal** [comment]
To emphasise this a bit more, you can send the invite to yourself via a proxy email. For example, if you have a gmail account this is super easy. Simply send the email to yourself as `email+person@gmail.com`. `email` being your own email and `+person` being who its intended for. After that, just check your invite page and copy the invite hash. Then you can send it to whomever and they can register.

**Comment by oconnor663** [comment]
Good point, that's probably easier.
