### ISSUE TITLE
Can't verify per-user directories of websites.

### ISSUE THREAD

**Issue by ejj** [keybase/keybase-issues#1717]
First off this is my account: https://keybase.io/ejj

I'm a graduate student at UC Berkeley, and here (as with a lot of other schools), it's common for each user to have their own subdirectory on the institutional website.  For example, my personal site is:

http://www.cs.berkeley.edu/~ejj/

berkeley.edu is owned by UC Berkeley, of course.  But ~ejj is my own little slice.

Unfortunately, when I try to verify this website on keybase, the system won't let me as it expects me to own the whole domain.  I could easily put the required keybase.txt file as in ~/ejj, but I can't put it at the root of berkeley.edu for obvious reasons.

This is a somewhat common use case, so I thought I'd bring it up in case this behavior wasn't intentional.

Ethan

**Comment by dtiersch** [comment]
I found a bit of discussion for this in #1103

**Comment by dtiersch** [comment]
I found a second issue for this, #496, where @malgorithms stated
> we probably won't end up supporting this

**Comment by ejj** [comment]
Sure makes sense.  Thanks for digging the explanation up.
