### ISSUE TITLE
Can't verify Reddit identity

### ISSUE THREAD

**Issue by hacdias** [keybase/keybase-issues#1718]
Hi! 
I'm having troubles verifying my Reddit identity. I created the [post](https://www.reddit.com/r/KeybaseProofs/comments/3fqowd/my_keybase_proof_reddithacdias_keybasehacdias/) but it doesn't appear listed on [KeybaseProofs](https://www.reddit.com/r/KeybaseProofs/). What am I doing wrong?

Thks.

**Comment by zQueal** [comment]
[You seem to be shadowbanned.](https://www.reddit.com/user/hacdias)

Keybase verification will not work for a shadowbanned user.

**Comment by hacdias** [comment]
What does that mean?

**Comment by paralin** [comment]
See #1208

**Comment by paralin** [comment]
Shadowban means that only you can see the posts you make. This is probably because you self promoted too much without actually participating in conversation.

**Comment by hacdias** [comment]
Strange. I'm going to see what I did wrong. I rarely use Reddit! That's why I think it's strange O.o Thanks for helping.

**Comment by paralin** [comment]
Well do actually check if you are shadowbanned. Google "am I shadowbanned".

If you aren't you probably are just getting spam filtered.

**Comment by hacdias** [comment]
Let me see @paralin

**Comment by hacdias** [comment]
Yeh, I am. "hacdias is shadowbanned or deleted"
