### ISSUE TITLE
Keybase account in limbo

### ISSUE THREAD

**Issue by orweinberger** [keybase/keybase-issues#1719]
I've created my Keybase account a while ago and set up my PGP keys at the time.

I've just logged in again and I see that I can no longer sign/verify or do anything anymore since my keys are not hosted on keybase.io.

So I try to do some stuff from my console and I am able to use the `keybase login` to authenticate to my account, I can also see that I have some keys in my ~/.gnupg directory and I have a <myuser>@keybase.io key visible when I run `pgp --list-keys` and it's the same one that is listed under my account over at keybase.io.

However, I can not perform any actions from the cli, for example, trying to run `keybase sign` outputs `error: can't perform secret-key action without a secret key`.

Is there a way to fix this without revoking the current key?

**Comment by oconnor663** [comment]
It sounds like the machine you're on has your public key, but not your private key. Could you run `gpg --list-secret-keys` to confirm that? If it's missing, you'll either need to get it from a different machine of yours, or you'll need to reset your account and generate a new key.

**Comment by orweinberger** [comment]
Yep seems like you're right. I don't see that secret key there. I might know where it is, thanks for the hint!

**Comment by oconnor663** [comment]
Good luck :)
