### ISSUE TITLE
`Verify` tab needs a description

### ISSUE THREAD

**Issue by rohithpr** [keybase/keybase-issues#1720]
I've been familiarizing myself with Keybase today (website, not the cli). I couldn't figure out what `verify` does.
Pasting plain text results in an error message telling that `No headers were found`. Pasting an encrypted message results in an error that says `You've pasted an encrypted message. Decrypt it.`

**Comment by zQueal** [comment]
For future reference, the `Verify` tab lets you verify the integrity of a signed statement. Assuming an entity which signed it is a Keybase member, their username will come up.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

This is a simple example of a signed message. Not only can you see that the message is authenticated with my Private key, it gives you a link directly to my Keybase account!
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.34
Comment: https://keybase.io/crypto

wsFcBAABCgAGBQJVxg2LAAoJELHaVty3PoUWGCQP/1E76B3H7xA/axCd/hGoldFC
vyWXcIJ2QMI4nGErvcRWEbeeFIhgVLdON9nccjU3o75oZ6oxQYeafC2Mfdiw/f+q
p6WeEk+j/lF2Vx5wP/kVLQx8Mka4dQ7YBFFK9ZhQDYQnffunhk5U3CSXfncxHmso
xlSgrxYfRhI/+13ogyPWzwuY/q+UFjgYwoQvIiXSlQNMR0Nrh9/y1sd7/4RbFGOW
viySDvWll1+USap++D/tHVPAAiE6iegMpB6Zyah/BskUCwwJ7iY7ImoX53AZiFTc
/S/PyyREfuqmKzWcLiloN+nUuKEtkNrRncs7QF1SzTlYqwD1/rzOYk7BAtg660g6
w2YIzr8GB92Hb0vnsRRIio4W2Q0RCznJaK3bL/pu2fZfIbu7rS3KlIBjCzHSPO07
ONeBe5Dc2bQx7uTlY/VZjeAhrp3P28ficom4fnECyRDyT2ij5qDgwT+OTCrSLhL/
ScN87AcAYNWCHOuIcTQo0WC23gcZW2VPPZX/qVZTuW8aKOtHS1CugtlpBlJUFaq2
Upxfbg6foyYNXwFKCSuBpiBJYMCMU6xnguu1HpnLXJdgZGP/WI5IgCrsLdnK8B34
l97rZWJ0/2kyvDoV2T5XRjTqWLeG5fy3XXyRZtODahNyTnhvarYvR499NjhNsdzS
H8p5Y5lmcvPu0NJJkoxI
=Lwdd
-----END PGP SIGNATURE-----
```

Paste the above into the verify tab and you'll see first hand.

**Comment by rohithpr** [comment]
Cool, it worked!

It still throws an error when I try to verify a message that I've created:
```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.34
Comment: https://keybase.io/crypto

wcFMA7HaVty3PoUWAQ/+LWUHKfx5e/GWmXYOQQxxP0Q+vjbrYKVEp7EswFxXfu2N
5Lo84NRlJGbwOdnp07WPYQ3JIPtOrsJJuKUQuepI/PQ0h/peodLYN+raG+nPyTCD
ejOBwiCqWQMfRtVe3no0Dgit0r0nBt7gRbXSWuZDdO9RJUV4oLpi6DWF6CpcnurH
3IwgqTOzCDodRjl/uyFPrAMUH9nfKh5QO+TXooK+hmVbqPRskEtKH3qoXp/rNU5H
/Y6b8LzBFRyFnefd+m0EIzkAuf0xAtVYeU2KVjomwWBF0ATJhBPkf/WqgMLlHxmY
A88GEFyNHagXWYPQXgpxrcQ6P/P0EtUM9g1b99wNJDH3E2UrjX9ArYmYqjUJhwiS
Z2fQC4PmhHK+ZhGaVp7XcBq/+9x7NpIM0yiY6ivqh5r2km761lr7ozWuUe87/RS5
CghIEBlbyIqfI8QQqo489Caaakuh9M9sOWAa6TC5bx6/ibt+TBGJdPyCsCUjs1nE
OGRnPOZXJTzWS9zimZyDH6dVy9p7MPLcZv0pGZel257r5q8zbBm6XK7Rw0Mhp0sh
tBFdrdL8bTskfaTcxr1SxgijvwRSoATwCZ3Y7iEqcJSR3B0EBdi05lSHnn+/1ihl
P2uT027a29Gbiyy04EqbSOxlh/ghyXpF5oDj3Ur4PCvydhXDVMqWtW+YbgwnfAHB
wEwDLUY6WYThy58BCADBj40lq/x/R1I6abgU2vARvCzB0FWe4I0fgzqkBm2/ZY+G
laJY+kQf5hZP5PUNzsxgOtTzRWyDLjv8oscyY3KUg0Vyh8CaY8YYmDWACidfjjqo
+GChGhhnv0TooD8P2e8qp4v1Dygr1cvKqwefFSak7QVIcqktEHAynwIFRvzTZTXw
OlGxBHNLugkBb1Qyd2vY4gpLUQ0WCeou0Ry8sl2fZyYAyeYByxn0dSwb7OqV8QGg
xOWhyiyQv9wo3IkghsZ0FHt3m6V/BQ77FtL9kn6bP8jq+znM3tuVCjIqm5h4w5xy
C732QuJl1/Zz71QB34+IDG1V7NnPGzr29+3qIJEE0sC0AZTdvaL+qEDrHcCLY5LI
cQqGSK7QDnUeqY+si8w/xPUAuCaD5bZ02Ui/odf1cABRB+rcrP5QJffqy2u/kdYs
i0YMZopDMftQbUEwl4raNpZ5r0p5qsw6kNBFDP9yUPLTaStzLlPPtWdY24UjfjXJ
29ZYhotGj1vPXGjuh6S+XwOZ5RvfiXA+lkV3qruCYlPy9vBSMHYc6CGEFqno/bII
kMxwMjIbOZEMyFwVVDVf0t31UUD1Sz9ZM8Iw7cs+VlQBHS9D2x0RDpzy15T2jPWZ
zXHKYKJfBnuoJ3KxbeAw+rrYFQ02O/dcmZIH5Qe4EtnFMraErXrfGF9bkhqsXeCK
deYQGDA6WTiuqIntWkzxfF4X+HIxKs5mj9vf4pR103sIK9ELTag5ll9Ccv9ApVVd
l2WJcieRTSMLujMZcrjGVccZmqCx/Q1vVfc1AabzEt447Q7LBk9+NXO6+CbVeINt
ePypLcnA3OAasm4Vau8j47RzAipd
=M+Lf
-----END PGP MESSAGE-----
```

Is it because I'm the sender (and the receiver)?

**Comment by rohithpr** [comment]
Okay, now I see that there isn't any signature in what I've generated!

Could you please tell me where I went wrong? This is what I did:

1. Go to the encrypt tab.
2. Enter recipient (zqueal)
3. Enter message
4. Check `sign the message`
5. Enter `passphrase`
6. Click on `Sign and encrypt`

**Comment by zQueal** [comment]
![dkti4jw](https://cloud.githubusercontent.com/assets/239193/9151172/7ea7bbd2-3dc7-11e5-8a5f-150df0f78946.png)

To the best of my knowledge, this is by design. Because you encrypted the message it should __only__ be decryptable by the person you sent it to. Because you used your private key, it should already be signed. (at least when you encrypt via Keybase) So if you have a clear-text message like I do, above, then you can verify it, and if you decrypt an encrypted message, it's verified also, but you can't use the verify process to verify an encrypted message.

If that makes any sense.

**Comment by rohithpr** [comment]
Hmm.. That made sense! :p 
I could decrypt the message using my passphrase too! So maybe it can be decrypted by both the sender and the receiver.
