### ISSUE TITLE
Keybase code-signing certificate not signed by Max's current key

### ISSUE THREAD

**Issue by ab9** [keybase/keybase-issues#1724]
On August 10, 2015, I retrieved Keybase's [code-signing certificate](https://keybase.io/docs/server_security/our_code_signing_key) (key ID 47484E50656D16C7). The page said to expect signatures from Max and Chris.

I imported it and found that it did not carry a signature by Max's current key on Keybase (key ID 6052B2AD31A6631C). It did, however, have a signature from key ID 63847B4B83930F0C, which can be found on [public keyservers](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x63847B4B83930F0C) and may be another certificate owned by Max.

If it were signed with Max's current Keybase certificate, it would raise fewer questions.

**Comment by zQueal** [comment]
```
uid Keybase.io Code Signing (v1) <code@keybase.io>
sig  sig3  656D16C7 2013-11-19 __________ 2017-11-19 [selfsig]
sig  sig3  83930F0C 2013-11-19 2017-11-19 __________ Maxwell Krohn <themax@gmail.com>
sig  sig3  97016CB3 2013-11-19 2017-11-19 __________ Chris Coyne <chris@chriscoyne.com>
sig  sig   61F8A93C 2014-11-01 __________ __________ Francois Belanger Boisclair <fbboisclair@gmail.com>
sig  sig   9875C3A6 2015-06-11 __________ __________ Hamdi Azis <hamdi@hamdi.web.id>
```

Seems to be.

**Comment by ab9** [comment]
No. The "Maxwell Krohn" signature you're showing is by key ID 83930F0C. Max's current key on Keybase has key ID 31A6631C.

![keybase-max](https://cloud.githubusercontent.com/assets/68527/9175296/8315177c-3fb7-11e5-8b96-0ed662baf35e.png)

**Comment by maxtaco** [comment]
I switched my key at some point is the issue.  But Aaron, you're right, I
should sign with both.  Will try to get to it soon, thanks for bringing it
to our attention!!!

**Comment by zQueal** [comment]
Ahh, I gotcha. I must have read your initial issue wrong and thought that you meant he didn't sign it and should. Good catch.

**Comment by maxtaco** [comment]
Should be fixed, thanks for the bug report.

**Comment by oconnor663** [comment]
I feel like this issue deserves its own slide in a "Moving Beyond PGP" presentation...

**Comment by ab9** [comment]
@maxtaco: Thanks! I see your new signature.

@zQueal: True, I didn't say Max didn't sign it. But I had to leave open the possibility. From my point of view, it was merely signed by a key attached to the label "Max Krohn"; I wasn't sure that key was owned by Max from Keybase. Man, talking about cryptography is hard!
