### ISSUE TITLE
Error: 'service' section is not allowed for this signature type

### ISSUE THREAD

**Issue by nibogd** [keybase/keybase-issues#1726]
Cannot verify a message via the public key, getting the following error: `Error: 'service' section is not allowed for this signature type`
Which type should it be then?

**Comment by maxtaco** [comment]
Who signed the message in question?  We'll investigate.  Thanks.

**Comment by nibogd** [comment]
Me.

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

The last message has the wrong signature because of smiley
So this is real me!
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBAgAGBQJVK4kTAAoJEGynwVlrN2Uw9O4QALArwyzGoTaK7lZSwr8mKgPe
h+VafQM01O3C6sR9y0dmInE5cnETqbPgPJQjQimnAgZK9607kCXujC1+3ap+BCCx
PGdjkQ/kLTuwX+gzU+CYoWYTDguEpEj5QXcgk3/tdA/BtUYuQIGkeG1+O/iLHBF7
NGI6TYQtjW9oZiHII9hn5qEVjePDbWG8+yh+EZy8rFuE1D6JA2KwxGLRh7ZMih9u
0LWkRx55B9UR+q+E1b5OAUqbJOVcyKoV8xGnxBAQEH3pgBtLDfGz9WKXG7KcD8n0
YGhFvp1BDWILH+y3Oq/yxbqD5n0UoF/IZUv96hb/memTQSLpLyJ3/lJXSUIfgBX3
rvK7aUma8d/s9XOhDwVBkt0VPq0RAJGD7n17TpYsPkj7MrHLa/0aLF5bG4j3ps4u
ZKG8pHnzcOxm31q5RpYGEFxS//GA/q/5SC9G7096esgMawRkEQ45s/o/j88Hwt3q
JaP96dOJ4xeqm+PJ4LGOGDWf3bRanrA2dXAc5adx+HE6YfZi820SXMsS5YkUBGDT
gipgI1JNt75ZTLgWQBHgX+ONAHz8tqdO17MCENCKrxNgYch9tyrPgU0iWeEUbfxF
Dp4qmJyMCqghRMoS2bVuUd3NUPYU7LB+q7TrAM/wb4bxkxjRZc4yBJbM/uaf1sH5
NW8JkqkboA1B4TeKlKUG
=cqwI
-----END PGP SIGNATURE-----

**Comment by lord** [comment]
@nibogd we've pushed a patch that should fix this — can you try verifying again?

**Comment by nibogd** [comment]
@lord yeah, thank you for a so fast fix :)

**Comment by lord** [comment]
No problem, thanks for reporting!
