### ISSUE TITLE
Error: no tailer found

### ISSUE THREAD

**Issue by Soupala** [keybase/keybase-issues#1727]
In attempting to decrypt a message with the web client, I get an error "Error: no tailer found"

Chrome Version 44.0.2403.125 m

Copy of encrypted message:
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA6lmUmOXgtKkAQf/aunnnHCNP4xmFY98WQe+NEVsxk4gDLOrmRzvUqVjWTtL
lQs1g+6w+FSoFw5b/OhjkukkJA2Y6+fXuYbcgai9RyYKPumUUNm/xuFqytEPphUd
DEuw/KtD60h8Wy9hzjONz6x6ZwVMgRuYu0n1PI7EQ3/vEeH+Wh+CjxJYy/OD/liU
rebngptlgJGfu3iNcfAqfcOKNCPc/PMBLAMYanamJQfoU58p+IV8TapZAeMOsW2a
AGvS035FSLdFkF3xFKCM2dKljkZmzucMSTqifGxwGLwMaOiz6v3j2QkaJkU6sE/N
SzthM2YSsQLKQZoSdw8cPLdX5Y2Ex2fmLknhz7UPOtKEAe4bJzc9LCEEBNfqBjyE
2v8bI0BYKhGvxlT8qjmBVAfQS159hWk968KYBg566/UwTN1iMuYDZbd5BH8y6AvL
UrkkUl6a1TjqWaN5zawnmrOycN6Z3qrF0y/zoVFgvCKWmR+9BM+z2YfMdUUCOByQ
q1BSsXrSC/Xd7hsm/GcOnzmmjYH1
=WOWx
-----END PGP MESSAGE——

**Comment by zQueal** [comment]
Try this:

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA6lmUmOXgtKkAQf/aunnnHCNP4xmFY98WQe+NEVsxk4gDLOrmRzvUqVjWTtL
lQs1g+6w+FSoFw5b/OhjkukkJA2Y6+fXuYbcgai9RyYKPumUUNm/xuFqytEPphUd
DEuw/KtD60h8Wy9hzjONz6x6ZwVMgRuYu0n1PI7EQ3/vEeH+Wh+CjxJYy/OD/liU
rebngptlgJGfu3iNcfAqfcOKNCPc/PMBLAMYanamJQfoU58p+IV8TapZAeMOsW2a
AGvS035FSLdFkF3xFKCM2dKljkZmzucMSTqifGxwGLwMaOiz6v3j2QkaJkU6sE/N
SzthM2YSsQLKQZoSdw8cPLdX5Y2Ex2fmLknhz7UPOtKEAe4bJzc9LCEEBNfqBjyE
2v8bI0BYKhGvxlT8qjmBVAfQS159hWk968KYBg566/UwTN1iMuYDZbd5BH8y6AvL
UrkkUl6a1TjqWaN5zawnmrOycN6Z3qrF0y/zoVFgvCKWmR+9BM+z2YfMdUUCOByQ
q1BSsXrSC/Xd7hsm/GcOnzmmjYH1
=WOWx
-----END PGP MESSAGE-----
```

Let me know if that works. If it __does__ post where you copied the message from.

**Comment by Soupala** [comment]
That works.  My sender copied from CLI and pasted into Applemail.  Applemail causes the ----- to change to ——
