### ISSUE TITLE
detected mammaliaforme

### ISSUE THREAD

**Issue by Soupala** [keybase/keybase-issues#1728]
Chrome Version 44.0.2403.125 m

Occurs when loading the following routes:
https://keybase.io/encrypt
https://keybase.io/decrypt
https://keybase.io/sign
https://keybase.io/_/user/account#link-tab-invitations

I noticed "detected mammaliaforme" from onloadwff.js:1025.

1025: function elt_is_formlike_container(a){if(!a)return!1;var b=a.ownerDocument,c;if(!lpIsVisible(a,!0)||0>=a.children.length)return!1;var d=a.getElementsByTagName("input"),e=[];if(d){if(0>=d.length)return!1;var f=MAX_INPUTS_SOFT;d.length<f&&(f=d.length);for(c=0;c<f;c++)if(popupfill_shoulddofield(b,d[c])){e.push(d[c]);break}}return 0>=e.length?!1:0<e.length?(console.warn("detected mammaliaforme "+LP_getname(a)),!0):!1}

Does not occur when loading:
https://keybase.io/
https://keybase.io/soupala (user profiles)
https://keybase.io/docs

**Comment by Sidnicious** [comment]
[This thread](http://stackoverflow.com/questions/31976062/in-chrome-console-what-is-detected-mammaliaforme) suggests that it's coming from the LastPass extension, not our site!
