### ISSUE TITLE
remove track or block track

### ISSUE THREAD

**Issue by readingsnail** [keybase/keybase-issues#1733]
a monent ago, i track someone. i don't know him and i want to not tracking to me. so please remove tracking or blocking tracking.

**Comment by Sidnicious** [comment]
Hey @readingsnail, we can't untrack people for you (since it requires your cryptographic signature), but you should be able to untrack them from the keybase command line or from the website.

**Comment by chigh** [comment]
@sidnicious other way around. @readingnsail wants to be able to remove/stop/block someone from publicly tracking them.
