### ISSUE TITLE
Curve25519 key support

### ISSUE THREAD

**Issue by dspearson** [keybase/keybase-issues#1738]
There's a new GnuPG modern out. See https://lists.gnupg.org/pipermail/gnupg-announce/2015q3/000371.html

Noteworthy changes in version 2.1.7:
- gpg: Support encryption with Curve25519 if Libgcrypt 1.7 is used.

Currently, the keys are not supported.

Example:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: ed25519 / cv25519
Version: requires GnuPG >=2.1.7 and libgcrypt >=1.7.0

mDMEVcxoAhYJKwYBBAHaRw8BAQdAF2SOaWvRyYFFjldmtyLMjcdv0lvCI9jGG8x3
XuHXh120KURvbWluaWMgUy4gUGVhcnNvbiA8ZHNwQHRlY2hub2FuaW1hbC5uZXQ+
iH8EExYIACcFAlXMaAICGwMFCRLMAwAFCwkIBwIGFQgJCgsCBBYCAwECHgECF4AA
CgkQg4/P6Ag8oqdKcQEAiAdVRV9EsTfJ7vCjBLrcFVC8D2XsSHZVaxpRgnxQyesB
AMj1wdViMbTvabBjOFQ206kox8dn/mNCVJUf6LkUoBwFuDgEVcxoAhIKKwYBBAGX
VQEFAQEHQBOdoYUDj/FRam2X5YrKpxU0Fk/IGAAlm0XZsjSo7KRSAwEIB4hnBBgW
CAAPBQJVzGgCAhsMBQkSzAMAAAoJEIOPz+gIPKKnVuUBAMNEr84TwlszbtXjjWBc
KV87g9kFKsNuPbz5MvvIFpaCAP9PVL+G+8x10ALtw+m4c7SPQ2wBdTAYFt6p68F1
AwGSDw==
=sF64
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by maxtaco** [comment]
I just added support for EdDSA but couldn't easily access Curve25519 support.  I'll try to get to it now that it's available. Thanks for the heads-up.

**Comment by mrapplegate** [comment]
Is there a way to be kept informed when Curve25519 support will be added. There are no release notes per say to watch, correct?

**Comment by linux-modder** [comment]
install libgcrypt 1.7  which supports it

**Comment by dtiersch** [comment]
With `libgcrypt 1.7` and `GnuPG >=2.1.7` you get Curve25519 support for gpg itself and everything that uses gpg, like Enigmail, git, ...
For keybase this is not true since it uses independent implementations in Go and Node.js as pointed out by @maxtaco [here](https://github.com/keybase/keybase-issues/issues/2213#issuecomment-211378867):
> In general, these implementations are simple once we have a reference implementation to base ours off of. We'll need one for https://github.com/keybase/kbpgp and one for https://github.com/keybase/go-crypto

**Comment by w4** [comment]
Is this viable in the near future?

**Comment by maxtaco** [comment]
Would love to but don't have the bandwidth on the team and it's not very often requested.  We're looking for volunteers to help us in either JS/IcedCoffeeScript or Golang

**Comment by mjbshaw** [comment]
What's left to do in JS and Go? I see upstream golang/crypto has support for [ed25519](https://github.com/golang/crypto/tree/master/ed25519). Does that just need to be pulled into keybase/go-crypto? And then ported to JS?

I'm not very familiar with ECC or Keybase's code, but if there's something I can do to help let me know. I'd love to be able to use my ed25519 key.

**Comment by maxtaco** [comment]
Eddsa is fully supported. We don't yet have support for encryption with
curve 25519 in pgp.  We have some work underway.  Thanks.

**Comment by linux-modder** [comment]
So I can start updating my profile with eddsa CSA keys?

**Comment by maxtaco** [comment]
It should work but might be a little bit bumpy.

**Comment by linux-modder** [comment]
nice

**Comment by zapu** [comment]
If you like to live dangerously, feel free to test my branch with full cv25519/ed25519 support (expect for keygen) in it: https://github.com/zapu/kbpgp/tree/curve25519

**Comment by zapu** [comment]
Just pinging people who might be interested in this - support for EDDSA+ECDH (along with Curve25519) keys has landed in master.

**Comment by mrapplegate** [comment]
Excuse my ignorance. Will this allow me to upload a Curve 25519 generated key? I still get an error when I try to upload through the web interface.

**Comment by maxtaco** [comment]
We still have some more integration work to do, and we need Go support to.

**Comment by mrapplegate** [comment]
Ah ok. Thanks.

**Comment by zapu** [comment]
Ah, sorry for the confusion, I didn't realize this is *keybase-issues* when I first posted my comment today.

**Comment by linux-modder** [comment]
@maxtaco, please ping me on any testing work and when gui and cli support is fully there for uploads of cv/ed keys. I really rather upload my ed25519 key not the rsa4096 there now:)

**Comment by zapu** [comment]
@linux-modder Support for cv25519/ed25519 landed a while ago, for both website and go client. I see that you some EC keys already. Let me know if you have any troubles.

**Comment by lesderid** [comment]
@zapu I might be doing something wrong, but I still can't import my key on Arch Linux (keybase 1.0.20):
```
lesderid@elsa ~> keybase pgp select
▶ INFO Forking background server with pid=28728
#    Algo   Key Id             Created   UserId
=    ====   ======             =======   ======
1    256?   5EC132DFA85DB372             Les De Ridder <les@lesderid.net>, Les De Ridder <les@fuwafuwa.moe>
Choose a key: 1
▶ ERROR ImportKey error: openpgp: unsupported feature: unsupported oid: 2b060104019755010501
```

**Comment by lesderid** [comment]
@maxtaco 
Client:  1.0.18
Service: 1.0.18

**Comment by maxtaco** [comment]
hmm looks like the upgrade didn't work

**Comment by maxtaco** [comment]
Oh looks like you're using the official package?  I guess that's pretty far behind now.  You can try our install instructions to see how to get the newer software

**Comment by lesderid** [comment]
Yeah, I just noticed that the official package has version 1.0.20 in pacman, but isn't actually version 1.0.20. Any idea why that's the case?

**Comment by maxtaco** [comment]
Yeah cc: @cjb and @oconnor663 on this...

BTW, I'm not 100% sure that 1.0.20 has Curve25519.  Our prerelease as of `1.0.20-20170330110021+bff28e7` does have it

**Comment by lesderid** [comment]
@maxtaco Got it to work with the git AUR package, thanks!
