### ISSUE TITLE
Why is the CLI secure?

### ISSUE THREAD

**Issue by yaronf** [keybase/keybase-issues#1746]
Hi, I am a new user and I would like to use the scripts. But I'm worried that installing a full scale server (node) on my Ubuntu desktop would add a significant attack surface. Can you say anything (or point me to a write up) that'll convince me that this is not a major risk?

Thanks!

**Comment by oconnor663** [comment]
Node.js is just an interpreter. Think of it like Python. It doesn't run any services or listen to any ports unless you install a server written in it.

**Comment by thequbit** [comment]
As @oconnor663 said, node.js (node) is not a webserver.  There are packages written in Javascript that allow you to run a web server.  The CLI clients for keybase do not install a 'full scale server'.

**Comment by yaronf** [comment]
Got it, thank you.
