### ISSUE TITLE
Mis-spelt Username

### ISSUE THREAD

**Issue by omon23** [keybase/keybase-issues#1749]
Really sorry to post here, you probably get many of these requests.

I missed out two numbers on my username whilst signing up. I recently got an invitation, and with me being keen to get started I didn't realise that I missed them out. 

The username I wanted was 'ethernet22', but I just put 'ethernet' instead. Is it possible it could be changed? I would be really grateful, but do not mind too much whether it is changed or not.

I look forward to trying out keybase, it certainly looks great. I saw similar issues posted here with users wanting to change their username so I figured I should post here too. 

Many Thanks,
Dan.

**Comment by oconnor663** [comment]
You can use the invitation code you got to sign up with any account name. It's not restricted to the email address that requested the invite, or anything like that. Was that what you were hoping for?

**Comment by omon23** [comment]
Sorry, no. I have already signed up for the account and just wondered if I
could change the name. I'm not too worried about it, if it is possible then
I would like to get my name changed.

- Dan

**Comment by oconnor663** [comment]
No, it's not possible to change account names. Given the focus on secure identity, we worry that changing names would bring up too many questions about what proofs should remain valid and how to present all that to other users.
