### ISSUE TITLE
Can't verify Reddit identity

### ISSUE THREAD

**Issue by felipeplets** [keybase/keybase-issues#1751]
Hello, 

I've tried three times to verify my reddit identity [http://reddit.com/user/felipeplets/](felipeplets) but still couldn't. As it had not worked in the first and second attempt (yesterday) I've deleted the posts now and did a new post, but still is not verified. 

Any idea on what can be the problem?
 
Cheers, 
Felipe Plets

**Comment by oconnor663** [comment]
When I go to https://www.reddit.com/user/felipeplets/, I see this:

![untitled](https://cloud.githubusercontent.com/assets/860932/9552194/3116ddfe-4d84-11e5-8575-6373bb717aa9.png)

Can you see your own user page from an incognito window? You might be shadowbanned.

**Comment by felipeplets** [comment]
Hello @oconnor663, 

I see the same as you in incognito, I checked and I was shadowboxed. 
I`m trying to contact admins to solve that. 

Thanks!

**Comment by oconnor663** [comment]
I think Reddit said they were going to stop shadowbanning real accounts soon. Good luck in the meantime.
