### ISSUE TITLE
Weird wording after verifying HN user

### ISSUE THREAD

**Issue by RexMorgan** [keybase/keybase-issues#1752]
I verified my HN user and it gave me this message:
![image](https://cloud.githubusercontent.com/assets/178752/9557711/d36d7b2a-4da3-11e5-9f72-345905ccef6f.png)

"For that reason, you should".... should what? :)

**Comment by oconnor663** [comment]
Thanks for reporting. Looks like we left Hacker News out of one of our switch statements.

**Comment by malgorithms** [comment]
@oconnor663  fixed this (thanks; and thanks for reporting @RexMorgan )
