### ISSUE TITLE
Cannot prove identity after initial install

### ISSUE THREAD

**Issue by stkent** [keybase/keybase-issues#1760]
Brand new user. When I try to e.g. prove my identity on twitter using the CLI command

    keybase prove twitter

I see a prompt like the following:

    You need a passphrase to unlock the secret key for
    user: "keybase.io/stkent <stkent@keybase.io>"
    4096-bit RSA key, ID C93D322CC9E53BD7, created 2015-09-03

When I enter my passphrase (I assume this should match the password I used when signing up?), it is indicated that the passphrase is invalid. I have tried suggestions on here to include the line

    export GPG_TTY=$(tty)

in my .bash_profile file, but nothing changes. I'm on 10.10.5 and have both gpg and gpg2 installed via Homebrew. Any insights appreciated!

**Comment by oconnor663** [comment]
This password is for your GPG private key. Whether it's the same as your login password depends on how you created that key. In particular, if you created the key yourself some time ago and then added it to your Keybase account more recently, they might be different.

**Comment by thecoshman** [comment]
It appears you never uploaded your public key. As such, unless I am mistaken, you are not able to 'prove' any other profiles; the first step is to upload your public key.

I am not sure why it is not clearly telling you that you do not have an uploaded public key, perhaps you have already generated a key pair, and it is simply picking up on the fact you have a private key.

**Comment by stkent** [comment]
I regenerated my public/private key pair, and everything seems to be working smoothly now! Thanks for the thoughts.

**Comment by zQueal** [comment]
> It appears you never uploaded your public key. As such, unless I am mistaken, you are not able to 'prove' any other profiles; the first step is to upload your public key.

This isn't quite right. To the best of my recollection you __are__ able to prove identities without uploading your private key to Keybase. It simply _must_ be done via the command line on a PC which does have local access to your private key. That being said, the simplest thing to do is to simply upload your private key to the web interface--however, some have serious reservations about uploading their key and protecting their identity. As a happy medium you can simply use the command line.

**Comment by thecoshman** [comment]
This example was of using the cli, and you are correct in saying that you do not need to upload your *private* key to be able to prove any accounts. You must, however, have a key pair, as that that is what is used to generate the proofs.

Weather or not you need to have uploaded the public key to keybase, I am not sure. It would seem very strange to be able to publicly link a keybase account with another online profile, without also having the public key that is supposed to be used to help verify that the the two are linked together by a certain key.
