### ISSUE TITLE
https proof issue

### ISSUE THREAD

**Issue by colbygk** [keybase/keybase-issues#1763]
I too am having trouble getting keybase to acknowledge https in my proof verification steps:

```text
curl -I https://shrewdraven.com/keybase.txt
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 08 Sep 2015 14:23:22 GMT
Content-Type: text/plain
Content-Length: 2753
Last-Modified: Tue, 08 Sep 2015 14:17:53 GMT
Connection: keep-alive
ETag: "55eeee11-ac1"
Accept-Ranges: bytes
```

A test with https://www.ssllabs.com/ssltest shows https://shrewdraven.com passing with an "A"

**Comment by malgorithms** [comment]
You're missing an intermediate certificate, and a lot of browsers / servers won't recognize your SSL as working. For example, this is your site in Firefox:

![image](https://cloud.githubusercontent.com/assets/614943/9881764/6cb9c744-5b9f-11e5-9868-a9c7cd72dfa2.png)

![image](https://cloud.githubusercontent.com/assets/614943/9881776/7dd2f546-5b9f-11e5-8388-e1710bd86fba.png)

Like Firefox, Node.js doesn't come with the intermediate certificate(s) and you should be hosting them on your site.
