### ISSUE TITLE
Something is wacky with email templates

### ISSUE THREAD

**Issue by aliceriot** [keybase/keybase-issues#1766]
I just got an email from ya'll, which looks like this in gmail (chromium on ubuntu linux):

![2015-09-15-213250_1427x738_scrot](https://cloud.githubusercontent.com/assets/6207644/9894410/992856ae-5bf1-11e5-990f-fff92a6486d4.png)

I smell some JavaScript bugs!

**Comment by malgorithms** [comment]
fixed, thanks!
