### ISSUE TITLE
Support multiple primary keys

### ISSUE THREAD

**Issue by flamsmark** [keybase/keybase-issues#178]
This is probably a future sort of an activity.

There are plenty of folks who have more than one key. They could create separate profiles for their different keys, but then you might have the same social media account proved by multiple users, which seems like the sort of thing Keybase might want to detect and warn people about.

Instead Keybase should support multiple keys on the same profile.

**Comment by DarkDimius** [comment]
+1

**Comment by zQueal** [comment]
Although none of these suggestions are unreasonable at all, and are somewhat expected of a service like Keybase, I think this is probably the best use case here:

> as a user, I'd like to have multiple keys so that I can host one with your in-browser private key thing which isn't terrifying to me.

**Comment by DarkDimius** [comment]
Actually I have found a workaround for this use-case. By using low-level `gpg` commands you can prepare a private key for keybase that doesn't include private master key, only includes private keys of two subkeys(one for encrypting, one for signing).
Here is a manual: https://wiki.debian.org/Subkeys.

**Comment by liljenstolpe** [comment]
+1

**Comment by dashohoxha** [comment]
:+1:

**Comment by chigh** [comment]
@DarkDimius I like this idea a lot. Thanks for that!

**Comment by maznu** [comment]
My keybase key is a key-signing key. It's an identity from years and years ago which I only ever use to prove my identity (i.e. sign my day-to-day keys, which are per-device — exactly the sort of thing zQueal and justinabrahams are talking about above).

While considering your support for multiple keys, it'd be great if we could somehow mark which key(s) other keybase users should use, possibly noting their use purpose. I can see that being helpful for people who have a personal key and a job-based key (e.g. they're part of a security team).

**Comment by ngulden** [comment]
+1

**Comment by oconnor663** [comment]
Help us test this! https://keybase.io/docs/cli_kbstage

**Comment by oconnor663** [comment]
Closing insofar as this is [*totally happening!*](https://keybase.io/blog/keybase-new-key-model)
