### ISSUE TITLE
.lol TLD does not get seen as a real TLD.

### ISSUE THREAD

**Issue by NurdTurd** [keybase/keybase-issues#1789]
The `.lol` TLD does not get seen a TLD. It simply says:

`could not query shel.lol. Are you running a site there?`

And yes, my website is correctly pointed. If you would like to check that. You can view the site perfectly fine here: https://shel.lol

I'm not sure as to why this doesn't work. It worked before, but doesn't now.

**Comment by dtiersch** [comment]
Are you sure the domain `shel.lol` is correct? The Google name servers are returning:
```
$ nslookup shel.lol 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find shel.lol: SERVFAIL
```

Opening your link in a browser resulted in a "Server not found"

**Comment by NurdTurd** [comment]
Hmm. That's weird. These are the DNS settings I have hosted at CloudFlare. And everything I know is pointed correctly...

https://shel.io/f/7DQ5.png

**Comment by NurdTurd** [comment]
I have re-added my domain to CloudFlare and re-added the DNS settings. Hopefully that fixes it.

**Comment by NurdTurd** [comment]
![Screenshot](https://shel.io/f/8Bf4.png)

We seem good to go. Sorry for the trouble. :)

**Comment by NurdTurd** [comment]
Wait... It still says can't find domain when selecting "Host a File" for proving.

**Comment by chigh** [comment]
The keybase servers use a caching server for DNS; they do not query the authoritative servers.
So, the cache will have to expire before it will pull the correct information for your domain. IMO, this is somewhat of a limitation.

**Comment by NurdTurd** [comment]
Alright. Thanks for the info.

**Comment by NurdTurd** [comment]
Alright, looks like their cache cleared pretty quickly. Everything works now. Thanks for the help guys.
