### ISSUE TITLE
Error while revoke site proof

### ISSUE THREAD

**Issue by fvalle1** [keybase/keybase-issues#1800]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I tried to revoke my proof for my fvalle.me domain using th GPG+bash+curl mode

Terminal tells me:
Code: 901
Name: KEY_NOT_FOUND
Description: signing_kid 01014676658217fbf1bb8f46455022d7db6daea9fbdaace178c279206d1529062cc30a not found

Why?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: https://keybase.io/filippov

iQEcBAEBCgAGBQJWEqTrAAoJENmbWkp/Lt2BUS0IAIfZCCwrrkyHrxu7Bpf0SaWD
llrVTxEeDVeeiaAfzGmKa3V0rhRr7FCGFf2PsYHdpWTyBETrphpvQcFlJH4Mwmcp
QeTKWuV3tmvZshJ65MLGaXcxqZPqT4iH759ZYbf45mXZOM2z5DDzGf1VQn6IWSc/
Q26Npx/wSDvCjGwPn86UuVva+I9aOHGdY2uRF0QMGKUyBy5eU2WQhu0d5X9jECqb
uuZeKwIcjQFpuNSmWsgDbk8ifUhyn8W+SspUkmk4EGGra7Lbzy079RXTAFO7OM3M
HX7D34s4NYYckF/ecEZnPvPIvYEyxRmQl/FbwhptRTwX7e6s0aqYrrAuWpk4Xpc=
=8MXN
-----END PGP SIGNATURE-----

**Comment by oconnor663** [comment]
It looks like we might've introduced a bug in key uploading. I'm trying to repro now. Can you confirm that you recently did a PGP key update using the website?

**Comment by fvalle1** [comment]
Yes I updated my key through the website before trying to revoke the proof...

Filippo

**Comment by oconnor663** [comment]
I got a repro. Thanks for reporting. We should have this fixed today or tomorrow.

**Comment by oconnor663** [comment]
@fvalle1 can you confirm that everything's working now?

**Comment by fvalle1** [comment]
@oconnor663 Yes now it works!

Thankk :-)

**Comment by oconnor663** [comment]
Awesome, if not I was all out of theories!
