### ISSUE TITLE
Error 922 when trying to sign own key

### ISSUE THREAD

**Issue by Odysimus** [keybase/keybase-issues#1803]
I just got started, uploaded my pub key to the site and when I was asked to sign the key I elected to do so with the keybase CLI. Logged in fine and ran 
```
keybase push
```
I was given some information about adding username@keybase.io to the key and presented with three options to add that address. I chose to do that myself (option 1) and the program terminated with the instruction to re-run the command once I had added the keybase.io address.

I added the address and re-ran the command as instructed and this time was told something about the key already existing and I needed to add the update flag. I did and was presented with the error 

> error: This key has been your eldest key before (error #922)

No search results returned any useful information, at least nothing pertaining to this error. I tried deleting my pubkey from the site to start again and now get the error on the site as well.

**Comment by zQueal** [comment]
Sounds like the key may have already been added to your Keybase profile. Try verifying that the new key is already in your keychain and doing a `keybase push` and see what that does for you.

Or is that _where_ you're coming across your issue?

**Comment by Odysimus** [comment]
```keybase push``` is where it came up first

**Comment by oconnor663** [comment]
This is probably my fault, I changed some code around key pushing recently. I'm trying to repro now.

**Comment by stumped2** [comment]
I'm having the same issue, only I already had my key setup on my profile (needed to update it though since I renewed it). The only way I could fix it was by pasted the armored public key to my profile.

And In trying to help @Odysimus, I reset the key in my account, and now keybase push doesn't work, and pasting the armored key to my profile through the webui doesn't work either. (Webui doesn't post the error number, just "Server failure: This key has been your eldest key before" which is the same error as keybase push).

**Comment by oconnor663** [comment]
I'm not able to repro this. Here are exactly the steps I followed. Could you please tell me where I diverged from what you did? (And also, what version of the command line client are you using?)

1. Sign up for a new account on the website.
2. Generate a GPG key locally, and paste it into my profile on the site.
3. Choose to add my Keybase identity to the key using the command line client.
4. Log into the command line client.
5. `gpg --edit-key` to add my Keybase identity to the key.
6. `keybase push --update` to send the new version of the key to the server.

The above gave me a success message. Were these the same steps that failed for you?

There's a separate issue people are running into here, which is that we do indeed explicitly prohibit you from reusing the same key again, if you've previously reset your account. Resetting is the menu item that looks like this (and is confusingly called `revoke` in the command line client right now):

![image](https://cloud.githubusercontent.com/assets/860932/10352153/68267b54-6d1b-11e5-8d36-a239d4c32c22.png)

If you're running into that, the current workaround is to generate a new PGP key for yourself and upload that instead. Of course that doesn't work for a lot of people who want to keep using the PGP key they're already known by elsewhere. We're working on relaxing this whole restriction, and hopefully within the next few days there will be a way to reuse the same key after a reset.

**Comment by stumped2** [comment]
@oconnor663 

Version: 0.8.16

I already had my key setup on my account from roughly 4 months ago. I tried to follow someone, it told me I had to have a key with my account (I assumed it was because the public key I originally uploaded expired). I tried to ``keybase push`` for the error 922, also tried to log out and back in, told me I needed to ``keybase push`` but still resulted in error 922. Tried to update versions (turns out I screwed up path related stuff so it was sticking to 0.8.16). Finally, I just pasted the exported ascii armoured version using the webui and that worked.d

Also, I didn't know that keybase porhibits te use of the same key again, and I guess that is what I'm currently running into.

**Comment by oconnor663** [comment]
@stumped2 I'm a little confused reading your description. [Here](https://github.com/keybase/keybase-issues/issues/1803#issuecomment-146248020) you mentioned that pasting your key into the web UI didn't work, but [now](https://github.com/keybase/keybase-issues/issues/1803#issuecomment-146344900) it sounds like it did work. Could you please file a new issue with steps listed [like this](https://github.com/keybase/keybase-issues/issues/1803#issuecomment-146343509), and tag me in it?

**Comment by stumped2** [comment]
@oconnor663 Sorry, that is a little confusing. Pasting my key doesn't work after I have "reset my keys and start from scratch". The webui pasting worked before I did that.

**Comment by Odysimus** [comment]
The steps I took were:
1) setup new account on the website
2)Paste public key to account using the web UI
3)Login through CLI
4)Verify key through CLI ```keybase push```
5)When CLI instructed to add keybase identity select option 1 (exit and do it myself)
6)Add keybase identity with ```gpg --edit-key```
7)Re-run ```keybase-push``` as instructed after selecting the exit and do it myself option from the first run
- This is where the first error comes up indicating I should try ```keybase push --update```

8)Run ```keybase push --update``` get error 922 "this has been your eldest key before"
9)'Reset my keys and start from scratch'
10)Error when pasting key through web UI, and when running ```keybase push``` with and without the  update flag

**Comment by oconnor663** [comment]
Ok, there *was* a terrible bug, and @maxtaco fixed it in https://github.com/keybase/keybase-issues/issues/1806. I would've seen it if I'd repeated my own step 6 twice, so now I feel foolish.

For reusing eldest keys after a reset, I will have an update in a few days.

**Comment by oconnor663** [comment]
Ok, reusing an eldest key should be possible now. You'll need to upload it via the website, either by having an your encrypted private key on our server, or by using the "command line with [bash + GPG + cURL]" option. (The command line `keybase` client won't work for this upload until the next major version is released.) Please try it and let me know if you run into any problems.

Known issue:
- The command line `keybase` client should generally work again after you get your key uploaded, but reusing the same BTC address runs into an error. As above, doing it in the browser is a workaround.

**Comment by Odysimus** [comment]
It does appear to be working fine for me now. Thank you.

**Comment by oconnor663** [comment]
Awesome, thanks for putting up with the wait.
