### ISSUE TITLE
Fail to prove Reddit profile 

### ISSUE THREAD

**Issue by chj1axr0** [keybase/keybase-issues#1805]
Having an issue proving my Reddit profile. Tried it on the command line and in browser and no luck.
Not sure what is going on but it will not recognize that I have posted.
 [Reddit proof](https://www.reddit.com/r/KeybaseProofs/comments/3nt95e/my_keybase_proof_redditchj1axr0_keybasechj1axr0/)

**Comment by oconnor663** [comment]
The text of the proof just says "[removed]". Did that change since you posted your issue?

A lot of people have issues on reddit when it turns out they've been shadowbanned. That doesn't appear to be the case here, but it might be worth confirming.

**Comment by chj1axr0** [comment]
Thanks for pointing the shadow ban thing out I completely over looked checking on that.
It seems I am for some weird reason. 
I am in contact with the Reddit staff and will close this issue.
