### ISSUE TITLE
Used key before

### ISSUE THREAD

**Issue by SvenKortekaas** [keybase/keybase-issues#1808]
I made a mistake and deleted my PGP key in Keybase.io but now I can not re-enter it. 

keybase push gives me this error: error: This key has been your eldest key before (error #922)

Can someone help me?

**Comment by oconnor663** [comment]
Take a look at what's going on in https://github.com/keybase/keybase-issues/issues/1803 and https://github.com/keybase/keybase-issues/issues/1806.

There's a lot of noise, but the short story is that we're planning on easing this restriction either today or next week. Sorry for the trouble in the meantime.

**Comment by SvenKortekaas** [comment]
How to know if it has been fixed?

Till that time I can not use Keybase because I don't want to create a new key.

**Comment by oconnor663** [comment]
I will comment in both those issues and this one when the fix is ready. Sorry for keeping you waiting in the meantime.

**Comment by SvenKortekaas** [comment]
No problem. Take your time! 

Keybase is awesome!

**Comment by oconnor663** [comment]
thanks :smile:

**Comment by oconnor663** [comment]
Ok, reusing an eldest key should be possible now. You'll need to upload it via the website, either by having an your encrypted private key on our server, or by using the "command line with [bash + GPG + cURL]" option. (The command line `keybase` client won't work for this upload until the next major version is released.) Please try it and let me know if you run into any problems.

Known issue:
- The command line `keybase` client should generally work again after you get your key uploaded, but reusing the same BTC address runs into an error. As above, doing it in the browser is a workaround.
