### ISSUE TITLE
Armored string format in kbpgp.js

### ISSUE THREAD

**Issue by lettergram** [keybase/keybase-issues#1813]
This may sound like a silly question, but, say I wanted to decrypt an armored string. What would the format have to be?

I couldn't just copy and paste the following into an armored string:

> armored_string = "
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.47
Comment: https://keybase.io/crypto

> wcBMAxcYngj9wWUrAQgAhA8fTzqewGOzxUaU15hyqYsoya/Iebon5N8CJPTv8+51
aOIXmOlSGBuUJgBUEebjvfgW0pLK9i9OPLEOB9XQ72ccep6b6ujREISnnB8fdRSI
80iIJ7A37lN5BdXPpot1gBRObMecE/PubV/o1p3rTOYAVgAHQMA/mgWDv2jVgOt3
IvvzK6uU2uTzc5QdF5U7FVeQo2b3iQ+qNH3YG+pv4gTIZeqdQwrDEG6SaPMtSk06
sx45uBAa44q0JiPMNu3qi4OW4IN+4fWdoQwHs+mdFw4sjWlQixrpu+FdmvwAD6Dz
Trou1kxr+fqj6+JjuY0KUZxPojdbaTUUwusfccNE38HATAMXGJ4I/cFlKwEIAKfJ
tCBQw4ieB6S3RUWdeCQ0tJof8k97VouPK7NwjBSL9Q9uhlCupfeiSGM4JbxG03yC
lPUPMsQm/bI1rvITr/yFf9OBNcpXYK9GfH+Oh9ZW9R9iCV4uTPik0XitEVkPlLoL
DTTZwtcFdzbi5GmV0lBEsWJX7eaNmIdadH894soe7dnq49lU+JFN5oDziDZNPn/w
SlkD8Ghr23QSgQRsITmt+3lX8xZqrkW7wW6drgxpk1nXItoBh0soPLlwiAxNo/Du
DbmFtUk3RxSpKaNiUf+8BSgb87yNPUzTmvdgksvV0O5As8tn8hD/Nd7N/7tmNuJo
LaLwfUgWyla0GLW3zNPSQwGH56ryQLjKGx4DLK170JAQ8Jqr1JD+81J0VNJvH0N6
4ftzc7KB5YxP+PXFHA1/K3Q/9rP/8MjP2sY6ZyF+9D2NvOY=
=tzXa
-----END PGP MESSAGE-----"

    kbpgp.unbox({keyfetch: keys, armored: armored_string}, 
         function(err, literals) {

I would need to either have spaces, or \r\n at the end of each line, yet everything I do seems to fail for one reason or another. I have received errors ranging from:

* No header
* No keys match the given fingerprint
* Error: no tailer found

I just want to know the format, and it doesn't seem to be listed anywhere (or I seem unable to find it).

**Comment by oconnor663** [comment]
Are you following the examples here: https://keybase.io/kbpgp/docs/decrypting

You shouldn't need to do anything funny with the format. A normal multi-line string is correct. The `No header` and `Error: no tailer found` sound like errors you'll see if you try to mess with the key format, but the `No keys match the given fingerprint` error sounds like it's actually your problem. Are you certain you've loaded the decryption key properly?

**Comment by lettergram** [comment]
This works:

    encrypt = function (keys) {

        var params = {
           msg:         "Chuck chucky, bo-bucky!",
           encrypt_for: keys
       };

        kbpgp.box(params, function(err, result_string, result_buffer) {

            console.log(err, result_string, result_buffer);
            if(!err){
                decrypt(keys, result_string);
            }
        });
    }

This does not: 

     var armored_string = "-----BEGIN PGP MESSAGE-----                                          
            Version: Keybase OpenPGP v2.0.9                                                    
            Comment: https://keybase.io/crypto                                                 
                                                                                               
            wX4D5LHWIIBmOGUSAgMEAM6uk7fTgyqZDdn9HCC7t4gTsslNgM7bPdN+ac8ukFob                   
            zGkJS3Rbgdxh7ZZQFyIsLcdm4rydRuct2Hx8jTMieTAckfwD2kF2RONtd4ST2mG+                   
                Tw0Ps4dLusFE9/9/ATMLtlb7hSGsqEl+ee82QXRN2QrSTgHrKtjY72PGxjVH4Xnu               
            DEnzsl4kQz1D3bpf9ToZmpL1QscPMmjMyiq93pGpYHyVTXBcfXV//FY5TP16k3cW                   
            AxVzYfPtd/6sqDNn7eBk+A==                                                           
                =dWYH                                                                          
            -----END PGP MESSAGE----- ";
    decrypt(keys, armored_string);

I copied and pasted the pgp message from the console output in the first working example.

**Comment by oconnor663** [comment]
In your last example, I'm worried about the spaces you've added on the left to indent the PGP message. Hard to say without knowing what your error message was. Does it work if you dedent the message all the way to the left?
