### ISSUE TITLE
Unable to update expired key

### ISSUE THREAD

**Issue by dainnilsson** [keybase/keybase-issues#1814]
I recently renewed the expiration date on my public key, but forgot to update the one on keybase, which is now expired. Any time I try to do anything with the site, I get an error due to this.

I've tried updating my public key by pasting the non-expired one into the "Update my key (I edited it elsewhere)" form, but after doing so Keybase is prompting me to sign this updated key, which then fails as my key (on Keybase) is expired:

Your public key appears corrupted (no valid primary key self-signature)

I've also tried using the Go command line client, but I am unable to login, as my key is expired. At least I assume that is what happens:

$ kbstage login
▶ WARNING Running in staging mode
Your keybase username or email: dain
Enter a public name for this device: X1Carbon
How would you like to sign this install of Keybase?

(1) using PGP   (requires access to your PGP key)
Choose a signing option: 1
▶ ERROR EOF from server

**Comment by maxtaco** [comment]
Thanks Dain. I will take a look today.

**Comment by maxtaco** [comment]
Can you send the key that you used in the first case (when attempting to update via the Web site?)  I haven't succeeded in reproducing this bug in testing.  Thanks, Max

**Comment by maxtaco** [comment]
In particular, @dainnilsson, I wonder if you tried to upload the expired PGP key a second time?  The error message you got would be consistent with that.  In my own experiments, it should work to upload a key whose life was extended via the Web method.

**Comment by dainnilsson** [comment]
I'll check again tomorrow to make sure I'm trying to upload the correct
key, and let you know the result, as well as post the failing key (if it is
indeed still failing). Thanks for looking into this!

**Comment by dainnilsson** [comment]
Ok, I tried the same thing again, with the same result as before. This is the key I'm trying to upload:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFLP7UQBCACbOjmf0DRdtSjxFpTk+a5+Wa0syMbOc90IyRB9BXldK5FhMESt
EuGw2uuXqzu45VRGslCl3h4Hyo2ogcyNT1dZQT9IcG/k/m15gZRRnyIiKftIqrTE
Rvp3Kt5ykoVe1UuSh7jmc9W6YYBuaekOgCFdOZEdGQ6cdZ3+y4hyXDDnLikR+qFd
Aywxvw1V7+iN+mW72FnyMZ0ncPfjvn1czjQGZ2mH1fQ1e3hvganPKZ2296J9Osuv
luQ2O31TSHpeH7xCIzDoctm7AiTo7xxsYzLQV8gG+aRwlg23uW1g4A0ef5cS3t7C
oyNEjToB+ub2sODSAR4qvRwsTrYAOSTxCHzpABEBAAG0HkRhaW4gTmlsc3NvbiA8
ZGFpbkB5dWJpY28uY29tPokBHAQQAQIABgUCUs/3qgAKCRDzcp584lTplHxPB/9h
dwV3m4tpL3z6EUy+GXBp/kpw0EJOWmWg3X/e1ywU1JMTale8t4tvb0JlAHE8V99D
nDrX6w7TqBJreeT7svvHx+/sKAFLO8PsAWkiAXgooc2DBUw+5ZcEQvzo9UxTOq6G
b5pwfQQVuOPEMuU27CMPdTsTsko+vm9WvvF7qFu7Q3jG+y5vOGwEdxh4zw0gKKaI
srVjABuCHodPmElNLVQOb9TRU17oFjzG4udcH16NigU7nscEjMrsz7mlMKB0HmJf
WvmBwrgm7rVPEe9pOxp3AAUMCPoZM8qcyLD4tDpz2TDqmdS1MbvBi7Ywenr86uZ1
4YqikhQO5GyHg4kIO8cEiQEcBBABAgAGBQJS0BkIAAoJELSQA9lXl5dSlNUIAIhk
Qbwl9By1EJ7oVIBJIJUi+GxpmydVPmSYo0WW/C7VGLakuZlhvS7kYdjLLhrXieik
ZnrTOK8RbGxrfX+17bv50LBsGhQEwQbN4TOi/gRlZhrKXIlEtG2v/1nx0xfaBdUd
d2h2jW+ZAMsy4KFTI8v6xYNeDGreFbODGBnFzK+cQHqKW4XxAWfR94eCR9uC0Iyz
Y6Gn7JTRrINxeIklVi/CICmOAR1bDhHnBgl5U6pF8tprOWLPdvMpMIwC58oYVr9U
xEdbff4miTtniU/T4rERMUxr5HxoSM0p5T6MnJ+DavBEmIO09bNHZ8idiYqWjy+n
kISHH2kU/ZqwcBswU9SJARwEEAEIAAYFAlLQGMMACgkQvKAP1LIWjAqaHQf+OvDl
pN4bZtmpH1rH/dLzNvGhc3Mn6vSKcc/SQ9FyoOiEnuOEB5rOYHAhOyj5tdGgfKCm
9YxLrHmH1Fbvsq6cwjze+UTM0inweJspYBlNPlSsA3DkRvINZnBkJkIfK3QQRPpc
FW64BbElCu6tyoA+83NONw4ji/QvdFfsTuEcW3LhUpne700qc2x/bNEEE0W6eUkt
vUyqkgLeTXCdlzbwxaNSOBvB+85hvfcXy7jqF1t9C8NkfBF3FBXrBAtmqzQrJIb1
91cxRezQNScu3juNI18mrzJhPwCE25IhjLZCqU8dSeeVmHhqr6wsR1BFFjBtehdj
RZVa8t1C+8Wq7B5RQokBPQQTAQIAJwUCUs/tRAIbAwUJAgIpAAYLCQgHAwIGFQgC
CQoLAxYCAQIeAQIXgAAKCRDwQ2cJb7qV6KKjB/wJMdXrSvIthIErNnQg8bR9gqHL
/Ke6Q+hwA7hNn7X2eFVaukNoAvEa4SlYXAUpydH6TsElXTxxglNMu82RDyWXKaAL
e3XSgswDRVJeRceP+Ejsf4dfxAprzFICcShZj5HKZilg0taeaHPF1ZWKDWe024kq
2DfIsb8FZ0qClgCxbPtQlo58WWF7p5ce/byLPZVPIskLRM0nxTsQk8y1RTsGM6rI
OZVqxoc+zDLtarAyR1d6kycI6d5nmtxzuveMK2V5LrvV6+Q3apLJqj6P1mCLy2Ds
u/WRwanFvyk6U+B/j3sS0BTLe/GxvBQIaaLerNLl/CIRqjtUadF45CSxOBX4iQE9
BBMBCAAnAhsDBgsJCAcDAgYVCAIJCgsDFgIBAh4BAheABQJWFkhQBQkFK4LUAAoJ
EPBDZwlvupXoP0YH+gOEjOQlZLxsq/wIolhR2ybE543IEedapxSWAikLclXW/H9B
l+wADh9FU+ZArCp6KK4YjHXRE76LOZ5SYGvwXmKZBpEk2pZP1ta7pvMwkFmVh2rn
KW+mdrDuGBeTCHTUoBevlPD57/EDqVDuvSk/u/40L+P3OhyWly55rpCPOiu00hsu
CQGs12iuJSnorzCRVpMyDBEzzzbKnJ2zBNQVfbzUOLBMXeQcDBZxlmfwHolOiBIu
5zJK55AQnK/ECldIwB1LKjABOgs3Sc+UNSzsKtM7jqIE//8BUyyCmpfv4ruDprkM
HywxULWvNN3kFDaALSwXloamYHtDcl9b+bAtWZKJAfAEEAECAAYFAlRvI7YACgkQ
nqkCQpWOBljsRw6eO6M+6DbK3SLn+IhZSMZU9kNqg3V7Lc6zHSZGGNX67kLcQ54w
4reJaH/OQBJ7P5gkkYYldnfeqKFd+j5X454JKG5m6yCXC6z8UQAhju6RoQmE0Mcw
l7bvmasQAO9qYdGm88MYhhi3M3KW4iksquTjeojSU5+qTy+BrOkVgndXHfzgCsnq
h7vdKgxvDT+IIUDmiw5zyg6h/04CPdUFADr51R1JmnGsnLr07ST62azPPPcptdkE
Z539hk3YGOVbUwa5cWtrX+imUToptVVMvkYspNPWBEd0hT8V6d6tlLjDMU6cBMvS
i5FTnEoH1RkK/jO9T5Tl2SOl2+xCxdWzBrPpoXhiHrU9UCTynJKEu9p+iBw61kCU
jxALkhpsAPzteJ0tD8nCjRprMWTeeikJhtXgXb6zLyD/dhy0DS5OGpZhUJDtUf6B
xS6OyqZF875R1N1TjCbnrRIZm0XRQMqGbRC5By0zHLAtTUcCIX8EWWOWzH+knDGd
I1FqFMm4qGzlfrtWquyAjLxgM6EkjH+d4EKlFoW8S8OdOaumUwDT2OAbte8Jm8Uy
aeAaoyn4SI+hpdqpFHiqsv5vQeKfZf65eQlUoUHsUQuEXdab0yRPpGnsNWM3WBkS
iQHwBBABCgAGBQJUtYccAAoJEAZkp2lUJl6MGhEOnjHIuHPe3QXAxDG5/CVJAqlS
Q9ie7n0oiF3i1MHGqsSSNtBaSQHLsB/2DbzaISIQzX+cFnjHb7mVRZIvcOI2jUtP
e6Rl3QEysPYfemPVx/aI9cBHWcSe5HFUNjUOWKC12v9uNcCGYe8MgZ89O4kfq2Gx
+3UitMbIf/vw1BpPSnWCbfo9NRK9lj1q7IR5ZfK0k5EhtiuMEuDEG6ulTn3DMfou
sYqPUqMoQE05+dqrcBYSAgLpicewBFS0dNgQJrn/qMNY1kcrN8+5P4hayM79Byls
/5SlB/Pmr3eptpao6/Zz2M/x72sQOLd0eB40Psuf+1q6fRLxTidb85MtnbVliFJj
Ci22EuUXvEHtOQ5zoqkR2dK1B20kqvex2oaArxYu07zycgZnKx95qCDSoZwGyQnQ
knJhBvAFn1j8Ab1ZaS9sZk3XnaJu+WMlyLqPdI8rwxT/7M6wRp6t5OlsBnz8nBUU
eTTnsXiWGvrGYaNJeC2/eS/IrFc9xYYj/bCth1oQmx64/lyyu6CNzbA3Ko8QmAic
ol9Q9fhqWxdCC8mQ5FDCpxQly7Q1O7gNyA5dQJEGsgbr92Q8Zo019CPh4jPUvnkI
kIptYoX2tSGU14s1SQG1EwyQiYkB8AQQAQoABgUCVNDREAAKCRD/jTtFt7h1qdFP
Dp4rszD8Yncqv5EZCR1glW4KqoY4KKPretcMGiDKkR0oDk2tw0LNytD7gcpyJ6Eh
lY0SxdUtHfyUBR8hoDOrSr21Qxe0By0tUnOPH0cyNGfWamNno/PhZfQfSPXgcRrn
ShHXCszXV+tbvlpGeN6FBeGBF/PBI7+yqo3LVbmeMGsf3Ytgh++qn6sYQib3PEh1
3Y/BuyfoKXxDgrQbcdE6IShryUOL1aMfQQxONlDWzEF/dUAme281g53FPnRF3gj6
rNqBRzqSWhx3JnaWddqEYcIWtjg9MkviM4aUvoa1MYbus4Q1rNiWOTG4KWZjlCFN
v6nEW1/ECjYcCY9a3TBLM7APFtZhDICv/Clt439mqvfstqBvC3uqGypjr6ThOb0k
+3CO5Fqaz6eT6+pVuHgOQtOj/f26V/e069c2CBOg1qf2vLH2eAV4qepsyGGHaZX5
lS7XkqF1+IxIyKzqJyWo53c6AK8rDlSUbBNoBs29JFSLBISPKR11CxEVoDr8Rovz
b1Q/WmThWy6tSMRWlR0Cy52fW+ZyP81WFTeWVj7rZE/87ky9bkO+q40L/lsHvwTv
GC4HAIDzRK3wjRXR4FdUEvQC/FLfDvdsSDB+a7XM8nt45JxJ01eJAfAEEAEKAAYF
AlTcdGIACgkQrSFbm8zSpKcO3Q6fciOKorMWxp2zv4sE4mXNudG/buZcdbSP/mvR
vhndk9NaxFkbo8rMsYMIGKyEfTMLl88TWey3PKAOeUFlr/0A+MKFSoQ7avRq7bIK
q80XiQOqyUucQgZsx+QUkLeauOwGA6p0zscQK47uRMuyzx8tuqtYeqQAI/8vD4lX
XOCbpUa2JvHwHJ94iaCJ52hMQXiiljDZe3BrxG9JpcYvkn4OsKy29HDTdaQhnvEo
53QQBPD32FjrDA3uX+Fr2df2VY9inZNggGhCtDDwEafVVDLJh8SV99zDqXO1O+rh
rZNSLxf1TJcGVDHMYnRSy63ZdTL0JAAR4G6Ejai5vBaSJsXvxwd7KkPVb+7bgBU2
lzUgKdHvi51AXRfahxiGtwyNV902ql3lO89LL3NMs2lyM3a6FcEd1DrkCHlen2a4
7PRczR66GvtLtVU/tXoUSu8NlAgSzIz7ffbch+SjjJtgxFnDKYKfTa059iirpwf7
55xSgBRJyXd/6TPIkNCkW9sHRKq7mO6kJyvfTOX7PcZD7duEWeZpZB1qfVshDwGr
TWKGhG27KwjIkwryoIRf4waMJOfSoupGc8GdHj5iWkPlZccizc+lXipyAUc8Cnjs
dGnHxzmUwXmRiQHwBBABCgAGBQJVI8zZAAoJEA53fdhXVapKXvIOniew7Vebe+GO
qMnDnahd3faA3z/v8Cmi4g1p/UQRFm9kNiz+R5ISiqkhWVjUiHz+5OJDmFeqIyQZ
MGsVqcU11JS/BB0/PF082zaxpM/+tJ9cIzfALddL8BYwRO3WSM4AyYly2NY4W3by
sqe9IWMy/xLiaxaKe77S10S3oDCA/3S7fdPHb6S+LMLOJC6kBRbNzVQqK3ee66S7
AvCc4dbgCdkFcSQZxH/PhbarKzlfjqFm6mt67sFOAbzPRrbE18lqj1nIpspuGdjn
DSAUg90Ar3tvI2el3if+3d5FgoA/p6RHiBf75nhgB9rUTRdTQt/zwGaPoI+snnH1
5yYx3pOz3yOaWrWHibzWjGdPfRh3MLv7Ucv9fOPNCTd46nZjbl9IoaZaN4bFiSaC
T1AhtAFDYpoOCefBvHPgPED7Pi0jRLlXbIGxESMNXOH99HWYWfaowpeIuktEVKN6
m4y8QyBQs7I9EyYDhprPX56XPAhVShY3eAbYDYSetW1+yi6AXFsz/dzXtDKCXlxH
c0F/oUV4rSEsNDTgPWJjsQiSU5mWBzz6dUHTe2ZvRpn6IACDcZXHCLieyY6BMS0Q
UchnKBso7phsyJ52WmNocCB1Dlg2BrhM9lPWZokCEAQQAQoABgUCVVynnQAKCRBy
2nXGEKIVS6wBD59CZq/L8yPhl+NszW5F06Spxp3V/U6cSpi8YH7xCD2UFEM/reHk
IntFL+HOfWxgKuPPQbPc40ZdE9vyjA2LN/icMP3f/0UKUeAMuJbhIHrzSf02RB3U
sf3DPWJbPjg8zoDwmlAu76UdwBBLelrioJ7mRJBl+QV00vsrmDTITVu47g54WdRr
GgMdyS1vXrM0l5+cLDv5DLOxWrrC/tCPysj0ftylwL9IAGjlapqb8CNV2u1stU4O
NsURJUSScmLY4wi2Oo0AfaaqBVYDTjpN1SW5Iq5fLCjFrraQF+94WlFTmTX9XJJ3
JJnGdxNutOaNtHYNdMNp8ETLiOkfxj6uLXajoO+a6Wkznhp2Anihusv2xuU0Z6eV
eD4wx4YaNn0LKC772xWH07OZoGp/7cn8tfdLyhACxxJSfmWBPXNw/SNny6d4gifA
dXUV+99sBv/WAgddmOG2zcmxluxVSjwiAYG+iCeRiyfy9en8+B1hw5OVzzsMmk0k
7VwK4WSztOUuBwOeUpGHx6gq0y9PDjIxvjOEbp4BN6y7FgE/4ZGJalUsDFM0abC5
mCchznGMfep41DiDt0fKrM9Wqy5N7UfbqfaXDAbuQaqpRS6NwIx22CWkUSNF+LD6
TtWVcsTo10AG4gN7sFSWqWxXmeR+ZkR9cU3LcU9YZIkCHAQQAQIABgUCVPmPFQAK
CRD8w3Z0RJ48/I4GEACx+xTqBfYsWsFaZkzl9afUCxr3PD0bzezbiJWz/tlAUktm
lq6jylDvu8jtE2lJCgv2eTr6F2vTLRXPXT/mmYULcbSSaMfZtfdxzPUV7eLm09rg
XIBx07WP2LU+32Da+jpQCl11RTvFbr2UtMhBBNvCv2w/FBtJdsU2lgVsbpDYe2yt
N24nfa80H7866sBtBiehMMyG8mygldraS7NOYF6BDapu7gSGOIx9h2rl3YrLi8AF
mA4oD71t9PCpVT6p90XmfZZDvSrEgobha1gN6eqtxnHkh856Mp0egRyWwLvG3Nde
aM/ErB+0GC3bERHBOstpK4FeDtyeOUUgGdp5AAxR344N3KU2oYssxneMvlHFnUul
7O0++Bz65jekTYCsjaQEsMirnAC2MU0YcTQ1Sp8g1+AIJqFtJ80AyxaOYXFM9rAi
N+yg/q1JWzAI1UE7QW9ywxBLjcSp33j4SRqTr3NEXQkQBr02ZNKaKuPYYW/g7dXZ
q1kQflKoAQhhGHFlyY0yxz1YX4NiZPy+a+KyMZ8wUIzIUW8VSHpSjU1TbXY187xe
kHKDREI/mjP7/lJMz9bVSYhiUUN2L7Hd0UnVB3VDCQjzMUqSYnKCd4+eCbvadqmW
TUtANKTAhRgCCkwg3HnT0LNdfg2pcWDfibiQ+JxTpy+39m7WgZDB1Lo87IG84okB
PQQTAQgAJwIbAwYLCQgHAwIGFQgCCQoLAxYCAQIeAQIXgAUCVD5UmwUJA0+a0gAK
CRDwQ2cJb7qV6OX0CACGM8AZKA1mJmzCbzP24lhNR/33QjutQTOPR0uqB38UQjRw
juh1ZLhFYiE4ybY2gmetLGgwiCQAj5yItB6EohScqwbtedM3Y9i9c/SRwZi5IceZ
1RusQGdITNRXBv5r6Nri+qibjdV48tcUVQKw0HcJoSkCn8bV3LJ55PI9VWjOgQ5x
Th7F7sJCUYWsvpFxcTZIfnkTmpSTDfq2hzMq+CijpaOaMu+3uUpEH/+qFQjBoP7R
4wsZUURLwhBA4AWI1vrubdycXmxqcGbGJ63KfT0OHjNZDdiFwXUmzxu0EnxCrOkR
gWAx94sdo6+qXU8Jm3ZIrEQ3fEFEEMXGm/9G5dTbuQENBFLP7UQBCADC9z9gXsDC
+PChgqQHqH24oXVMLcDBpO7eLdu2cEuxlZE4e+7FlwBs6dS3iQz4bWfaEMvP3h5v
D1TZCQSSbTFRXQm2WAMjsPV6AadJAE+3zviI9/zDBARPYHvE4TfqPoE6SNCjOKCU
jBtluDe0fbWRrMPH8PHFQF5K96F+pSdgMd2Emvy3BMhQ9Z0MhHxXwXBEbhwZzPCR
oZ79lrsKBMiL0tZ+TYd8h8lLUNM8TObJF407o3XDRl2RrunzRbxNVGTABAqBvUqz
IXZT2pQZ8N5F2DAnCNmA8Q+ZtxFrGyKxezC40+94Ut8mdI2IOcoUV1RUiPN+w9NX
o4kD70p5xtN3ABEBAAGJASUEGAEIAA8CGwwFAlYWSGgFCQUrgx4ACgkQ8ENnCW+6
lehERwf/YnupNVbhpjW7mimFheqhHawnmCLRvvhon40nbUJK3XDkvmdseHbrvlDz
R7OVEP6XQkxOGULVYZ2OmQaMrPMIF7KA5rQbXZHVPh8Lx8mjbreRAyU8FSzYLHgn
nHOdT1A3cd0VZupM9Wh5fF64cVAOkjECsYbGa2YFnQCfrkeKZFCuDCyKFAb+G7Ld
4bgQyI7SM3X1oYynIb0IDQfk5X/DJMZdt37Q+zSSrntjAm1EZrXUa46ZokZM1HRo
WhYf9C5FgIVfKpbKYBtT5Md6hlMCpuoUMkpFG6t5g+/jJJXqCZxPrvltk5euk9F6
UuR8B6+5h6Ufd63kZqJ0oQC2iyqOR7kBDQRSz+2uAQgAsBqgHrEDm9ftgdOtVp2N
x9itj6X1cSBKyQiYWBCPrNxm3WY4Z04HTZfVRNO0lFf/J1N9KxJr0ClgPlYvjz11
PfmjBlu5MJrSPGLxGZgp+hv7cyPDw9t617NqTW59rnywl0WJBgzOXlD1Ei7HOBb1
RWBVQAuXe9mhyHsy1BBRVh2+cnZeBY9fSFWNzZvP3xNuK3vpIiBY6gqkYWUHzDxt
MvdYR0bMj5QwK1BNHd0NN4h0cuVVQOpR29GEVhqiuvV9xWqssz3XMVXU6GFRt/he
+q+j3K+SULsnFxR+nVpYGyh8JPq0CGh36dF0Dy/NFloMTD1Mn2w9m7zsofNWaWVP
UwARAQABiQElBBgBCAAPAhsgBQJWFkiEBQkFK4LRAAoJEPBDZwlvupXoTHMH/RuR
hxnvvBLq77uYqPUVAjokeSq49p9TcNx4YTxfwPztop+hk2DN84sHj4G7agfsD8ne
uYpiYuWZpxE07LkKPCNJAK0JnBSyRKSDInidsQ/M62LbZGkqkM0OhM9YO89KfPXx
j82qSh7tRrT3McHJgqX6hSFsBrMJ7N2r2q59T3PmudA2Xyqj+VMNVXK2V7dyFSot
tcXvUqEJttye5Qy8fjfhe0SJUUXm/v7g1XNunyM4RTJuGK0c33OZbGKvgIH5mZPh
gs/9hFkoqBzb/f0lQ3OoxcCendkAMcgdW2QI9CDY5Z53OcaLEzfC/nvsxQvcEz31
qimHZnabvAMiE327fMg=
=lpYC
-----END PGP PUBLIC KEY BLOCK-----

**Comment by dainnilsson** [comment]
So, I tried this again today and everything seemed to work. So, fixed I guess!
