### ISSUE TITLE
Help trying to re-prove web identity

### ISSUE THREAD

**Issue by alexgibson** [keybase/keybase-issues#1818]
Hi,

I signed up for keybase.io quite sometime ago, and proved my web identify here: http://alxgbsn.co.uk/keybase.txt. I'm currently trying to update my verification for this web identity since I switched to https.

I originally verified things using just the keybase.io website, but it seems like this is no longer possible without the command line. So, I have installed keybase, have logged in successfully and have run `keybase pull`. However I can't prove anything since it tells me I don't have a GPG secret key available. When I log into the keybase website, it says I don't have a private key in Keybase's encrypted key store. 

What's the easiest way to rectify this? If I run `keybase keygen` it tells me I already have a key registered. Is it a case of revoking everything and generating a new GPG key pair, or is there a simpler/quicker way?

Sorry if this is simple or if I'm misunderstanding something, but I struggled to find what I needed on the keybase website in terms of instructions.

**Comment by zQueal** [comment]
> I originally verified things using just the keybase.io website, but it seems like this is no longer possible without the command line.

Have you removed your secret key from Keybase? The only thing that I know of which would remove your ability to use the web interface is if you removed your private key. If you have, then you __are forced__ to proof via the CLI as Keybase doesn't have access to the key required to initiate the proofs. 

> What's the easiest way to rectify this?

Upload your private key to Keybase would be the easiest. (but many might not recomend it for security purposes) Other than that, ensure that your local workstation has `gpg` correctly installed and configured and execute `gpg -K` to verify that you've imported your private key.

> If I run keybase keygen it tells me I already have a key registered. Is it a case of revoking everything and generating a new GPG key pair, or is there a simpler/quicker way?

If you simply _can't_ get this to work, even after checking that you have your private key correctly installed, then backup your keys (public and private) then try to [start from scratch](https://i.imgur.com/JHSe9Q4.png). Unfortunately this will invalidate all of the proofs you've made so far, but if it gets it working then it's a small price to pay.

If after all that you still can't get it working? Run `keybase-installer` to make sure you have the newest version of the node client and execute `keybase version` and maybe someone with more experience will be able to help.

**Comment by alexgibson** [comment]
> Have you removed your secret key from Keybase? The only thing that I know of which would remove your ability to use the web interface is if you removed your private key. If you have, then you are forced to proof via the CLI as Keybase doesn't have access to the key required to initiate the proofs. 

This is the strange thing, I never removed the secret key from Keybase, it just seems to have disappeared? I have not logged in for some time since I first set things up.

I can't see what other option I have except from starting again from scratch? :cry:

**Comment by alexgibson** [comment]
Hmm, I can't even reset my account. 

* Via the website I get: `502 Bad Gateway https://keybase.io/_/api/1.0/nuke.json`
* Via the command line I get `error: this API endpoint no longer supported; use nuke.json instead (error #238)`

Running `keybase version` I get:

    keybase (keybase.io CLI) v0.8.22
    - node.js v4.1.0
    - gpg (GnuPG/MacGPG2) 2.0.28
    - libgcrypt 1.6.3
    Identifies as: 'keybase.io node.js client v0.8.22 darwin'

**Comment by maxtaco** [comment]
I'll take a look, seems like we have a bug. thanks

**Comment by maxtaco** [comment]
Ok, nuke should work, sorry about that.

**Comment by alexgibson** [comment]
Thanks, I managed to reset and generated a new key.
