### ISSUE TITLE
"error: No GPG secret key available for user [x]"

### ISSUE THREAD

**Issue by kevinSuttle** [keybase/keybase-issues#1819]
I get this when trying to prove any new account. Not sure if it's keybase, gpg, or coinbase. 
When I try via bash + cURL: `gpg: signing failed: secret key not available`

Sorry if this is a newb thing. I looked around quire a bit and couldn't find a similar problem. 
OSX, El Capitan, beta and stable CLI keybase client versions.

**Comment by zQueal** [comment]
What is the output of `gpg -K`?

**Comment by kevinSuttle** [comment]
```bash
❯ gpg -K
/Users/kevinSuttle/.gnupg/secring.gpg
-------------------------------------
sec   4096R/413A560C 2015-10-19 [expires: 2019-10-19]
uid                  Kevin Suttle (El Capitan) <kevin@suttle.email>
ssb   4096R/020A77B9 2015-10-19

sec   4096R/0D75B59A 2015-10-19 [expires: 2020-10-17]
uid                  Kevin Suttle (Custom CLI-generated key) <kevin@suttle.email>
ssb   4096R/A2D9F0CF 2015-10-19
```

**Comment by zQueal** [comment]
You might be forced to use the `kbstage` Go client for the time being because of your multiple keys. If I read correcly, in another thread you said that you've tried the Go client; if that's true, give:

    kbstage pgp select --multi

and the client will ask you which key to use for `kbstage`.

```
root@dev ~# kbstage pgp select --multi
▶ WARNING Running in staging mode
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   B1DA56DCB73E8516             Zachary Queal <zach.queal@gmail.com>, keybase.io/zqueal <zqueal@keybase.io>, Zachary Queal <zachary.queal@mycampus.apus.edu>
Choose a key: 1
You've already selected this public key for use on Keybase. Would you like to update it on Keybase? [Y/n] n
▶ ERROR Key is already selected for use on Keybase
```

**Comment by maxtaco** [comment]
Thanks for the feedback Kevin. Your profile shows your PGP key as `23F1B6E0E9D8CF86`.  Your local GPG keyring doesn't seem to have to corresponding secret key (as seen in your `gpg -K` output from above).

**Comment by kevinSuttle** [comment]
Gah. And of course I can't remember my local passphrase. Looks like I need to nuke and start over. Instructions?
