### ISSUE TITLE
How to migrate to a new key?

### ISSUE THREAD

**Issue by alex** [keybase/keybase-issues#1824]
I set up an account on keybase, verified my key (never uploaded it to keybase), got some followers, etc. I just generated a new PGP key (to move it to a hardware device). How do I add a _new_ key to my keybase account?

**Comment by linuxvorpal** [comment]
In your profile there is a gear icon. If you click it you will see 
"Reset my keys & start from scratch"

That should do it.

Regards,
Travis

**Comment by alex** [comment]
Indeed, thanks!
