### ISSUE TITLE
Support for Teams

### ISSUE THREAD

**Issue by CharlieSu** [keybase/keybase-issues#1826]
A large portion of our workforce uses encryption and KeyBase, and it would be nice to group them in a trackable way so that sending encrypted messages to more than one person at a time is easier.

**Comment by malgorithms** [comment]
We have a good plan for groups/teams/orgs on Keybase, but it's a few months off. There's a lot to get right. Group membership itself has to be an auditable system where the Keybase clients don't trust the Keybase server. 

We'll get there.

**Comment by fidian** [comment]
With the advent of the Keybase Filesystem, it would be huge if we could designate a shared folder for a team and be able to add and remove team members. The same could be applied to the new chat system.

Currently:

* A group of files can be shared to a collection of unrelated people. A group chat is a message sent to a collection of unrelated people.
* Adding someone means making a new folder with the new member and moving files.
* Removing someone means making a new folder without the old member and moving files.

I only see this problem getting worse as additional features are added and it is preventing the use of Keybase on a larger scale within our development team.

Ideally:

* A grouping of users can be created and managed somehow. Users may join a group or request to join if the group is moderated. Members can opt-out of a group or be kicked out by a group moderator.
* Sharing files and chatting with the group would send to everyone.
* Adding someone to the group would entitle them to the shared files and historical chat information without anyone else making a new folder and moving the file contents.
* Removing someone from the group would revoke their access to the folder containing shared files and lock them out of the chat. Of course, if the user made a backup before that time then they would still have the files and chat logs.

In October 2015 it was stated that anything along this line is a few months off. I assume that this feature was a lower priority than other items. Is there any progress being made towards supporting any type of group membership system in a generic way, so the filesystems and chats can both leverage this type of functionality?

**Comment by cjb** [comment]
@fidian We still agree this is super important, but don't have an ETA to share with you.  (We're working hard on getting mobile apps out at the moment.)

**Comment by josh-padnick** [comment]
We're looking for the exact use case that @fidian describes. In fact, this may well even be a paid feature for Keybase. Just to give some color around our use case:

We started out as a small team of 2, so manual password sharing was good enough. Even though our team are experts at setting up services like HashiCorp Vault, we know enough to know that maintaining *any* extra infrastructure costs money/time/attention, so we prefer to use existing services.

For that reason, we started by just each purchasing 1Password and then setting up a shared folder on Dropbox to sync our Vaults. This actually worked pretty well and we paid $0 on a recurring basis. We also got the slick 1Password UI. We had some reservations about using a closed-source password manager, but we basically were willing to trust that 1Password has no access to our secrets as they claim, and we kept our most sensitive customer secrets outside of 1Password anyway.

But then 1Password began moving to a cloud-only/subscription-only model. We don't really want to commit to $6/user/month for the rest of our company's life, not to mention put potentially critical company secrets in the hands of a third-party, so we began looking for alternatives.

Our current thought is that HashiCorp Vault, while an amazingly well-written piece of software, is still overkill for our needs, so we'd like to use a combination of Keybase File System and Amazon Key Management Service (KMS). This way, we first use Keybase to securely share files, but the files that we're sharing are themsleves encrypted using Amazon KMS. This gives us two factors from totally separate channels, not to mention that we can remotely disable a user's access to KMS.

But now the issue we run into is how to share secrets among our team at scale? For now, we're left to just keep appending another username to the KeybaseFS folder name (e.g. `/keybase/private/user1,user2 --> /keybase/private/user1,user2 ,user3`, but this of course can only scale so much.

So...all of this is a long-winded way of saying that what would be really nice is if we could somehow share a file with `/keybase/private/team` and separately control who's a member of that team. If we could further enforce that each team member uses passphrases on their GPG key and a sufficiently strong GPG key, that'd be even better.

Maybe the way for Keybase to set this up is to implement it all in open source but offer a paid UI tool that just calls the open source tooling to make managing team members really nice...and even something we could run locally.

For now, I think we'll go with `/keybase/private/user1,user2 --> /keybase/private/user1,user2 ,user3`, but I'll stay subscribed to this thread in the hopes that updates are forthcoming! Thanks for a great product.

**Comment by zQueal** [comment]
> and separately control who's a member of that team. If we could further enforce that each team member uses passphrases on their GPG key and a sufficiently strong GPG key, that'd be even better.

I'll just throw some quick input in here; I would honestly say that without these two features, having a Keybase team is of little to no value. Encryption is only as strong as your easiest attack vector, which would be anyone able to decrypt your company passwords (or whatever was in your team folder) without having a 2nd factor on their key. (password)

**Comment by malgorithms** [comment]
we're pretty close with an MVP of a team feature. We expect to have it available in skeleton form by the end of the summer. It will have a "signature chain" of team additions and removals, so team additions/removals/role changes will allow be strictly ordered and auditable (it's important keybase can't just add someone to your team.)  Teams will come with both chat and a special files mount. For example, `/keybase/team/yourteam` ...

**Comment by maxtaco** [comment]
Why don't we bite the bullet and just ship teams this week? It is already
usable!

**Comment by malgorithms** [comment]
those of you watching this thread who are interested in testing some early teams stuff, hit me up on keybase chat...

**Comment by jkrauska** [comment]
Did this go live with Teams?

**Comment by malgorithms** [comment]
yeah, I guess we can close this issue. Oh also, there will be support for managing your teams from right inside the GUI added in the next couple weeks.
