### ISSUE TITLE
twitter verification

### ISSUE THREAD

**Issue by aryehbeitz** [keybase/keybase-issues#1829]
I tried to verify my twitter identity. I Tweeted the given text, but you couldn't find it.
I am including a link to my tweet:
https://twitter.com/1d72c99a744e49b/status/658942465294995456

**Comment by oconnor663** [comment]
All of [your twitter proofs](https://keybase.io/aryehbeitz/chain) reference the Twitter user "aryehbeitz", but twitter.com/aryehbeitz doesn't seem to exist. If you claim that username, your existing proof should start working.

**Comment by aryehbeitz** [comment]
Thanks. My I changed my username to match (it was default to some random
string) and all works. Thanks :-)

**Comment by oconnor663** [comment]
No problem :)

**Comment by mecampbellsoup** [comment]
Hi guys, I can't find documentation anywhere on how to generate a Twitter proof/verification. Do I just sign a message and tweet it out?

**Comment by oconnor663** [comment]
@mecampbellsoup are you using the Keybase GUI app? The GUI will walk you through it:

![image](https://user-images.githubusercontent.com/860932/38625917-8068cd30-3d79-11e8-8bbb-f576a35e2974.png)
