### ISSUE TITLE
Can't upload private key

### ISSUE THREAD

**Issue by demize** [keybase/keybase-issues#1835]
I reset my keys to start over, since I generated entirely new GPG keys. I managed to import my public key fine, but every time I try to upload my private key I get this error:

    {"status":{"code":501,"desc":"failed to insert into database","name":"DB_INSERT_ERROR"},"csrf_token":"[snip]"}

I'm https://keybase.io/demize95 if that helps. I can't think of any more useful information, but I'll be glad to provide it if anyone asks.

**Comment by maxtaco** [comment]
our fault

try it now, it should be fix.

sorry about that!

**Comment by demize** [comment]
That fixed it!
