### ISSUE TITLE
Private key compromised

### ISSUE THREAD

**Issue by honza** [keybase/keybase-issues#1837]
When happens when a private key is compromised?

**Comment by zQueal** [comment]
It really depends on the situation--but usually it's simply revoked by pushing the [revocation certificate](https://www.gnupg.org/gph/en/manual/c14.html) to a keyserver which will then propogate to _most_ other keyservers. The result will be the end user will be able to see that your key has been revoked.

[Here is what it looks like.](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x7715BB392D0019C4)

**Comment by honza** [comment]
I foolishly uploaded my private key to Dropbox, and now consider it compromised. I would like to create a new key and use it with keybase without losing my account. Is that possible? cc @zQueal

**Comment by malgorithms** [comment]
I assume you're talking about your PGP key?

It looks like you've installed the keybase app, so this is very easy to fix. just sign a statment removing the PGP key and then add a new one.

```
keybase pgp list # list your pgp keys
keybase pgp drop <key-id> # from above list
keybase pgp gen # to make a new one (or keybase pgp help for other options)
```

you should see your graph change on the site afterwards to reflect the changes:

https://keybase.io/honza/graph

**Comment by malgorithms** [comment]
in case you're wondering, this all works because your device key is signing statements about your PGP key.

**Comment by oconnor663** [comment]
@honza keep in mind that the PGP-style revoke that @zQueal mentioned, and the Keybase-style drop that @malgorithms mentioned, are two independent things. If you used your PGP key both inside and outside of Keybase, you might need to do both.

**Comment by zQueal** [comment]
> the PGP-style revoke that @zQueal mentioned, and the Keybase-style drop that @malgorithms mentioned

Thanks @oconnor663 rereading my comment I'm a little surprised at myself for not mentioning that...

**Comment by honza** [comment]
Awesome, I'll try it out!

**Comment by honza** [comment]
Worked like a charm, thanks!
