### ISSUE TITLE
Keybase continues to request keybase.txt even after revocation

### ISSUE THREAD

**Issue by citricsquid** [keybase/keybase-issues#1839]
I originally used `keybase.txt` to prove ownership of my domain `samryan.co.uk`, but after updating my website `keybase.txt` has been removed. As expected when the file was removed keybase updated the website to say it was missing, and ever since keybase has been requesting the file every minute and a half:

```
52.3.62.97 - - [01/Nov/2015:14:48:24 +0000] "GET /keybase.txt HTTP/1.1" 404 735 "https://samryan.co.uk/keybase.txt" "keybase-proofs/2.0.44"
52.3.62.97 - - [01/Nov/2015:14:49:57 +0000] "GET /keybase.txt HTTP/1.1" 404 735 "https://samryan.co.uk/keybase.txt" "keybase-proofs/2.0.44"
52.3.62.97 - - [01/Nov/2015:14:51:29 +0000] "GET /keybase.txt HTTP/1.1" 404 735 "https://samryan.co.uk/keybase.txt" "keybase-proofs/2.0.44"
52.3.62.97 - - [01/Nov/2015:14:53:00 +0000] "GET /keybase.txt HTTP/1.1" 404 735 "https://samryan.co.uk/keybase.txt" "keybase-proofs/2.0.44"
52.3.62.97 - - [01/Nov/2015:14:54:33 +0000] "GET /keybase.txt HTTP/1.1" 404 735 "https://samryan.co.uk/keybase.txt" "keybase-proofs/2.0.44"
```

I revoked the signature via the command line to try and stop the requests but the requests for `keybase.txt` kept coming, then I switched to using DNS to verify ownership of samryan.co.uk (which is now complete) but the requests for `keybase.txt` keep coming.

There appears to be a bug that causes keybase-proofs to continue requesting a proof file after the signature has been revoked, or I've done something wrong. Any ideas? Thanks.

**Comment by maxtaco** [comment]
This is a bug in that we should have stopped sooner, but we do give up
eventually.  I believe this was the last attempt:

Nov  1 09:08:34 ws6 proofd.iced[20898]: [I] - - [GenericWebSite] completed:
Error: Hunt failed for {"hostname":"samryan.co.uk","protocol":"*https*:"}
w/ code 240 {"state":2,"status":240} ({"hostname":"samryan.co.uk
","protocol":"*https*:"})

Thanks for letting us know!  (Timezone = EST)

**Comment by pkirkovsky** [comment]
I encountered this issue after removing all proofs from my account (full reset). Since my account has no proofs to verify, why is keybase still trying to access old ones?
