### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by grcninja** [keybase/keybase-issues#1840]
So I log in at work into keybase, I try to go to track someone, I get told that I cannot because I am not storing my private key in the keystore..... but there's no instructions on how to do that.  The personal PC I have did allow me to do that previously, but since I've re-imaged it, I can no longer do it that way either.  So WITHOUT using command line, only using the broswer - how do I "track" someone using the button in the browser now?

**Comment by oconnor663** [comment]
Go to your profile and click the [edit] button next to your PGP key. It looks like this:

![image](https://cloud.githubusercontent.com/assets/860932/10895293/6e7b7ade-8181-11e5-9ba7-d655b9696c05.png)

In that menu, there's an option to upload your encrypted private key. If you click on it, you'll get further instructions.

You'll need to be on a computer that has your PGP private key in the local keyring for this to work. From your description, it's not clear to me whether the PC you're using has your private key or not.

**Comment by grcninja** [comment]
Neither of them has my private key I don't think :(.  I shall go try this now and I will report back momentarily :)

**Comment by oconnor663** [comment]
Sorry about that. In the next version of our command line client, we're going to be pretty aggressive about pushing people to make paper backup keys.

**Comment by malgorithms** [comment]
@grcninja  - you can "reset" your keybase account and start over...you'll establish a new key. That's really the only move if you've lost your private key.

it means you will have to redo any social proofs you have.

That's accessible under the gear icon on your profile:

![image](https://cloud.githubusercontent.com/assets/614943/10911004/971928ee-8210-11e5-9eb1-72d35d90f554.png)
