### ISSUE TITLE
Error 901 (KEY_NOT_FOUND) when trying to track another user

### ISSUE THREAD

**Issue by Arkanosis** [keybase/keybase-issues#1841]
Hi,

I've just updated my public key (same fingerprint, new expiration date) and now, when I try to track another user using command line (zsh + curl + gpg), I get the following error message:

    Error in your post
    -------------------

    Code: 901
    Name: KEY_NOT_FOUND
    Description: signing_kid <kid> not found

… where `<kid>` is the one in the command line I'm asked to copy-paste.

I'd be happy to give more information if needed. Thanks.

**Comment by maxtaco** [comment]
Thanks for the error report. I will look into it. Can you post what that
kid is? It is public info, already available in your public signature
chain. (It is the sha-256 of your pgp public key). Thank you!

**Comment by Arkanosis** [comment]
I've indeed figured out I could as well git you the kid in question, since it's only based on public information, so here it is: 0101c57d600ca0c434a500a2368dc9c648eb301a3acc8403d2ac1c463a951ab479b80a :)

Thanks again!

**Comment by maxtaco** [comment]
Sorry about the bug, try it again now?  It should work.  Thanks for your feedback and patience!

**Comment by Arkanosis** [comment]
It works like a charm; now tracking three more people :)

Thank you so much for the awesome support and the quick fix!

**Comment by maxtaco** [comment]
:+1:
