### ISSUE TITLE
Twitter verification from command line fails

### ISSUE THREAD

**Issue by madamimadam** [keybase/keybase-issues#1843]
Twitter verification from the command line fails. Been repeating ad nauseam for half an hour after I tweeted. My profile is public, all my tweets are public.

Incidentally, your tool really should be smart enough to strip the @ off of a twitter username.

Log:
Corgulator:hipmunk adaml$ keybase prove twitter
Your username on Twitter: @dogsofsf
Your username on Twitter (alphanumerics, between 1 and 15 characters long): dogsofsf

You need a passphrase to unlock the secret key for
user: "keybase.io/alang <alang@keybase.io>"
2048-bit RSA key, ID 23D3AC66410DC764, created 2014-09-12

Please publicly tweet the following:

Verifying myself: I am alang on Keybase.io. CKsJHcizIMqqjrIniWg_6YNPOXMZ3_4brZjx / https://keybase.io/alang/sigs/CKsJHcizIMqqjrIniWg_6YNPOXMZ3_4brZjx

Check Twitter now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
Check Twitter again now? [Y/n] Y
warn: Didn't find the posted proof.
etc

My tweet on twitter is attached
![foo](https://cloud.githubusercontent.com/assets/8387601/11004284/2fe139ec-846c-11e5-9a97-b3d0e7b933e6.png)

**Comment by cjb** [comment]
@madamimadam Ah, you didn't include the "Verifying myself: " part.

**Comment by madamimadam** [comment]
Oops.
