### ISSUE TITLE
login on the CLI fails

### ISSUE THREAD

**Issue by alex** [keybase/keybase-issues#1855]
```
~ $ keybase login alex_gaynor
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 3
▶ ERROR No username known
```

Unsurprisingly, my username is `alex_gaynor` :-)

**Comment by maxtaco** [comment]
Thanks for he bug report.  Well this one is slightly embarrassing :)

Does it work without a command line argument? My guess is that it will.

**Comment by alex** [comment]
Sorry, should have included that: same error.

**Comment by maxtaco** [comment]
Will take a look tonight or tomorrow. Thanks!

**Comment by maxtaco** [comment]
Confirmed this bug, it's because you don't have a key.  Still on our part.

**Comment by alex** [comment]
Yup, I removed my previous key to move to a new one, and now I'm trying to login so that I can verify my new key :-)

**Comment by maxtaco** [comment]
cool.  We'll figure it out, thanks for your patience!

**Comment by alex** [comment]
Confirm that this was resolved :-)
