### ISSUE TITLE
reddit proof failing

### ISSUE THREAD

**Issue by parazyd** [keybase/keybase-issues#1856]
I am trying to prove ownership of my reddit account, but it seems to fail every single time. I tried all three methods of proving, none worked.
[Here](https://www.reddit.com/r/KeybaseProofs/comments/3t6twb/my_keybase_proof_redditparazyd_keybaseparazyd/) is the last time I tried.

**Comment by oconnor663** [comment]
You're missing all the newlines in your reddit proof. Maybe you copy/pasted it in an unusual way? Look at the difference between your proof and others in that subreddit.

**Comment by parazyd** [comment]
I clicked the link on keybase.io. There's nothing I've copied wrong... Perhaps the link generator is bugged?

**Comment by oconnor663** [comment]
Hmm, it works find for me when I try it now. What's your browser/OS?

**Comment by parazyd** [comment]
Firefox 42, Arch Linux LTS kernel

**Comment by parazyd** [comment]
Chromium  with curl method worked. But I still don't realize why Firefox doesn't...

**Comment by oconnor663** [comment]
I'm also on Arch (mainline kernel), and I wasn't able to repro on Firefox either. Very weird.

**Comment by oconnor663** [comment]
I don't imagine you're using XMonad with some fancy clipboard daemon? :)

**Comment by parazyd** [comment]
Openbox and Clipman. But it's Firefox's issue. Because it doesn't work from the browser either.
