### ISSUE TITLE
Reddit proof from CLI: title is missing

### ISSUE THREAD

**Issue by Geekfish** [keybase/keybase-issues#1860]
When I try to create a proof on reddit from the command line, the url produced does not contain a title param, so similar to:
```bash
$ keybase prove reddit geekfish88
Please click on the following link to post to Reddit:

https://www.reddit.com/r/KeybaseProofs/submit?text=%23%23%23+Keybase+proof%0A%0AI+hereby+claim...
```
This results in the post not having the title pre-filled:
![keybase-reddit-title](https://cloud.githubusercontent.com/assets/511547/11268418/9453f72a-8ea8-11e5-9214-e326123e1952.png)

On the other hand when I try from the browser the link looks more like:
```url
https://www.reddit.com/r/KeybaseProofs/submit?selftext=true&title=My%20Keybase%20proof%20%5Breddit%3Ageekfish88%20%3D%20keybase%3Aeleni%5D%20(xmS7-VJtFjO_J-ePt_45tMvhG3BkQK3clQjSXGDrxUQ)&text=%23%23%23+Keybase+proof%0A%0AI+hereby+claim
```
Not sure what the "selftext" param is for, but it definitely contains the title and it works fine.

**Comment by Geekfish** [comment]
This is on keybase version 1.0.0-47

**Comment by maxtaco** [comment]
Thanks for the bug report. It's likely a bug in our new client.  We'll take a look today!

**Comment by oconnor663** [comment]
Hmm, when I try to claim your reddit account as a test user, here's the link it tells me to click (with the text edited out for length):

https://www.reddit.com/r/KeybaseProofs/submit?text=[EDITED%20FOR%20LENGTH]&title=My+Keybase+proof+%5Breddit%3Ageekfish88+%3D+keybase%3Aad9s8321%5D+%28V47RLVX6hh-6Bof7g9jDuGWcM1FcamHLQqGoGSu6v_g%29

@maxtaco is it possible the server didn't include a `title` field in the proof post response?

**Comment by oconnor663** [comment]
Max suggests that it could maybe be an issue with your terminal leaving off a query parameter when it hypertextified the link? Can you post the full output of the command, just to be sure?

**Comment by Geekfish** [comment]
Yes guys, you are absolutely right!

For reference:

The url returned by keybase cli is fine, it contains the title as expected. However when I click on the url the title component gets lost. But this is not all that gets lost, more things actually get lost!

The original url has a length of **3370 chars** and is reduced to **1320 chars** instead, seeming kind of randomly cut-off...

This seems to be a problem possibly related to iTerm2.
So if I paste a silly url, eg `https://www.example.com?aaaaa....` where `a` extends to 3000 characters then then when I click through my browser (Chrome) opens with the same url cut-off at... 1321 chars. Suspiciously close to the issue above.

Thank you for looking into this and sorry for wasting your time!

**Comment by oconnor663** [comment]
Good to know!
