### ISSUE TITLE
Download links too hard to find

### ISSUE THREAD

**Issue by pedromagnus** [keybase/keybase-issues#1861]
It took me 4/5 clicks (and its pages) to get to a page where I get the downloads for my OS. Plus the reccomendation to download Keybase for command line was in the 3rd page of the "trip".
This should be up in the home page!
First step should be download/install Keybase and from that point showing how to create a key, list, etc, etc.

**Comment by malgorithms** [comment]
thanks for the advice. We just switched to the Go client, so we're slowing pushing people to the app. I'll make downloading more prominent in a little bit.
