### ISSUE TITLE
Got "consider tracking" email despite tracking already

### ISSUE THREAD

**Issue by yedpodtrzitko** [keybase/keybase-issues#1862]
Hi,
I've invited a new user to Keybase, and start following them afterwards. Given user have added some other accounts into their profile. I received the following email several hours after that, even if we both track each other.

> You follow @foo on twitter, and now you both have public keys on Keybase, with signed twitter connections. This is cryptographic utopia! You should consider tracking them, which commences a signed record of their public key and identity announcements.

> @foo on keybase: bar

**Comment by vingtdeux** [comment]
FYI, this looks like a duplicate of #1737.

**Comment by yedpodtrzitko** [comment]
Hm, you're right. Thanks for heads up.
