### ISSUE TITLE
[Docs] File input flag is missing in encrypt & decrypt documentation

### ISSUE THREAD

**Issue by redoPop** [keybase/keybase-issues#1869]
In several places, Keybase's documentation is missing the file input (`-i`) parameter required by the CLI:

---

On [keybase.io/docs/command_line](https://keybase.io/docs/command_line#encrypting-a-pgp-message), under the "Encrypting a PGP message" headline:

> ```
> keybase pgp encrypt chris foo.txt             # foo.txt -> foo.txt.asc
> keybase pgp encrypt chris foo.txt -o bar.asc  # foo.txt -> bar.asc
> ````

Should read:

```
keybase pgp encrypt chris -i foo.txt             # foo.txt -> foo.txt.asc
keybase pgp encrypt chris -i foo.txt -o bar.asc  # foo.txt -> bar.asc
```

---

Also on [keybase.io/docs/command_line](https://keybase.io/docs/command_line#decrypting-a-pgp-message), under the "Decrypting a PGP message" headline:

> ```
> keybase pgp decrypt foo.txt.asc              # foo.txt.asc -> stdout
> keybase pgp decrypt foo.txt.asc -o foo.txt   # foo.txt.asc -> foo.txt
> ```

Should read:

```
keybase pgp decrypt -i foo.txt.asc              # foo.txt.asc -> stdout
keybase pgp decrypt -i foo.txt.asc -o foo.txt   # foo.txt.asc -> foo.txt
```

---

Also on [keybase.io/docs/command_line](https://keybase.io/docs/command_line#verifying-a-pgp-message), under the "Verifying a PGP message" headline:

> ```
> keybase pgp verify foo.txt.asc          # verify a self-signed file
> keybase pgp verify foo.txt.asc foo.txt  # verify a file + detatched signature
> ```

Should read:

```
keybase pgp verify -i foo.txt.asc             # verify a self-signed file
keybase pgp verify -d foo.txt.asc -i foo.txt  # verify a file + detatched signature
```

(Note that the second example is also missing the `-d` flag for the detached signature.)

---

_For logged in users only_, on user pages (e.g., [keybase.io/redopop](https://keybase.io/redopop)), in the "Getting started from the command line" well:

> ```
> keybase pgp encrypt redopop mom.jpg # a file
> keybase pgp decrypt mom.jpg.asc -o mom.jpg
> ```

Should read:

```
keybase pgp encrypt redopop -i mom.jpg # a file
keybase pgp decrypt -i mom.jpg.asc -o mom.jpg
```

---

On [the homepage](https://keybase.io/):

> ```
> keybase decrypt maria_reply.asc
> ```

(I know, I know, [it's just a demo](http://i.imgur.com/6HvDAxL.gif), but it really helps us end users when these things are consistent!)

Should read:

```
keybase pgp decrypt -i maria_reply.asc
```

(Note that this example is also using the old `keybase decrypt` instead of `keybase pgp decrypt`.)

---

Also on [the homepage](https://keybase.io/):

> ```
> keybase verify self_contained.asc
> cat foo.txt | keybase verify sig.asc
> ```

Should read:

```
keybase pgp verify -i self_contained.asc
cat foo.txt | keybase pgp verify -d sig.asc
```

**Comment by malgorithms** [comment]
fixed, thanks. will be live in a few mins.

**Comment by malgorithms** [comment]
(and seriously, thanks for seeking out all the mistakes!)
