### ISSUE TITLE
Broken/inconsistent installation instructions

### ISSUE THREAD

**Issue by otherjoel** [keybase/keybase-issues#1872]
I originally installed the keybase client via `npm` as explained on the home page:

    # installation walkthrough
    npm install -g keybase-installer
    
    keybase-installer   # this gets the latest version

However, the [docs for OS X](https://keybase.io/docs/command_line/install_osx) now say that `brew` is the recommended method.

On my mac (El Capitan), `keybase update` will not update the client past version 0.8.23. (although it finishes without giving any error messages). There are a lot of example commands on the website that do not work on this version (e.g. `keybase paperkey`). The latest [release](https://github.com/keybase/client/releases) as of this writing appears to be 1.0.0-46.

So there are a lot of problems here:

1. The website's installation instructions offer two different installation methods, one of them apparently deprecated
2. Apparently the mechanism for updating clients installed using the old method is now broken
3. There's no documentation for how to uninstall the npm-installed version safely (i.e. without affecting your keybase account) in order to switch to the homebrew method, or to otherwise get a clean start on a particular machine
4. Although I assume that 1.0.0-46 is the latest stable release, this is not clearly stated anywhere on the website

**Comment by malgorithms** [comment]
Hi, thanks for reporting this. The site has more aggressive notes now on the switch from Node to Go. For example:

![image](https://cloud.githubusercontent.com/assets/614943/11349554/bf99eb2e-91fa-11e5-8204-a48ad77db27c.png)
