### ISSUE TITLE
Reddit proof failed

### ISSUE THREAD

**Issue by dhimmel** [keybase/keybase-issues#1875]
I am @dhimmel on [keybase](https://keybase.io/dhimmel) and [reddit](https://www.reddit.com/user/dhimmel). I attempted Reddit verification ([see post](https://www.reddit.com/r/KeybaseProofs/comments/3tyq85/my_keybase_proof_redditdhimmel_keybasedhimmel/)), which failed. I retried several times and eventually received this email:

> Hi, dhimmel, your attempted reddit identity proof of dhimmel never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

**Comment by oconnor663** [comment]
I see [two reddit proofs in your sigchain](https://keybase.io/dhimmel/chain), but the reddit link you provided above refers to the earlier of the two. The server will be looking for the later one. Please go through the flow again and make sure you make a new reddit post to go with it.

**Comment by dhimmel** [comment]
Okay, I replaced my proof. Verification with the [new comment](https://www.reddit.com/r/KeybaseProofs/comments/3tzzc2/my_keybase_proof_redditdhimmel_keybasedhimmel/) succeeded.

I think I may have gotten half way through the reddit verification and then stalled, causing the issue. Definitely I did something that made me issue two proofs. I wish I could remember my steps more precisely.

**Comment by oconnor663** [comment]
Thanks for the followup. This is an error that other people have hit before -- probably we should add the link we were attempting to check to the error message to make it clear what's failing. @malgorithms would that be easy?
