### ISSUE TITLE
Hacker News popup contains 'undefined'

### ISSUE THREAD

**Issue by anowlcalledjosh** [keybase/keybase-issues#1876]
The HN 'profile!' popup (for when the API hasn't updated yet but Keybase continues to check for the next \<time\>) appears broken:

![image](https://cloud.githubusercontent.com/assets/9433472/11351207/2dd8c056-922d-11e5-84dd-bae1a2b62223.png)

**Comment by malgorithms** [comment]
should be fixed, thanks!
