### ISSUE TITLE
ERROR dial unix ~/Library/Caches/Keybase/keybased.sock

### ISSUE THREAD

**Issue by fifigyuri** [keybase/keybase-issues#1883]
After installing keybase using homebrew I get the error in the title when I `keybase login`. How can I fix it?

**Comment by maxtaco** [comment]
Sorry about this problem! I'm not immediately sure what could be causing it, but can you paste in the output of : `tail -100 ~/Library/Logs/homebrew.mxcl.keybase.log` ?  The log file is sanitized.  Thanks!

**Comment by fifigyuri** [comment]
I do not have this log tried to find in at different places... any hints where else it can be? Maybe keybase is not logging...?

**Comment by maxtaco** [comment]
Seems like your homebrew setup is slightly different from the ones we've seen. What happens when you run `keybase -d login` ? Thanks.

**Comment by fifigyuri** [comment]
keybase adviced me to reinstall it. I did but did not help. Thanks for the help.

```
15:38:53.091512 ▶ [DEBU keybase json.go:49] 002 No config file found; tried /Users/fifigyuri/Library/Application Support/Keybase/config.json
15:38:53.091590 ▶ [DEBU keybase config.go:114] 003 Config: mapping server ->
15:38:53.091797 ▶ [DEBU keybase config.go:114] 004 Config: mapping socket_file ->
15:38:53.091827 ▶ [DEBU keybase config.go:114] 005 Config: mapping home ->
15:38:53.091977 ▶ [DEBU keybase config.go:114] 006 Config: mapping timers ->
15:38:53.092004 ▶ [DEBU keybase globals.go:189] 007 Keybase CLI 1.0.3-0
15:38:53.092027 ▶ [DEBU keybase globals.go:189] 008 - Built with go1.5.1
15:38:53.092043 ▶ [DEBU keybase globals.go:189] 009 - Visit https://keybase.io for more details
15:38:53.092082 ▶ [DEBU keybase main.go:100] 00a + configureProcesses
15:38:53.092122 ▶ [DEBU keybase install_osx.go:668] 00b + AutoInstall for launchd
15:38:53.093750 ▶ [DEBU keybase install_osx.go:681] 00c | already installed at /Users/fifigyuri/Library/LaunchAgents/homebrew.mxcl.keybase.plist
15:38:53.093820 ▶ [DEBU keybase install_osx.go:670] 00d - AutoInstall -> false, <nil>
15:38:53.093844 ▶ [DEBU keybase main.go:157] 00e | After forks; newProc=false
15:38:53.093868 ▶ [DEBU keybase main.go:178] 00f + configureLogging
15:38:53.093908 ▶ [DEBU keybase config.go:114] 010 Config: mapping local_rpc_debug ->
15:38:53.093983 ▶ [DEBU keybase socket_nix.go:23] 011 Dialing unix:/Users/fifigyuri/Library/Caches/Keybase/keybased.sock

There are no Keybase services installed. You may need to re-install.
15:38:53.094500 ▶ [DEBU keybase main.go:180] 012 - configureLogging
15:38:53.094546 ▶ [DEBU keybase main.go:102] 013 - configureProcesses -> dial unix /Users/fifigyuri/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
15:38:53.094596 ▶ [DEBU keybase globals.go:235] 014 Calling shutdown first time through
15:38:53.094636 ▶ [DEBU keybase login_state.go:883] 015 + Account "LoginState - Shutdown"
15:38:53.094705 ▶ [DEBU keybase login_state.go:885] 016 - Account "LoginState - Shutdown"
15:38:53.094729 ▶ [DEBU keybase globals.go:275] 017 exiting shutdown code=0; err=<nil>
15:38:53.094769 ▶ [ERRO keybase main.go:47] 018 dial unix /Users/fifigyuri/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
```

**Comment by maxtaco** [comment]
Can you paste the output of your plist file?

```bash
cat /Users/fifigyuri/Library/LaunchAgents/homebrew.mxcl.keybase.plist
```

Thanks

**Comment by fifigyuri** [comment]
Here it is. The log file it refers to does not exist.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebrew.mxcl.keybase</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin</string>
    <key>KEYBASE_LABEL</key>
    <string>homebrew.mxcl.keybase</string>
    <key>KEYBASE_LOG_FORMAT</key>
    <string>file</string>
    <key>KEYBASE_RUNTIME_DIR</key>
    <string>/Users/fifigyuri/Library/Caches/Keybase</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/keybase/bin/keybase</string>
    <string>service</string>
  </array>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardErrorPath</key>
  <string>/Users/fifigyuri/Library/Logs/homebrew.mxcl.keybase.log</string>
  <key>StandardOutPath</key>
  <string>/Users/fifigyuri/Library/Logs/homebrew.mxcl.keybase.log</string>
</dict>
</plist>
```

**Comment by maxtaco** [comment]
@gabriel any thoughts on this?

**Comment by gabriel** [comment]
@fifigyuri what is your brew prefix? Output of `brew --prefix keybase`

We fixed an issue with non-standard brew locations so if you do:

```
brew update
brew upgrade keybase
rm ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist
```

and then if you run a command it should work properly.

**Comment by fifigyuri** [comment]
Thanks now it works. I'm bit struggling with the `keybase login`, will return to that later.

my prefix was this

```
→ brew --prefix keybase                                                                                                   
/usr/local/opt/keybase
```

**Comment by gabriel** [comment]
Ok great, feel free to open another issue with your login struggles

**Comment by zg** [comment]
I was running into the same issue. I was able to get my specific setup working by typing `launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist` *outside* of my tmux instance. Then back in my tmux instance I was able to run `keybase` without any issues.

**Comment by zoogeny** [comment]
+1 on zg's comment. I brew installed keybase from within a tmux session and I was getting an error saying that keybase was installed but that the service was not running. Even if I attempted to start the service from the command line using the recommended `keybase launchd start homebrew.mxcl.keybase` it would not work. I detached tmux and ran the launchd start command from outside tmux. I then re-attached to tmux and I was able to run `keybase signup` with success.

**Comment by themightyoarfish** [comment]
I installed with macports and receive this error also. What can I do?

**Comment by maxtaco** [comment]
Never tried macports.  Seems like the background daemon didn't start up.

**Comment by themightyoarfish** [comment]
Can I start it manually? I tried to find a  `.plist` file like the one from above, but there is none. Compiling from source on OS X does not seem to work (cocoapods throws some error) and I'm not going to install another package manager for one binary.

**Comment by maxtaco** [comment]
You can run 'keybase --run-mode=prod service'

We are switching the a self-contained installer soon.

**Comment by themightyoarfish** [comment]
Great to hear. Starting the deamon seems to work.

Maxwell Krohn wrote:
>
> You can run 'keybase --run-mode=prod service'
>
> We are switching the a self-contained installer soon.
>

**Comment by gabriel** [comment]
If you compile you need to send a `production` tag...

It looks like macports is sending the right flag:
https://trac.macports.org/browser/trunk/dports/security/keybase/Portfile

**Comment by gabriel** [comment]
oh but macports doesn't automatically install the launchd service... you can manually run: `keybase install --components=service` to install the launchd service

**Comment by casank25** [comment]
I know this is closed already but i keep having same issue. I installed keybase with homebrew and nothing on this thread helped me solved my problem. I keep getting `ERROR dial unix /Users/casank25/Library/Caches/Keybase/keybased.sock: connect: no such file or directory`

Please advise

**Comment by glenjarvis** [comment]
For the record, I also see what zg and @zoogeny received. I also was using tmux at the time. I believe strongly this is tmux related (even if indirectly) and that is a question we should ask ourselves when we encounter this.

**Comment by Robinnnnn** [comment]
Having the same issue here. I tried the commands recommended in this thread and got these results:

```
~ keybase status
ERROR dial unix /Users/robinkim/Library/Caches/Keybase/keybased.sock: connect: no such file or directory

~ brew --prefix keybase
/usr/local/opt/keybase

~ brew upgrade keybase
Error: keybase 1.0.16 already installed

~ rm ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist
rm: /Users/robinkim/Library/LaunchAgents/homebrew.mxcl.keybase.plist: Not a directory

~ keybase -d install
...
Error installing updater service: open /Users/robinkim/Library/LaunchAgents/keybase.updater.plist.DODOZRX6APRZS75E6GWBH5NJSGUNXDEH: not a directory
...

~ keybase install --components=service
▶ INFO Stopping keybase.service
▶ INFO Stopping homebrew.mxcl.keybase
▶ INFO Saving /Users/robinkim/Library/LaunchAgents/keybase.service.plist
▶ ERROR Error installing Keybase service: open /Users/robinkim/Library/LaunchAgents/keybase.service.plist.2JTFEMWCI7ARM77E4NCXI5FOHLLX3ZLJ: not a directory
▶ INFO Install Service: open /Users/robinkim/Library/LaunchAgents/keybase.service.plist.2JTFEMWCI7ARM77E4NCXI5FOHLLX3ZLJ: not a directory
```

I'm using [zsh](https://github.com/robbyrussell/oh-my-zsh) for my console and I'm wondering this may have an impact?

**Comment by Daylon** [comment]
Same here (**OSX** + **zsh**, btw). The app works fine when toying around with KBFS, but I cannot use the CLI anymore since the update. Logins fails, etc.

```sh
2016-08-06T13:22:51.919791 ▶ [DEBU keybase json.go:50] 001 + loading config file: /Users/__/Library/Application Support/Keybase/config.json
2016-08-06T13:22:51.921675 ▶ [DEBU keybase json.go:78] 002 - successfully loaded config file
2016-08-06T13:22:51.921852 ▶ [DEBU keybase json.go:50] 003 + loading updater config file: /Users/__/Library/Application Support/Keybase/updater.json
2016-08-06T13:22:51.922150 ▶ [DEBU keybase json.go:78] 004 - successfully loaded updater config file
2016-08-06T13:22:51.922524 ▶ [DEBU keybase client.go:113] 005 Using special root CA for api.keybase.io: -----BEGIN CERTIFICATE----- 
2016-08-06T13:22:51.922783 ▶ [DEBU keybase globals.go:271] 006 Created LinkCache, max size: 65536, clean dur: 1m0s
2016-08-06T13:22:51.924798 ▶ [DEBU keybase ui.go:555] 007 Setting GPG_TTY to /dev/ttys002
2016-08-06T13:22:51.924865 ▶ [DEBU keybase globals.go:252] 008 Keybase CLI 1.0.16-20160715110019+f0caa34
2016-08-06T13:22:51.925269 ▶ [DEBU keybase globals.go:252] 009 - Built with go1.6.2
2016-08-06T13:22:51.925300 ▶ [DEBU keybase globals.go:252] 00a - Visit https://keybase.io for more details
2016-08-06T13:22:51.925575 ▶ [DEBU keybase main.go:143] 00b + configureProcesses
2016-08-06T13:22:51.925648 ▶ [DEBU keybase versionfix.go:58] 00c + FixVersionClash
2016-08-06T13:22:51.926535 ▶ [DEBU keybase socket_nix.go:23] 00d Dialing unix:/Users/__/Library/Caches/Keybase/keybased.sock
2016-08-06T13:22:51.927606 ▶ [DEBU keybase versionfix.go:64] 00e - FixVersionClash -> dial unix /Users/__/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2016-08-06T13:22:51.927685 ▶ [DEBU keybase main.go:145] 00f - configureProcesses -> dial unix /Users/__/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2016-08-06T13:22:52.030298 ▶ [DEBU keybase globals.go:299] 010 Calling shutdown first time through
2016-08-06T13:22:52.030559 ▶ [DEBU keybase login_state.go:1004] 011 + Account "LoginState - Shutdown"
2016-08-06T13:22:52.030655 ▶ [DEBU keybase login_state.go:1006] 012 - Account "LoginState - Shutdown"
2016-08-06T13:22:52.030699 ▶ [DEBU keybase globals.go:347] 013 exiting shutdown code=0; err=<nil>
2016-08-06T13:22:52.031943 ▶ [ERRO keybase standard.go:200] 014 dial unix /Users/__/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
```

Requesting the log file doesn't return anything.

**Comment by cjb** [comment]
CC @gabriel

**Comment by Daylon** [comment]
The last update fixed it out for me.  🎉

**Comment by gabriel** [comment]
Yeah this failure occurs when `~/Library/LaunchAgents` doesn't exist. I think we fixed awhile back but haven't done a brew release in a while...

I think we're overdue for that.

**Comment by kinnla** [comment]
Had the same issue. `~ keybase install --components=service` fixed it for me.

**Comment by gabriel** [comment]
@Robinnnnn i just noticed your ~/Library/LaunchAgents is a symlink.. that should be a folder... if you do fix that and reboot...

**Comment by joscha** [comment]
I am getting this with nix and keybase version 6.4.0.
References https://github.com/keybase/client/issues/14476
