### ISSUE TITLE
Unable to setup keybase with existing gpg key

### ISSUE THREAD

**Issue by tomhoover** [keybase/keybase-issues#1887]
The "keybase signup" command aborted with the following error msg:

    ▶ WARNING GPG index error at line 20: Bad fingerprint; wrong length: 16
    ▶ ERROR EOF

However, my keybase account was successfully created. I then attempted to execute "keybase pgp select" but received the same error.

I'm using the latest version of keybase from homebrew, on a Macbook Pro running El Capitan:

    Client:  1.0.1-0
    Service: 1.0.1-0

NOTE: GPG functions normally, with no other apparent problems with my keyrings.

**Comment by maxtaco** [comment]
sorry about that!  Can you run with `keybase -d signup` and let us know what you see? Many thanks.

**Comment by tomhoover** [comment]
> On Nov 25, 2015, at 10:40 AM, Maxwell Krohn <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> keybase -d signup 

⌁ [tom:~] % keybase -d signup
10:41:20.311056 ▶ [DEBU keybase json.go:40] 001 + loading config file: /Users/tom/Library/Application Support/Keybase/config.json
10:41:20.311172 ▶ [DEBU keybase json.go:68] 002 - successfully loaded config file
10:41:20.311254 ▶ [DEBU keybase config.go:114] 003 Config: mapping server ->
10:41:20.311446 ▶ [DEBU keybase config.go:114] 004 Config: mapping socket_file ->
10:41:20.311466 ▶ [DEBU keybase config.go:114] 005 Config: mapping home ->
10:41:20.311602 ▶ [DEBU keybase config.go:114] 006 Config: mapping timers ->
10:41:20.311623 ▶ [DEBU keybase globals.go:189] 007 Keybase CLI 1.0.1-0
10:41:20.311634 ▶ [DEBU keybase globals.go:189] 008 - Built with go1.5.1
10:41:20.311653 ▶ [DEBU keybase globals.go:189] 009 - Visit https://keybase.io <https://keybase.io/> for more details
10:41:20.311673 ▶ [DEBU keybase main.go:100] 00a + configureProcesses
10:41:20.311702 ▶ [DEBU keybase install_osx.go:563] 00b + AutoInstall for launchd
10:41:20.312945 ▶ [DEBU keybase install_osx.go:576] 00c | already installed at /Users/tom/Library/LaunchAgents/homebrew.mxcl.keybase.plist
10:41:20.312971 ▶ [DEBU keybase install_osx.go:565] 00d - AutoInstall -> false, <nil>
10:41:20.312980 ▶ [DEBU keybase main.go:157] 00e | After forks; newProc=false
10:41:20.312988 ▶ [DEBU keybase main.go:178] 00f + configureLogging
10:41:20.313008 ▶ [DEBU keybase config.go:114] 010 Config: mapping local_rpc_debug ->
10:41:20.313028 ▶ [DEBU keybase socket_nix.go:23] 011 Dialing unix:/Users/tom/Library/Caches/Keybase/keybased.sock
10:41:20.313244 ▶ [DEBU keybase config.go:114] 012 Config: mapping local_rpc_debug ->
10:41:20.313359 ▶ [DEBU keybase main.go:214] 013 Setting remote log level: 1
10:41:20.313877 ▶ [DEBU keybase main.go:180] 014 - configureLogging
10:41:20.313931 ▶ [DEBU keybase versionfix.go:21] 015 + FixVersionClash
10:41:20.314319 ▶ [DEBU keybase log.go:30] 016 Config: mapping server ->
10:41:20.314602 ▶ [DEBU keybase log.go:30] 017 Config: mapping socket_file ->
10:41:20.314796 ▶ [DEBU keybase log.go:30] 018 Config: mapping home ->
10:41:20.315026 ▶ [DEBU keybase log.go:30] 019 | configured GPG w/ path: /usr/local/bin/gpg
10:41:20.315258 ▶ [DEBU keybase log.go:30] 01a | configured GPG w/ path: /usr/local/bin/gpg
10:41:20.315429 ▶ [DEBU keybase log.go:30] 01b Config: mapping config_file ->
10:41:20.315604 ▶ [DEBU keybase log.go:30] 01c Config: mapping home ->
10:41:20.315845 ▶ [DEBU keybase versionfix.go:33] 01d | Contacted service; got version: 1.0.1-0
10:41:20.315879 ▶ [DEBU keybase versionfix.go:55] 01e | version check 1.0.1-0 v 1.0.1-0
10:41:20.315894 ▶ [DEBU keybase versionfix.go:57] 01f | versions check out
10:41:20.315902 ▶ [DEBU keybase versionfix.go:23] 020 - FixVersionClash -> <nil>
10:41:20.315909 ▶ [DEBU keybase main.go:102] 021 - configureProcesses -> <nil>
10:41:20.315916 ▶ [DEBU keybase cmd_signup.go:143] 022 | Client mode
10:41:20.315977 ▶ [DEBU keybase cmd_signup.go:167] 023 + clientModeSignupEngine::CheckRegistered
10:41:20.316315 ▶ [DEBU keybase log.go:30] 024 + Account "LoggedInProvisionedLoad"
10:41:20.316545 ▶ [DEBU keybase log.go:30] 025 + Loading session
10:41:20.316769 ▶ [DEBU keybase log.go:30] 026 Config: mapping session_file ->
10:41:20.316974 ▶ [DEBU keybase log.go:30] 027 Config: mapping home ->
10:41:20.317283 ▶ [DEBU keybase log.go:30] 028 Config: mapping session_file ->
10:41:20.317689 ▶ [DEBU keybase log.go:30] 029 Config: mapping home ->
10:41:20.318106 ▶ [DEBU keybase log.go:30] 02a + loading session file: /Users/tom/Library/Caches/Keybase/session.json
10:41:20.318708 ▶ [DEBU keybase log.go:30] 02b - successfully loaded session file
10:41:20.319108 ▶ [DEBU keybase log.go:30] 02c - Loaded session
10:41:20.319318 ▶ [DEBU keybase log.go:30] 02d + Checking session
10:41:20.319551 ▶ [DEBU keybase log.go:30] 02e + API GET request to https://keybase.io/_/api/1.0/sesscheck.json <https://keybase.io/_/api/1.0/sesscheck.json>
10:41:20.319789 ▶ [DEBU keybase log.go:30] 02f | Cli wasn't found; remaking for cookied=true
10:41:20.887494 ▶ [DEBU keybase log.go:30] 030 | Result is: 200 OK
10:41:20.888038 ▶ [DEBU keybase log.go:30] 031 - successful API call
10:41:20.888345 ▶ [DEBU keybase log.go:30] 032 | Stored session checked out
10:41:20.888758 ▶ [DEBU keybase log.go:30] 033 + saving session file /Users/tom/Library/Caches/Keybase/session.json
10:41:20.889417 ▶ [DEBU keybase log.go:30] 034 Wrote session file to /Users/tom/Library/Caches/Keybase/session.json
10:41:20.889766 ▶ [DEBU keybase log.go:30] 035 - saved session file /Users/tom/Library/Caches/Keybase/session.json
10:41:20.890245 ▶ [DEBU keybase log.go:30] 036 - Checked session
10:41:20.890626 ▶ [DEBU keybase log.go:30] 037 - Account "LoggedInProvisionedLoad"
Already registered; do you want to reregister? [y/N]

**Comment by tomhoover** [comment]
I have not yet responded to the question, "Already registered; do you want to reregister? [y/N]". Should I select y or n? If yes, will my invitation code work a second time?

**Comment by maxtaco** [comment]
Ah, sorry, I misread.  How about `keybase -d pgp select`.  Thanks!

**Comment by maxtaco** [comment]
(And no, don't reregister! Sorry about that!)

**Comment by tomhoover** [comment]
[tom:~] % keybase -d pgp select

   —deleted a bunch of stuff—

10:47:34.606084 ▶ [DEBU keybase log.go:30] 096 | configured GPG w/ path: /usr/local/bin/gpg
10:47:34.606331 ▶ [DEBU keybase log.go:30] 097 | running Gpg: /usr/local/bin/gpg [--with-colons --fingerprint -K]
10:47:34.620133 ▶ [WARN keybase log.go:34] 098 GPG index error at line 20: Bad fingerprint; wrong length: 16
10:47:34.620486 ▶ [DEBU keybase log.go:30] 099 - RunEngine(GPGImportKeyEngine) -> ok
10:47:34.659955 ▶ [DEBU keybase globals.go:235] 09a Calling shutdown first time through
10:47:34.660082 ▶ [DEBU keybase login_state.go:873] 09b + Account "LoginState - Shutdown"
10:47:34.660142 ▶ [DEBU keybase login_state.go:875] 09c - Account "LoginState - Shutdown"
10:47:34.660164 ▶ [DEBU keybase globals.go:275] 09d exiting shutdown code=0; err=<nil>
10:47:34.660190 ▶ [ERRO keybase main.go:47] 09e EOF
 [tom:~] %



After reviewing the above output, I executed “gpg —with-colons —fingerprint -K” and found I had an old, revoked, key with a fingerprint of only 32 characters (as opposed to all other fingerprints having 40 characters). I removed that key from my keyring, and tried again:



 [tom:~] % keybase pgp select
 #    Algo    Key Id             Created   UserId
 =    ====    ======             =======   ======
 1    1024D   99E6E60B4673C8B7             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 2    4096R   F692094969B7CDBF             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 3    2048R   171C4EED7EBD582A             Tom Hoover <tom@hisword.net>
 4    4096R   66145703C000ABD5             Tom Hoover <tom@hisword.net>
 Choose a key: 2
 ▶ ERROR ImportKey error: openpgp: unsupported feature: S2K function
 [tom:~] %



Not quite there…here’s the current output from the debug command:



 [tom:~] % keybase -d pgp select

   —deleted a bunch of stuff—

11:16:36.193451 ▶ [DEBU keybase log.go:30] 08d | configured GPG w/ path: /usr/local/bin/gpg
11:16:36.193661 ▶ [DEBU keybase log.go:30] 08e | running Gpg: /usr/local/bin/gpg [--with-colons --fingerprint -K]
 #    Algo    Key Id             Created   UserId
 =    ====    ======             =======   ======
 1    1024D   99E6E60B4673C8B7             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 2    4096R   F692094969B7CDBF             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 3    2048R   171C4EED7EBD582A             Tom Hoover <tom@hisword.net>
 4    4096R   66145703C000ABD5             Tom Hoover <tom@hisword.net>
 Choose a key: 2
11:16:45.120176 ▶ [DEBU keybase log.go:30] 08f SelectKey result: {KeyID:F692094969B7CDBF DoSecretPush:false}
11:16:45.120646 ▶ [DEBU keybase log.go:30] 090 GPG version:
gpg (GnuPG) 1.4.19
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
11:16:45.121069 ▶ [DEBU keybase log.go:30] 091 | running Gpg: /usr/local/bin/gpg [--armor --export-secret-key 51646e346924f69b9960cf46f692094969b7cdbf]
11:16:45.135115 ▶ [DEBU keybase log.go:30] 092 - RunEngine(GPGImportKeyEngine) -> ERROR: ImportKey error: openpgp: unsupported feature: S2K function
11:16:45.135397 ▶ [DEBU keybase globals.go:235] 093 Calling shutdown first time through
11:16:45.135435 ▶ [DEBU keybase login_state.go:873] 094 + Account "LoginState - Shutdown"
11:16:45.135471 ▶ [DEBU keybase login_state.go:875] 095 - Account "LoginState - Shutdown"
11:16:45.135488 ▶ [DEBU keybase globals.go:275] 096 exiting shutdown code=0; err=<nil>
11:16:45.135509 ▶ [ERRO keybase main.go:47] 097 ImportKey error: openpgp: unsupported feature: S2K function
 [tom:~] %



It appears this line is the culprit:

    RunEngine(GPGImportKeyEngine) -> ERROR: ImportKey error: openpgp: unsupported feature: S2K function

Where do I need to look to troubleshoot further?

**Comment by maxtaco** [comment]
Thanks so much for this, I agree 100% so far.

One last piece of data:

```sh
gpg --export-secret-key F692094969B7CDBF | gpg --list-packets | grep -i s2k
```

This will output what type of S2K function is actually in use. Go's libraries don't have complete coverage yet and I've been adding them in as people need them. Also, are you using a Yubikey?

Thanks!

**Comment by tomhoover** [comment]
No Yubikey here. I don't know if the "salt" in the following is OK to post in a public forum, so I x'd it out. If you need it, and it doesn't reveal anything that should remain private, let me know.

 [tom:~] % gpg --export-secret-key F692094969B7CDBF | gpg --list-packets | grep -i s2k
	gnu-dummy S2K, algo: 3, SHA1 protection, hash: 2
	iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: xxxxxxxxxxxxxxxx
	iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: xxxxxxxxxxxxxxxx
 [tom:~] %

**Comment by maxtaco** [comment]
Good news, we have S2K Gnu-Dummy support in v1.0.3! Which version are you on? The salt isn't really private, but best not to post it, you're right!

**Comment by tomhoover** [comment]
[tom:~] % keybase version
Client:  1.0.1-0
Service: 1.0.1-0

The latest from homebrew.

**Comment by maxtaco** [comment]
I think the newer version is in homebrew, make sure you'd updated fully?

**Comment by tomhoover** [comment]
I only installed it via homebrew last night. Just did another "brew update && brew upgrade" and I now have 1.0.3. :-)

Ran it again, and got the following (I was prompted for both my gpg passphrase and my keybase passphrase before getting the error message).

 [tom:~] 1 % keybase pgp select
 #    Algo    Key Id             Created   UserId
 =    ====    ======             =======   ======
 1    1024D   99E6E60B4673C8B7             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 2    4096R   F692094969B7CDBF             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 3    2048R   171C4EED7EBD582A             Tom Hoover <tom@hisword.net>
 4    4096R   66145703C000ABD5             Tom Hoover <tom@hisword.net>
 Choose a key: 2
Collecting your passphrase for Import of key into keybase keyring.
▶ INFO Bundle unlocked: F692094969B7CDBF
Collecting your passphrase for sign new key.
▶ ERROR key generation error: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type

Here's the command with the debug flag:

 [tom:~] % keybase -d pgp select

 —deleted a bunch of stuff—

13:47:15.205601 ▶ [DEBU keybase log.go:30] 08d | configured GPG w/ path: /usr/local/bin/gpg
13:47:15.205827 ▶ [DEBU keybase log.go:30] 08e | running Gpg: /usr/local/bin/gpg [--with-colons --fingerprint -K]
 #    Algo    Key Id             Created   UserId
 =    ====    ======             =======   ======
 1    1024D   99E6E60B4673C8B7             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 2    4096R   F692094969B7CDBF             Tom Hoover <tom@hisword.net>, Tom Hoover <tom@tomhoover.net>
 3    2048R   171C4EED7EBD582A             Tom Hoover <tom@hisword.net>
 4    4096R   66145703C000ABD5             Tom Hoover <tom@hisword.net>
 Choose a key: 2
13:47:21.515710 ▶ [DEBU keybase log.go:30] 08f SelectKey result: {KeyID:F692094969B7CDBF DoSecretPush:false}
13:47:21.516091 ▶ [DEBU keybase log.go:30] 090 GPG version:
gpg (GnuPG) 1.4.19
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
13:47:21.516439 ▶ [DEBU keybase log.go:30] 091 | running Gpg: /usr/local/bin/gpg [--armor --export-secret-key 51646e346924f69b9960cf46f692094969b7cdbf]
13:47:21.532881 ▶ [DEBU keybase log.go:30] 092 GPG version:
gpg (GnuPG) 1.4.19
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
13:47:21.533162 ▶ [DEBU keybase log.go:30] 093 | running Gpg: /usr/local/bin/gpg [--armor --export 51646e346924f69b9960cf46f692094969b7cdbf]
13:47:21.572700 ▶ [DEBU keybase secret_entry.go:30] 094 + SecretEntry.Init()
13:47:21.572794 ▶ [DEBU keybase pinentry_nix.go:62] 095 + FindPinentry()
13:47:21.572821 ▶ [DEBU keybase pinentry_nix.go:71] 096 | Check fullpath /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
13:47:21.572946 ▶ [DEBU keybase pinentry_nix.go:74] 097 - Found: /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
13:47:21.572994 ▶ [DEBU keybase pinentry_nix.go:111] 098 | Can't find terminal name via /proc lookup: readlink /proc/self/fd/0: no such file or directory
13:47:21.573063 ▶ [DEBU keybase pinentry_nix.go:122] 099 | found tty=/dev/tty
13:47:21.573079 ▶ [DEBU keybase secret_entry.go:47] 09a | Pinentry initialized
13:47:21.573104 ▶ [DEBU keybase secret_entry.go:59] 09b - SecretEntry.Init() -> ok
Collecting your passphrase for Import of key into keybase keyring.
13:47:21.573125 ▶ [DEBU keybase pinentry.go:78] 09c + Pinentry::Get()
13:47:21.573138 ▶ [DEBU keybase pinentry.go:131] 09d + pinentryInstance::Init()
13:47:21.778053 ▶ [DEBU keybase pinentry.go:157] 09e setting ttyname to /dev/tty
13:47:21.778156 ▶ [DEBU keybase pinentry.go:164] 09f setting ttytype to xterm-256color
13:47:21.778210 ▶ [DEBU keybase pinentry.go:171] 0a0 - pinentryInstance::Init() -> <nil>
13:47:26.481813 ▶ [DEBU keybase pinentry.go:95] 0a1 - Pinentry::Get() -> <nil>
13:47:26.518019 ▶ [INFO keybase log.go:32] 0a2 Bundle unlocked: F692094969B7CDBF
13:47:26.519574 ▶ [DEBU keybase log.go:30] 0a3 + RunEngine(PGPKeyImportEngine)
13:47:26.519998 ▶ [DEBU keybase log.go:30] 0a4 + Account "LoggedInLoad"
13:47:26.520435 ▶ [DEBU keybase log.go:30] 0a5 + Loading session
13:47:26.520721 ▶ [DEBU keybase log.go:30] 0a6 - Skipped; already loaded
13:47:26.521047 ▶ [DEBU keybase log.go:30] 0a7 + Checking session
13:47:26.521355 ▶ [DEBU keybase log.go:30] 0a8 - session is recent, short-circuiting
13:47:26.521657 ▶ [DEBU keybase log.go:30] 0a9 - Account "LoggedInLoad"
13:47:26.521974 ▶ [DEBU keybase log.go:30] 0aa + PGPKeyImportEngine::Run
13:47:26.522308 ▶ [DEBU keybase log.go:30] 0ab + Account "PGPKeyImportEngine - loadLoginSession"
13:47:26.522647 ▶ [DEBU keybase log.go:30] 0ac - Account "PGPKeyImportEngine - loadLoginSession"
13:47:26.522996 ▶ [DEBU keybase log.go:30] 0ad + Delegator::LoadSigningKey
13:47:26.523292 ▶ [DEBU keybase log.go:30] 0ae + GetSecretKeyWithPrompt(sign new key)
13:47:26.532790 ▶ [DEBU keybase log.go:30] 0af + Account "Keyrings - cachedSecretKey"
13:47:26.533178 ▶ [DEBU keybase log.go:30] 0b0 - Account "Keyrings - cachedSecretKey"
13:47:26.533489 ▶ [DEBU keybase log.go:30] 0b1 found cached secret key for ska: {Me:0xc820338b40 KeyType:DeviceSigningKeyType KeyQuery: ExactMatch:false}
13:47:26.533888 ▶ [DEBU keybase log.go:30] 0b2 - GetSecretKeyWithPrompt() -> ok
13:47:26.534398 ▶ [DEBU keybase log.go:30] 0b3 + Delegator::LoadSigningKey -> ok, (found=true)
13:47:26.534749 ▶ [DEBU keybase log.go:30] 0b4 + PGPKeyImportEngine::unlock
13:47:26.535181 ▶ [DEBU keybase log.go:30] 0b5 | short circuit unlock function
13:47:26.535721 ▶ [DEBU keybase log.go:30] 0b6 - PGPKeyImportEngine::unlock -> ok
13:47:26.536195 ▶ [DEBU keybase log.go:30] 0b7 + PGP::Generate
13:47:26.536584 ▶ [DEBU keybase log.go:30] 0b8 | GenerateKey
13:47:26.536858 ▶ [DEBU keybase log.go:30] 0b9 | WriteKey (hasSecret = true)
13:47:26.537151 ▶ [DEBU keybase log.go:30] 0ba + PGPKeyImportEngine::saveLKS
13:47:26.537412 ▶ [DEBU keybase log.go:30] 0bb + GetPassphraseStream() called
13:47:26.537639 ▶ [DEBU keybase log.go:30] 0bc + GetPassphraseStreamForUser() called
13:47:26.537922 ▶ [DEBU keybase log.go:30] 0bd + Account "PassphraseStream"
13:47:26.538228 ▶ [DEBU keybase log.go:30] 0be - Account "PassphraseStream"
13:47:26.538513 ▶ [DEBU keybase log.go:30] 0bf - GetPassphraseStreamForUser() -> ok
13:47:26.538786 ▶ [DEBU keybase log.go:30] 0c0 - GetPassphraseStream() -> ok
13:47:26.539061 ▶ [DEBU keybase log.go:30] 0c1 - PGPKeyImportEngine::saveLKS -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
13:47:26.539384 ▶ [DEBU keybase log.go:30] 0c2 - PGP::Generate -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
13:47:26.539655 ▶ [DEBU keybase log.go:30] 0c3 - PGPKeyImportEngine::Run
13:47:26.539934 ▶ [DEBU keybase log.go:30] 0c4 - RunEngine(PGPKeyImportEngine) -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
13:47:26.540203 ▶ [DEBU keybase log.go:30] 0c5 - RunEngine(GPGImportKeyEngine) -> ERROR: key generation error: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
13:47:26.540491 ▶ [DEBU keybase globals.go:235] 0c6 Calling shutdown first time through
13:47:26.540530 ▶ [DEBU keybase login_state.go:883] 0c7 + Account "LoginState - Shutdown"
13:47:26.540592 ▶ [DEBU keybase login_state.go:885] 0c8 - Account "LoginState - Shutdown"
13:47:26.540617 ▶ [DEBU keybase globals.go:275] 0c9 exiting shutdown code=0; err=<nil>
13:47:26.540660 ▶ [ERRO keybase main.go:47] 0ca key generation error: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
⌁74% [tom:~] %

    PGPKeyImportEngine::saveLKS -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
    PGP::Generate -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
    PGPKeyImportEngine::Run
    RunEngine(PGPKeyImportEngine) -> ERROR: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type
    RunEngine(GPGImportKeyEngine) -> ERROR: key generation error: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type


Standing by...  :-)

**Comment by maxtaco** [comment]
Thanks Tom. I have enough to repro the problem. Let me work on it for a bit
and get back to you.

**Comment by maxtaco** [comment]
A fix just went in with https://github.com/keybase/client/pull/1420.  We'll cut a v1.0.4 release today.

**Comment by tomhoover** [comment]
1.0.4 fixed it.

**Comment by maxtaco** [comment]
Yes!!!!
