### ISSUE TITLE
Invite code doesn't total to 24 characters (including spaces)

### ISSUE THREAD

**Issue by dkasak** [keybase/keybase-issues#1888]
I just invited a friend to keybase and he got an invite code that was 23 characters long (when counting the spaces that separate the words). The client refused to validate the code since it was expecting 24 characters. After some testing, we noticed that you can work around it by adding a space at the end, but that seems very confusing and is likely a bug.

**Comment by oconnor663** [comment]
@malgorithms is it possible we just never hit a non-24-character case when we tested the wordy invite codes?

**Comment by maxtaco** [comment]
I think there is an obsolete checker on the go client that predates the
changes @malgorithms made. Should be a simple enough fix.

**Comment by oconnor663** [comment]
It looks like the Go client just checks that the code is >4 characters. (checkers.go:CheckInviteCode)

@dkasak, what client were you using to sign up?

**Comment by dkasak** [comment]
On 2015-11-27 00:44, oconnor663 wrote:
> It looks like the Go client just checks that the code is >4
> characters. (checkers.go:CheckInviteCode)
> 
> @dkasak [1], what client were you using to sign up?

keybase, the CLI tool.

-- 
Denis Kasak

**Comment by oconnor663** [comment]
Did you install it with `npm`? If you don't remember, could you paste in
the output of `keybase version`?

**Comment by dkasak** [comment]
Ah, sorry, I wasn't aware there was a Go version. Yes, it was the nodejs version of the client, version 0.8.24. This is what Arch Linux has in its official repository. Is the Go client now the official one? Is the nodejs client still supported?

**Comment by oconnor663** [comment]
We're in the middle of transitioning between the two clients, and we haven't yet pushed everyone to switch. The node client is still supported for now.

If you'd like an AUR package for the Go client, check out `keybase-release`. When we're ready for the big push, we'll coordinate with the maintainer of the `keybase` package to switch it over to the Go implementation. (We didn't create that package.)

In the meantime, I'll go ahead and fix this issue in the node client. Thanks for the report.

**Comment by oconnor663** [comment]
@dkasak this should be fixed now. Would you please run `keybase-installer` to update and try the invitation code again?

**Comment by dkasak** [comment]
@oconnor663 It was my friend who encountered this bug (I'm just the reporter) and we both already have an account. Also, the bug didn't happen with every invitation code (my code *was* 24 characters in length, for instance). Therefore, I'm not sure how to test this.

**Comment by oconnor663** [comment]
No worries, it worked for me when I tested it. Thanks for following up.
