### ISSUE TITLE
Keybase CLI instructions for website proof are wrong

### ISSUE THREAD

**Issue by bsedat** [keybase/keybase-issues#1891]
The instructions for proving identity via a website may be out of date. Keybase.io says to use the CLI using the following command: `keybase prove web <URL>`. Instead I had to use `keybase prove http <URL>`. I was using the OSX Go compiled CLI.

**Comment by zQueal** [comment]
The devs have been hard at work on the Go client. Just about 70-90% of the documentation is up for review I would assume. It might take a while, but it'll be addressed in time.

**Comment by misterdna** [comment]
Would this have any relation to the why the web (non-CLI) interface is failing time after time to see the TXT file I placed on my website?

**Comment by bsedat** [comment]
I apologize if this issue was too aggressively worded! It's not a big deal, the other docs seemed to be spot-on so I figured this was an oversight :smile:

**Comment by zQueal** [comment]
> Would this have any relation to the why the web (non-CLI) interface is failing time after time to see the TXT file I placed on my website?

Very doubtful. If you can't seem to get it to work, query any error messages that you're getting in the issue tracking system to see if there's already a thread open with your issue. If not, feel free to make a new one.

> I apologize if this issue was too aggressively worded!

Nope, didn't take it that way at all.

> It's not a big deal, the other docs seemed to be spot-on so I figured this was an oversight

Sure it's a big deal. But just know it's being worked on!

**Comment by malgorithms** [comment]
thanks - I've temporarily changed the documentation, although we'll have `keybase prove web` fixed in the go client shortly.

**Comment by maxtaco** [comment]
Fix is here: https://github.com/keybase/client/pull/1418
