### ISSUE TITLE
Drunken Computing:  How to lock yourself out of keybase 101

### ISSUE THREAD

**Issue by hogieone** [keybase/keybase-issues#1898]
Tonight, I was playing around while drinking, and accidently my keybase account (named hogie).  I was trying to get my keys uploaded to it and kept getting some GPG errors which I worked out.  But by then, I figured it would be a good idea to revoke my account via the website and delete all my devices (thanks vadept for suggesting that in google hangouts!).  Now, when I try to add a device via the go client (1.0.5) on two different linux machines, I get the error:

02:43:19.244596 â–¶ [ERRO keybase main.go:47] 18f You need to delete your active key before uploading a new one (via multikey) (error 908)

If I try to add the public key via the curl method, I get:

Code: 908
Name: KEY_NEED_REVOKE
Description: You need to delete your active key before uploading a new one

But I have no active keys...  Any help would be helpful.

**Comment by oconnor663** [comment]
Hmm...looks like your account's been reset like you said, but [the API](https://keybase.io/_/api/1.0/user/lookup.json?username=hogie) is still reporting that you have an eldest key. Looking into it.

**Comment by oconnor663** [comment]
Oh neat, I see what happened. It looks like you revoked your eldest key before you reset your account. So then when the reset happened, you ran into a bug where we don't properly handle eldest keys that are already revoked. Thanks for the report! I should be able to manually fix you in our database, once I'm sure that's what's going on.

**Comment by oconnor663** [comment]
@hogieone, I've cleared the `is_primary` flag on your key `012075a638baa6b26c8418c33514e090e8508b68e05dba18d29b3871585218a880ab0a`. You should be good to go. Please let me know if you hit any more issues.

**Comment by hogieone** [comment]
Thank you.  I got a public key uploaded now it appears.  

This bug was brought to you by not your father's root beer, angry orchard, black velvet and rum & coke.

**Comment by oconnor663** [comment]
![image](https://cloud.githubusercontent.com/assets/860932/11576576/a1f77e86-99e5-11e5-9bc7-c38abd800659.png)

**Comment by mogaal** [comment]
Hello, I am facing exactly the same problem. Any idea how to sort it out? My username is mogaal

☻  keybase login
Your keybase username or email address: XXX@gmail.com

************************************************************
* Name your new device!                                    *
************************************************************

Enter a public name for this device: OSX
▶ ERROR You need to delete your active key before uploading a new one (via multikey) (code 908)

**Comment by maxtaco** [comment]
@patrickxb can you help debug?
