### ISSUE TITLE
DNS verification - Can I delete TXT afterwards?

### ISSUE THREAD

**Issue by ephexeve** [keybase/keybase-issues#1899]
Sorry if this may sound a silly question, but after Keybase verifies my domain TXT, if I delete the .TXT some hours later the proof starts pending (of course), but I wonder if there is *any* security risk leaving the TXT verification on the DNS? Couldn't someone just use that same verification key on their DNS? (After the attacker gets hold of my PGP key for example)

**Comment by maxtaco** [comment]
It's supposed to be a public advertisement of your public key, so there's no security risk. The message you post is the hash of a signature taken over your username on Keybase, you public key, and the DNS Zone you're proving.  So it's definitely not transferable.

**Comment by ephexeve** [comment]
@maxtaco Thanks for clarifying.
