### ISSUE TITLE
keybase prove https does not work for HTTPS only sites (when the HTTP port is closed)

### ISSUE THREAD

**Issue by mszabo** [keybase/keybase-issues#1904]
If you try to prove a site which is HTTPS only (the HTTP port is firewalled) the API call returns failure after 10 seconds.

For example:
https://keybase.io/_/api/1.0/remotes/check.json?hostname=initrd.net

returns the following:
```
{
  status: {
    code: 218
    desc: Connection timed out
    name: GENERIC
  }
  results: {
    protocols: {
      https:: {
        code: 200
      }
      http:: {
        err: Connection timed out
      }
    }
    first: https:
  }
  csrf_token: ...
}
```
Even it gets 200 on HTTPS, the client fails with the following:
$> keybase prove https initrd.net
▶ ERROR Connection timed out

**Comment by maxtaco** [comment]
Thanks for the bug report! Should be fixed now.
