### ISSUE TITLE
Logging in and using the private_keys.primary to decrypt messages

### ISSUE THREAD

**Issue by lettergram** [keybase/keybase-issues#1905]
I currently am trying to use kbpgp to encrypt and decrypt messages between me and my friends. To do this, I need to have access to my private key to decrypt the messages people send me. However, the private key in the provided by the object after logging in does not appear to be in the appropriate format.

Take the example below from the [kbpgp docs](https://keybase.io/kbpgp/docs/loading_a_key):

    var alice_pgp_key    = "-----BEGIN PGP PRIVATE ... etc.";
    var alice_passphrase = "martian-dung-flinger";

    kbpgp.KeyManager.import_from_armored_pgp({
      armored: alice_pgp_key
    }, function(err, alice) {
        if (!err) {
            if (alice.is_pgp_locked()) {
                  alice.unlock_pgp({
                  passphrase: alice_passphrase
            }, function(err) {
                 if (!err) {
                      console.log("Loaded private key with passphrase");
             }
          });
        } else {
             console.log("Loaded private key w/o passphrase");
        }
      }
    });

The pgp_key from private_keys.primary doesn't start with "----- BEGIN...etc." it instead appears to be just the internal string. Now, I can go ahead and just manually add the "--------BEGIN PGP blah blah blah", but I was curious if anyone else has tried this before and knows the solution, or if it is even possible?

**Comment by oconnor663** [comment]
Functions like `export_pgp_public` will re-armor the key if you want that.

**Comment by lettergram** [comment]
Perhaps I should rephrase, how do I decrypt a message encrypted using my public keybase key? 

To me, the logical way to do it would be to login to keybase, import the private key to the kbpgp KeyManager, then decrypt the message.

I believe that using the export_pgp_public function can only export a key once it is in the KeyManager. Am I incorrect in that belief? 

If that is the case, then using export_pgp_public would not work because the key would not be in the KeyManager.
