### ISSUE TITLE
ERROR key generation error: Failed to get pubkey: openpgp: invalid data: subkey signature invalid: openpgp: invalid data: signing subkey is missing cross-signature

### ISSUE THREAD

**Issue by kaylabs** [keybase/keybase-issues#1906]
Hi,

when i try to import my public-key to the keybase keychain i got the error as shown below

ERROR key generation error: Failed to get pubkey: openpgp: invalid data: subkey signature invalid: openpgp: invalid data: signing subkey is missing cross-signature

My key got 3 subs - it is completely trusted and verified.

What should i do to get rid of that message.

Kind regards 

Kaylabs

**Comment by oconnor663** [comment]
This sort of thing is often due to having an expired key. Let me take a look though.

**Comment by oconnor663** [comment]
Could you post the public key here that you were trying to upload?

**Comment by kaylabs** [comment]
Hello thank you for your advice

Here is my key i try to upload:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFUL+MUBEADC4kiPTXVvYncK7YetrcRZEFdB+6uonJgCzBE/EH7vPOQRV7rq
PQDFzo+XQXMYWUUWgfMwG00DxmbCyv45tJzXiEZChnyi0EC63kRoNKtyDM6MKTgr
tr77TGc1nMAVkwZIW2THHded445nLiZgk1RCz5XzlqSPlqNhRpXC1bFrSUs/rMTZ
EN/lSpvIs/ykn0ZY9gzMgkFUprNkzAMosNIt02FyY3Afoc7zKxra6BNyhbUBEAi1
qwPf7FfPC9y0tT1DYqQOgmzAjc9UtMrV+6HqPIlBkYKdBCWuCK4l/+9VziHnu82y
F1z0wFkFgzCRydb9dlAREmxPl0PV9cKQtibR/ycGd71JmI4yv5d7OT4eYn/Ds5ix
MOxHxjKLRLADsJNItbqZa+g1HSCPjhF2tCLi2cLOkJzLTn8SBngjGPl0IQ9tliyb
Nio/NJa4nfKp7GNbdtJo8daLTODpOFwbN8NCbrBdwr0SzSRZXSkh5E3r/gwDYrsL
B0EypcEEeCsCSIlrOqDEEDBJd1HpVlaZokDtOMT5ZQFM0k5fIzu6mmAHwg6sJCXG
kFxxlgVywnR4X2HnzmvxJZhIne8602ElsgkBMt33SprYd3hLRgCNwl2LFvVjmTvd
GiBcUXgxQ4GXBxfVInEZFTrTgN0EvrQI8ubvLwPayNiDxzZtNJp4AYcC8wARAQAB
tB5Kb2VybiBLdWVobCA8a2F5bGFic0BhcmNvci5kZT6JAj4EEwECACgFAlUL+PgC
Gy8FCQPDuIAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELfXlrsyoycxzVUP
+wUjErOAL/cCc59aMyFcUZvT1qg8xHAU/mblS3KCkv3joU48rk6yDkNHGzCbsqST
RIizMjKSIPPfVyV33+tYoT62+WaXEjlmCue6fBwt4wZDBQ0KOn7FKm/hz/4/tog2
lO/DPrpFAusuQ0sYuLbuyPMuPBDi8pdRcMzGGy33Ywvbh3gLZpTKek5T/xrstiUF
AoXjuHKMms5HfdImME2dOBjolw3sjbZkK4BgyPg421hSvXr1yco1nlOesmZAvrry
3Y9NQphSNq67IInsjgHMQd0Irkb9UFo3C/Gm9vHIhF8FDWhtMh25v/yYTkb+Y/Rx
tOfnHUH0OGqN/A1yAiTwOmra7EdvMAI5ohia+vslua7eOgNK73aW3E3cDrGhWGmz
Wj40l9drtfG57qv0wyCO5K81uEeERz8nxNVS3JSAOUDENfYVVl+Ag+JZ40D6lPST
OXE9kUb+8GtG+ruJ76U5qsg8kUhlBqmC6N69+vFoioA2lTfPJTfzbaw3n2TL9htq
LGzdyzbV0JJpsk6zHwIXktJ/7Keso2cvPCbBrEgvoc3TX3ALvISauhIeIU1vFbrn
zI9J/5Pe67biqcQGV11l5jQrmHrk7nV+IXyDgKYf/IkeccyjQ8b2VtjdSukYM3hn
DeDq3ESgpW9DrZmk+TixwADCtblq/TosE9n5VUiYDy3ztCFKb2VybiBLdWVobCA8
ai5rdWVobEBsZW5uZXRhbC5ldT6JAkEEEwECACsCGy8FCQPDuIAGCwkIBwMCBhUI
AgkKCwQWAgMBAh4BAheABQJWZgE6AhkBAAoJELfXlrsyoycxTR8P/0CaOWf4Rtjd
a2bfWOV6HCKbazbkIZK5KXQ40fYx3fbZ8e6axo2vulLLFSD9NcVMkII87FUzZDIa
D+o0kCJK7wn+2+DIuT0I699438c7BCi/dkYngj/Ka2M6SVt13ASmbrJg4v5P7w9W
cDUIpM0LLxl5lPqN7N9wK22P27bfiOlMFFo0Vzq9tyhdjNBi1aksB1MpHjQbJ/yO
REEnBBWUOMRTetwzAfryuIf/y7t2Mc1HZ0MAqE/y3i7c+bpk1LLu+xIwSw6Gy/xR
w1SkZ104ZkoG5OKVYaQzlVETgyGqZbIctqQEb6MZ11YRGjpMTAhNrZU/4wopFhy7
DQCyfsnrK3eMLBOTH8DI42YSlFGhb7pLEKZdmRuxcM9nmCmYJ2bL+tLIzzSqMRLu
5KTUWqb9bwm7zNaQuWfbYNbXHfrZNma4xBsTIhYevzLSiWs2kDxZ97RSbIdF5Jo/
wTBSDZAFaSNFlLA2qNIQNyhsRHNsrBCMATNxlMS5N1wsEWDswdqyhB1OBhSUEZf4
6BfQJngz6Duxf3X2y+AktrRgPVOUPauhGPTubUxPxWTX5g9cxSuZewuz25isl2C3
NF5GHdITy0mxZr9q0VxLIua0vCewLuksrchCxqTPtGMMidiBmxKfT5J+CcthTjxC
B1SH/erBPy8hOOlw/HZSAgr0QDUOZfV+tCFKb2VybiBLdWVobCA8ai5rdWVobEBp
dC10ZWFtLmJpej6JAj4EEwECACgFAlUL+PMCGy8FCQPDuIAGCwkIBwMCBhUIAgkK
CwQWAgMBAh4BAheAAAoJELfXlrsyoycx+78QAIDFEs6hdwV4Ltop/WsD62Op/xBB
Cy+4j0itpOnO0iWJIhbgwlBPGiYrVEqFJQLxUp3CovbP1tBAI7rWCeIyNMqmd0Qs
9DeSxGtIJNPRolKHHXTHiFcszo2SefmHIu3l8HH3hdo+XzpYbV13IFOoABIqfbj2
CBHEyV+4DSKXvJ1j1d6sMFOIyBkwYMhvrXYXIngAK1qTNMQkkJI9ZaNKwIZIlZnl
YavkyuHTD/4oCTf1f7boB447ac7RWCByDP/kfARLsJ8TwrOO4+cD6+Z/dBMrvBe1
0tDM0GnXJV/03PsxNqkPrDzMh0ShSddJlEZZ0lNcnrDdXGr7vn5BWj3rpHUKL4mj
XGbJSFj5anwxnSwSi15HRSbz5GcuIqbLorsRcoEY7D7y+ZkN8d/5fqDDulCA56rv
5HIl4Ztm1DgDmIIUq24OaIQevLmjI1ZexuxdSDdWC5BEJd/YAUbw8sadoahhVrte
xzY8rHy3lrZ4RX4KScPukKVU3Jq95sfDSo9Mrux4CfFDg2e4dA+1Okhy7yli2mis
ta9GLHPeLNPlaHZG2d31BGqXTk29m4hwCfuY5Iuo9Am1CRRbw2Vbz+YSF7Ojn9F6
m8Nf9lvEJBc3ffYbEnyXZwT8pLy1iRfNUGW8OhN/VqDFADMQbKs2YTlHNiJS56hk
/ByseXKAUA0VuHTRuQINBFUL+MUBEADAl3F5c+VoEKC6CecqdrHr77sOFRpyVHw4
rCDo54TI0wzJtHQyzOV6L6sGpUMUD/NTZ0FO/csOViQfBYinfiqdOVu/bDiq6rlG
nWXVw1s6AjXD+b0/wGvKLkaEk+lajmM+ifcrJPHJ34wzMdqohf7yST/suMGcpODt
/m1LN+15uxdItuqZnolKzdB/vOjuGZEE22NhpzumZk652Z5WosOIDVdn1sKROr+O
ziZooVYiWY20l6QLS4tcuAaCizbWOGnF9bQzLZlQ/BPFk+j6EzRwpmYSWBT/qXdd
wz2L288uiiCZjx85wvIcv6WMEWBf/ahYMwzTOn4sz2vu5RQ2FJgBdgEuEV38LzTY
J0mso4Ch+x5WnZ7Lg3iPCjQJUIeKIEo6gWDhjYzZru4qcbjoBLCSzHQgsuD5ICfd
OQdaLk3pvLFyJqFCQHuR3hL0pyvW0a6gNzxjZtGKbs8W6H6Sd8mlTBfECqkMa1pE
rS7VrMo6fBtbYArqK8QnA1FPCPeh/r23PGtYhtM3Mi1eRNRoDbsbx/ufQ6BxivJB
dILRUO37ubxik+MEUU/4CxRX9ArOW67IWcdZxtwXryiaiZFtkcaky7tSG9G97F72
CBgKwwLE0HscHG9yh79taUc60KB5ApSeeZHAnXAUW0gSW+atddcZKdGy3KlCtV+k
z0xYpzEu7QARAQABiQREBBgBAgAPBQJVC/jFAhsuBQkDw7iAAikJELfXlrsyoycx
wV0gBBkBAgAGBQJVC/jFAAoJEB7sRj7oDEeE3LYQALkYiq5K4GPm17V4aXIyyVOS
81VzhSvxhBl6uJLVeEHGEGMhdUg6xz4MqQOadNmG+SAWeZPWRRwmnYFHs+Mp+YXJ
fGxqq/DFPnKDYyL610k06tAyup3071PXqIBHQuzFAZWxqW7xMsu+PVXVQOq/PTso
WZdB3/KPweh/led4lLq45odQeEq/hILNBwAzxeuwAdeBg7aeK9YJCLhyNT7hRV06
BQ6Ypohbi9nvyCOuThJ4UFwlRl/mYEKwqTto7wh9txoaVaplUYmgE1vxlRny5Y/l
ESrDaNBo2qQ08qg4fLJgDHkZfkenLOsJEzinlqfqCMZ4a/X5eKxywoi6lOTlGscj
03BddTRInV5yTzJar7zvHzwT0J868NAoh9EQdkxna3TOr5oFhG/dxuDmPEPUI9PP
9f8iM+W1w15it94LJOWQ5+/YApmnZqaiCUU+DzwoU43RkGP37wBbWtGywmqlFH6s
xA7kdy680B2FnNoN96eI5WkXCOxxFVCx/8/z5h7dPo0hwIj5NDP5qGRp2/GSM+P3
46kh5lON2rFDebKJsAlUT6JeYAVJ8sueMp7vZLV/cfY5vrkULG6Z0q+lOk4Dmc/z
CqlN0LZF30lwZvyC15zeh13uSP9MSLyH0y4bTAEkTGCSLmRo1Mo8XnJWVNuEghBR
JIhVcE4LQp0cKrWLWuTL+ccP/jBfOLHFVBZkJ29T83+c8N4DsgKNGyZy6dVoaK/y
iRTrKZeCjGt5clgnezPsTi3Q3bggmAbsZnBhDw1i0e99eCuAjWGS8bt8xPQ6eKHF
1fgBjinNpUojQulEicM3jsrjFfv6Ozn6SxhuUYzHfPjeGF1Pwt8tGmcDTVqiagdF
MqKVI8Bx4TD4PY7PJF+JDgqnc59MRF2EQZeeGyWncR/Q13Wh9XIIYMFgqGx7QlRY
qOsXsei/0xmTwFv56ymrlM8DrQZM07b5C0EvTe4HlXCFRYrwpbvwk8dpsNGcCalK
S1UClQewg4ceqp1vflbVqR0r4cugYpM4MjO/Xg52kuO/9q+uXegHm9lReEfNoXZv
5M+kp5zhSz735LoBTR7fyH26S/V9m9INPLUb7KWC4yLEF+byXOalL/ts3ixHuUEM
0jUxCCUUHrkHCoj9NEIzWvcWsd6MxmD7J07+7d+jn5UOv8z3few80Y30K2Irsa4k
8KlDL7t14lzL8K4HLXkE55SyDMeCbwLWfuesETOT/LznPHlR7RVYGe2E9VHxhd0y
VguYv7vyVx7u0TAr1EoSxEkKzYEyQhJQ0m2Kxp9lZEHc5yHtWvhvZQj0NdzPiGn9
Ut3r1bY/37uoEIQfxsaqOZxcX/lx2q9t8ylaV123yZ8zFNrB+eCcVRVUZpkvw+xE
blYJ
=7oW5
-----END PGP PUBLIC KEY BLOCK-----

**Comment by toxygeneb** [comment]
I'm having the same problem with a key that only has one subkey and isn't due to expire until 2018.

Is a fix or workaround available please?

[bjorn.ballard.public.asc.txt](https://github.com/keybase/keybase-issues/files/81942/bjorn.ballard.public.asc.txt)

**Comment by maxtaco** [comment]
Thanks, I'll take a look!

**Comment by maxtaco** [comment]
Should be fixed in 1.0.9.  Let me know if not!
