### ISSUE TITLE
Merkle tree and delay between payload generation and signing

### ISSUE THREAD

**Issue by mitar** [keybase/keybase-issues#1914]
So I see that there is a `merkle_root` value in the payload users have to sign to prove their identity. But that value changes with every change to the tree, no? So it could happen that when I am signing the payload using command line that the delay between payload being generated and me running the command is large enough that the `merkle_root` changes in meantime? Will this scale as more and more users will be modifying the tree?

**Comment by maxtaco** [comment]
Good sleuthing.  I think it should scale. Users sign the last root they observed.  If that changes out from underneath them, it doesn't affect the validity of the signature at all.  This cross-signature is meant as a protection against the server maliciously rolling forward or back and isn't required for protocol correctness.

**Comment by mitar** [comment]
And `prev` is just previous signature in my personal chain, yes?

**Comment by maxtaco** [comment]
Yes. And that *is* crucial to the protocol and is carefully checked by server and client.

**Comment by mitar** [comment]
OK, but this is a reasonable thing to request, that the client assures that they serialize their requests. Good.

**Comment by mitar** [comment]
Thinking a bit more about this. This is in fact an interesting idea. So you are repurposing the proof signatures also to create a set of signatures which verify the history of the whole tree. And then by including that signature in the tree itself you are freezing the whole thing.

Although, ideally, the client would verify the tree before signing the payload. Based on the speed of signing I do not think this is happening.

**Comment by maxtaco** [comment]
It's true. The client is just checking that the tree is consistent with the state that it has previously cached.  So the server hasn't rolled back the state of its chain.

Longer-term, we're hoping third party auditors will keep keybase honest and monitor each state of the merkle tree.

**Comment by mitar** [comment]
Yes, or store it in some blockchain or something.

Thank you really for all the answers.

**Comment by maxtaco** [comment]
[We already do!](https://keybase.io/docs/server_security/merkle_root_in_bitcoin_blockchain)

Checking it on the client side, that's a different issue....

**Comment by oconnor663** [comment]
Someday when we have infinite time we'll use https://en.bitcoin.it/wiki/Thin_Client_Security :)
