### ISSUE TITLE
Export private key to GPG2

### ISSUE THREAD

**Issue by chrysm** [keybase/keybase-issues#1917]
I'm trying to give GPGTools access to my Keybase generated key... I'm not sure of that's doable, given that my local copy is encrypted and GPG doesn't know to ask to decrypt it.  Is there some way of exporting that GPG could interpret?  I'm not finding anything in the help or doc... and the web interface doesn't appear to offer much in the way of key management either.  Thanks.

**Comment by maxtaco** [comment]
try `keybase pgp export` or `keybase pgp export --secret`

**Comment by chrysm** [comment]
the first just gave the public key, but the second worked.  thanks.

**Comment by maxtaco** [comment]
Sure thing.
