### ISSUE TITLE
The OSX command line client doesn't know who I am

### ISSUE THREAD

**Issue by paulehoffman** [keybase/keybase-issues#1918]
Greetings. On OSX, I uninstalled the npm version and installed with brew. When I do "keybase login", I get:
```
# keybase login
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
Choose a signing option: 3
Your keybase username: paulehoffman
▶ ERROR No synced secret PGP key stored on keybase.io for paulehoffman; please try logging in via GPG, an existing device, or a paper key (error 901)
```
That is correct, I have not synced a secret PGP key there. However, there are no instructions for "loggin in via GPG". I don't have any other existing device, nor a paper key.

**Comment by maxtaco** [comment]
Thanks for the feedback and sorry for the snafu.  It seems like keybase can't find GPG in your path.  Can you do a `which gpg`?

**Comment by paulehoffman** [comment]
```
# which gpg
/usr/local/bin/gpg
```

**Comment by maxtaco** [comment]
Sigh, I have a feeling you're up against a bug in launchd that we've yet to workaround.  Can you dump out the environment that `keybase` is running with? `ps -axwE | grep keybase | grep service` Thanks so much for your help.

**Comment by maxtaco** [comment]
(My guess is that launchd is going to overwrite your PATH with a PATH that doesn't include `/usr/local/bin`)

**Comment by paulehoffman** [comment]
```
# ps -axwE | grep keybase | grep service
30917 ??         0:02.63 /usr/local/opt/keybase/bin/keybase service TMPDIR=/var/folders/sr/hnxnccz97pd_478gb5l2zp9r0000gp/T/ KEYBASE_LABEL=homebrew.mxcl.keybase SHELL=/bin/bash HOME=/Users/paul.hoffman Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.pvVpvyLXDJ/Render SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.83scWzLAyx/Listeners KEYBASE_LOG_FORMAT=file LOGNAME=paul.hoffman DISPLAY=/private/tmp/com.apple.launchd.n0dMQ3Cnac/org.macosforge.xquartz:0 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin KEYBASE_RUNTIME_DIR=/Users/paul.hoffman/Library/Caches/Keybase XPC_SERVICE_NAME=homebrew.mxcl.keybase USER=paul.hoffman XPC_FLAGS=0x1
# echo $PATH
/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/Users/paul.hoffman/Bin
```

**Comment by maxtaco** [comment]
So much for that theory.

Oh, it could be your current machine doesn't have access to your GPG private key, maybe.  

Does `gpg -K` yield any results?

**Comment by paulehoffman** [comment]
Nope, "gpg -K" returns nothing. Should it?

**Comment by maxtaco** [comment]
To provision your new device, yes. In login, we use your existing PGP key to sign your new per-device keys into your identity.  If keybase can't find it, you're out of luck.

So in your case, you'd have to install keybase first on the machine where you used to use PGP from.  

Or have you recently nuked your GPG keyring? Uninstalling keybase npm should definitely not have touched your existing GPG keyring.

**Comment by paulehoffman** [comment]
Geebus, this is a pain in the ass. I had a different account on my Mac, and had used Keybase from that. I have now logged in to that account, gotten the paper key, and used it in my now-nomral account.

Am I getting the feeling that the only way to use Keybase reliably is to give them my PGP private key? That didn't seem to be the case earlier. (I don't consider typing in the paper key each time to be reasonable, FWIW)

**Comment by zQueal** [comment]
> Nope, "gpg -K" returns nothing. Should it?
> Geebus, this is a pain in the ass.

This is expected behavior, though, no? To access your PGP key, it needs to be added to your keyring...

> Am I getting the feeling that the only way to use Keybase reliably is to give them my PGP private key? 

This isn't necessarily true. You can execute gpg commands with the Keybase client, so Keybase never really __needs__ access to your private key if you don't want it to.

> I don't consider typing in the paper key each time to be reasonable, FWIW

To the best of my knowledge (don't quote me if I'm wrong) the paper key is to provision a new device, it's not a passphrase to login to your Keybase account. Once you enter your paper key a single time and provision your new device, you're already logged into your Keybase account and don't need to reenter your paper key each time -- you only need to know the passphrase for your private key to sign, encrypt and decrypt communication.

**Comment by paulehoffman** [comment]
Ah, OK, I think I see where I was misunderstanding the setup issues. Thanks! I'll close this off, since I don't see anything that would need to be changed for the general case.

**Comment by malgorithms** [comment]
> Am I getting the feeling that the only way to use Keybase reliably is to give them my PGP private key

We hope for the opposite, actually. Once we start making the app easier to install and finish our mobile app, provisioning new computers will be done by bringing any 2 together. 

Still, if you want to do *PGP* operations, of course you'll need your PGP private key. If you don't use Keybase's encrypted key store for that, it's up to you how to move it around.
