### ISSUE TITLE
OS X installation issue via homebrew

### ISSUE THREAD

**Issue by christopherkeller** [keybase/keybase-issues#1921]
I recently upgraded my keybase installation from NPM to to the new go version and, while it installs fine, I think I hit an edge case. I suspect the issue is related to using a separate privileged account to install homebrew and maintain packages.  I don't use keybase much, but from what I recall, this is pretty basic functionality. Apologies if this was covered within the docs.

It installed via hombrew with zero issues.

 $ keybase version
Client:  1.0.6-0

$ keybase login
There are no Keybase services installed. You may need to re-install.
ERROR dial unix /Users/christopher/Library/Caches/Keybase/keybased.sock: connect: socket operation on non-socket

I didn't see anything related to this in the docs, but I figured I'd run the install routine.

$ keybase install
INFO Checking /usr/local/bin/keybase (/usr/local/opt/keybase/bin/keybase)
ERROR Command line not installed properly (remove /usr/local/bin/keybase: permission denied)
INFO Checking service
INFO Service: Not Installed (Action: Install)
INFO Installing Keybase service
INFO Checking KBFS
INFO KBFS: Not Installed (Action: Install)
INFO Installing KBFS
ERROR Error installing KBFS: exit status 1
INFO Installer for cli: INSTALL_ERROR remove /usr/local/bin/keybase: permission denied
INFO Installer for service: OK
INFO Installer for kbfs: INSTALL_ERROR exit status 1

I noticed a couple of other issues that were similar, but just creating the symlink won't work because my non-admin user doesn't own /usr/local/bin. So before I run around changing perms and messing up homebrew, I wanted to check with folks.

**Comment by gabriel** [comment]
Thanks for the bug report. What happens if you do `brew doctor`?

Can you post a recent chunk of `~/Library/Logs/keybase.service.log`?

What is the output of `keybase launchd list`?

**Comment by gabriel** [comment]
Oops I mean `~/Library/Logs/homebrew.mxcl.keybase.log` (not `keybase.service.log`)

**Comment by christopherkeller** [comment]
`brew doctor` from the unprivileged account generates a few screens of permissions errors (as I would expect). 

From the privileged account:

`$ brew doctor`
Please note that these warnings are just used to help the Homebrew maintainers with debugging if you file an issue. If everything you use Homebrew for is working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Back to the user account here.

`$ cat ~/Library/Logs/homebrew.mxcl.keybase.log`
cat: /Users/christopher/Library/Logs/homebrew.mxcl.keybase.log: No such file or directory

`$ keybase launchd list`
Keybase service:
homebrew.mxcl.keybase: Not Running

No KBFS services.

**Comment by gabriel** [comment]
My current guess is that the service wants to launch keybase and thinks it's at `/usr/local/opt/keybase/bin/keybase` but that doesn't exist or points to the old keybase or there is a permissions problem.

What is the output of `which keybase`?

What happens if you re-link keybase? e.g. `brew unlink keybase && brew link keybase`

Thanks for your help debugging

**Comment by christopherkeller** [comment]
I'm not sure that's it. To the best of my understanding, the installation was fine. 

`$ which keybase`
/usr/local/bin/keybase

`$ ls -l /usr/local/bin/keybase`
lrwxr-xr-x  1 macadmin  admin  37 Dec 14 10:46 /usr/local/bin/keybase@ -> ../Cellar/keybase/1.0.6-0/bin/keybase

After executing the `unlink` and `link` commands, the output is the same. I checked my privileged account and the various keybase logs and socket files don't exist, so they clearly aren't part of the home-brew installation process itself. At what point should the socket file get created that is referenced when I run the login command? 

By the way, when I run `keybase login` in the privileged account, I get a different set of error messages:

ERROR Error installing Keybase service: open /Users/macadmin/Library/LaunchAgents/homebrew.mxcl.keybase.plist.2HM74VJW35WWH2EDKEP4DORW5NAVZQJC: no such file or directory
ERROR open /Users/macadmin/Library/LaunchAgents/homebrew.mxcl.keybase.plist.2HM74VJW35WWH2EDKEP4DORW5NAVZQJC: no such file or directory


So it seems like regardless of account in which I attempt to run, some expected files are missing, yet the installation itself seems to be normal.

**Comment by gabriel** [comment]
Does the following directories exist and are writable for you?

```
/Users/christopher/Library/LaunchAgents 
/Users/christopher/Library/Logs
/Users/christopher/Library/Application Support
/Users/christopher/Library/Caches
```

If any of those dirs are missing you can try to `mkdir` to create them which might fix the problem.

I'm going to create a non-admin user and see if I can reproduce. (Admittedly I should have done this first.)

**Comment by christopherkeller** [comment]
Those all look normal to me. I have a small mac cluster here I use for some development and I sanity checked against that and the only one with odd permissions is the `Logs`, but that's clearly not related. This account has been through a few OS X upgrade cycles. 

`$ ls -ld /Users/christopher/Library/LaunchAgents  /Users/christopher/Library/Logs /Users/christopher/Library/Application\ Support /Users/christopher/Library/
Caches`
drwx------+  99 christopher  staff  3366 Dec  6 07:10 /Users/christopher/Library/Application Support/
drwx------+ 107 christopher  staff  3638 Dec 17 12:19 /Users/christopher/Library/Caches/
drwx------    9 christopher  staff   306 Dec 18 08:55 /Users/christopher/Library/LaunchAgents/
drwxrwxrwx+  81 christopher  staff  2754 Dec 18 15:55 /Users/christopher/Library/Logs/

One of the first things I tried  was `touch /Users/christopher/Library/Caches/Keybase/keybased.sock`, but it made no difference. If you can't replicate the issue on your side, I'll try it on another mac here as a control. Appreciate the assistance.

**Comment by gabriel** [comment]
It seems like the service isn't starting up at all, and not even getting a chance to write to the log. There is probably an error when launchd starts up and that will go to the console (but hard to pick out from other messages there).

Maybe try this:

- Go into Console app
- Select All Messages
- Clear Display
- Reload the service manually:
```
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist && launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist
```
- See if the console outputs an error message

If for some reason that worked you should see it as `Running` when doing `keybase launchd list`

**Comment by christopherkeller** [comment]
This doesn't make any sense and I'm checking things out, but I wanted to share the immediate results. There is nothing in `Console` whatsoever.


`$ sudo launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist && sudo launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist`
/Users/christopher/Library/LaunchAgents/homebrew.mxcl.keybase.plist: Could not find specified service
/Users/christopher/Library/LaunchAgents/homebrew.mxcl.keybase.plist: Path had bad ownership/permissions

 `$ ls -l ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist`
-rw-r--r--  1 christopher  staff  1086 Dec 18 08:55 /Users/christopher/Library/LaunchAgents/homebrew.mxcl.keybase.plist

`$ cat ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist`
```yaml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList 1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key> 
<string>homebrew.mxcl.keybase</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin</string>
    <key>KEYBASE_LABEL</key>
    <string>homebrew.mxcl.keybase</string>
    <key>KEYBASE_LOG_FORMAT</key>
    <string>file</string>
    <key>KEYBASE_RUNTIME_DIR</key>
    <string>/Users/christopher/Library/Caches/Keybase</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/keybase/bin/keybase</string>
    <string>service</string>
  </array>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardErrorPath</key>
  <string>/Users/christopher/Library/Logs/homebrew.mxcl.keybase.log</string>
  <key>StandardOutPath</key>
  <string>/Users/christopher/Library/Logs/homebrew.mxcl.keybase.log</string>
  <key>WorkingDirectory</key>
  <string>/tmp</string>
</dict>
</plist>
```

**Comment by gabriel** [comment]
Ah you don't want to `sudo` that command cause then you are installing/running the service as root.

You might want to:

Remove (unload) from root user:
```
sudo launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist
```

It is possible that running as root created some files that are now owned by root in which case you'll need to remove them or change ownership back.

These are the files/dirs that keybase creates:

```
/Users/christopher/Library/Application Support/Keybase
/Users/christopher/Library/Caches/Keybase
/Users/christopher/Library/Logs/homebrew.mxcl.keybase.log
```

And then load as yourself:
```
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist
```

**Comment by gabriel** [comment]
If the service won't start, one other thing to try is to run the keybase service manually with debug on (`-d`) to see if it is erroring out:

```
/usr/local/opt/keybase/bin/keybase -d service
```

**Comment by christopherkeller** [comment]
`$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist`
`$ keybase login`
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG

I went ahead and cleared those directories by hand (none were owned by root) and then loaded the service manually. I'm not sure I can explain why it appears to be working, but it does appear that way. I wonder if there was a conflict somehow in the pre-brew npm version. This is on my desktop which doesn't reboot all that often, so maybe during yesterdays reboot, stuff got cleared. At any rate, I'll play it a bit and make sure it's working and then close this out. Appreciate all the quick feedback and advice.

**Comment by gabriel** [comment]
ok glad it's working... Sorry for all the back and forth and being hard to debug.

For the next version, I am gonna try to add in more checks and debug so that if the service fails to launch it will be easier to diagnose. Currently it's really hard to figure out what went wrong when launchd decides not to run the service.

So maybe if keybase runs and fails to connect to the service, it does a bunch of checks and shows a really nice error message with all the things that might be wrong.

And also we'll do more testing on accounts without admin access.

**Comment by christopherkeller** [comment]
Checks out here, happy to do any future testing.

**Comment by zg** [comment]
I was running into the same issue. I was able to get my specific setup working by typing `launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist` *outside* of my tmux instance. Then back in my tmux instance I was able to run `keybase` without any issues.

**Comment by samhandev** [comment]
Same issue for me.
running the command @zg provided solved it.

`keybase version 1.0.9-0`

**Comment by ceeblet** [comment]
I had the same problem too, however, the command that worked for others did not work for me:
`launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist`

which gave this response:

`/Users/ceeblet/Library/LaunchAgents/homebrew.mxcl.keybase.plist: service already loaded`

What *did* work for me was the command @gabriel suggested:
`/usr/local/opt/keybase/bin/keybase -d service`

At this time I don't know if this will persist or not. No console messages were created with the failures.

other output below:

`[ceeblet:~] $ keybase launchd list

homebrew.mxcl.keybase: Not Running exit=0 [Keybase]

No KBFS services.

[ceeblet:~] $ keybase launchd start homebrew.mxcl.keybase

▶ INFO Starting homebrew.mxcl.keybase

[ceeblet:~] $ keybase launchd list

homebrew.mxcl.keybase: Not Running exit=0 [Keybase]

No KBFS services.

[ceeblet:~] $ keybase launchd status homebrew.mxcl.keybase

{

  "version": "",

  "label": "homebrew.mxcl.keybase",

  "pid": "",

  "lastExitStatus": "0",

  "bundleVersion": "1.0.11-0",

  "installStatus": 1,

  "installAction": 3,

  "status": {

    "code": 1803,

    "name": "ERROR",

    "desc": "homebrew.mxcl.keybase is not running",

    "fields": null

  }

}

[ceeblet:~] $ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.keybase.plist

/Users/ceeblet/Library/LaunchAgents/homebrew.mxcl.keybase.plist: service already loaded

[ceeblet:~] $ keybase login

▶ ERROR dial unix /Users/ceeblet/Library/Caches/Keybase/keybased.sock: connect: no such file or directory

`

**Comment by gabriel** [comment]
@ceeblet There was an upgrade bug (unrelated to tmux issue)... to fix you can run:

```
$ launchctl unload $HOME/Library/LaunchAgents/homebrew.mxcl.keybase.plist
$ rm $HOME/Library/LaunchAgents/homebrew.mxcl.keybase.plist
$ keybase install
```

We also have a brew update pending (version 1.0.12) which also fixes the upgrade issue.
