### ISSUE TITLE
Can't replace expired key

### ISSUE THREAD

**Issue by djmitche** [keybase/keybase-issues#1926]
My old key (7F0D15B1) expired.  Before that occurred, I signed my new key (154E3226) but didn't think to update it on keybase (honestly, I totally forgot about the service).

Now I don't seem to be able to update the key.  In fact, I don't seem to be able to do much, since the `keybase` command only sees the un-expired private key, which isn't registered on keybase.

It'd be great to have some way to add an entry to the sigchain based on the existing key signature.

**Comment by maxtaco** [comment]
The website should work, though honestly, the command-line should work too.  Do you have an older version?

**Comment by djmitche** [comment]
Nope, just installed it today.  The website doesn't seem to have any option for adding a new key to an account.

**Comment by djmitche** [comment]
"Update my key (I edited it elsewhere)" is the closest I can find, but it requires that the fingerprint has not changed -- and of course it has (it's a new key)

**Comment by maxtaco** [comment]
Oh sorry, now I understand.  Well it's possible to fix this in a few steps if you still have the old key sitting around.  Or you can nuke your account and reprove your external identities is the path of less resistance.

**Comment by malgorithms** [comment]
to clarify, when @maxtaco says "nuke your account" he does not mean delete the account entirely, which would make the username unrecoverable. He means reset your sig chain, which would require redoing proofs and start from scratch. This button on the site would let you start fresh:

![image](https://cloud.githubusercontent.com/assets/614943/11881020/3b0a00fc-a4d2-11e5-9659-79a47414967a.png)

**Comment by djmitche** [comment]
I do still have the old key sitting around, so I'm willing to try "a few steps" if that means keeping my watching/watched.  If it works I'll make a PR for the docs :)

**Comment by maxtaco** [comment]
Ok, so you can use GPG to extend the lifetime of that key, here's a [tutorial](http://www.g-loaded.eu/2010/11/01/change-expiration-date-gpg-key/) I found when googling around.

You might be able to run `keybase login` and login via your old GPG key. I say "might" because I haven't tried this exactly case.

If that doesn't work, I'd click that little "edit" tooltip next to your old keybase fingerprint on the web site. Then, we'll step you through an update process.

Now you definitely should be able to login with your old key.  Once you have, you can `keybase pgp select --multi` to select your new key.

Hope this works, let me know if you hit any hiccups!

**Comment by djmitche** [comment]
OK, that worked.  Here's what I did:

 * extended the expiration of the original key until tomorrow (`gpg2 --edit-key 7F0D15B1`)
 * ran `keybase --gpg=$(which gpg2) login` (the need for the `--gpg` is unrelated to this bug, but took me a while to figure out -- and may have helped in the first place!)
 * Ran `keybase --gpg=$(which gpg2) select --multi`

Now, I see both keys in keybase!  Thanks!

**Comment by djmitche** [comment]
Huh, I don't see a place where I might send a PR for the docs -- what's the repo I need?

**Comment by maxtaco** [comment]
It's a surprise it couldn't find gpg2. It could be that it wasn't showing you the GPG prompt unless it found a suitable private key to import.

Which doc set were you referring to, the online docs from the client, or the docs on the Web site?  If the former, its [keybase/client](https://github.com/keybase/client).  I'm really psyched everything worked out, and thanks for your feedback.

**Comment by maxtaco** [comment]
BTW, [here](https://keybase.io/djmitche/graph)'s a visualization of what happened, very cool.

**Comment by djmitche** [comment]
I'm psyched too, and the graph is cool!

Here's what I got without using gpg2:
```
dustin@hopper ~ $ keybase login
▶ INFO gpg: checking the trustdb
▶ INFO gpg: public key of ultimately trusted key 64D29DB3 not found
▶ INFO gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
▶ INFO gpg: depth: 0  valid:   3  signed:  65  trust: 0-, 0q, 0n, 0m, 0f, 3u
▶ INFO gpg: depth: 1  valid:  65  signed:  56  trust: 60-, 0q, 1n, 3m, 1f, 0u
▶ INFO gpg: depth: 2  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
▶ INFO gpg: next trustdb check due at 2015-12-19
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
Choose a signing option: 3
▶ ERROR user canceled input
```
and later in the same session, without making any destructive changes:
```
dustin@hopper ~ $ keybase --gpg=$(which gpg2) login
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 4
```
I have both gpg and gpg2 installed, since Fedora seems to require gpg for its internal stuff.  But gpg can't read gpg2's keystore.

I can open a new issue if this is is significant enough to warrant.

**Comment by djmitche** [comment]
Oh, and I was thinking of adding the key-replacement procedure at https://keybase.io/docs/command_line
