### ISSUE TITLE
Including CAcert.org's Certificates

### ISSUE THREAD

**Issue by Bandie** [keybase/keybase-issues#1932]
I request to include CAcert.org's Root Certificate to the PKI of the keybase.io-Servers.
CAcert.org is a Web-Of-Trust driven Community which signs certificates for free.

This would include issue #1422 and #1088 (comment by @amingilani).

**Comment by BrandonIngalls** [comment]
I am personally against trusting CAcert, I know it is an older post but some people advocated adding CAcert to Mozilla's default store and one of the CAcert representatives had [this](https://bugzilla.mozilla.org/show_bug.cgi?id=215243#c158) to say.

None of the browsers on any of the operating system I have used -- besides from Arch -- have had CAcert in their trusted stores. Plus with the adition of LetsEncrypt to the CA ecosystem, I find that I trust the [ACME](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md) spec far more than what CAcert offers...

There are many [people](https://lwn.net/Articles/590879/) that have spoken of weak points in the CAcert model, some even comparing their trust in CAcert signed certs to that of random self-signed certs. So if few other places trust CAcert... Why should Keybase?

**Comment by RichJeanes** [comment]
Yeah, we had quite the discussion with a CAcert representative over on the [TwoFactorAuth.org repo](https://github.com/2factorauth/twofactorauth/pull/1196). Honestly, disenfranchised me from the site, even if I had been interested in what they did before.
