### ISSUE TITLE
Gist proof not working?

### ISSUE THREAD

**Issue by PublicStartup** [keybase/keybase-issues#1938]
Attempting to post a Gist to my github account as instructed:

C:\Program Files (x86)\Keybase>keybase prove github PublicStartup
Please publicly post the following Gist, and name it
keybase.md

My Proof is here:

https://gist.github.com/PublicStartup/

https://gist.github.com/PublicStartup/2701001506ca9efc8e2d

Attempting to Check Github fails. See:

Check Github now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] y
Couldn't find posted proof.

**Comment by maxtaco** [comment]
I believe this issue is that you introduced newlines when you posted your gist. Can you delete the newlines in the signature block, so it's just one giant line, and then click the "retry" button on the website?

**Comment by maxtaco** [comment]
(If this is the issue, we'll put in a server-side workaround)

**Comment by maxtaco** [comment]
Actually, leave it as is, I'm pretty sure that's the problem, I'll put a fix and let you know when it's good.

**Comment by careyblack** [comment]
I also had a similar issue... 

keybase prove --output github.proof github careyblack
   I did a copy and paste to gist. But, it did not verify. (I tried enough times and waited, no love.)

However I did find a (reasonable IMHO) workaround and it did work.

keybase prove --output github.proof github careyblack

Then opened the github.proof file that was created and pasted it into the gist.

**Comment by maxtaco** [comment]
This issue is now resolved.  @PublicStartup, confirmed that your GitHub proof is now up!

**Comment by nawa** [comment]
I think that proof file must contain empty last line

**Comment by ki9us** [comment]
I'm having this issue.  Tried with and without newlines.  Tried it yesterday and today.  Tried it sitting and standing.  Not sure what else to try.  

https://gist.github.com/ki9us/63b1b57799366c936413b5516086712e
