### ISSUE TITLE
Message encryption instructions inconsistant

### ISSUE THREAD

**Issue by Jaymoon85** [keybase/keybase-issues#1945]
On the Encrypt and Decrypt pages, the instruction on the right is:
> keybase encrypt -m "message" [them]

![(screenshot)](https://u.pomf.is/sjorwd.png)

When inputting this command, I receive the error:
> No help topic for 'encrypt'

I think the command should be?
> keybase pgp encrypt -m "message" [them]

**Comment by malgorithms** [comment]
yes, thanks, fixed!
