### ISSUE TITLE
Website shows invalid tracking information

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#1948]
I recently -- 2016-01-05 -- generated a new gpg key and nuked my Keybase profile to start from scratch...

The [keybase page](https://keybase.io/bi) shows that I am currently tracking a bunch of people that I did have tracked before the wipe...

But with the new key I am only tracking the following people...

```
[~]$ keybase list-tracking
ampadmos
dbd

```

**Comment by maxtaco** [comment]
Thanks Brandon, this is a known bug, we have to fix it...
