### ISSUE TITLE
unable to check site, maybe letsencrypt cert related

### ISSUE THREAD

**Issue by digininja** [keybase/keybase-issues#1950]
Yesterday I changed my site from using a commercial cert to using one from LetsEncrypt, this morning I get an error saying that my site can no longer be verified. I've checked and the site is definitely up and the file that you used to access is still there

When I tell you the URL you hit the site on http and I send you a 302 to the https site, you don't hit that and on screen show me this error:

"could not query digi.ninja. Are you running a site there?"

My guess is that you don't accept the LetsEncrypt certificate, can you check that and if not, add it to your certs list.

**Comment by maxtaco** [comment]
Yeah, that's indeed the problem.  We're using [Node's list](https://github.com/nodejs/node/blob/master/src/node_root_certs.h). In particular, we're on 4.2.3 LTS Argon, whose list is [the slightly older](https://github.com/nodejs/node/blob/aa1e9a42f7188986d1aaa5c081d80230fd8ee54a/src/node_root_certs.h).

**Comment by digininja** [comment]
Glad there is a definite reason. I've done the confirmation through DNS so I'm OK for now, will look at adding web as well once you've fixed it.

**Comment by maxtaco** [comment]
Sounds good, thanks for the feedback and bug report. We'll wait a little bit to see if the node people fix it and if not we'll submit a P/R or patch. Thanks!

**Comment by maxtaco** [comment]
BTW, there's not an issue for this, but there is a [higher level discussion](https://github.com/nodejs/node/issues/4175) as to how they manage their C/A list.

**Comment by digininja** [comment]
Does seem like an odd decision.

**Comment by lp0** [comment]
Your server is missing the Intermediate Certificate "Let's Encrypt Authority X1" required to chain to a Root Certificate that could be accepted.

**Comment by digininja** [comment]
I thought I'd got the intermediates in and it works fine through browsers.
I'll have a look and see what I've missed.

**Comment by kmkaplan** [comment]
Since PR nodejs/node#9139 was merged you can use `NODE_EXTRA_CA_CERTS` to manage root certificates.

**Comment by digininja** [comment]
Its all working and registered so closing this
