### ISSUE TITLE
Website: Correct install command for Arch Linux

### ISSUE THREAD

**Issue by Tenzer** [keybase/keybase-issues#1960]
At https://keybase.io/docs/the_app/install_linux#arch-linux the install command is listed as:

    yaourt -S keybase-release

Since there's now official [keybase](https://www.archlinux.org/packages/?q=keybase) packages for Arch Linux, the command should instead be:

    sudo pacman -S keybase

**Comment by malgorithms** [comment]
excellent. updated, thanks.
