### ISSUE TITLE
Another Account Username Change (Through Deletion) 

### ISSUE THREAD

**Issue by cviebrock** [keybase/keybase-issues#1964]
Similar to #1851, I messed up with choosing my username.  Any chance I can get another invite, so I can then delete my existing account and start again?

Thanks!

**Comment by malgorithms** [comment]
use this code: 

```
theme tent run empty
```

(grab it before someone else stumbles onto it....)

**Comment by cviebrock** [comment]
Got it.  New account set up at "cviebrock" and old one deleted.  Thank you!

Any chance you can give those 4 invites to the new account, since I've now deleted the old one? ;)

**Comment by malgorithms** [comment]
done
