### ISSUE TITLE
Test API?

### ISSUE THREAD

**Issue by sunny-g** [keybase/keybase-issues#1969]
Is there a test API available for developers to use for building other clients? It would be nice to not have to test creation of new proofs and trackers (tracks?) on my own, live account.

Also, slightly unrelated - is it recommended to interface with Keybase servers over msgpack RPC or through the RESTful API?

**Comment by malgorithms** [comment]
sure, you can use this site: https://stage0.keybase.io

it's a fork of the db so you might have to re-register. In fact you can automate signups to its API if you want, with the invite code 'stage0'

**Comment by sunny-g** [comment]
@malgorithms thank you for this! I just have a couple follow-up questions:

- REST or Msgpack?
- Is it safe to assume that this staging server sign tracks and proofs?

**Comment by malgorithms** [comment]
the api matches the doc at https://keybase.io/docs/api/1.0 except just at the different domain. It's all json and pretty RESTful.

the staging server runs all the same code as the regular site, just with a DB fork. if you want to post a new signature to your sig chain, you'll have to sign it in the same ways, and the site will check your proofs, etc. it should work just like the regular site. but note we may nuke its data periodically.

**Comment by sunny-g** [comment]
@malgorithms thank you!
