### ISSUE TITLE
Unable to login on Chrome

### ISSUE THREAD

**Issue by guildencrantz** [keybase/keybase-issues#1970]
Chrome Version 49.0.2623.0 dev (64-bit) on Linux keeps saying "Incorrect password. Fix it or reset your password" when attempting to login. Login with the same passphrase works correctly in Firefox. It might be worth noting that originally I thought it might be a passphrase issue so I tried to reset via chrome and kept getting "Server failure: missing non-optional field pwh" when submitting the form linked from the email. Resetting also worked in Firefox.

**Comment by malgorithms** [comment]
Hmm, one other user had the same issue. they were running Chrome Canary.

Questions:
1. Any idea how I can get 49.0.2623.0 on an Ubuntu machine? I've installed Chrome Stable and it's only 47.*. Google's site says they don't release Canary for linux. But I'd like to try to reproduce your situation.
2. do you have any extensions installed? can you try disabling them all, esp. any ad blockers (which can occasionally break pages) or password managers (lastpass, etc.). I want to make sure none of them are messing with the login form so we really can narrow this down to chrome.
3. in either the login form or the reset form do you produce any JS errors in the console when this fails?

I've tried this in linux 47.*, OSX 47.*, and OSX with canary 50.*.

**Comment by guildencrantz** [comment]
@malgorithms 
1. on ubuntu (which I'm on, 14.04) the package is `google-chrome-unstable`. 
2. I have many extensions installed, but even without extensions (incognito or `--disable-extensions`)
3. I have no errors in the console.

**Comment by guildencrantz** [comment]
I just validated that downgrading to Version 47.0.2526.111 (64-bit) works.

**Comment by malgorithms** [comment]
this is all very helpful. thanks!

**Comment by malgorithms** [comment]
Ok, we found this after a looooot of debugging. This is a bug in Chrome Canary and has already been fixed. Discussed here:

https://github.com/feross/buffer/issues/94

**Comment by guildencrantz** [comment]
Crazy. Your investigation, and sharing the findings, is appreciated.
