### ISSUE TITLE
Unable to reset account password from keybase.io site

### ISSUE THREAD

**Issue by Zbob750** [keybase/keybase-issues#1972]
I click recover, am able to get the email, follow the link, but when I submit my new password the server responds with
```Server failure: missing non-optional field pwh```

Is this a known issue or how best do I proceed?

![keybase_reset_fail](https://cloud.githubusercontent.com/assets/1254957/12500141/0363cfba-c076-11e5-992e-f71452d8cfd5.jpg)

**Comment by maxtaco** [comment]
Are you running a Chrome Canary?

**Comment by Zbob750** [comment]
Not quite, but relatively close. I'm running in the development channel, just a step above canary. 
Chrome Version 49.0.2623.13 dev (64-bit)

**Comment by maxtaco** [comment]
I think you hit #1970.

**Comment by Zbob750** [comment]
That appears to be the issue, downloaded a firefox package and all is well. Thanks for the quick response :+1:

**Comment by maxtaco** [comment]
Crazy bug in Chrome, hope they fix it soon!
