### ISSUE TITLE
install GPG and put your PGP private key on this machine and try again

### ISSUE THREAD

**Issue by phiku** [keybase/keybase-issues#1977]
Hello, 

I have generated a GPG key and uploaded it. Then I wanted to login "keybase login", selected 3) and got the following message (there were two others, but since I have gpg installed, I thought it should work):
"install GPG and put your PGP private key on this machine and try again"

However, this does not work. So I deleted the keys, and chose the other option:
"reset your account and start fresh: https://keybase.io/#account-reset"

Then I deleted my keys and thought, try "keybase pgp gen". Then after entering the key details, again the error "ERROR in login" appeared. So, what to do? I have to have keys to login, however to generate keys I have to login too. And generating them with gpg neither works. 

Btw, I do not want to upload my private key.

My user is "phiku". 

Thanks in advance!

**Comment by maxtaco** [comment]
If I were you, I would:

1. Reset again
1. Sign in with the CLI and "use keybase passphrase"
1. You `keybase pgp gen`

That should do it.

**Comment by phiku** [comment]
I somehow have the problem now, that i want to login, but have already a device registered. To delete it first, i need to login:

------------------------------------------------------------------------------------
shell> keybase login
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
Choose a signing option: 3
Your keybase username or email address: phiku
Please enter the Keybase passphrase for phiku (12+ characters): 
Enter a public name for this device: phiku zhdk
▶ ERROR Device name is already in use by this user (error 1408)
shell> keybase device list
▶ ERROR Login required
------------------------------------------------------------------------------------

**Comment by maxtaco** [comment]
You can only use a given device name once. Pick a different name.
