### ISSUE TITLE
Keybase installed on OS X with Homebrew failing with "protocol not found"

### ISSUE THREAD

**Issue by echosa** [keybase/keybase-issues#1978]
I've installed the latest Keybase from Homebrew. I've even uninstalled and reinstalled. Yet, keybase doesn't run any commands except `version`. Everything else errors out with a "protocol not found" error. 

The Client and Service versions are out of sync, though. I assume that's the issue, but I'm not sure how to fix it. I don't see a separate homebrew forumla for the service, and I actually don't see anything in the keybase formula that seems service specific. 

I also don't see a file anywhere named `keybase.1.log`.

```
$ brew rm keybase
Uninstalling /usr/local/Cellar/keybase/1.0.9-0... (4 files, 35.2M)

$ brew cleanup keybase

$ brew --cache keybase
/Library/Caches/Homebrew/keybase-1.0.9-0.el_capitan.bottle.tar.gz

$ rm /Library/Caches/Homebrew/keybase-1.0.9-0.el_capitan.bottle.tar.gz

$ brew install keybase
==> Downloading https://homebrew.bintray.com/bottles/keybase-1.0.9-0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring keybase-1.0.9-0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/keybase/1.0.9-0: 4 files, 35.2M

$ keybase version
Client:  1.0.9-0
Service: 1.0.7-0

$ keybase status
▶ ERROR protocol not found: keybase.1.log
```

**Comment by maxtaco** [comment]
This was a botched/incompatible update. Our fault.  You can fix it via `pkill keybase`. Sorry about that!

**Comment by echosa** [comment]
Yep. That did it. Thanks! I'll close the ticket now.
