### ISSUE TITLE
Just getting "ERROR EOF" for most commands

### ISSUE THREAD

**Issue by 2bithacker** [keybase/keybase-issues#1981]
```
chip@thunder ~> keybase version
Client:  1.0.9-0
Service: 1.0.8-0
chip@thunder ~> keybase update check
▶ ERROR EOF
chip@thunder ~> keybase update run
▶ ERROR EOF
chip@thunder ~> keybase id 2bithacker
▶ ERROR EOF
```

Not really sure what's going on here, seems like most commands are returning "ERROR EOF" almost immediately.

This is on Mac OS X 10.11.2.

**Comment by maxtaco** [comment]
This was a botched update on our part.  Solvable via `pkill keybase`. Thanks

**Comment by 2bithacker** [comment]
Yup, that did it. Thanks!
