### ISSUE TITLE
error "Provision transaction already in progress" on keybase login

### ISSUE THREAD

**Issue by Gobiner** [keybase/keybase-issues#1986]
log dump id 5db98270e3d7792010a10d1c
I followed the friend of keybase instructions on my macbook. After running the app, I tried to run `keybase login` which only returns "ERROR Provision transaction already in progress"

**Comment by maxtaco** [comment]
Thanks for the bug report.  Known issue, we'll have a fix out today, sorry about that, and thanks for your patience!

**Comment by chrisnojima** [comment]
This should be fixed in the next release, please reopen if you see this again, thanks!

**Comment by el-dude** [comment]
I am experiencing the same symptom: I get the same error as described above("`ERROR Provision transaction already in progress`") when running "keybase login" I am running version 1.0.16-20160715110019+f0caa34 that I just downloaded and installed on my new work laptop.

**Comment by JoeGermuska** [comment]
I have this same error. I started trying to use the MacOS app today. 
Version 1.0.17-20160930202009+0229d49 (1.0.17-20160930202009+0229d49)

I get the error trying to log in with the GUI app or with `keybase login` on the CLI.

**Comment by maxtaco** [comment]
@JoeGermuska  can you do a `keybase log send` from the CLI?

**Comment by adamhotep** [comment]
I had this error as well (log id f21be6b6d1c6218edd744c1c on Debian Testing amd64, keybase version 1.0.18-20161104184826+1bf9718).

I'm pretty sure this came from a GUI bug.  I had logged in via the GUI and then tried to do things on the command line.

My solution was to kill all keybase instances: `ps auxww |awk '/keybase/{print $2}' |xargs kill` (I advise you run `psauxww |awk '/keybase/'` to see what this will kill before pumping the PIDs into kill.)
