### ISSUE TITLE
Cannot set profile photo even though github identity established

### ISSUE THREAD

**Issue by timmc** [keybase/keybase-issues#1990]
I have account https://keybase.io/timmc linked to this GitHub account, and no profile photo. When I try to set a photo, I am told I need to prove my Twitter or GitHub identity -- which I already have!

**Comment by zQueal** [comment]
You say that you have verified your Github account, however, your profile doesn't seem to reflect that and I see [no evidence of you posting a Gist](https://gist.github.com/timmc) which would identify your account to Keybase. Could you please post a direct link to the Gist which is hosted with Github?

**Comment by timmc** [comment]
But it shows me Github on my profile... aha! The proof has started failing, and I didn't notice that "gist!" was festive red instead of festive green. I'll see if fixing that does the trick.

**Comment by timmc** [comment]
For what it's worth, here's the old gist, which... I guess stopped working? Maybe that deserves another bug, although it's 2 years old and maybe keybase had breaking changes since then. https://gist.github.com/timmc/d78ac17dcec759742d04

And here's the new one, which worked: https://gist.github.com/timmc/4e2687adf244739d1ec9
