### ISSUE TITLE
Question: where is data stored?

### ISSUE THREAD

**Issue by dbkaplun** [keybase/keybase-issues#1993]
I read https://keybase.io/introducing-the-keybase-filesystem but I am still a little unclear.. where exactly is the data stored? Is it decentralized, like BitTorrent Sync, or centralized, like Dropbox? Thanks in advance!

**Comment by cjb** [comment]
Centralized (on the Keybase servers), like Dropbox.

But unlike Dropbox in that there's signing and end-to-end encryption.
