### ISSUE TITLE
Login error - ERROR protocol not found: keybase.1.log

### ISSUE THREAD

**Issue by RandomLetter** [keybase/keybase-issues#1994]
Hi,

I'm running the following keybase versions.  I installed keybase using homebrew on OS X (10.10.5)
Client:  1.0.9-0
Service: 1.0.0-47

When I run "keybase login" I get the following error:
ERROR protocol not found: keybase.1.log

Thanks,
Rohit

**Comment by maxtaco** [comment]
This was due to a botched upgrade, I think. Does `pkill keybase` fix the problem?

**Comment by RandomLetter** [comment]
That fixed the problem.

Thanks!
Rohit

**Comment by maxtaco** [comment]
Glad it worked.  This shouldn't be an issue going forward, it was a bug in that release.
