### ISSUE TITLE
ERROR protocol not found: keybase.1.log

### ISSUE THREAD

**Issue by artursapek** [keybase/keybase-issues#1995]
I just updated from 1.0.3-0 to 1.0.9-0 by doing the following:

```
brew update
brew upgrade keybase
```

and now I get this for every `keybase` command:

![image](https://cloud.githubusercontent.com/assets/897596/12832589/dc4e36ec-cb68-11e5-907c-603edeeea4b9.png)

I was previously logged in and the client was working fine. Not sure what other info to provide. If there's a log file that would help, let me know where to find it and I'll post the contents.

**Comment by maxtaco** [comment]
Our bad, we botched an upgrade path.  It should be fixable with `pkill keybase`.  LMK if not.

**Comment by artursapek** [comment]
Wow, that was fast. Yes, this fixed it. Thanks a million!
