### ISSUE TITLE
Mac commands fail with "ERROR protocol not found"

### ISSUE THREAD

**Issue by offbyone** [keybase/keybase-issues#1996]
Every keybase command I run is resulting in this:

```
chrisros at a0999b1999c3 in ~
$ keybase login
▶ ERROR protocol not found: keybase.1.log
```

Keybase version is `1.0.9-0` installed via homebrew just today.

**Comment by maxtaco** [comment]
See previous issue.

**Comment by jeremywohl** [comment]
@maxtaco is referring to #1995, for those like me, slow on the uptake.

**Comment by offbyone** [comment]
That'll do it. I didn't realize it'd be resolved so fast.
