### ISSUE TITLE
keybase.io/pomf

### ISSUE THREAD

**Issue by banksymate** [keybase/keybase-issues#1997]
I setup my reddit, posted it didn't detect, so I tried removing my reddit. whenever I try to encrypt something to myself, it says that there is no server-given hint for sig=b6ce2117948ae90870a5b54749a7e39bd9490246552577c02a4d04dd2214ac820f

I also setup twitter, posted it. It says on the website that it is verified, whenever I use the command-line to encrypt something to myself it says
"BAD "iliuminous" on twitter failed: Could not find 'Verifying myself: I am pomf
on Keybase.io. 8a6cewzit2o7zuLKGbDqQADhzfOlGerGuBpq /' in 'Verifying myself: I a
m pomf on Keybase.io. 8a6cewzit2o7zuLKGbDqQADhzfOlGerGuBpq
/ https://keybase.io/pomf/sigs/8a6cewzit2o7zuLKGbDqQADhzfOlGerGuBpq .' (code=301
)"

**Comment by maxtaco** [comment]
thanks for the bug report, I'll look into the twitter thing right away, seems like a bug in our Go-client scraper.

**Comment by banksymate** [comment]
@maxtaco okay thanks. what about the reddit?

**Comment by maxtaco** [comment]
One thing at a time!

BTW, you're running windows, right?

**Comment by banksymate** [comment]
Yes.

**Comment by maxtaco** [comment]
I have a PR up for the twitter problem: https://github.com/keybase/client/pull/1896/files . It was caused by the newline you inserted before the `/` character, but we should handle that...

**Comment by maxtaco** [comment]
Looks like you fixed the Reddit issue via `keybase sig revoke`?

**Comment by banksymate** [comment]
I used the link and pressed post, didn't add anything. For the reddit, I revoked it and removed it from the server because I couldn't verify it, and it shows that message I put earlier.

**Comment by maxtaco** [comment]
Ah, I understand. We fixed this issue in 1.0.9, I think you're still on 1.0.8. Thanks!

**Comment by banksymate** [comment]
Is there an update command? Not familiar with all the commands yet.

**Comment by banksymate** [comment]
Nevermind, found it. Thanks

**Comment by banksymate** [comment]
"ERROR No updater available?"

**Comment by maxtaco** [comment]
Gah, @zanderz any thoughts on the Windows updater issue above?

**Comment by banksymate** [comment]
https://keybase.io/docs/the_app/install_windows shows latest as 1.0.8

**Comment by maxtaco** [comment]
@zanderz are there plans for a new command-line release?

**Comment by banksymate** [comment]
What's the latest Linux version, I have a server running Ubuntu server 14.04 that I can use

**Comment by maxtaco** [comment]
1.0.9 on the server...

**Comment by banksymate** [comment]
Package: keybase
Version: 1.0.9-1 <--
Architecture: amd64
Installed-Size: 33108
Maintainer: Keybase Bugs <bugs@keybase.io>
Section: misc
Priority: optional
Description: Keybase's command line client

I think the Linux version should work.
How come Windows is 1.0.8 and Linux is 1.0.9? Don't you guys use a language that compiles and works with different OS'?

**Comment by banksymate** [comment]
And the updater issue for Windows is still apparent.

**Comment by banksymate** [comment]
same w/ linux.
[temperr@pomf] |~ |// keybase update check
▶ INFO Forking background server with pid=1452
▶ ERROR No updater available

**Comment by maxtaco** [comment]
What about the reddit issue?

**Comment by banksymate** [comment]
Checking.

**Comment by banksymate** [comment]
reddit & twitter errors still apparent when running " keybase pgp encrypt pomf -m "testing" "

**Comment by banksymate** [comment]
Just added my reddit again, clicked the URL, posted exactly what it said. 
https://www.reddit.com/r/KeybaseProofs/comments/4492v6/my_keybase_proof_redditiambanksyok_keybasepomf/
Still fails to verify.

**Comment by maxtaco** [comment]
Your proof is pretty badly mangled; check out mine:

https://www.reddit.com/r/KeybaseProofs/comments/2clf9c/my_keybase_proof_redditmaxtaco_keybasemax/

**Comment by banksymate** [comment]
Weird, I did it from the link and pressed post.

**Comment by banksymate** [comment]
Maybe it's my browser? I'm using Firefox Dev Edition w/ NoScript(disabled), uBlock, and LastPass

**Comment by banksymate** [comment]
When I press "edit" it shows http://a.pomf.cat/sgtmnz.txt
Looks like the right formatting to me.

**Comment by maxtaco** [comment]
Wow, that's seriously mangled. urg.

**Comment by banksymate** [comment]
Also, since you're here. This confused me yesterday when I setup my account, when you go to your account page and it shows the setup instructions. It says "keybase gen" when it's actually "keybase pgp gen"

**Comment by banksymate** [comment]
Oh, I don't even see it there anymore.

**Comment by banksymate** [comment]
worked w/ chrome. weird

**Comment by banksymate** [comment]
ill try reverifying twitter with chrome too

**Comment by banksymate** [comment]
Okay. Everything seems to work after I used chrome. Weird, still gonna use Firefox though.
Thanks

**Comment by banksymate** [comment]
Also, you guys should make a check for the formatting on Windows, when it says "Is this the (username) you wanted?" The white-bold unix color code (not sure what they're exactly called just a guess lol) doesn't seem to work on Windows.
![Uploading svxjwi.png…]()
