### ISSUE TITLE
Attempt to recover account suggests 'keybase passphrase change', but 0.8.25 won't

### ISSUE THREAD

**Issue by kyanha** [keybase/keybase-issues#1998]
I've forgotten my keybase.io website passphrase.  I click 'recover account', and it suggests that if my computer is still logged in I should use the 'keybase passphrase change' command.

I attempt to do so, and it seems that such a command is not recognized by my newly-updated keybase installation.

Since I'd prefer not to have to rekey everything, is there any timetable for making this functionality available?

**Comment by kyanha** [comment]
Just realized that nothing from the old Javascript code is going to work.

**Comment by maxtaco** [comment]
`keybase version` for me?

**Comment by kyanha** [comment]
keybase (keybase.io CLI) v0.8.25
- node.js v0.10.32
- gpg (GnuPG) 2.0.28 (Gpg4win 2.2.5)
- libgcrypt 1.6.3
Identifies as: 'keybase.io node.js client v0.8.25 win32'

**Comment by maxtaco** [comment]
Yeah, the `keybase passphrase change` command will only work with our new Go app. Sorry, it probably won't work for you then to recover...

**Comment by kyanha** [comment]
No way to use my already-attested key to submit a passphrase change?  darn.

**Comment by maxtaco** [comment]
Not with GPG unfortunately.  In theory, yes, I don't think we implemented it though....

**Comment by kyanha** [comment]
Interesting.  It didn't appear to have reset my account.

**Comment by maxtaco** [comment]
Oh, so it worked?  Did you run `keybase passphrase recover`?  It's been about 5 months, I kind of forgot the parameters for that command.  Thanks!

**Comment by kyanha** [comment]
No, I had it send me a link via email, and I changed my passphrase through that.  When I did, I expected it to have wiped my account's gpg keys and already-existing proven identities.  It apparently did not.

**Comment by maxtaco** [comment]
We allow this form of key recovery if you don't store your secret key on the server and you don't have any device keys.

**Comment by kyanha** [comment]
Awesome, it looks like I've got it!

**Comment by kyanha** [comment]
(Thank you very much!)

**Comment by maxtaco** [comment]
Cool.  Took me a few minutes to page this back in, but the key points are:

* We use your keybase passphrase for some or all of, depending on your use:
   * authenticating yourself to the server
   * locking your server-synced PGP private key
   * locking your local device keys

If you lose your key, we can reset the first use, but not the second two, since we just don't know those secret values (by design).  So it looks like you only had the first use, and it was OK to do a traditional passphrase reset...

**Comment by kyanha** [comment]
I knew there was a reason I kept my private key local, and not synced to the server.  Cool, thank you very much!
