### ISSUE TITLE
Disable creation of repo entry on deb packages

### ISSUE THREAD

**Issue by edgard** [keybase/keybase-issues#1999]
Is this possible? Google, Dropbox and others have an option to disable to create the repo source.list on install, if I create for example a /etc/defaults/google-chrome or /etc/defaults/dropbox, it skips the creation of it.

Most of my setup is automated by Ansible, and it uses it's own naming scheme, so when installing keybase it adds a duplicate source.

**Comment by oconnor663** [comment]
Sure, we could do this. Is it as simple as saying, if `/etc/default/$whatever` exists, don't add the repo?

**Comment by edgard** [comment]
Yep! That would be it. Thanks!! :)

**Comment by oconnor663** [comment]
This should be work as of https://github.com/keybase/client/compare/59578b80b93bef2c78522e9f424cad6fd82aad68...fdbf6eeed4a3b255e9762f33f3024fb18cff3539, which will go out with the next production release.

**Comment by edgard** [comment]
Awesome, thanks a lot!

**Comment by oconnor663** [comment]
No problem, let me know if it gives you any trouble.
