### ISSUE TITLE
Cannot use GPG login on keybase version 1.0.9-0 (Failed to parse public key at position 3)

### ISSUE THREAD

**Issue by dametenshi** [keybase/keybase-issues#2000]
Consistently get:
```
▶ NOTICE Failed to parse public key at position 3
▶ ERROR Bad key family: No key found for 0101d022d1a5bb03f00d57f5982d8204572642f47d898791b612504f43463c0650c50a
```

when trying to login using GPG commands:
```
$ rm -r ~/Library/Application\ Support/Keybase
$ keybase login
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 4
In order to authorize this installation, keybase needs to sign this installation
with your GPG secret key.

You have two options.

(1) Keybase can use GPG commands to sign the installation.

(2) Keybase can export your secret key from GPG and save it to keybase's local encrypted
    keyring. This way, it can be used in 'keybase pgp sign' and 'keybase pgp decrypt'
    going forward.
Which do you prefer?: 1
#    Algo   Key Id             Created      UserId
=    ====   ======             =======      ======
1    R      FFFFADDEB0BA4A11   2015-01-24   *snip*
Choose a key: 1
▶ NOTICE Failed to parse public key at position 3
▶ ERROR Bad key family: No key found for 0101d022d1a5bb03f00d57f5982d8204572642f47d898791b612504f43463c0650c50a
```

Output of ```keybase login -d``` is attached
[keybase_login.txt](https://github.com/keybase/keybase-issues/files/118624/keybase_login.txt)

**Comment by maxtaco** [comment]
Do you have an RSA key with an unusually large public exponent?

**Comment by maxtaco** [comment]
I think you might be in the same camp as #1984

**Comment by dametenshi** [comment]
Might be… full ```pgpdump -i``` output attached:
[pgpdump.txt](https://github.com/keybase/keybase-issues/files/118643/pgpdump.txt)

**Comment by maxtaco** [comment]
Yeah, shucks. We're screwed here because Go decided to use a signed `int` for the `e` parameter in their RSA implementation.  Which would work for you if we didn't need to support 32 bit platforms, which we're currently doing.  Well now that there are two complaints with this, we might consider reimplementing :( their RSA but it probably can't be a high priority issue just yet.

**Comment by dametenshi** [comment]
Understood. Thanks for the quick responses

**Comment by maxtaco** [comment]
Reading a little bit more, I think Adam was thinking [along these lines](https://www.imperialviolet.org/2012/03/16/rsae.html) in that decision...  Hm... Maybe we can hack something together eventually....

**Comment by maxtaco** [comment]
We've forked the Go code. PR now up here: keybase/go-crypto#8

**Comment by dametenshi** [comment]
updated to keybase version 1.0.11-0. Looks good: https://keybase.io/bpugh/devices

**Comment by maxtaco** [comment]
:+1:
