### ISSUE TITLE
`gen` or `pgp gen` ?

### ISSUE THREAD

**Issue by avdd** [keybase/keybase-issues#2002]
The *getting started* instructions say to run `keybase gen`, but that doesn't seem to be a command ("no help topic for 'gen'").  I searched issues and code, and I see there's a `keybase pgp gen` command.  Is that the correct command or something different?

Thanks!

**Comment by strib** [comment]
Yes, you're right, it should be `keybase pgp gen`.  We already have a fix queued up for this, but it's not live yet.  Sorry for the confusion!

**Comment by avdd** [comment]
My fault for being in an early timezone!  Thanks!
