### ISSUE TITLE
Keybase can't find gpg on OS X

### ISSUE THREAD

**Issue by morgante** [keybase/keybase-issues#2005]
I am trying to log in to keybase using my PGP key, but Keybase can't find GPG.

The output of `keybase -d login` includes this:
```
12:59:26.620187 ▶ [DEBU keybase log.go:30] 02c gpg not an option: get index error: exec: "gpg": executable file not found in $PATH
```

This is despite gpg being installed and available:
```
13:00:03 morgante@tarvos ~ where gpg
/opt/boxen/homebrew/bin/gpg
```

I'm on `v1.0.9-0` of the OS X client. Is there any way to work around this?

**Comment by patrickxb** [comment]
Hi, `keybase` CLI should look for `gpg` in your `PATH`, but if that seems to be failing for you.  So you can supply the path to gpg like so:

    keybase --gpg /opt/boken/homebrew/bin/gpg login

Let me know if that doesn't work.  

I'm curious what your `PATH` is set to, though, to see what the problem could be.  So if you could also post the output of `echo $PATH`, that would be great.

Thanks!

**Comment by patrickxb** [comment]
Sorry, my last post was incorrect.  I believe we've tracked down the bug.  Will report back here soon when it is resolved.

As an awful, awful workaround right now, you could do `ln -s /opt/boken/homebrew/bin/gpg /usr/local/bin`.  I'm embarrassed to suggest that, but it should work until we get this straightened out.

**Comment by morgante** [comment]
Okay, the symlink worked as temporary workaround. FYI this is my PATH:

```
/Users/morgante/anaconda/bin:/opt/boxen/phpenv/shims:/opt/boxen/phpenv/bin:/opt/boxen/phpenv/plugins/php-build/bin:/opt/boxen/heroku/bin:bin:/opt/boxen/foreman/bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/node-build/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/opt/boxen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mpell/code/aws/eb/eb/macosx/python2.7/:/Users/mpell/code/bin/
```

**Comment by patrickxb** [comment]
Thanks!  We will have a release out soon that will use the user's PATH.  The current service has a default PATH set and thus can't find gpg if it is installed somewhere else.

**Comment by patrickxb** [comment]
@morgante version 1.0.11 is available via brew and should fix this issue for you.  Thanks for the bug report!
