### ISSUE TITLE
ERROR protocol not found: keybase.1.log

### ISSUE THREAD

**Issue by grobmeier** [keybase/keybase-issues#2007]
After upgrading keybase with:
```
$> brew update && brew upgrade keybase
```
to keybase --version:
```
keybase version 1.0.9-0
```

I get:

```
ERROR protocol not found: keybase.1.log
```

with all operations, like keybase login or keybase track <id>

**Comment by maxtaco** [comment]
We botched the upgrade from 1.0.8 to 1.0.9. Resolve this issue via 'pkill
keybase'   Sorry about that!

**Comment by grobmeier** [comment]
Thank you! Worked perfectly!
