### ISSUE TITLE
Install Keybase File System

### ISSUE THREAD

**Issue by diego898** [keybase/keybase-issues#2009]
Hello,

I have been a keybase user for some time, I saw that today you released the alpha version of the KBFS. How can I can use the alpha?

**Comment by patcon** [comment]
I am totally unofficial, but this is what got me on it: https://s3.amazonaws.com/prerelease.keybase.io/index.html

**Comment by strib** [comment]
Hi @diego898, thanks for your interest!  We're keeping the alpha very limited right now, but https://keybase.io/introducing-the-keybase-filesystem has instructions on who to email if you want to get on the list.  Thanks!

**Comment by patcon** [comment]
ACK :speak_no_evil:
