### ISSUE TITLE
Verify online out of sync with command line

### ISSUE THREAD

**Issue by diego898** [keybase/keybase-issues#2010]
I tried to verify my hackernews account through the command line, but when I tried to post it on hackernews I had a strange error. I then just did it directly through the site, and it seems the site believes I've went ahead and verified it. However, when I type `keybase id diego`, I get an error that kackernews isnt yet verified?

**Comment by diego898** [comment]
I just received an email from keybase saying this happened. How should I proceed?

**Comment by oconnor663** [comment]
I see your proof here: https://news.ycombinator.com/user?id=diego898
But not here: https://hacker-news.firebaseio.com/v0/user/diego898/about.json
Compare to the same query for my account: https://hacker-news.firebaseio.com/v0/user/oconnor663/about.json

It looks like there are issues with HackerNews's API. I'm looking into it.

**Comment by oconnor663** [comment]
Ok, this should be fixed now. Dan from Hacker News helped us fix the bug in their Firebase API. (Thanks Dan!) Can you verify, @diego898?

**Comment by diego898** [comment]
its working now! thanks Dan and @oconnor663 !

**Comment by oconnor663** [comment]
woo!
