### ISSUE TITLE
KEY_NO_ELDEST when trying to interact with keybase via GPG/cURL

### ISSUE THREAD

**Issue by jwives** [keybase/keybase-issues#2013]
Today I was hoping to track a keybase user and was using the command provided for bash + GPG + cURL to do so; this failed:

```
Error in your post
-------------------
Code: 920
Name: KEY_NO_ELDEST
Description: no eldest key for user
```

I receive the same response when trying to update my own key (which shouldn't actually be necessary but I was hoping that it might resolve whatever issue is popping up here).

Any suggestions?

**Comment by maxtaco** [comment]
I am on the train so I cannot investigate at the moment. Is it possible
your pgp key hosted on keybase has expired?

**Comment by jwives** [comment]
No - my master key expires in 2020 and the signing subkey I am trying to use expires in 2017:

```
pub   4096R/36809156 2015-10-12 [expires: 2020-10-31]
uid       [ultimate] Jason W. Ives (jwives) <jwives@jwives.com>
sub   2048R/D7CAF479 2015-11-02 [expires: 2017-11-01]
sub   2048R/901EEE6B 2015-11-02 [expires: 2017-11-01]
sub   2048R/8A0ABF02 2015-11-02 [expires: 2017-11-01]
sub   4096R/42F3E622 2015-10-12 [expires: 2018-11-01]
sub   4096R/6B6FF957 2015-10-12 [expires: 2018-11-01]
```

**Comment by maxtaco** [comment]
Ok. We will have to take a look.  Pretty busy so might take a bit.  Thanks.

**Comment by oconnor663** [comment]
Hmm, https://keybase.io/_/api/1.0/user/lookup.json?username=jwives lists your eldest kid as null, @jwives. I'll need to dig some more.

**Comment by jwives** [comment]
No worries. For what it's worth, keybase was able to successfully verify the following when I used the website:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hello Keybase!
-----BEGIN PGP SIGNATURE-----

iQEcBAEBCgAGBQJWtR3uAAoJEJXsMpOQHu5rWz8H/R9uybB5CYbqEcTfJPBO9KVE
BUXxd+K+95qV4GGULBpMWGgAF8rUY2BN9/sBN9w7zI4wmBsVw1veBMlkYJor1uz7
z0gHRtzeL4gcoliGnCzUEwDCj2XMynOEkVd83hcrQW6JKzJpxKpKRpa+anbYln3D
rw3TlDScsHHXy5OgfcNAVRagMn/kHBnU7nou1xyorLwJyE3uW9xMZBQ1OlIH50T8
Y1FVBFnad63dmYtdue1Jb/2OCXJkuTRhrcxginWPc4v3C+nhuir8Y3eOyNKDT1+6
/qOE6UlXJco81Jbl0FNo75dzUfCL9fOFjQKUyqEsXgTB4N6zaXfYooqSjMXerLI=
=sQZd
-----END PGP SIGNATURE-----
```

Thanks for the help!

**Comment by oconnor663** [comment]
Yeah, the server knows that you have *some* keys, it just got into a weird state about which one is your eldest/first key, which is important for keeping track of the history of your whole identity. (@maxtaco looks like the [merkle tree eldest kid is null too](https://keybase.io/_/api/1.0/merkle/path.json?username=jwives).)

**Comment by oconnor663** [comment]
We saw a bug like this a few weeks ago but now I can't remember which one it was...

**Comment by maxtaco** [comment]
Agreed.  It was in Jira as I recall.  Offline until around 8 unfortunately.

**Comment by maxtaco** [comment]
@jwives looks like you did a PGP update when we had a bug on 11/2.  I can fix it for you on the server side, stay tuned!

**Comment by maxtaco** [comment]
@jwives have you configured your GPG client to emit V3 signatures?

**Comment by maxtaco** [comment]
Server-side fix up.  Client side fix at: keybase/client#1921

**Comment by jwives** [comment]
Thanks for working on this so quickly...

@maxtaco -- no, I haven't configured GPG to emit V3 signatures; are V3 signatures required for working with keybase?

I'm still encountering this error when trying to use GPG + cURL; will I need to be using the keybase client for this to work? I still need to give that a try but prefer to use GPG and cURL for now.

Although it would be inconvenient, as I'd have to post new verifications, should I just try replacing my key entirely and see if this problem goes away? It seems a bit odd to do since I've got the same fingerprint and all, though my use of keybase isn't large enough to have this cause a problem other than having to go and create new verification posts/records.

**Comment by maxtaco** [comment]
Ok, now it should be better, try it again via GPG + cURL?  Thanks!

**Comment by maxtaco** [comment]
(And no, V3 signatures aren't required, it was a wrong guess on my part...)

**Comment by jwives** [comment]
Looks like everything is working as expected now - I noticed before that nothing was showing up at https://keybase.io/jwives/graph but that's not the case now; guessing there was something odd with me in keybase?

Thanks for the help!

**Comment by maxtaco** [comment]
:+1:  Thank you for the bug report!

**Comment by maxtaco** [comment]
(and your patience)
