### ISSUE TITLE
problems with command line on OSX

### ISSUE THREAD

**Issue by jaywgraves** [keybase/keybase-issues#2014]
I know my passphrase and can sign in on the web but I can't seem to login using the command line tool.

when running
 
    keybase login jaywgraves
    How would you like to sign this install of Keybase?
    
    (1) Use an existing device
    (2) Use a paper key
    (3) Use my Keybase passphrase
    Choose a signing option:

I can't use 1,2 because I don't have an existing device or a paper key and using my known passphrase from web (tried multiple times so I know I didn't typo)

    ▶ ERROR No synced secret PGP key stored on keybase.io for jaywgraves; please try logging in via GPG, an existing device, or a paper key (error 901)

I don't know how to proceed.

**Comment by maxtaco** [comment]
Do you have gpg installed?

**Comment by jaywgraves** [comment]
yes.  (I didn't at first but then installed with brew.)

**Comment by strib** [comment]
Now that you have gpg installed, do you see a (4) option when you run `keybase login`?  You'll need to have your private PGP key (the one associated with your Keybase public PGP key) imported into GPG on your local device.

**Comment by jaywgraves** [comment]
No option 4.

(although I did a `keybase pgp pull jaywgraves` and it says it imported my key)

the next `keybase login jaywgraves`  still has 1-3 from above and 3 with correct passphrase fails with same error as above.

**Comment by strib** [comment]
Hmm.  If you lost your private PGP key, you might have to reset your account.  It looks like the website doesn't have it, based on your error message.  @oconnor663, maybe you can double check his account to make sure the encrypted private key is in a weird state?

**Comment by jaywgraves** [comment]
I figured that might be the case.  (but was scared to do the reset until I was sure I just wasn't doing something wrong.)

I was an early user and remember tracking people from the web.  As I mentioned, I never installed the Node client because I was primarily on an older version of windows at the time.  So I *think* but I don't know that I never actually downloaded my private key file.

**Comment by jaywgraves** [comment]
I ended up resetting.
