### ISSUE TITLE
`keybase pgp encrypt` fails when my own key is involved: "cannot encrypt to public key of type 17"

### ISSUE THREAD

**Issue by timmc** [keybase/keybase-issues#2019]
I can only encrypt messages with keybase if I include `--no-self`. I'm using keybase 1.0.9-1 on Debian 7 (Wheezy). Demonstration of failure and success, with tracking output removed:

```bash
timmc@curmudgeon:~$ keybase pgp encrypt -m "test" chris
▶ INFO Generating tracking statement for chris
...
▶ INFO Your tracking statement is up-to-date
▶ ERROR openpgp: invalid argument: cannot encrypt to public key of type 17
```

(That appears to be an error message from a Go crypto library.) Adding `--no-self`:

```bash
timmc@curmudgeon:~$ keybase pgp encrypt --no-self -m "test" chris
▶ INFO Generating tracking statement for chris
...
▶ INFO Your tracking statement is up-to-date
-----BEGIN PGP MESSAGE-----
Comment: https://keybase.io/download
Version: Keybase Go 1.0.9 (linux)

wcFMA9IkQTsc+mSQARAAEi/y/tTlXyPSkQnVwQ9Ia+Fqv+rjEDRiRli+NcPjaEMt
DC+eL2Ok0oZgwtl2r/vVJ9cEXifZ3wIWHcwsGE/d0qMsqae5qeILYwXjOIuGFcka
eH+ye1sQOxNJkQ91Qo5Cee0kX07xI2rGr9dU913CTRk89RJgNiI91AqygjoOZpFI
QEuincGCh7+P7e/Zm/KI1RbJQC5L/975gR+nUm2ei5hvs0FmdMjkjgzwmKrHICnC
iSRXBHibjgbD5+nnlyhJWDqbL/SE6EaOTmR9kAzl/jlw+EWlp85n/P9sNBiDnfsy
ZLHkdwgztP3pCKgFswXLEE1KbacD5iMCXL+Kdxfj/zpiCyFjaQnB/8/fqctaMDa1
K2tOcHEV7YyLtGtKqbVmdLXvTvaXNZp6o6+Ddr3AWnlvOcapg7LRc4o7yQb0iNvh
x5VsIzPs3BD0dlkN9wnucxPbM+2CY91kgKH+M0fHAYPYPhGwHmPfuKpHhPTcnuZh
nZg+mt8SAlgouNZyJIosuG9U0DdYbgBqSQ7DZ37o8iSdrLSFQ9bijda2TYvgc7bi
yLR3zdDWM36y1Uby/qp00h7+P/xKIX95oM9+INBGMMqb6t+UASvHzJt5efplq7As
IFdDhU13CiVS9zMm5mz7dosIUjQlWSuszVqEnFEXSQ+hiVpnPgM9GJx6IyqEPBnS
4AHkJwcY2pr4P3+TlGBbRDXsPOHzmOCi4D/hLJHgreIvSYgD4Cni7+teqODQ5OQ+
lCRgUKHeYVJLGsKZVxXiaL8IYuGy0wA=
=vHPX
-----END PGP MESSAGE-----
```

This happens with or without having recently unlocked the GPG agent, although that certainly shouldn't matter.

**Comment by maxtaco** [comment]
Yeah, that's screwed up the go libraries are trying to encrypt to a DSA key.  I have a hunch for what might be going on, but won't be able to follow up for a bit.  Thanks for the bug report!

**Comment by timmc** [comment]
Ah, same as #1910 then? OK, will track that issue instead, feel free to close this one if that's the case.

**Comment by maxtaco** [comment]
Sigh, that's a different issue.  That's EdDSA.  This is regular old DSA.

**Comment by maxtaco** [comment]
I think I've fixed this, can you let me know if not?  Thanks!

**Comment by timmc** [comment]
I think it's fixed, although there's another bug to file or find.

Using version 1.0.11-20160212170047+3050b64 I can do the encryption without `--no-self`, and `gpg --decrypt` works on the resulting ciphertext, but keybase cannot decrypt it:

```bash
keybase pgp decrypt < msg
▶ ERROR decrypt error: unable to find a PGP decryption key for this message
```

**Comment by maxtaco** [comment]
Great news. Ish.

Can you rerun keybase pgp select --only-import

I think it failed to import your elgamal subkey the last time.

**Comment by timmc** [comment]
Yes, that worked, thanks! After `keybase pgp select --only-import` I was able to run `keybase pgp decrypt` successfully.

**Comment by maxtaco** [comment]
Excellent.  Yeah it was about 3 related bugs in the go pgp library that
masked each other.  Glad it is fixed!
