### ISSUE TITLE
"argument list too long: curl" when verifying very long key with curl

### ISSUE THREAD

**Issue by vollkorn1982** [keybase/keybase-issues#2026]
My key expired, so I extended it's expiry date locally and wanted to upload the modified key on the keybase web-frontend. I clicked "edit  key", pasted my new (very long: 588KB!) key and then selected the "command line with [bash + GPG + cURL]" method. But pasting that into my terminal gives me an error:

`argument list too long: curl`

I suggest to use a different way of getting the key. For example by piping it from gpg into curl and use --data-urlencode - to read the key from the pipe.

**Comment by oconnor663** [comment]
Oh dear. Another option here (if you didn't already edit that script) is `keybase pgp update` using the command line app.

**Comment by oconnor663** [comment]
Unfortunately we can't trust that gpg will export exactly the public key that you _said_ you wanted to upload, so the huge armor blob has to be in there somewhere. I worry that even if we try to do some clever hack with a `<<HERE` input, we're still going to break something.

**Comment by vollkorn1982** [comment]
Hi @oconnor663,

I understand your reasoning to not trust gpgs output. But as a software developer with some UX experience I strongly recommend reopening this bug and thinking about other options to avoid this problem.

1) `keybase pgp update` is not always an option. Like for me. I had an expired key on keybase.io and neither a machine where I was logged in, nor a paper key. So this was the only way I was able to verify my key.

2) Telling users to run a command that is known to fail is a really, really bad user experience. You can check the length of the key and above a certain cut off give a warning or a longer explanation on how to get around this problem (like putting the key into a file).

3) It looks really bad on you to know about but not have this bug fixed on purpose and let users figure it out.

**Comment by oconnor663** [comment]
Filed https://keybase.atlassian.net/browse/CORE-2535 inernally.
