### ISSUE TITLE
Verifying hackernews http fails 

### ISSUE THREAD

**Issue by KrishMunot** [keybase/keybase-issues#2031]
The verification of HackerNews failed regardless of the profile being live.

**Comment by swsnider** [comment]
Ditto -- you can see mine here: https://news.ycombinator.com/user?id=thesnider

**Comment by maxtaco** [comment]
Urg: https://hacker-news.firebaseio.com/v0/user/thesnider/about.json

We're stuck dealing with this flakey API, not much we can do.

**Comment by swsnider** [comment]
Is there a technical reason we couldn't use screen-scraping for this? Not even 'real' screen-scraping, just look for `[ my public key:`, or something, and understand html entities?

**Comment by maxtaco** [comment]
It's against their ToS and they very aggressively blackhole scrapers.

**Comment by swsnider** [comment]
Oh, well, thanks for responding so quickly.

**Comment by steko** [comment]
According to [the official documentation](https://github.com/HackerNews/API#users) the correct URL would be https://hacker-news.firebaseio.com/v0/user/thesnider.json?print=pretty however the "about" field doesn't match for your user (but it does for the example `jl` user in the documentation).

**Comment by nbarbettini** [comment]
My hackernews proof is also repeatedly failing: https://news.ycombinator.com/user?id=nbarbettini

**Comment by ericsampson** [comment]
Ditto. Why not reach out to the site admins and see if there's something they could do on their end? hn@ycombinator.com

**Comment by oconnor663** [comment]
(Similar reports at https://github.com/keybase/keybase-issues/issues/1874.)

I'm in touch with Dan at Hacker News support, and he tells me that they've fixed the source of these stale API reads, but going through the backlog of stale accounts might take a while. I've mentioned your usernames to him, so hopefully everything will magically be working shortly.

**Comment by ericsampson** [comment]
Thanks @oconnor663 !

**Comment by crw** [comment]
I am also having this issue. Thanks!

**Comment by swsnider** [comment]
@oconnor663: Are you guys going to restart the attempts to verify on your end? I got an email saying that Keybase.io gave up.

**Comment by swsnider** [comment]
Nevermind, found the button on my profile :)

**Comment by maxtaco** [comment]
you can use the the Web UI to restart the checker

**Comment by andyburke** [comment]
Seeing this as well, tried the button on my profile to update but the issue is on the HN side:
https://hacker-news.firebaseio.com/v0/user/andyburke.json?print=pretty

**Comment by nbarbettini** [comment]
Update: retried my hackernews proof through the web UI, and it succeeded this time! Thanks for looking into this. :+1:

**Comment by crw** [comment]
:+1: Works. Thanks!
