### ISSUE TITLE
Removing devices example is wrong on the website

### ISSUE THREAD

**Issue by svenluijten** [keybase/keybase-issues#2033]
When looking up how to remove a device, it's stated that you should run `keybase device remove '<id>'` (with quotes!), while in reality it should be without the quotes. This can be found on https://keybase.io/username/devices, then open a dropdown for one of the devices listed.

![](http://puu.sh/mZ3fn/f021a909a4.png)

**Comment by maxtaco** [comment]
Are you on Windows?

**Comment by svenluijten** [comment]
I am, yes.

**Comment by maxtaco** [comment]
Ok our bad.  On Linux and OS X those quotes are ignored.  On Windows they
have meaning. We will fix the docs.

**Comment by svenluijten** [comment]
Sweet, thanks :+1:
