### ISSUE TITLE
Unable to verify hackernews identity

### ISSUE THREAD

**Issue by extesy** [keybase/keybase-issues#2035]
I've tried multiple times, both from command line and from the browser. Keybase can't find the proof and sends a failure email a day later. Here's my profile: https://news.ycombinator.com/user?id=extesy

**Comment by steko** [comment]
Seems you encountered the same issue described here: #2031

**Comment by extesy** [comment]
Seems so. Apparently HN API is broken since https://hacker-news.firebaseio.com/v0/user/extesy.json?print=pretty doesn't have "about" field populated.
