### ISSUE TITLE
Error: duplicate key ''

### ISSUE THREAD

**Issue by Tomalak** [keybase/keybase-issues#2036]
Trying to do anything (signing, encrypting, tracking) on the keybase.io website fails with the error 

> Error: duplicate key ''

or, in the case of tracking, with the slightly more elaborate, but equally unhelpful

> Error: Your private key appears corrupted (duplicate key '')

I am at a loss of what I need to do now. My key graph is over here: https://keybase.io/tomalak/graph - I can't see any duplicate keys in there.

Other phenomenons:

 - I can log out and log in to the website, so I do have he keybase.io account password correct (it's not the same as my key passphrase, never has been)
 - I can also log out and back in again on the command line (using version 1.0.8-0 btw)
 - Signing actually works on the command line, therefore I know that I still have the correct passphrase to my secret key (PGP key keybase.io/tomalak <tomalak@keybase.io> 134E854E117D1A21). 
 - Tracking users works from the command line, **but only** shortly after I signed something, i.e. when my passphrase for the above key is still in the cache.
 - Tracking someone ad-hoc fails on the command line, the client asks me for the password of my device key, which I apparently don't have (I'm also unsure why or how I should have such a passphrase, my account predates the switch to the device-based system).

So... it looks like something about my account is botched. I'd love to fix this but I no longer dare touching anything.

**Comment by maxtaco** [comment]
I'll take a look

**Comment by maxtaco** [comment]
Can you send a JS stacktrace?  Which browser are you on?  Thanks

**Comment by maxtaco** [comment]
The password on your device key is the same as your passphrase for keybase BTW

**Comment by Tomalak** [comment]
This is happening on Chrome 49.0.2623.13 dev-m (64-bit).

How do I add a stack trace when there are no errors in the console?

**Comment by maxtaco** [comment]
Is this an unstable build? Does it happen in a stable browser and/or firefox?

**Comment by Tomalak** [comment]
Yeah, it's the dev channel, so let's give it a go in Firefox (44.0, just updated)...

It works, that's interesting. 

Any way I can help with providing insight into why it fails on Chrome?

**Comment by maxtaco** [comment]
Seems like we're having msgpack failures on dev Chrome.  I haven't seen this particular issue before on dev channel chrome, but I've seen others related to broken buffer-slicing code.... There's a ticket open for it in feros's buffer polyfill (I forget the exact repo)

**Comment by Tomalak** [comment]
I have just updated Chrome to 50.0.2638.0 dev-m (64-bit) and the problem seems to be gone, so scratch that. 

Boy, do I hate to open an issue that dissolves just like that. :/

**Comment by maxtaco** [comment]
no worries.  i'm just glad it wasn't yet another bug in Go OpenPGP!

**Comment by maxtaco** [comment]
CC: @malgorithms there's another problem with dev channel Chrome builds ^.  It might be the same issue of course, just showing up someplace else...

**Comment by Tomalak** [comment]
Well, there's that. :)

Now, help vampire mode, because it's not clear to me even after reading the docs. I had set up my keybase.io account to have passord A and my PGP key to have passphrase B. This involved some manual steps but it worked well and I rather like the setup.

Then came the change to device keys, and the setup still works. But things get a bit muddy - is it still possible to maintain such a setup? What happens if I do `keybase passphrase` - will it change the website password? The pgp key passphrase? Both? What about the device keys? I admit, I'm a bit confused.

**Comment by maxtaco** [comment]
We have a doc on this but haven't published it yet.

Our goal with keybase is only: (1) one passphrase to remember (either for logging in to Website, or for locking your local keys); and (2) this doesn't mean a compromised server can unlock your local keys (this is crucial); and! (3) if you update on one device, the other devices show the update too, even if they weren't online at the time.

We've actually achieved all 3, using some simple crypto. I hope to get the doc up soon.

The one thing we can't do is affect the way you choose to lock your PGP keys in your local GPG keyring, since that's outside of our purview.  We do use the system above for locking/unlocking your PGP key if you allow us to import it into the keybase local keyring.

**Comment by Tomalak** [comment]
I'm really curious to read how this works without compromising security on the way. Thanks so far, @maxtaco.

**Comment by malgorithms** [comment]
@maxtaco  - the next time this happens let's get them to confirm it's the same `.slice()` issue, then track down where we use it.

**Comment by maxtaco** [comment]
Yeah I meant to trace it back to the purepack library but didn't get a
chance.  It feels like the same issue.

**Comment by maxtaco** [comment]
I believe [this line](https://github.com/maxtaco/purepack/blob/master/src/buffer.coffee#L201) to be the culprit.  FWIW, I implemented most of this class before there was a good Buffer polyfill for the browser. But eventually I believe I changed it to take advantage of the Buffer polyfill in browserify.
