### ISSUE TITLE
Invalid name error on command line example

### ISSUE THREAD

**Issue by roelvanderplank** [keybase/keybase-issues#2038]
Installed the command line client on windows. Using the following example keyboard command:

keybase encrypt maria -m 'secret message'

with 'maria' replaced* by a user that I know, gives the error:
ERROR invalid name (bad fields: username) (error 100).

The strange thing, if I add a _ to the message, e.g. 'secret message' ==> 'secret_message', the command is succesfull and I get a complete --BEGIN PGP -- END PGP block.

Looks like a problem with the client (commandline client on windows)?
For the record: keybase update check gives an error as well, --ERROR: No updater available, as the commandline client is only a few days old (new user!), an old version does not seem to be the problem...

Kind regards,
Roel

* Actually, the message was "een geheim" which is "a secret" in Dutch.

**Comment by maxtaco** [comment]
Are you on Windows?

Use double quotes on Windows. Should work.  We should update the docs

Cc @malgorithms @zanderz

**Comment by roelvanderplank** [comment]
OK, seems logical that it would be something like that. Will check at home, but for now closing the issue seems appropriate. Kind regards (and thanks), Roel
