### ISSUE TITLE
KBFS Not Running; kbfsfuse command not found

### ISSUE THREAD

**Issue by jameyhammock** [keybase/keybase-issues#2045]
I apologize if this is documented elsewhere and I just missed it, but does KBFS have to be separately installed?  Output from "keybase status" shows KBFS is not running and the log file indicates "kbfsfuse: command not found".

Platform: Ubuntu 15.10

Installed (as documented https://keybase.io/docs/the_app/install_linux):
curl -O https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb && sudo dpkg -i keybase-latest-amd64.deb

$ keybase status
Username:      jameyhammock
Logged in:     yes

Device:
    name:   work-vbox-ubuntu15
    ID:     106aa53ddc95ce53eaef559b8c408318
    status: active

Local keybase keychain: locked
Session status:         no session

KBFS:
    status:    not running
    version:   
    log:       /home/osboxes/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.10-0
    log:       /home/osboxes/.cache/keybase/keybase.service.log

Platform Information:
    OS:        linux
    Runtime:   go1.5.3
    Arch:      amd64

Client:
    version:   1.0.10-0

Desktop app:
    status:    not running
    log:       /home/osboxes/.cache/keybase/keybase.gui.log

Config path:        /home/osboxes/.config/keybase/config.json
Default user:       jameyhammock
Provisioned users:  

command-line client(s):
    keybase status [pid: 19692, version: 1.0.10-0]
$ cat /home/osboxes/.cache/keybase/keybase.kbfs.log
/usr/bin/run_keybase: line 47: kbfsfuse: command not found
$

**Comment by oconnor663** [comment]
My bad! `run_keybase` should not be included in our production packages, since it doesn't work without KBFS. The KBFS bits aren't a separate package, but we're still testing them, and we haven't added them to the production package yet. The next production package will remove the `run_keybase` script, until the KBFS bits are actually ready to go in there.
