### ISSUE TITLE
Multiple PGP keys but one "raw" key URL

### ISSUE THREAD

**Issue by smoyer64** [keybase/keybase-issues#2046]
I'm one of those people that use completely different PGP key-pairs for work and "other" but I've got a slight twist on the (many) issues filed.  I've uploaded both keys to keybase.io (the second with the --multi flag) but I'm not quite sure how to provide links to my raw public keys.

If I click either key in my profile, I get a pop-up window that contains the appropriate public key text for the chosen fingerprint.  Unfortunately, the "curl/raw" link provided in both pop-ups is https://keybase.io/smoyer/key.asc which always points to the first key I uploaded.

Can a URL be provided for each of the PGP keys uploaded?  Perhaps something like:

```
https://keybase.io/smoyer/<fingerprint>/key.asc
https://keybase.io/smoyer/D8D464C9D22FB8E0/key.asc
https://keybase.io/smoyer/1D058DBEB558C308/key.asc
```

**Comment by iambrosie** [comment]
I just stumbled across this issue myself.
I would also like to mention the fact that I like your proposed solution.

**Comment by jdblair** [comment]
I also just reproduced this same issue - I added a second key, but now there's no curl/raw link to the second key. I like smoyer64's proposed solution - it mirrors the way I extract the keys using the "keybase pgp" command.

**Comment by malgorithms** [comment]
ok, finally fixed this, thanks for your patience. Check out my notes/example on #2665
