### ISSUE TITLE
Upgraded keybase, try to login, fail with with "install GPG and put your PGP private key on this machine and try again"

### ISSUE THREAD

**Issue by mrled** [keybase/keybase-issues#2047]
Hello, 

1. I had Keybase 0.8.22 installed on my Mac, and it was working
2. I upgraded to 1.0.9-0
3. It asked me to login again, so I ran `keybase login`
4. I don't have any paper keys (yet) or other devices, so I want to log in using my Keybase passphrase
5. I enter my username and passphrase and it results in the following error: 

        ▶ ERROR in Login

        Sorry, you have a PGP private key that Keybase doesn't have a copy of.
        You need to prove you're you. Any of these will unlock this computer:

           - reset your account and start fresh: https://keybase.io/#account-reset
           - install GPG and put your PGP private key on this machine and try again
           - go back and provision with another device or paper key

... but the thing is, my PGP key *is* on this machine. I was using it to encrypt and decrypt with the old version of Keybase, and also from the `gpg` command line directly. 

I'm not sure of the ramifications of resetting my account, and as I mentioned I don't have another device or paper key yet. I'd like to give Keybase whatever it needs to see my private key. What do I need to do? 

Note: I want to keep my private PGP key on my local devices - Keybase does not have a copy. 

Thanks

**Comment by mrled** [comment]
I managed to work around this

For unrelated reasons, after I encountered this error, I installed [GPG Tools](https://gpgtools.org) on my Mac (note: I had commandline `gpg` installed before encountering the error; GPG Tools is a GUI). Even later, I decided to try `keybase login` again. 

Before, I had only the first three of these signing options, but after installing GPG tools, I had a fourth: 

     me@laptop> keybase login
     How would you like to sign this install of Keybase?
    
    (1) Use an existing device
    (2) Use a paper key
    (3) Use my Keybase passphrase
    (4) Use GPG
     Choose a signing option: 

Then: 

1. I selected the new, fourth item, "Use GPG"
2. I selected "Keybase can use GPG commands to sign the installation"
3. I chose my private key from a list of all the available private keys on this computer
4. I entered my private key's passphrase 
5. I copied down my new paper key 

And I was logged in.

**Comment by maxtaco** [comment]
cc: @patrickxb.  I believe this issue is resolved in master.  It was a path problem finding GPG I belive

**Comment by mrled** [comment]
Ahhhh, that might make sense. My GPG is installed to a nonstandard place (though it is in my `$PATH`), but I noticed that GPG Tools installs another binary to `/usr/local/bin/gpg`.

**Comment by maxtaco** [comment]
We had an issue that the service is started by launchd and doesn't get your shell path. But we've since worked around that issue by having the client update the service's path...

**Comment by patrickxb** [comment]
Yes, this will be fixed in 1.0.11.

**Comment by jc00ke** [comment]
I'm seeing the same thing on Ubuntu 15.10 that had `keybase` working previously.

I have `gpg` installed to `/usr/bin/gpg` and I'm running `keybase version 1.0.11-20160212170047+3050b64`

```
➜ ~ gpg --list-keys
/home/jesse/.gnupg/pubring.gpg
------------------------------
pub   4096R/EC8C9492 2014-04-26
uid                  Keybase.io Merkle Signing (v1) <merkle@keybase.io>
sub   4096R/8080955B 2014-04-26
sub   4096R/49DA99D5 2014-04-26 [expires: 2024-04-23]

pub   4096R/F03AB48B 2014-10-27
uid                  Jesse Cooke <redacted@gmail.com>
uid                  Jesse Cooke <redacted@jc00ke.com>
uid                  keybase.io/jc00ke <jc00ke@keybase.io>
sub   4096R/7482B4F8 2014-10-27
```

I still find `gpg` to be quite confusing, so any help would be greatly appreciated. I'd like to avoid resetting my account, and I don't have a paper key (oops!)

Thanks!

**Comment by westonruter** [comment]
I just installed `1.0.13` and I have the same issue.

My key is already linked to my Keybase account and it worked in an older version of `keybase` (prior to the new key model), but the newest version can't find my private key when I try the “Use my Keybase passphrase” option:

> ▶ ERROR in Login
> 
> Sorry, your account is already established with a PGP public key, but this
utility cannot access the corresponding private key. You need to prove
you're you. We suggest one of the following:
> 
>    - install GPG and put your PGP private key on this machine and try again
>    - reset your account and start fresh: https://keybase.io/#account-reset
>    - go back and provision with another device or paper key

If I try again and do “Use GPG” with “Keybase can use GPG commands to sign the installation.” I get:

> ▶ ERROR Could not open key: no valid primary key self-signature (error 905)

If I try instead to do “Keybase can export your secret key from GPG and save it to keybase's local encrypted keyring” I get:

> ▶ ERROR openpgp: invalid data: entity without any identities

I have GPG 1.4.20 installed via Homebrew and it is located at `/usr/local/bin/gpg`

**Comment by maxtaco** [comment]
Can you paste in the output of `gpg --export -a <your-GPG-key-ID>` here?

**Comment by westonruter** [comment]
@maxtaco My key ID `0x632FBCAE` and here is the output: https://gist.github.com/westonruter/2cab7b0244a0cc9a003b#file-0x632fbcae-key-txt

**Comment by maxtaco** [comment]
Thanks.  No guarantee when I can get to it.  The Go PGP library is crapping out on your key.  Thanks...

**Comment by maxtaco** [comment]
@westonruter can you also do a `keybase log send` ? Thanks

**Comment by westonruter** [comment]
@maxtaco thanks, yeah, log ID is 6700878f0c86cf65d1883f1c

**Comment by maxtaco** [comment]
Seems like it's a server-side error on our part.  Will investigate further!

**Comment by maxtaco** [comment]
@westonruter can't repro this issue.  Do you have several local keys?  Which one are you selecting?  So see, try `gpg -K`.   We ask you to pick, maybe you're picking the wrong one that's expired?

**Comment by maxtaco** [comment]
I managed to repro, your key on our server is expired.  Update it via the web site, and then try again.  See the attached screenshot

Note to team: we should make better debugging in this (common) case....

![screen shot 2016-02-22 at 9 09 00 pm](https://cloud.githubusercontent.com/assets/866815/13239499/d463711a-d9a8-11e5-8658-0e74ef10ba87.png)

**Comment by westonruter** [comment]
@maxtaco thanks. I updated my key. I was then able to login by signing the install via GPG and with the “Keybase can use GPG commands to sign the installation” option. When I tried to authenticated via Keybase passphrase I got the  same error as before, and when I tried GPG with the option to export the secret key into the local encrypted keyring, it also gave the same error as before. In any case, one method worked, and I now have device provisioned. Thanks for the help.

**Comment by a11enh** [comment]
I may be experiencing a similar issue (somewhat less experienced user here) - I just now managed to remove macports, install homebrew, and of course wanted to install keybase (item that finally pushed me over the edge to homebrew).  I am using a key on a Yubikey4, so I have no actual access to the secret key, other than by way of access to the hardware key.  For some reason I'm also getting the secret key error seen above.  (probably not properly performing needed steps to login on CLI)
