### ISSUE TITLE
Remove a public key from Keybase.io message is incorrect

### ISSUE THREAD

**Issue by talves** [keybase/keybase-issues#2053]
Keybase.io message should be `keybase pgp drop <key>`, so `pgp drop` rather than `revoke`. Might be a good idea to stick with just one description **revoke vs delete vs drop vs remove**
![image](https://cloud.githubusercontent.com/assets/784848/12936909/dbfd8bc8-cf57-11e5-953b-2cfed3d9db44.png)

**Comment by oconnor663** [comment]
Thanks for the report, this should be fixed now.

**Comment by oconnor663** [comment]
The trouble with naming here is that "revoke" means at least two very different things. One is adding a signature to your Keybase sigchain, saying that the key is no longer connected to your Keybase identity going forward. The other is inserting a revocation packet into the PGP key itself, saying that the key is never valid for anything ever again. We really don't want to make PGP users think we're doing the second thing, when we're only doing the first thing. "Drop" was what we came up with, though I wouldn't be surprised if we could think of something better.

**Comment by talves** [comment]
Yeah, after reading through some more I have to agree with you. There is definitely a difference between deleting of a key off Keybase and dropping it from Keybase. Drop is good for the CLI, because that made more sense once I found it in the docs. 

You guys have some great stuff here. Keep up the good work.

**Comment by oconnor663** [comment]
Thanks :)
