### ISSUE TITLE
ability for multiple people to prove same web identity domain

### ISSUE THREAD

**Issue by doapp-ryanp** [keybase/keybase-issues#2060]
I think keybase can be a powerful tool to share information from a business to their clients.  However one feature I think is missing is the ability for multiple people to verify a web identity for the same domain.

For example: I work at doapps.com, and I want to encrypt and sign data to send to our customers.  I can invite them to keybase, I can email them a link to my keybase profile - but ultimately they want to know without a doubt that I (and my keybase user) work at doapps.com.  The current solution (and its a good one) is to verify my keybase user with a web identity for doapps.com.

However, from what I can tell, only one person can "verify web identity" for doapps.com as there is only one `http(s)://doapps.com/keybase.txt` or one `txt` record.  My proposal is to support convention based file names / TXT records so that multiple employees can verify they work for a company.  Ex: `http(s)://doapps.com/keybase-rynop.txt`

Also I think it is important to support verification of multiple web identities. I want people to know my keybase profile has been verified to own my personal site (rynop.com) as well as my work website (doapps.com).

Are either of these already supported? Haven't had luck searching through the issues.

If not would anyone else find this useful?

**Comment by maxtaco** [comment]
this works, just concatenate, check out
https://keybase.io/.well-known/keybase.txt

**Comment by doapp-ryanp** [comment]
@maxtaco sweet! thanks for the quick reply. 

I also notice that once I verify one web ident, I get the ability to add another.

Wonderful work here guys, really.
