### ISSUE TITLE
Clarify why the installer requires root privs on install page

### ISSUE THREAD

**Issue by dametenshi** [keybase/keybase-issues#2064]
Looks like [there's some concern](https://storify.com/dametenshi/conversation-with-flamsmark-zmanian-and-dametenshi-56bd3d516baca8e90c2628f5) about having to run dpkg/rpm/pacman with root privs to install keybase. Perhaps [the install page](https://keybase.io/docs/the_app/install_linux) needs some disclaimer about why root privs are required and maybe a link to the install script source so it can be inspected?

**Comment by maxtaco** [comment]
@oconnor663 what's the story on root?  We don't need it for FUSE, but I just figured that debian makes you do all `apt-get` work as root.  Is there an unprivileged `apt` workflow?

Thanks for the feedback @dametenshi!

**Comment by maxtaco** [comment]
...OSX is sadly a different story.  We need root to stall the FUSE kext.

**Comment by dametenshi** [comment]
Looks like [tor's install instructions](https://www.torproject.org/docs/debian.html.en) don't require root so presumably it's not _required_ unless you're writing to a path owned by root (← guessing here, but IANA engineer 😜)

**Comment by cjb** [comment]
dpkg, yum, rpm, apt-get, pacman, etc, all require sudo to manipulate the package database.

This objection is to "curl piped to sudo [dpkg]" in general.

**Comment by dametenshi** [comment]
@oconnor663 & @maxtaco: Should this be closed as a duplicate of #2065 then?

**Comment by oconnor663** [comment]
I think so, though I'm glad you posted the link to that Twitter conversation.

To elaborate on what @cjb mentioned, the Tor instructions will fail if you're not root, they just don't say so clearly. This is a common problem with Linux documentation, which I've personally been yelled at for inflicting on people :)
