### ISSUE TITLE
https://keybase.pub is down

### ISSUE THREAD

**Issue by dametenshi** [keybase/keybase-issues#2067]
I'm getting nothing back from the server:

$ curl https://keybase.pub
$

**Comment by cjb** [comment]
Thanks for the report!

@malgorithms We're back up now.  There was a service panic.  I ran log send on the keybasepub machine for us to investigate it:  26bead8af873ab2f0272361c

**Comment by maxtaco** [comment]
Never seen a crasher here before, we'll take a look:

```
86214 [signal 0xb code=0x1 addr=0x0 pc=0x5ed89b]
86215
86216 goroutine 24013 [running]:
86217 github.com/keybase/client/go/libkb.(*WebChecker).CheckStatus(0xc822986e60, 0xc8277760a0, 0x42, 0xc82752dc40, 0x20, 0xc82752dba0, 0x20, 0xc82752dc00, 0x20, 0xc823c5b180, ...)
86218 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/proof_support_web.go:79 +0x4ab
86219 github.com/keybase/client/go/libkb.(*IdentityTable).proofRemoteCheck(0xc82789f200, 0x0, 0xc82572af80)
86220 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1284 +0xa02
86221 github.com/keybase/client/go/libkb.(*IdentityTable).identifyActiveProof(0xc82789f200, 0xc82572af80, 0xc82353a840, 0xc827cbde40, 0x0, 0x0, 0x7f1c101ca110, 0xc827879880, 0x7f1c0cb3b930, 0xc8261dfef0)
86222 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1183 +0x61
86223 github.com/keybase/client/go/libkb.(*IdentityTable).Identify.func1(0xc822f14320, 0xc82789f200, 0xc82353a840, 0xc827cbde40, 0x0, 0xc821285a00, 0x7f1c101ca110, 0xc827879880, 0x7f1c0cb3b930, 0xc8261dfef0, ...)
86224 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1168 +0xbb
86225 created by github.com/keybase/client/go/libkb.(*IdentityTable).Identify
86226 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1169 +0x15c
86227
```

**Comment by maxtaco** [comment]
Looks like an extra `:` got us in trouble.  Update to follow...

**Comment by maxtaco** [comment]
Should fix the issue, but it doesn't seem to common, so no big rush on the redeploy

**Comment by maxtaco** [comment]
(Thanks for the bug report @dametenshi!)

**Comment by dametenshi** [comment]
Aaaaand we're down again.

$ curl https://keybase.pub
$

**Comment by timmc** [comment]
I assume this is why I cannot read or write to /keybase directories? Or would that be a different issue?

**Comment by strib** [comment]
@timmc: different issue.  /keybase works fine for me.  Earlier, keybase.pub was crashing due to purely local issues.

Please open a new ticket (including a `keybase log send` ID) if you need help accessing the file system locally.

(And sorry, I don't have access to keybase.pub to get it up and running again -- I'm sure someone will take a look in the morning eastern time.)

**Comment by cjb** [comment]
(It's back now.)

**Comment by timmc** [comment]
Figured it out, doc problem actually.
