### ISSUE TITLE
`/keybase/public/<myname>` does not implicitly exist

### ISSUE THREAD

**Issue by timmc** [keybase/keybase-issues#2071]
According to the launch announcement and other KBFS docs, public or private directories implicitly exist and can simply be written to. For example, from the launch announcement:

> Anyway, if you have the new Keybase, go ahead, start a diary:
> 
> `cd /keybase/private/timmc`
> `echo 'The brain...it moved again.' > diary.txt`

On Debian 7 (Wheezy) I'm not finding that to be true. For example, even though `/keybase` exists, I cannot list my private dir contents:

```
$ ls /keybase/private/timmc
ls: cannot access /keybase/private/timmc: No such file or directory
```

If I first do `mkdir -p /keybase/private/timmc` then I can.

**Comment by malgorithms** [comment]
hey @timmc - that should've worked! hmm.  you don't need to mkdir, so there's a bug.

when hitting bugs can you run `keybase log send` which will package up your logs and also generate a link to post in our keybase/client issues (with the log id for the admins to access)?

**Comment by timmc** [comment]
Aha! OK, here's a log ID: d421f79901ad1646c87fa61c

This is on Debian 7 (Wheezy).

I'll change the topic and description to match.

**Comment by timmc** [comment]
Possibly related: I can write to the public folder, but nothing appears on keybase.pub.

```
timmc@curmudgeon:~$ mkdir -p /keybase/public/timmc
timmc@curmudgeon:~$ echo 'works locally' > /keybase/public/timmc/demo-keybase-issues-2071
timmc@curmudgeon:~$ cat /keybase/public/timmc/demo-keybase-issues-2071
works locally
# log send: 04d1f2c103056305ed870b1c
```

Separate ticket, or possibly related?

**Comment by cjb** [comment]
KBFS isn't running due to:
```
3 2016-02-13T00:12:44.606749 ▶ [DEBU main.go:93] 003 Mounting: /keybase
4 kbfsfuse error: (2) fusermount: fork/exec /bin/fusermount: permission denied
```

**Comment by cjb** [comment]
Does `sudo apt-get install fuse` help?

**Comment by cjb** [comment]
(and then `run_keybase`)

**Comment by timmc** [comment]
`fuse` is already installed at the latest version.

So you're saying that the mountpoint has been created, but no KBFS mounted over it. That... would explain a lot. :-)

Where can I look at these logs myself?

**Comment by maxtaco** [comment]
Maybe the mount point was created by a different user?

**Comment by cjb** [comment]
They're in `$HOME/.cache/keybase`.  That one was from `keybase.kbfs.log`.

Maybe your fusermount isn't SUID and it should be?  I don't know why that would happen.  Or what @maxtaco just said.

**Comment by timmc** [comment]
The mountpoint itself is owned by root and has 777 permissions:

```
timmc@curmudgeon:~$ ls -ld /keybase
drwxrwxrwx 3 root root 4096 Feb 13 08:57 /keybase
```

And here's my /etc/fuse.conf if it helps:

```
# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#
#mount_max = 1000

# Allow non-root users to specify the 'allow_other' or 'allow_root'
# mount options.
#
#user_allow_other
```

**Comment by strib** [comment]
What are the results of:

```
ls -l `which fusermount`
```
?

**Comment by timmc** [comment]
Not found, but then apparently I would need to be root or fuse to x it:

`-rwsr-xr-- 1 root fuse 30864 May 21  2015 /bin/fusermount`

**Comment by strib** [comment]
This is what mine looks like, on Ubuntu 14.04:

```
$ ls -l `which fusermount`
-rwsr-xr-x 1 root root 30800 May 15  2015 /bin/fusermount
```

So I guess you're missing the other executable bit.  It looks like Wheezy did things a bit different:

https://superuser.com/questions/466304/how-do-i-make-sshfs-work-in-debian-i-get-dev-fuse-permission-denied

Can you try running `sudo gpasswd -a $USER fuse`, re-run `run_keybase` and see if that works?

**Comment by strib** [comment]
Oh, and as per the link, you either have to log out and log back in again after you add yourself to the `fuse` link, or using `newgrp fuse` might work too.

**Comment by timmc** [comment]
(I can also check later on my Debian 8 (Jessie) machine; 8 is now stable, and 7 is oldstable, and I'm not sure what versions you're going to support for how long...)

**Comment by strib** [comment]
(You might also need to do `rm -rf /keybase/*` to clear out the stuff you made in there before it was mounted.)

**Comment by strib** [comment]
We don't have an official list of distros we're supporting.  We're just working with individuals for now trying to get it running in their environments.  Let us know if the above suggestion (adding yourself to the `fuse` group) fixes your wheezy issues.

**Comment by timmc** [comment]
Partial success!

- Needed to add myself to `fuse` group and logout/in again on Debian 7
- Debian 8's permissions on fusermount match the Ubuntu 14.04 sample above
- Had to clear out contents of mountpoint and re-run `run_keybase`
- `/keybase` now has expected contents:

```
timmc@curmudgeon:~$ ls -al /keybase
total 0
drwxr-xr-x 1 root root 0 Feb 13 15:12 private
drwxr-xr-x 1 root root 0 Feb 13 15:12 public
```

However, I can't list any implicit folders. (Log ID 1888fcb6afa71d3dcc62171c)

```
timmc@curmudgeon:~$ ls /keybase/public/chris
^Cls: cannot open directory /keybase/public/chris: Input/output error
```

I've seen other issues around that, so I'll poke around.

**Comment by cjb** [comment]
```
9 /opt/keybase/Keybase: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/keybase/Keybase)
```
Our GUI isn't working because of your older glibc.  We use the GUI to prompt you for your Keybase passphrase, which unlocks KBFS.  You can unlock it manually with `keybase unlock`, and KBFS will sort of work, but the GUI's an important component.

**Comment by timmc** [comment]
`keybase unlock` works! I consider this issue closed unless you want to keep it open for documentation work.

**Comment by cjb** [comment]
Cool.  Since the GUI won't be telling you this since it isn't running, if you ever see input/output errors cd'ing into directories, try `keybase track <thatuser>` on the command line and retry -- you have to have a good track of someone for KBFS sharing to work.

**Comment by strib** [comment]
Huzzah!  Please open a new issue if anything else trips you up.
