### ISSUE TITLE
How to rename my device 

### ISSUE THREAD

**Issue by xiashali** [keybase/keybase-issues#2075]
I input the wrong name of my laptop.But I can't find how to rename or remove the device.

**Comment by oconnor663** [comment]
By design, you can't rename an existing keybase device. But you can revoke that device by running `keybase deprovision` on it, and then you can provision it again with a new name using `keybase login`. (Note that you can't reuse the old name -- it will be occupied forever.)

**Comment by ekevoo** [comment]
What happens between other things that were authenticated using that device only?

**Comment by oconnor663** [comment]
Everything still works. Your signature chain remains as proof that your device was valid at the time it provisioned those other devices.

**Comment by tckb** [comment]
is it possible to remove traces of the name of the device? Would a reset or delete of the account help?
