### ISSUE TITLE
New Account Periodically Vanishes

### ISSUE THREAD

**Issue by thenaterhood** [keybase/keybase-issues#2077]
This seems to be like something that's a result of caching on some level.

I have a brand new account (made within the hour of my posting this) with a few verifications. Every so often when I try to load my profile, Keybase tells me that it can't find me. This happens whether or not I'm signed in. It keeps happening for a few minutes before it resolves itself and I can view my profile again.

**Comment by cjb** [comment]
Thanks for the report, would it be possible to post a screenshot of the page where Keybase is saying it can't find you?

**Comment by thenaterhood** [comment]
Sure! It's just the generic user not found page.

![keybase-not-found](https://cloud.githubusercontent.com/assets/2584772/13060199/bf499e22-d3fd-11e5-94e0-e7c48ba44188.png)

**Comment by cjb** [comment]
Huh! @maxtaco, want to check the web server logs for 404s on keybase.io/thenaterhood ?

**Comment by thenaterhood** [comment]
Scared me the first time, I hopped on to add a device and it couldn't find me! Kept getting the same for a minute or two over a couple tries then it worked again. Same thing happened again a few minutes later.

**Comment by thenaterhood** [comment]
Re-logging in while it couldn't find me was a bust as well.

**Comment by maxtaco** [comment]
Small downtime at that hour since I was cycling the databases!  I think that explains it.  Saw other people in the logs who had a 404 too....

**Comment by maxtaco** [comment]
Yeah, here's what the logs show at that time:

```
Feb 15 14:44:53 ws6 app.iced[27842]: RPC [I] localhost:37795 reconnecting (attempt 19)
Feb 15 14:44:53 ws6 app.iced[27842]: RPC [W] localhost:37795 Error: connect ECONNREFUSED 127.0.0.1:37795
Feb 15 14:44:53 ws6 app.iced[27842]: [I] - New guest session created w/ gid=1a9599d4537e0dc032b8904a04696208
Feb 15 14:44:53 ws6 app.iced[27842]: [E] - Error in User LOL: Error: DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [W] - set_error 205 DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [I] - New guest session created w/ gid=1b3d0d5d71378a6e5eb76bf102208d08
Feb 15 14:44:53 ws6 app.iced[27842]: [E] - Error in User LOL: Error: DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [W] - set_error 205 3ad8a02499ae93031f5d7b6c9f705800: user not found
Feb 15 14:44:53 ws6 app.iced[27842]: [I] - New guest session created w/ gid=4572a80a1698b8ee1ffc8545860efc08
Feb 15 14:44:53 ws6 app.iced[27842]: [E] - Error: DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [W] - Error: DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [E] - Error: DB error
Feb 15 14:44:53 ws6 app.iced[27842]: [I] - pub_some_peeps in 6
Feb 15 14:44:53 ws6 app.iced[27842]: [E] - Error: RPC error 505: Error: DB error
```
