### ISSUE TITLE
"Hardcore mode" key verification gives bad terminal command

### ISSUE THREAD

**Issue by pkirkovsky** [keybase/keybase-issues#2080]
The CLI command block provided by the manual key verification process seem to bomb on my machine. In the middle of the process I'm prompted with a pinentry dialog (I use a Yubikey for sig/enc subkeys + an offline master), which is followed by a bunch of bash errors.

![screen shot 2016-02-15 at 8 55 46 pm](https://cloud.githubusercontent.com/assets/8731045/13067707/32f41b02-d428-11e5-9920-b317c2521534.png)

![keybase-cli-error](https://cloud.githubusercontent.com/assets/8731045/13067709/39870c54-d428-11e5-93ea-ba27ba658831.png)

**Comment by oconnor663** [comment]
@pkirkovsky do you have a large public key, for example with an image in it? This could be the same issue as https://github.com/keybase/keybase-issues/issues/2026.

**Comment by pkirkovsky** [comment]
@oconnor663 I don't have an image in it. Not sure what constitutes a large key -- mine is ~19kb. Is that large enough to trigger the issue seen in #2026?

https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0x4328CFD67B46A8FB32270F4F0CE4A0B83F3FC81F

**Comment by oconnor663** [comment]
Ah I'm sorry, this is a totally different error. "No such file or directory" and "file name too long" look like quoting errors. I haven't seen those before. Any chance you only pasted part of the whole command into your terminal? Or maybe you're running `fish` or something with new and exciting syntax?

**Comment by pkirkovsky** [comment]
I've narrowed this down to an issue with large pastes (it's somewhat related to GPG key size) and iTerm2: https://gitlab.com/gnachman/iterm2/issues/3160
Setting paste speed at ~20kb/sec appears to be the most stable option:

![screen shot 2016-02-23 at 3 12 29 pm](https://cloud.githubusercontent.com/assets/8731045/13270088/90bb90c6-da40-11e5-9116-c600d9c6a38a.png)
![screen shot 2016-02-23 at 3 32 07 pm](https://cloud.githubusercontent.com/assets/8731045/13270539/bf9ea484-da43-11e5-81be-963e76c5e216.png)
![screen shot 2016-02-23 at 3 39 12 pm](https://cloud.githubusercontent.com/assets/8731045/13270546/cbc87172-da43-11e5-8bee-f5df82400a74.png)

(bash 4.3.42, iTerm2 2.9.20160206)

Using Terminal.app works without issue, since it pastes slowly by default.

**Comment by oconnor663** [comment]
What's the theory here? Is it bash that's mishandling the fast paste? I've never seen/heard of/conceived-of-in-all-my-life an issue related to paste speed, so I'm kind of at a loss here :|

**Comment by pkirkovsky** [comment]
>What's the theory here?

It has to do with the underlying tty system as well as how we're interacting with it:

> http://www.linusakesson.net/programming/tty/
**Line editing.** Most users make mistakes while typing, so a backspace key is often useful. This could of course be implemented by the applications themselves, but in accordance with the UNIX design philosophy, applications should be kept as simple as possible. So as a convenience, the operating system provides an editing buffer and some rudimentary editing commands (backspace, erase word, clear line, reprint), which are enabled by default inside the line discipline. Advanced applications may disable these features by putting the line discipline in raw mode instead of the default cooked (or canonical) mode. Most interactive applications (editors, mail user agents, shells, all programs relying on curses or readline) run in raw mode, and handle all the line editing commands themselves. The line discipline also contains options for character echoing and automatic conversion between carriage returns and linefeeds. Think of it as a primitive kernel-level sed(1), if you like.

See also: http://superuser.com/questions/219225/command-limits-when-pasting-into-tcsh-mac-os-x

There are ways of overcoming this issue (maybe including `stty raw` in the commnd, or recommending `pbpaste` for OS X users & `xsel`/`xclip` for Linux) but the easiest way here is to just dial down the paste speed :stuck_out_tongue:
