### ISSUE TITLE
ERROR Error installing KBFS: exit status 1

### ISSUE THREAD

**Issue by bdunbar** [keybase/keybase-issues#2081]
Signed up for keybase.
Setup profile.
Went through the key & identity proving process.
Installed app.
Applied for alpha for kbfs.
Accepted invitation.

➜  ~  keybase ctl stop
➜  ~  keybase ctl start
➜  ~  keybase install
▶ INFO Checking /usr/local/bin/keybase (/usr/local/opt/keybase/bin/keybase)
▶ INFO Checking service
▶ INFO Service: Installed (Action: None)
▶ INFO Checking KBFS
▶ INFO KBFS: Not Installed (Action: Install)
▶ INFO Installing KBFS
▶ ERROR Error installing KBFS: exit status 1
▶ INFO Installer for cli: OK
▶ INFO Installer for service: OK
▶ INFO Installer for kbfs: INSTALL_ERROR exit status 1
➜  ~ keybase version
Client:  1.0.6-0
Service: 1.0.6-0
➜  ~  uname -a
Darwin hilda.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Now what?  Restart laptop? Roll dice for a saving throw?

**Comment by gabriel** [comment]
This was fixed a little while ago, you can ignore that error...

I recommend upgrading your keybase client (currently we're at 1.0.12).
