### ISSUE TITLE
Unresolved dependency under xubuntu 15.10

### ISSUE THREAD

**Issue by snorerot13** [keybase/keybase-issues#2087]
$ curl -O https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb \
> && sudo dpkg -i keybase-latest-amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5479k  100 5479k    0     0  3606k      0  0:00:01  0:00:01 --:--:-- 3607k
Selecting previously unselected package keybase.
(Reading database ... 208129 files and directories currently installed.)
Preparing to unpack keybase-latest-amd64.deb ...
Unpacking keybase (1.0.13-0) ...
dpkg: dependency problems prevent configuration of keybase:
 keybase depends on libappindicator1; however:
  Package libappindicator1 is not installed.

dpkg: error processing package keybase (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 keybase

**Comment by oconnor663** [comment]
Ack, my fault, thanks for reporting. I added a dependency in our internal builds that shouldn't have made it into prod. For now you should be able to finish the install by running `sudo apt-get install -f`. I'll fix this in the next prod build.

**Comment by snorerot13** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 02/19/2016 08:26 AM, oconnor663 wrote:
> Ack, my fault, thanks for reporting. I added a dependency in our 
> internal builds that shouldn't have made it into prod. For now you 
> should be able to finish the install by running |sudo apt-get
> install -f|. I'll fix this in the next prod build.


That looks good.

Thanks for the quick reply!


- -- 
http://www.lunabase.org/~faber
http://www.lunabase.org/~faber/blog
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJWx0LpAAoJELKW6dHrttp3I98H/2GuTpnSESGEjq8rCUMMG5D8
3CjqD2ucfwL3ufbPESrM+KfuIduXE837tbFR3Oxze72bbnhDeQOvv23smi13xFUW
YegzCxCwdJ0w+hu+WTFhXYRhOKOIo5aMSOSPDfy/Aj3ZazDVtzjPVFFqIteiaRkR
dwsyB5pODvi4Cr2TMj3RmKFHoLE2AQlAsZRyrSX1ivdMK/Ap3Fsrg/gSitykP/Lv
3Reg1vUbguhzB1trOaSyuxP6o8xbtYztH/Rvk3UlXQR7n/srPpmUdLjgX46DCcSZ
BcNMOoicoRmt/kkv2r7W3f/UXwd4iZ/cEwK8ZSDXBtD90iUknIhLjxQfghJBUrI=
=ZTwV
-----END PGP SIGNATURE-----
