### ISSUE TITLE
Gist proof worked and then failed 41 minutes later

### ISSUE THREAD

**Issue by geofflee** [keybase/keybase-issues#2091]
Last night, I posted keybase.md as a public gist at: https://gist.github.com/geofflee

I initially got an email at 11:10pm PST saying "your github (@geofflee) proof just succeeded!", then followed by another email 41 minutes later saying "your github (@geofflee) proof just broke".

I tried deleting and re-posting the gist, but that hasn't helped.

I am using Windows, and copy/pasting the proof from the command line window introduces lots of newlines that I had to manually clean-up. It's possible that I'm missing a newline somewhere, but I don't see it. In order to avoid the newline problem, maybe it would be better to output the proof as a file instead?

It would also be helpful if the error message was more detailed. For example, instead of simply saying that the proof broke, it should indicate whether the file could not be found, the proof could not be parsed, the signature is wrong, or whatever other reason.

**Comment by sbriskin** [comment]
Try https://sourceforge.net/projects/conemu/ or https://sourceforge.net/projects/console/ - it's much better then cmd.exe when you need to copy and paste a lot of text

**Comment by zQueal** [comment]
Working with Windows as much as I do, the main reason I switched to [Cmder](http://cmder.net/) is to copy and paste al la Linux via CLI.

**Comment by geofflee** [comment]
I retried with PowerShell, and it worked.
