### ISSUE TITLE
Twitter validation failing (306)

### ISSUE THREAD

**Issue by RyanMcG** [keybase/keybase-issues#2096]
[The validation tweet.](https://twitter.com/Ryan_VM/status/701707566439501824)

Proof fails.

```sh
$ keybase id ryanmcg
✖ "ryan_vm" on twitter failed: No server-given hint for sig=5c55f966596365f81946209eda88a62599905174d9be571383d9a6e4f95e52cf0f (code=306)
```

My twitter handle is normally capitalized like *Ryan_VM*, I'm not sure if that can be it.

**Comment by maxtaco** [comment]
You left out "Verifying myself." Just post the tweet again but put in that
prefix.  Then ask the server to recheck on the website.

**Comment by RyanMcG** [comment]
That was it! I'm not sure how I missed part of the message the first two times. Oh well.
