### ISSUE TITLE
Encrypting messages with public keys not username

### ISSUE THREAD

**Issue by goatandsheep** [keybase/keybase-issues#2097]
Is there a way to encrypt a message that you're sending to someone who isn't a user of Keybase?

**Comment by dtiersch** [comment]
With public key cryptography this is not possible because you need to have the public key of the person you want to send the message to - and they need the according private key, so simply generating a key on the fly wouldn't solve this

**Comment by goatandsheep** [comment]
@dtiersch I never suggested generating a key on the fly. I have multiple contacts who I have the GPG public key of and they obviously have their private key. I was wondering if there is a way to encrypt a message using somebody's public key who is not a keybase user.

**Comment by RichJeanes** [comment]
From the Keybase website, no. But if you're talking about using the client to do so, then why not use a dedicated PGP client directly?

**Comment by goatandsheep** [comment]
@RichJeanes 

1. I don't want to have 2 public keys. 
2. I don't want to have so many different tools
3. If the client already does it, then why would I want a second client?

**Comment by RichJeanes** [comment]
1) You don't have to have two public keys. You can use the same key in Keybase and elsewhere. I'm using the same key with Keybase that I have been for a couple years.
Use `keybase pgp select` to select a keypair from your GPG keyring and use that as your PGP key for Keybase. The public half will be pushed to the server and associated with your account and the private half will be imported into your local Keybase keyring. Or if you want to generate a new key to start from scratch, `keybase pgp gen` will generate a new key for you, push the public half to Keybase and export it to your GPG keyring for use there as well.
2) I don't know if two counts as many...
3) Keybase isn't meant to replace your standard PGP client like GPG, rather to make it easier to verify someone's online identity and communicate with those people . GPG is already a very powerful PGP client itself and has different use cases from Keybase. Namely people that don't use Keybase and, ideally, have been either personally verified or verified via web of trust.
