### ISSUE TITLE
"Error in your post" response with blank fields when adding key via GPG + curl (Yubikey)

### ISSUE THREAD

**Issue by pkirkovsky** [keybase/keybase-issues#2098]
I'm trying to add my key using the GPG/curl method, but after submitting the curl request I get a GPG pinentry dialog (for the Yubikey PIN) followed by a blank error:

```
[...]
> sLHIaykfqLM4el+FglG7Jh+NN8Yg/TFy8+lKb7ajUBa8hRmzis7ftPADh1pQqgDD
> =4XiP
> -----END PGP PUBLIC KEY BLOCK-----
> " \
>   --data-urlencode is_primary="true" \
>   --data-urlencode sig_required="true" \
>   https://keybase.io/_/api/1.0/key/add.json
Error in your post
-------------------

Code:
Name:
Description:
```

I suspect this is related to currently unresolved issues #1598, #1822, and #1885. It would be helpful to provide a useful error message to "hardcore mode" users in the interim.

**Comment by maxtaco** [comment]
I will look into it but no guarantees I can get to it right away.

**Comment by maxtaco** [comment]
I think it's fixed, give it a whirl?

**Comment by pkirkovsky** [comment]
Nope, same error.

**Comment by maxtaco** [comment]
The same error, meaning an empty error output?  or does the error output show?  If you could, can you send me the full post so I can repro the issue?  You can use PGP or saltpack. It's all public with the exception of your session cookie, which the site operators know anyways. Thanks

**Comment by pkirkovsky** [comment]
Yes, I got the same exact "Error in your post" response as seen in my first post. Another point of interest: I repeated the curl command about 5-6 times before before the website told me it timed out, and on one of the tries got a "Success!" message. All other attempts failed with that same blank error message.

Did you want me to post the entire command & output here or in an email?

**Comment by maxtaco** [comment]
An email is better, so you don't leak your session cookie. Thank you!

**Comment by maxtaco** [comment]
max@keybase.io ...

**Comment by pkirkovsky** [comment]
Email sent.
I tried it again a couple of times and managed to get a "Success!" message again...

**Comment by maxtaco** [comment]
Gah, my bad.  I forgot to push my code live.  Should be live now.  The error, I'm guessing from the server logs, would say that there's a bad input, error 'Bad base64 string'.  Meaning it could be the post was truncated and the base64 body of the key or sig wasn't 4-byte aligned.

**Comment by pkirkovsky** [comment]
Great, it looks like errors are showing up now! I sent some intentionally malformed API requests and got these back:

```
Error in your post
-------------------

Code: 1002
Name: SIG_CANNOT_VERIFY
Description: bad signature: Wrong previous hash; wanted 'xxx' but got 'yyy'
```

```
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string
```

Thanks for looking into this, Max.

**Comment by maxtaco** [comment]
No worries, thanks for your bug report. We previously showed the first error type but weren't properly showing the error type in the second case, since it goes through a different code path (input parameter checking) that never even got to the `key/add.json` handler.

**Comment by scott-wilson** [comment]
I just tried to verify my private key, and I'm getting the same error as the OP. (Not sure if this'll help, but I'm on CentOS 7, 64 bit)

```
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string
```

**Comment by maxtaco** [comment]
try to debug it  a bit, maybe by seeing what the intermediate values are

**Comment by scott-wilson** [comment]
If I manually resolve the input for curl `--data-urlencode sig=`, then I get the following error:

```
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: missing or invalid input
```

Thanks for the help so far! Also, should I move this to a new ticket, or send it through email since there may be session info?

**Comment by scott-wilson** [comment]
I have managed to make this work on my Ubuntu machine, so I'm going to consider this closed for me.

**Comment by john-n-smith** [comment]
Signing a public key using the generated command line script (command line with [bash + GPG + cURL] option on keybase) fails on OS X (Mojave 10.14.4) with the `bad base 64 string` error. The same generated script succeeds on Linux.

**Comment by heronhaye** [comment]
@john-n-smith Are you using bash? What is your `gpg --version`?

**Comment by john-n-smith** [comment]
Yes, I'm using bash. `gpg --version` reports `gpg (GnuPG/MacGPG2) 2.2.10`.

**Comment by heronhaye** [comment]
Do you see any errors from gpg? Could you run and post the `echo '...' | gpg -u ... -a --sign` part?

**Comment by john-n-smith** [comment]
That part of the command succeeds:

**Comment by heronhaye** [comment]
Could you post the entire command it generates for you?

**Comment by heronhaye** [comment]
A workaround (as long as your public key isn't very very large) is to replace the "@-" in the generated script with the public key block at the end. So something like

```
curl \
  --data-urlencode sig="$(\
   echo '...' | \
   gpg -u '....' -a --sign)" \
  --data-urlencode type="eldest" \
  --data-urlencode csrf_token="...." \
  --data-urlencode plain_out="1" \
  --data-urlencode session="...." \
  --data-urlencode signing_kid="..." \
  --data-urlencode public_key="---BEGIN PGP PUBLIC KEY ...." \
  --data-urlencode is_primary="true" \
  --data-urlencode sig_required="true" \
  https://keybase.io/_/api/1.0/key/add.json
```
