### ISSUE TITLE
Firefox does not offer to save credentials

### ISSUE THREAD

**Issue by lucb1e** [keybase/keybase-issues#21]
Because the username and password fields have no name attribute, Firefox is not able to save them for the website. I tried to work around this by storing the username and password combination on a localhost mock-up page and then editing the hostname in ~/.mozilla/firefox/profile/signons.sqlite, but this didn't work. Firefox really seems to want name attributes, using the id does not work.

I don't want to use an external password manager and use Firefox' with a strong master password. Not being able to use the password storing feature actually caused me to forget saving the newly generated password, which is why I needed that password reset feature already (referring to issue #16).

There is also an autocomplete=off attribute on the username field, which is highly annoying and does not provide any security since it's public, searchable information that can usually be found locally in the browser history. There is no reason to turn this useful feature off.

**Comment by coyotebush** [comment]
Firefox isn't offering to save my passphrase. (Except when I call `document.forms[0].submit`, which also causes the passphrase to be submitted directly to the server...)

**Comment by pkirkovsky** [comment]
@malgorithms Still an issue, at least in FF and Chrome. See #1591
