### ISSUE TITLE
Unable to login to keybase on Mac OS X after upgrade from 0.8.23 to 1.0.13

### ISSUE THREAD

**Issue by nigelm** [keybase/keybase-issues#2101]
I have had a keybase account/install for a while but not made any real use, so left it to fester...

Today having realised that the docs on keybase do not reflect the version I am running I upgraded - directly from 0.8.23 (so no devices etc within that) to 1.0.13.  The system was working prior to the upgrade (I logged in and proved my github account).  Subsequent to the upgrade I cannot login with symptoms very similar to issue #1984 :-

```
$ keybase --version
keybase version 1.0.13-0

$ keybase login
... [go for GPG option - but keybase key is similar]
▶ NOTICE Failed to parse public key at position 0
▶ ERROR Bad key family: No key found for 0111f96e37689a34b1fedbcd417fe0b6ba86a506bccc15f81ca3daf9826d85314f120a

```

Have attached the output of `keybase -d login`

[keybase_login.txt](https://github.com/keybase/keybase-issues/files/144755/keybase_login.txt)

This looks similar to the issue #1984 but I am running the version that apparently fixes that issue.

I have tried removing old config from the previous version of the keybase client, uninstaling and reinstalling, ensuring that the launchd items are set up appropriately, and the laptop has been rebooted so any old versions are definitely no longer in the way.

**Comment by maxtaco** [comment]
You have found yet another short-coming in the Go OpenPGP library.  You have included a primary key packet twice in your PGP public key, and our server-side javascript can handle it, but the Go library is interpreting it as two keys.

Probably the right solution is to fix the OpenPGP library, but for the short-term, can you reexport your primary key from GPG, update it via the Website, and then try again?

**Comment by nigelm** [comment]
Going nuclear on the website using the "Reset the keys and start from scratch" option sort of worked...

However since that was an ancient gpg key which was too short for current use, had too much history (attached addresses for a company that rebranded) etc, I went for the nuclear option on that too - revoked it and have started a new key.
