### ISSUE TITLE
Proposal: Docs improvements about what to save

### ISSUE THREAD

**Issue by PierreZ** [keybase/keybase-issues#2103]
Hi, 

I'm currently looking to format my unique desktop device. I have two Paper keys, and I didn't find any information about what I need to save, and more generally, what I need to do before completely wipe my hard drive. Should I:

* revoke my device before?
* simply login with my paper key and then revoke it?
* etc... 

Could you please add more informations about this process on the documentation?

**Comment by dtiersch** [comment]
Your device key is in `~/.config/keybase` so you should carry that over if you don't want to revoke and create a new device.

The folder `~/.cache/keybase` should be save to remove. What`s in there could be recreated (although nuking this should require a re-login). And there is also `~/.local/share/keybase` which has a database in it but I don't know if it is safe to delete it. (Maybe one of the devs could clarify this?)

The safe bet would be to back up both `~/.config/keybase` and `~/.local/share/keybase`.

The paper keys don't need additional backup if you have the phrases written down somewhere; they are not references to some keys, the are the keys.

**Comment by maxtaco** [comment]
:+1: 

As for `.local/share/keybase`, that's where you keep a LevelDB that caches the sigchains of your contacts, and also states of the sitewide Merkle tree.  It's used to speed-up operations and also to catch the server if it ever tries to roll back state.  It's safe to delete this if you're switching machines but we don't recommend you do so during ordinary operation.

@dtiersch is right on the money.  The most important file is your `.config/keybase/secretkeys.<you>.mpack` file, which holds your secret device-specific keys.  There is no way to get back that information once it's gone.  `.config/keybase/config.json` is possible to recreate, but we don't currently have the tooling to do so; I would also make sure you back it up.

Thanks!

**Comment by PierreZ** [comment]
Cool thanks for all the informations!
