### ISSUE TITLE
Proof fails with signature not found in body error

### ISSUE THREAD

**Issue by yous** [keybase/keybase-issues#2114]
Hi, I recently updated to latest keybase client, `keybase version 1.0.14-0` on Arch Linux. I logged in and ran `keybase id yous`, but I got following results:

```
▶ INFO Identifying yous
✔ public key fingerprint: 1BF1 AFE8 682E 45A2 11FF 2C0E 891B 7A9E 1D5A 400A
✔ "yous" on github: https://gist.github.com/149b0775d2ff02eac323 [cached 2016-03-03 11:29:29 KST]
✔ admin of yous.be via HTTPS: https://yous.be/keybase.txt [cached 2016-03-03 12:18:49 KST]
✖ Proof for yous.be failed: signature not found in body (code=205)
```

I don't understand what's the problem since I can't find anything erroneous, and this problem still occurs even if I refresh my HTTPS proof.

Thanks in advance.

**Comment by maxtaco** [comment]
Did you also try a proof via DNS? That one could be falling.

**Comment by yous** [comment]
I just tried a proof via DNS and it succeeded. But `keybase id yous` still prints an error:

```
▶ INFO Identifying yous
✔ public key fingerprint: 1BF1 AFE8 682E 45A2 11FF 2C0E 891B 7A9E 1D5A 400A
✔ admin of DNS zone yous.be: found TXT entry keybase-site-verification=Kcjx2Bw2SR48ENyUw3VfpTLgyzaF_yFDWEn5pfWBsys
✔ "yous" on github: https://gist.github.com/149b0775d2ff02eac323
✖ Proof for yous.be failed: signature not found in body (code=205)
✔ admin of yous.be via HTTPS: https://yous.be/keybase.txt
```

**Comment by maxtaco** [comment]
Our bug, we'll fix it. Thanks!

**Comment by yous** [comment]
Thanks for handling this!

**Comment by maxtaco** [comment]
BTW, it's [this signature](https://keybase.io/_/api/1.0/sig/get.json?sig_id=c0c98d0a56fbcd2d6596cdf7d58326eb788f78fd41ba24beeba977f86a03c1250f) that's failing; it's not revoked, and it's a proof of http://yous.be via HTTP.  I guess it's an open question if the client should ignore that HTTP proof since you have an HTTPS proof as well.  But it could be the easiest thing is to just:

```
keybase sigs revoke c0c98d0a56fbcd2d6596cdf7d58326eb788f78fd41ba24beeba977f86a03c1250f
```

**Comment by yous** [comment]
Now `keybase id yous` doesn't print an error. Thank you for the notice. Closing.

**Comment by kyrias** [comment]
Any way you could make this simpler to debug?..
