### ISSUE TITLE
Cannot update prerelease via apt

### ISSUE THREAD

**Issue by timmc** [keybase/keybase-issues#2116]
I installed the prerelease, but I cannot get updates via apt like I can the normal version:

```
Error message:
Failed to fetch http://s3.amazonaws.com/prerelease.keybase.io/deb/pool/main/k/keybase/keybase_1.0.14-20160302170044+fa02591_amd64.deb 404  Not Found
```

This is on Debian 7 (wheezy).

**Comment by cjb** [comment]
Huh, works here on Ubuntu:
```
 λ sudo apt-get install keybase
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  keybase
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 41.5 MB of archives.
After this operation, 182 MB of additional disk space will be used.
Get:1 http://s3.amazonaws.com/prerelease.keybase.io/deb/ stable/main keybase amd64 1.0.14-20160302170044+fa02591 [41.5 MB]
Fetched 41.5 MB in 2s (17.4 MB/s)  
Selecting previously unselected package keybase.
(Reading database ... 328865 files and directories currently installed.)
Preparing to unpack .../keybase_1.0.14-20160302170044+fa02591_amd64.deb ...
Unpacking keybase (1.0.14-20160302170044+fa02591) ...
```

**Comment by cjb** [comment]
Is your apt-get not urlencoding the `+` to a `%2B`?

This URL works:

http://s3.amazonaws.com/prerelease.keybase.io/deb/pool/main/k/keybase/keybase_1.0.14-20160302170044%2Bfa02591_amd64.deb

**Comment by cjb** [comment]
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1003633

**Comment by timmc** [comment]
Aw jeez, that's terrible. S3, what are you doing...

**Comment by oconnor663** [comment]
Is is possible Debian 8 fixed this? I wasn't able to repro it there.

**Comment by cjb** [comment]
Yes, the launchpad link above shows it was fixed in apt in 2013.

**Comment by oconnor663** [comment]
I just landed a hack to fix this, which should go out with tomorrow's daily build. @timmc could you try it tomorrow afternoon and let us know how it goes?

(If you want to test by hand *right this very second*, you can repoint `/etc/apt/sources.list.d/keybase` to https://s3.amazonaws.com/jack-testing.keybase.io/index.html instead of https://s3.amazonaws.com/prerelease.keybase.io/index.html.)

**Comment by oconnor663** [comment]
Scratch that: I'm going to publish a manual build right now, so that we avoid running into any problems over the weekend.

**Comment by oconnor663** [comment]
Ok, the new build is out, and it seems to work for me on Debian 7. @timmc can you confirm?

**Comment by timmc** [comment]
Yup, that works!

(And I'll get around to upgrading to Debian 8 one of these days...)

**Comment by oconnor663** [comment]
Woo!
