### ISSUE TITLE
Twitter won't verify: what's wrong?

### ISSUE THREAD

**Issue by daveewart** [keybase/keybase-issues#2133]
After using 'keybase prove twitter' I copy/pasted & tweeted the resulting output as https://twitter.com/DaveEwart/status/709809946976722944

This continually fails to verify.  This is my second attempt after the first attempt continually failed similarly.  I got an email stating "[The tweet] is either (a) not there, or (b) not posted precisely".  It's definitely there, it's public and as far as I can see it is posted precisely.

Is there anything obviously wrong with what I've tweeted?

Thanks :-)

**Comment by maxtaco** [comment]
You left out "verifying myself"

**Comment by daveewart** [comment]
Ah, I see.  For some reason I didn't think that was part of the tweet. I stand corrected and have now successfully verified.  Thanks @maxtaco :-)
