### ISSUE TITLE
Annoying popup: /keybase/Keybase.app is not a Keybase folder

### ISSUE THREAD

**Issue by golddranks** [keybase/keybase-issues#2134]
<img width="364" alt="2016-03-16 21 54 16" src="https://cloud.githubusercontent.com/assets/2675542/13812856/c19f9e02-ebc1-11e5-8280-003eab7e90dd.png">

A popup like this shows up fairly often.

**Comment by cjb** [comment]
I think this should be fixed in five hours (that's when the build containing the fix will roll out).. please try running `keybase update check` then.
