### ISSUE TITLE
reddit Verification Link not working

### ISSUE THREAD

**Issue by NaEaP** [keybase/keybase-issues#2138]
I'm always getting a 502 Bad Gateway using the provided link

Could you also give me the option to copy-paste the message to reddit?

**Comment by maxtaco** [comment]
are you logged in?

**Comment by NaEaP** [comment]
Ah... stupid me
Yes, you're right.

Thank you very much!

**Comment by maxtaco** [comment]
on our part, the error message and flow could use work though....
