### ISSUE TITLE
I keep hitting refresh images to get my profile avatar updated but no results

### ISSUE THREAD

**Issue by master412160** [keybase/keybase-issues#2141]
I have verified my github and twitter acc in the browser and hit the "Refresh my photo" and nothing happens.

**Comment by malgorithms** [comment]
I'm doing an across-the-board resize of images of the site right now so shit is slow on that front. I think yours is updated on your profile now? if not it will be shortly.

**Comment by master412160** [comment]
Yeah, it shows up now.
