### ISSUE TITLE
Getting started from the command line

### ISSUE THREAD

**Issue by levidurfee** [keybase/keybase-issues#2142]
When I try this command:

```bash
keybase encrypt levidurfee -m 'a secret'
```

![image](https://cloud.githubusercontent.com/assets/10798199/13895169/880feabc-ed46-11e5-8a28-90e4045f5483.png)

**Comment by maxtaco** [comment]
Try double rather than single quotation marks.

**Comment by levidurfee** [comment]
Thanks, that worked. It might need updated on the website.

![image](https://cloud.githubusercontent.com/assets/10798199/13895224/2fd939ec-ed47-11e5-89da-d604bd1d8a4d.png)

**Comment by maxtaco** [comment]
cc: @malgorithms, I'll fix this one!

**Comment by levidurfee** [comment]
https://keybase.io/docs/command_line

This page needs some double quote love.
