### ISSUE TITLE
HTTPS Proof failed on client but not website

### ISSUE THREAD

**Issue by virtualdxs** [keybase/keybase-issues#2146]
When IDing myself, for my website I get:

    Proof for k7dxs.xyz failed: No server-given hint for sig=2f7185072ad69a460d6aba7f62cff14fb632c3ba33c21fa897f286ba62e0d9d10f (code=306)

But on the site it says it's fine. What's going on?

**Comment by maxtaco** [comment]
It's an arguable bug in the client, but I think you can solve it by revoking that defunct proof:

```
keybase sigs revoke 2f7185072ad69a460d6aba7f62cff14fb632c3ba33c21fa897f286ba62e0d9d10f
```

**Comment by virtualdxs** [comment]
That fixed it. Thanks! Closing this issue.


Duncan X. Simpson
Amateur Radio callsign: K7DXS
Visit my site at http://www.virtualdxs.tk/

Removal of this tagline is a violation of Federal Law.
