### ISSUE TITLE
username.keybase.pub no longer defaults to serving over https 

### ISSUE THREAD

**Issue by peterood** [keybase/keybase-issues#2147]
As of March 20, 02:50 EDT peterood.keybase.pub no longer defaults to serving over https which I believe was previously the case.

**Comment by zQueal** [comment]
Every other profile I try, including my own, defaults to HTTPS. When I initially tried yours, I saw that it was no longer loading on HTTPS by default--however now when I try, it does but only in Chrome. If I try in IE/Opera, the issue is as stated.

Very peculiar situation if you ask me.

**Comment by maxtaco** [comment]
Can't repro!

**Comment by peterood** [comment]
Yeah, definitely peculiar. When I filed the issue, I noticed it on my iPhone using Brave and Safari.

Right now I'm using OS X and tried [zqueal.keybase.pub](http://zqueal.keybase.pub) and [peterood.keybase.pub](http://peterood.keybase.pub).
**defaults to https**
Chrome Canary

**does not default**
Firefox Developer Edition
Safari

**Comment by cjb** [comment]
Hi folks, I think I've just fixed this, please could you retest?  We weren't enforcing a redirect to https on subdomains.  (

I'd guess the cross-browser differences are just that some browsers, when given 'foo.com', will try HTTPS and fall back to HTTP, and some will do it the other way around.

**Comment by peterood** [comment]
Thanks for the fix, Chris. I retested peterood.keybase.pub and zqueal.keybase.pub in Brave and Safari on iOS and both now redirect to HTTPS.
