### ISSUE TITLE
Unable to login on Ubuntu 16.04, keybase 1.0.14-1

### ISSUE THREAD

**Issue by jcassee** [keybase/keybase-issues#2151]
Having bought a new laptop I am trying to install keybase on it. Unfortunately, `keybase login` fails with the same message as issues #2000, #1984 and #2101. Those are closed, so I am opening a new issue.

This is the command:

```
$ keybase -d login 2>keybase-login.out
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 3
Your keybase username or email address: joost@cassee.net
```

The content of `keybase-login.out` is here: https://pastebin.com/9N7G6WT8

Can I do anything else to help debug the problem?

**Comment by maxtaco** [comment]
We are barfing on your PGP key.  I believe we fixed this pgp shortcoming of
the go pgp library in master but it isn't live yet on our main channel.

**Comment by jcassee** [comment]
Okay, good to know. Is there something like a beta channel I can use to get the fix?

**Comment by maxtaco** [comment]
Confirmed that I can `keybase id` you with the new client.  Decrypt the following for info on how to grab it:

```
-----BEGIN PGP MESSAGE----- 
Comment: GPGTools - https://gpgtools.org

hQEMA4YxvkHvJ+1fAQf+IlIvXNIINaDuNBzcJxvrIiAcaz8SuSFFMwReoU1WFI/+
ORiSB+appmgHXd3dBSPHU2snOnn+7mLcVjqOtah1rr1mWl/8DkSiCUJFegKM9aHX
9FHZU9wauVoYK4D/w2LK2ylJ28k2kw0UaaecvITHpX2Y4BG24oGpOw3FMn5Xi2QE
rSQabxHvIxYP7nuounCtubU8/tU/0XilGxodLcWP3K8LgA+HBMXrqcW4jctvhLAJ
6pytALBKpSca64X69kvPlVPB5FybkYXeHJumlRHsFI1MNwppaDsKdVuS5yGW+FvP
tGWgJf3wmFPqa5s2cK1/HomVuW5YY6kldBXqCALRb9KPAT/8T2dChAr7bqGlgaoC
LjOBagTlJlwYp4D57n0958REQjhFzLcXgUWIPQIEYmRQRtQIahmCDYHxMO4xReyD
B15X1YrnKRRipTc0sUFEG7rKxjvI0ZPBNFvnslHPEdfNSTV0joDZgQ/OTKJd+IWF
3gYTn7bPT50BmG2tsKGsDa4sXR5TpjgILpJwUuytgjE=
=Pp8F
-----END PGP MESSAGE-----
```

**Comment by jcassee** [comment]
Cool! Thanks, Maxwell.

**Comment by jcassee** [comment]
@maxtaco Shall I close this issue or leave it open for others to stumble across if they have the same problem?

**Comment by maxtaco** [comment]
i'd say close it, thanks...

**Comment by jcassee** [comment]
Alright, thanks Maxwell!
