### ISSUE TITLE
"Direct encrypt button" on the user profile page disappeared

### ISSUE THREAD

**Issue by lynt-smitka** [keybase/keybase-issues#2154]
There was a very useful button "Encrypt" on the user profile, but it was removed with the last redesign.

It provided easy way to encrypt messages from users who aren't keen on PGP and want to send encrypted message to keybase users.

The current procedure is much more difficult:
- click on the micro icon in header
- search user by his username
- encrypt

**Comment by oconnor663** [comment]
I still see this "PGP Encrypt" button. Are you referring to something different?

![image](https://cloud.githubusercontent.com/assets/860932/13999725/fd353cfe-f113-11e5-9d7b-8e9c23a8aa38.png)

**Comment by lynt-smitka** [comment]
My view (Chrome 49 on Windows 7):
![Profile without Encrypt button](https://dl.dropboxusercontent.com/s/zo2x3fzjvxfjh0x/2016-03-23%2021_31_13-Vladim%C3%ADr%20Smitka%20%28smitka%29%20_%20Keybase.png?dl=0)

**Comment by lynt-smitka** [comment]
Ok, "PGP encrypt" button is displayed only for logged in users.

**Comment by oconnor663** [comment]
Yes, though that might still be a regression. Thanks for the report. I'll ask the designers :)
