### ISSUE TITLE
keybase logout should also forget username

### ISSUE THREAD

**Issue by aaronorosen** [keybase/keybase-issues#2158]
If you run:

$ keybase logout 
then 
$ keybase login 

it asks you to put in the passphrase for the previous account they you were logged in with. How do you get it to forget the user that it used to login with?

**Comment by strib** [comment]
If you just want to log in as another user, you can do `keybase login <otherusername>`.  But if you literally want all local data about the other user to be erased, I don't think we have any easy solution for that yet -- right now you'd need to clear out some stuff from disk manually.

**Comment by aaronorosen** [comment]
ah okay that's what i wanted to do. Thanks!

**Comment by maxtaco** [comment]
Is `keybase deprovision` what you want?

**Comment by maxtaco** [comment]
cc: @oconnor663

**Comment by oconnor663** [comment]
It should be. We don't advertise the `deprovision` command too prominently, because it *really* removes all your local account state, including deleting secret keys.

**Comment by aaronorosen** [comment]
I didn't realize the client supported multiple accounts at once. That's awesome :+1:
