### ISSUE TITLE
Where does the public key in a http verify come from?

### ISSUE THREAD

**Issue by Tahvohck** [keybase/keybase-issues#2162]
I have a verification for kaeva.info here: http://kaeva.info/.well-known/keybase.txt
Where did the public key used in this come from? I have a public key with the fingerprint `08BF A8FC CCBB C09E 1192  9FA9 6AC4 28A5 EE2C 5FDD`. I do not, to my knowledge, have a key fingerprint of `ASA13t02GQ4AmLPIDwXcdHLHN5E1t_m_35DF1n8VK8wYYQo`, I've never seen a key identified that way. If this is a conversion from my actual key then I think it should be dropped: if I want to verify the signature and don't know whose key it is I have no way to check but to go through keybase. If it is gotten from my public PGP key, then I think this should at least be made clear in the verification document somehow.

**Comment by malgorithms** [comment]
This should explain it, I think:

https://keybase.io/tahvohck/sigchain#a1a05f3839713b104a17a6f64b381e582ac5000f10198cb43b992088bc99227a0f

If you're looking for more info on how this works, this could be a helpful post from a few months ago:

https://keybase.io/blog/keybase-new-key-model

**Comment by malgorithms** [comment]
a link to the specific sig:

https://keybase.io/tahvohck/sigchain#1a022076af6fb3c658fdf320af8cf80cd77082b229216ae7cc9d4808114782810f

**Comment by Tahvohck** [comment]
That does make a little more sense now. So it was signed with the kserver device key, which was authenticated with my PGP key, correct?

**Comment by malgorithms** [comment]
yeah, your PGP key signed kserver (and kserver accepted by countersigning; both in https://keybase.io/tahvohck/sigchain#4d87b0758c285cf48eca286c725c66e108f848c7a4d66abe1bbc221986b90ae80f ) 

then kserver did the domain proof.

you've since removed kserver, but it did the proof before it was subsequently revoked. logically that's still valid since the key that revoked it can also remove the domain proof if it wants.

**Comment by Tahvohck** [comment]
How would the revoking key remove the domain proof, exactly? I assume I could remove the file itself, but that wouldn't be the key revoking it.

**Comment by cjb** [comment]
On the command line, `keybase sigs list; keybase sigs revoke`.

**Comment by Tahvohck** [comment]
Gotcha. Well, that answers everything I needed to know about this, closing it before it scope creeps further.
