### ISSUE TITLE
Revoked BTC address not shown as revoked in chain

### ISSUE THREAD

**Issue by libeclipse** [keybase/keybase-issues#2164]
https://keybase.io/eclipse/sigchain#fb0464afe68c78ca5845ebea8d6326c03f65cdb762b6e1b704729601ed3633090f

26 says that 13 is revoked, but 13 isn't shown as revoked on that same page.

**Comment by oconnor663** [comment]
Nice catch. This should be a quick fix. Taking a look...

**Comment by oconnor663** [comment]
This should be fixed now. Please let me know if you see any cases I missed.
