### ISSUE TITLE
keybase encrypt large file memory usage

### ISSUE THREAD

**Issue by travcunn** [keybase/keybase-issues#2167]
I am using keybase to backup my home directory. After about 50 GB has been written to the disk, I notice keybase is using about 4.5 GB of memory. How can I encrypt large files without running into memory problems?

Here is the command I use:
```tar -zcvf - /home/travis | xz -8 | keybase encrypt travcunn > backup.bak```

**Comment by maxtaco** [comment]
Well at least it is less than 50Gb!

We should look into this.

Thanks for the bug report.

Cc: @oconnor663

**Comment by patrickxb** [comment]
@travcunn You probably want to output binary instead of armored: `keybase encrypt -b travcunn ...`

**Comment by travcunn** [comment]
@patrickxb Thanks for the tip

**Comment by zQueal** [comment]
Just an observation; is there any advantage for you to encrypt this way?

I don't really want to speak for the developers here (nor do I), but Keybase really isn't (or shouldn't) be used for anything this big (IMO). IMO if you need to encrypt something this large, especially in your home folder, you should probably be using drive encryption instead.

**Comment by travcunn** [comment]
Although it might not be the best way to backup my home directory, I don't think it's unreasonable to expect a PGP encryption tool to accept large files.

**Comment by maxtaco** [comment]
Public key is quite useful for unattended backups when the private keys
aren't available. This is a good use of saltpack in our opinion.

**Comment by patrickxb** [comment]
Fixed in https://github.com/keybase/client/pull/2837
