### ISSUE TITLE
Available to cancel account?

### ISSUE THREAD

**Issue by TommyJerryMairo** [keybase/keybase-issues#2171]
After registration I found that I make it a wrong username. So is it available for user to cancel a new account and register again with the username he wanted?

**Comment by malgorithms** [comment]
yeah, delete the account. use this invite code: `flock asthma rule stay` (posting this publicly...so act fast :-) )

**Comment by TommyJerryMairo** [comment]
@malgorithms  Excuse me, but how to use that code? Type it in address filed?

**Comment by malgorithms** [comment]
well, it depends on whether you're signing up from the website or the keybase client. but both ask you for an "invitation code". you probably didn't see it the first time you joined, if you came by clicking an invitation link which prefilled it for you.

Click "already have a code" here:

![image](https://cloud.githubusercontent.com/assets/614943/14208576/23716b64-f7ee-11e5-9673-d2a84c77e916.png)

Then put it in the first field:

![image](https://cloud.githubusercontent.com/assets/614943/14208593/35fc0e10-f7ee-11e5-8966-bdf7a3e851b5.png)

**Comment by TommyJerryMairo** [comment]
I register it by a invite link.
https://keybase.io/_/accept/obey_gun_scheme_whip What can I do next?

2016-04-01 21:43 GMT+08:00 Chris Coyne <notifications@github.com>:

**Comment by TommyJerryMairo** [comment]
And I have to complain that the system do not tell me the max length of the
username. And then automatically cut some letters off in the end.

2016-04-01 21:46 GMT+08:00 Tommy Mairo <tommy.mairo@gmail.com>:

**Comment by TommyJerryMairo** [comment]
@malgorithms

**Comment by TommyJerryMairo** [comment]
Okay, I have found Delete me on the website, thank you for your helping XD

2016-04-01 21:51 GMT+08:00 Tommy Mairo <tommy.mairo@gmail.com>:
