### ISSUE TITLE
My web proof has started failing

### ISSUE THREAD

**Issue by mitar** [keybase/keybase-issues#2173]
For some reason, two days ago my web proof has started failing:

http://mitar.tnode.com/keybase.txt

The file is still available. And it still looks like it contains the file. But it is internally HTML. I am not sure if now keybase started being more strict, or did Tumblr started adding this HTML tags around?

**Comment by maxtaco** [comment]
Tumblr had a bug where they were sending back valid HTML With HTTP Code 404.  I thought it was fixed yesterday, can you try it again?

**Comment by maxtaco** [comment]
(I.e., push the "retry" button on the Web UI)

**Comment by mitar** [comment]
I just now retried. It failed again.

Is it maybe because I also clicked to regenerate the proof, but then did not upload the new proof but I am keeping the old one?

**Comment by maxtaco** [comment]
yes, that is what happened.  if you generated a new proof, our scraper is looking for the new proof (and not the old...)

**Comment by mitar** [comment]
But the old proof is still valid or was it revoked? I mean, conceptually, in the merkle tree, did I also submit a revocation of the old one when I generated a new proof?

**Comment by maxtaco** [comment]
You did both with the same sig, as shown, somewhat buggily, [here](https://keybase.io/mitar/sigchain#d3192b0a6c213f5227024010e89cedb869384d2df7d01f44b5d5b08ae4f1b7610f)

**Comment by mitar** [comment]
Fixed. Thanks.

**Comment by mitar** [comment]
But isn't this a problem? Then somebody who compromises my web account, but not my PGP key, could trick your web interface to show that all my proofs are invalid by invoking new proof generation for all of them?

**Comment by maxtaco** [comment]
An attacker needs your private key to make a new signature and claim a new web site or revoke an old one. The retry button just asks our scraper to try something again if it has otherwise given up.  

I am not sure I follow your question

**Comment by mitar** [comment]
But, after my old signature was back up, it didn't see it anymore as valid.

**Comment by maxtaco** [comment]
But you provably revoked those old signatures, as signed with your private key.  It's shown [here](https://keybase.io/mitar/sigchain#d3192b0a6c213f5227024010e89cedb869384d2df7d01f44b5d5b08ae4f1b7610f)

**Comment by mitar** [comment]
Hm, you are probably right. OK.
