### ISSUE TITLE
No instructions for running kbfs

### ISSUE THREAD

**Issue by reem** [keybase/keybase-issues#2177]
I am unable to get kbfs running and can't seem to find any commands that will help me start it. `keybase status` reports it's not running, `keybase launchd list` says that there are no services for kbfs.

I have the latest version of keybase, `keybase version 1.0.14-1`, installed via brew. Any help would be much appreciated!

**Comment by strib** [comment]
KBFS is still invite-only, as explained on this page: http://keybase.io/docs/kbfs.  That link also contains instructions on how to get your name on the invite list.  KBFS is not currently included in the brew releases or the downloads from the main website.
