### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by JokerQyou** [keybase/keybase-issues#2189]
I forget my passphrase for keybase, as well as for my main GPG key pair. After revoking my GPG key I searched for a way to recover my keybase account. I tried the following:

* From the keybase commandline, typed `keybase passphrase recover`, error returned as `No paper key found`
* From the form on the login webpage, entered my email address, error returned as `You have active devide so we cannot recover your account via webpage` (the active device is my Mac, which is no longer loggedd in)
* Emailed the mail address given in the error message after submitting the web form, but still has not received any reply after 30+ hours.

What should I do now? Is there any way other than abandoning this keybase account?

**Comment by zQueal** [comment]
This is the second such ticket in a short period of time. It could be that the email daemon is down, or something similar. 

/cc @maxtaco @malgorithms

**Comment by wojtekk** [comment]
I have similar problem :/

**Comment by JokerQyou** [comment]
15 days passed and there is no progress at all. :(

**Comment by maxtaco** [comment]
@JokerQyou, what is your keybase username or email?

**Comment by JokerQyou** [comment]
@maxtaco This is me: https://keybase.io/jokerqyou

**Comment by maxtaco** [comment]
I sent an email to your address on record.  Reply in the affirmative if you want me to reset your account.

**Comment by blackxored** [comment]
I also have the same problem @maxtaco. Had to downgrade back to El Capitan from Sierra and can't recover my account via any of the listed methods.

**Comment by nikhildhamija24** [comment]
I am not logged in, an unable to recover my passphrase as well. Forgot password is not working, keybase passphrase recover and keybase passphrase change are also not working. What should i do now?

**Comment by nikhildhamija24** [comment]
@maxtaco
