### ISSUE TITLE
Unable to sign installation of Keybase

### ISSUE THREAD

**Issue by chortlehoort** [keybase/keybase-issues#2196]
Today I noticed that the old Node program was obsolete, so I followed instructions to remove it, and then installed via homebrew. Then tried to login with the new program and got the following error.  Public key is still valid (not expired)

```
╰─$ keybase login stevebrownlee
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
Choose a signing option: 3
Enter a public name for this device: MACPRO17
▶ ERROR openpgp: invalid argument: no valid signing keys
```

Need guidance.  Thanks in advance.

**Comment by maxtaco** [comment]
Can you send the result of running:

`keybase -d login`

?

**Comment by chortlehoort** [comment]
Sorry, missed this before I resolved it, which was done by deleting my keys and then re-importing.
