### ISSUE TITLE
unmatched paren in Sign function, docs/crypto/kbfs section 4.2

### ISSUE THREAD

**Issue by hasherati** [keybase/keybase-issues#2208]
There is an unmatched closing parenthesis in the Sign function equation.  Section 4.2 here
https://keybase.io/docs/crypto/kbfs
σ(md)= Sign(e​ui,md))

Couple other typos in the doc
Section 3.1 
`s/out/our`
Section 5.3
`s/ever/every`

**Comment by strib** [comment]
Thanks!  This is fixed internally, and will update the next time we deploy our webserver.
