### ISSUE TITLE
[QOL] Brace Expansion

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#2211]
Is there any way to get this working?

I recently ran `keybase pgp pull` which required me to re-track a few users. I got a really cool popup via the GUI client, which showed me graphically what changed, but after clicking "retrack user" (or whatever it was), and running `keybase pgp pull` again, I was met with the same issues prompting me to manually `keybase pgp track` which seemed to work fine.

The first time I tried it, however, I tried to do a brace expansion.

    keybase gpg track {user1,user2,user3}

to make life a little easier but was met with an error;

    Error parsing command line arguments: Track only takes one argument, the user to track.

I've always used brace expansion to make working with the CLI a little easier--that and it opens up the CLI for basic [pattern matching](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html#Pattern-Matching).

Any idea if this could be implemented? I'm not entirely sure if this is a Keybase or a Windows thing, however, I do know that expansion for most things already works with Windows.

**Comment by zanderz** [comment]
Commands which support multiple user ids, such as `keybase pgp pull user1 user2...`, already work without brackets or special formatting. In the windows command console, quotes can be used to include spaces in a single argument, such as a paper key, but there are no formatting tricks which can change a single user ID into multiple ones if a command wasn't written specifically to accept them.

**Comment by zQueal** [comment]
OK!

As always, thanks for the reply!
