### ISSUE TITLE
Unable to replace/update PGP key

### ISSUE THREAD

**Issue by asbjornu** [keybase/keybase-issues#2215]
I've created a new public key I'd like to use in Keybase, GitHub and everywhere else. The reason I'm not using the one Keybase created for me, is because I'd like it to have my personal e-mail address, while Keybase's key uses asbjornu@keybase.io.

Anyway, I'm unable to get this to work. I've tried directly updating the key, but since my new key obviously don't share a fingerprint with the old one in Keybase, that doesn't work. The error message I got when doing this, wasn't obvious, though; it said something along the lines of "This key is not active".

So, I tried deleting the key from my Keybase account in order to replace it with my new public key. I exported Keybase's public/private key pair and deleted the private key. I am now able to input my new key without any errors, but I'm unable to verify it:

> **How would you like to sign your updated public key? You'll do this using your private key.**
> - [ ] in the browser (unavailable for you)
> - [ ] command line with keybase
> - [ ] command line with [bash + GPG + cURL]

If I choose "command line with keybase", it tells me to run `keybase pgp update`, which just fails with:

```
▶ ERROR Login required
```

If I choose "command line with [bash + GPG + cURL]", it tells me to run a gigabyte long statement that ends up asking for the passphrase of my old Keybase key:

```
You need a passphrase to unlock the secret key for
user: "keybase.io/asbjornu <asbjornu@keybase.io>"
4096-bit RSA key, ID 43E5C36E, created 2014-09-30

Enter passphrase:
```

When I enter my passphrase, it fails with:

```
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string
```

So I'm now not entirely sure what to do. Ideas?

**Comment by ehvattum** [comment]
I attempted to accomplish the same, but on windows.
I ended up manioulating my private key in gpg, by adding one more email address to it, and thereafter I think, I recreated the public key based on the updated private key.
Then i uploaded the private key to keybase through the cli, and updated the pubkey through the web-interface.

**Comment by maxtaco** [comment]
@asbjornu try 'keybase login'

**Comment by asbjornu** [comment]
@maxtaco Thanks, that helped! It would be lovely if `keybase` pointed me in that direction automatically. :smiley:

**Comment by maikell** [comment]
Keybase client version: 0.8.25
I was able to reproduce this bug, including the 'keybase login' step:

$ keybase login
$ ./update_key                                                                                                                                       
You need a passphrase to unlock the secret key for
user: "Maikel*  <maikel@*>"
4096-bit RSA key, ID 4011758E, created 2013-06-30

Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string

**Comment by maxtaco** [comment]
What does "update_key" do?

Likely the issue is that your key is too big to be passed via command line argument to curl. We can definitely Jack around this by making a temporary file and passing that to curl

**Comment by maikell** [comment]
Hi maxtaco,
Sorry, I should have been more clear about that. That's the script you'll get after 'change public key' on keybase.io.  My key is 4096 bits and contains four e-mail addresses of mine. I don't know if I expose personal data if I will expose that script. My public key can be found @ https://keybase.io/maikel/key.asc

**Comment by maxtaco** [comment]
That error results from truncation or something similar.  You can debug
this on your own. Good luck!
