### ISSUE TITLE
keybase for Windows suspected malware by FSecure 

### ISSUE THREAD

**Issue by bkimminich** [keybase/keybase-issues#2216]
The F-Secure antivirus software suspects keybase to be malware. It prevents installation:
![keybase_install_fsecure_alert](https://cloud.githubusercontent.com/assets/3531020/14763469/c58697d0-0996-11e6-9bb7-bf90345f0505.jpg)

When turned off during installation F-secure will delete keybase.exe after next reboot:
![keybase_fsecure_alert_on_launch](https://cloud.githubusercontent.com/assets/3531020/14763468/c56ea198-0996-11e6-9fd6-c2aee1e0dd4d.jpg)

After been removed keybase of course doesn't work any more on every consecutive boot:
![keybase_launch_error](https://cloud.githubusercontent.com/assets/3531020/14763470/c5985f6a-0996-11e6-86e9-03bdb97499a4.jpg)

Does anyone get similar reaction by other AV software? Any ideas why this happens? Happened to me with v1.0.15. The version I had before (don't remember which one) never caused any problem like this.

(cc/ @F-Secure)

**Comment by zQueal** [comment]
> Does anyone get similar reaction by other AV software?

I haven't been a slave to an AV for some 10 years, but it's an interesting false/positive.

This is the file in question;

```
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Program Files (x86)\Keybase\keybase.exe" & Chr(34) & " ctl watchdog", 0
WinScriptHost.Run Chr(34) & "C:\Program Files (x86)\Keybase\kbfsdokan.exe" & Chr(34) & " -log-to-file -debug k:", 0
Set WinScriptHost = Nothing
```

**Comment by bkimminich** [comment]
Hm, probably based on the assumption "VBS is evil by default" which is like 99,99% true... (-:

Am 24. April 2016 04:11:56 MESZ, schrieb Zach Queal <notifications@github.com>:

**Comment by zQueal** [comment]
Dear Customer,

    Thank you for submitting a sample to us. Your report has been sent to our Response team to be analysed. If you have chosen to be notified of the analysis result, the result will be sent to your email in a short while.

    F-Secure Labs

In the interim I've submitted the `vbs` sample to F-Secure as a false positive. In hindsight `vbs` probably isn't the best way to handle this, although I can't think of any alternatives on the spot.

**Comment by zanderz** [comment]
zQueal: Thanks for your help, but isn't this issue about the CLI client? It has a slightly different .vbs file, which of course does not include kbfsdokan.

bkimminich: We are still determining the best installed configuration on Windows. The vbscript launches our command line processes without showing console windows; if this continues to cause problems with AV software we will sue some other method.

As to the .exe file, it is signed with an EV certificate. We'll submit it to F-Secure and see what they say.

**Comment by zQueal** [comment]
> isn't this issue about the CLI client?

Either I just didn't read it, or it was edited in after I saw this ticket;

> When turned off during installation F-secure will delete keybase.exe after next reboot:

Seems like it is. I must have just assumed it was the .vbs for various reasons--mostly just assuming that F-Secure was using lazy heuristics.

**Comment by zanderz** [comment]
As far as keybase.exe, FSecure replied that it was clean, and offered instructions for allowing specific files:

> Hello,
> 
> Thank you for your submission.
> The file you submitted is indeed clean. A database update will be released to resolve this issue.
> 
> For the meantime, you may exclude this file from Real-time Scanning.Instructions for exclusions can be found here:
> 
> Internet Security 2013/2014:
> https://community.f-secure.com/t5/Security-for-PC/How-do-I-exclude-a-file-or/ta-p/15398 
> 
> Internet Security 2015:
> https://community.f-secure.com/t5/Security-for-PC/How-do-I-exclude-a-file-or/ta-p/56363 
> 
> Policy Manager and PSB Workstation:
> https://community.f-secure.com/t5/Management/Excluding-objects-from-Real-Time/ta-p/66013
> 
> For the latest database updates please visit this page:
> https://www.f-secure.com/en/web/labs_global/removal-tools/-/carousel/view/140
> 
> We apologize for any inconveniences that this may have brought you. 
> 
> Should you have further questions, please do not hesitate to contact us again.
> 
> Best regards,
> Victor
> Malware Analyst
> F-Secure Security Labs
> 
> Visit our Labs blog at https://labsblog.f-secure.com/Give and get advice in our F-Secure Community at https://community.f-secure.com 
> Contact Support at https://www.f-secure.com/support
>

**Comment by bkimminich** [comment]
Seems they did that DB update already as I now could install the client w/o any trouble (except that the installer can't be closed afterwards. Nothing a reboot can't fix, luckily...)
