### ISSUE TITLE
Direct link to encrypt message for me?

### ISSUE THREAD

**Issue by libeclipse** [keybase/keybase-issues#2219]
Basically what I'm suggesting is there be a direct link that anyone can click on and it will take them to https://keybase.io/encrypt but with the username already filled out with my own. This would make it really useful to link in on websites and blogs without instructing people to enter my username there.

**Comment by dtiersch** [comment]
This already exists, you just need to append `#username`, like this: https://keybase.io/encrypt#eclipse

**Comment by libeclipse** [comment]
Ah. Thank you.
