### ISSUE TITLE
Keybase web says "not hosting your private key", but key uploaded

### ISSUE THREAD

**Issue by maebert** [keybase/keybase-issues#2220]
I just noticed I can't decrypt from the browser because apparently I didn't upload a private key. I checked my [profile](https://keybase.io/maebert) and there is definitely a private key for my [public key](https://keybase.io/maebert/key.asc) (it offered me to `Export my private key from Keybase`). I deleted the private key and uploaded it again, but it still doesn't seem to find it.

**Comment by agsimeonov** [comment]
I am having the exact same issue. When I try to decrypt I get:

```
alexandersimeono, you're not hosting your private key in Keybase's encrypted key store, so you can't use the in-browser decryptor. You'll need to use the keybase command line program.
```

Same thing happens with signing:

```
alexandersimeono, you're not hosting your private key in Keybase's encrypted key store, so you can't use the in-browser signing script. You can still sign messages, of course.
```

**Comment by malgorithms** [comment]
thanks - fixed!
