### ISSUE TITLE
illegal abstract question label

### ISSUE THREAD

**Issue by NodeGuy** [keybase/keybase-issues#2221]
I tried to invite a friend.  The interface reads `Optional: friend's email` and `Optional: message`.  I'm glad they're optional because I don't want to give you my friend's email.

I clicked the `Invite` button and received this message:

> A friend

> Success! Please share this invitation code with them:
> illegal abstract question label

**Comment by cjb** [comment]
Amusingly, I think that is the actual (randomly generated) invite code.

**Comment by dtiersch** [comment]
Guys? It looks like your random invitation code generator has become self-aware  :laughing:

**Comment by NodeGuy** [comment]
OMG, how funny!
