### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by MxLinux** [keybase/keybase-issues#2223]
when running `keybase decrypt` there is the potential for an error message

> Error parsing command line arguments: Command `decrypt` doesn't talk any non-flag arugments

I'm assuming 'talk' should be 'take' and 'arugments' should be 'arguments'.

**Comment by pwendelboe** [comment]
Client:  1.0.15
Service: 1.0.15
Windows 8.1 x64
Doesn't seem to be present in this version on windows.

`Error parsing command line arguments: Command decrypt doesn't take any non-flag arguments`
when `keybase decrypt a` is run. (The a is just to prompt the error)

**Comment by maxtaco** [comment]
Fixed as stated above, thanks!
