### ISSUE TITLE
Can't paste my 100 character passphrase into pinentry

### ISSUE THREAD

**Issue by amingilani** [keybase/keybase-issues#2225]
Hi

I use LastPass, and pinentry does not allow me to paste in my 100 character randomly generated passphrase. Is there a way to get around this?

**Comment by mortenlj** [comment]
See https://github.com/keybase/keybase-issues/issues/2069

**Comment by amingilani** [comment]
I recently switched from Ubuntu and no longer use pinentry, so I guess i'll just close this issue.
