### ISSUE TITLE
Keybase: Bad folder

### ISSUE THREAD

**Issue by RickyB98** [keybase/keybase-issues#2226]
I'm often getting this message in Notification Center: http://puu.sh/oBchK/a4cbe2f9b8.png
Of course, I'm not trying to write anything to /keybase/fakehome.dat - but other programs might be. Is this a known issue? Has anyone experienced the same issue and/or do you know of some other program that usually writes to that file?
Here is my log ID: 527dc3efe0d46d5f1dae6c1c
Thanks in advance :)

**Comment by cjb** [comment]
Depending on your OSX version, the `opensnoop` command can tell you which process is performing each file open.

**Comment by RickyB98** [comment]
Alright, I started this command: `sudo opensnoop -f /keybase/fakehome.dat 2>/dev/null`
Will wait until something is found. However, let me know if anything relevant can be found in the logs.
Thanks :)

**Comment by RickyB98** [comment]
Found it!
  UID    PID COMM          FD PATH                 
  501    508 TomTomHOMERunner  -1 /keybase/fakehome.dat 
  501    508 TomTomHOMERunner  -1 /keybase/fakehome.dat 
Definitely not Keybase's fault. Thank you :)
