### ISSUE TITLE
Cannot validate by TXT

### ISSUE THREAD

**Issue by chuckdee68** [keybase/keybase-issues#2227]
I tried to verify my website by TXT, but it's geting a failure, even though the TXT entry is there.

![Imgur](http://i.imgur.com/5s29Jgp.png)

![Imgur](http://i.imgur.com/rtcCSux.png)

**Comment by BrandonIngalls** [comment]
It looks like your TXT DNS entry was not configured correctly...

Here are the DNS results I see when I query one of my domains, which is correct.
```
[~]$ nslookup -query=TXT _keybase.ingalls.io - 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
_keybase.ingalls.io	text = "keybase-site-verification=okU57CEBKBWVRtWXl6xQuxqLwiNjce4D2f9ZJfs9Imc"

Authoritative answers can be found from:
```

And this is what I see when I query `_keybase.domain-name.tld` for your domain.
```
[~]$ nslookup -query=TXT _keybase.chuckdee.net - 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find _keybase.chuckdee.net: NXDOMAIN
```

**Comment by cjb** [comment]
I think it's correct -- it can be at the _keybase subdomain or directly on the zone apex, which it is here.

**Comment by chuckdee68** [comment]
I see the difference.  Yours is in the _keybase subdomain.  In the docs, it says specifically *not* to name it.  Should both work?

**Comment by maxtaco** [comment]
DNS lag can be long in some cases. Your TTL is at least 10799s

**Comment by chuckdee68** [comment]
I've been trying this for two days, and can get it as so:

$ nslookup

> set query=txt
> chuckdee.net

Non-authoritative answer:
chuckdee.net    text =

        "keybase-site-verification=-i3Y6Vh9NNbKE-5q8GBxVE_7uVjDk8i2p320bSm_FM"

**Comment by maxtaco** [comment]
click on the "retry" button on the website, it should work now

**Comment by chuckdee68** [comment]
Nope.  Just retried, and received the same results.

**Comment by chuckdee68** [comment]
I replaced the proof, and it succeeded immediately.  Thanks!
