### ISSUE TITLE
/user/lookup.json returns 0/OK with blank them field for all key fingerprint queries

### ISSUE THREAD

**Issue by scrivener** [keybase/keybase-issues#2232]
In the last week I've noticed what I think is a bug appear. All queries against the `/user/lookup.json` API for well-formed `key_fingerprint`s produce a `0/OK` response with nothing in the `them` field, like this:

```
{
  status: {
    code: 0,
    name: "OK"
  },
  them: [ ]
}
```
This is happening on both staging and live.

**What should happen**
Looking someone up by `key_fingerprint` should return information about them.

**What does happen**
All well-formed hex strings that could be  `key_fingerprint`s return an empty `them` field and a `0/OK` status value, regardless of whether the user exists or not.

**Reproduction:**
Extant user (should be @maxtaco):
https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint=8efbe2e4dd56b35273634e8f6052b2ad31a6631c

(Presumed) non-existent key:
https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

Both return the object shown above.

**Comment by kentonv** [comment]
I am seeing this too. This is causing all Sandstorm.io app installs to report that the app author is unknown, since we use the Keybase API to map fingerprints to people. I believe it was working as of Wednesday.

**Comment by maxtaco** [comment]
Thanks for the report, I pushed new code here on Wednesday.  I'll take a look

**Comment by maxtaco** [comment]
So sorry guys, fixed!  Thanks for the report.

**Comment by kentonv** [comment]
Confirmed, all better now. Thanks!

**Comment by scrivener** [comment]
@maxtaco Thanks!
