### ISSUE TITLE
[Question] What is device key, when I created it and was I asked for password?

### ISSUE THREAD

**Issue by Mikaela** [keybase/keybase-issues#2233]
I tried to track two people today, but I failed to getting asked for password for sedric by pinentry. Sedric is my hostname and I see that I have added it at Keybase (https://keybase.io/mikaela/sigchain#48adf7a9c0691df8abd63fd9291772aa39996d6cbcca2a5be53e510400de8c590f), but I have no idea what it is.

The only thing I remember is the wallet key which I have written down, but the device key password is apparently not the same thing.

**Comment by cjb** [comment]
Try your Keybase passphrase?

**Comment by Mikaela** [comment]
Too obvious to be thought about. Why this isn't mentioned anywhere when I am asked for the password?
