### ISSUE TITLE
Error: hash mismatch

### ISSUE THREAD

**Issue by Eduardogbg** [keybase/keybase-issues#2236]
I'm using keybase on browser, generated a signature and couldn't verify neither mine or my friend's.
"Error: hash mismatch"

**Comment by maxtaco** [comment]
Can you post a sample message for me to investigate?

**Comment by Eduardogbg** [comment]
Oh sorry, it was a human mistake. We were copy-pasting from email, and some formatting was automatically done. You can close this issue now.
