### ISSUE TITLE
Error: No tailer found

### ISSUE THREAD

**Issue by reallyerrol** [keybase/keybase-issues#2244]
Hello, my friends are sending me messages, using keybase.io/encrypt and using my keybase username (typed correctly etc) We've tried multiple times now, when they send me the encrypted message, I go to the decrypt page on keybase.io and paste the message and I am certain I type in my password correctly, it always says "Error: No tailer found"

I've done this multiple times and even used the CLI app but it never works.

Thanks.

**Comment by maxtaco** [comment]
copy-paste bug.  you're leaving off the end of the message:

```---- END PGP ENCRYPTED MESSAGE-----```

etc

**Comment by reallyerrol** [comment]
Upon generating an encrypted message - it doesn't appear to have the "ENCRYPTED" part. I also attempted to fix the message by adding the ENCRYPTED part, but still the same issue. 

I also tried to send myself a message from my other Keybase, which also failed as it didn't have the ENCRYPTED tag and spat out the same issue.

I'm 100% certain I'm not copying nor pasting it wrong.

**Comment by maxtaco** [comment]
I'm certain this is an error on your part. I've spent years now helping people debug the likes of these problems. I just tried it and it worked. We've had no other complaints.  Here is what a complete PGP message looks like:

```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.53
Comment: https://keybase.io/crypto

wcBMA5gKPw0B/gTfAQf/bkoHdu33BG5ahL/DZjk/pqdUTpOouKARNK1LNPRwI02K
iFpEzUcQCAtuUSENkiak5Kg9oblb97FEMAw3YEanWPSEg6DUWDZYcbPF8ufjz8lz
26f95hf17NL/mjztSK3D9fEN0EZrtYJI+Gj9Hg9v517e4hwi+Mp2CA3AqKbeM/67
psE08gtQjWkCSvqePfxqMnLgbzQ/RgRivUvXSlPS50JVANSyHgelKsvZSOm9fu8z
4aewZmdYuRTD5SXmyGGD4E2oOFIVWvhe/bpUIm1OrdMK/xHjbbvhNZpNsrWSTgrA
TUSjHqVHF3mqYWIuOL2e2iSVlSaYM9pz2QpRgcTEz9I+ARZhiZDc+7dOFE5v+5WF
6OHnUgqumZ0PnEzziGwiFR/STzSRHkcv+Y4C/V7B21GYhmRcvIsliitFAuvXsIQ=
=GU74
-----END PGP MESSAGE-----
```

You have to copy the whole thing.  If you leave off the last line, you'll get that error message.

**Comment by reallyerrol** [comment]
I think I have noticed the issue, thanks.

With Reddit ~ the way comments are formatted messes it up a bit.

Thanks for help.

**Comment by maxtaco** [comment]
Good to know about the reddit problem.  Saltpack solves this issue, but we've yet to roll it out on the web form yet. Thanks!

**Comment by christian-oudard** [comment]
This error message was pretty confusing to me when I got it. Maybe it would be worth improving the error message to mention that it was a PGP parse error?
