### ISSUE TITLE
E-mail / Username User Issues

### ISSUE THREAD

**Issue by hybby** [keybase/keybase-issues#2245]
So, I kind of messed up while getting set up on Keybase.  And it was definitely my fault, but the tools don't seem to exist for me to fix the mistakes I made while joining.

A few months ago, I was given a Keybase invite code by a co-worker, and I signed up using my work e-mail account.  For my username, I initially used my real name so that co-workers could access my account easily.  I intended to change it to something else afterwards.

After joining, I associated my personal e-mail account and verified it.  I quickly realised that i didn't want to do this, and unassociated my personal e-mail account with my Keybase account.  I also realised that I couldn't change my Keybase account name at this point, either.

I then asked someone to send a new invite to my personal e-mail address so that I could set up a new account with the name I intended.  I'd then delete my old account afterwards.  However, he couldn't send the invite - it said that my e-mail address had already been invited and couldn't send one to me.  

It seems that since I previously verified my personal e-mail account with Keybase, it's no longer valid to receive invitations.  Is there any way I can fix this, or have I messed everything up?

I'd like to delete my existing account and start again, using my personal e-mail account.  Is there any way I can do that?  Apologies for the hassle.  It's all my bad.

**Comment by malgorithms** [comment]
the invitation form doesn't require putting an email address in at all. 

so: (1) you or your friend can generate an invite code without putting an email in. (2) note the invite code. (3) delete your account. (4) signup with new invite code.

**Comment by hybby** [comment]
Huh, that's weird.  The message he sent me yesterday was "Yeah. I got big red text when I attempted sending you an invite".

**Comment by malgorithms** [comment]
I'm guessing it's because he put your email address in. The server won't send invitations to people who've already been invited, to protect against harassment/spam. But he can leave it blank and manually send you the invite code it spits out.

**Comment by hybby** [comment]
Ah, okay, thanks for explaining.  In that case, is there any chance I could have an invite applied to the `drewjess` account?  After I generate the invite and create a new account I'll delete the old account.

**Comment by malgorithms** [comment]
yup, you have invites now: https://keybase.io/account/invitations

**Comment by hybby** [comment]
Thanks a ton!  I've successfully created a new account, I'll get my old one deleted ASAP!
