### ISSUE TITLE
Invite can't be issued to email which had invite before but are deleted and open for new account

### ISSUE THREAD

**Issue by sudhirkhanger** [keybase/keybase-issues#2246]
Hi,

I had an old keybase account with silly username. I wanted to have a new official username but that is not allowed. I deleted that account and am up for queue with the same email id. Now if you had an invite on an email id which was then deleted and up in queue for new account then you can't receive an invite.

`sudhir @ sudhir khanger dot com` was invited by someone else already.

Thanks.

**Comment by zQueal** [comment]
This is entirely intended. Keybase assumes that if you delete your account then you shouldn't be contacted.

If your email server supports it, you can simply use an email address alias to receive a new invite.

    sudhir+keybase@example.com

should route to;

    sudhir@example.com

without issue.

**Comment by sudhirkhanger** [comment]
Thanks. Solved.
