### ISSUE TITLE
Proof is not being found on gh-page.

### ISSUE THREAD

**Issue by Ward9250** [keybase/keybase-issues#2247]
Hi All, I've tried to prove my gh-pages webpage (ward9250.github.io) but to no success. I added the key base.txt file to by root dir of the repo, and that didn't work. So I checked a previous issue and found that adding a file called `.nojekyll`, and making sure it and `.well-known` is included in the `_config.yaml` file and also that the `keybase.txt` file contained a yaml header that set layout to nothing and permalink to `.well-known/keybase.txt`and still no joy. How do I get this to work? My site is a HPSTR one.

**Comment by Ward9250** [comment]
Oh! It's decided to work after leaving it a while.

**Comment by sebie** [comment]
Hey,

`https://ward9250.github.io/keybase.txt` looks good to me. :)
You should only use `.well-known/keybase.txt` if you can't or do not want to put `keybase.txt` in the root of your website. Thus, you shouldn't need `include: [".well-known", ".nojekyll", ...]`. (Removing .nojekyll will also help fix up your site!)

Don't forget to close the issue if it is working. :tada:
