### ISSUE TITLE
Twitter Identity

### ISSUE THREAD

**Issue by rob-nash** [keybase/keybase-issues#2255]
I cannot verify my twitter profile. I believe it is because @rob__nash (two underscores) is causing confusion in your ur system. The generated text appears like so.

Verifying myself: I am rob_nash on Keybase.io. 5lwNT1Kj81VRT-JZ2SiG_RNSSA8TF-cC29No / https://keybase.io/rob_nash/sigs/5lwNT1Kj81VRT-JZ2SiG_RNSSA8TF-cC29No

**Comment by malgorithms** [comment]
oh hmm! what client did you generate the proof on? The website or in our app? cc @maxtaco

**Comment by rob-nash** [comment]
Website

**Comment by malgorithms** [comment]
Hi Rob - I don't think it has anything to do with the underscores. Your tweets aren't public. Keybase forms connections between public keys and public identities, via public posts. The idea is that anyone running the keybase client can verify the tweet, they don't have to trust keybase's claim of something it saw.

If you're not interested in exposing your twitter account publicly, you can still share your keybase key with your twitter friends by just tweeting your keybase username and/or key to them.  you just can't attach it to your public identity.

**Comment by rob-nash** [comment]
ok thanks dude. makes sense.
