### ISSUE TITLE
Web proof is online but Keybase thinks it's broken

### ISSUE THREAD

**Issue by inklesspen** [keybase/keybase-issues#2261]
https://inklesspen.com/.well-known/keybase.txt
https://keybase.io/inklesspen

Keybase says the proof isn't up. It plainly is. How can I proceed from here?

**Comment by maxtaco** [comment]
Something's up with your TLS config.  Open your site on firefox, and you get a security warning. We use the same CA list as firefox (via Node.js), so likely you're missing an intermediate cert

**Comment by inklesspen** [comment]
In Firefox on OSX, it works just fine. I was able to reproduce the issue with node on linux, though, which enabled me to verify the fix after refetching the intermediate cert. Dunno what went wrong. Maybe you can point to some tool that will let people easily fetch the proof just as keybase would?
