### ISSUE TITLE
Unable to validate website via http/https

### ISSUE THREAD

**Issue by nugget** [keybase/keybase-issues#2263]
I noticed recently that my https validation of macnugget.org on https://keybase.io/nugget is showing a failure.  This used to work, but now it resists a "retry" or "replace" operation.  It seems as if the Keybase.io side is failing to connect to my web server.

I can't reproduce the problem, though, and https://macnugget.org/keybase.txt loads just fine for me using curl or desktop browsers.

Any clue what the problem is?

**Comment by nugget** [comment]
Upon review, I'm betting this is a duplicate of #1801

**Comment by nugget** [comment]
No, doesn't look like it's the redirect issue.  I configured apache so that it will serve http://macnugget.org/keybase.txt without a redirect to https and the validation is still failing.

**Comment by maxtaco** [comment]
This one seems like a bug in Node 4.3.1 that's timing out in the TLS/HTTP handshake.  I'll see if an upgrade can fix it.  Thanks!

**Comment by maxtaco** [comment]
Should be fixed!
