### ISSUE TITLE
Unable to login using client

### ISSUE THREAD

**Issue by Rock-Y** [keybase/keybase-issues#2264]
After deprovisioning my account, I'm unable to login the keybase client again. It results in the following error:

keybase login
Your keybase username or email address: {e-mail}
Please enter the Keybase passphrase for {e-mail} (12+ characters):
- ERROR eldest called on user with existing eldest KID

I can logon to the website, but I'm unable to ad my PGP key, I get the following error:
could not find the requested key.
Generating a new PGP key doesn't appear as well.

Currently I'm unable to recreate my account.

**Comment by maxtaco** [comment]
Thanks for the report. Can you run `keybase log send`?  Thank you!

**Comment by maxtaco** [comment]
Do you mean to fully reset your account?

@oconnor663 looks like he revoked his last device (username rock_y)

**Comment by Rock-Y** [comment]
@maxtaco I've run `keybase log send`, log ID: 645dfe8a654ed74a853a931c

Yes, I wanted to fully reset my account

**Comment by maxtaco** [comment]
Ok, you're now fully reset

**Comment by Rock-Y** [comment]
Thanks @maxtaco
