### ISSUE TITLE
Adding new services, like GNUSocial instances.

### ISSUE THREAD

**Issue by JaymesKeller** [keybase/keybase-issues#2267]
Some people have their reasons for not using things like Twitter. I propose that the ability to add GNUSocial instances, like Quitter, to keybase profiles. As for proofs in that system, I've yet to figure it out, as I'm not sure if it supports APIs like twitter.

**Comment by zQueal** [comment]
#518

**Comment by JaymesKeller** [comment]
Okay, I'll close the issue as a dupe.
