### ISSUE TITLE
Public key only

### ISSUE THREAD

**Issue by herrjemand** [keybase/keybase-issues#2268]
How do I upload ONLY public key and not private? I don't exactly want to upload my private key to keybase, and I could not figure out how to upload just public key.

**Comment by maxtaco** [comment]
It should be self explanatory. Are you using the web site or the client? It
web site, click "maybe later"

**Comment by herrjemand** [comment]
@maxtaco I am using CLI. You can not add public keys through web interface anymore.

**Comment by maxtaco** [comment]
Yes you can.

And you can do it through the CLI via 'keybase pgp select'

**Comment by herrjemand** [comment]
@maxtaco Ok. That's worked. I got a bit confused with man pages. Thanks for help.
