### ISSUE TITLE
Trial expired, name claim expired

### ISSUE THREAD

**Issue by willjasen** [keybase/keybase-issues#2269]
I had received an invite a while back and began the signup process as willjasen, but I forgot to complete it. I was no longer able to use the original invite, but I wasn't able to reset my account password either. Using a new invite, I signed up as willjasen2, but I'd really like to merge the second into the first. Note that I haven't posted a key on either yet.

https://keybase.io/willjasen
https://keybase.io/willjasen2

**Comment by malgorithms** [comment]
there's no way to merge accounts, but can you email me? (chris at keybase io) I think you can prove you're the owner willjasen and I can repurpose the account for you. I can prob get to it tomorrow. start by emailing me from the account you registered the second one from. gonna close this issue.
