### ISSUE TITLE
[KBFS] Lost view of favorites

### ISSUE THREAD

**Issue by petethomas** [keybase/keybase-issues#2271]
Using Keybase GUI (1.0.16-20160610231501+9ac76dd) the client seems to have lost its view of any favorite folders.  The folders are accessible as I assert them but they don't seem to stick.  I do see `keybase.kbfs.log` entries reading in part `method 'favoriteList' not found in protocol` but not sure if those are related:
```
> pwd
/Users/petethomas
> ls /keybase/private
> cat /keybase/private/petethomas/test.txt
Hello, world!
> ls /keybase/private/petethomas,max
> ls /keybase/private
> ls /keybase/public
> cd /keybase/private/petethomas
> cat test.txt
Hello, world!
> ls /keybase/private/
[...]
> keybase log send
```

I also tried restarting the app a few times and rebooting the laptop but result is the same.  Thanks in advance!  -p

**Comment by maxtaco** [comment]
Ruh roh

@oconnor663 more fallout from the protocol breakage

**Comment by oconnor663** [comment]
Ack, totally my fault. The fix is already checked in (https://github.com/keybase/kbfs/commit/e09a6a530519946b4b4491c4cef3757042d0afd0) and will go out with our next update.

**Comment by cjb** [comment]
@petethomas Hi, is this still broken for you with your current build?

**Comment by petethomas** [comment]
Yes if "current build" means the same build running when I first reported the issue.  Dropdown shows the one favorite I added separately (after mounting `/keybase` myself from [source](https://github.com/keybase/kbfs/commit/e09a6a530519946b4b4491c4cef3757042d0afd0)) but the command line and Finder don't show it and no favorites I try to create are visible.  

<img width="400" alt="kb" src="https://cloud.githubusercontent.com/assets/138717/16018490/7eb3865c-3159-11e6-9d82-5b81ddb7a039.png">

If "current build" meant the latest available, I have't tried it yet but am happy to upgrade.  Thanks again for the help.

**Comment by petethomas** [comment]
Just tried the 0613110021build and unlike using 0610231501 above, it so far works as expected regarding favorites.

**Comment by cjb** [comment]
@petethomas Sorry to keep bugging you -- we're unclear on how you're getting these builds, are you downloading each .dmg manually, or using our updater?

**Comment by petethomas** [comment]
@cjb No it's fine to bug me; I have been trying one .dmg at a time and also trying some things from the command line within the repos you guys provide. This is just to help us with issue isolation when debugging some of our own experiments.
