### ISSUE TITLE
Coinbase doesn't have a "public key" field in the settings.

### ISSUE THREAD

**Issue by jericson** [keybase/keybase-issues#2275]
The instructions for proving ownership of a Coinbase account say:

> Please visit this link  and paste the below text, exactly as it appears, as your "public key" on Coinbase.

The link is to my settings on Coinbase. However, the only that change my public profile are:

* Your Coinbase URL
* Location
* Caption

None of these fields are large enough to hold the Keybase proof. Searching the Coinbase help pages, I can't find where the "public key" field might have moved or if it still exists at all. So I'm unable to link Keybase to Coinbase.

(See also: [Instructions for Coinbase need clarification](https://github.com/keybase/keybase-issues/issues/935).)

**Comment by malgorithms** [comment]
Hmm, have you set a "coinbase URL" yet that matches your coinbase username? 

If you have, *and* you're logged in, you should be able to visit a page of this form:

```
www.coinbase.com/<yourusername>#settings
```

and see the public-key link.

I just tested and it works for me. But this only works if this page works for you in an incognito/private window, logged out, too:

```
www.coinbase.com/<yourusername>
```

**Comment by jericson** [comment]
Derp. I ended up on https://www.coinbase.com/settings somehow. I think I assumed this was the same settings page as www.coinbase.com/<yourusername>#settings. Sorry about that.
