### ISSUE TITLE
Telehack Proof

### ISSUE THREAD

**Issue by virtualdxs** [keybase/keybase-issues#2283]
Telehack allows you to create up to a 10-line plan, which is publicly accessible via finger. This seems like it would be neat and simple to implement. Preferably it would be a short one like Twitter, so we can use our plans for more than just that. Sound good?

**Comment by zQueal** [comment]
Added to #518

**Comment by virtualdxs** [comment]
For the link you can add http://telehack.com/telehack.html.

**Comment by virtualdxs** [comment]
I'd use / but it doesn't describe what TH is.
