### ISSUE TITLE
Keybase website - Not pulling avatar from Github

### ISSUE THREAD

**Issue by ammaraskar** [keybase/keybase-issues#2285]
https://keybase.io/ammar2

When I click the edit button next to my avatar it displays a link to `prove my github identity` even though it's already proven.

Upon clicking the `Refresh my photos` button a `Success, reloading...` message shows up but the avatar still isn't updated.

Not sure if it makes a difference but I recently wiped my key and reseted my profile.

**Comment by joshrendek** [comment]
I just signed up and tried to get my github icon to pull as well - I did the proof step 2x and had the same outcome as above.

**Comment by malgorithms** [comment]
hey both of  you - can you click your avatar on the site and try to refresh your photos? I think I fixed it.

**Comment by ammaraskar** [comment]
Seems to be fixed for me, thanks!

**Comment by malgorithms** [comment]
that was awesomely fast. thanks!

**Comment by joshrendek** [comment]
Working, thanks!
