### ISSUE TITLE
Can't create "New passphrase"

### ISSUE THREAD

**Issue by KyleKing** [keybase/keybase-issues#2286]
Is there any way to update the Keybase.io passphrase? The current form is disabled

<img width="885" alt="keybase google chrome today at 7 56 03 am" src="https://cloud.githubusercontent.com/assets/3784339/16118814/c03e3096-33a6-11e6-88ab-74b176328cc2.png">

**Comment by cjb** [comment]
Have you tried pressing it?  I don't think that onclick prevents the form working.

**Comment by KyleKing** [comment]
You have amazing speed at responding! I tried again and the original issue was that I used too short a password (11 characters). So error on my part and the disabled button works perfectly
