### ISSUE TITLE
Windows client flagged by Kapersky, Qihoo-360, and Fortinet as a virus

### ISSUE THREAD

**Issue by emanb29** [keybase/keybase-issues#2289]
My AVs are throwing a fit over keybase for some reason, which I've never seen before. Very likely a false positive. I am using `Service: 1.0.11-201602111011+b5a91f4` which has a SHA256 hash of 2e79b7f093aa47d8401433ded34658732c858f40159c5af87e32399bd0346ed3.

I've attached screenshots of the file (with size) as well as the "malware detected" notification from kapersky.
![2016-06-16 22_16_57-alertwindow](https://cloud.githubusercontent.com/assets/789922/16141519/640eb78a-3411-11e6-83ac-4d07848c9517.png)
![2016-06-16 22_17_07-keybase](https://cloud.githubusercontent.com/assets/789922/16141520/64142a9e-3411-11e6-8c59-00f35861a2e9.png)

No flags have been raised by MalwareBytes or any other anti-viruses than those listed.

See also: #2216

**Comment by emanb29** [comment]
Result types from Qihoo and Fortinet
![2016-06-16 22_28_47-antivirus scan for 2e79b7f093aa47d8401433ded34658732c858f40159c5af87e32399bd0346](https://cloud.githubusercontent.com/assets/789922/16141560/c0e3ba8c-3411-11e6-9ddc-942733ce9579.png)

**Comment by ChizuruAmamiya** [comment]
Qihoo 360 is thought of as a spyware in China(Most people including me.) and it collects personal data from its users, so my suggestion is to abort it and try some other antivirus software. Thanks for your understanding.

**Comment by ChizuruAmamiya** [comment]
Could you please submit the sample to the Kaspersky Lab? Make sure it is compressed without password protected. And official will remove the suspicious "keybase" file from their database after it is confirmed as safe one. Thank you for your cooperation！
