### ISSUE TITLE
Which public key is used in identity proofs?

### ISSUE THREAD

**Issue by larryv** [keybase/keybase-issues#2294]
Several people I know have had Keybase for varying amounts of time.
- [raimue]
- [lavergne]
- [cm2]

All three of the linked GitHub proofs seemed to use a PGP key, since they contain fingerprints and ASCII-armored signatures.

[My proof][larryv], on the other hand, used something that does not seem to be a PGP key. I generated my proofs (see [Reddit] also) with the 1.0.16 command-line client (`keybase prove github larryv`) *after* importing my PGP key.

Is this expected behavior? If so, exactly what public key was used? If not, how can I get Keybase to use my PGP key?

(Forgive me if I'm missing something fundamental about the way Keybase works; I'm very new to it.)

[cm2]: https://gist.github.com/cm2/70020aada90b0eb91b81e8cf6d597208
[larryv]: https://gist.github.com/larryv/08a9da31df4014aaeaf997eb370f9912
[lavergne]: https://gist.github.com/nerdling/7521a60d4afecf337adeb405bf164cbe
[raimue]: https://gist.github.com/raimue/9997790
[reddit]: https://www.reddit.com/r/KeybaseProofs/comments/4p0ukf/my_keybase_proof_redditlarryv_keybaselarryv/

**Comment by malgorithms** [comment]
good question!

Keybase now works on per-device keys, which are safer than trying to move private keys around, which is dangerous/confusing, and which screws up your whole cryptographic identity if you have a single device lost/stolen/compromised.

here's a blog post about it: https://keybase.io/blog/keybase-new-key-model

and here's your own relationship among your keys:

https://keybase.io/larryv/graph

as you can see from the sigchain view:

https://keybase.io/larryv/sigchain#df0b4889ee7d3be9d62042fd669679efd0413cc36b548cb4a5103c53a766946b0f

the person who signed that Github proof (with a key called `titan` - you!) is exactly the same person who owns a certain PGP key, and it's provable in both directions. The PGP key leads to the Github proof and vice versa. 

As you add more devices, you'll only need to put your PGP on the devices that actually need PGP, yet you will still be you, cryptographically speaking.

**Comment by larryv** [comment]
Thanks for pointing out the blog post! I'd missed it somehow.

My pieced-together understanding is:
- If a user did/does the following, then their proof is signed with a PGP key:
    - Signed before you rolled out your new key model.
    - Uploads their private PGP key and signs using the web interface.
    - Signs using your `curl`+`gpg` incantation.
- If a user uses a recent version of the CLI or GUI, then their proof is signed with a per-device key, and the entire public key is published in the proof (since Ed25519 public keys are so small).
- Proofs are symmetric, so signing with a per-device key should be as good as signing with the PGP key (for practical purposes).

Is this more or less correct?

**Comment by malgorithms** [comment]
Yup, that sounds right. Remember, all these public keys are written into a chain, so when your PGP key adds a "device" key or vice versa, it is actually signing a statement that that key can also add statements to your signature chain, and the key getting added also signs a counter-statement accepting that. So they really both have equal power in your sig chain. Further, if you decide to remove a device key, that also goes into your sig chain. We've set up things with extreme transparency on these chains, so the server can't get away with hiding them.

**Comment by larryv** [comment]
Alright, I think I'm getting the hang of it. Thanks for your help (and work)!
