### ISSUE TITLE
KBFS - Linux Error private folder for multiple users

### ISSUE THREAD

**Issue by jeffbristow** [keybase/keybase-issues#2295]
Background: I created a private folder using a Mac for myself and one other user. My Mac is able to access the folder and so is the other user.

I added another device, this time a Linux computer. Keybase on the Linux computer is able to access my private folder and my public folder with no issue. However, the folder for myself and one other user is giving the following error:

"Sorry, could not display all the contents of "user1,user2": Error opening directory '/keybase/private/user1,user2': Input/Output error".

Note: I swapped out the actual usernames in the error with user1 and user2.

On the Mac I am still able to access this private folder, just not on the newly added Linux device.

**Comment by cjb** [comment]
Has the Mac been online recently, and is it running recent Keybase software? It needs to "rekey" the folder for your Linux machine.

If it's online and still not working, please type "keybase log send" and share the log ID.

**Comment by jeffbristow** [comment]
Yes, the Mac is online and running the latest version of keybase. Here is the log ID from the Mac.

3501ae42f7e466be1cc2e21c

Is there a command to force the mac to rekey the private folder?

**Comment by jeffbristow** [comment]
Additional Information: I restarted the Mac and now the Mac is also unable to access the private folder shared between myself and another user.

New log ID after the Mac encountered the error as well.

4fc0cb8462b68f99e4a70f1c

**Comment by jeffbristow** [comment]
Looks like ya'll are already on top of this. My friend had reported the issue yesterday and you are working on it from that end. This is the related request from him.

https://github.com/keybase/client/issues/3143#issuecomment-227286822

**Comment by strib** [comment]
Yep, we'll take care of it over at keybase/client#3143.  Thanks for the report and the logs.  Closing this as a dup.
