### ISSUE TITLE
KBFS sending OS X notifications for other users' operations

### ISSUE THREAD

**Issue by meristem** [keybase/keybase-issues#2297]
This afternoon I began seeing OSX notifications for KBFS errors I'm not generating. This is new behavior, and I'm wondering if related to the update I installed a few minutes ago.

My device runs keybase
Client:  1.0.16-20160615195851+9200593
Service: 1.0.16-20160615195851+9200593

![screen shot 2016-06-21 at 16 00 39](https://cloud.githubusercontent.com/assets/19893979/16249294/a90b6bec-37c9-11e6-82f9-e0c1799335db.png)

**Comment by strib** [comment]
Those are generated by some program on your device that is trying to lookup those paths under `/keybase/`, `/keybase/private/` and `/keybase/public`.  We show you those notifications to help teach you how to use Keybase, but we understand that when it's some other program on your computer, it can be confusing when you see popups for no reason.  Unfortunately, we can't tell the difference between you doing something and your device doing it in the background.

Looks like both of these might be related to some video or camera software running on your computer that scours your folders for certain names?  If this is a widespread issue, we could add these to a blacklist of errors not to cause popups for.

**Comment by meristem** [comment]
Jeremy, thanks to you pointing out the problem is on my side I was able to replicate the condition.  Starting iMovie 10.1.2 (on El Captan 10.11.5) led to the messages. Disabling all iMovie notifications in the pref panel did not stop the behavior.

**Comment by strib** [comment]
@meristem: They are definitely Keybase notifications, not iMovie notifications.  Maybe there's a setting in iMovie to restrict what folders it scans, or turn off that feature?

**Comment by meristem** [comment]
This behavior has to do with my iMovie install looking for particular codecs.  Reached out to a friend at Apple. Will let you know if/what I learn.

**Comment by strib** [comment]
Notifications for these iMovie names will now be suppressed, starting in the next release.
