### ISSUE TITLE
Moving /keybase.txt to /.well-known/keybase.txt

### ISSUE THREAD

**Issue by OllieTerrance** [keybase/keybase-issues#2305]
I have moved some HTTP proofs from `/keybase.txt` to `/.well-known/keybase.txt` on my server, however I am now getting recurrent requests to the old location (which 404), without any apparent attempt to try the updated location.

Is there a way to get Keybase to check both locations again, without regenerating all the proofs?

**Comment by maxtaco** [comment]
Give it a day or so, I believe it will stop...

**Comment by OllieTerrance** [comment]
Righto, I'll keep an eye on it.

**Comment by OllieTerrance** [comment]
It appears all the proofs have broke now.  😦  Can't see any requests for `/.well-known/keybase.txt` in the logs, and selecting "my proof is now live, retry" also only checks the old location.

**Comment by maxtaco** [comment]
Oh I misunderstood the original issue, sorry about that.  I can push a few
buttons on the backend on Monday if I don't get pulled away on something
else.

**Comment by maxtaco** [comment]
Hah, I didn't realize you had N>10 of them.  Anyways, fixed.
