### ISSUE TITLE
Not proving myself with github and twitter ,inspite of having valid account.

### ISSUE THREAD

**Issue by unixbhaskar** [keybase/keybase-issues#2308]
Here is what I tried:

My account :   https://keybase.io/bhaskarchowdhury

On my laptop shell 

Twitter:
bhaskar@Fedora_17:50:27_Sat Jun 25:~> keybase prove twitter
You already have a proof for unixbhaskar@twitter; overwrite? [y/N] y
Your username on Twitter: unixbhaskar
Please publicly tweet the following, and don't delete it:

Verifying myself: I am bhaskarchowdhury on Keybase.io. 1KRf1S9kraKkhnucYFVDNf9kM4rMDXqyjLIk / https://keybase.io/bhaskarchowdhury/sigs/1KRf1S9kraKkhnucYFVDNf9kM4rMDXqyjLIk

Check Twitter now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] 

Then CTRL-C 

for Github:

bhaskar@Fedora_17:52:24_Sat Jun 25:~> keybase prove github
You already have a proof for unixbhaskar@github; overwrite? [y/N] y
Your username on Github: unixbhaskar
Please publicly post the following Gist, and name it keybase.md

### Keybase proof

I hereby claim:

  * I am unixbhaskar on github.
  * I am bhaskarchowdhury (https://keybase.io/bhaskarchowdhury) on keybase.
  * I have a public key ASBmb5hbp6_D1UJ1GZF9aIz54e2_93t4_rPhvxNvQ_9ELgo

To claim this, I am signing this object:

```json
{
    "body": {
        "key": {
            "eldest_kid": "0120666f985ba7afc3d5427519917d688cf9e1edbff77b78feb3e1bf136f43ff442e0a",
            "host": "keybase.io",
            "kid": "0120666f985ba7afc3d5427519917d688cf9e1edbff77b78feb3e1bf136f43ff442e0a",
            "uid": "e348758d6ddca56b802d4a5b061af519",
            "username": "bhaskarchowdhury"
        },
        "service": {
            "name": "github",
            "username": "unixbhaskar"
        },
        "type": "web_service_binding",
        "version": 1
    },
    "client": {
        "name": "keybase.io go client",
        "version": "1.0.16"
    },
    "ctime": 1466857388,
    "expire_in": 504576000,
    "merkle_root": {
        "ctime": 1466857348,
        "hash": "638db4648ef7db5a3f95cf1c59d763a83a331e6beb1aea363cbcd6a6ed3bd97c6a4c61d5fd20c94769e8a2654f354895daf23c9932372a6b47e5832d7c1d2ce5",
        "seqno": 498475
    },
    "prev": "e5babc56f66203d20e61d2855d324a9d2948c71c43b5cb9ae52aaa21d25d3259",
    "seqno": 11,
    "tag": "signature"
}
```

with the key [ASBmb5hbp6_D1UJ1GZF9aIz54e2_93t4_rPhvxNvQ_9ELgo](https://keybase.io/bhaskarchowdhury), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgZm+YW6evw9VCdRmRfWiM+eHtv/d7eP6z4b8Tb0P/RC4Kp3BheWxvYWTFAvh7ImJvZHkiOnsia2V5Ijp7ImVsZGVzdF9raWQiOiIwMTIwNjY2Zjk4NWJhN2FmYzNkNTQyNzUxOTkxN2Q2ODhjZjllMWVkYmZmNzdiNzhmZWIzZTFiZjEzNmY0M2ZmNDQyZTBhIiwiaG9zdCI6ImtleWJhc2UuaW8iLCJraWQiOiIwMTIwNjY2Zjk4NWJhN2FmYzNkNTQyNzUxOTkxN2Q2ODhjZjllMWVkYmZmNzdiNzhmZWIzZTFiZjEzNmY0M2ZmNDQyZTBhIiwidWlkIjoiZTM0ODc1OGQ2ZGRjYTU2YjgwMmQ0YTViMDYxYWY1MTkiLCJ1c2VybmFtZSI6ImJoYXNrYXJjaG93ZGh1cnkifSwic2VydmljZSI6eyJuYW1lIjoiZ2l0aHViIiwidXNlcm5hbWUiOiJ1bml4Ymhhc2thciJ9LCJ0eXBlIjoid2ViX3NlcnZpY2VfYmluZGluZyIsInZlcnNpb24iOjF9LCJjbGllbnQiOnsibmFtZSI6ImtleWJhc2UuaW8gZ28gY2xpZW50IiwidmVyc2lvbiI6IjEuMC4xNiJ9LCJjdGltZSI6MTQ2Njg1NzM4OCwiZXhwaXJlX2luIjo1MDQ1NzYwMDAsIm1lcmtsZV9yb290Ijp7ImN0aW1lIjoxNDY2ODU3MzQ4LCJoYXNoIjoiNjM4ZGI0NjQ4ZWY3ZGI1YTNmOTVjZjFjNTlkNzYzYTgzYTMzMWU2YmViMWFlYTM2M2NiY2Q2YTZlZDNiZDk3YzZhNGM2MWQ1ZmQyMGM5NDc2OWU4YTI2NTRmMzU0ODk1ZGFmMjNjOTkzMjM3MmE2YjQ3ZTU4MzJkN2MxZDJjZTUiLCJzZXFubyI6NDk4NDc1fSwicHJldiI6ImU1YmFiYzU2ZjY2MjAzZDIwZTYxZDI4NTVkMzI0YTlkMjk0OGM3MWM0M2I1Y2I5YWU1MmFhYTIxZDI1ZDMyNTkiLCJzZXFubyI6MTEsInRhZyI6InNpZ25hdHVyZSJ9o3NpZ8RAL41qbUWPZWlpVBnu5lMSwdW3LMmklhaUOsQDTELcilb8dqf6jGTconJHKunh+w2xOEWaurK+ZhmPrvK3w2MqDahzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIIkbVFWIkCNQW6arwZC8td0/lPWyFIa0aqAr9J3rEkRmo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/bhaskarchowdhury

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id bhaskarchowdhury
```

Check Github now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] y
Couldn't find posted proof.
Check Github again now? [Y/n] 

What is going on?? Am I missing the obvious??

On one catch, I have my public key ,on my mail address and username on those site is different than mail id. But that mail ID is included in those accounts.

Shed some light.

**Comment by dtiersch** [comment]
I couldn't find the proofs in both your [Twitter](https://twitter.com/unixbhaskar) and [Github](https://gist.github.com/unixbhaskar) account. Did you delete them?

**Comment by unixbhaskar** [comment]
NOOOOOO...I am getting the same error on reddit too :( . First of all why it is asking again and again??? I am putting the correct username everytime with every service...wondering.

**Comment by dtiersch** [comment]
Sorry to ask, but _did_ you post the proofs in your accounts?

**Comment by unixbhaskar** [comment]
what do you mean by that? Can you please let me know the steps? Here is mine:

https://keybase.io/bhaskarchowdhury

**Comment by dtiersch** [comment]
You have to post the proofs by yourself. As told by keybase when trying to proof:

> Please publicly tweet the following, and don't delete it:
> 
> Verifying myself: I am bhaskarchowdhury on Keybase.io. 1KRf1S9kraKkhnucYFVDNf9kM4rMDXqyjLIk / https://keybase.io/bhaskarchowdhury/sigs/1KRf1S9kraKkhnucYFVDNf9kM4rMDXqyjLIk

and
> Please publicly post the following Gist, and name it keybase.md
>
> [...]

Keybase can't do that for you, because they cannot login as you. This would require Keybase knowing the login credentials and this is both not a good idea and also unwanted.

**Comment by unixbhaskar** [comment]
Yay!! gotcha!! my dull head prove again..thanks a bunch...honestly

**Comment by unixbhaskar** [comment]
Not happing :(

Twitter link: 
https://twitter.com/unixbhaskar/status/746699660262137858

and accept on the shell 

bhaskar@Fedora_19:08:36_Sat Jun 25:~> keybase prove twitter unixbhaskar
You already have a proof for unixbhaskar@twitter; overwrite? [y/N] y
Please publicly tweet the following, and don't delete it:

Verifying myself: I am bhaskarchowdhury on Keybase.io. AFNWUnGmdhP9Qx8j5xniJxjARW7iYSnV8Jgh / https://keybase.io/bhaskarchowdhury/sigs/AFNWUnGmdhP9Qx8j5xniJxjARW7iYSnV8Jgh

Check Twitter now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] y
Couldn't find posted proof.
Check Twitter again now? [Y/n] 

irk....:(

**Comment by dtiersch** [comment]
You left out the `Verifying myself: ` part. That is needed so that Keybase can find the tweet. Just post the whole thing again (you can delete the incomplete tweet) and Keybase should catch up on its own after a small waiting time

**Comment by unixbhaskar** [comment]
oooops...steep learning curve ..heck

**Comment by unixbhaskar** [comment]
Thanks! and appreciate your patience!! at last :) let me try with my other link too..

bhaskar@Fedora_19:16:22_Sat Jun 25:~> keybase prove twitter unixbhaskar
You already have a proof for unixbhaskar@twitter; overwrite? [y/N] y
Please publicly tweet the following, and don't delete it:

Verifying myself: I am bhaskarchowdhury on Keybase.io. hMSz8CFIrNPJrOl6yxCvMTGhIFcm6oXZmuj0 / https://keybase.io/bhaskarchowdhury/sigs/hMSz8CFIrNPJrOl6yxCvMTGhIFcm6oXZmuj0

Check Twitter now? [Y/n] y
▶ NOTICE Success!

**Comment by dtiersch** [comment]
Great :)
If your other proof now works as well, please close this issue to keep the issue tracker clean ;)

**Comment by unixbhaskar** [comment]
As we sorted out the problems. I am closing this thread.
