### ISSUE TITLE
Alternative to the system tray

### ISSUE THREAD

**Issue by Link-Satonaka** [keybase/keybase-issues#2313]
Hello! I do not have a system tray in my Linux environment, and so I cannot access the GUI! I know the GUI isn't done yet; are you planning on adding other ways to invoke the UI?

Thanks.

**Comment by cjb** [comment]
Hi -- our plan is for there to be a "main window" that allows you to do everything inside the app (not yet finished, coming soon), so I think you'll be mostly okay using that instead of the tray icon.

**Comment by Link-Satonaka** [comment]
Perfect, thanks
