### ISSUE TITLE
Permission denied when attempting to access KBFS

### ISSUE THREAD

**Issue by Spydar007** [keybase/keybase-issues#2315]
After mounting KBFS, I get:

```
spydar007@fr1 ~ $ cd /keybase/public/spydar007
-bash: cd: /keybase/public/spydar007: Permission denied
spydar007@fr1 ~ $ 
```
The same happens with any other folder in /keybase. 

Fuse is already installed and I am in the group, and I am logged in to Keybase, and have already tried `keybase unlock` with no success.

**Comment by cjb** [comment]
Please run `keybase log send`, thanks.

**Comment by Spydar007** [comment]
Apologies, I intended to do this before. 

Log ID: 2a381a93cbb12ad2dff7711c

**Comment by cjb** [comment]
You're getting permission denied trying to mount the fuse folder on /keybase.

**Comment by Spydar007** [comment]
Yes, but I think the main problem is the fact that I cannot connect to you:

`KeybaseDaemonRPC: connection error`

**Comment by strib** [comment]
@Spydar007 -- I don't see that message in the log you sent.  If you see it somewhere, it means the `keybase` service isn't running, but you could also see it temporarily when they both start up at the same time.

The bigger problem, as @cjb said, is that `/keybase` on your device is probably owned by a different user than what you're running `run_keybase` as.  Try `chmod $USER /keybase` (maybe with a `sudo`) and see if that helps.

**Comment by Spydar007** [comment]
@strib `chown` allows me to access the keybase directory, but not the public or private folders. These load indefinitely, because the mount is failing. Even if I attempt to `chown` the other folders, or recursively /keybase, it just infinitely tries to change into it.

Fuse is, as far as I am aware, set up correctly, because I do not have permission to mount /keybase in the first place. If I use `run_keybase` as root, I get the error mentioned previously.

**Comment by cjb** [comment]
The error is:
```
2016/06/27 09:04:49 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
```
It's hard for us to help remotely.  I think you might just have to try a bunch of things to fix the permissions.  You could try mounting a different FUSE fs, for example, to see whether the problem is with FUSE in general or Keybase.  G'luck!

**Comment by Spydar007** [comment]
I have attempted to install Keybase on Windows too, and dokan just says it "could not mount" it. Could it be something with my account/public key?

**Comment by zanderz** [comment]
Can you also do a `keybase log send` from your Windows installation? Thanks.

**Comment by Spydar007** [comment]
Log ID: abc0454dbec6fde747a9e31c

**Comment by zanderz** [comment]
Is there a chance drive letter k: was already assigned on your Windows system? If so, you can change the KBFS mount drive by setting KEYBASE_DRIVE_LETTER=M: in your global environment [or any other available letter, including colon] and rebooting.

If you are certain that drive letter K: is available, please check that the filesystem driver is running by issuing `SC QUERY dokan1` as administrator. Thanks!

**Comment by Spydar007** [comment]
Reassigning the drive letter fixed the issue on Windows. Thanks.
