### ISSUE TITLE
Use CMD to encrypt a message

### ISSUE THREAD

**Issue by dersoi** [keybase/keybase-issues#2316]
So I just installed the CMD keybase, and I wanted to try to encrypt a message, reading the instructions on the wiki. In the CMD are the things that I typed, and in when I hi enter for the lat command, the pop-up on the right appeared, and apparently, instead of preparing the message for gent1018, it prepared it for Matt Baer ...
![2016-06-27_22-11-58](https://cloud.githubusercontent.com/assets/6134706/16394388/38ecb8f2-3cb5-11e6-803c-623a1d91b649.jpg)

**Comment by maxtaco** [comment]
the instructions are wrong, you need double quotes rather than single quotes.  @malgorithms can you check this out?

**Comment by malgorithms** [comment]
I just changed the instructions on the live site...thanks for reporting.

**Comment by malgorithms** [comment]
Btw, if you catch anything else that's wrong in the docs on Windows, please let us know. Very few people have used Keybase in the Windows CMD so far.

**Comment by dersoi** [comment]
Whoa! Thanks for the quick response! I tried with double quote and it works. Thank you :)
