### ISSUE TITLE
The elephant emoji in bio removes everything after it.

### ISSUE THREAD

**Issue by svenluijten** [keybase/keybase-issues#2317]
This is such an oddly specific bug, but here we go. Inserting the elephant emoji (🐘) anywhere in your bio clears everything that comes after it. Here's a quick demo:

![keybase-emoji-bug](https://cloud.githubusercontent.com/assets/11269635/16397974/d7ede0fe-3cc7-11e6-9800-4d86f9cbf0b7.gif)

So far this is the only emoji I've encountered this bug with, though I haven't tried them all yet.

**Comment by zQueal** [comment]
This is just the coolest bug! It seems to be specifically reproducible exactly as described.

**Comment by strib** [comment]
@malgorithms: liberal bias?

**Comment by frantic1048** [comment]
Same here, but with rabbit emoji 🐰

**Comment by svenluijten** [comment]
@frantic1048 Keybase isn't animal friendly, it seems :stuck_out_tongue:

**Comment by malgorithms** [comment]
haha @strib 

It appears it's because we're using `utf8` in MySQL for the bio/profile fields - the following article describes the truncation:

https://mathiasbynens.be/notes/mysql-utf8mb4

hopefully we can get to this soon.

**Comment by malgorithms** [comment]
Thanks for your patience everyone...this is finally done:

https://keybase.io/chris

let me know if you see any issues, and if not, we can close this out...

**Comment by svenluijten** [comment]
Woo! 🐘

![screenshot](http://i.imgur.com/UJhh1cf.png)

**Comment by malgorithms** [comment]
excellent, gonna close this issue....
