### ISSUE TITLE
Unclear behaviour when using multiple user accounts on a Mac

### ISSUE THREAD

**Issue by tilmans** [keybase/keybase-issues#2322]
I am running 2 separate user accounts on my mac, one is for work and the other private. I've installed keybase on the private user account, when trying to start it from my work account I get the error below.
I can ignore this error, in that case I have to log in and then I'm offered the option to choose a device. 

What is unclear to me is if I should use the same device, even though it's a different account or if device also implies data in my home folder which would not be accessible from the other account. It would be great if the client could make this clearer. Maybe there's already some documentation on this scenario?

The error:

```
Installer: 1.1.31
Privileged Helper: Installed, Bundle Version: 1.0.27, Version: 1.0.27
Updater: Installed, PID: 7531
Service: Installed, Version: 1.0.16-20160627110020+11e6f10, PID: 7543
Fuse: Installed, Version: 3.2.0, Kext ID: com.github.kbfuse.filesystems.kbfuse, Kext Loaded: Yes, Path: /Library/Filesystems/kbfuse.fs
KBFS: Install, Install Error: stat /keybase: no such file or directory (kbfs), Not Installed, Bundle Version: 1.0.2-20160627110104+96f0df9
CLI: Installed

Log:
Installables: (
    "<KBHelperTool: 0x7fb048414110>",
    "<KBUpdaterService: 0x7fb04a95a2a0>",
    "<KBService: 0x7fb04a961e50>",
    "<KBFuseComponent: 0x7fb04a9620e0>",
    "<KBFSService: 0x7fb04a962f30>",
    "<KBCommandLine: 0x7fb04a963160>"
)
Install: Privileged Helper
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater
```

**Comment by cjb** [comment]
Yes, the device keys are stored in your home directory -- two devices seems like a good answer for you.

(We haven't spent any time at all optimizing for the use case of two users on the same machine, so you may hit more problems.)

**Comment by telekid** [comment]
This just tripped me up. Like @tilmans, I have one account for work and one account for pleasure. When running the Keybase app in two accounts, the second account can't access `/keybase`. Took a few minutes of head-scratching to figure out what was happening.

If this is unsupported behavior, then it might be a good idea to prevent the second user from launching Keybase with an explanation why.

**Comment by sfkleach** [comment]
The better solution is not to mount an individual user's /keybase outside of $HOME. If it has to be a central location /var/keybase/USERID would be fairly natural, with symlinks from $HOME.

**Comment by maxtaco** [comment]
We spent a fair amount of effort engineering around this problem and we've tested it to work pretty well. I'm going to close the issue. Feel free to reopen if it's still buggy.
