### ISSUE TITLE
Google Play Android app

### ISSUE THREAD

**Issue by rshipp** [keybase/keybase-issues#2325]
There's a "Keybase (Unreleased)" app on the Google Play store (https://play.google.com/store/apps/details?id=io.keybase.ossifrage), with the same namespace as the files in the client repo, but this app isn't mentioned anywhere I can find on the Keybase site. The developer email is "@keyba.se", not keybase.io. Is this app legit?

**Comment by cjb** [comment]
@MarcoPolo eek, looks like our unreleased app is released! Can you fix?

**Comment by cjb** [comment]
@rshipp In case it's not obvious, it's legit but unfinished :)

**Comment by rshipp** [comment]
got it, thanks :)

**Comment by MarcoPolo** [comment]
I'm curious to how you found it, did you just put our namespace into the id field in `https://play.google.com/store/apps/details?id={IDFIELD}` ?

**Comment by rshipp** [comment]
Nope, just searched "keybase" on the store.

**Comment by MarcoPolo** [comment]
@rshipp do you still see it?

**Comment by rshipp** [comment]
No, it just gives me a Not Found message now. :+1:
