### ISSUE TITLE
Unable to log in on osx app

### ISSUE THREAD

**Issue by nphase** [keybase/keybase-issues#2328]
Was just invited and logged in to the website, but when I try to log in on the osx app, the button is stuck spinning after typing in my username or email. I'm never given the option to enter a passphrase.

Thanks for your help!

**Comment by cjb** [comment]
Hi! Sorry about this, we've noticed it too. Please could you run `keybase log send`? 

As a workaround, you can type `keybase login` to log in using the terminal.

**Comment by nphase** [comment]
Sure! Where is the keybase binary located? It doesn't seem to be in my $PATH post install.

**Comment by cjb** [comment]
Huh! The weirdness continues. It should be in your $PATH. @gabriel, any ideas?

**Comment by nphase** [comment]
I went ahead and installed the cli from homebrew, and it all works now.

**Comment by gabriel** [comment]
Looks like the installer failed to run on your first app start?

The first time you started the app, did you get a dialog like this?

![image](https://cloud.githubusercontent.com/assets/2669/16672210/6fe90e04-4459-11e6-90c1-8bf70c46c33e.png)

If you install the app what is the output of the installer:

```sh
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

**Comment by gabriel** [comment]
If you are still having problems, here is a version with some enhancements around install:
https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160817191833%2Be83e8a5.dmg
