### ISSUE TITLE
"Possible revoked data detected" error

### ISSUE THREAD

**Issue by JaymesKeller** [keybase/keybase-issues#2333]
I'm getting an error that states the following:

"/keybase/public/jaymeskeller has been edited by a revoked or bad device. Use keybase log send to open an issue with the keybase admins."

So, I've done that, and the log id is: 6767a2d24a81a86968587b1c

**Comment by strib** [comment]
Hi @JaymesKeller -- looks like you reset your Keybase account on 6/26/16, and last wrote to your public directory before that, with a key from your pre-reset account.  Right now, the only easy option is to reset your public and private folders to a blank state (losing any data in them).

But we need your signed, public permission to reset those folders. If you want us to do that, please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/jaymeskeller and /keybase/public/jaymeskeller because I reset my Keybase account."
```

and post the output here. I can get to resetting them tomorrow.  Thanks!

**Comment by JaymesKeller** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsAEbLCc Su4bOif6m4xVYuB T8Y3PNG2mMfFLsr lIYA1LMutPe5T0h mjtRuXnQdTvkJcx O8pPNf7dv1a8FcX Ut2oTZYZaw9S5BU ZghWNPoFhJbMqEL ZHiKFJLtQMDcBLE fjXDyhxpr1gKqxT 592Ktpk96CGhrgX puDNO4HOS9GdimA x9shIChu1SK1KvS AlnAuPheJ7z3VOG LLczozExVuhCTfR JduvhMeIAR8954a dihPSx6rEciW1I6 oTd0tbkm746X4Sl H07oXaKrHUrBxft s7dBpUUzRugVNcy D4xHKj4i08df0OQ kkUXWZidYi6MKbN Z6Z98laH5FqSL1n 1E8ulZHgJGGlDd8 jCRESZvlqObkB2j 0DlKzQ6nFAQ42NP sEwTSRSGn7kRxvi GX7o9hk0EqIuw3E bK0gC7hdrbCtFGf sYN4pBe9yEARBA0 bri5KIvX0zjmNoc Jk. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok I reset your public folder. The private folder seemed new enough to not be broken, so I didn't bother with that one.  Please check them out and close this if everything seems ok.

**Comment by JaymesKeller** [comment]
All seems to be working fine. No errors.

**Comment by szaffarano** [comment]
Hi, Please, I also need to restart my public and private folder.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrxVBUdP ROrUbMM4yHcReGg SiSPitEBOT9zOXe AaSBnZRXxUgkc8c zCFflbafUoY3bkF x7tQwO4gnf98QTN ZB8PXC6zPhKkaQe BEiUcGIDbScHT5C Y5XMwvmKixY6Y0l hTiXunpjEApgYed 1xgM3kvg9uUqv8p jDSp7uIKagql9cl jJD72sRoMzm7gct OUvgpNylvwNI9QZ gqIOVnehkoGb9fz yM6OFRKQJG5IwRT U9qN6jN0RDxFNpN mwainWrYhC46KNm 7tH2eKPnP3LtsUR 0N6jN0RDzVM9PXz ouKZPdWJPfgBtDD KhKE5hsjbzkxPcR 7rk3g9q24q5t0MZ KZpRICs8pIzGIyw ZXbBZYyxnvSQFNp wfWZzBOF2mZfNTv vRut84Ww1xGMyL1 mFv73wCGho0rx6w 2jQulOZXfsg0DwU fU5DUsorEpBAMoq X485T6. END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you

**Comment by strib** [comment]
@szaffarano: please open a new ticket for your issue, since this one is closed and we'l probably lose track of it.  I'll get to the resetting on Monday probably.

**Comment by szaffarano** [comment]
Done (#2385)  
Thank you @strib !
