### ISSUE TITLE
keybase.pub is not working

### ISSUE THREAD

**Issue by neutrinog** [keybase/keybase-issues#2334]
I just noticed this morning that my pub dir is not working https://keybase.pub/da1nerd
![image](https://cloud.githubusercontent.com/assets/166412/16591884/e13493bc-4292-11e6-80d4-4c9218013563.png)

And it appears all other users cannot be found as well.

Another issue that may not be related is I cannot click to open any directories from the keybase client. And that new private shared one does not even exist on my file system.

![image](https://cloud.githubusercontent.com/assets/166412/16591978/5ed7aa52-4293-11e6-9f46-579cd03c92a3.png)

I'm running Debian 8 with keybase version 1.0.16-20160628170406+181ffc1

**Comment by strib** [comment]
Thanks for the heads up on keybase.pub.  It's restarted.

I think the GUI clicking issue is known and unrelated.  keybase/client#3240

**Comment by neutrinog** [comment]
thanks I updated to keybase version 1.0.16-20160630160045+c643773 and am able to receive shared folders now.
