### ISSUE TITLE
Twitter verification issue

### ISSUE THREAD

**Issue by bslatner** [keybase/keybase-issues#2347]
Using windows version (from Keybase CMD icon), I attempted twitter verification and received the following message:

```
C:\Users\bryans\AppData\Roaming\Keybase>keybase prove twitter bslatner
- WARNING Failed to register as a logger: The handle is invalid.
- ERROR The handle is invalid.
```

I ran the command a second time and it worked.

**Comment by maxtaco** [comment]
cc: @zanderz, can you attach this to the GH issue?

**Comment by owencook** [comment]
I also have a twittor failure. Permission denied! We can't support private feeds

[owen@localhost ~]$ keybase prove twitter
You already have a proof for xemoth@twitter; overwrite? [y/N] y
Your username on Twitter: xemoth
Please publicly tweet the following, and don't delete it:

Verifying myself: I am owencook on Keybase.io. Pig10fVPKAkY76Su_HNU3tnTW35SJ4-y0MYG / https://keybase.io/owencook/sigs/Pig10fVPKAkY76Su_HNU3tnTW35SJ4-y0MYG

Check Twitter now? [Y/n] 
Permission denied! We can't support private feeds.
Check Twitter again now? [Y/n]

**Comment by maxtaco** [comment]
By design.  We don't support private feeds and likely never will.  Either
make your feed public or don't link it.
