### ISSUE TITLE
KBFS on linux not streaming/syncing

### ISSUE THREAD

**Issue by fkautz** [keybase/keybase-issues#2354]
I am using 

```
Client:  1.0.16-20160630160045+c643773
Service: 1.0.16-20160630160045+c643773
```

I can see `/keybase` was created

```sh
$ cd /keybase/public/fkautz # fails
$ mkdir /keybase/public/fkautz
$ echo "hello" > /keybase/public/fkautz/hello
```

I cannot see anything on keybase.pub/fkautz

I tried sharing a test file with cmyers at `/keybase/private/fkautz,cmyers` but he was unable to see anything on his side, also using the latest alpha from today.

Let me know what I can do to help debug this issue.

**Comment by cjb** [comment]
Hi, please run "keybase log send".

**Comment by fkautz** [comment]
@cjb my log id: d5d544799f112751738b1c1c

**Comment by fkautz** [comment]
@cjb also got some warnings:

▶ WARNING error opening log "/home/fkautz/.cache/keybase/keybase.kbfs.log": open /home/fkautz/.cache/keybase/keybase.kbfs.log: no such file or directory
▶ WARNING error opening log "/home/fkautz/.cache/keybase/Keybase.app.log": open /home/fkautz/.cache/keybase/Keybase.app.log: no such file or directory
▶ WARNING error opening log "/home/fkautz/.cache/keybase/keybase.updater.log": open /home/fkautz/.cache/keybase/keybase.updater.log: no such file or directory
▶ WARNING error opening log "/home/fkautz/.cache/keybase/keybase.start.log": open /home/fkautz/.cache/keybase/keybase.start.log: no such file or directory

**Comment by cjb** [comment]
@fkautz did you type "run_keybase"?

**Comment by fkautz** [comment]
So, two things came up. First, run_keybase wasn't run. I now know to run it.

Second, when run_keybase was executed, it did not populate my directory. I had to delete everything in /keybase. Once /keybase was empty, I could execute run_keybase and it properly populated my directory.

So, one suggestion would be to throw an error when /keybase is not empty.

Thanks for your help!

**Comment by strib** [comment]
Glad it's working now, thanks for the follow up!
