### ISSUE TITLE
Twitter proof

### ISSUE THREAD

**Issue by Luca0208** [keybase/keybase-issues#2358]
https://twitter.com/ProgrammerLuca/status/751885807930187776

It doesn't work however

**Comment by tjchambers** [comment]
Are you luca_s or luca_a?

**Comment by Luca0208** [comment]
Luca_s is keybase and luca a is twitter

**Comment by zQueal** [comment]
Looks like you're missing `Verifying myself:` in the tweet. Not sure if it's required, though, but the scraper may use that phrase to identify proofs.

**Comment by Luca0208** [comment]
Worked, thanks.

But I could swear I just copied the whole tweet over from the command line.
