### ISSUE TITLE
Delete account and make new one

### ISSUE THREAD

**Issue by iFreilicht** [keybase/keybase-issues#2363]
As it's not possible to change the name of an account, I'd like to delete mine and make a new one. That was done a few times for other users already, can that be done still?

Apart from making a public key and verifying my twitter and github identity, I've done nothing with the account so far.

**Comment by iFreilicht** [comment]
Don't want to litter your issue queue with this.

**Comment by malgorithms** [comment]
hi @iFreilicht  - I was on vacation and missed this note....email me and I'll set you up, if you haven't done this already.

**Comment by iFreilicht** [comment]
I already sent you an email on 9th of July, should I send another one?

**Comment by malgorithms** [comment]
found it - working through email backlog today
