### ISSUE TITLE
config is not a Keybase user

### ISSUE THREAD

**Issue by mhykes** [keybase/keybase-issues#2367]
I installed the latest version of keybase on Windows 10 last week.
I have been testing KBFS.
I have successfully created shared private folders and see edits to a text file shared between people.

However, ever since I installed this version, I keep getting a notification in the bottom right corner that says 
```
Keybase: User not found
config is not a Keybase user
```
This happens most often when I am navigating the K: drive that was added by KBFS.

Although I have folder options set to show everything, including hidden and system files and folder, I see no sign of a folder or file named config anywhere on the K: drive.

Please let me know if there are any troubleshooting steps you would like me to apply.

Thank you.

**Comment by strib** [comment]
Thanks for the report!  Closing as a dup of keybase/client#3158.

**Comment by mhykes** [comment]
Thanks, strib.
This does seem to be a duplicate of that issue.

I was careful to search for my issue title before submitting this, and didn't find that issue.  I wonder how I missed it.
