### ISSUE TITLE
File reading from kbfs folder

### ISSUE THREAD

**Issue by pie-flavor** [keybase/keybase-issues#2370]
This may occur with other types of files, but right now, I can't open video files in VLC because "Bad file descriptor". No such error occurs if I copy the file locally.

**Comment by strib** [comment]
Thanks for the report.  It would help if you could run `keybase log send` from the kbcmd prompt and let us know the resulting ID, so we could check out the logs.

**Comment by pie-flavor** [comment]
@strib 8eef635fa9e1db4bc907ec1c

**Comment by strib** [comment]
Thanks! Do you remember about how long before you filed this issue you experienced the problem?  I can't find any errors reading a video file in the log, so knowing a more exact time might help me narrow it down.
