### ISSUE TITLE
Stop keybase from starting on system start?

### ISSUE THREAD

**Issue by bwarren2** [keybase/keybase-issues#2380]
I am on Ubuntu 14.04, have nothing in `/etc/xdg/autostart/` or Startup Applications for keybase, and yet on every system start I am prompted for my keybase password as keybase starts.  There appear to be no useful settings for startup management in keybase itself.  How can I stop this?

**Comment by obijan42** [comment]
Same here on OSX El Capitain.
Expected behavior:  Being able to control startup in User preferences.

**Comment by cjb** [comment]
@bwarren2 Hi, try commenting out the final line of:
```
~/.config/autostart/keybase_autostart.desktop
```

**Comment by bwarren2** [comment]
Works perfectly.  Thanks!

**Comment by jakerobers** [comment]
I don't have a ~/.config/autostart folder, but it may be because I am on Yosemite. Also checked `/Library/StartupItems` and `/System/Library/StartupItems`, but couldn't find anything.

**Comment by braimee** [comment]
Yeah I've got the same issue as @jakerobers.  I'm on a Mac (10.11.6) and can't seem to disable Keybase from firing up on login.  I've got nothing in Login Items in System Preferences and nothing in `/Library/StartupItems` or `System/Library/StartupItems` either.  Am I missing the obvious here?

**Comment by mifix** [comment]
As far as I know, there isn't any userfriendly configuration yet.

On OS X, in your terminal run:

```bash
cd ~/Library/LaunchAgents; launchctl unload keybase.*; mv ./keybase.* ~/Desktop; launchctl unload /Library/LaunchDaemons/keybase.Helper.plist; sudo mv /Library/LaunchDaemons/keybase.Helper.plist ~/Desktop
```

(As a backup, the plists are moved to your Desktop)

**Comment by phlebotinum** [comment]
Just realized there is no option. INSTANT UNINSTALL. Let me know when your marketing strategies grow up.

**Comment by zQueal** [comment]
> Let me know when your marketing strategies grow up.

Keybase is FOSS. Not exactly sure how ensuring software which may be used during a session is properly started equates to shady "business" practices and marketing ploys... But if you have that much of an issue with it, you could always submit a pull request implementing this feature.

But is it honestly __that__ difficult to simply disable via the system without a built-in mechanism for it in the installer? What if a user disables it at startup and wants to re enable it? Or the inverse of that? Selectively users already need to know how to enable or disable startup options to ensure Keybase works for them. Not sure why it's ridiculous to you that a disable feature isn't included in the installer in beta community driven software.

**Comment by phlebotinum** [comment]
ok. i am an idiot.

**Comment by zQueal** [comment]
Keybase as a company received $10.8M in [series A funding](https://en.wikipedia.org/wiki/Series_A_round) (venture capital) from which they hope to eventually develop a product which can be used for team based collaboration and hosted solutions--possibly for a corporate environment;

> some people may turn to us for more advanced, hosted solutions. That could be anything from team management (in the enterprise) to hosting of public, signed files.

Keybase as a consumer product is likely to never change--by which I mean __F__OSS. So yes, it absolutely is a product, but "marketing" when used the way you did is nothing more than a knee-jerk term (IMO) used to imply distasteful or surreptitious advertising on the same level of Symantec (once you install you physically can't uninstall without a special tool) or something.

I'm not trying to call you out here or anything, but I'm trying to understand why you would think that the lack of startup options immediately mean something malicious or underhanded--especially so when dealing with beta software--even more so when you can manually disable launch at startup with ease.

**Comment by phlebotinum** [comment]
I overreacted initially. VC needs no explaining. It might not be on purpose on their side. These days i have zero tolerance for anything with the slightest appearance of not being ultra user service oriented and basically "old school" decent behavior / new school "ethical software". Anybody putting decent behavior first will get me as a paying customer easily. Everyone else gets the backlash after years of RealPlayer, Facebook privacy settings, etc...

**Comment by lvh** [comment]
`keybase uninstall --components service` appears to uninstall the LaunchAgent.

**Comment by dmiddlecamp** [comment]
hitting this as well, I tend to uninstall apps that don't let me control their startup behavior...

**Comment by nicjansma** [comment]
I'm frustrated I can't control this from the UI.

On Windows, I have to remove the _two_ start menu links (`AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`) via AutoRuns, and somehow, Keybase just popped up again (long after a Windows reboot) _and_ readded its links.

![image](https://cloud.githubusercontent.com/assets/1004649/22216735/3f32c310-e16e-11e6-8b94-974102c8abf9.png)

This kind of option needs to be controllable via the UI, or you will likely get users like myself and others in the thread who will simply remove it.

**Comment by rodimius** [comment]
Honestly you don't get a chance on this one, programs re-enabling themselves get uninstalled.

**Comment by zanderz** [comment]
@nicjansma The app does not re-write those startup shortcuts, they are only made at install time. What most likely happened is a silent update. Note that the first time the update option is shown, there is a checkbox, on by default, which says to update silently next time.

You could edit updater.json and turn auto updates back off to avoid silently re-installing those links, but there is no friendly gui to prevent running at startup.

**Comment by jackcasey** [comment]
Seems like this could do with re-opening. 
I've had to uninstall on windows. Not due to some moral high ground or anything, but just the fact that my keybase filesystem (including /private/) is mounted and accessible automatically when my windows PC starts up. No password or anything. I really can't have that :(

**Comment by zanderz** [comment]
@jackcasey If you log out of Keybase, the filesystem will not be accessible.

**Comment by jackcasey** [comment]
@zanderz I have the same issue on my macosx machine. There is no 'logout' option. It seems I can either have my /keybase/private accessible on system start (with no password prompt even), or I can uninstall the app?

**Comment by zanderz** [comment]
At the command line (`Keybase Shell` on Windows), issue `keybase logout`. Then the filesystem will be inaccessible at reboot until you log in again.

**Comment by josephg** [comment]
@zanderz That makes the files inaccessible but doesn't solve the problem. The keybase app is based on electron, so it has a huge (chrome sized) memory footprint and idle CPU use. I only open chrome & friends when I'm plugged in because battery life is important to me. Leaving keybase running but logged out just makes that memory & cpu wasted.

**Comment by banool** [comment]
Any progress on this? None of the solutions posted here worked for me on MacOS High Sierra, nor those from https://github.com/keybase/client/issues/3904. This and the lack of 2FA are big deterrents from me properly using keybase.

**Comment by sean9999** [comment]
i'd like to write a GUI client in something less heavy than electron. Any interest?

**Comment by austinheap** [comment]
Two years in and you still can't disable the autostart on this?! 🤔

**Comment by maxtaco** [comment]
on Linux? you can.  cc: @oconnor663

**Comment by patrickxb** [comment]
macOS:

System Preferences -> User Preferences -> Login Items, remove keybase

after that, keybase won't start when you boot your computer.

There have been 1 or 2 rare reports that that doesn't work for some people, we have been unable to reproduce it.  The above works for me on several devices.

**Comment by quanticle** [comment]
Why is this issue closed? I'm on Windows, and Keybase still starts up on system login, even though I have the "Open Keybase on startup" option unchecked, under the "Advanced" preferences.

**Comment by thenaturalist** [comment]
macOS:

Any time I launch keybase again, it automatically adds itself to the Login Items. This is infuriating.

**Comment by maxtaco** [comment]
Hmm, thought we fixed this, but there's a race condition we never got to the bottom of.

Cc: @patrickxb

**Comment by oconnor663** [comment]
It seems like something regressed recently. I got a report about this from another friend of mine who uses Windows.

**Comment by patrickxb** [comment]
I didn't make any changes for Windows.  

@chrisnojima made most recent fixes in this area, including adding the checkbox to preferences.  I'm not sure if his work affected windows or just macOS.

**Comment by chrisnojima** [comment]
The fix for windows and osx should be in the next release. We merged a fix 20 hours ago : https://github.com/keybase/client/pull/10338

**Comment by abdulhannanali** [comment]
why are people so bummed about an application that is just trying to load first so it can be available on time. One upside to it is, that Electron based apps have a bit of startup time, so this ensure that Keybase is already there. If anyone took all the time and trouble to install an app and then sign up it means the user wants the app. 

We know people majority doesn't stay on websites longer than 3 seconds. Keybase's goal is to make secure communication easier and I think it's okay if it starts up earlier.  Although I am here to disable but it's not the only application that starts up on boot. 

Nobody would have put the blame on marketing strategies and stuff if it was a not for profit thing, but that doesn't take us anywhere in making open source sustainable. People love keybase and if they want to pay for their food while they make a FOSS product, please let them do it it's their right.

Companies like Keybase provide us a space to speak out, share concerns and feedback, so let's use that power positively instead of putting all the blame on their Marketing strategy, save it for Apple please.

**Comment by josephg** [comment]
@abdulhannanali because every electron app uses heaps of RAM. At least amongst firefox users, 4GB of ram is the most common ram size. So using 500mb - 1gb of ram for an app that the user isn't even using at the time is a huge cost. If you like, you can think about it as an accessibility problem. By having high RAM costs, you're making your app inaccessible to poor people.

Also, many electron apps also sit at 1-5% CPU all the time, even when the user isn't interacting with the app. Because of the way modern power saving features work, this dramatically decreases battery life.

I'm happy for people to selectively pay this cost, and I applaud the effort put into keybase. But electron + autostart-at-login is a dealbreaker for me as a user.

**Comment by Hexawolf** [comment]
No, shit, starting a Electon application makes no sense. Just stop arguing and accept that this is **horribly wrong** behavior that makes **no sense**. Seriously, you are talking even worse than Microsoft. This is open-source, and if people demand to have choice - you give them it, stop spreading cancer. Period.

**Comment by joaovarelas** [comment]
Keybase was supposed to assure user privacy & security but in the end it is doing the _opposite_.

- Cant block or remove users
- Software automatically runs on startup (without asking)
- The account "reset" is not an actual reset.

**Comment by clayt0nk** [comment]
Wow, 2019 and this is still an issue. I just spent over an hour, and I STILL cannot stop keybase from starting. I am not a Linux newbie, by a long shot.

**Comment by Asday** [comment]
Wait why is this issue closed?  This is ridiculous.

**Comment by TACIXAT** [comment]
I uninstalled today. Why is there no simple option of "don't start at startup" in the app? I don't need to dick around with disabling services and stopping the desktop app. Encrypted git is cool, but not worth an app that doesn't offer user control.

**Comment by patrickxb** [comment]
There is on Settings -> Advanced:

<img width="893" alt="Screen Shot 2019-03-27 at 12 45 11 PM" src="https://user-images.githubusercontent.com/2508/55099715-3a960880-508e-11e9-93b8-4fc05d8be9d2.png">

**Comment by clayt0nk** [comment]
That "Open Keybase on startup" tick box does not appear on my Linux version of keybase, straight out of the keybase debian repo: Version 3.1.2-20190312133549.4c383e6a53 (which I had to dig out of the packaging system, software version seems nowhere to be found in the Keybase UI). I do not recall every having seen such an option, and I have looked more than once.

**Comment by heronhaye** [comment]
On Linux, the standard way is to disable it from your DE's startup manager (Gnome: https://askubuntu.com/questions/37957/how-do-i-manage-applications-on-startup-in-gnome-3, KDE: https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/autostart/index.html).

Alternatively, we provide a convenience function to do this in the CLI:

```
keybase ctl autostart --disable
```

If this doesn't work, let us know, thanks!

**Comment by toxik-io** [comment]
`keybase ctl stop` would be a lovely option to have in the GUI, as would disabling autostart...

**Comment by tobypinder** [comment]
> why are people so bummed about an application that is just trying to load first so it can be available on time. One upside to it is, that Electron based apps have a bit of startup time, so this ensure that Keybase is already there. If anyone took all the time and trouble to install an app and then sign up it means the user wants the app.
> 
> We know people majority doesn't stay on websites longer than 3 seconds. Keybase's goal is to make secure communication easier and I think it's okay if it starts up earlier. Although I am here to disable but it's not the only application that starts up on boot without asking me for it. I am finding a way to disable each of those to speed up my boot times.
> 
> Nobody would have put the blame on marketing strategies and stuff if it was a not for profit thing, but that doesn't take us anywhere in making open source sustainable. People love keybase and if they want to pay for their food while they make a FOSS product, please let them do it it's their right.
> 
> Companies like Keybase provide us a space to speak out, share concerns and feedback, so let's use that power positively instead of putting all the blame on their Marketing strategy, save it for Apple please.

The UX argument goes both ways. There's a discussion to be had about the sensible defaults, but the fact that the consumer product does not have a "Open Keybase on Startup" on linux (or even a link to the cmd line docs within the product) is disappointing and contributes significantly to the frustration here, especially when many users are in RAM constrained environments etc.

I would suggest that the appropriate links to the Linux User Guide (`keybase ctl autostart --disable`) command is documented directly within the advanced options panel in the short term, and that potentially the client is updated to support direct manipulation of this value in future - this would completely alleviate people's concerns in my opinion, and mirror the behaviour of other electron-style apps (Slack, Discord etc)

**Comment by navin09** [comment]
Thank you, @toxik-io  and @heronhaye for the stop and disable autostart commands. This is indeed a frustrating "feature".

**Comment by heronhaye** [comment]
`ctl stop` is now available in the GUI by clicking your username at the top left -> Quit Keybase.

**Comment by toxik-io** [comment]
keybase fs still running in the background when you killed keybase was always a fun thing to keep me up at night....

**Comment by heronhaye** [comment]
@toxik-io Does this still happen? It was fixed recently. Could you reproduce and make another issue?

**Comment by oliverbienert** [comment]
This does not work:
`keybase ctl autostart --disable`
Ubuntu 18.04, Plasma Desktop
`keybase --version`
keybase version 4.2.1-20190718132443+117e8ce562

After issuing the above command, there are now 2 desktop files in the autostart folder:
`keybase` and `keybase_autostart`
Is that correct?

I also tried to put an `-a` to the command in the desktop file:
`Exec=XDG_CURRENT_DESKTOP=Unity /home/oliver/bin/start_keybase.sh -a`
but to no avail.
Should I open a new issue?

**Comment by heronhaye** [comment]
@oliverbienert That's odd, `keybase.desktop` should not be in that folder. Please make a new issue if it reappears or if you have other issues with autostart.

**Comment by oliverbienert** [comment]
As I mentioned, in the past I had this issue with an oversized keybase tray icon in KDE/Plasma. The solution someone posted was to set `XDG_CURRENT_DESKTOP=Unity`, so I don't know if by chance I put the desktop file in this folder deliberately.
I'll let you know when something unusual happens. As of today, everything runs fine.

**Comment by LucasAndrad** [comment]
> There is on Settings -> Advanced:
> 
> <img alt="Screen Shot 2019-03-27 at 12 45 11 PM" width="893" src="https://user-images.githubusercontent.com/2508/55099715-3a960880-508e-11e9-93b8-4fc05d8be9d2.png">

**No there isn't:**
![keybase_settings](https://user-images.githubusercontent.com/17948392/61889019-13840200-aedb-11e9-9703-ba23be78569f.png)

**Comment by rubo77** [comment]
there is on Ubuntu 19.10 with keybase version 5.1.1-20191211223501+15bbb94c23

![Bildschirmfoto von 2020-01-21 17-23-18](https://user-images.githubusercontent.com/1591563/72822736-e5f1f880-3c72-11ea-9e9c-337ca996d5bd.png)

**Comment by wkarshat** [comment]
On Windows, the program surreptitiously re-enables **explicitly disabled** startup commands in the registry, which result in five processes running in the background. Specifically, the keys:
HKCU:Run	Keybase.Keybase.GUI
Startup User	KeybaseStartup.lnk

For me this is a deal breaker, even Adobe does not do such any longer...

@bwarren2, why did you close this Issue, are you happy with this situation, three years later??

**Comment by Asday** [comment]
> the program surreptitiously re-enables explicitly disabled startup commands in the registry, which result in five processes running in the background

Isn't that what viruses do?

**Comment by belarm** [comment]
Sounds like the safest thing to do is just uninstall it.

**Comment by belarm** [comment]
> Keybase as a company received $10.8M in [series A funding](https://en.wikipedia.org/wiki/Series_A_round) (venture capital) from which they hope to eventually develop a product which can be used for team based collaboration and hosted solutions--possibly for a corporate environment;
> 
> > some people may turn to us for more advanced, hosted solutions. That could be anything from team management (in the enterprise) to hosting of public, signed files.
> 
> Keybase as a consumer product is likely to never change--by which I mean __F__OSS. So yes, it absolutely is a product, but "marketing" when used the way you did is nothing more than a knee-jerk term (IMO) used to imply distasteful or surreptitious advertising on the same level of Symantec (once you install you physically can't uninstall without a special tool) or something.
> 
> I'm not trying to call you out here or anything, but I'm trying to understand why you would think that the lack of startup options immediately mean something malicious or underhanded--especially so when dealing with beta software--even more so when you can manually disable launch at startup with ease.

And that's why, despite my desperate need for an end-to-end encrypted chat app, I'll be uninstalling keybase. Thanks.

**Comment by gravyplaya** [comment]
This works for me on Mac OS Catalina. (copied from above)
$ keybase uninstall --components service
▶ INFO Removing /Users/geo/Library/LaunchAgents/keybase.service.plist
▶ INFO Waiting for keybase.service to exit...
▶ INFO Stopped keybase.service
▶ INFO Nothing to stop (homebrew.mxcl.keybase)
