### ISSUE TITLE
Error after reset my keybase account

### ISSUE THREAD

**Issue by szaffarano** [keybase/keybase-issues#2385]
Today I reseted my keybase account, after that I get the error "Possible revoked data detected" when I try to add files to my public folder.   I saw the same error in #2333, please can you restart my public and private folder.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrxVBUdP ROrUbMM4yHcReGg SiSPitEBOT9zOXe AaSBnZRXxUgkc8c zCFflbafUoY3bkF x7tQwO4gnf98QTN ZB8PXC6zPhKkaQe BEiUcGIDbScHT5C Y5XMwvmKixY6Y0l hTiXunpjEApgYed 1xgM3kvg9uUqv8p jDSp7uIKagql9cl jJD72sRoMzm7gct OUvgpNylvwNI9QZ gqIOVnehkoGb9fz yM6OFRKQJG5IwRT U9qN6jN0RDxFNpN mwainWrYhC46KNm 7tH2eKPnP3LtsUR 0N6jN0RDzVM9PXz ouKZPdWJPfgBtDD KhKE5hsjbzkxPcR 7rk3g9q24q5t0MZ KZpRICs8pIzGIyw ZXbBZYyxnvSQFNp wfWZzBOF2mZfNTv vRut84Ww1xGMyL1 mFv73wCGho0rx6w 2jQulOZXfsg0DwU fU5DUsorEpBAMoq X485T6. END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you

**Comment by strib** [comment]
Ok, those folders should be cleared out now.  Please close this if things look ok.  Thanks!

**Comment by szaffarano** [comment]
Thanks! everything is ok
