### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by ringvold** [keybase/keybase-issues#2393]
Hi

I would like to change my username, but it seems not to be possible as far as I can tell.
Is there any way I can change to another username (preferably without loosing the invites)?

Thanks. :)

**Comment by malgorithms** [comment]
email me and I'll hook you up. you'll have to delete your account and redo your proofs, since usernames aren't actually changeable. But I can replace your invites.

**Comment by flyingoctopus** [comment]
Hi, I would like to do the same if possible. Thanks!
