### ISSUE TITLE
no tailer found (Very Urgent!)

### ISSUE THREAD

**Issue by tomguim** [keybase/keybase-issues#2405]
I looked at the other posts about this error, and it seemed to be parse errors but I believe i have tried all the combinations of formatting. I am still getting "Error: no tailer found". Am i missing something? Please help this is extremely urgent.

`-----BEGIN PGP MESSAGE----- Version: GnuPG v2.0.14 (GNU/Linux) hQEMA1bCchW1O9etAQf+OX1ijMNXaTXMtf4rjYUsHGTLplKxhCs7HL5YaD2LobtI 8V4OSVDg4N8uANohowNIPKmQivw3DhTq4jDnMDoMfj32c7SBI12XpeBnUsRArZwz NLiUmE//HhrdtkLCdLw8moohNkXAxvh12Tbpal+HIauf8ixfklUT74ASVteItwDu +bf76u3NnRlaEwqNHaZKwJKycXI4w1My1nnqDEZ2vgFfaO5vthzaFWWHbk+6IMWb QXK2z8muMfVsnAGm2omti2uJ+iyEQQPCpwf72XbbHQ8s+/uYYLVQkuZLlaJiWMB4 VfvxrmV++vXjATqd3Y25RNPytBd2Qa4+grr2UP61m9LpAVaV4NffXKYPpp3gR/OM xlMrWc5DAeYKNuLoI7TS1o1mVcxjNY7t6SIdgQFqw3pCvHLD8O0PPysa+BO1Tivr miv14eVPDa9N0Mphjbr8dFZ/2INqeU78T+YILYExErt9q8yZ8T23Hj4UQHaGd/Ga I84h++bzUOT/87vjfAUxi6fIBkAORM4Eo/nsFbdaD8pb0PeN087TZA/GbnE1/8VT smYOiLuD9INaW6T9yGg/FGT8hmeYg4ZrASiCpqWwy8W/b+1EI7JCcAitwDQFLFIY 2/HiHKIkVCmiCQWFcX00A83+yJsk/KSTGO9P5jaeifjYjEiuiwmmU56aoih1LDAM IR8oPdX0lLa00mplGDhcfyT8ULhcKSevHrgZQjJ1dITWbU2BEd3Rjwowe+owy0Lf 6d/S8q/AOCt/7rgcNzA26TSc+vnC/0l9FpAO3KBUDFRh/ZucC35aOQif6/GIdsNu /tkCnZoFsB0XQiz8ZpKAfTvMjziJf09eBON9y/LyFgulOQfihbYvNQoV9+hCcIT6 6qaOfSe3ty8Sea9aK+nE9x2dVW4zD5r7t+uu0UKG8kvES/wCe0+LqPHcqljcvACA pbB8i7PQenI8nRs2mex158iqp3HC7oOFLsWO82TQPVI4z76+gTKsyS2UgqUFEzu7 bh22J6PmB4VHZlfog+0At6K8A2uK1SbRqAZkcxVnYwD/8lJuvNtCSIuKpBm3TNAt ukpFh0hvkFIdUzv0UoSBfo4JUAHBFwfwD7bAfVDB03p6n38U/apL5qXTPcQJUWVw T70qnc/e2UcVWW8o8fsco3r/NjuU+suNAmqyQyEGYrCDH6rKTpQSQH7kiZseShrt wAr7G+TpBuaIvYAVyHS989X5Cpnnq6Cavp1jrP9ES9UBPmGhPQwuYUZTGML79NNc uf5BnBvOq98A0xk//GA= =dIh8 -----END PGP MESSAGE-----`

**Comment by maxtaco** [comment]
Your formatting is wonky. Try this instead:

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v2.0.14 (GNU/Linux) 

hQEMA1bCchW1O9etAQf+OX1ijMNXaTXMtf4rjYUsHGTLplKxhCs7HL5YaD2LobtI 
8V4OSVDg4N8uANohowNIPKmQivw3DhTq4jDnMDoMfj32c7SBI12XpeBnUsRArZwz 
NLiUmE//HhrdtkLCdLw8moohNkXAxvh12Tbpal+HIauf8ixfklUT74ASVteItwDu 
+bf76u3NnRlaEwqNHaZKwJKycXI4w1My1nnqDEZ2vgFfaO5vthzaFWWHbk+6IMWb 
QXK2z8muMfVsnAGm2omti2uJ+iyEQQPCpwf72XbbHQ8s+/uYYLVQkuZLlaJiWMB4 
VfvxrmV++vXjATqd3Y25RNPytBd2Qa4+grr2UP61m9LpAVaV4NffXKYPpp3gR/OM 
xlMrWc5DAeYKNuLoI7TS1o1mVcxjNY7t6SIdgQFqw3pCvHLD8O0PPysa+BO1Tivr 
miv14eVPDa9N0Mphjbr8dFZ/2INqeU78T+YILYExErt9q8yZ8T23Hj4UQHaGd/Ga 
I84h++bzUOT/87vjfAUxi6fIBkAORM4Eo/nsFbdaD8pb0PeN087TZA/GbnE1/8VT 
smYOiLuD9INaW6T9yGg/FGT8hmeYg4ZrASiCpqWwy8W/b+1EI7JCcAitwDQFLFIY 
2/HiHKIkVCmiCQWFcX00A83+yJsk/KSTGO9P5jaeifjYjEiuiwmmU56aoih1LDAM 
IR8oPdX0lLa00mplGDhcfyT8ULhcKSevHrgZQjJ1dITWbU2BEd3Rjwowe+owy0Lf 
6d/S8q/AOCt/7rgcNzA26TSc+vnC/0l9FpAO3KBUDFRh/ZucC35aOQif6/GIdsNu 
/tkCnZoFsB0XQiz8ZpKAfTvMjziJf09eBON9y/LyFgulOQfihbYvNQoV9+hCcIT6 
6qaOfSe3ty8Sea9aK+nE9x2dVW4zD5r7t+uu0UKG8kvES/wCe0+LqPHcqljcvACA 
pbB8i7PQenI8nRs2mex158iqp3HC7oOFLsWO82TQPVI4z76+gTKsyS2UgqUFEzu7 
bh22J6PmB4VHZlfog+0At6K8A2uK1SbRqAZkcxVnYwD/8lJuvNtCSIuKpBm3TNAt 
ukpFh0hvkFIdUzv0UoSBfo4JUAHBFwfwD7bAfVDB03p6n38U/apL5qXTPcQJUWVw 
T70qnc/e2UcVWW8o8fsco3r/NjuU+suNAmqyQyEGYrCDH6rKTpQSQH7kiZseShrt 
wAr7G+TpBuaIvYAVyHS989X5Cpnnq6Cavp1jrP9ES9UBPmGhPQwuYUZTGML79NNc 
uf5BnBvOq98A0xk//GA=
=dIh8
-----END PGP MESSAGE-----

**Comment by tomguim** [comment]
@maxtaco For future reference how did you do that?

**Comment by tomguim** [comment]
@maxtaco I am very sorry to ask you again but this is really an emergency :)

-----BEGIN PGP MESSAGE----- Version: GnuPG v2.0.14 (GNU/Linux) hQEMA1bCchW1O9etAQgAsVas5+h+V1Q3Iibhuy4v8ZUj4yiWcK7z7tdp1sw+zzLu Ssw6SXPw6G2JygWMH6QGaXhjPCEQuFSOwO+M2ZMmUecvDl3IUXGquYE9CH2snmJg 3FIkdfhlXPVk4hXReBPdxThgjZESnP7hNnFtgNwBDgDq9a9NR4mYMT/E7Q/tqcys l+ne5StczOheNc7iUCOvUrKqQ647+FZ25vsiLl0B667Ce6UecZ45OqJP8ydiGfKJ 6y03XWE9OtkdDlPWSRxKdGYP7aMtBk9iljBsIcNyRiGc2G9AZh3H0r2GewAXcTi6 VUwOVnmLivzcYgw4w181TMZZl0OQ7eEaUeQ6CDara9LpAcKrbg5TgHmaXiA6jYFQ +WesdT7+4HioOY5id2oNJP+S/2Edav5Fr1WK80TYKLyeTM1OW0YQIG0vI9rzJDHM atO3njRqu+iiDmt20UR3XqaTawwxDFSsU/z+MbZEwYyt4inKog2EcxA6oS1RE/ba sO10PWc2txxbL3qh+u2NdiH9cutyJ8CcVtMctl0NiufIlCAxs5vmDcSo0gLqAfqY JC/5gRAVUNAfp9/fpyWvR2XA5xU+/U/NLlBZZlJrjSrTjetWLInnSrZLsANWlaee 7aDrAbz+3ZjSrJpiNGh+nXsdjNA7tWncibWFkHU7zl40DMoRlLShVfSDlf9NpLXt Gkt9ryX9RkoV+yQxA4ajegYEKnht0aQyNOPjjRHQPQql2eSqyYz9ZNfKXmiaw8PI Tp7v/T0b47uEOZBYjGJvv8SqG3h8tL8s3WBR9Equ2DfPyg5GpGZGrDYd+gCiRA0o Nuv6WBy56OPY8cJBlrWEpLQ65eFzBj4Ts0PrtaOxwIXRdDt0ihAU8qs5icAoVgcR FdbcXGUAV7GfspgePNX1n4lBVrmBBZJGNZyq3tdzhf2h75J7xoT8bsGkxJyZXPQE 1/UM/Kn2dC5EB1emN6omwtTMouFaBP+MEMZUZKHZl/e69TQV5B9KNsbuJyBrHXlF dOCygXXQc6LScsr3oO55NKy+96zUaRg7v0V2eT3Peq7751iZKej4RunX39YdnbDz 9qaRskYUPqfhLxesXho8wXH9qs72OYNGqplhx51hOX4ScntCmIC6PMUX1BfUGt2/ xqDG3c/IzOWIJ7sqTGn/huAADdWWzpTiK6p1PKkCBUqLV/WamVmKxpJ5WA+0pfr7 jxmVUBicaJHGLaB6cBiPdMPs/wjNH3XQNwawEUsVYAwH45qGjWtsW8JBJ1VSO45o boE1DmWLXy3zhRl+aTZ4TA== =wSgb -----END PGP MESSAGE-----

**Comment by maxtaco** [comment]
Just use a text processor program and put newlines where you have spaces.  However you are receiving these messages, it's converting newlines to spaces, but PGP doesn't like that.

**Comment by maxtaco** [comment]
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v2.0.14 (GNU/Linux)

hQEMA1bCchW1O9etAQgAsVas5+h+V1Q3Iibhuy4v8ZUj4yiWcK7z7tdp1sw+zzLu 
Ssw6SXPw6G2JygWMH6QGaXhjPCEQuFSOwO+M2ZMmUecvDl3IUXGquYE9CH2snmJg 
3FIkdfhlXPVk4hXReBPdxThgjZESnP7hNnFtgNwBDgDq9a9NR4mYMT/E7Q/tqcys 
l+ne5StczOheNc7iUCOvUrKqQ647+FZ25vsiLl0B667Ce6UecZ45OqJP8ydiGfKJ 
6y03XWE9OtkdDlPWSRxKdGYP7aMtBk9iljBsIcNyRiGc2G9AZh3H0r2GewAXcTi6 
VUwOVnmLivzcYgw4w181TMZZl0OQ7eEaUeQ6CDara9LpAcKrbg5TgHmaXiA6jYFQ 
+WesdT7+4HioOY5id2oNJP+S/2Edav5Fr1WK80TYKLyeTM1OW0YQIG0vI9rzJDHM 
atO3njRqu+iiDmt20UR3XqaTawwxDFSsU/z+MbZEwYyt4inKog2EcxA6oS1RE/ba 
sO10PWc2txxbL3qh+u2NdiH9cutyJ8CcVtMctl0NiufIlCAxs5vmDcSo0gLqAfqY 
JC/5gRAVUNAfp9/fpyWvR2XA5xU+/U/NLlBZZlJrjSrTjetWLInnSrZLsANWlaee 
7aDrAbz+3ZjSrJpiNGh+nXsdjNA7tWncibWFkHU7zl40DMoRlLShVfSDlf9NpLXt 
Gkt9ryX9RkoV+yQxA4ajegYEKnht0aQyNOPjjRHQPQql2eSqyYz9ZNfKXmiaw8PI 
Tp7v/T0b47uEOZBYjGJvv8SqG3h8tL8s3WBR9Equ2DfPyg5GpGZGrDYd+gCiRA0o 
Nuv6WBy56OPY8cJBlrWEpLQ65eFzBj4Ts0PrtaOxwIXRdDt0ihAU8qs5icAoVgcR 
FdbcXGUAV7GfspgePNX1n4lBVrmBBZJGNZyq3tdzhf2h75J7xoT8bsGkxJyZXPQE 
1/UM/Kn2dC5EB1emN6omwtTMouFaBP+MEMZUZKHZl/e69TQV5B9KNsbuJyBrHXlF 
dOCygXXQc6LScsr3oO55NKy+96zUaRg7v0V2eT3Peq7751iZKej4RunX39YdnbDz 
9qaRskYUPqfhLxesXho8wXH9qs72OYNGqplhx51hOX4ScntCmIC6PMUX1BfUGt2/ 
xqDG3c/IzOWIJ7sqTGn/huAADdWWzpTiK6p1PKkCBUqLV/WamVmKxpJ5WA+0pfr7 
jxmVUBicaJHGLaB6cBiPdMPs/wjNH3XQNwawEUsVYAwH45qGjWtsW8JBJ1VSO45o 
boE1DmWLXy3zhRl+aTZ4TA==
=wSgb
-----END PGP MESSAGE-----```

**Comment by tomguim** [comment]
@maxtaco :D ur a life saver!
