### ISSUE TITLE
keybase.io describes DNS proof hash process incorrectly and shows wrong hash value

### ISSUE THREAD

**Issue by gene1wood** [keybase/keybase-issues#2408]
If you look at an [example DNS proof page](https://keybase.io/chris/sigchain#dbf530c689d2f3af60c5b11341d5eb2ad229995d6ef39dfd1661962d088a75ec0f) you'll see that it describes how the DNS TXT record hash is generated. That description says

```
Hash 
first 27 bytes
base64(SHA-256(dearmored(signed payload)))
```

![keybase_dns_proof_instructions](https://cloud.githubusercontent.com/assets/1134034/17071090/48ab9390-5014-11e6-96f4-13ad0fab87f8.png)

Beside the description is a base64 encoded string of the first 27 bytes of a 32 byte sha256 hash, as you would expect. In our example that value is `2_UwxonS869gxbETQdXrKtIpmV1u8539FmGW`

Problem is, this is not how the client checks a proof or how the website generates a proof to be added to DNS. The actual DNS proof process does *not* truncate the sha256 hash to 27 bytes, it instead uses the full 32 bytes.

You can see this by either looking up the actual DNS TXT record for our example above by running

`dig chriscoyne.com TXT  | grep keybase`

or by running the keybase `id` command

`keybase id chris`

both of which return the full hash `2_UwxonS869gxbETQdXrKtIpmV1u8539FmGWLQiKdew`

I suspect what happened here is that the website page that shows DNS proofs is incorrectly using the text and the logic for the twitter page (which *does* truncate to 27 bytes). Here's [an example tweet](https://twitter.com/malgorithms/status/433640580220874754) which is only 27 bytes long.

Please change the proof page for DNS to instead present the actual 32 byte base64 encoded value and describe the process as

```
Hash 
base64(SHA-256(dearmored(signed payload)))
```

**Comment by malgorithms** [comment]
thanks @gene1wood  - I changed this. There was also HackerNews proofs which had a similar prob.

**Comment by gene1wood** [comment]
Looks good, thanks.
