### ISSUE TITLE
Twitter proof hash process description doesn't match actual process

### ISSUE THREAD

**Issue by gene1wood** [keybase/keybase-issues#2409]
The process description for the Twitter hash, as can be seen in [this example](https://keybase.io/chris/sigchain#0d9f6b71c043f2ef80b6dea44338471edc3ef76e2cee236dd397412ad9631aa90f) is as follows

```
first 27 bytes base64(SHA-256(dearmored(signed payload)))
```

This isn't actually how the hash is made however because the base64 encoded hash isn't truncated to 27 bytes, instead the binary SHA-256 hash is truncated to 27 bytes, then the resulting 27 binary bytes are base64 encoded.

In addition some of the terms in this description are either vague (`dearmored`) or obscure important details (`base64`)

What do you think about changing the description from this
```
<small><br>first 27 bytes<br>base64(SHA-256(dearmored(signed payload)))</small>
```
which renders like this

![keybase_twitter_hash_current_description](https://cloud.githubusercontent.com/assets/1134034/17074297/fd473128-502e-11e6-8689-bdff749beb9d.png)

to something like this
```
<small><br><span title="urlsafe base64 without padding">base64</span>(first 27 bytes<br>SHA-256(<span title="base64 decode">dearmored</span>(<br>signed payload)))</small>
```
which renders like this

![keybase_twitter_hash_new_description](https://cloud.githubusercontent.com/assets/1134034/17074299/0233624c-502f-11e6-874d-8d8cab239a6b.png)

This would clarify what dearmored means, put the `first 27 bytes` in the correct place in the process and add the details about the `base64` step that show it's actually a `urlsafe` `base64` with the padding removed.

Currently this misordered text also exists in the DNS proof page, however since the hash process is different I opened a ticket suggesting a different fix for it ( #2408 )

**Comment by malgorithms** [comment]
thanks! look good now?

**Comment by gene1wood** [comment]
@malgorithms Ya, looks good. You didn't add the title tags with the additional detail about what the terms mean (e.g. base64 is actually urlsafe base64 without padding) but the important part of reversing the position of the "base64" and the "first 27 bytes" is present. Thanks.
