### ISSUE TITLE
keybase makes updatedb stop on linux

### ISSUE THREAD

**Issue by Ian321** [keybase/keybase-issues#2417]
It just stops at /keybase/public

to fix this I added `/keybase` to `PRUNEPATHS` in `/etc/updatedb.conf`
It would be nice if it would do this automatically.

**Comment by cjb** [comment]
Thanks for the report, CC @oconnor663.

**Comment by oconnor663** [comment]
This doesn't repro for me. I think it's because the default `/etc/updatedb.conf` file on Arch has `PRUNEFS = ... fuse ...`. @Ian321, does your config not exclude FUSE filesystems?

**Comment by Ian321** [comment]
That's the PRUNEFS part of my `/etc/updatedb.conf` i don't know if this excludes all fuse filesystems @oconnor663 

`PRUNEFS="NFS nfs nfs4 rpc_pipefs afs binfmt_misc proc smbfs autofs iso9660 ncpfs coda devpts ftpfs devfs mfs shfs sysfs cifs lustre tmpfs usbfs udf fuse.glusterfs fuse.sshfs curlftpfs ecryptfs fusesmb devtmpfs"`

**Comment by oconnor663** [comment]
Here's my entire config:

```
PRUNE_BIND_MOUNTS = "yes"
PRUNEFS = "9p afs anon_inodefs auto autofs bdev binfmt_misc cgroup cifs coda configfs cpuset cramfs debugfs devpts devtmpfs ecryptfs exofs ftpfs fuse fuse.encfs fuse.sshfs fusectl gfs gfs2 hugetlbfs inotifyfs iso9660 jffs2 lustre mqueue ncpfs nfs nfs4 nfsd pipefs proc ramfs rootfs rpc_pipefs securityfs selinuxfs sfs shfs smbfs sockfs sshfs sysfs tmpfs ubifs udf usbfs vboxsf"
PRUNENAMES = ".git .hg .svn"
PRUNEPATHS = "/afs /media /mnt /net /sfs /tmp /udev /var/cache /var/lib/pacman/local /var/lock /var/run /var/spool /var/tmp"
```

My guess is that the standalone `fuse` entry is important. @Ian321 what distro are you using, and what version  ef this is a config bug that only exists in old versions of updatedb, we might call it Working As Intended on the Keybase end?

**Comment by Ian321** [comment]
@oconnor663 It's Ubuntu 16.04.1 LTS and updatedb (mlocate) 0.26

**Comment by Ian321** [comment]
It's a error in the distro (or VM-Ware) i checked it with a new VM and iso, and fuse was missing. 
I added it to the config and it's working now.
Thx for the help.

**Comment by oconnor663** [comment]
No problem, interesting bug.
