### ISSUE TITLE
Problem with names

### ISSUE THREAD

**Issue by Luca0208** [keybase/keybase-issues#2425]
I can't name my Device MacBook, it says the name is already in use.
But if I look in my device list it doesn't show up there.

<img width="1065" alt="devices" src="https://cloud.githubusercontent.com/assets/9638292/17225167/2032aa44-5504-11e6-8795-84df8dc531f2.png">

**Comment by cjb** [comment]
You probably used the name previously and then revoked it.  You can't reuse a device name, even after a revocation.

**Comment by Luca0208** [comment]
Why not?

**Comment by cjb** [comment]
It's important for security reasons that a client can see a `<username>:<device name>` pair and know exactly which device it's referring to, rather than have it be something that changes over time.
