### ISSUE TITLE
Unable to submit PGP proofs – "502 Bad Gateway"

### ISSUE THREAD

**Issue by grawity** [keybase/keybase-issues#243]
It seems that any attempts to submit a proof of PGP key ownership – both through the web interface, and the command line – result in a "502 Bad Gateway" HTTP error. Other functions (signing up, uploading the public key) have worked fine.

(Also: The web interface doesn't even indicate that any error has occurred if I don't look in the browser's console…)

**Comment by mathemaphysics** [comment]
This issue has returned. Running `keybase pgp encrypt maxtaco@github <<<"monosodium glutamate"` give `502 Bad Gateway`. Work for me and a few others.

**Comment by maxtaco** [comment]
@mathemaphysics can you try it again, and if it still fails, do `keybase log send`? thanks
