### ISSUE TITLE
▶ ERROR dial unix /run/user/0/keybase/keybased.sock: connect: permission denied

### ISSUE THREAD

**Issue by sweepyoface** [keybase/keybase-issues#2436]
Hello, I've just installed Keybase on my Ubuntu 16.04 VPS and when I try to use any commands (search, login, etc) I'm getting this error:

`▶ ERROR dial unix /run/user/0/keybase/keybased.sock: connect: permission denied`

I've tried installing it both manually and with `apt`, same result.

`keybase log send` results in
`▶ ERROR Not confirmed`

**Comment by sweepyoface** [comment]
I am still having this issue on the latest version 1.0.16-20160808160043+cc9784a

Anyone know a fix?

**Comment by tehbmar** [comment]
On my debian system, running keybase as a normal user I have the following..

```
╭─ /run/user/1000/keybase  
╰─$ ls -al
-rw-r--r--  1 account account  63 Aug  9 14:23 keybased.info
-rw-------  1 account account   4 Aug  9 14:23 keybased.pid
srwxr-xr-x  1 account account   0 Aug  9 14:23 keybased.sock
```

Also based on the path you are giving it seems like the keybase sock is running as root (Or at least as group 0).

Note: You shouldn't have to use ./run_keybase as root (no sudo).  It is possible that you mucked things up on the install

Possible solution.  Uninstall keybase, purge keybase, and then run locate keybase to find any left over config files or scripts/settings.  Manually delete these.  Then install keybase through apt.

**Comment by sweepyoface** [comment]
I purged it with apt, ran autoremove and removed whatever I could that showed up in `locate keybase` (though a lot of them were giving me no such file or directory). I then installed it again with apt and any commands are still resulting in the same error.

I then ran run_keybase from the non root user which was successful, and it is still giving me the same thing even though the only thing in /run/user/ is 0/systemd.

**Comment by sweepyoface** [comment]
Aha! The solution [here](https://github.com/keybase/client/issues/2200) fixed the issue. Thanks.

**Comment by sweepyoface** [comment]
I am now getting permission denied when trying to access my kbfs directory. Log ID 5753bd69ed2a6a375f2ff21c

**Comment by strib** [comment]
```
 2016/08/09 21:03:04 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
16 kbfsfuse error: (2) fusermount: exit status 1
```

Looks like you have a `/keybase` directory lying around that maybe has the wrong permissions on it.

**Comment by sweepyoface** [comment]
Strange, I'm not sure what to do about that, here is the output of `locate keybase`

https://gist.github.com/sweepyoface/e25aff860f96b9646e3fa91def7f7374

**Comment by strib** [comment]
What does `ls -l /keybase` say and as what user are you doing `run_keybase`?

**Comment by strib** [comment]
I mean `ls -ld /keybase`, sorry.  Fixed.

**Comment by sweepyoface** [comment]
`run_user` was done by the sweepy user.

`drwxr-xr-x 1 root root 0 Jul 29 20:11 /keybase`

**Comment by sweepyoface** [comment]
How would I stop the service and unmount to try again? I accidentally just did it as root and when I ran it after with sweepy it didn't unmount and stop it first.

**Comment by strib** [comment]
You can look in the `run_keybase` script to see how it kills things:

```
cat `which run_keybase`
```

Those `/keybase` permissions look fine to me.  Is there any chance you have a non-standard FUSE configuration that requires your local user to be in a special group to run `fusermount`?  What does this show?

```
ls -l `which fusermount`
```

**Comment by sweepyoface** [comment]
Forgot to update this. Using `su` before interacting with keybase causes these issues. The solution is to log in directly as that user.
