### ISSUE TITLE
Uninstall Keybase Windows 10

### ISSUE THREAD

**Issue by cheesebug** [keybase/keybase-issues#2439]
Is there a way to uninstall Keybase on Windows 10? It's not listed in the Settings/apps and the installer file has no uninstall option. 

Does it have to manually be removed?

**Comment by zanderz** [comment]
It appears in the control panel under `Control Panel\Programs\Programs and Features`, unless something has gone wrong. If you have the original installation program, you can invoke it with the `/uninstall` option.

You can also try navigating to `%LOCALAPPDATA%\Package Cache` and searching subdirectories for Keybase*.exe. If you find it, invoke it with `/uninstall`.

**Comment by yarick** [comment]
```
cd C:\Users\myUser\AppData\Local\Keybase
keybase.exe /Uninstall
No help topic for '/Uninstall'
```
