### ISSUE TITLE
How do I stop it?

### ISSUE THREAD

**Issue by hippyjim** [keybase/keybase-issues#2441]
Since installing Keybase my system is slowed to a crawl.

I think the client combined with the filesystem is bringing my laptop to its knees. I don't want to uninstall, just not have the client running and I really don't care abiout the filesystem if it stops me getting on with my work. How do I disable just those things so I can use my laptop again?

There doesn't seem to be a "keybase stop" command.

**Comment by cjb** [comment]
Which OS?

I think "keybase ctl stop" does this.

**Comment by hippyjim** [comment]
Thanks - that did it. Finding my way around these help files is tough!

Using Xubuntu 14.04 by the way.

**Comment by cjb** [comment]
Cool. "sudo apt-get remove keybase" for permanent uninstall.
