### ISSUE TITLE
`keybase pgp gen` only adds user's Full Name to the first email address

### ISSUE THREAD

**Issue by arjunravinarayan** [keybase/keybase-issues#2446]
### What is the problem:
When you create a gpg key using keybase that has multiple email addresses, keybase only adds the user's Full Name to the first email address. The remaining email addresses are left nameless. The ideal behavior would be to attach the Full Name to each email address.

### Why this matters:
Does this matter? Perhaps this doesn't; I'd be interested to hear arguments against the proposed behavior. If you tried to manually generate keys with multiple emails, some of which had no names in gpg, it complains and does not let you proceed.

### Steps to reproduce:
Create a pgp key using `keybase pgp gen`:
`keybase pgp gen --no-export --debug`
I used the following inputs:
```
Enter your real name, which will be publicly visible in your new key: Test Key Please Ignore
Enter a public email address for your key: testing@example.com
Enter another email address (or <enter> when done): testingagain@example.com
Enter another email address (or <enter> when done):
Push an encrypted copy of your new secret key to the Keybase.io server? [Y/n] n
```

The resulting key can be seen with `keybase pgp list`:
```
Keybase Key ID:  010148e24fd65851bb6dda13909e55b12bb3bf738e1513312e80549ca05d55f0307c0a
PGP Fingerprint: F405 AD1C 6262 6B2C 51D6 8E78 559C E50B 1E27 8D94
PGP Identities:
   Test Key Please Ignore <testing@example.com>
    <testingagain@example.com>
```

Notice how the second email has no name? This is wrong.

### Interim manual fix
This can be patched up through gpg, with the following commands:
`gpg --edit-key F405`
Select the emails without names with `uid`, and drop them, one by one with `deluid`.
Add them back with `adduid`, but type Full Names and emails each time.

Now the email IDs will each individually have your name attached. But this is only in gpg. Import the edited key back into keybase with
`keybase pgp update F405`
This also pushes it to keybase.io, and you are done.

As a tangent, this action will show up in the sigchain (for instance, see [my sigchain](https://keybase.io/arjun/sigchain#2a2298048e7ceeb5a60af8d18ec7dd124f67e39413afd744f2016f539f620e2d0f)) as "performed no action". Strictly speaking, this isn't true. Perhaps it should say "key identity updated", or "key metadata changed", or something of that sort.

**Comment by gavatron90** [comment]
Gavatron90
