### ISSUE TITLE
Cannot configure Keybase App to not autostart on Mac OSX

### ISSUE THREAD

**Issue by smingins** [keybase/keybase-issues#2448]
Where do I configure keybase to not start every time OSX starts?

**Comment by mifix** [comment]
As far as I know, there isn't any userfriendly configuration yet.

In your terminal run:

```bash
cd ~/Library/LaunchAgents; launchctl unload keybase.*; mv ./keybase.* ~/Desktop; launchctl unload /Library/LaunchDaemons/keybase.Helper.plist; sudo mv /Library/LaunchDaemons/keybase.Helper.plist ~/Desktop
```

(As a backup, the plists are moved to your Desktop)


(see also #2477 and #2380)

**Comment by phlebotinum** [comment]
Just realized there is no option. INSTANT UNINSTALL. Let me know when your marketing strategies grow up.

**Comment by heronhaye** [comment]
In Keybase 5.0 you can change this setting on all platforms in Settings -> Advanced. Please make another issue if it doesn't work. Thanks.
