### ISSUE TITLE
`keybase track` vs. `keybase follow`

### ISSUE THREAD

**Issue by crosser** [keybase/keybase-issues#2451]
The web site suggests to use `keybase track` command to track a user:
![screenshot keybase track 2016-08-03 20-21-46](https://cloud.githubusercontent.com/assets/1404921/17375284/558e8d86-59c1-11e6-9fb0-4ff85ef70128.png)
However, command line client as of version `1.0.16-20160802173443+d99d9c7` does not have this command:

```
crosser@pccross:~$ keybase track troff
No help topic for 'track'
```

The command line tool has command `follow` that actually enables tracking.

**Comment by malgorithms** [comment]
oh, thanks!  `keybase track` should stay working for a while, even if it doesn't show up in the help. that allows us to change the name smoothly. will fix asap.

**Comment by strib** [comment]
@malgorithms `keybase track` does not work anymore (at least not on Linux).  Maybe whoever made the change made a mistake?

**Comment by maxtaco** [comment]
I had a PR that I forgot about with the alias change. Sorry.  Merged now.

**Comment by maxtaco** [comment]
https://github.com/keybase/client/pull/3663

**Comment by cjb** [comment]
@crosser this fix is released in the latest Linux build now

**Comment by crosser** [comment]
`keybase track` command works in recent build, closing the ticket. Thanks! :+1:
