### ISSUE TITLE
Upload public key only

### ISSUE THREAD

**Issue by smalldave** [keybase/keybase-issues#2454]
I can't find a way to do this.

The cli always pops up a window that says I need to enter the secret key passphrase (I can't the key is on a yubikey) regardless of what options I pass.
The website says that 'this can't be done in the browser' when I try to add a pgp key and points me to the cli.

**Comment by maxtaco** [comment]
You need to make a signature with your private key as part of provisioning.
That is why you are seeing the pinentry popup.  There is no expectation of
exporting your secret key.

**Comment by smalldave** [comment]
My mistake. Thanks
