### ISSUE TITLE
http access on keybase.pub redirects to root

### ISSUE THREAD

**Issue by zzh8829** [keybase/keybase-issues#2466]
`curl -L zihao.keybase.pub/test.txt`
should redirect to `https://zihao.keybase.pub/test.txt`
but right now everything goes back to `https://zihao.keybase.pub`

**Comment by zQueal** [comment]
This seems to be fixed?

    λ curl -L zihao.keybase.pub/test.txt
    This is Zihao Zhang
    <br>
    keybase.io is pretty cool
    <br>
    <a href="resume.pdf">Resume</a>

**Comment by zzh8829** [comment]
that is my `index.html` not `test.txt`

**Comment by zQueal** [comment]
Seems to be a disconnect between HTTPS and non-HTTPS connection requests;

    λ curl -L https://zihao.keybase.pub/test.txt
    test
    
    λ curl -L http://zihao.keybase.pub/test.txt
    This is Zihao Zhang
    <br>
    keybase.io is pretty cool
    <br>
    <a href="resume.pdf">Resume</a>

**Comment by malgorithms** [comment]
nice catch - we'll fix this redirect soon

**Comment by cjb** [comment]
Ah, that's funny -- this works in wget, and it works in browsers, because they first perform HSTS translation and curl doesn't:
```
 λ wget zihao.keybase.pub/test.txt
URL transformed to HTTPS due to an HSTS policy
--2016-08-08 09:57:15--  https://zihao.keybase.pub/test.txt
```

**Comment by cjb** [comment]
I think this is fixed now.  Please could you retest and confirm?

**Comment by zQueal** [comment]
λ curl -L https://zihao.keybase.pub/test.txt
    test

    λ curl -L http://zihao.keybase.pub/test.txt
    test

Seems to be squished for me. :+1:
