### ISSUE TITLE
`keybase pgp select <key-id>` displays conflicting requests for the PGP passphrase

### ISSUE THREAD

**Issue by dusek** [keybase/keybase-issues#2471]
`keybase pgp select <key-id>` asks for the passphrase to the private PGP key. However the message it uses in two places within a single screen is conflicting:
- in the introductory text, it asks for "_PGP key passphrase_" (**correct**)
- in the prompt, it asks for "_Your Keybase Passphrase_" (**wrong**)

See this illustrated on the following screenshot:
![keybase_pgp_select__passphrase](https://cloud.githubusercontent.com/assets/41975/17515941/b9b713a4-5e3b-11e6-8187-285263858179.png)

Therefore the user is left confused which passphrase he/she is to enter.

Stack:
- macOS 10.11.6
- keybase version 1.0.16
- gpgv (GnuPG) 2.0.30
- libgcrypt 1.7.2

**Comment by maxtaco** [comment]
You are right, we'll fix it. Thanks!

**Comment by zapu** [comment]
Fixed in https://github.com/keybase/client/pull/6065
