### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by jamiedukeellis** [keybase/keybase-issues#2475]
When logging in to keybase from someone's profile, i get this spelling error. 
http://imgur.com/a/5USev

**Comment by tehbmar** [comment]
This actually isn't a spelling error (AFAIK) it's actually how keybase derives keys.  If you're interested in learning more here is the TripleSec docs which is what keybase uses for protecting sensitive information with passphrases.  https://keybase.io/triplesec/

**Comment by zQueal** [comment]
Scrypt is the [KDF](https://en.wikipedia.org/wiki/Scrypt) which protects your password/account.
