### ISSUE TITLE
OSX(10.11.5) keybase(GUI) starts when login

### ISSUE THREAD

**Issue by D0zingcat** [keybase/keybase-issues#2477]
Could anybody tell me how to turn off the autostart configuration on OSX?

It's quite annoying the keybase app shows up when the system starts!

**Comment by fzzr-** [comment]
Simply unload & remove three files:
```
~/Library/LaunchAgents/keybase.kbfs.plist
~/Library/LaunchAgents/keybase.service.plist
~/Library/LaunchAgents/keybase.updater.plist
```

Run this shell command:
```bash
cd ~/Library/LaunchAgents; launchctl unload keybase.*; rm ./keybase.*
```

**Comment by fzzr-** [comment]
But I don't know what doing next tool:
```
/Library/PrivilegedHelperTools/keybase.Helper
```

**Comment by MattiSG** [comment]
Duplicate of #2448 (#2448 is better phrased).
