### ISSUE TITLE
Username Issue

### ISSUE THREAD

**Issue by kieransaul** [keybase/keybase-issues#2478]
Hi,

I just got my invite and created my account. Is there any way for me to change this? I only activated my account and not uploaded anything to it. I can't seem to find any documentation online.

Here is my account url: https://keybase.io/kieransau

Thanks
Kieran!

**Comment by oconnor663** [comment]
There's no way to change your username once you've created your account, but I've sent you another invite so that you can create a new one. It'll go to the email address you list on your GH profile.

**Comment by kieransaul** [comment]
Hi,

I don't know how long it takes for the email to be delivered, but i haven't received anything.

Thanks,
Kieran

**Comment by oconnor663** [comment]
Do you still have access toi dev@kieransaul.tk ?

**Comment by kieransaul** [comment]
Hi,

Would it be possible to send it to kieran@kieransaul.co.uk please. 

Thanks again,
Kieran

**Comment by oconnor663** [comment]
Sure thing. Done.
