### ISSUE TITLE
[Windows] QOL Issue

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#2480]
Keybase runs for me at startup which I like. It's there if I need it. What I don't like is having to enter my huge ass password every time I login--so sometimes I simply close the window and stay logged out until I have the need to use Keybase.

This prompts Keybase to ask for my password _every time_ Windows scans available drives. About once every 8 minutes. It interrupts whatever I have going on at the time be it a game, video, or work. It's such a simple thing, but it's incredibly maddening.

There needs to be a QOL option to either stop this popup, or to allow me (because I'm the only one in my home...) to simply be logged it at all times without having to unlock my key again until just before I'm about to use it.

Any thoughts on this? It sounds small but it's seriously annoying.

**Comment by maxtaco** [comment]
Agreed, we are fixing this asap

cc: @patrickxb

**Comment by hedgehog1029** [comment]
:+1: on this, I will also note that I get random popups telling me I accessed a public folder with `chris`, but not any of the other people I have opened the public folders of. That might be considered a seperate issue though.

**Comment by juanminm** [comment]
@hedgehog1029 happened to me and some others with "chris" folder as well. I solved it by deleting the folder with "rmdir", then killing RuntimeBroker.exe (which was querying that folder at random times) and also rebooted Windows. You may use Process Monitor (a Sysinternals tool) so you can filter all handles that contain "K:\" or "K:\public\chris" and see which process is the culprit. Just be careful cause it can be RAM and CPU consuming as it keeps capturing handles.

**Comment by zQueal** [comment]
Since the fix is under way I'm going to close this.
