### ISSUE TITLE
Cannot sign public key (any method)

### ISSUE THREAD

**Issue by brendan-r** [keybase/keybase-issues#2483]
Hello there,

I don't remember seeing the red "oops" text on my profile before. It tells me I need to sign my public key (which is not/no longer on my public profile).

Context:
* I do not have my private key on your servers (in fact, I don't have ready access to it)
* I am using subkeys, [Debian style](https://wiki.debian.org/Subkeys)
* Stored on a YubiKey 4

via the CLI:

```
$ keybase pgp select <KEY>
▶ ERROR You already have a PGP key registered (D606 ...)
Specify the `--multi` flag to override this check


$ keybase pgp select <KEY> --multi
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   27E32E7C7E604247             Brendan Rocks <brendan@brendanrocks.com>
Choose a key: 1
You've already selected this public key for use on Keybase. Would you like to update it on Keybase? [Y/n] y
▶ INFO Posting update for key  <KEY>.
▶ INFO Key was already up to date.
```

`gpg` generally doesn't get on well with YubiKeys, so using `gpg2`, for the `bash` and `curl` method:

```
Error in your post
-------------------

Code: 908
Name: KEY_NEED_REVOKE
Description: You need to delete your active key before uploading a new one
```
Any ideas?

I have `keybase pgp import`'ed.

Ubuntu 16.04.01:
```
$ keybase version
Client:  1.0.17-20160812160036+d206db9
Service: 1.0.17-20160812160036+d206db9
```

**Comment by maxtaco** [comment]
Try `keybase pgp update` ?

**Comment by brendan-r** [comment]
Same message (and result in the web UI: no change) as `keybase pgp select ...`

```

$ keybase pgp update
▶ INFO Posting update for key <KEY>
▶ INFO Key was already up to date.
```

**Comment by maxtaco** [comment]
Ok, this is likely a bug on our side. We'll look into it. Thanks for  your patience!

**Comment by maxtaco** [comment]
The plot thickens, the CLI seems to think you PGP key is fine:

```
keybase id brocks
▶ INFO Identifying brocks
✔ public key fingerprint: D606 578B 103A FC8E C056 619D 27E3 2E7C 7E60 4247
✔ "rocksbrendan" on twitter: https://twitter.com/rocksbrendan/status/761356137702756354
✔ admin of brendanrocks.com via HTTPS: https://brendanrocks.com/keybase.txt
✔ "brendan-r" on github: https://gist.github.com/d2ee938d1f8ff5ec22946c5e59722596
```

**Comment by maxtaco** [comment]
It's because you revoked twitchbox.  Our bug, I can likely resolve it without any intervention from you.

**Comment by bhhaskin** [comment]
@maxtaco I am also unable to sign my public key using my yubikey.

**Comment by maxtaco** [comment]
@bhhaskin I don't think it's related to this issue.

**Comment by bhhaskin** [comment]
I am also using a YubiKey 4 with sub keys (stored on the key).

It may or may not be directly related, but seeing as I am having the issue with two different YubiKeys..

I am also unable to use the curl bash gpg method because of this notice on the website. 

```
Now that you've installed Keybase and generated device keys, adding a PGP key must be done on your computer. 
```


```
$ keybase pgp select
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   03A599A9579E7C0B             Bryan Haskin <bryan.haskin@noblestudios.com>
2    3744R   A59C4A2A837693B0             Bryan Haskin <bhhaskin@gmail.com>
Choose a key: 1
▶ INFO Bundle unlocked: 03A599A9579E7C0B
▶ ERROR key generation error: GPG error: exit status 2

```

Mac OSX 10.11.5
```
keybase version
Client:  1.0.16-20160803190018+268b023
Service: 1.0.16-20160803190018+268b023
```

**Comment by maxtaco** [comment]
You want `keybase pgp select --no-import`.  Your issue isn't related to this bug though.

**Comment by bhhaskin** [comment]
If you don't believe this is the same issue I will open a new ticket.

```
keybase pgp select --no-import
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   03A599A9579E7C0B             Bryan Haskin <bryan.haskin@noblestudios.com>
2    3744R   A59C4A2A837693B0             Bryan Haskin <bhhaskin@gmail.com>
Choose a key: 1
▶ INFO Bundle unlocked: 03A599A9579E7C0B
▶ ERROR key generation error: GPG error: exit status 2
```

**Comment by maxtaco** [comment]
Yeah, please move over to a new ticket.  Run with `-d` and let me know what happens. It's so ridiculously hard for us to support GPG since there's not a good API to it and it fails in lots of ways on people's machines.  So there's likely a GPG failure of some sort.  Likely pinentry I'm guessing.

**Comment by maxtaco** [comment]
I'm certain it's a different issue.

**Comment by maxtaco** [comment]
@brendan-r should be fixed, let me know if not.

**Comment by brendan-r** [comment]
Key in web UI LGTM, many thanks! :tada:
