### ISSUE TITLE
"web proof just broke"

### ISSUE THREAD

**Issue by pseudometric** [keybase/keybase-issues#2488]
Hi,

I've had a Keybase account for a while now. Today I got a message that my web proof at https://www.qoxp.net/keybase.txt broke. I when I try to reactivate it in the Keybase UI, it says "that domain isn't loading," suggesting that it can't reach the web server -- but it's running and the file is there. How should I understand and resolve this?

Thanks,

Richard E. Silverman

**Comment by BrandonIngalls** [comment]
It looks like there is something wrong with your DNS server.
```bash
[~]$ nslookup www.qoxp.net 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find www.qoxp.net: SERVFAIL

[~]$ nslookup qoxp.net 8.8.8.8 
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find qoxp.net: SERVFAIL

[~]$ nslookup google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	google.com
Address: 216.58.216.238
```

SERVFAIL info from [wordtothewise.com](https://wordtothewise.com/2013/04/dns-servfail-firewalls-microsoft/)
> SERVFAIL is the all purpose “something went wrong” response. By far the most common cause for it is that there’s something broken or misconfigured with the authoritative DNS for the domain you’re querying so that your local DNS server sends out questions and never gets any answers back. After a few seconds of no responses it’ll give up and return this error.

**Comment by pseudometric** [comment]
Oops, yes. :( The problem is related to DNSSEC, in fact, and so some uses succeed and some fail depending on whether the resolver in use does DNSSEC validation. (It wasn't relevant in the environment where I tested it before reporting this.) I'll deal with it. Thanks.
