### ISSUE TITLE
Reddit proof fails

### ISSUE THREAD

**Issue by creack** [keybase/keybase-issues#2490]
I tried 3 times to proove my redis identify without any success.

Link to proofs: https://www.reddit.com/user/creack

Let me know what other info I could provide.

**Comment by juanminm** [comment]
Your user page outputs "page not found" and I can't find your proof in r/KeybaseProofs

**Comment by creack** [comment]
Direct link: https://www.reddit.com/r/KeybaseProofs/comments/4xtmoi/my_keybase_proof_redditcreack_keybasecreack/

**Comment by creack** [comment]
Indeed, looking at it wihtout being logged in, it is marked as "deleted", not sure why..

**Comment by juanminm** [comment]
Most likely you are shadowbanned, similar to this: https://github.com/keybase/keybase-issues/issues/2270
