### ISSUE TITLE
Twitter verification less spammily

### ISSUE THREAD

**Issue by dreeves** [keybase/keybase-issues#2496]
I stuck an "@keybaseIO" at the beginning of my verification tweet so as to only spam my followers who already follow Keybase on Twitter. It's still public that way and should work as verification but it doesn't seem to. Of course you want to encourage people to broadcast the tweet widely but they shouldn't *have* to.

**Comment by oconnor663** [comment]
This actually should work. I think you've hit a different confusing failure mode, where you made two different twitter proofs, but only the first is posted. When you made the [second signature](https://keybase.io/dreeves/sigchain#733a348c171a8af0d09b1f9f9e3bd545ae2234e5b515ddc43f4a8be0bc56ca5f0f), it revoked the first one automatically, so the server is ignoring it and only looking for the second. The easiest way to fix this is to prove Twitter a third time and post the tweet that that generates. It's safe to delete the first one if you want.

**Comment by dreeves** [comment]
Confirmed! I'm all good now. Thanks!
