### ISSUE TITLE
twitter proof failure

### ISSUE THREAD

**Issue by lakeborn** [keybase/keybase-issues#2498]
Regarding @jonathan_rupp and Keybase.io verification of ownership. I have completed this and tweaked the required link. Please verify and provide verifcation.

**Comment by 0x4445565A** [comment]
It looks like your proof passed and is working?  Are you still experiencing issues?

**Comment by lakeborn** [comment]
No, I went into the shell and was able to resolve everything.

Thank yo u for the follow up.

Jon / lakeborn

**Comment by 0x4445565A** [comment]
No problem, feel free to close this issue out (I would do it for you but I'm not in the Keybase Github group)

**Comment by lakeborn** [comment]
Everything is resolved.
