### ISSUE TITLE
`Device ID` not deleting from DB after «reset my keys & start from scratch»

### ISSUE THREAD

**Issue by artbelov** [keybase/keybase-issues#2507]
Hello «Keybase» team!

After «reset my keys & start from scratch» action, my `keybase device list` was clean, but...
After login from MacOS App I can't create device with same (early existing) name.
And some commands fails too:

```sh
keybase login
▶ ERROR No device found for device ID 9304ae2d2c28d86272dd01a259297918
keybase device remove 9304ae2d2c28d86272dd01a259297918
▶ ERROR Can't revoke the current device.
```

It means, than my DeviceID still in DB 😐 
*Temporary solution: create device with another name.*

Best regards, Artem.

**Comment by oconnor663** [comment]
Believe it or not, this is deliberate. We might relax it in the future, but for now we want to give ourselves the option of relying on username+devicename as a never-changing identifier for a specific key.
