### ISSUE TITLE
Github proof

### ISSUE THREAD

**Issue by domharrington** [keybase/keybase-issues#2516]
I'm trying to prove my github account but the check is failing.

Keybase account: https://keybase.io/domharrington
Github proof: https://gist.github.com/domharrington/70110bed5e73ae41fcdb309d859aa25f

Is there anything else i need to do? Or anything i've done wrong?

Thanks

**Comment by ChipWolf** [comment]
See https://gist.github.com/ChipWolf/e988f4986e0f9647c352
Looks like you missed the majority of the gist

**Comment by domharrington** [comment]
Gahh! I must've C+P'd it badly. Sorry!
