### ISSUE TITLE
Add option to display SSH key from account public key

### ISSUE THREAD

**Issue by plttn** [keybase/keybase-issues#2517]
Since GPG offers an SSH auth agent, would it be possible to display the SSH compatible key somewhere on the Keybase user page as an option? My current method is shoving `ssh.txt` in my public folder, which is a pretty good solution, but it's not on the Keybase user page directly.

**Comment by webbson** [comment]
+1. Just though of that as well. Was on my way in here to write it when I saw your issue.

**Comment by thiagowfx** [comment]
See #710
