### ISSUE TITLE
Chris granted me more invites but they disappeared

### ISSUE THREAD

**Issue by burningTyger** [keybase/keybase-issues#2518]
I was sent an email which said it granted me five more invites (had 4 left) and that I could use the file system feature to invite. I did that but was then informed that I had no invites left and couldn't yet use this feature because the other user had not yet signed up. I did not invite anybody else. Looks like a bug to me.

**Comment by burningTyger** [comment]
Did this only happen to me?

**Comment by malgorithms** [comment]
I definitely didn't withdraw any invites. sounds like a bug of some kind. What's your keybase username? does it show you have invites available if you're logged into the website and look at 

https://keybase.io/account/invitations

**Comment by burningTyger** [comment]
Thank you, didn't assume you personally withdrew :). It looks like the 9 invites have been sent all at once. That must have been a mistake because I just added the twitter user to my private folder as described in the docs. So I guess I can just revoke the invites and be good again? The username is hmt btw.

**Comment by malgorithms** [comment]
yeah, you're definitely the first to report this. there's definitely a bug. we'll fix this ASAP and I'll send you another bunch of invites

**Comment by malgorithms** [comment]
actually, apparently this is a known issue and I believe it's fixed. @strib can I get a confirmation? (On 8/24 they tried to share file(s) with a twitter user and it used up all 9 of their invites.)

**Comment by strib** [comment]
Yes, fixed in keybase/client#4082, merged 29 days ago (after 8/24).

**Comment by burningTyger** [comment]
Thank you!
