### ISSUE TITLE
df -h /keybase says it has 16Exabytes

### ISSUE THREAD

**Issue by lesleyxyz** [keybase/keybase-issues#2521]
```
root@x:~# df -h /keybase
Filesystem      Size  Used Avail Use% Mounted on
/dev/fuse        16E     0   16E   0% /keybase
```

This gives me a problem in Virtualmin cause it says I have 16 exabytes of free storage.
It should be 10gb like in Windows or something more reasonable.

I've also addressed this issue on virtualmin's issue tracker.

**Comment by ax3l** [comment]
I have the same `df -h` output but am not using it with virtualmin, so no problem so far (besides that showing the actual 10G quota would be way more reasonable).

@lesleyxyz It might help to cross-link the two issue trackers in your reports :)

**Comment by Sevyls** [comment]
On macOS Sierra it says I have 2,31 Exabyte available:
Screenshot:
![image](https://cloud.githubusercontent.com/assets/547842/22507486/1a3d7b80-e886-11e6-97d8-ffe5e79ef073.png)

``df -h``:
```
michael$ df -h
Filesystem                          Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1                         233Gi  216Gi   17Gi    93% 2441132 4292526147    0%   /
...
...
kbfs@kbfuse0                       2.0Ei    0Bi  2.0Ei     0%       0          0  100%   /keybase
```

**Comment by zQueal** [comment]
Working fine on Windows with GNU Coretools `df`;

    λ df -h
    Filesystem                                     Size  Used Avail Use% Mounted on
    C:                                              233G  149G   84G  64% /
    D:                                              1.9T  1.5T  425G  78% /d
    K:                                              10G   24M   10G   1% /k
