### ISSUE TITLE
Labeling your MD file with a comma instead of a . succeeds verification.

### ISSUE THREAD

**Issue by djchateau** [keybase/keybase-issues#2522]
When proving myself on a GitHub account I noticed I mistyped the filename of keybase.md as keybase,md, but it still succeeded in spite of that. Assuming you want to have an accurate verification, this shouldn't happen.

**Comment by malgorithms** [comment]
we intentionally allow you to name the file anything you want; the `keybase.md` suggestion is really becuase (1) people didn't know what to call it, and (2) to tell github it's a markdown file for code coloring reasons.
