### ISSUE TITLE
"ppgen assertion failed before update (error 1407)" after changing passphrase

### ISSUE THREAD

**Issue by geepee** [keybase/keybase-issues#2524]
I seem to be having an issue similar to @yipal ( #2070 ); after trying to add a new device, either via the CLI or the GUI, I get the dreaded "ppgen assertion failed before update (error 1407)" right after selecting a name for the new device. Thing is, I've recently changed my passphrase via the website (IIRC), so the profile could be borked. Issue happens on multiple platforms (tried in Xubuntu 16.4.1 and Windows 10).

Logs sent. ID: 949ada5ca6a259406fb4f01c

Thanks.

**Comment by maxtaco** [comment]
Oy sorry about this.  No one dreads it more than I. I will have to page
back in exactly what the issue was and how to fix it.  As far as I recall
it was a server side patch.  I will be in touch tomorrow. Thanks for your
feedback.

**Comment by maxtaco** [comment]
On the device that's already provisioned, can you do a `keybase log send`?

Also, can you try a `keybase db nuke` on the device that's already provisioned? And then try to provision again?

Thank you

**Comment by maxtaco** [comment]
Alternatively, @geepee, can you try to `keybase logout` and then `keybase login` on your existing device?  From the server side, your account looks ok.  I think your existing client is just in a stuck state, and it's the one sending over that passphrase generation (`ppgen`).

CC: @patrickxb

**Comment by maxtaco** [comment]
Also, it looks like you changed your passphrase twice.  Can you remember did you try `keybase passphrase recover` at some point in there?

**Comment by geepee** [comment]
Thanks for those quick replies. The provisioned device is my workstation at home, I'll give it a shot later tonight. And yes, I did change change my passphrase twice and I did use `keybase passphrase recover` (the second time around, I believe).

**Comment by maxtaco** [comment]
This is very helpful, thank you. Did you change it to be the same passphrase when you ran `passphrase recover`?  And do you remember why you thought you had to do that?  I.e., did the CLI give you an error?

I think I can work on repro'ing the bug now, thanks for all of your help...

**Comment by maxtaco** [comment]
Sadly I couldn't repro your issue, though I tried a bunch.  I guess let me know if those various changes fix it.

**Comment by geepee** [comment]
Yes, it was the same phrase. I originally changed it because I wasn't sure I entered the right one originally... I'll try to nuke the database on my provisioned device at home tonight and give it another go then, I'll keep you posted.

**Comment by maxtaco** [comment]
Thanks @geepee.  Please try `keybase logout ; keybase login` first

thanks

**Comment by geepee** [comment]
Looks like the `nuke`'ing of the DB did it - I was able to provision my other device after clearing out the database on the first one. Thanks @maxtaco !
