### ISSUE TITLE
Cannot verify my proof on Reddit

### ISSUE THREAD

**Issue by J2TeaM** [keybase/keybase-issues#2527]
My Keybase proof: https://www.reddit.com/r/KeybaseProofs/comments/501f5u/my_keybase_proof_redditjuno_okyo_keybasejuno_okyo/

But it always says failed:

![image](https://cloud.githubusercontent.com/assets/5250117/18036784/a7de3c80-6d9e-11e6-9964-b081132a7977.png)

**Comment by juanminm** [comment]
It seems like you are shadowbanned. The post appears as [removed] and your userpage appears as "page not found". You can try for yourself by opening a Private/Incognito tab/window with your browser and looking at the proof and profile page; or logging out in the current tab. You can find more info here for steps on how to know if you are shadowbanned here: https://github.com/keybase/keybase-issues/issues/2270

If you are indeed shadowbanned, then you'll have to contact Reddit administration.
