### ISSUE TITLE
Windows 1607 Dokan Driver

### ISSUE THREAD

**Issue by BranicYeti** [keybase/keybase-issues#2530]
I was having an issue where a fresh install of Windows 1607 (with Bash on Ubuntu on Windows enabled) and a fresh install of Keybase would not show the K drive that comes with KBFS. `keybase status` suggested that KBFS was running, but the status log was saying that the "write journal was not enabled". I wondered if the Linux Subsystem was causing an issue, so freshly installed Windows again and didn't enable LXSS before installing Keybase. This time, I saw an error message that before I either missed or didn't get.
![dokan-driver-error](https://cloud.githubusercontent.com/assets/1971818/18038504/f59c4b64-6d90-11e6-9a2d-323382f8cf5b.jpg)
I assume this error is the cause of my earlier issues. A quick skim of the log file showed the same error message:

```
2016-08-29T02:35:43.474905 - [WARN kbfs asm_386.s:1585] 021 KBFS Status failed: Write journal not enabled
2016-08-29T02:35:44.678158 - [ERRO kbfs mounter.go:53] 022 Failed to mount dokan filesystem (i=16): Dokan failed: -3
2016-08-29T02:35:47.897250 - [ERRO kbfs mounter.go:53] 023 Failed to mount dokan filesystem (i=32): Dokan failed: -3
2016-08-29T02:35:54.304184 - [ERRO kbfs mounter.go:53] 024 Failed to mount dokan filesystem (i=64): Dokan failed: -3
```

I'll hold off doing what Windows suggests and installing Dokan myself, since I believe I saw advice in the past against such a thing, and I haven't really looked since to see if there is still an issue with running your own Dokan library, unless you can tell me otherwise or suggest a fix I can do before the next release of the Keybase app.

**Comment by zanderz** [comment]
Hi, I forgot to mention here that we are now shipping drivers that have successfully been signed with Microsoft's process. Does it install and work OK now?

**Comment by BranicYeti** [comment]
Yessir. I didn't notice immediately because I was just removing the keybase-installed Dokan and installing the signed one from the git repo, but the update I ran before closing the issue acted as expected. Thank you.
