### ISSUE TITLE
Error EOF trying to submit public ECC key using the Windows App 

### ISSUE THREAD

**Issue by tanto259** [keybase/keybase-issues#2533]
I tried to submit my ECC 521E public key to keybase. First it gave the warning 
- WARNING GPG index error at line 3: Unknown subfield: grp
- WARNING GPG index error at line 7: Unknown subfield: grp
- WARNING GPG index error at line 10: Unknown subfield: grp
- WARNING GPG index error at line 13: Unknown subfield: grp
  <br></br>
  then after selecting the key and entering the password, I got the ERROR EOF.
  During the keybase popup for password input, it detect the key as 0-bit ECDSA.
  <br>
  Log ID: ae7e811d76d63c7f1720cc1c

**Comment by plttn** [comment]
I cannot say for sure, but it looks like Keybase only supports RSA keys from looking at the client source.

**Comment by maxtaco** [comment]
We definitely support ECC keys but seems like you've hit a limitation in Go's OpenPGP libraries.  We can take a look but probably can't prioritize it.  Thanks for your feedback!

**Comment by tanto259** [comment]
Thanks for the reply, anyway I do a couple of test and here's the result
Using GnuPG 2.1.15 to generate the key and using Keybase 1.0.17-20160822152935+692af12
Running Windows 10. All keys are generating using the command
`gpg --expert --full-gen-key` and selecting option `(9) ECC and ECC`

Using a new NIST-P521 curve and it gave 2 warning
`- WARNING GPG index error at line 3: Unknown subfield: grp`
`- WARNING GPG index error at line 7: Unknown subfield: grp`
with the Error EOF again.

Testing with a 4096RSA gave it 2 warning
`- WARNING GPG index error at line 3: Unknown subfield: grpAlgo`
`- WARNING GPG index error at line 7: Unknown subfield: grp`
but this time it succeeded in importing the key.

Using a Brainpool P512 key, it gave 2 warning
`- WARNING GPG index error at line 3: Unknown subfield: grpUserId`
`- WARNING GPG index error at line 7: Unknown subfield: grp`
with the Error EOF again.

Using a Curve 25519 key, it gave 2 warning 
`- WARNING GPG index error at line 3: Unknown subfield: grp`
`- WARNING GPG index error at line 7: Unknown subfield: grp`
with the error below when trying to import it.
`- ERROR ImportKey error: openpgp: unsupported feature: unsupported oid: 2b060104019755010501`

Using a secp256k1 curve, it gave 2 warning
`- WARNING GPG index error at line 3: Unknown subfield: grpAlgo`
`- WARNING GPG index error at line 7: Unknown subfield: grp`
with the error below when trying to import it.
`- ERROR ImportKey error: openpgp: unsupported feature: unsupported oid: 2b8104000a`

**Comment by zapu** [comment]
@tanto259 Could you try this again? We had some improvements for ECC keys (especially for Curve25519) during last few months. Thank you!

**Comment by tanto259** [comment]
Closed as issue is fixed. Thanks!
