### ISSUE TITLE
keybase identity

### ISSUE THREAD

**Issue by koehn** [keybase/keybase-issues#2534]
Can you add a way to get just the currently logged in user's identity from keybase? I'm thinking of something like `keybase id --self` which would return (for me) `koehn`. This would be handy for the script I'm currently writing, which is dependent upon keybase. 

Thanks!

**Comment by petethomas** [comment]
Something like this may be a workaround:

```
> MYKEYBASEID=`keybase id 2>&1  | grep Identifying | sed 's/.*[[:blank:]]//;/./!d'`
```

**Comment by patrickxb** [comment]
`keybase status -json` will output `{ "Username": "patrick", ...}` along with a bunch of other information.
