### ISSUE TITLE
Windows cannot access the specified device...

### ISSUE THREAD

**Issue by zillz** [keybase/keybase-issues#2537]
In windows 10, after downloading the app, and attempting to install it as admin:

> Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

**Comment by zanderz** [comment]
Can you attach the installer logs (`%temp%\keybase*.log`)? Installation should be perfomed under the user account, but the user must also belong to the admin group. Installing with elevated privileges is not recommended.

**Comment by zillz** [comment]
i think that was my issue -- installing as admin. after a couple of weeks I tried again and installed  as user and it worked fine. Thank you zanderz.
