### ISSUE TITLE
Bad issues folder

### ISSUE THREAD

**Issue by rob-nash** [keybase/keybase-issues#2538]
This just [very randomly] appeared. It may be a coincidence that it appeared at exactly the same time that I launched the native mac os x 'messenger' App.

![](https://i.imgur.com/GtTJeB7.png?1)

Version 1.0.17-20160829110024+c4e8dc8 (1.0.17-20160829110024+c4e8dc8)
OS X El Capitan 10.11.6 (15G31)

**Comment by strib** [comment]
Is there any chance you typed "/keybase/keybase-issues" into your browser or elsewhere that takes a URL?  If so it might have interpreted that as a "file://" URL and looked it up locally, prompting that warning...

**Comment by rob-nash** [comment]
Nah I would have noticed if I typed that

**Comment by strib** [comment]
Hmm, I'm stumped.  The notification is sent when you or some program on your computer tried to look up that folder.  I have no idea why messenger would do that; it seems like something trying to access github without the first part of the URL.  Maybe you can run `opensnoop` and see if you can trigger it again?

**Comment by rob-nash** [comment]
It was quite bizarre. Maybe a red herring. I will re-open this ticket if it happens again. Thanks for your time.

**Comment by rob-nash** [comment]
Happened again. Same conditions. Launched the messenger App. Seems to be reproducible 1/4 times maybe.

**Comment by rob-nash** [comment]
More like 1/2

**Comment by rob-nash** [comment]
Tried open snoop. Dtrace requires privileges. You know how to grant privileges ?

**Comment by rob-nash** [comment]
Have removed the app for now. Will try again in future release.
