### ISSUE TITLE
gpg: signing failed: Inappropriate ioctl for device when trying to import key using cURL + Bash + GPG

### ISSUE THREAD

**Issue by tanto259** [keybase/keybase-issues#2539]
When trying to import using the given curl command in the bash terminal, I got 
```
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
```
followed with
```
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string
```

Note: 
* Using GnuPG 2.1.11 and cURL 7.47.0 and GNU bash 4.3.46(1) with Ubuntu 16.04.1 Xenial on Windows Subsystem for Linux (Beta).
* I also replaced the **gpg -u '_key fingerprint_' -a --sign** to **gpg2 -u '_key fingerprint_' -a --sign** since I am using an ECC key

**Comment by maxtaco** [comment]
My guess is a pinentry in problem

**Comment by tanto259** [comment]
It is the pinentry, it somehow won't pop up when executing the curl command. Got it fixed thanks for your help.
