### ISSUE TITLE
keybase pgp select does not display beginning of fingerprint

### ISSUE THREAD

**Issue by slizzered** [keybase/keybase-issues#2545]
When trying to verify my PGP key, I follow the instructions from the app.
The first command issues some warnings and Key IDs that do not match the beginning of my PGP Key IDs:  
```
$ keybase pgp select

▶ WARNING GPG index error at line 3: Unknown subfield: grp
▶ WARNING GPG index error at line 8: Unknown subfield: grp
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    2048R   XXXXXXXXXXXXXXX             Carlchristian Eckert <xxxx@xxxx>
2    2048R   YYYYYYYYYYYYYYY             Slizzered <xxxx@xxxx>
Choose a key: ▶ WARNING GPG index error at line 11: Unknown subfield: grp
▶ WARNING GPG index error at line 15: Unknown subfield: grp
▶ WARNING GPG index error at line 19: Unknown subfield: grp
```
Instead, the IDs `XXXXXXXXXXXXXXX` and `YYYYYYYYYYYYYYY` match somewhere in the **middle** or **end** of my public keys:
```
aaaaaaaaaaaaaaaaaaaaaaaaaXXXXXXXXXXXXXXXaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbYYYYYYYYYYYYYYY
```
This feels very counter-intuitive, since most tools (like enigmail) use the **beginning** of the PGP fingerprint.

```
$ gpg --version
gpg (GnuPG) 2.1.15
libgcrypt 1.7.3

$ keybase version
Client:  1.0.17-20160901161729+3f83b35
Service: 1.0.17-20160901161729+3f83b35
```

**Comment by maxtaco** [comment]
Those `grp` warnings are due to changes in the new GPG that we don't yet support.  As for the fingerprints, I didn't realize that some apps do it differently.  We just use the same convention as the GPG command line client for taking bottom 64-bit suffixes.
