### ISSUE TITLE
[client][proof][web] not-all-lower domains broken 

### ISSUE THREAD

**Issue by ax3l** [keybase/keybase-issues#2546]
since today, running `keybase id [-s] user` seems to be broken for http if the scheme `.well-known/keybase.txt` is used.

In my example, I have two domains set up. Both via http only (buh!) and one with `/keybase.txt` and an other with `/.well-known/keybase.txt` via GitHub.

Running the id lookup failes the second:
```bash
$ keybase id -s ax3l@github
▶ INFO Identifying ax3l
✔ public key fingerprint: 6FB0 32DD 5150 5348 E982 E100 472D 2C36 4E21 D94B
✖ Proof for openPMD.org failed: Bad hint from server; didn't recognize API url: http://openPMD.org/.well-known/keybase.txt (code=304)
✔ admin of plasma.ninja via HTTP: http://plasma.ninja/keybase.txt
✔ "ax3l" on github: https://gist.github.com/69da4c96aa19ed49fb664fe3beeffd28
✔ "axccl" on twitter: https://twitter.com/axccl/status/772200877679575040
```

The site in trouble is hosted on GitHub
```bash
$ curl -I http://openPMD.org/.well-known/keybase.txt          
HTTP/1.1 200 OK
Server: GitHub.com
Date: Mon, 05 Sep 2016 17:00:21 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 2968
Last-Modified: Mon, 05 Sep 2016 16:48:50 GMT
Access-Control-Allow-Origin: *
Expires: Mon, 05 Sep 2016 17:10:21 GMT
Cache-Control: max-age=600
Accept-Ranges: bytes
X-GitHub-Request-Id: 95DC3F19:C724:21899C6:57CDA4A5
```

**Comment by ax3l** [comment]
Found why, [urlBase](https://github.com/keybase/client/blob/b091059021e499ec698710cb6b228074ed4bbd3b/go/externals/proof_support_web.go#L52-L54) is not `ToLower()`. and I was fancy enough to get the spelling `openPMD.org` approved :P

**Comment by mlsteele** [comment]
Fixed in https://github.com/keybase/client/pull/4305

Thanks @ax3l!

Btw, the kbfs proofs is vendored from client, so it'll be updated as a dependency.
