### ISSUE TITLE
Keybase version stuck at 0.8.23 even after following update instructions on Ubuntu 14.04-based system

### ISSUE THREAD

**Issue by stragu** [keybase/keybase-issues#2549]
Hi there

Sorry of this has been brought up before, but I couldn't find anything similar.

I installed keybase a whiiiile ago, and wanted to update today. I followed the instructions on keybase.io/docs/the_app/install_linux:

```
curl -O https://prerelease.keybase.io/keybase_amd64.deb
sudo dpkg -i keybase_amd64.deb
sudo apt-get install -f
run_keybase
```
After that, the squirrel appears in the terminal, and the GUI is stuck forever with the "Loading..." screen.

To check the keybase version, I try two methods with different results:

```
~> apt-cache policy keybase
keybase:
  Installed: 1.0.17-20160906160030.1f66ba7
  Candidate: 1.0.17-20160906160030.1f66ba7
  Version table:
 *** 1.0.17-20160906160030.1f66ba7 0
        500 http://prerelease.keybase.io/deb/ stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

and

```
~> keybase version
keybase (keybase.io CLI) v0.8.23
- node.js v0.10.25
- gpg (GnuPG) 2.0.22
- libgcrypt 1.5.3
Identifies as: 'keybase.io node.js client v0.8.23 linux'
```

If I try to prove an HN identity, I get the following error:

```
~> keybase prove hackernews chtfn
error: Upgrade is required! Please download v1.0.16 from https://keybase.io/download -- now with KBFS!
```

Any idea what might be going on?

**Comment by cjb** [comment]
Perhaps the old version of Keybase is in /usr/bin/keybase and the new version is in /usr/local/bin/keybase, which is later in precedence order in your PATH.

**Comment by stragu** [comment]
Yep you are spot on:

```
 ~> ../../usr/bin/keybase version
Client:  1.0.17-20160906160030+1f66ba7
 ~> ../../usr/local/bin/keybase version
keybase (keybase.io CLI) v0.8.23
- node.js v0.10.25
- gpg (GnuPG) 2.0.22
- libgcrypt 1.5.3
Identifies as: 'keybase.io node.js client v0.8.23 linux'
```

What's a safe way to remove the old version?

**Comment by stragu** [comment]
Righto, all good, I removed the node.js version with the following command:

```
sudo npm uninstall -g keybase
```
Now everything works fine. Thanks for the pointer!
