### ISSUE TITLE
Web Site Verification (non-DNS) Fails

### ISSUE THREAD

**Issue by stonemirror** [keybase/keybase-issues#2551]
As instructed, I placed a file -- the contents are apparently immaterial, I copied a short Python script — on my web server at http://mcfate.us/.well-known/keybase.txt; the command-line utility failed to find it. I duplicate the file at the web root, i.e. http://mcfate.us/keybase.txt; again, the command-line utility failed to verify its existence.

I can see both files in my browser; curl commands to the URLs produce the expected responses.

**Comment by zQueal** [comment]
```
λ http http://mcfate.us/keybase.txt
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: close
Content-Length: 754
Content-Type: text/plain; charset=UTF-8
Date: Fri, 09 Sep 2016 03:43:08 GMT
ETag: "1428a-2f2-53c0ab0571790"
Last-Modified: Fri, 09 Sep 2016 03:24:49 GMT
Server: Apache/2.2.15 (CentOS)

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

access_token = "684743-v2W8YFGR0OKoWjbSIkPyFr1rt67Ak9HFiXTWKjssfD4"
access_token_secret = "G3xG4qX0LzVCkBumXnmTVzc3VoK2wIAbuAvXLFDRGdF1C"
consumer_key ="1AMNwMAF5jMTQfcOu64eGe6LG"
consumer_secret = "kz8aYu6tXqxbOilA0wweTyg5Q2zXcuvJ6ZwG82PITDUZiO4GUF"

class StdOutListener(StreamListener):

        def on_data(self, data):
                print data
                return True

        def on_error(self, status):
                print status

if __name__ == '__main__':

        listener = StdOutListener()
        auth_handler = OAuthHandler(consumer_key, consumer_secret)
        auth_handler.set_access_token(access_token, access_token_secret)
        stream = Stream(auth_handler, listener)

        stream.filter(track=['gamergate'])
```

`keybase.txt` doesn't seem to have the contents of your proof within it. This is unexpected and will never verify. Just incase you were unaware when you enter the proof into the command line you're given an output as to what is supposed to be within the `keybase.txt` file.

**Comment by stonemirror** [comment]
As I said, there was no guidance or suggestion provided on what needs to be *in* the file. Having tried it again, I'm seeing the required file contents now; no explanation why they weren't showing up previously. Pilot error, I suppose.
