### ISSUE TITLE
Keybase won't verify my Twitter

### ISSUE THREAD

**Issue by kstorvik** [keybase/keybase-issues#2553]
My verification twitter:
https://twitter.com/knutstorvik007/status/774363988050210817

**Comment by cjb** [comment]
I think you revoked the proof, and maybe added a space or something to the link in the tweet. If I click through the link inside the tweet it says the proof is bad.

**Comment by kstorvik** [comment]
Yeah, looks like a couple of line brakes were inserted in the proof when I copied it from the Keybase Shell. As soon I deleted those it worked like a charm.
