### ISSUE TITLE
Keybase won't prove my coinbase username

### ISSUE THREAD

**Issue by kstorvik** [keybase/keybase-issues#2554]
Error: https://coinbase.com/kstorvik isn't public!
But as far as I can see, it is...

**Comment by 0x4445565A** [comment]
It seems like you haven't placed your proof in the proper section of your profile.

If you see https://www.coinbase.com/kstorvik/public-key there is no proof, as an example here is my coinbase proof.

https://www.coinbase.com/bmar/public-key

**Comment by nnutter** [comment]
@kstorvik Based on [](https://github.com/keybase/keybase-issues/issues/1877#issuecomment-159272730),

> there's a cog wheel on your public profile page from which you can upload a new proof

So go to https://www.coinbase.com/kstorvik/ and then click on the cog wheel in the upper right of the profile card.

**Comment by nnutter** [comment]
@kstorvik Actually, it looks like you already figured that out in which case you probably ought to close this issue.
