### ISSUE TITLE
Add desktop.ini to KBFS notification ignores

### ISSUE THREAD

**Issue by Sanqui** [keybase/keybase-issues#2562]
![Notification screenshot](http://sanqui.sweb.cz/screen/2016-09-15T19%3A59%3A34-Selection.png)

A Wine application was generating this notification.  I got told on IRC to make an issue to have `desktop.ini` added to ignores.

**Comment by malgorithms** [comment]
thanks!

we're going to get rid of this notification entirely:
   - /keybase/$(something) is not a folder

it should solve your and other people's problems. This notification type is almost always some app that's peeking around for stuff, and it's better if it just doesn't bother you.

**Comment by Sanqui** [comment]
That's great news, I didn't really like the notification either, to be honest!  Thanks!
