### ISSUE TITLE
sign-up error

### ISSUE THREAD

**Issue by KasiaCat** [keybase/keybase-issues#2564]
Hi team,

Once I try to signup, I put my e-mail address, login, hostname and invitation code received via e-mail.
I received error message: ERROR Failed to get getpin greeting: EOF".
I'm unable to signup.
Is it possible that invitation code received 9 day ago has expired?
Could you generate a new one?

Regards,

**Comment by maxtaco** [comment]
Hi, which version of keybase are you running?  Can you do a `keybase log send`?  Thanks

**Comment by KasiaCat** [comment]
Hi,

It's:
kasiacat@debian:/keybase$ keybase version
Client:  1.0.17-20160916160035+9aa63e0
Service: 1.0.17-20160916160035+9aa63e0

my log id: 4bff1b70a8d44df0aed1771c

kasiacat@debian:~$ keybase signup
Your email address:
Your invite code (leave blank if you don't have one):
Your desired username:
A public name for this device [home computer]:
▶ ERROR Failed to get getpin greeting: EOF




2016-09-16 21:27 GMT+02:00 Maxwell Krohn <notifications@github.com>:
