### ISSUE TITLE
Log in to another username

### ISSUE THREAD

**Issue by Mosesofmason** [keybase/keybase-issues#2565]
I share computer with others, I want other people sharing the computer could use Keybase under the same account too. I know I can logout my Keybase session by command `keybase logout`. However, when I try to login (`keybase login`), the Keybase app do not asking username, it just asking for original user's passphrase. There is no box to entry other people's username.

**Comment by cjb** [comment]
Are you using the GUI app or the command line? The GUI app has a dropdown that lets you choose "Someone else.."

**Comment by Mosesofmason** [comment]
Thanks! I am always using the command line, never look carefully in the GUI. Hope command line add this useful switching soon :)

**Comment by juanminm** [comment]
@Mosesofmason There should be that option. Instead of `keybase login` use `keybase login username` to log in with the other account.

**Comment by Mosesofmason** [comment]
@juanminm Thanks for the tip. It works.
