### ISSUE TITLE
Link to Github Proof should include commit

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#2567]
## About

If you look at the keybase user [ktf](https://keybase.io/ktf)'s Github proof on the website you will see https://gist.github.com/274e6160c0639aeaee87d2fe3ed7c47a.

The Keybase client does not go off of that link so it is not of much use, it looks pretty but is not always correct.

``` bash
[~]$ curl --silent 'https://keybase.io/_/api/1.0/sig/get.json?sig_id=9f8ee08317859eb2ae66a217496a39aa77babc37feb1d0cac62ffcdfa8f3c6040f' | python -c 'import sys, json; print(json.load(sys.stdin)["sigs"][0]["api_url"])'
https://gist.githubusercontent.com/BrandonIngalls/274e6160c0639aeaee87d2fe3ed7c47a/raw/5ffc8a907e41c70d187f22d8d9168e9d4017c8d2/keybase.md
```

In the very least the link that is displayed for the Github Gist should be extended to provide the commit at which the proof was valid...
https://gist.githubusercontent.com/BrandonIngalls/274e6160c0639aeaee87d2fe3ed7c47a/raw/5ffc8a907e41c70d187f22d8d9168e9d4017c8d2

The other option of using the non-raw link will not always work...
https://gist.github.com/274e6160c0639aeaee87d2fe3ed7c47a/5ffc8a907e41c70d187f22d8d9168e9d4017c8d2

The ktf user's proof is an example of altering the git history, the commit where the keybase proof was valid is now orphaned and not accessible unless you know the commit id.

**Comment by maxtaco** [comment]
Thanks for this bug report. Probably the best solution is to show the
pretty human url in the vast majority of cases but to show the raw url in
cases such as this one. We can probably figure that out on the server side
with a fair amount of elbow grease.
