### ISSUE TITLE
How to install it on Sabayon Linux??

### ISSUE THREAD

**Issue by unixbhaskar** [keybase/keybase-issues#2568]
Your install page doesn't specify that. Did you enlist how to get it on gentoo too? 

Please provide the details.

**Comment by nicolasbock** [comment]
I packaged it for gentoo. You can find app-crypt/keybase and app-crypt/kbfs in tree.

**Comment by unixbhaskar** [comment]
well, thanks ..here is the outcome :+1: 

root@SabayonLinux_14:40:18_Mon Sep 19:~#equo install app-crypt/keybase 
╠  @@ Calculating dependencies...
╠  ## [R] [sabayon-weekly] app-crypt/keybase-1.0.17|0   [1.0.17|0]
╠  @@ Packages needing to be installed/updated/downgraded: 1
╠  @@ Packages needing to be removed: 0
╠  @@ Download size: 0b
╠  @@ Freed disk space: 0.0b
╠  @@ You need at least: 11.5MB of free space
╠  ::: >>>  (1/1) 1 package
╠    ## Downloading: 1 package
╠    ## ( mirror #1 ) [app-crypt:keybase-1.0.17.d0f6a02632e5bc3757dd3856ddb1cefc802379c6~0.tbz2] @ http://debian.mirror.dkm.cz
╠   ## Aggregated download: 1 item
╠    # [1] debian.mirror.dkm.cz => app-crypt:keybase-1.0.17.d0f6a02632e5bc3757dd3856ddb1cefc802379c6~0.tbz2
╠    ## Checking package checksum...
╠    ## ( mirror #1 ) [app-crypt:keybase-1.0.17.d0f6a02632e5bc3757dd3856ddb1cefc802379c6~0.tbz2] success @ http://debian.mirror.dkm.cz
╠  +++ >>>  (1/1) app-crypt/keybase-1.0.17
╠    ## Unpacking: app-crypt:keybase-1.0.17.d0f6a02632e5bc3757dd3856ddb1cefc802379c6~0.tbz2
╠    ## Installing package: app-crypt/keybase-1.0.17
╠    ## [Client for keybase.io]
╠    ## Updating installed packages repository: app-crypt/keybase-1.0.17
╠    ## Cleaning previously installed application data.
╠    ## Cleaning: app-crypt/keybase-1.0.17
╠  @@ Installation complete.


bhaskar@SabayonLinux_14:42:00_Mon Sep 19:~>keybase login
▶ INFO Forking background server with pid=10728
bhaskar@SabayonLinux_14:42:26_Mon Sep 19:~>ps -ef | grep keybase
bhaskar  10728     1  1 14:42 ?        00:00:00 /usr/bin/keybase --debug --log-file /home/bhaskar/.cache/keybase/keybase.service.log service --chdir /run/user/1000/keybase --auto-forked
bhaskar  10773  3086  0 14:42 pts/1    00:00:00 grep keybase

**Comment by unixbhaskar** [comment]
Closing this issue as it resolved the requirement.
