### ISSUE TITLE
Could there be a possible bug in Reddit Keybase proof?

### ISSUE THREAD

**Issue by oliahad** [keybase/keybase-issues#2571]
Greetings! Thank you for inviting me :-)

Please see, I've successfully connected my GitHub and Twitter accounts; but, couldn't do it for Reddit. I've tried it three times and I am reasonably certain I've posted the exact texts (the credit actually goes to you as I've simply used the pre-populated form).

Could you please check? Here are the links:
https://www.reddit.com/user/oliahad
https://www.reddit.com/r/KeybaseProofs/comments/53ib1c/my_keybase_proof_redditoliahad_keybaseoliahad/
https://www.reddit.com/r/KeybaseProofs/comments/53i53z/my_keybase_proof_redditoliahad_keybaseoliahad/
https://www.reddit.com/r/KeybaseProofs/comments/53i07c/my_keybase_proof_redditoliahad_keybaseoliahad/

Many thanks in advance for looking into it. Wish you all continued great time and deserving successes! Great user benefits, Keybase :-)

Best regards,
Oli

**Comment by zQueal** [comment]
Oli, it appears that you've been shadowbanned. When you're shadowbanned the Keybase proof scraper is unable to recognize your proof and it will never verify. The best thing you can do is either create a new Reddit account or message the admins to see if they will reverse the ban on your account.

**Comment by oliahad** [comment]
Thank you, @zQueal! Didn't know; will attempt writing the admin first :-) Hope you're having a great day, Zach!
