### ISSUE TITLE
Issues with Keybase file system and Tresorit application on OSX

### ISSUE THREAD

**Issue by jcmurray** [keybase/keybase-issues#2573]
### Description:

I run [Tresorit](https://web.tresorit.com/browse) on OSX as a secure file system replication service between devices. Tresorit uses FUSE technology to provide a user space file system.

After installing Keybase with the Keybase file system and navigating to `/keybase/public/chris` as in the examples I noticed that a folder called  `Keybase` in my Tresorit mount point started to be populated with the contents of `/keybase/public/chris` and synched over Tresorit.

I suspect that there is some interference between FUSE in Keybase and in Tresorit.

### Steps to reproduce

1. Install/start Tresorit on OSX and add a synchronised directory at, say, `~/mytresor`
1. Install/start Keybase as per instructions and version in this email
1. Navigate to `/keybase/public/chris` and watch public content be synched to directory
1. Create a folder in Tresorit mount point `mkdir ~/mytresor/Keybase`

### Observed behaviour

1. Content in `/keybase/public/chris` appears in `~/mytresor/Keybase/chris` and synched across Tresorit devices.

### Expected behaviour

1. No content should appear in `~/mytresor/Keybase`

**Comment by strib** [comment]
Thanks for the report.  I've never used Tresor before, but I can't imagine there's any interference at the FUSE layer -- Keybase installs its own uniquely-named FUSE module in the kernel.

By making `~/tresor/Keybase`, is there any chance that tresor interprets that as you wanting to sync `/Keybase`?  That seems like the most logical explanation given what I read about how Tresor works.  What if you make some other folder like `~/tresor/tmp` -- does it start syncing `/tmp/`?

**Comment by jcmurray** [comment]
Thanks for the insight on FUSE! I think you may be right. I created a directory structure off `/foo` and added `~/tresor/foo` to Tresor -- lo-and-behold Tresor proceeded to synch the whole of `/foo` even preserving symbolic links!

I think this is an issue with Tresor then -- seems an unwanted behaviour to me.

Feel free to regard this issue as resolved. Thanks for your help!
