### ISSUE TITLE
macOS System Integrity Protection off = Keybase not Fully Installing

### ISSUE THREAD

**Issue by jpartain89** [keybase/keybase-issues#2574]
Hello,

While updating [Bartender](https://www.macbartender.com) today, and it requesting I turn off System Integrity Protection for a short time, I had attempted to update Keybase by the `/Applications/Keybase.app/Contents/SharedSupport/bin/updater check`. It never would complete, resulting in a long error message. 

Just now, about 9:35 PM CDT, I restarted and turned SIP back on again, and when my Mac came up, got a nice welcome message from keybase in the browser that said "thanks for installing" and the GUI part of the app also appeared, as it did not before. 

This is probably something that really needs to be added to documentation for macOS users, as at least a basic reminder. 

Thanks !

**Comment by gabriel** [comment]
Do you know what the error message was for the updater? You can send us logs by doing: `keybase log send`.

We fixed the "Thanks for Installing" message recently, so if you haven't seen it, that might come up even if you installed Keybase awhile ago.

Also if you had Keybase running before restarting your computer and had enabled the option to Restore it would relaunch. We're working on not having the GUI come up unless you are starting the app explicitly or are restoring (and the GUI was previously showing).

So currently these things are expected but we are working on making these things less abrupt.

Thanks for the feedback.
