### ISSUE TITLE
Unable to change username

### ISSUE THREAD

**Issue by exmqyu526j** [keybase/keybase-issues#2576]
I meant to make my username the same as my email account, exmqyu526j@gmail.com, for clarity and security.  I accidentally left out the "j" on the end when I chose my username.  Now, it seems impossible to fix that error.  It looks fishy, and there's no way I can currently solve this problem.  It looks like the only option is to create an entirely new set of accounts and try to get another invitation.  Unfortunate.

**Comment by malgorithms** [comment]
yeah, that's correct. we don't allow username changing currently, and may never. there are too many things to get right in the UX, when a username is supposed to equate to a chain of key announcements. sorry!

if you delete your account and need a new invite code, email me.
