### ISSUE TITLE
Windows keybase client installer removes existing dokan installation on install/upgrade...

### ISSUE THREAD

**Issue by cerebrate** [keybase/keybase-issues#2580]
...even when the dokan installation in question is newer (i.e., later version) and/or used by other applications. This can break other dokan-using software, obviously.

**Comment by maxtaco** [comment]
Cc @zanderz

Thanks for the feedback and we are really sorry this happened.  We are working on a fix ASAP

**Comment by zanderz** [comment]
We have a two-phase solution for this. The first phase will come in an update which records the product ID of our driver installation in the registry, and the second phase (tracked internally via https://keybase.atlassian.net/browse/CORE-3743) will look for this key and not overwrite Dokan installations that do not match. Sorry about that!

**Comment by cerebrate** [comment]
The latest update (the one I received today) is still doing this, incidentally, replacing my Dokan 1.0.1 with 1.0.0. 

(Particularly problematic because this still causes https://github.com/keybase/keybase-issues/issues/2595 on recent Windows builds.)

**Comment by zanderz** [comment]
That was still the first phase, sorry about that. It may have brutalized your Dokan, but it has now written to your registry, so the next update will not.

I believe, instead, the installation of the update will fail, so maybe we need a way around that too.

**Comment by cerebrate** [comment]
@zanderz The trouble I'm having at the moment is that because of #2595, the system blue-screens before the installation is complete. If I subsequently replace the Dokan with 1.0.1 to stop the blue-screen on startup, I have a partially working Keybase installation (the main functionality works and I believe has been upgraded, per keybase version:

```
Client:  1.0.17-20161024112511+4dcf351
Service: 1.0.17-20161024112511+4dcf351
```

...but the Start Menu shortcuts are both default icons with no targets, and when run directly from the .exe, the GUI refused to start with the error in the attached screenshot:

![keybase-error](https://cloud.githubusercontent.com/assets/371623/19781517/2bf446c0-9c4f-11e6-8c27-7e58bf67ad45.PNG)

) However, it doesn't look like it's written Dokan information to the registry, at least not in what I suspect to be the location:

![keybase-reg](https://cloud.githubusercontent.com/assets/371623/19781604/9fab8da8-9c4f-11e6-9144-e881463d8699.PNG)

If I'm correct about that, is there any way I can enter such information manually into the registry to prevent a repeat of this problem with the next update? And if so will that, or is there any other workaround to, prevent Dokan from being replaced in this update? I'd like to try a repair to get the shortcuts and GUI working, but if it's going to replace Dokan and then blue-screen before the installer completes, that's not going to work.

**Comment by zanderz** [comment]
ugh, we really need an option to just install Keybase with no drivers, then. I'm afraid you're stuck otherwise. You found the registry keys, the dokan product codes, but in a mismatch the installer will just quit. We'll have to add this feature to our installer.

**Comment by cerebrate** [comment]
Sounds like that'd be best, and I'd certainly appreciate it.

(I got it working this time, FWIW, by firing up a Amazon AWS VM, installing it there, then cloning that install to my local machine with the exception of keeping my config files and existing Dokan. Seems to be running fine, but it's a bit of a circus to have to go through... :) )

**Comment by zanderz** [comment]
https://keybase.atlassian.net/browse/CORE-4038

**Comment by cerebrate** [comment]
This appears to no longer be a problem in recent updates, so closing my report.
