### ISSUE TITLE
Keybase updater (on Windows) can launch installer multiple times

### ISSUE THREAD

**Issue by cerebrate** [keybase/keybase-issues#2583]
I was away from my desk for a few hours, and came back to four separate instances of the Keybase installer on my desktop. It should probably check to ensure that it hasn't already got an installation in progress before launching another one.

**Comment by maxtaco** [comment]
Thanks for the report. I believe this is fixed in the upcoming release.

Cc @zanderz

**Comment by cerebrate** [comment]
This appears to no longer be a problem in recent updates, so closing my report.
