### ISSUE TITLE
Forgot password 

### ISSUE THREAD

**Issue by tsbates** [keybase/keybase-issues#2584]
Hey, 

So I've forgotten my password, and apparently used a 10 minute email address to create the account. Is there anyway I can reset the password by verifying myself (domain, twitter or similar) and have the pass reset? I can even provide the invite url I given if needed.

**Comment by tsbates** [comment]
Figured it out. I had my email set to blah@tsbates.con, not dot com... Anyway I can have a password reset sent to my actual email?

**Comment by malgorithms** [comment]
I think we're good! can you try rese
