### ISSUE TITLE
Verifying website hosted on github

### ISSUE THREAD

**Issue by eirannejad** [keybase/keybase-issues#2590]
How can I verify a website that's hosted on github? The website verification system only keeps the domain name (<username>.github.io) and removes the repository name.

**Comment by juanminm** [comment]
If you have a keybase.txt file or a .well-known/keybase.txt after including .well-known in _config.yml (`
include: [".well-known"]`)  in the username.github.io repository, and then pushing the repository it should work correctly.

**Comment by eirannejad** [comment]
Here is the link. Browser opens it with no issue but keybase says 'Failed'
[https://eirannejad.github.io/keybase.txt](https://eirannejad.github.io/keybase.txt)

**Comment by juanminm** [comment]
Could it be that it needs to have an index.html so that Github stop giving the Error 404 page file on https://eirannejad.github.io, so that it can then search for https://eirannejad.github.io/keybase.txt? Even Firefox developer tool says it gives a 404 error.

**Comment by eirannejad** [comment]
Nope. Pushed an `index.html` file and still fails.

**Comment by k0mach1** [comment]
I found that the problem of @eirannejad 's page https://eirannejad.github.io/keybase.txt has already been solved, so this issue should be closed.

**Comment by eirannejad** [comment]
@k0mach1 Thank you!
