### ISSUE TITLE
keybase file system

### ISSUE THREAD

**Issue by ChrisFernandez** [keybase/keybase-issues#2593]
Idk if this is a bug or I am just doing it wrong..
when in my laptop if I drop a file into /keybase/private/name
it wont show up on my desktop ever.. under same directory
and vice versa even do is the same account..
whats going on?

**Comment by strib** [comment]
Hi @ChrisFernandez -- this is the same underlying issue as #2594 -- one device is on a conflict branch.  Let;s track it over there.
