### ISSUE TITLE
Leveldb/storage corrupted or incomplete meta file

### ISSUE THREAD

**Issue by martindevans** [keybase/keybase-issues#2600]
I haven't used keybase on my laptop (Windows 10) for a while. I came to update it today and now when I try to login it gives me the following error:

![untitled](https://cloud.githubusercontent.com/assets/177519/19021030/5f7aacbc-88b0-11e6-9454-536089fb54ae.png)

This *may* have been caused by the update installation being interrupted (I slept my laptop mid install, oops). The installation resumed after boot up, complained about something (the error message closed itself before I could read it) and then completed.

I suspect I could just complete uninstall and reinstall keybase to fix this, but is there any additional info you'd like before I do this?

**Comment by maxtaco** [comment]
Cc: @zanderz 

We've gotten some isolated reports of this problem, but we'll look further into it.

For now, you can `keybase db nuke` from the CLI and that should workaround the issue.

**Comment by martindevans** [comment]
I can log in now, thanks :D

**Comment by maxtaco** [comment]
@martindevans which release are you on?

**Comment by martindevans** [comment]
C:\Users\marti\AppData\Roaming\Keybase>keybase version
Client:  1.0.17-20160908172133+f09996a
Service: 1.0.17-20160908172133+f09996a
