### ISSUE TITLE
website proof fails after enabling TLS

### ISSUE THREAD

**Issue by chadmiller** [keybase/keybase-issues#2601]
I used Lets Encrypt to add encryption to chad.org for qengho account. I got email that night that the proof was invalid, and at re-trying on the web site, it says there's an error. I don't see a request arrive at my web server, I think.

**Comment by mlsteele** [comment]
Hi @chadmiller 

Is this the error you get when you `keybase id chadmiller`?
```
✖ Proof for chad.org failed: API network error: Get https://chad.org/keybase.txt: x509: certificate signed by unknown authority (code=170)
```

We use a similar cert authority bundle to Firefox and it looks like your https cert doesn't work in Firefox. It could be your server isn't configured to serve intermediate certs or something like that. My recommendation would be to get your https site working on Firefox and then keybase should be able to verify it again.

Also, the `http` protocol is embedded in your proof, so it is following your 301 to find the proof. You can strengthen your proof by replacing it with an https version by going to https://keybase.io/qengho and click "http" -> "Replace". From then on clients will not go through http. You can try this now, but it will probably only work after fixing your https setup.

**Comment by chadmiller** [comment]
Found it. The chain certificate was the wrong one. At Let's Encrypt, they have several different chain certificates, 

I had this one, which was wrong for me. It might be right for others. Which one is right depends on what your issued key is signed from.

https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem

https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem

Weirdly, chrome and chromium had no trouble with it.
