### ISSUE TITLE
Do not mount keybase FS on /keybase – bad idea

### ISSUE THREAD

**Issue by smurfix** [keybase/keybase-issues#2606]
run_keybase mounts the keybase FS on /keybase. This is a bad idea, for multiple reasons:

* what about multi-user systems?

* The user can easily stop the kbfsfuse process and thereby hang any program which enumerates the root file system. This is a very bad idea.

* The same thing happens by accident if the kbfsfuse process takes too long to respond, e.g. when the network connection is broken or flaky.

Please use $HOME/keybase. Or /media/$USER/keybase. Or /run/user/$UID/keybase. The latter is probably best, because nobody ever enumerates it. You can add a symlink from $HOME to it.

**Comment by strib** [comment]
See the discussion of this elsewhere, e.g. keybase/client#3349 for the macOS side of things.  Short answer is we want global paths, and no other argument so far including those above have dissuaded us from that.

We don't support multi-user systems yet, but when we do `/keybase` will likely be a special redirect mount that does redirect to somewhere in $HOME, depending on who the current user is.

**Comment by nh2** [comment]
Also in fairness, this is not a keybase specific problem. The user could do the same thing with `sshfs` or any other fuse based tool. Thus often programs enumerating file systems ensure that they don't descend across file system boundaries; examples would be `find -xdev` or `rsync --one-file-system`.
