### ISSUE TITLE
Twitter proof failed

### ISSUE THREAD

**Issue by jbedo** [keybase/keybase-issues#2607]
My twitter proof failed. I tried posting from two different clients and neither of them succeeded. My twitter username is @jbedo and I'm keybase.io/bedo. My tweet with the proof is at https://twitter.com/jbedo/status/783282472557707264

**Comment by zQueal** [comment]
You're missing `Verifying myself:`.

https://twitter.com/zqueal/status/449697262059663360

**Comment by jbedo** [comment]
That was it, problem solved! Thanks.
