### ISSUE TITLE
Can't find https proof

### ISSUE THREAD

**Issue by juliusrickert** [keybase/keybase-issues#2608]
I have posted the proof generated by the keybase website to [the .well-known folder](https://juliusrickert.de/.well-known/keybase.txt) on my website.

But keybase refuses to find it.

Placing the proof in [the root](https://juliusrickert.de/keybase.txt) didn't help either.

**Comment by maxtaco** [comment]
Both of those links 404'ed

**Comment by juliusrickert** [comment]
The proof just succeeded after I purged my Cloudflare cache.
