### ISSUE TITLE
login.json API endpoint no longer returns private keys in user object

### ISSUE THREAD

**Issue by eric-zeng** [keybase/keybase-issues#2611]
Hi Keybase folks,

In an application we've been building, we have used `login.json` to retrieve a users' private PGP keys so that we can do encryption/signing client-side. The keys were previously located in `me.private_keys` in the return value of the response. 

However, at some point in the past month or so, we no longer get the full user object after logging in. Instead, we only get the fields `id` and `basics`. Here are the results from a call to `login.json`:

```javascript
{
  "status": {
    "code": 0,
    "name": "OK"
  },
  "session": "...",
  "uid": "...",
  "me": {
    "id": "...",
    "basics": {
      "username": "ericzeng",
      "ctime": 1444081693,
      "mtime": 1444081693,
      "id_version": 14,
      "track_version": 3,
      "last_id_change": 1469649358,
      "username_cased": "ericzeng",
      "salt": "...",
      "passphrase_generation": 1
    }
    /* Missing extra fields in 'me' here */
    /* private_keys: {...} */
    /* public_keys: {...} */
  },
  "csrf_token": "..."
}
```

What's up with that? And if it's an undocumented API change, is there an alternative way to get a private key?

**Comment by maxtaco** [comment]
Sounds like a regression.  I will take a lot tomorrow.  Thanks and sorry
for the bug!

**Comment by maxtaco** [comment]
Should be fixed...

**Comment by eric-zeng** [comment]
Verified on our end. Thanks Max!
