### ISSUE TITLE
couldn't associate twitter handle

### ISSUE THREAD

**Issue by jhaar** [keybase/keybase-issues#2612]
Using your web interface, I associated my jhaar-keybase-io@whanau.org account successfully with my jhaar github account. I then tried to do the same with my twitter jhaar account, but it failed. 

I initially did a cut-n-paste into a tweet and that was not detected by keybase. I then used to push-button to auto-fill in a tweet, and when I published that, Twitter told me "You have already sent this message". So I am confident exactly what was requested by me was done - but it didn't work

Then within 1/2 hour I received an email from keybase saying "your twitter (@jhaar) proof has failed". I also noticed I now have a red twitter icon in my keybase profile. Clicking on that, it says "your proof has failed for over a day" - well it's only been a couple of hours :-)

**Comment by maxtaco** [comment]
your tweets are protected; we explicitly say you need to tweet publicly
