### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by codenameflip** [keybase/keybase-issues#2614]
Whenever my MacbookPro boots up I get a keybase error when my mac is trying to boot up the application.

The dialog looks like: http://prntscr.com/cre1tj
And the explicit error code provided is: 

`Installer: 1.1.42
Privileged Helper: Installed, Bundle Version: 1.0.29, Version: 1.0.29
Updater: Unknown, Install Error: Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater
Service: Unknown, 
Fuse: Unknown, 
Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 

Log:
Version: 1.1.42
Installables: (
    "<KBHelperTool: 0x7fd164d5d6e0>",
    "<KBUpdaterService: 0x7fd164daffe0>",
    "<KBService: 0x7fd164db8db0>",
    "<KBFuseComponent: 0x7fd164db9040>",
    "<KBMountDir: 0x7fd164d42bc0>",
    "<KBFSService: 0x7fd164d468c0>",
    "<KBCommandLine: 0x7fd164d58b00>"
)
Install: Privileged Helper
Connecting to keybase.Helper (privileged=1)
Connected
Helper version: {
    build = 2;
    version = "1.0.29";
}
Helper version: {
    build = 2;
    version = "1.0.29";
}
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater
Task error: Error Domain=Keybase Code=-210 "Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater" UserInfo={NSLocalizedDescription=Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater, NSLocalizedRecoveryOptions=(
    OK
)}
Task EOF
Already completed, skipping (completion)
Install complete
Privileged Helper: Installed, Bundle Version: 1.0.29
Version: 1.0.29
Updater: Install Error: Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater`

This action seems to log me out of Keybase on my mac altogether and will freeze up the application when trying to log back in!

-codenameflip

**Comment by malgorithms** [comment]
thanks! we're aware of this issue (I got it too) and working on a fix.

**Comment by harmon** [comment]
👍

**Comment by gabriel** [comment]
Timeout issues should be resolved in recent builds.
