### ISSUE TITLE
Notification on boot

### ISSUE THREAD

**Issue by maxcb97** [keybase/keybase-issues#2617]
When logging in, keybase will show the "You have accessed Chris' public folder". I tried using rmdir on the folder, but it reappeared the next boot.

Ubuntu 16.04
Keybase version 1.0.17-20161007160040.61672fe

**Comment by strib** [comment]
Sorry for the inconvenience.  Something on your system has probably saved the path in a list of recently- (or previously-) visited locations, and is crawling it.  If you can't figure out which application has done that, you might consider following `chris` to avoid seeing the popup.  You can follow him locally just on your device with `keybase follow -l chris`, so it doesn't have to be a public statement of trust if you don't want it to be.

**Comment by maxcb97** [comment]
Following worked. Thanks.
