### ISSUE TITLE
Keybase.io Database Leaked

### ISSUE THREAD

**Issue by qwerty99501** [keybase/keybase-issues#2623]
Hi. I am neither stating that I did or did not leak the user database, but the details of over 7,000 Keybase.io accounts has been leaked and is being sold. Obviously, your private keys are encrypted with your chosen password, but users with weak passwords should change them immediately. I have not verified the authenticity of the dump yet, but it looks to be legitimate, as all of the users in the dump are in fact, existing users of Keybase. I am bringing this to your attention as a privacy enthusiast, plus I have used the service. I do not know how the data was leaked, but server security & SSH logs to the server should be checked, along with checking for SQLi vulnerabilities; who knows if the server may be rooted or such. Below I have included an encrypted paste link to the first three users' information in the dump for verification.

This URL expires in 30 days from this post, and the password for it is (no spaces at start or beginning): kTb4m242LHp6m42!
Link: https://defuse.ca/b/6kVRXAS3Ikiuk1A7oJxmAb

Also, I have not contacted the owners of Keybase, as they have no support email and I do not user Twitter.
As an additional note, none of the accounts I have created or are known to have be created in the last ~5 months are in the leak. The leak is _probably_ older than that.

Sincerely,
~acorns

**Comment by maxtaco** [comment]
?

This is all public data

**Comment by maxtaco** [comment]
Is there any non-public data in the "leak"?

**Comment by zQueal** [comment]
I'd be really interested for an update, too. Since the paste contains public information, I don't see a need to keep it a secret. Here's a screenshot of the page for anyone wondering.

![ayvqid](https://cloud.githubusercontent.com/assets/239193/19372951/2cf9287c-918e-11e6-8d45-c4b24d4daf62.png)

**Comment by notstevek** [comment]
Like @maxtaco and @zQueal already stated, this seems to be all public data. Can you share any other information? This is how keybase authenticates your accounts. These in particular are for twitter.

Example of such, the first line in your pastebin links to this: https://twitter.com/logitek/status/766930850860589056

**Comment by malgorithms** [comment]
I'm going to close this issue out - we can reopen if someone posts proof otherwise. Our entire site's merkle tree is public, which can be traversed to all users' full signature chains, containing all public statements and all usernames.  It can be spidered without any kind of API key, by design. In fact, we'd be happy for people to mirror keybase.

One user on twitter reported that a summary of the data saying it was usernames only: https://twitter.com/fuska__/status/785952649933885440
