### ISSUE TITLE
Keybase Exports GPG Private Keys 

### ISSUE THREAD

**Issue by jandrusk** [keybase/keybase-issues#2624]
It appears when you want to add a GPG key through Keybase that the process exports your private key to the backend Keybase servers. I ran through the process and sure enough when I chose to add an existing key it prompted me for the password for my private key so it could export it. 

I'm not sure where the app is sending private keys, but this completely breaks Public Key Crypto! The private key is to forever remain known only to the owner of the key. Assuming the private keys are being stored on the backend, if that store is ever compromised every users GPG key would need to be revoked and everything they used to encrypt & sign would be compromised if their private key password was cracked. 

I realize this software is in the Alpha stage, but this really needs to be fixed ASAP. 
![keybase_evil_private_key_export](https://cloud.githubusercontent.com/assets/1035829/19406443/a8042038-9253-11e6-8e34-ae9d3dee7dd5.jpg)

**Comment by maxtaco** [comment]
Hi, that's not true, the private key isn't exported to the server.  Which command did you type?  See `keybase help gpg` for what's going on.

**Comment by jandrusk** [comment]
I see, the dialog box is misleading. I'm glad it's not copied to the server ;) #3 in the help for 'keybase pgp select' says, "copy a version of secret key to your local keybase keychain;" What happens if my GPG secret key changes? Will it request the passphrase to sync them back up again?

**Comment by linux-modder** [comment]
Yes, it assumes a change has happened and treats a change as a initial instance.
