### ISSUE TITLE
gpg command is incorrect on MacOS+HomeBrew

### ISSUE THREAD

**Issue by pablobm** [keybase/keybase-issues#2634]
The "hardcore" (bash+gpg+curl) instructions for following do not appear to be correct on MacOS.

I'm on Yosemite and gpg is installed using HomeBrew. I have both v1 and v2 installed, and the binaries are called `gpgv1` and `gpgv2`. Therefore, the first problem is that the command you give uses `gpg`, which doesn't exist on my system.

I tried replacing that with either `gpgv1` or `gpgv2`, but this fails again, this time with the message `gpgv: invalid option "-u"`.

(Note that the error message mentioning `gpgv` without a number at the end is not a typo. Both versions say that).

**Comment by juanminm** [comment]
Strange that it has `gpgv1` and `gpgv2` but not `gpg1` and/or `gpg2`. `gpgv1` and `gpgv2` are stripped versions of `gpg1` and `gpg2` respectively used for checking signatures only. It cannot be used for signing nor encrypting, and this are the only commands as far as [documentation](https://www.gnupg.org/documentation/manuals/gnupg/gpgv.html) is correct.

I don't know how GnuPG is installed with Homebrew (I assume you did `brew install gnupg gnupg2`?) but GnuPG official page recommends [GPGTools](https://gpgtools.org/) (for GnuPG 2.0 (stable), I think) or [GnuPG for OSX](https://sourceforge.net/p/gpgosx/docu/Download/) (for GnuPG 2.1 (modern))

**Comment by pablobm** [comment]
Oh pants. You are right. There are indeed `gpg1` and `gpg2` binaries, but I had missed them because the `-v-` ones caught my eye instead. Using those works. 

Thank you for your time!
