### ISSUE TITLE
Can't add key

### ISSUE THREAD

**Issue by tulir** [keybase/keybase-issues#2636]
I seem to have broken my account (https://keybase.io/tulir) while trying to switch to a new key.
I can't log in on the desktop app (`ERROR eldest called on user with existing eldest KID`, log ID `a137615c324e4487d6fe8c1c`). The web interface says that I need to add a key, but when I tried to add one, I got the `KEY_NEED_REVOKE` error. Creating keys through the web interface doesn't work either. Even though the creation finishes, the key doesn't appear.

**Comment by maxtaco** [comment]
yeah looks like you revoked your last device.  We should put in better protection against this.  I went ahead and reset your account.

**Comment by tulir** [comment]
Thanks, it's working now.
