### ISSUE TITLE
Can't login at command line, get KID error (website login fine)

### ISSUE THREAD

**Issue by conornash** [keybase/keybase-issues#2645]
I'm trying to login to Keybase through the command line (version 1.0.18) but I get the following error:

`ERROR eldest called on user with existing eldest KID`

I can still login to the website without issue. What can I do to be able to login through the command line again?

**Comment by oconnor663** [comment]
It looks like your PGP key is expired, and that's probably what's causing errors here. If you bump the expiration time and then upload the new key via the website (example screenshot below), I think that will fix you.

![image](https://cloud.githubusercontent.com/assets/860932/19863018/f9bc298a-9f68-11e6-87d7-4f7187ba6293.png)

That said, the error we're showing you is super confusing. When I try `keybase id conornash` I at least see some relevant warnings before the cryptic error, like this (not great that it's duplicated three times):

```
▶ WARNING Checking status of key 0101f07b8dd0addfeb5a75994cb4de702364d50991d2fcc78016d90c201f1713b7ee0a
    with respect to time [Mon Oct 31 12:53:50 -0400 EDT 2016],
    found it had expired at [Thu Apr 2 18:02:52 -0400 EDT 2015].
▶ WARNING Checking status of key 0101f07b8dd0addfeb5a75994cb4de702364d50991d2fcc78016d90c201f1713b7ee0a
    with respect to time [Mon Oct 31 12:53:50 -0400 EDT 2016],
    found it had expired at [Thu Apr 2 18:02:52 -0400 EDT 2015].
▶ WARNING Checking status of key 0101f07b8dd0addfeb5a75994cb4de702364d50991d2fcc78016d90c201f1713b7ee0a
    with respect to time [Mon Oct 31 12:53:50 -0400 EDT 2016],
    found it had expired at [Thu Apr 2 18:02:52 -0400 EDT 2015].
▶ ERROR No sigchain was available
```

Do you remember if there were any warnings like that for you?

**Comment by conornash** [comment]
I got the following error a few times:

Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: bad base 64 string

But it worked correctly after a few tries. My issue is solved. Thank you so much for the assistance!
