### ISSUE TITLE
Facebook proof failing

### ISSUE THREAD

**Issue by SyntaxColoring** [keybase/keybase-issues#2648]
My Facebook proof is failing and I'm not sure why.  I retried (with the same proof), but that didn't help.

Facebook post: https://www.facebook.com/SyntaxColoring/posts/1311964075520299
Keybase profile: https://keybase.io/maxpm

**Comment by cjb** [comment]
Thanks, we have a known bug at our end so it might be that.

CC @oconnor663

**Comment by oconnor663** [comment]
Yep, known problem. You have the **Allow search engines outside of Facebook to link to your profile** option disabled in your Facebook settings. That's a case I didn't test before we launched the feature, and it breaks the part of our proof checking that wants to see a link to your profile to confirm that you're really the author of the post. I'll hopefully have a fix up within the next day or two. In the meantime I'm turning off the Facebook proof creation UI on the site.

**Comment by oconnor663** [comment]
In progress: https://github.com/keybase/client/pull/4786 https://github.com/keybase/proofs/pull/51

**Comment by oconnor663** [comment]
Your proof should be succeeding now according to the server. If you're running the Linux client and you install the very latest update, it should also be succeeding according to the client. (macOS and Windows will follow behind shortly.)

**Comment by SyntaxColoring** [comment]
Confirmed.  Thanks!
