### ISSUE TITLE
cannot import pgp key

### ISSUE THREAD

**Issue by eri451** [keybase/keybase-issues#2651]
$ gpg --export -a 0x65f349f2 | keybase --log-file keybase.log pgp import
$ cat keybase.log
▶ DEBUG + loading config file: /home/eri/.config/keybase/config.json
▶ DEBUG - successfully loaded config file
▶ DEBUG + loading updater config file: /home/eri/.config/keybase/updater.json
▶ DEBUG No updater config file found; tried /home/eri/.config/keybase/updater.json
▶ DEBUG Using special root CA for api.keybase.io: -----BEGIN CERTIFICATE----- MIIGmzCCBIOgAwIBAgIJAPzhpcIBaOeNMA0GCSqGSIb3DQEBBQUAMIGPMQswCQYD VQQGEwJVUzELMAkGA1UECBMCTlkxETAPBgNVBAcTCE5ldyBZb3JrMRQwEgYDVQQK...
▶ DEBUG Created Identify2Cache, max age: 5m0s
▶ DEBUG Created LinkCache, max size: 65536, clean dur: 1m0s
▶ DEBUG Created CardCache, max age: 5m0s
▶ DEBUG Can't set GPG_TTY; discover failed
▶ DEBUG Keybase CLI 1.0.18-20161101160102+a862115
▶ DEBUG - Built with go1.7.1
▶ DEBUG - Visit https://keybase.io for more details
▶ DEBUG + configureProcesses
▶ DEBUG Getting flock
▶ DEBUG The server is still up
▶ DEBUG + FixVersionClash
▶ DEBUG Dialing unix:/run/user/1000/keybase/keybased.sock
▶ DEBUG | Contacted service; got version: 1.0.18-20161101160102+a862115
▶ DEBUG | version check 1.0.18-20161101160102+a862115 v 1.0.18-20161101160102+a862115
▶ DEBUG | versions check out
▶ DEBUG - FixVersionClash -> <nil>
▶ DEBUG | After forks; newProc=false
▶ DEBUG + configureLogging
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG | empty socket wrapper; need a new one
▶ DEBUG Dialing unix:/run/user/1000/keybase/keybased.sock
▶ DEBUG | DialSocket -> ok
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG - configureLogging
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG - configureProcesses -> <nil>
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG + PrintOutOfDateWarnings
▶ DEBUG + GetSocket
▶ DEBUG - GetSocket -> ok
▶ DEBUG Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:""}
▶ DEBUG - PrintOutOfDateWarnings
▶ DEBUG Calling shutdown first time through
▶ DEBUG + Account "LoginState - Shutdown"
▶ DEBUG - LoginState: Leaving request loop
▶ DEBUG - Account "LoginState - Shutdown"
▶ DEBUG exiting shutdown code=0; err=<nil>
▶ ERROR No secret key available

**Comment by eri451** [comment]
Ahhhh I see you need the private on your side as well, ha?

**Comment by maxtaco** [comment]
Try 'keybase pgp select --no-import' if you'd prefer. We need a signature
with your private key to prove you own it.

**Comment by eri451** [comment]
sorry same same but different

▶ ERROR ImportKey error: GPG error: exit status 2

what shall I sign? the public part of my key?

**Comment by maxtaco** [comment]
Can you send a `keybase log send`? Someone can hopefully take a look soon (though no guarantees)

**Comment by eri451** [comment]
It was totaly on my side ... just got it right.
Okay so what was it? Of cause pinentry + dbus + not really have gnome3 while having gnome3.

Thanks for the help.

**Comment by maxtaco** [comment]
yeah, that sounds right. Thanks for the follow up.  Man, GPG is hard to support!

**Comment by xkr47** [comment]
Took me a while too to understand I should use `keybase pgp select` instead of `gpg --export abcd | keybase pgp import`..
