### ISSUE TITLE
Absence of Facebook Verification from keybase.io

### ISSUE THREAD

**Issue by akaashmaharaj** [keybase/keybase-issues#2652]
I have notice that there is currently an option to "Search Facebook user names..." at the keybase.io web site, and there are many profiles at the web site that list proven Facebook accounts.

However, there appears to be no option to prove one's Facebook identity at keybase.io (at least when I log in).  I see options only for Twitter, Github, Reddit, coinbase.com, Hacker News, "another web identity", and a Bitcoin address.

Is it only possible to prove a Facebook identity using the app?  Alternatively, is the option to prove a Facebook identity through the web site being rolled out in stages (i.e., currently available only to some users)?  In either case, are there plans to make the option available at the web site for all users?

**Comment by cjb** [comment]
Well spotted! Yes, we're in the middle of rolling it out, it should be live on the website for creating proofs next week.
