### ISSUE TITLE
login.json: no auth system available

### ISSUE THREAD

**Issue by eric-zeng** [keybase/keybase-issues#2655]
Hey y'all,

I haven't been able to log into Keybase using the login.json API endpoint today, I'm getting this error back from the server:

```
{
  "status": {
    "code": 100,
    "desc": "no auth system available",
    "name": "INPUT_ERROR"
  }
}
```

My login code hasn't changed for a while, so I don't think this is on my end. Any assistance would be greatly appreciated!

**Comment by maxtaco** [comment]
We're retiring v3 of the login system and have upgraded everyone to v4.  But I can grandfather in select users if you'd like. (The new system is documented on our API pages)

**Comment by eric-zeng** [comment]
Oops, I didn't see that the login system has changed. I will work on upgrading my client to support v5, so I don't think I'll need an exception for v3. Thanks!

**Comment by maxtaco** [comment]
@eric-zeng what language are you programming in?  I can send you some sample code. Cheers.

**Comment by eric-zeng** [comment]
I'm writing it using JavaScript + npm, for a browser-based client. Thanks!

**Comment by maxtaco** [comment]
Ok, let me whip up some sample code....

**Comment by maxtaco** [comment]
Hey, I threw something up here:

keybase/node-login

It should be all browser-compatible except the `read` dependency, but that's in there just as a demo.

**Comment by eric-zeng** [comment]
Awesome, thanks! This is super helpful.
