### ISSUE TITLE
Web interface doesn't tolerate spaces after hash name

### ISSUE THREAD

**Issue by viraptor** [keybase/keybase-issues#2658]
Gpg itself disregards spaces a the end of lines. This is not the case for the message verifier on the website however. Even more confusing - the spaces are stripped in the error message, so it simply says: `"Error: Unknown hash algorithm: SHA256"` rather than `"Error: Unknown hash algorithm: SHA256 "`

For example this message is verified by gpg, but not keybase.io
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256 

message
-----BEGIN PGP SIGNATURE-----

iQEcBAEBCAAGBQJYI6sYAAoJEHsv2rfg6zbtDxEH/RcCcsG9sgFwaEmk3i+92/8m
cYy5go64JsHyLFOzrtHbkzM9/Eda9AuX9Ys+gAp3kq7ARpBIDTDthoQsbL9yLxrZ
oGb2ToLxn2RmiDPkPotnIVDbs4MJQ122sJQ9xgyhq/uArmw/wuc1UqnBENb3aueN
Ftfp7OF7anKtPw7JRwV1bBE0xmsgQG5W5ZAzoKhCZ/+tnq1ENitHkIGEyUI2oO7/
N5dEyhGU1BszpRi2rN5OctV6YC2P2JuH3RQezooIyXSSftCcFk7GsRrEx7SH4Tps
anejdQJRsQw3jwnGSZyOs28w18DmYrxG/zXVn5PLOBkaryGGWUQZcLAAM4HkTnE=
=4zrS
-----END PGP SIGNATURE-----
```

**Comment by maxtaco** [comment]
Cool, thanks for the report, I'll get a fix in soon...
