### ISSUE TITLE
Keybase equivalent to gpg --clearsign?

### ISSUE THREAD

**Issue by rnkn** [keybase/keybase-issues#2663]
Is there a Keybase equivalent to `gpg --clearsign FILE`?

This signs *and* encrypts
```
keybase pgp sign < message.txt
```
but I'd like to just sign.

**Comment by patrickxb** [comment]
keybase pgp sign < message.txt

will just sign.

    keybase pgp sign --clearsign < message.txt

will clearsign.

    keybase pgp encrypt < message.txt

will encrypt.

    keybase pgp encrypt --sign < message.txt

will encrypt and sign.

**Comment by rnkn** [comment]
Ah thanks. I really probably should have been able to figure this one out myself...

Can I ask, what's the functional difference between `sign` and `sign --detached`? i.e. how is the produced output properly used?

**Comment by linux-modder** [comment]
--detached would be its own .asc so you'd have file and file .asc sign by itself should just make a .asc file
