### ISSUE TITLE
Incorrect "curl/raw" public key link when a user has multiple keys

### ISSUE THREAD

**Issue by ryan-at-morningstar** [keybase/keybase-issues#2665]
Keybase user [avh4](https://keybase.io/avh4) has two public keys.  If I click on the first key listed (fingerprint 79AC6B2F3F6CCA93), the "curl/raw" link in the modal is a link to a file with the correct public key.  If I try to download the second key (fingerprint 11357FB6FDD7BEC0) using its "curl/raw" link in its modal, the [file](https://keybase.io/avh4/key.asc) that is downloaded contains the first public key.  Both links seem to point to the same key.asc file.

**Comment by malgorithms** [comment]
oh nice catch. we hadn't been supporting multiple keys when that was written. hope to get to this soon.

**Comment by RomainMuller** [comment]
I second this one... Currently I manage copies of my personal keys in my public kbfs folder... But this duplication isn't all that useful.

**Comment by Kajisav** [comment]
Noticed this this morning after adding a 2nd key; I make my pubkeys available on my web server via HTTPS and liked being able to link to Keybase as a redundancy. Just wanted to mention that the text inside the modal for the second key does properly show the 2nd key's data at least. Maybe the name format of the curl/raw public key could be changed from key.asc to <fingerprint>.asc or just going key.asc, key2.asc, key3.asc as you add new keys.

**Comment by malgorithms** [comment]
thanks for reporting this one, people. I made a new endpoint (`pgp_keys.asc`) and am deprecating the old `key.asc` one, which doesn't make sense in our multi-key world.

This by default now returns all of your PGP keys (for easy importing)...examples:

### all of the pgp public keys max has 
https://keybase.io/max/pgp_keys.asc

### a specific one
https://keybase.io/max/pgp_keys.asc?fingerprint=8EFBE2E4DD56B35273634E8F6052B2AD31A6631C

I updated the modal that pops up on the website to have links to both version, and it gives an example gpg+curl command using the full import.

also updated site API docs
