### ISSUE TITLE
Installation failure on Windows 10 x64

### ISSUE THREAD

**Issue by Tamerz** [keybase/keybase-issues#2675]
The installer fails with the error message:

`0x80070643 - Fatal error during installation.`

[Keybase_20161119223443.log.txt](https://github.com/keybase/keybase-issues/files/601676/Keybase_20161119223443.log.txt)

**Comment by zQueal** [comment]
> This issue may occur if the MSI software update registration has become corrupted, or if the .NET Framework installation on the computer has become corrupted.

Try uninstalling and reinstalling .NET framework. Use the [.NET repair tool here](http://go.microsoft.com/fwlink/?LinkID=246062) to fix .NET then reinstall the affected version from Microsoft.

[More here](https://support.microsoft.com/en-us/kb/976982).

**Comment by Tamerz** [comment]
Thank you. The repair tool didn't fix the issue, so I used the ".NET Framework cleanup tool" to remove all versions of .NET and rebooted. The installation worked after that.

**Comment by zanderz** [comment]
Wow, great work @zQueal , thank you!
