### ISSUE TITLE
Web identity is  failing

### ISSUE THREAD

**Issue by saikatharryc** [keybase/keybase-issues#2677]
helo, here i added my website ,,and also added the script file in both position it said, but its failed to prove identity.
though my web site is on "http" not in "https".

**Comment by zQueal** [comment]
```
λ http www.saikat.cf/keybase.txt
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html
Date: Sun, 20 Nov 2016 14:34:18 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding

<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("6e3107dde324a938ecc96594da928e2f");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://www.saikat.cf/keybase.txt?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
```

Your webserver isn't serving the text proof for the web scraper. That's why your proof is failing as far as I can tell.

**Comment by saikatharryc** [comment]
any suggestion to solve? @zQueal

**Comment by zQueal** [comment]
Yea, don't serve the page with `aes.js`. Serve it as plain text verbatim. Should work fine afterwards.

**Comment by saikatharryc** [comment]
> yeah i got the solution.
 i didnt done anything with aes.js. and also i dont know where it is actually. its served by host. and my hosting is 

> byethost

and i just used an ssl certificate to make it https from http . and it just worked. 

> if then also not worked , then just use cloudflare integration.

[here is the link of my website](www.saikat.cfl)

![image](https://cloud.githubusercontent.com/assets/15653282/20871701/5ebdab68-babe-11e6-833e-0b98c3536d37.png)
