### ISSUE TITLE
Just a small documentatin issue.

### ISSUE THREAD

**Issue by awood4929** [keybase/keybase-issues#2680]
Not sure if this example is for a specific OS (I ran into this on Windows 10 x64), while logged in to the web account, on page keybase.io/[account name]/devices, the instructions from the drop-down for a host shows:

![keybase_remove](https://cloud.githubusercontent.com/assets/12056414/20544853/e6723022-b0c0-11e6-8d7b-8c936b8e6cca.JPG)

( keybase device remove '09ab9[rest of device id]b2ae18' )

From the Keybase Shell, if I include the single quotes it throws an Invalid Device ID of Unknown Device Name error.  Removing the single quotes and running the command revoked the KIDs (if only that easy to revoke real kids).  Thanks.

**Comment by malgorithms** [comment]
ah thanks, fixed and live.

yeah, revoking real kids is tough, but at least their kid status expires after 18 years.

**Comment by awood4929** [comment]
Thanks.  Love the product, thanks for all the work on our behalf.
