### ISSUE TITLE
Using a URL scheme with keybase as the handler for kbfs instead of the /keybase mount

### ISSUE THREAD

**Issue by trainmeditations** [keybase/keybase-issues#2681]
I realise this issue has been discussed before but I am opposed to having kbfs mounted in /keybase and I really think there will be a lot of pushback against it with wider adoption also.

There's two main issues here:

1. it pollutes the / location and is mounting on all *nix systems in a non standard location
2. it's not compatible with multiple users on the same system

In regards to the first point, the argument is to have a standard way to address a file across all systems. This already doesn't work in Windows anyway, and any scripts that want to access a file from keybase are likely to be different in other ways across Linux or Mac OSX implementations anyway, so having a separate path at access them from for each system doesn't seem like it would be a huge issue.

A standard environment variable pointing to the kbfs root could also be implemented, exported by the run_keybase script when the user logs in.

As for the second point, the issue could be avoided by having kbfs mounted in a user specific location (such as under $XDG_RUNTIME_DIR on Linux systems) and have this environment variable point there.

For an even more cross platform solution that would work even in windows, why not use a keybase URI scheme and have the keybase service set up as the URL handler. keybase://public/userid could point to a users public folder. Most Linux DE's and Windows have ways of registering global URI handlers, this seems to suggest Mac OSX does too (I'm not familiar with it myself) https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x

A combination of an environment variable and a URI handler seems like it would provide as much support (if not more because it would work in Windows as well) rather than just mounting in /keybase

**Comment by strib** [comment]
There is an open discussion about this at #2306, please add to that conversation instead of starting a new issue.  I'll be closing this one.

**Comment by strib** [comment]
See also keybase/client#3349

**Comment by trainmeditations** [comment]
I thought those issues were Mac OSX specific, whereas I'm talking across all platforms.
