### ISSUE TITLE
Setting CA root for "keybase prove https"

### ISSUE THREAD

**Issue by gahr** [keybase/keybase-issues#2686]
How do I set the CA root file for `keybase prove https <url>`?

**Comment by cjb** [comment]
I don't think you can -- other Keybase clients have to verify your proof, not just the Keybase server.

**Comment by gahr** [comment]
It's a valid certificate, as far as most browsers are concerned:
https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem

**Comment by cjb** [comment]
Huh, I thought letsencrypt proofs were working. Might you be missing an intermediate cert in your chain? If it's not that, it'll be because the LTS version of Node we're using doesn't have that root added yet.

**Comment by gahr** [comment]
The path is DST Root CA X3 -> Let's Encrypt Authority X3 -> my cert
The website is https://www.gahr.ch/

**Comment by skwerlman** [comment]
Are you using `fullchain.pem`? I had a similar issue when I was using `cert.pem`, because not all clients trust letsencrypt itself (things like `curl` won't work).

**Comment by gahr** [comment]
Thanks, I'll try that and report results!

**Comment by juanminm** [comment]
It sure may be a chain problem as SSLLabs is giving a warning about it

**Comment by gahr** [comment]
Using `fullchain.pem`solved the issue, thanks!
