### ISSUE TITLE
Can't verify twitter account

### ISSUE THREAD

**Issue by noelweichbrodt** [keybase/keybase-issues#2696]
Public account, multiple attempts. Last two attempts:
https://twitter.com/noelweichbrodt/status/800107978921824257
https://twitter.com/noelweichbrodt/status/804362811824553985

**Comment by maxtaco** [comment]
I don't know why the first one failed but the second failed due to the
unexpected prefix

If you want to try a third time, delete the unexpected prefix but you can
prefix with @keybaseio if you don't want to rebroadcast.

No one else has reported issues so it is likely a mistake on your part.

**Comment by mlsteele** [comment]
The first one has `j.mp` links instead of the expected text and link.

**Comment by noelweichbrodt** [comment]
@maxtaco I've tried a few times (about three more times than I listed) without success. Thanks for the tip about about the prefix.
@mlsteele isn't that twitter's own url shortener thing? would it prevent keybase from following the link?

**Comment by noelweichbrodt** [comment]
Weird, it worked with the @keybaseio prefix. Thanks for the suggestion!

**Comment by mlsteele** [comment]
The tweet text has to include exactly the text we're looking for so machines can easily verify it, so yeah, no url shorteners for now.

Glad it finally worked for you!
