### ISSUE TITLE
Cannot import private PGP key

### ISSUE THREAD

**Issue by Ketchup901** [keybase/keybase-issues#2698]
From the command line it gives the following:  
`$ keybase pgp import -i ~/.gnupg/privkey.asc`  
`▶ ERROR This key is already active. You can't add it twice. (error 923)`

On the website it gives `Error: Unknown signature subpacket: 33`

**Comment by maxtaco** [comment]
Dupe of an earlier issue. We're working on it.  It's a new feature GPG rolled out :/

**Comment by maxtaco** [comment]
See #2668
