### ISSUE TITLE
Is Keybase still invite-only? Doesn't seem like it is

### ISSUE THREAD

**Issue by luisivan** [keybase/keybase-issues#2703]
Hi there!

I just wanted to clarify if Keybase continues being an invite-only system or not, since I just signed up an example user (that I deleted later) without any kind of invite code.
I'm using Keybase for a company project right now and I think we all would benefit from an open Keybase.

Thanks,
Luis

**Comment by malgorithms** [comment]
we're not entirely open - we are playing with letting a certain number of people in without invite codes...so some users don't see the queue when trying to join.

but if you need a bunch of invites for your company, reach out to me and I can set you up.

**Comment by luisivan** [comment]
Thanks @malgorithms, will reach you out in the future, closing this issue for now!
