### ISSUE TITLE
Windows update fails: A previous version of Dokan Library 1.0.1.81 (x64) is already installed

### ISSUE THREAD

**Issue by OliverCole** [keybase/keybase-issues#2706]
> A previous version of Dokan Library 1.0.1.81 (x64) is already installed. Please uninstall the existing version first, reboot the system and start the setup again.

**Comment by zanderz** [comment]
Can you please do a `keybase log send` from the Keybase shell and post the ID, so we can see what state you're in?

You may need to uninstall Keybase and Dokan and re-run the Keybase installer. Your settings and device provisioning will remain.

**Comment by OliverCole** [comment]
Sure: 7b04f87c6069ee631861b11c

**Comment by zanderz** [comment]
I see you were updating from 1.0.17-20160822152935+692af12 ? It is pretty old but it should be supported. We'll test that update path again, but meanwhile I suggest you uninstall both Dokan and Keybase and run the latest installer. Your settings and device provisioning will remain.

**Comment by OliverCole** [comment]
The device was only offline for a few months! Any luck reproducing it?

Where are the settings/provisioning stored? I'd like to back them up before uninstalling.

**Comment by maxtaco** [comment]
Cc @zanderz

**Comment by OliverCole** [comment]
Bump @zanderz ?

**Comment by zanderz** [comment]
We haven't had any luck reproducing this exact error. In that older version, settings and provisioning are stored in %APPDATA%\Keybase, but in newer versions they are migrated to %LOCALAPPDATA%\Keybase. Again, they persist after uninstall, no need to backup.

**Comment by OliverCole** [comment]
OK, all done. Thanks.
