### ISSUE TITLE
DNS based proof should be using a prefix to the base DNS domain name

### ISSUE THREAD

**Issue by cstrotm** [keybase/keybase-issues#2717]
Adding a new TXT record at the APEX (base name of a delegated domain) is a bad design choice, as it can break (keybase and also other applications such as SPF or other Apps that make the same bad design choice).

The IETF has published RFC 5507 "Design Choices When Expanding the DNS" that discusses the problem (section 3.1).

https://tools.ietf.org/html/rfc5507

For keybase a good solution would be to use a prefix to the DNS owner name (domain-name), like

```
_keybase.example.com. IN TXT "foo bar"
```

so all keybase related DNS records would be found under this prefix (sometimes called a "selector")

I've made this comment initially to issue #1722 here breakage is already showing up.

**Comment by mlsteele** [comment]
We do check `_keybase.example.com` so DNS proofs can live either at the apex or at the `_keybase.` sub.

When creating a proof, the command line instructions say:
```
Please save the following as a DNS TXT entry for example.com OR _keybase.example.com:
```

The web instructions if you have a synced key do not mention it.
```
Please enter the following as a TXT entry in your DNS zone,
exactly as it appears. If you need a "name" for your entry, give it @.
```

**Comment by maxtaco** [comment]
We currently allow exactly the feature you ask for.

**Comment by cstrotm** [comment]
Yes, tested and works. The web instructions send me on the wrong path. I will close this issue and open a new one with a re-phrased web instruction.
Thanks for the quick answer.
