### ISSUE TITLE
My Facebook username is less than 5 characters, gets rejected

### ISSUE THREAD

**Issue by jfroy** [keybase/keybase-issues#2729]
My facebook profile username is jfr (you can [verify it yourself](https://www.facebook.com/jfr)). The verification process rejects it nonetheless. I am assuming it is doing a simple length check (5 characters probably), but that restriction is soft and there are people with shorter usernames.

**Comment by omry** [comment]
Hi, I just confirmed my own account that has 4 characters so at least this works :)

**Comment by songgao** [comment]
@jfroy Your FB proof seems to be working fine now. Do you mind me closing this?

(I guess the reason it didn't work the first time was that you didn't set the post to be public?)

**Comment by jfroy** [comment]
No I definitely was blocked because the username was too short. But it appears to have been changed. Closing.
