### ISSUE TITLE
Keybase.io Email?

### ISSUE THREAD

**Issue by drohm** [keybase/keybase-issues#2730]
Silly question, but I have seen some Keybase users with keybase.io email addresses.  If you're currently a user is it possible to get a keybase.io email address or was that a limited-time thing for the earliest adopters?  I haven't found any information in regards to this in the docs so I thought I'd ask here.  Thanks.

**Comment by zQueal** [comment]
> or was that a limited-time thing for the earliest adopters?

I guess you could say that. Keybase used to come with .io email forwarding for users--but this feature [has been discontinued](https://github.com/keybase/keybase-issues/issues/941#issuecomment-185218865) because it distracted devs from Keybase and posed security risks.

**Comment by drohm** [comment]
Thanks @zQueal, figured it was something like that.
