### ISSUE TITLE
twitter proof failed twice

### ISSUE THREAD

**Issue by DeanHaritos** [keybase/keybase-issues#2732]
Here's the most recent of two attempted proofs...
 
![dean haritos on twitter_ _verifying myself_ i am deanharitos on keybase io xclfwu1facdpsty5zyw5oyat6rusro2u03sg _ https___t co_8qvkwti4de_](https://cloud.githubusercontent.com/assets/24662342/21334728/5adb7c4a-c60e-11e6-837d-c165cff3ae37.jpg)

**Comment by cjb** [comment]
Your account is protected, so other people can't see these tweets.

**Comment by DeanHaritos** [comment]
That is a very good point! 

I use twitter so rarely that I didn't even remember that. 

Thank you! Closing issue.
