### ISSUE TITLE
How to use RPC daemon

### ISSUE THREAD

**Issue by luisivan** [keybase/keybase-issues#2733]
Hey there,

I've been looking through your code trying to figure out how to interact with `keybased.sock`.
I've managed to connect to the RPC server using framed-msgpack-rpc, but each time I invoke anything, it gives me back `EofError: EOF from server (code 101)` and `EOF on transport`.

This is my code:

```javascript

client = new rpc.Client(r, 'keybase.1')

client.invoke('user.loadUserByName', { sessionID: 300, username: 'li' }, (err, ...args) => {
  console.log('Error', err)
  console.log('Res', args)
})

```

**Comment by luisivan** [comment]
@MarcoPolo @chrisnojima maybe you guys can shed some light here. Thx a lot!

**Comment by cjb** [comment]
Maybe share your transport (`r`) code too? Does `r.connect()` send you an error?

**Comment by luisivan** [comment]
@cjb it does not throw an error when connecting. This is it:

```javascript
const rpc = require('framed-msgpack-rpc')

const path = `/Users/${process.env.USER}/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock`

const r = new rpc.transport.RobustTransport({
  dbgr: new rpc.debug.Debugger('A'),
  path,
})


r.connect((connErr) => {
  if (connErr) return
  const client = new rpc.Client(r, 'keybase.1')
  client.invoke('user.loadUserByName', { sessionID: 300, username: 'li' }, (err, ...args) => {
    console.log('Error', err)
    console.log('Res', args)
  })
})
```

**Comment by cjb** [comment]
If you run `keybase -d service`, you can see the service's side of the conversation -- in your case it's throwing an error presumably 'cause the arguments aren't correct:
```
2016-12-21T14:27:43.042686 ▶ [ERRO keybase log.go:175] 12e {unix://@} Error in transport: RPC error. type: 0, method: keybase.1.user.loadUserByName, length: 4, error: error decoding message field at position 3, error: only encoded map or array can be decoded into a struct
```

**Comment by luisivan** [comment]
Oh, that was very helpful. I was passing an object, now I'm passing an array with the object and it works. Thanks a lot!!
