### ISSUE TITLE
Outdated comment needs to be removed in keybase pgp key update UI

### ISSUE THREAD

**Issue by grempe** [keybase/keybase-issues#2734]
In the logged in UI there is a dropdown menu item to 'update my key' for the PGP public key. In the popup dialog that follows you have to paste in your updated pub key and then it asks how you want to update.  If you choose 'command line' it provides the command:

```
# easy! just run this
# NOTE: This command won't be available until our new client is released.
keybase pgp update
```

I think the `NOTE` is outdated and should be removed as this command runs without error in my current version of keybase cli.

```
$ keybase pgp update
▶ INFO Posting update for key 497a6138963d6c47202b238ba4a288a3beccae17.
▶ INFO Update succeeded for key 497a6138963d6c47202b238ba4a288a3beccae17.
```

```
$ keybase version
Client:  1.0.18-20161219185928+7868d49
Service: 1.0.18-20161219185928+7868d49
```

**Comment by maxtaco** [comment]
thanks! fixed! will roll out this change shortly
