### ISSUE TITLE
Pinentry dialog is empty when selecting PGP key.

### ISSUE THREAD

**Issue by 0n-s** [keybase/keybase-issues#2749]
Hello.
I am trying to import my pre-existing PGP key to Keybase. The thing is, when it asks
for the password, the password dialog (Pinentry) is white. There seems to be no elements
that my cursor can click.
I'm running Keybase 1.0.18.
![2016-12-31-211606_2390x768_scrot](https://cloud.githubusercontent.com/assets/23233607/21578678/25b75f76-cf9f-11e6-8ff4-a313345f44e6.png)
The white box is the Pinentry dialog.

**Comment by cjb** [comment]
Hi, we'll get a fix released for this soon, in the meantime you could run the import without the GUI running to get a command line prompt instead.

**Comment by 0n-s** [comment]
Works now.
