### ISSUE TITLE
run_keybase reports success even if fuse mount fails

### ISSUE THREAD

**Issue by doron1** [keybase/keybase-issues#2750]
run_keybase reports success (including successful mount) even though the mount fails. In my case it failed cuz the shell user was not part of the "fuse" group - a requirement of the /bin/fusermount setuid bits. I was going sideways in figuring out why I can't even get the thing started, since there is no error (actually explicit success message) when run_keybase is run.

**Comment by strib** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
This has come up for a few people recently. @doron1 what distro are you running? (I do most of my testing on Arch, which doesn't seem to have a fuse group.) @strib, can you think of a reasonable way to launch kbfsfuse and determine something like "it started successfully" without blocking forever?

**Comment by strib** [comment]
@oconnor663: Depends how you want to define successfully, but yeah you can just try `cat /keybase/.kbfs_status` (which blocks on a network call to the bserver) or something like `cat /keybase/.kbfs_profiles/block` (which, ironically, doesn't block).

**Comment by oconnor663** [comment]
Update on this: We're going to ship systemd support soon. (See [here](https://github.com/keybase/client/issues/5355#issuecomment-342590835).) As part of those changes, the `run_keybase` command now runs this:

    systemctl --user start keybase.service kbfs.service keybase.gui.service

The first two services there are `Type=notify`, which means that errors during startup should cause `run_keybase` to report an error.

**Comment by oconnor663** [comment]
(That said, FUSE failing to mount might not prevent startup from succeeding, so it's possible that this specific case would still be hard to report. @strib would know more.)

**Comment by heronhaye** [comment]
Exit code is still zero (some systems don't need/want/can't use the mount) but `run_keybase` should print the error if it did fail to mount now.
