### ISSUE TITLE
Keybase icon suddenly disappeared

### ISSUE THREAD

**Issue by WInf9Kieran** [keybase/keybase-issues#2752]
I got a little problem, nothing serious but still not nice xD
The keybase icon of my keybase drive is just gone. Does anybody know how I can add it again?

**Comment by WInf9Kieran** [comment]
Nevermind. Fixed it by going in HKEY_CLASSES_ROOT\Applications\Explorer.exe\Drives\X\DefaultIcon and setting the correct path to the exe

**Comment by cjb** [comment]
Thanks, CC @zanderz

**Comment by zanderz** [comment]
This is a bug in the Remote->Local migration, tracked with https://keybase.atlassian.net/browse/CORE-4312.
Thanks for the report, @WInf9Kieran
