### ISSUE TITLE
Facebook verification fails

### ISSUE THREAD

**Issue by heytrav** [keybase/keybase-issues#2755]
I've made 3 attempts to verify my Facebook account and both have failed. I believe I am following you instructions correctly and making a public post when instructed (see screenshot). Yet I still get an email saying my post is:
> (a) not there, or (b) not posted precisely.

Although I'm a bit unclear on the definition of _posted precisely_ given that the instructions only said it had to be public and could be whatever I like.

![screen shot 2017-01-04 at 07 26 43](https://cloud.githubusercontent.com/assets/64812/21618338/57ff9c02-d24f-11e6-9a6c-89297698286c.png)

I have no idea what I'm doing wrong and I really dislike making public posts on my FB profile _ever_ so I hope that this doesn't require any more attempts.

**Comment by mlsteele** [comment]
Heyheytrav,

The facebook post has to be created by clicking the link. That will prefill the post with the proof hash. The part about "whatever you like" just means you can add additional text to the post if you'd like, but it must include the link with the proof hash which is prefilled in the popup.

![image](https://cloud.githubusercontent.com/assets/705646/21622153/1dc8bea4-d1ca-11e6-9a2c-1747f6ffd810.png)

If all is going according to plan, it should look like this when you're about to post the post.

![image](https://cloud.githubusercontent.com/assets/705646/21622276/b614cd38-d1ca-11e6-95df-5b872f5fb666.png)

**Comment by heytrav** [comment]
OK, I clicked on the link but didn't see anything like that. Could be
because I log into Facebook using a different browser than I use for other
things 😀

**Comment by mlsteele** [comment]
Yep, that would do it. It should work if you either log in on the same browser or copy the link to the other browser.
