### ISSUE TITLE
Can't reset account using paper key

### ISSUE THREAD

**Issue by sebhans** [keybase/keybase-issues#2759]
Having lost my passphrase (dumb, I know), I'd like to reset my account (sebastianhans) using a paper key - which I still have - but am unable to find out how this works.

First, because I was still logged in on my desktop computer, I tried `keybase passphrase recover`, but this just hung. From reading other issue descriptions, I gather the client should have opened, but it never did. Somewhere in my series of trials I did a `keybase logout`, so this way is closed to me now in any case.

On the website, the account recovery dialog tells me, "You can't reset your passphrase, since you have active device or paper keys. The following devices all have the power to change your passphrase." I take this to mean I can somehow log in with my paper key and use this to change the passphrase (or to generate new keys, which would not be a problem for me), but no matter what I try, I am always asked for my passphrase, never for a paper key.

Maybe I'm missing something obvious, but how the heck is account recovery with a paper key supposed to work?

**Comment by sebhans** [comment]
FWIW, running `keybase passphrase recover` now that I am logged out, yields the following message (emphasis mine).

> Passphrase recovery requires that you are logged in first.
> Please run `keybase login` before `keybase passphrase recover`.
> But don't panic, **you can log in with a paper key**.

Now the question is, how do I do that?

**Comment by maxtaco** [comment]
@miles can you help out?

**Comment by maxtaco** [comment]
Whoops I meant @mlsteele

**Comment by mlsteele** [comment]
Huh. I had thought you could login with a paper key somehow but now can't seem to. If you happen to have another device around without keybase on it then you can provision it with a paper key. That device will then be logged in and you could `keybase passphrase recover` from it.

But we'll definitely fix this case of recovering starting from a paper key and locked device.

**Comment by sebhans** [comment]
Thank you. I don't have another device at hand, so I guess I'll have to wait for the fix.

**Comment by malgorithms** [comment]
@maxtaco  is there a reason for now that @sebhans  shouldn't just:

```bash
keybase deprovision # deactivate current device
keybase login            # re-provision current device with paper key
keybase passphrase change # change passphrase
```

which will let them reprovision the busted device? This can be done with a paper key, right?

@sebhans, you would have to choose a new device name, though.

**Comment by maxtaco** [comment]
This should indeed work

**Comment by sebhans** [comment]
@malgorithms, it did work, although I did a `keybase passphrase recover` instead of `change`, because that was the whole point. Thanks to all!

**Comment by linux-modder** [comment]
motion to close as this is resolved?
