### ISSUE TITLE
suggestion: provide a keybase icon to fontawesome

### ISSUE THREAD

**Issue by tessus** [keybase/keybase-issues#2763]
It would be great to have a keybase icon in fontawesome.

**Comment by anowlcalledjosh** [comment]
Duplicate of #973 and #957.

**Comment by tessus** [comment]
Thanks for the info. I've just read these 2 issues and a few others that were referenced. The fact is that there hasn't been any progress for the last 18 months, so what's the status?

I'm ok with a 'won't fix', but being stuck in 'it will come, maybe' for 1.5 years is a joke.

**Comment by cjb** [comment]
I think we're planning on changing our logo very soon. So we might as well wait for that.

**Comment by tessus** [comment]
@cjb thanks, this is a status update I like, although 'very soon' can be a rather variable timeframe. ;-)

e.g. for me 'very soon' means within a week, 'soon' means less than a month. what does it mean for you?

**Comment by anowlcalledjosh** [comment]
Turns out "very soon" was just over 2 weeks!

**Comment by tessus** [comment]
yep, although the new logo is quite ugly. but tastes differ.
I would have gone with a modern look, not a Flintstone character with a key in the hairdo...

**Comment by anowlcalledjosh** [comment]
Yeah, I'm not sure how well it works as an icon – for example the Linux desktop app icon is monochrome and tiny, and so it's barely recognisable:

![image](https://cloud.githubusercontent.com/assets/9433472/22756806/4c2c3612-ee40-11e6-89c9-aa0b49120796.png)

**Comment by tessus** [comment]
I had something like [this](https://thumbs.dreamstime.com/z/data-security-icon-circuit-board-key-dark-blue-background-42863002.jpg) in my mind, when I heard of a new logo...

**Comment by xuv** [comment]
@tessus: since there has not been progress on the Font Awesome part in 3 years. And since they've parted in a different direction with v5.0. We forked it here and have added the Keybase icon https://forkawesome.github.io/Fork-Awesome/icon/keybase/

**Comment by tessus** [comment]
@xuv thanks for the info. this is a great idea. unfortunately Fork Awesome does not seem to be available via a CDN.

**Comment by xuv** [comment]
@tessus Nope. Not yet. Is this an absolute requirement for you? And if so, could you point us in the direction on how to achieve this?

**Comment by tessus** [comment]
@xuv it's not an absolute requirement, but an important part of improving site speed.

I'd contact different CDN providers and ask them, if they are willing to make it available. it is a community project after all and this service would benefit the entire community. bootstrap, font awesome, jquery, ... all of those projects managed to get it done somehow.

**Comment by xuv** [comment]
@tessus: Ok, well noted. I don't think it's a priority at the moment to go find a VPN. We better build momentum first around this project. Get it recognized and known. And then it'll be easier to find a CDN.

**Comment by tessus** [comment]
@xuv I understand. however, people are more likely to adapt it, if they only have to change a link in their code.

**Comment by xuv** [comment]
@tessus: You're probably right. Now, we have looked at cdnjs, which is supposedly very friendly to open source projects... [They require 200★ on gh and 800 downloads per day on npm](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) to be considered a potential candidate. It makes sense I guess. Why bother maintaining a package that no one uses. So please, add a ★ to [Fork Awesome](/ForkAwesome/Fork-Awesome) and help spread the word. ;)

**Comment by xuv** [comment]
@tessus: Ok, found a CDN solution. Not that super elegant, but here it is using [jsDelivr](https://www.jsdelivr.com/package/npm/fork-awesome). Don't forget to import also each individual font file.

**Comment by xuv** [comment]
@tessus: Ok, figured it out. Here is a CDN for Fork Awesome: https://cdn.jsdelivr.net/npm/fork-awesome@1.0.8/css/fork-awesome.min.css 
You can use that link now in your personal website and have a Keybase icon. ;)

**Comment by tessus** [comment]
@xuv awesome. starred it, and I will use it on my web site as soon as I was able to create an SRI hash.

please see https://github.com/ForkAwesome/Fork-Awesome/issues/32#issuecomment-368267654

**Comment by tessus** [comment]
thx, switched to Fork Awesome.
