### ISSUE TITLE
Password recovery via the website

### ISSUE THREAD

**Issue by canfan** [keybase/keybase-issues#2766]
I see a few open issues related to account recovery but the issue I encountered seems unique and specific to recovery via the website.

I get a `error in POST (404)` message after submitting new password, here's a screenshot

<img width="1429" alt="keybase_issue" src="https://cloud.githubusercontent.com/assets/37341/21868792/7f972d56-d822-11e6-925f-bd705be253d6.png">

Context: I registered for keybase when it was still in beta and had it fully setup on my old machine but never got to use it much. I would now like to use my existing account and I don't have keybase installed on my current machine.

**Comment by maxtaco** [comment]
My mistake, should be fixed now...

**Comment by canfan** [comment]
Thanks! All good.
