### ISSUE TITLE
Need folders reset after installing on new machine and revoking old one

### ISSUE THREAD

**Issue by copyhacker** [keybase/keybase-issues#2769]
I'm not sure why this happened. Only thing I can figure is that I installed Keybase onto a new laptop and I had the old one open while revoking its key. One of my shared private folders is fine, but another shared one and my personal one both need resetting.

Latest log id is: 627d90152a3bbf8ca8ef191c

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrxMI7OT XB3x7o9z82a9Jod hz1xBzi4MYJ82oD UJsBRvgqgAIbhth uQc5pOoaDWDmW2S tFRR58z0CuehtGD KyqCO7wjxIZM3ZR gZq7ZidSoms6sHG o0WD39sLPPtfzBe 8PpqDs9PsahOCch 3HAMR9jKrc3Cd0k 3HjvFY9GfOoLD7o 792mJc5FMBhJkYJ iWVnQ7dLgij2Xel 5yza7IG43cnCxz4 fcWt6P5TS9mz3Eg eggQQ9rj0pHCOZt ptuMUdW3nljUyCp fHbrE1ZDGuUg6P9 fO3SyY1pYFOx8y3 NvU3j3xMSlNUX3k M5pCppozDvzk9zO 3T8uEVXrPzSyRNX PqP91JPhasOKwys TqWmPilu7KmSxPD X08UjXZyUTm3rkN dOg6rW2oLNR13l6 oTOs6FcjX10ahgH LxPKA1tlwjkaISv 5apk6SI1R2. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Arg, yeah looks like the old device managed to write to those folders in the same second that the key was revoked, and our code to check the revocation times on keys is being very strict.  Do you have any data in those folders that you care about, or is resetting definitely an ok option?  We could probably find a way to relax the check for you as a one-time thing if you need to recover the data.  But resetting is the easiest thing, if you are definitely ok with it.

**Comment by copyhacker** [comment]
@strib Resetting is perfectly fine. Nothing in those folders that needs saving, the shared one is with someone who hasn't joined yet. Thanks!

**Comment by strib** [comment]
Ok @copyhacker, done.  Do things look ok now?  You should be seeing empty folders for those 2 now.  Please close this out if things seem ok.  Thanks!

**Comment by copyhacker** [comment]
All folders working again. Much appreciated!
