### ISSUE TITLE
Can't delete public folder after account reset

### ISSUE THREAD

**Issue by folixg** [keybase/keybase-issues#2775]
I had to reset my keybase account (silly me forgot the pgp-key passphrase). Now I have a folder `/keybase/public/folixg (files before account reset 2017-01-18)` in my kbfs. I tried to delete this folder and its content, however I get a "Permission denied" error (even tried using `sudo`). When I try to access my public folder via [keybase.pub](https://keybase.pub) I can only access this old folder, not my current folder.

Has anyone any ideas, what steps I need to take in order to completely remove the old folder?
Thanks a lot in advance.

**Comment by strib** [comment]
You can use `rmdir` on the folder, or go through the Keybase GUI and mark it as a folder to ignore.

**Comment by folixg** [comment]
I was indeed able to use `rmdir`. Had not tried that before, because I didn't expect `rmdir` to work on a non-empty folder. So now I don't see the folder and its contents on my machine (except as an ignorder folder in the keybase gui). Unfortunately the webinterface at [keybase.pub](https://keybase.pub) still shows the old folder.

**Comment by strib** [comment]
Ah that's a separate, known bug.  We need to manually restart keybase,pub to get around that issue for now.  I'll do so later today when I get into the office.

**Comment by folixg** [comment]
Thanks a lot.
