### ISSUE TITLE
Web Site Verification

### ISSUE THREAD

**Issue by stew3721** [keybase/keybase-issues#2780]
I have a NextCloud installation with oCloud at https://stew721.ocloud.de

I've submitted a ticket asking them to put the keybase.txt file at either of the following URLs:
* https://stew721.ocloud.de/keybase.txt
* https://stew721.ocloud.de/.well-known/keybase.txt

However, until they respond and/or if they won't, I have the file publicly accessible at:
* https://stew721.ocloud.de/index.php/s/nUUzMq3lfJ60eam
  * https://stew721.ocloud.de/index.php/s/nUUzMq3lfJ60eam/download

Can that location be used for proof/verification?

**Comment by malgorithms** [comment]
it can't, unfortunately. the assumption of keybase web proofs is that to prove you own a domain, you can put a file in a specific spot. I see this is annoying in your case, but in other cases there are all kinds of problems by allowing this. For example if we allowed arbitrary file locations, you could prove ownership of `drive.google.com` by putting a file in a spot, finding the URL they give you, and then submitting it as proof.

sorry!
