### ISSUE TITLE
Username change?

### ISSUE THREAD

**Issue by ckingdev** [keybase/keybase-issues#2781]
Apologies if this isn't the right venue, I couldn't find an email contact. 

I recently changed my name and it's important for personal reasons that I update all of my accounts/usernames to reflect that. My keybase username contains my old name. 

Is there any way that I could update my username without creating a new account and starting from scratch? If it's not possible to directly change the username, is there anything i can export from the old account and then import to save some work?

Thanks!

**Comment by anowlcalledjosh** [comment]
I think this is not possible, see #2576, #2478, #2393, etc.

You could export your PGP key in order to avoid creating a new one if you want, but you'll have to redo all your proofs whatever you do.

**Comment by ckingdev** [comment]
I figured that there would be technical challenges associated with that, totally understandable. Thanks for the extra info and letting me know.

Cheers!
