### ISSUE TITLE
need 34 bytes per EdDSA value

### ISSUE THREAD

**Issue by echto** [keybase/keybase-issues#2787]
I am unable to load my public key on the website.  I get the following error, "need 34 bytes per EdDSA value".

**Comment by maxtaco** [comment]
well, now we know where the error is coming from.

can't say we can get to fixing this right away.

**Comment by maxtaco** [comment]
Made an internal ticket for it...

**Comment by echto** [comment]
Ok, thanks.   I didn't see the notifications about this until now.  When I came back to the PC and refreshed the bug listing page, I thought I didn't post the bug correctly because it wasn't listed, so I posted it again.  Sorry about that. Please feel free to delete it.

**Comment by echto** [comment]
I just tried importing my key within the client and I received this error.

ERROR key generation error: need 34 bytes per EdDSA value (error 905)

I was hoping it was a browser copy/paste issue but it appears it is not.   Log submitted.

------------
Success! Your log ID is:

  e8d6b98a98cf2aebdbfb051c

------------

**Comment by maxtaco** [comment]
the server is rejecting the key update because it's running the same library --- https://github.com/keybase/kbpgp

**Comment by frantic1048** [comment]
Same error here: I can't update my public key on the web page. I just added an uid to the key.
It was successful at the previous time I add an uid and update my key.

Here's my public key:  https://sks-keyservers.net/pks/lookup?op=get&search=0xD2DE8CCA1E74D572369F4C699207632BD48BDDAA

**Comment by maxtaco** [comment]
This might be a regression introduced by recent improvements to our eddsa handling. @zapu can you take a look?

**Comment by zapu** [comment]
That's a new one! Definitely will look into that, thank you for your report.

**Comment by maxtaco** [comment]
@zapu  I couldn't find the earlier story, so I filed a new one: CORE-4758
