### ISSUE TITLE
Install fails on Ubuntu 16.10 with unmet dependencies

### ISSUE THREAD

**Issue by jlopp** [keybase/keybase-issues#2788]
I'm unable to install keybase; it give the following error (and I'm unable to manually install the dependency)

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 keybase : Depends: libappindicator1 but it is not installed
```

**Comment by jlopp** [comment]
Never mind, apparently my package manager was in a bad state.

**Comment by maxtaco** [comment]
Cc @oconnor663

**Comment by oconnor663** [comment]
Did you need to do the `app-get install -f` part of the install instructions? Let me know if you landed on some instructions that don't include that.
