### ISSUE TITLE
ARM Build? For Raspberry Pi etc.

### ISSUE THREAD

**Issue by edsw** [keybase/keybase-issues#2794]
Is there any plan to have Keybase/kbfs be compatible with building on ARM? I would like to use the Keybase file system on a Raspberry Pi, as I already do on x86 servers. Here's the processor architecture for a Pi 3, for example:

"The Raspberry Pi 3 uses a Broadcom BCM2837 SoC with a 1.2 GHz 64-bit quad-core ARM Cortex-A53 processor"
(via https://en.wikipedia.org/wiki/Raspberry_Pi#Processor)

Thank you! 😀

**Comment by cjb** [comment]
We've got issues open on this -- Keybase isn't going to compile ARM binaries for you, but you're welcome to ask your distribution vendor to, they're the right people to do it. Thanks!
