### ISSUE TITLE
PGP update: warning no key matching fingerprint found in the GPG keyring

### ISSUE THREAD

**Issue by OJFord** [keybase/keybase-issues#2797]
I added a couple of identities needed in order to stop my commits showing with an ominous 'unverified' on Github, and then tried to to update my public key on Keybase with `keybase pgp update` when I get the 'warning' above.

I thought maybe since it was just a 'warning' it might not be a problem, but my key on Keybase doesn't match that locally, with which I successfully updated Github.

The fingerprint's definitely the same - Github refused to 'add' it since it thought it was already there; I had to delete it and re-add it, then the emails changed to reflect the identities added.

And the key for that fingerprint definitely is in the GPG keyring, since it would need to be for me to have added the identities.

I also tried via the web interface, which then wants confirmation via either `pgp update` (which still doesn't work) or an HTTP request. With the latter, it complains about a bad base64 encoding. I fiddled with it a bit, but I couldn't even determine which parameter was the problem, nevermind what the issue with it was.

`keybase` is set to use `gpg2`.

**Comment by maxtaco** [comment]
Can you rerun the update attempt and then run `keybase log send`? Thanks
