### ISSUE TITLE
Proving a website ownership seems to be broken

### ISSUE THREAD

**Issue by codella** [keybase/keybase-issues#2799]
I put the `keybase.txt` fil eunder my domain ([https://codella.bitbucket.io/keybase.txt](https://codella.bitbucket.io/keybase.txt)), and it's currently reachable.

Unfortunately, trying to prove my domain I get errors from the interface, and I also received this mail this morning:

![screen shot 2017-02-03 at 09 27 41](https://cloud.githubusercontent.com/assets/4209616/22584521/24c569be-e9f3-11e6-8ba6-297ec850a72f.png)

any ideas why this is happening?

Cheers!

**Comment by zQueal** [comment]
IIRC this is entirely intended. Keybase doesn't support subdomain verification, only domain verification. So you're asserting that you own `bitbucket.io` which isn't true. On the surface, proving you have access to a subdomain doesn't establish ownership.

I may be wrong, though.

**Comment by codella** [comment]
I am pretty sure I managed to verify https://codella.gitlab.io a few days ago, so that's why I expected the bitbucket url to work.

Thanks for your reply!

**Comment by malgorithms** [comment]
we do support subdomain verification. Your proof isn't working because that's a proof for codella.gitlab.io being hosted on codella.bitbucket.io. I think maybe you mixed up some proof texts.

**Comment by codella** [comment]
I see! That was a rookie mistake.. Sorry!

**Comment by codella** [comment]
.. and thanks, of course :)

**Comment by malgorithms** [comment]
np!
