### ISSUE TITLE
Icons changed during upgrade with no messaging around it.

### ISSUE THREAD

**Issue by jtligon** [keybase/keybase-issues#2801]
There was an upgrade window that popped up, and after the upgrade, all of the icons changed to a new icon that is not found anywhere on the website. 

Maybe launch it on the website first so that a user can expect to see a new icon in the top menu?

**Comment by cjb** [comment]
@jtligon Fair point! We went the other way around -- pushing out the new clients first, and the website's being updated to have the new iconset as we speak.  Should be changed over soon.

**Comment by cjb** [comment]
Done!
