### ISSUE TITLE
"upgrade is required" despite having higher version

### ISSUE THREAD

**Issue by philsnow** [keybase/keybase-issues#2807]
I followed the instructions on the [linux client installation page](https://keybase.io/docs/the_app/install_linux) and ran `run_keybase`.

```
philsnow@luna:~$ run_keybase
Unmounting /keybase...
Shutting down kbfsfuse...
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!
[snip squirrel]
```

This is a headless machine though, so there's no display.  How could "Launching Keybase GUI" have succeeded?  Anyway I try to `keybase login` and:

```
philsnow@luna:~$ keybase login
error: Upgrade is required! Please download v1.0.16 from https://keybase.io/download -- now with KBFS!
```

It's asking me to upgrade to version `1.0.16` but I have `1.0.18`:

```
philsnow@luna:~$ dpkg -l keybase | grep Keybase
ii  keybase        1.0.18-20170208170104.dc66461 amd64        Keybase's command line client
```

**Comment by oconnor663** [comment]
That's weird. I wonder if you have an old `keybase` executable somewhere in your `PATH` that's shadowing the new one? What do you see if you run `keybase --version`?

**Comment by philsnow** [comment]
derp.

```
philsnow@luna:~$ for exe in $(which -a keybase); do echo -n "$exe: " ; $exe --version; done
/usr/local/bin/keybase: 0.7.0
/usr/bin/keybase: keybase version 1.0.18-20170208170104+dc66461
```

PEBKAC, this must be from an ancient version of the keybase exe that I had forgotten about... yeah it's from Sep 2014.

**Comment by oconnor663** [comment]
This is arguably our fault, because we never added any logic in the old client to somehow detect that the new client was installed and warn you about this. Sorry for the runaround.
