### ISSUE TITLE
Yum repodata becomes stale pretty quickly

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#2816]
Keybase frequently causes my workstation to fail updating as the package your repo says is available seems to disappear whenever a newer version is pushed out.

```bash
[~]$ sudo dnf update
...
[MIRROR] keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm: Status code: 404 for http://prerelease.keybase.io/rpm/x86_64/keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm                 
[FAILED] keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
...
Error: Error downloading packages:
  Cannot download keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm: All mirrors were tried
```

Attempting to download the file that is in my computers cached data about the keybase repo.
```bash
[~]$ curl http://prerelease.keybase.io/rpm/x86_64/keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>rpm/x86_64/keybase-1.0.18.20170206170059.4931777-1.x86_64.rpm</Key><RequestId>7CD3F489E2BE123D</RequestId><HostId>8ZThI+/2X/MacEIEa3rgN8tMPolbGXPTufnb9P/DVZGRYu6se/LrTUzh1fWhIvbevRQ59ROnJlM=</HostId></Error>
```

Two possible solutions:
1. Add an explicit metadata expire time to keybase's repodata file
    ```
    [~]$ cat /etc/yum.repos.d/keybase.repo 
    [keybase]
    name=keybase
    baseurl=http://prerelease.keybase.io/rpm/x86_64
    enabled=1
    gpgcheck=1
    metadata_expire=60
    gpgkey=https://keybase.io/docs/server_security/code_signing_key.asc
    ```
2. Keep the files you advertise out to the world for a little longer

I understand wanting people to have the latest version, but that shouldn't come with the risk of breaking automated system events -- even if you are only breaking them for hours / days.

**Comment by maxtaco** [comment]
Thanks @BrandonIngalls.  Cc: @oconnor663

**Comment by oconnor663** [comment]
Wow, thanks for the detailed fixes. If all we need to do is avoid deleting the old package files from S3, I think this should be a trivial change to our push script. I'll set aside some time to test it and make sure nothing breaks.

**Comment by oconnor663** [comment]
This change should go out with tomorrow's build, though it won't automatically apply to your machine unless you delete `/etc/default/keybase` (or change the `repo_add_once` param in there to "true").
