### ISSUE TITLE
Energy impact high

### ISSUE THREAD

**Issue by howderek** [keybase/keybase-issues#2824]
Keybase's recent update has made it unusable on my MacBook Pro. It's energy usage is really high and my battery life has been substantially decreased. I am running OS X 10.12.4 Beta.

Attached is a screenshot of the usage

Here is a screenshot of the usage:
<img width="806" alt="screenshot 2017-02-09 09 05 15" src="https://cloud.githubusercontent.com/assets/835856/22788979/38cb604a-eea7-11e6-9cb7-ad983c71d6f5.png">
Where 28.39 is the average energy impact

**Comment by maxtaco** [comment]
Cc: @keybase/react-hackers 

thanks for the report, we'll investigate....

**Comment by chrisnojima** [comment]
Can you expand that row so we can see more detail?

**Comment by howderek** [comment]
Here's the full row on the Energy tab of Activity Monitor:

<img width="852" alt="screenshot 2017-02-09 09 24 47" src="https://cloud.githubusercontent.com/assets/835856/22789831/e352ddac-eea9-11e6-8d13-00761fbbcdae.png">

Here's every process that has "Keybase" in it's name on the CPU tab:

<img width="648" alt="screenshot 2017-02-09 09 25 57" src="https://cloud.githubusercontent.com/assets/835856/22789844/ec2d2d06-eea9-11e6-9c05-cdd9500b9ff2.png">

My version of keybase is: 1.0.18-20170207120017+ce0f90d

**Comment by chrisnojima** [comment]
can you run a 'keybase log send' on the cli? Does it maintain this level of load after restarting the app?

**Comment by howderek** [comment]
After restarting, it's gotten somewhat better. The average has gone down a little bit (21.45) but looks to be remaining pretty constant there.

My log id is `6c85a8a3c747513829db1e1c`

**Comment by chrisnojima** [comment]
Thanks we'll investigate!

**Comment by chrisnojima** [comment]
One more question. If you change screens does it affect the load? Like go to settings and see if it is reduced. Thanks

**Comment by howderek** [comment]
If I interact with the settings page, the instantaneous energy impact is very high (44), but after UI renders it stays roughly where it was before (0.1 - 3.0).

**Comment by NoahO** [comment]
I have another energy bug, I use Tripmode to block access to non-essential apps while tethering (including keybase). When Keybase is blocked from the network, it uses a solid 30% cpu continually.

**Comment by maxtaco** [comment]
Thanks for the report. I believe we solved this problem in master and haven't made a public build yet -- it's the dreaded energy-eating spinner, right?  cc: @chrisnojima

**Comment by chrisnojima** [comment]
It'll be in master very soon and will be in the next release. Thanks for the report!
(https://github.com/keybase/client/pull/6495)
