### ISSUE TITLE
Never prompted for gpg passhrase, so 'keybase login' fails (I think).

### ISSUE THREAD

**Issue by m00dawg** [keybase/keybase-issues#2832]
I'm trying to do this:

```
tim@lindawg ~ $ keybase login sweetums
▶ ERROR Sorry, your account is already established with a PGP public key, but this
utility cannot find the corresponding private key on this machine.
This is the fingerprint of the PGP key in your account:

   24DD B07D 83EB 157F 4A3B DF3E 0100 AACD 688A 03BE

You need to prove you're you. We suggest one of the following:

   - put one of the PGP private keys listed above on this machine and try again
   - reset your account and start fresh: https://keybase.io/#account-reset
```

I can try both the GUI option (running Keybase from my start menu) or command-line, same result. But the private key is definitely installed (I know because it's the same computer I made the key on). I think it's having trouble either accessing gpg (/usr/bin/gpg on my Linux Mint install) or it needs to unlock the private key and that's bailing somehow? Key was made Jan 2017.

Am I missing something critical here or? Help would be greatly appreciated. I was going to use that awesome crazy secure Chat feature (that looks fantastic, by the way!)

**Comment by maxtaco** [comment]
does `gpg2 -K` show that your private key is available on this machine?

**Comment by m00dawg** [comment]
ah hmm interesting...`gpg -K` does. `gpg2 -K` does not.

**Comment by m00dawg** [comment]
http://superuser.com/questions/655246/are-gnupg-1-and-gnupg-2-compatible-with-each-other
^ that helped me figure out what was going on. Rather confusing mix of gpg (1.x) and gpg2, but after doing the import key trick, I seem to be in good shape now!
