### ISSUE TITLE
Can't verify private twitter account?

### ISSUE THREAD

**Issue by finsprings** [keybase/keybase-issues#2834]
I'm guessing my twitter verification failed because my twitter account is private.
Is there an account of yours I can add?
Why isn't it grabbing my GitHub avatar in the meantime?

**Comment by finsprings** [comment]
I made my account public and verification succeeded immediately.

**Comment by skwerlman** [comment]
This is expected. The reason private twitter accounts fail is that all verifications should be individually reproducible by anyone, and private accounts inherently prevent that.

**Comment by finsprings** [comment]
That makes sense, thanks.
