### ISSUE TITLE
Request: No notification when Keybase is active window

### ISSUE THREAD

**Issue by Arty-chan** [keybase/keybase-issues#2837]
On the Windows version (using Windows 10), I get a notification for all chat messages. It would be great if we didn't get notifications when Keybase is already the program that we are actively looking at.

**Comment by cjb** [comment]
Thanks for the report! We've actually fixed this already but we haven't released the fixed version yet on Windows, should be out in the next few days.

**Comment by Arty-chan** [comment]
Awesome, thanks!
