### ISSUE TITLE
My verification code sucked

### ISSUE THREAD

**Issue by hfaran** [keybase/keybase-issues#2838]
> Your verification code sucked.
> It's probably our fault, but make sure you didn't mangle the link from your email. If this problem persists, email us.

Not sure if this is the proper avenue for reporting this but I couldn't find a contact email on the website. I just clicked the link from the email. Using Gmail and Chrome on Windows.

**Comment by malgorithms** [comment]
hmm, could you send me the link via keybase chat? i'd love to take a look at it. (I am `chris` on there)

**Comment by hfaran** [comment]
I kind of forgot to follow up on this, but I retried with a new code, and it worked this time. So whatever the issue was, looks like it's gone now. ¯\_(ツ)_/¯
