### ISSUE TITLE
Unable to decrypt.

### ISSUE THREAD

**Issue by shiva28** [keybase/keybase-issues#2839]
I am using Keybase on windows desktop. I have encrypted a message using my own public key. I am using command line app to decrypt that encrypted messages. But it always shows me some error. I'm using command line app because I haven't put my private key on Keybase's server. Is there any solution?

**Comment by maxtaco** [comment]
Very vague report.  What is the error message?

**Comment by shiva28** [comment]
I am entering this ( keybase pgp decrypt -m "myencryptedmessage" ) command in the keybase shell. Then this appears :: 
![errorkb](https://cloud.githubusercontent.com/assets/16119366/22882806/ee0b3412-f212-11e6-80b0-875d47189b43.PNG)

**Comment by maxtaco** [comment]
try putting the message in a file and decrypting the file.

**Comment by shiva28** [comment]
I'm extremely sorry but I didn't get you. Should I put my message in a .txt file and decrypt it? What is the command for decrypting a file?

**Comment by nikinath** [comment]
There are two ways to solve this issue:

1. **Use quotes properly**:
Put the entire encrypted message at once in quotes in the decrypt command. By entire encrypted message, I mean the block of text that starts from `-----BEGIN PGP MESSAGE-----` and ends at `-----END PGP MESSAGE-----`.

2. **Using a file**:

To encrypt a file - say you are encrypting the file `foo.txt` (containing plain text). This command will encrypt `foo.txt` and create a file called `bar.asc` containing encrypted text.
```
$ keybase pgp encrypt nikhita -i foo.txt -o bar.asc
```
To decrypt that file - this takes `bar.asc` as an input i.e. the encrypted message and stores the decrypted message in a file called `baz.txt`.
```
$ keybase pgp decrypt -i bar.asc -o baz.txt

**Comment by maxtaco** [comment]
Thank you @nikinath

**Comment by shiva28** [comment]
Thanks a lot @nikinath
