### ISSUE TITLE
Username capitalization not normalized in PGP key modal

### ISSUE THREAD

**Issue by jeremyBanks** [keybase/keybase-issues#2843]
Per #397, usernames are supposed to be normalized to lowercase in all situations.

However, if a user registers using a non-lowercase name, the originally capitalization (which I guess is still saved internally) will be preserved in the PGP key modal:

<img width="634" alt="screen shot 2017-02-13 at 11 37 31 pm" src="https://cloud.githubusercontent.com/assets/18020/22915469/7c3e98e6-f245-11e6-8a41-440d701bfb2a.png">

(The commands and URLs listed do work; they seem insensitive to the username's capitalization.)

**Comment by malgorithms** [comment]
nice catch, thanks. fixed and live.
