### ISSUE TITLE
Can't Verify Twitter Account

### ISSUE THREAD

**Issue by mpc0** [keybase/keybase-issues#2844]
I've posted the verification here: https://twitter.com/Matt_Carlson
I'm able to access it when logged out, so I don't believe my account is protected. 

Here's what I see from the command line.

$ keybase id mpc0
▶ INFO Identifying mpc0
✔ public key fingerprint: 3EB9 2E27 473B 247A A400 D917 97A9 0201 776A FA0C
✔ "matt_carlson" on twitter failed: No server-given hint for sig=48eb6a55828f6d89acb1e234efd2fcaf9eea52bf5a6b0c585b9bf15d7c675cbb0f (code=306)
✔ admin of DNS zone mpcarlson.com: found TXT entry keybase-site-verification=0nGczWUMDEKsvr0NjDwV5kFAYaBI5z3p_b6BLXBiSy0 [cached 2017-02-14 07:04:10 PST]

What am I missing?

**Comment by mlsteele** [comment]
Hi @mpc0. Looks like your tweet contains a signature from an earlier proof you made. But it must instead include the latest signature. Your latest proof hash is `SOtqVYKPbYmsseI079L8r57qUr9aawxYW5vx` but your tweet contains `PF9kG5ZkIAmXBiuEDxnA7LvDEqUehchcfeJA`. You can try making a new tweet _of the same exact format_ with `SOtqVYKPbYmsseI079L8r57qUr9aawxYW5vx` and after a while the server should pick it up. Or for instant gratification you can just make a new twitter proof, but be sure to use the (new) latest hash.

**Comment by mpc0** [comment]
Thanks. That worked.
