### ISSUE TITLE
Don't recommend `yaourt`

### ISSUE THREAD

**Issue by skwerlman** [keybase/keybase-issues#2848]
On the linux install page, the instructions say to use `yaourt -S keybase-bin`.
However, `yaourt` is no longer considered safe because it sources code without asking for user confirmation first.

Please recommend a safer AUR helper in the installation instructions. (`pacaur` is a popular one)

https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by oconnor663** [comment]
Interesting, first I've heard of the issue. Do you have any links to a more detailed discussion about it? I notice that wiki article links to the routine in yaourt's code where they source the PKGBUILD, but it doesn't seem to comment on whether the `sanitize_pkgbuild` routine that they do first is effective or not. (Admittedly that sort of strategy isn't...entirely...a good sign...)

**Comment by skwerlman** [comment]
`yaourt`'s `sanitize_pkgbuild` function is [here](https://github.com/archlinuxfr/yaourt/blob/2ba7d511ee86b3a05b5f0766796cbac6bd8c1c74/src/lib/pkgbuild.sh.in#L417), although it is _really_ difficult to understand.

Honestly, I think even if `sanitize_pkgbuild` is some sort of magical code that does away with all malicious code (which it isn't), it's still better to just prompt the user for a manual review anyway.

**Comment by oconnor663** [comment]
Made this change. Thanks for pointing it out.
