### ISSUE TITLE
cannot verify Twitter 

### ISSUE THREAD

**Issue by gh-jslee1301** [keybase/keybase-issues#2850]
After posting the code still unable verify.

**Comment by songgao** [comment]
What's your keybase and twitter username? Any chance you have a private twitter account where tweets are hidden?

**Comment by zQueal** [comment]
Assuming your twitter username is: jslee1301

Your twitter account cannot be protected if you want to verify it with Keybase. Proofs are meant to be publicly accessible.

**Comment by songgao** [comment]
Thanks @zQueal ! @gh-jslee1301 I'm assuming that's your twitter handle and closing this. Feel free to re-open it if that's not the case.
