### ISSUE TITLE
Installation issues on macOS with brew and GUI

### ISSUE THREAD

**Issue by lkuper** [keybase/keybase-issues#2851]
I seem to be having trouble installing Keybase on a new Mac running macOS 10.12.3.  I tried `brew install Caskroom/cask/keybase`, which appeared to complete successfully, but when trying to run `keybase` I get `keybase: command not found`.

Then I tried installing the GUI using the directions at https://keybase.io/docs/the_app/install_macos, but got the same plist error mentioned in https://github.com/keybase/client/issues/5206 when I tried to run it.

`/Applications/Keybase.app/Contents/SharedSupport/bin/keybase` exists (thanks, @cjb), so I did a `keybase log send`, ID `cd31d5e63a87a616f32d461c`, if that's helpful.

**Comment by cjb** [comment]
@lkuper Thanks for the report! @gabriel's going to look at this tomorrow and get back to you then.

**Comment by lkuper** [comment]
Thanks!

Possibly-relevant ownership/permissions info:
```
$ ls -al ~/Library/LaunchAgents/
total 8
drwxr-xr-x   3 root    staff   102 Dec 15 15:47 .
drwx------@ 63 lkuper  staff  2142 Feb 15 17:46 ..
-rw-r--r--   1 root    wheel   474 Dec 15 15:47 com.intel.fuzz.plist
```

**Comment by gabriel** [comment]
Ah yes, it looks like `~/Library/LaunchAgents/` is owned by root.

You can fix this by running:

```sh
sudo chown -R ~/Library/LaunchAgents/
```

I'm not sure why the permissions are wrong there. You might want to check that other folders in ~/Library are not also owned by root.

**Comment by gabriel** [comment]
This is a wild guess but I wonder if `com.intel.fuzz` installed itself as root in your home folder and since it was the first launch agent it created the folder as root.

**Comment by gabriel** [comment]
(Edited above post to fix: `sudo chown -R "$USER" ~/Library/LaunchAgents/`)

**Comment by lkuper** [comment]
Great.  I ran `sudo chown -R "$USER" ~/Library/LaunchAgents/`, reinstalled with `brew cask reinstall keybase`, and the `keybase` command now works.  The plist error when launching the GUI app is also gone.  I've so far been unable to log into the GUI app (I get a timeout error), but that seems like an unrelated issue.  Thanks!
