### ISSUE TITLE
Reddit form link in Windows app does nothing

### ISSUE THREAD

**Issue by Chroaster** [keybase/keybase-issues#2852]
Clicking on the link does nothing.
![2017-02-16 13_14_02-keybase - copy](https://cloud.githubusercontent.com/assets/7350928/23007325/5241dcee-f44b-11e6-8c92-66abdbfcd10c.png)

Returning to the home screen shows a spinner next to the reddit line and the following dialog.
![2017-02-16 13_14_03-keybase - copy](https://cloud.githubusercontent.com/assets/7350928/23007411/d2c75984-f44b-11e6-952f-4f93a0615f66.png)

**Comment by maxtaco** [comment]
cc: @keybase/react-hackers

**Comment by Chroaster** [comment]
Oops, this is a duplicate issue with [5888](https://github.com/keybase/client/issues/5888), [5792](https://github.com/keybase/client/issues/5792), [5741](https://github.com/keybase/client/issues/5741), and [5107](https://github.com/keybase/client/issues/5107). My bad. But hey, at least there are screen shots here 👍

**Comment by malgorithms** [comment]
@Chroaster  - can you try one more time? I think we just fixed this in the last 5 minutes.

**Comment by Chroaster** [comment]
@malgorithms Yep! It worked. Nice.

**Comment by malgorithms** [comment]
excellent. closing!
