### ISSUE TITLE
[Windows] Start GUI at boot should be optional

### ISSUE THREAD

**Issue by rpottsoh** [keybase/keybase-issues#2855]
I see that two shortcuts were inserted into my startup folder during installation of the Windows Keybase client.  I presume that one loads the tray icon and the other the GUI.  It would be nice if during the install of the Windows client if a selection was available to allow the GUI to start or not start at start up.  I don't recall getting that choice.

**Comment by orcmid** [comment]
I agree.  I assume the startup is to support the secure file system, if one is used.   I only see the GUI on startup because it wants to get my first login, which is failing.  Still, I was surprised that the login comes up on startup.

**Comment by robyf** [comment]
I agree with this. I don't think the gui should start up automatically on startup so at least I should be able to disable it from the client's settings.

**Comment by zanderz** [comment]
A less intrusive GUI is on the roadmap. Meanwhile, you can disable the GUI startup shortcut by deleting `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`. Then the Keybase start menu shortcut can be used to access the GUI.

**Comment by rpottsoh** [comment]
This I know.  The downside to this work around is that tray app is not started so no notifications of pending messages to read or files to view.


Sent from my android device.

**Comment by rpottsoh** [comment]
Has the windows gui been quietly updated?  Upon start up the UI is not appearing and the icon is still appearing in the tray. :+1:  :1st_place_medal:   I like it!  Thanks!

**Comment by zanderz** [comment]
Yes, if the GUI was not foreground when it last ran, it will no longer insist on popping up on update or reboot. The services still start at startup by default, but even if the startup shortcuts are removed, the GUI now will start the service as needed. Thanks for the feedback.
