### ISSUE TITLE
Can't prove GitHub account

### ISSUE THREAD

**Issue by Shuey187** [keybase/keybase-issues#2871]
I've posted the following public gist, but keybase continues to say that the proof failed:
https://gist.github.com/Shuey187/69e567ba0c339d092e4eb7bcf9ba96e1#file-keybase-md

What am I missing? :(

**Comment by maxtaco** [comment]
You've attempted to prove ownership of `Shuey` at github but you are @Shuey187

**Comment by Shuey187** [comment]
I merely pasted exactly what keybase told me to paste in the gist...

**Comment by maxtaco** [comment]
When it asked you what your github account name is, you entered `Shuey` rather than `Shuey187`

**Comment by Shuey187** [comment]
I did it the first time through the web and it never prompted me.  I did it from the command line this time and entered my correct username on GitHub and it worked.  Thanks for pointing me in the right direction maxtaco!  It's proven now! :)
