### ISSUE TITLE
Reset private kbfs folders

### ISSUE THREAD

**Issue by beardog108** [keybase/keybase-issues#2872]
February 24th, 2017 12:28 PM: Please reset folder /keybase/private/beardog because I revoked all the keys that have access to it.
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs4WMFak CPDlVsB78l7WCaG 9vf7ucfW8CDYaqj FXvwp1E02kCqShm JJUFbrrmEtVP1RP kmkya2Odxahtxnr VcW4fdp5M63ilQX cXemkB6LefYARPZ GP7pRzUSNMr5dTs 3155F9Pv1za9Uxh RTUK1vwMeVDAuEh n3aITVIJTKWQu0Q 01MdQa3lyQyEuAQ XkbiUBuKNxfeNfK lZmwhu11XfMk0uf iJqK6uT3ZtxKbnE JlqN6jN0RDxFNpN mwail5kRwabVJKS 8w0LcGfJZ2hIEYA XS5FMPTChYn9Jxw yTTeyuAvKSSMVO3 AVsDzByCwEZNQpO 3XgfJLrv4zJZaRj PkQK3hP1doRj9xE ISx9kQ0jXq9uV1G oQaHGJVDTEwVsFe leS6bEitVzKOTCQ KarHRLG80r4X1A5 rWqnHMf9yAweRUq 80. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @beardog108 -- I can do that for you, but can you please update your signed statement to include the current date and time?  Usually we ask people to run this command, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folders /keybase/private/beardog108 because I revoked all the keys that have access to it."
```

and post the results here.

Also, it would be nice to have some more context, so we can try to help people avoid this in the future -- why did you revoke your original device and paper key before provisioning your new one?

Also, it looks like `virtualdxs` still has active devices -- would you be able to ask that person to simply sign into Keybase on one of their devices?  That should give you access to the shared folder.

**Comment by strib** [comment]
Oh, hrm, maybe `virtualdxs` doesn't have an active device that can rekey that folder after all...

**Comment by beardog108** [comment]
I updated my message. 

Context: I can't speak for virtualdxs, but I really messed up my system a while back & had to reinstall, and couldn't find my paper key. I know I should have been more responsible. My new paper key is in a safe place. 

Thanks for your assistance. :+1:

**Comment by strib** [comment]
Ok done!  Please check it out and close this if things seem ok.
