### ISSUE TITLE
FB Proof does not work

### ISSUE THREAD

**Issue by edj-boston** [keybase/keybase-issues#2874]
Here is the public link: https://www.facebook.com/edj.boston/posts/10101441012730792?pnref=story

**Comment by songgao** [comment]
Did you use the CLI to do the proof?

cc @oconnor663

**Comment by mlsteele** [comment]
@edj-boston Our server is looking at a facebook url for the facebook account `warptera1` which you tried to prove before. Did you by any chance edit your proof manually after changing your facebook username? It looks like it has the signature hash from the `warptera1` proof..

**Comment by edj-boston** [comment]
I did this from the new keybase desktop app.

Yes, I went back and fixed the username after I realized it was wrong and restarted the proof. Is it cached?

**Comment by mlsteele** [comment]
Ah that's the problem. Not only is it cached, the username is signed into the proof. So that `Tyl8jx-2201PCZmAUga_48egRxbGYf9HdXBzYiQ9z_w` would only work for `warptera1@facebook<->ejdboston@keybase`.

Just go ahead and revoke that proof and do a make a new facebook one.

**Comment by edj-boston** [comment]
Tried that twice now (in the mac app). Still no joy.


Eric J

**Comment by oconnor663** [comment]
@edj-boston when I look at your Facebook profile I only see the old proof, that you linked at the beginning of this issue. I can see [in your sigchain](https://keybase.io/edjboston/chain) that you made two new proofs, but did you finish the full Facebook flow and post them (publicly)? The original post that you linked is no good anymore, and you can delete it.

**Comment by edj-boston** [comment]
ah, that worked :+1:

Thanks!


Eric J
