### ISSUE TITLE
Windows Client shows valid Twitter proof as 'unreachable' 

### ISSUE THREAD

**Issue by shrtstck** [keybase/keybase-issues#2879]
I assume/hope this is a client issue but I am showing my Twitter proof as "unreachable," logging into Keybase.io via web browser and viewing my profile shows the proof as still valid. I assume a discrepancy here is less than ideal.

**View Proof** shows the associated Tweet correctly
**I Fixed It - recheck** doesn't fix it.
**Revoke** probably works but seems like a sledgehammer to a anthill

**Comment by cjb** [comment]
What's your Keybase username?

**Comment by shrtstck** [comment]
keybase.io/orenn

**Comment by cjb** [comment]
Could you run `keybase log send` and tell us the ID?

**Comment by shrtstck** [comment]
This appears to have 'fixed itself' - not sure if it was a soft failure because some network host was unreachable but since it caused a mismatch in the proof of keys felt it worth a report.
