### ISSUE TITLE
Keybase Write Timeout Errors / Write Operation Took Too Long And Failed

### ISSUE THREAD

**Issue by briandcosta** [keybase/keybase-issues#2880]
Hey guys,

First time using a KBFS folder with a friend and I keep getting write timeout errors on macOS. Originally I tried a series of files and it was not happy. Compressed them to a ZIP and that seemed to be going better, but I keep getting a lot of "write operation took too long and failed" popping up via Notification Center. Then the transfer failed giving me a -36 error saying some data in the file could not be read or written to which is bonkers since there's no protections or permissions on the file. I ran a Error Report and sent it in: 8da74b8f49c020f754952b1c

--Brian

**Comment by briandcosta** [comment]
So it ended up finishing, but the ZIP file is half what it should be.

**Comment by strib** [comment]
Hi @briandcosta -- we have known issues trasnferring files > 5 MB or so, especially on slow networks or busy CPUs.  We have a fix in the works that should be released to the public in the next couple weeks.  Sorry for the inconvenience.  For now, the only thing to do is retry on a better network -- `rsync` is sometimes helpful in restarting the transfer wherever it left off.  Sorry for the inconvenience!

**Comment by briandcosta** [comment]
Thanks for the reply and info! I don't really consider my network slow by any means, nor was my system busy...but the ZIP file was over 500 MB ;)
