### ISSUE TITLE
Possibly adding Steam proof?

### ISSUE THREAD

**Issue by TheOdd** [keybase/keybase-issues#2882]
Not sure if this has any interest behind it from others or if it will gain any traction, but I was wondering if it was possible and realistic to add a feature to validate Steam account identity. For example, you could put the key in the description of your profile for Keybase to check. If I'm just missing something big or haven't thought of any obvious issues preventing this, please let me know!

**Comment by cjb** [comment]
Thanks, this is being tracked in #518.
