### ISSUE TITLE
Recovery email not sent

### ISSUE THREAD

**Issue by lemieux** [keybase/keybase-issues#2889]
Not sure where to ask for this but it's been a while since I used keybase and I can't remember my passphrase at all. When trying to reset it, I don't receive any email (seems similar to #2190).

Hopefuly you can help me!

Thanks!

**Comment by maxtaco** [comment]
what's your keybase name? it could be you typo'ed your email address when you signed up.

**Comment by lemieux** [comment]
it's lemieux

**Comment by maxtaco** [comment]
our DB shows that the email is verified (one was clicked on) and that the last several have been delivered successfully. are you sure it's not in spam?

**Comment by lemieux** [comment]
yeah I checked and it's not there... I don't even see a verification email in my inbox.

I joined during the alpha, so I don't know if anything was different back then.

![image](https://cloud.githubusercontent.com/assets/781844/23759386/ab3c62f4-04ba-11e7-96fc-fbdde04e424f.png)

when I enter my email marc@*********ieux.com it says user not found and I tried with all email addresses I know and none are matching. I fully understand that you can't possibly tell me the email associated with it (even though my github account is validated though keybase).

Not sure what to do at this point.

**Comment by maxtaco** [comment]
See below:

```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.64
Comment: https://keybase.io/crypto

wcFMAz3UHfWhUNF5AQ/+I0dO/LoTkrxcwshGgK/jV+tgECjVcgiKQPQx3Br/GcbM
jYFgj2/j0D3g9a7k63oRaXC9l+hSjZabUOx5za/P7vqd9rw13N3toGeuSGYWbppz
TVQLbSIq4Jl0fHt1NU+WmKx+pxyynF+trPtCObWhE860FFENcf40x12RKRse88MN
9ZTDjgryZ4G0DxmTMPn7HvlOhOT1194Nib92SIJxVjWD7GJFePN/7HKKRrEiMSG0
32rZmiyndr7nxLRnJc2I9vp2Cv/GQC1uetsf2xXq2+T4GGQCgaY3Mo76InskHjZN
3o1h+IaL8sKydiLjYQBE/O9KOg0y/SC+rcet8IL8XRmcpHUPlrt5EzX/76xjfEDu
UDp3ATzNtE4M2RPxLJEeF/FBxtMBtTsRwTvfrCmjWCHGtgw1m/ANR1TKP/tuCj7X
0fqrKzfZBU16MPKv8mtz9/mGR7N+HnW1SZ99SIk3dp4diaTz/pHLH0wUzxNENNPB
NT+RanSBt30DR/KuM6PFFbxoxwn+8H2VGeMHy0WjftD9K9OLKxxsXq77czyL9w/s
MppPYPA5WKO+2Xan3oxA7Lbp4X/nvJxY2wDfhvhtQT0U0Ppah8qKcgbiaxLwgeFk
xIY4frFi2pEXTkR4Si6dcEgYxwR7m8KzBhit6W5tG/vmrFfAbA6QQYyW/A8vCfXB
wUwDYFKyrTGmYxwBD/9Qfwsq98Wu72zoTxv20g8Um2oKeUmc1zgG5YTMGhDR14LF
x6AXMwDUb24oiqk6fI/iVymOzlGCCF9mj+tryQ5gnVsWXhAs7AcYh8WmRmXzNQCn
1dKTlmMJGqKkg0pkiEtlBa4hAhaXM20qoWMz8oS3saKm+eCiT8+ezZhnTxY6RM99
zSFoj0R9XXJtfhkUApUXttyQvzXHULr6K0S498zBa8N8BxWcuNbtQiTQW5TxPsCE
S6HKnB0+z51LjzTqbVj+JfUQgLXxkPEz1y2vTWXgxG9XPOWArhzaLxw/ZYI3vhqU
2mFg4v+5CHgWoTjekQk3mPrlUygjLFa/dEvEgaqqDnjWG+9TBYC3GXLBZ3zU6YEO
jbvORVz6o8qYiUFbkXiwzCHvRZuBsqSnF77NQykTJK414sy1WF50ZVoNOAGamhRU
VEc3Nune398G9noAVfPQtL6VdRXWgqbD+LvvCRkNUEOYAHJ4ylLHIcuhFknlFwEI
6VgvL48SqMl2rd/SPaCPLVkpBgUg7p2LAM0FEA/DjbF7Uq88Qq0P5pomRMm+01g+
kSu8aDXyWobtEl+4cJVIZkSR09slqug7LxxAdTDct45dnyKwpoKnTkr/m1Dlh0jH
ondv78PsDw3bO5cgL8ocq0Z+0BzwW5yUs5S1DLfyS6lwYBg5wQu67YPi9XfaIsHB
TAMv4BxFQ0jaOQEP/iF4XuZKQMGs0+n97/gUlzNR2Gz0PZwlRfoRhk754nHlj+db
db3c817HGnB2+81Gzl/CjaucZNhh8RdCBw5rXquAcw4PyOK7MV8+gwazTsLEcofs
Iub7HK/CIP00iIcBiQOAEMLq/uwnV0sa4NfibRomJ+Ot8akpF6DorSZ9Pp1PyHVr
2ppj0SDmU2D3CcmtjZq8Vmav9FTxB3Y6pj6AZy12kKo15m8PW1+8KUOSAV8JxEOP
lPy3olR1xT1ttEfdHUSllQ0nsSYh7cBNkCnY4dDOrlBPRTxlZuFKKq4Fu6pWe7pu
6H0fJ6iEaT1jRpbxmQ5Vb1+pQ361aSQ0I7aCFXhxksZL2Z4WmiBh7jayLMFRvQBL
DucnELYg1a5u4kZCMQpZChWEoZklyez1VYNuPTH/W00auICva7bzeFvwWBm5fjxD
ug/m8t/rmol7n04KFmNgECJRwkY/IE2gfrWVkerhHUZd3TzjDmACT3dqJg1jnEuN
Y/eu+O+QC5fk1Wux5I/zcCelFJsLEGyIcRESEbJtXK0Rz2ceb5879b1rbmk+SJko
guAbT3pyd/A8S1WuG3ZxCgIowRk4+eva6I9F3PCi0wZ/eakCAq7Anaeuef5qH0Oq
jJp3/ESAj5ENtEJxElDPBotLgJu/3dgjbqCqYXwAOwRoddOyiXK4BokG+URN0sHf
AdjiKQ1p9Qmup0O4s7xAMZk4uCt/zlQ6isHIEUjZ/O7uOX6WbcACK/06vSsv5el6
HrAAbrbUtKszGR9pHxzexMr0z3FlpxBUd4xKIAZM/NlB2vC47FS/cGXiavcp5UCJ
ucEu1x5RVG/RdE4VC0CPmyzYyQlTKXzXTRgAa0fbMwLoTib7/f5y3WWHg8szym67
jQezu7snr63B7VmFGzrhR9JrXTZ0cip8DA8+NVOPpv7rIRuqeE7XF3qXko/UkABE
BYhmO58BUeZoF6lDzLa6Pdv2Qjh7WC6Tr+2lfZEQyFlIcdVRVDAmjif7IiAt3UA8
SKU3S3K7uu0KZbAtP7v9NCC0BVUwPD9a95IRaoHRKb1HTIfvp2f/atCCBVSustdd
tA86qg5TXJPyzbY5SS/aNvic54qd7J6HFCJeT9pnzV1T+FWreLizSU7wdAZLc5Nv
MwdSTCyqHaXIIAPxhIGikMTQvXeQgWby7ncrnbi49DocZzpsV+O6qlgeUu8GkykA
oU5YtmTZh2OUiiaTfbcAXFygltj/N0PnePpnYdBC69/Kj9mZSYsemLhk+Oe+UqSa
vHGwJd6CC+1D0aW5thCwXzw4J9rLPkb1Jh88OK3S1AX0lyEwbMXjTW3FRZuKaFno
ns5oHFJFCmzHxz4xF5o9de/bVDU8+WcYKUwB6QBeKUWGYhyiI4wMrtyO2EdApYfq
X7iT6UInaqCSGNAknG/bJKp/2aEI4ZP/JYsmr4CckV56vp7GCK9izKZHUAiFMV6q
EDDNwdEOD2iXthgpz1QBlZne3DDeWeRL/S3VktDmuqy+b6q7umVBHdufj1lmfbfS
C8yoMKrd3a/jMboRjAwmvJgJn/rdQ0p0KTGMZSfMYIkdl4+eGh8cQAnSywZZAD0=
=M5Tb
-----END PGP MESSAGE-----
```

**Comment by lemieux** [comment]
Yeah, I lost access to my account and can't decrypt this obviously. As I said, not sure what to do about this.

**Comment by lemieux** [comment]
I'm not sure how I can prove my identity to you with other means. This encrypted message is useless to me since I no longer have my private key. I've verified my account with DNS, and multiple social accounts.

Apparently, my main email account (marc@marcantoinelemieux.com) wasn't linked to that account for some reason, even though I was invited on that one for the alpha. I have no idea on to recover access to my account at this point.

**Comment by maxtaco** [comment]
I see you've proven this github account, so if you consent, I can just reset your account here.  Also, as backup, can you post:

```
@maxtaco tlxy9kox5k1oZxp9j1O0ud8tOpOZRbPIxzDyyzwl
```

to twitter?

**Comment by lemieux** [comment]
sure thing!

**Comment by maxtaco** [comment]
ok, i've reset your account, thanks for bearing with me

you can now use the "passphrase recover" option of the Web-based login form

**Comment by lemieux** [comment]
hmm so what's supposed to be different? when trying the form I still don't get any email anywhere to recover my passphrase

**Comment by maxtaco** [comment]
oh right, this problem too.  one sec

**Comment by maxtaco** [comment]
i see the problem btw, you left out the 2nd `i` in your email address.

**Comment by lemieux** [comment]
......... lol.

**Comment by lemieux** [comment]
no wonder I didn't get any email ever

**Comment by maxtaco** [comment]
yeah, you had `marc@marcantoinelemeux.com`

ok, try the email recovery again, should work

**Comment by lemieux** [comment]
all good! thanks a lot :)

**Comment by lemieux** [comment]
I wonder how my account got verified in the first place though 🤔 I guess the alpha didn't have much verifications back then

**Comment by maxtaco** [comment]
we don't use email verification for much, since a lot of people don't bother with it.  the DB shows your email was never verified.

**Comment by lemieux** [comment]
oh I thought you said it was verified in the first messages of this thread
