### ISSUE TITLE
"Provably" typo when browsing public folders

### ISSUE THREAD

**Issue by domainzero** [keybase/keybase-issues#2890]
Easy but inconsequential one!

When browsing publicly shared folders there is text that says:
"Who is also provably:" instead of probably.

**Comment by songgao** [comment]
@malgorithms would know for sure, but I believe it's intended to be "provably", meaning: "Who is also provable to be:". The key is proofs exist for each of the links following that line :)

**Comment by strib** [comment]
Thanks, but not a typo, as @songgao says.

**Comment by domainzero** [comment]
dude i'm a dumbass. thanks for the heads up.
