### ISSUE TITLE
Login error, SecretSyncer device ID already exists

### ISSUE THREAD

**Issue by abaustin1** [keybase/keybase-issues#2891]
Sorry I don't have the exact text of the error any more, but here's a summary of what happened.

1. Clean install of Keybase Windows
2. keybase login haltandcatchfire
3. Enter password
4. Enter name of device
5. Error device name already exists (this was true, I typed in the exact name I used before)
6. keybase login haltandcatchfire
6. Enter password
7. Error SecretSyncer device ID exists
6. Kept getting same error every time until I deleted config.json

**Comment by maxtaco** [comment]
We have fixed this but haven't released it yet. Thanks.
