### ISSUE TITLE
Where is the private key?

### ISSUE THREAD

**Issue by damccull** [keybase/keybase-issues#2892]
If we let the client generate us a private key, then don't upload it to the servers, where do we find it for manual migration to another device?

**Comment by cjb** [comment]
Which OS are you running?

Do you know whether you're asking about a Keybase device key or a PGP key?

**Comment by damccull** [comment]
@cjb I apologize for not being specific enough. I'm fairly new to PGP and just installed Keybase today. I'm referring to whichever key does the encryption. I believe that's the PGP key. I'm running on Windows for this device, but I'd like to know where it's stored on Linux too, since I also use that.

**Comment by cjb** [comment]
Hm, thanks.  On Linux it should be the `$HOME/.config/keybase/` and perhaps `$HOME/.gnupg` dirs, I'm not sure about Windows, CC @zanderz.

**Comment by pwendelboe** [comment]
It should be possible to use the keybase command line and use the command
`keybase pgp export`
The command
`keybase pgp`
will give you a help on that sub-command.

As to where it's stored I'm not sure but I know when I import the keybase keys of others I am able to see them in kleopatra part of gpg4win.

Hope that helps. I haven't used the command myself but I would expect it to be straight forward.

**Comment by Quantumplation** [comment]
Hello!

I have an old laptop hard drive that contains the key I generated for my keybase account.  it would be useful to know exactly where the private key is stored, so that I can grab the file and re-import it to my current keybase installation.

Operating system is Windows 10.  It might be an older version of keybase, from some time late 2016 / early 2017.

**Comment by zanderz** [comment]
`%localappdata%\Keybase` is the directory and the device files end with `.ss`

**Comment by archywilhes** [comment]
What about Mac OS? Where can I find my private key?

**Comment by archywilhes** [comment]
Is it this one: `/Users/a/Library/Application Support/Keybase/secretkeys.{username}.mpack`?

**Comment by Hexstream** [comment]
I *think* that's the device key, not the PGP key.

(This is a non-authoritative answer, I'm still figuring things out...)

**Comment by GrossDomesticHappiness** [comment]
I successfully restored a Keybase device to a new computer running macOS by copying the following files from a Time Machine backup:

1. `~/Library/Application Support/Keybase/secretkeys.<username>.mpack`
2. `~/Library/Application Support/Keybase/config.json`

After restarting the Keybase application I was able to sign in using my credentials without having to authorize with an existing device.

**Comment by Hexstream** [comment]
Right. [I wish keybase supported such "device migrations" natively...](https://github.com/keybase/keybase-issues/issues/3565)

**Comment by DanyC97** [comment]
> I successfully restored a Keybase device to a new computer running macOS by copying the following files from a Time Machine backup:
> 
>     1. `~/Library/Application Support/Keybase/secretkeys.<username>.mpack`
> 
>     2. `~/Library/Application Support/Keybase/config.json`
> 
> 
> After restarting the Keybase application I was able to sign in using my credentials without having to authorize with an existing device.

thank you very much for sharing this info!!

**Comment by pol500** [comment]
I can’t log into my computer account. no saved phrases. How to restore access to an account on a computer? will the  XLM airdrop disappear? account was tied to a phone number
