### ISSUE TITLE
Keybase Updating?

### ISSUE THREAD

**Issue by briandcosta** [keybase/keybase-issues#2894]
Hey,

Since I installed Keybase a few weeks ago, I've gotten one update push. How can we tell if a new version is out and that the updater is checking?

--Brian

**Comment by cjb** [comment]
Good questions!  Assuming macOS:

1) New version is out:

`keybase version` != version in http://prerelease.keybase.io.s3.amazonaws.com/update-darwin-prod-v2.json

2) that the updater is checking

`~/Library/Logs/Keybase/keybase.updater.log` should show you what it got back from that URL once an hour.

**Comment by briandcosta** [comment]
Hey, here's what I found in the log so it does look like it is going after updates, but I guess I'm on the "stable" track, which is fine!

2017/03/08 11:16:41 DEBG Checking for update (ticker)
2017/03/08 11:16:41 DEBG Execute: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2017/03/08 11:16:41 DEBG Executed /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2017/03/08 11:16:41 DEBG Execute: /usr/bin/sw_vers [-productVersion]
2017/03/08 11:16:41 DEBG Executed /usr/bin/sw_vers [-productVersion]
2017/03/08 11:16:41 INFO Checking for update, current version is 1.0.18-20170223162556+af0e640
2017/03/08 11:16:41 INFO Using updater source: Keybase.io
2017/03/08 11:16:41 DEBG Using options: updater.UpdateOptions{Version:"1.0.18-20170223162556+af0e640", Platform:"darwin", DestinationPath:"/Applications/Keybase.app", URL:"", Channel:"", Env:"prod", Arch:"amd64", Force:false, OSVersion:"10.12.3", UpdaterVersion:"0.2.8"}
2017/03/08 11:16:41 INFO Request "https://api.keybase.io/_/api/1.0/pkg/update.json?auto_update=1&install_id=73037613bcdf49153f14af24489a053b7f71401f3c6b771d&os_version=10.12.3&platform=darwin&run_mode=prod&upd_version=0.2.8&version=1.0.18-20170223162556%2Baf0e640"
2017/03/08 11:16:42 DEBG Received update response: updater.Update{Version:"1.0.18-20170223162556+af0e640", Name:"v1.0.18-20170223162556+af0e640", Description:"Recent changes:\n---------------\n- Keybase has a new icon. We thank our departing ferret-dog mascot for his years of loyalty.\n\n- Keybase Chat has launched! You can read more about it on the Keybase blog.\n\n- Sharing before signup: Go ahead and put data in /keybase/private/you,friend@twitter/. If you have any invite codes, this will pop up a window with a link to DM them. It also works for end-to-end encryption with Reddit, Coinbase, Github, and Hacker News users.\n\nWhat we are currently working on:\n---------------------------------\n- Mobile apps!\n", InstallID:"73037613bcdf49153f14af24489a053b7f71401f3c6b771d", RequestID:"", Type:0, PublishedAt:1487867156000, Props:[]updater.Property(nil), Asset:(*updater.Asset)(0xc42012fd60), NeedUpdate:false}

**Comment by cjb** [comment]
Yep, that's all correct -- the "prerelease" stream is actually just for Keybase employees.  Probably there'll be a new "production" stream release tomorrow or the day after.
