### ISSUE TITLE
Minor grammar issue on the website.

### ISSUE THREAD

**Issue by ckj9779** [keybase/keybase-issues#2898]
![screen shot 2017-03-09 at 3 08 28 pm](https://cloud.githubusercontent.com/assets/8650796/23774801/5efdc124-04da-11e7-8d88-1b31586ed503.png)

Encrypt should be Encrypted if the rest of the sentence is not changed.  Some have questioned the validity of the service as the apparent typo seems to signal spoofing.

**Comment by cjb** [comment]
Thanks for the typo, CC @malgorithms to fix.

The typo is just a typo.

**Comment by malgorithms** [comment]
thanks, fixed! (will be deployed soon)
