### ISSUE TITLE
twitter proof not working for me

### ISSUE THREAD

**Issue by leitmedium** [keybase/keybase-issues#290]
Hey,

twitter prove is not working for me (leitmedium). On the command line:

![juu2](https://f.cloud.github.com/assets/305663/2458858/e142d82c-af51-11e3-97f6-58053bf2df2d.png)

On Twitter:

https://twitter.com/leitmedium/status/446230602497671168

**Comment by ruudk** [comment]
I just tried to prove myself on Twitter and forgot to include "Verifying myself: " in the tweet too. It took me a while before I found the issue. 

Maybe the output should be quoted and with a warning that exactly the stuff between quotes should be posted :)
