### ISSUE TITLE
Feature Request: Slack-like (or Github-like) performance for typing out emojis

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/keybase-issues#2901]
Emoji functionality along the lines of Slack.... where you can type an emoji beginning with a ':' and from what you type, it helps you select an emoji.  An example, rather than clicking on the emoji button to select a thumbs up 👍, I can just type ': + 1 : (sans spaces) and the emoji presents itself, rather than having to forceably remove my fingers from the keyboard to grab a mouse, and navigate my way to whatever emoji I'm feeling at that moment.  I'd rather type it.  Further, I'd also have functionality where the keybase chat is able to remember my favorite emojis to make it easier for me to quickly decide on an appropriate emoji 😉 .  

Perhaps it could be a github functionality request too... as it is also predicting emojis... 😜

**Comment by jtsmith0101** [comment]
#just_saying

**Comment by AlJohri** [comment]
👍 I need me some typable emojis

**Comment by replaid** [comment]
I think this one can be closed now that this feature is in Keybase.
