### ISSUE TITLE
Issue with Keybase reporting failure to connect to website after switching from apache to nginx

### ISSUE THREAD

**Issue by samdmarshall** [keybase/keybase-issues#2918]
Over the weekend i switched from using apache to nginx as what was serving up my website ([pewpewthespells.com](https://pewpewthespells.com)); since then keybase has been reporting my website as offline or unavailable. if there is any additional information I can provide about this issue, i'd be happy to!

**Comment by cjb** [comment]
@samdmarshall I'm seeing an SSL failure when I run:
```
λ curl https://pewpewthespells.com
curl: (60) server certificate verification failed.
```
I think this probably means you're missing an "intermediate certificate" in your nginx setup.  If you can fix and get the site working again in curl, it'll start working for Keybase again too.

(Sometimes browsers are more permissive about missing intermediate certs than curl and Keybase are.)

**Comment by samdmarshall** [comment]
ah, i see. thanks for this info; i was able to resolve this by regenerating my full certificate chain.
