### ISSUE TITLE
Unable to prove http website

### ISSUE THREAD

**Issue by sloria** [keybase/keybase-issues#2919]
I've posted my proof at http://beliefs.stevenloria.com/keybase.txt , but keybase is not able to find it. I have tried adding the proof through both the desktop and the CLI clients.

**Comment by fiatjaf** [comment]
I believe this issue has already been solved.

**Comment by sloria** [comment]
No, I just tried again, and it is still an issue.

**Comment by fiatjaf** [comment]
I said that because I see your site as confirmed on your profile.

**Comment by sloria** [comment]
It isn't. http://stevenloria.com is proven, but http://beliefs.stevenloria.com is not.

**Comment by maxtaco** [comment]
User error.  You posted sig chain link 27, and later made link 50 to prove the same thing, and we're looking for 50

https://keybase.io/sloria/chain

**Comment by sloria** [comment]
Ah gee. Sure enough. Reposted keybase.txt , and I was able to prove the site. Thanks!

**Comment by maxtaco** [comment]
Cool glad it worked.   We need to fix the error reporting path to make it
more clear what went wrong. This is a fairly common mistake.
