### ISSUE TITLE
Request: Time Certification Service

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#2926]
# About

I think it would be cool to have the ability to validate that someone said something at a specific time.

### Possible flow
1. User signs a message / file and chooses to have the signature certified
2. Keybase client sends hash of signed message(?) to some keybase hosted service
3. Time service grabs its epoch time and composes a message to sign that contains epoch time + input hash
4. Time service returns a signed message saying it received content with **X** at **Y** time
5. Keybase client slips the certified time signature into the resulting message for the user.

I know there would be a lot of moving parts to this and that it may be difficult to implement safely / sanely, but I think it could be a cool feature.

**Comment by maxtaco** [comment]
Great idea.  We have preliminary support for this feature with a "Proof Of Existence" slot in the main merkle tree.  We'll hopefully get to this soon.  The idea is to get the time certification into our tree and therefore into the bitcoin blockchain ASAP
