### ISSUE TITLE
Proving web identity does not work

### ISSUE THREAD

**Issue by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [keybase/keybase-issues#2929]
I put the generated keybase.txt file into my domain's root and started the verifying process. The answer is: We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely. I cannot see any mistake an I am able to open the file in any browser on any machine.
The link: www.boehlk.com/keybase.txt.
The hint trying the cl-app leads to a new issue describing a design error.
Regards
Andreas

**Comment by mlsteele** [comment]
I think this is failing because http://boehlk.com/.well-known/keybase.txt returns a `300` Multiple Choices.

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Why should I use this link You have mentioned. The original works and is a possible location.

**Comment by mlsteele** [comment]
I agree, don't change anything, we should be able to fix this on our end easily. I was just noting what's unique about this situation that leads to the bug.

**Comment by mlsteele** [comment]
There, now boehlk.com is working.

It hasn't retried your other domains, but I don't think they will work because they're behind 401s. There is a retry button if you click the red `http!`s next to failing proofs on https://keybase.io/boehlk

![image](https://cloud.githubusercontent.com/assets/705646/24729873/5393bf46-1a2e-11e7-9e07-b9b14eb50357.png)

**Comment by zoof** [comment]
Hi, I don't know if it is related or not but today, I noticed that proof of my website (theo.to) has been failing.  Prior to today, it was working fine.  The only change on my end has been a transition from a StartSSL cert to a Let's Encrypt cert.  Clearly my proof is still accessible as you can see at: https://theo.to/keybase.txt

**Comment by mlsteele** [comment]
@zoof That might have to do with your server not serving the whole certificate chain. https://www.ssllabs.com/ssltest/analyze.html?d=theo.to
`Chain issues: Incomplete`

**Comment by zoof** [comment]
That was it, thanks!

**Comment by mlsteele** [comment]
@zoof great :)

@HXmniDhWNevihHm7PwVyN4Knvt9yQrRt your other domains have basic auth and return 401 to the checkers.
