### ISSUE TITLE
0x80070005 - Access is denied when installing; Windows 10

### ISSUE THREAD

**Issue by Lyxnx** [keybase/keybase-issues#2938]
When installing on Windows 10, the installer gets to the initialisation stage and asks for elevated privileges. It then fails with the above error code and message.

Here's the log file that it presents to me:
[Keybase_20170402195838.txt](https://github.com/keybase/keybase-issues/files/888585/Keybase_20170402195838.txt)

**Comment by zanderz** [comment]
Someone else with this exact error solved it by temporarily disabling their antivirus. Are you running one?
https://github.com/keybase/client/issues/6412#issuecomment-290195427

**Comment by zanderz** [comment]
@Lyxnx Did disabling your antivirus help?

**Comment by Lyxnx** [comment]
@zanderz Ah yes, thank you. Sorry - forgot to post back here.
