### ISSUE TITLE
DNS Proof fails on Amazon Route 53

### ISSUE THREAD

**Issue by mrapplegate** [keybase/keybase-issues#2943]
I am having trouble with my DNS proof on Amazon's Route 53 DNS provider.
I set the @ record to my domain and set the text as instructed but it is not working. 
Any suggestions?
Paul

<img width="1897" alt="screen shot 2017-04-06 at 12 24 55 pm" src="https://cloud.githubusercontent.com/assets/441081/24765087/82286de8-1ac4-11e7-877d-127c1e753ab1.png">

<img width="419" alt="screen shot 2017-04-06 at 12 25 09 pm" src="https://cloud.githubusercontent.com/assets/441081/24765092/84c27774-1ac4-11e7-922e-712f467a5505.png">

**Comment by maxtaco** [comment]
you have a long TTL and have to wait an hour before it shows up

**Comment by mrapplegate** [comment]
I've had problems since yesterday. I re-submitted this morning around 11:30am EST.

**Comment by mrapplegate** [comment]
I'm not seeing my TXT record when I run a query using dig.
dig -t txt paulapplegate.com

; <<>> DiG 9.8.3-P1 <<>> -t txt paulapplegate.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12377
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;paulapplegate.com.		IN	TXT

;; ANSWER SECTION:
paulapplegate.com.	3599	IN	TXT	"v=spf1 include:_spf.google.com ~all"

;; Query time: 63 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Apr  6 19:12:56 2017
;; MSG SIZE  rcvd: 83

When I try to add a blank TXT record I get an error. I already have one for Google's services.
That's why I used an @ as instructed in the instructions.

<img width="422" alt="screen shot 2017-04-06 at 7 15 37 pm" src="https://cloud.githubusercontent.com/assets/441081/24779307/87da5f60-1afd-11e7-97a2-c99ed925947a.png">

**Comment by mrapplegate** [comment]
It's obvious now this is a problem with Amazon's Route 53 DNS, not keybase.io.
Please ignore.

**Comment by PaulRBerg** [comment]
@mrapplegate Route53 is working well. There are two things that I did to make it work on my end:

## Delete the "@" from the record name

It's misleading because Keybase recommends setting "@" as the record name. Not sure why Keybase can't verify a TXT record from Route53 this way.

## Span values over multiple lines

As explained in this [ServerFault thread](https://serverfault.com/a/814050/457461), you can set multiple values for the same TXT record name by listing them on multiple lines. Example:

```
ms=M23445345
v=spf1 include:spf.protection.outlook.com -all
```
