### ISSUE TITLE
How does the chat API actually work?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [keybase/keybase-issues#2951]

**Comment by mlsteele** [comment]
Try running ```keybase chat api -h```, there are a bunch of examples in there.

```
# to list your inbox
echo '{"method": "list"}' | keybase chat api
```

**Comment by MarcelloTheArcane** [comment]
(accidentally posted without description)

anyway, `keybase chat help api` returns different JSON strings and their uses, but no instructions about how keybase is expecting the JSON string. I've tried saving a string and piping it into `keybase chat api -m`, and `keybase chat api -i "[JSON string]"`, both to no avail.

what is the correct way of using this feature?

**Comment by mlsteele** [comment]
Ah, like this for files, which is fine for testing but has the drawbacks of making sure not to leave the files around readable.
```
echo '{"method": "list"}' > /tmp/in.json
keybase chat api -i /tmp/in.json -o /tmp/out.json
cat /tmp/out.json
```

For piping, omit `-m`. `-m` means you're supplying the json as a command line arg.

**Comment by MarcelloTheArcane** [comment]
thanks, I'll try that. How would you get that to work with, say, a chatbot? @malgorithms, possible update? it's not super clear on the website or CLI...

**Comment by songgao** [comment]
There are some examples [here](https://github.com/keybase/keybase-chat-bot) for building a chat bot. Hope it helps!
