### ISSUE TITLE
HTTPS and TOR

### ISSUE THREAD

**Issue by MarcelloTheArcane** [keybase/keybase-issues#2952]
I noticed keybase uses an [http site for TOR](http://fncuwbiisyh6ak3i.onion), something that is [not advised](https://security.stackexchange.com/questions/105646/is-it-safe-to-access-http-sites-from-tor).

Is this something that should be changed?

**Comment by malgorithms** [comment]
from that same page:

> This does not apply to hidden services (.onion websites). In that case the encryption is end-to-end and another https layer is redundant (and counter-productive because one purpose of https is to de-anonymize the server).

**Comment by MarcelloTheArcane** [comment]
ahh, okay.
