### ISSUE TITLE
Can't import a GPG key

### ISSUE THREAD

**Issue by totakura** [keybase/keybase-issues#2956]
I tried to import a GPG key after removing an old one using the command:

    keybase pgp select --no-import

When I selected the right key index to import, it printed out `▶ ERROR EOF`

The GPG key has only the public part of the certification key, and both public and private parts for the encryption and signing sub-keys.  The certification key is RSA4096 and the subkeys are ECC keys based on cv25519 and ed25519 curves respectively:

```
pub   rsa4096 2017-04-12 [SC] [expires: 2027-04-10]
      1E4F65F71279BCCBA7FA1B6D5B34C9C79172DC6D
uid           [  full  ] Sree Harsha Totakura <totakura@hi1Tee.gh>
uid           [  full  ] Sree Harsha Totakura <ttkr@hi1Tee.gh>
uid           [  full  ] Sree Harsha Totakura <sreeharsha@hi1Tee.gh>
sub   ed25519 2017-04-12 [S] [expires: 2019-04-12]
sub   cv25519 2017-04-12 [E] [expires: 2018-04-12]
```

This is the log generated during the import: [import-failure.txt](https://github.com/keybase/keybase-issues/files/919417/import-failure.txt)

**Comment by maxtaco** [comment]
Can you do 'keybase log send'?

@zapu can you triage?

**Comment by totakura** [comment]
Sure, the log is uploaded with ID 8bf96f15d1e881e6e78cda1c

**Comment by totakura** [comment]
I also noticed the same error on another computer which has the private part of the certification key.  It's log is uploaded with ID: e927c3843c009594b5875d1c

**Comment by maxtaco** [comment]
Old version, can you upgrade?  Should work.

**Comment by totakura** [comment]
I'm using 1.0.20; that is to the latest version, right?

**Comment by maxtaco** [comment]
Your log said 1.0.18 I believe.

What platform are you on?

**Comment by totakura** [comment]
I'm on Arch Linux. Strange, `keybase version` says `Client: 1.0.18`.

**Comment by maxtaco** [comment]
@oconnor663 can you help?

**Comment by totakura** [comment]
Found it, the package recipe is indeed using the older version. https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/keybase

Reported the package bug here: https://bugs.archlinux.org/task/53661

**Comment by oconnor663** [comment]
For context, this is the Arch `community/keybase` package, which is not the one we maintain or recommend in our [install instructions](https://keybase.io/docs/the_app/install_linux). It's missing the KBFS and GUI elements, and while it's probably going to keep working for the foreseeable future, the divergence is going to get more confusing over time.

**Comment by zapu** [comment]
@totakura do you still have this issue? If so, would you mind posting your public key so I can check if our libraries parse it correctly? Thanks

**Comment by totakura** [comment]
Yes, this has been fixed; apologies for not noticing your comment earlier.
