### ISSUE TITLE
Can not confirm FACEBOOK

### ISSUE THREAD

**Issue by dennis-linux** [keybase/keybase-issues#2957]
https://www.facebook.com/dennis.a.hunter?ref=bookmarks

**Comment by paulhugel** [comment]
paulghugel unreachable proof is public https://www.facebook.com/paulghugel/posts/620211368180926

**Comment by paulhugel** [comment]
revoked  Facebook proof
deleted proof on Facebook
Created new Facebook Proof
https://www.facebook.com/paulghugel/posts/698602103675185
rechecked and still says "UNREACHABLE":

![screen shot 2017-04-24 at 5 45 37 pm](https://cloud.githubusercontent.com/assets/6466830/25368098/06d21e40-2916-11e7-9755-e22e7e1153fa.png)

**Comment by maxtaco** [comment]
@oconnor663 can you take a look?

**Comment by oconnor663** [comment]
@paulhugel your Facebook proof looks like it's working now, both on keybase.io and when I `keybase id paulhugel` on the command line. Some temporary issue?

Looking at @dennis-linux now.

**Comment by oconnor663** [comment]
@dennis-linux it looks like you've tried to prove the username `dennis7x` on Facebook, but I [don't see any account by that name](https://www.facebook.com/dennis7x). The account you linked to at the very top uses the name `dennis.a.hunter`; is that the account you meant to prove?

**Comment by paulhugel** [comment]
my facebook proof from the OSX GUI was unreachable but now show its good entered command

keybase id --skip-proof-cache

and it shifted timing out several times but now is normal ?
![screen shot 2017-04-25 at 5 47 52 pm](https://cloud.githubusercontent.com/assets/6466830/25417460/fd002c70-29df-11e7-8e7b-03c4465fafb1.png)
