### ISSUE TITLE
Installer fails when MS Visual C++ 2017 Redistributable is present

### ISSUE THREAD

**Issue by soyfrien** [keybase/keybase-issues#2958]
The installer fails when trying to install the Microsoft Visual C++ 2015 redistributables on systems with the 2017 versions.

Uninstalling them allows the keybase installer to successfully finish, but Visual Studio 2017 installs these and I'm not sure how else to get them, so this is doubly inconvenient.

Please see [installer log file](https://github.com/keybase/keybase-issues/files/924228/keybase-installer.txt).

**Comment by ppdac** [comment]
I found the redistributable, under _Other Tools and Frameworks_: https://www.visualstudio.com/downloads/

**Comment by soyfrien** [comment]
Enjjoy your vacation @malgorithms, we ain't mad atcha. I would try the new version but all the issues I see about the random loss of pgp functionality and with it messaging
