### ISSUE TITLE
Secure chat sits in "securing..." loop forever

### ISSUE THREAD

**Issue by taw00** [keybase/keybase-issues#2959]
Originally posted here: <https://www.reddit.com/r/Keybase/comments/662425/secure_chat_sits_in_a_securing_loop_forever_this/>
Version: keybase-1.0.21.20170414160027.c035b7e-1.x86_64

> Note: I am on a slow internet connection at the moment[1]. That may be a contributing factor, or a red herring, I will not know until I visit a faster connection.

**The issue:** The keybase application comes up on my desktop. I log in and notice someone has sent me a chat message. This is someone I have been chatting with back and forth for months. I click on his icon and keybase goes into a "securing..." loop forever. I have tried exiting and re-loading the application. I clicked on an old chat interaction as well to see if the issue was a general issue. It is. Same problem.

The rest of the interface seems to work fine.

-todd
![screenshot from 2017-04-18 06-51-12](https://cloud.githubusercontent.com/assets/6908872/25128203/e1cc0fe8-2406-11e7-9fb5-b2d4b9f52322.png)

[1] This is a satellite internet connection. When I have not blown my data cap, it is actually pretty speedy (considering). I do VOIP and video conferencing over it. I VPN to work, etc. All these things still function after I have blown my cap but they do slow things down tremendously. Still functional, just very slow.

**Comment by rob-nash** [comment]
I have the same issue. I am using Starbucks wifi. 
Version 1.0.21-20170413194119+9dea6e1

**Comment by taw00** [comment]
I finally went to a very high speed network (fiber, I believe) and it continued to sit forever in "securing..." until I exited out completely (an explicit "Quit") and then restarted. I am not sure if my slow network created some caching issue or not, but it did resolve eventually on the high speed network after taking that action. And, going back home to the slow, high-latency, network... it just sits there in the "securing..." loop again.

Note: Everything else works. I can see my profile (though that sometimes requires a click away and a click back). KBFS works (I use KBFS pretty regularly with some large files even) though sometimes it will require a `run_keybase` periodically.

I think what is missing is testing and tuning to higher latency networks (or just slower networks?). I would be curious if that wifi network that rob-nash commented on above was pretty sluggish.

**Comment by zQueal** [comment]
This is pretty interesting. I've tested the chat before and it seemed to work immediately. Opening the same conversation as before it took upwards of 1 minute to "decode" and initialize two test messages. Probably less than 10 words total.

What are your PC specs? Specifically your processor. Perhaps its an issue with processing?

**Comment by rob-nash** [comment]
MacBook Pro (Retina, 13-inch, Late 2013)
2.8 GHz Intel Core i7
8 GB 1600 MHz DDR3

**Comment by taw00** [comment]
Duplicated on two machines with me...

1. Lenovo T460s
    * Intel i7 2.6GHz
    * 20GB RAM
2. Razer Blade Stealth
    * Intel i7 2.7Ghz
    * 16GB RAM

So, all are pretty beefy machines. And Intel

**Comment by maxtaco** [comment]
@taw00 there might be something wrong with your account. Can you do a `keybase log send`?

**Comment by rob-nash** [comment]
there might be something wrong with my account too :(

**Comment by maxtaco** [comment]
log dump: 54cc38f0f65ad6c545973d1c

@mmaxim can you take a look?

**Comment by maxtaco** [comment]
I take it back, BTW, there's nothing wrong with your account, but maybe something wrong with this conversation

**Comment by nova77** [comment]
Same here: it's been sitting on "securing..." for the past 10 minutes and I have a pretty good connection (1GB/s). Win-10/64.

**Comment by taw00** [comment]
It's been 5 years. Closing.
