### ISSUE TITLE
Desktop Client Supports Adding Phone But No Mobile Apps Available

### ISSUE THREAD

**Issue by compumike08** [keybase/keybase-issues#2960]
In the latest version of the Keybase desktop client, when you add a new device there is an option to add a new phone via scanning a QR code (although the option is labeled as "[in beta]"). However, I was unable to find any Keybase app for mobile phones in either the Android App Store or the Apple App Store. I also was unable to find any mention of mobile phone apps on your [website](https://keybase.io/).

While I realize the option is labeled as "in beta", are there any Keybase mobile phone and/or tablet apps available yet? If so, how can I download one (either for an iPhone or a Samsung Galaxy tablet)? I am interested in participating in the mobile phone beta, if possible.

If your mobile phone app beta program is not open for any Keybase member to participate in at this time, I would suggest you modify for desktop client UI to make it more clear that the "New phone [in beta]" option when you add a new device is **not** available for everyone to try at this time. Simply labeling it as "in beta" in the UI implies that, while the feature may not be "finished" yet, it is something that any Keybase member can use, if he/she wants to. This can lead to confusion if users then try to find the mobile app to download and cannot find one.

@malgorithms

**Comment by compumike08** [comment]
Related to issue #2758.

**Comment by danieldavidpeterson** [comment]
I second this, I still can not find any mention of a mobile app.

**Comment by zQueal** [comment]
I know for a fact that there _is_ an Android app under development but, to quote @MarcoPolo;

> it's very buggy and in desperate need of love

I can't see them developing an Android client without also developing one for iOS. My advice would be to assume that they're coming, just simply don't hold your breath for anything too soon.

**Comment by MarcoPolo** [comment]
Apps are live!
