### ISSUE TITLE
Finder App does not display file in public folder

### ISSUE THREAD

**Issue by rob-nash** [keybase/keybase-issues#2962]
I don't remember when I created this file. I totally accept that I may have actually created it at some point.

https://keybase.pub/rob_nash/plan.txt

I can't access the file using the macOS Sierra Finder App. I have installed the macOS client App and the command line tools.

I abandoned my account for quite a while and I may have created plan.txt a while ago. I have since reset all of my keys.

**Comment by strib** [comment]
Hi @rob-nash, I fixed keybase.pub for you (I think your old public folder was too old to be reset automatically on an account reset, which is what's supposed to happen).  You should be able to start seeing your local public folder changes show up on keybase.pub now.  Please close this out if things look ok to you now.

**Comment by rob-nash** [comment]
Thanks
