### ISSUE TITLE
Moving keybase.txt to .well-known broke proof

### ISSUE THREAD

**Issue by tanto259** [keybase/keybase-issues#2966]
I moved keybase.txt from `/keybase.txt` to `/.well-known/keybase.txt` yesterday and I just got the email saying my web proof just broke.

I can verify that I can access the proof at `/.well-known/keybase.txt`.
Do I need to wait or do I need to set up a 301 redirect from `/keybase.txt` to `/.well-known/keybase.txt`?

I have already tried to retry proof checking, but I still got the web proof broken email.

**Comment by malgorithms** [comment]
sorry - I think currently the way it works is when keybase verifies a proof it notes which location you chose and won't switch to the other one. It should, but we're unlikely to get to that soon. If I were you, I'd do the simplest thing which is just revoke/redo the domain proof.

**Comment by tanto259** [comment]
Thanks, redoing the proof fix it.
