### ISSUE TITLE
Reset account via signed message

### ISSUE THREAD

**Issue by apfelchips** [keybase/keybase-issues#2967]
A very long time ago I've created a keybase account, but for 'security reasons' I foolishly didn't put the credentials into my Password-Manager and used a unique eMail-Address that I also don't know/control anymore to sing up to the service.

So lately I wanted to make some changes to my keybase account and start using all its new features, but all the recovery options don't work for me and so I'm locked out.

What I do have control over is my PGP-Private-Key of which the public key is stored on my KB-account and the twitter handle used to verify it all this time ago.

So what I'm asking is to please give the option to reset your Keybase account by signing a reset message, and/or make an exception in my case.

I've tried to contact @KeybaseIO via twitter in the past but didn't get a response and gave up, now I'm trying again here on github by opening this issue.

https://twitter.com/attero_/status/800834723031420928
https://twitter.com/attero_/status/800836507560919041
https://pastebin.com/6XnjuWML
[https://keybase.io/attero_](https://keybase.io/attero_)

**Comment by mlsteele** [comment]
Hi @apfelchips sorry for the slow response! You should be able to get back into your account from the pgp key but we have a bug with that right now. Would you sign an email address that you would like to use for your account after a reset? If you don't want to post it publicly, you can encrypt to my key: https://keybase.io/mlsteele

**Comment by apfelchips** [comment]
Oh thanks.

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.70
Comment: https://keybase.io/crypto

wcBMA8wAq9xUlS/pAQf9GyRKm2nEO2H5Tfbw1iobm0PFANGg1yGek6dpFK3vpupL
wHeVqdKzoQakRN1s25sgR8nJ4lDMOvsUpDqJe+4xIX1dDfJjyQ8v34JHYj0Gi1S2
0UnMF/NZe+61fEOBY0Vrmoc3w820Vt4bdyqTxr9r9eVTNPFU9+jMcswwBBhB1y+S
oQAUdVivTjSYM6c11NvToZQxkF0UF+0enixaeHlLLyeCavyKvfIulLhmF45wpmMu
No0UiOzJpPNgYc0fZY4Rd5TG0S9qPupPHvtfAEDr5NnKFIc9k2OQuUaeeVz0HCE7
Ky4vDj5+1okDepvLvWmVwImrTqvC/u+HD/YbjsNP7dJ6AeaFekm2AhMxwU8aQ6Xh
LqtDC5lbraLDUasPmNJdKU/fnL122wgNLDfoLYw7lbMQDHH+2ne9dVwXhgjhZ9LA
lG9/GAc3OswiphzqlO+90gKpBzt8QQAXpa8fSLD48OYc/cnz/PgUwZyrw2Drpp5K
89dRiJ4nD+ts6c8=
=9Eqf
-----END PGP MESSAGE-----

**Comment by apfelchips** [comment]
oh sorry didn't see the signing requirement there, anyways here it is...

-----BEGIN PGP MESSAGE-----

hQEMA8wAq9xUlS/pAQf+M0XO4RWwnmcuJwZ7pfbtRopx7tERX2Cqj53SHjXZu1Dk
3Uc8qi2i9UNhIdFz+6D73u3isSsGGFJkzZJDLjVkErtW8eozHJh8O+4tleYso34T
5p17Ase2ErraoBS530cfnJxClym4Ewje7OAnLXyJ+oWPjPHhD5OApo6gSDK3t8Im
BDMXnf+jN4vJyJMkKek9lDEVajtNBb7MxrtfSayo9xPOkxZ00Z0A1ugvkura9bSm
ypJDyqJj7eAl+DUCX2y2u8YXhvZpUW9hjggQbimgrKFjnw0YQ4x4hJ28khjLYGfX
Cdx9oQFOdPqzDN5cnCc0ktZrlwis2Ep48uSpP2Ucs9LpAdu7TYwp+J6337XEREIJ
lVhz12FJAik63ry2qPftn6itrXmHHJTxxKO5P2U8NDpJG6JfuPzBCk84V2IsvtoF
8lvPou2DFs17VlhEER6ckBu4dGM7eWGffiXdLEpRy/tVYzRui9MgqP+11AOI4OmX
C5+VmBJngoExiNXyqQkNRdWDgfuAU4Y2GjA/iKGG88mN8tvMJkYhW71ZCkKrI/qU
V4IX/UfMDrL7YEgKc8QRCioC0ZwfzjAJEudEF02WDcRG4PrGO4vG6rO2KSGm7SYz
mgwag/8g73DZmfBUIPk0AV37637nMUbyH8awmC4vWeGLc24D4OTHibz2f1ft+HL4
Nl8eDWmMp2mt3wsDLK/9uAFs+hTjEnD765S4MozchfAFi17hP7sG8Y8AvgdTljxx
Rn7O83VzYfApflp6GvYGe7ogrxBk07ra+A+z5RxjydA9QZbHuuC8B3rQ7eHlBVL6
+taTOMViQPHgXTvYL5gs2H2BUsiE8Fj4vxYHImuY0vzy2RkMRhJWlmhPizqGFEgz
6Nc/FcAjePGr7SXy/Q/aePdkgmPnBwLcPARtkSVEQM+BBLlfGVj7rT7Jn/eS1LVd
vJL6zfuDIUpa9BnKgnClyvg8eBitxUqmfJmLDL98+3DWye2DjVsq3xQK50IJ8QIb
kmqiuSmj5Z5Z9lCOjzlzvdzAOJlA+LFznDpBIcGQ1TuYnoQtOmmmSfQHiljlpFQS
ugCbHnkkDBQAknee3hXLi0aJJZ4r2WDDaPHA9U3Quof7kCoOhGh1pVH4CXsDZ9zo
ZVZV+D9oxxUammtsTnWUKVuFhzeWrigQ12BpDxmgCpZkgafvYWM8ZhHVeHhlNEhv
2XmaJTkFxk6b5YeiAn+2McAGBTZ3Z2udazoMXhrkPAGNpNUbiZLP3VZWhKMUCHcG
F28Pg/vNC67gJoWWVI4PqV4votWVbEPbrhcVnqSmvZsmJ7ZPZyJW4l/tPdsFFHAO
7DLNoDWxIk5zAlVV+3HZZNToM7WZDTFzDjih
=CRr0
-----END PGP MESSAGE-----
