### ISSUE TITLE
Information regarding provisioning of device. gpg and gpg2

### ISSUE THREAD

**Issue by epicpewpew** [keybase/keybase-issues#2975]
I had an issue with provisioning my device whereby keybase would not find the secret key.
* used linux OS. Kali linux to be specific
* initially my gpg keys were generated on the root account
* keybase only works on standard user accounts.
* need to migrate secret key on root to standard user

#### On root
``` 
gpg -export-secret-keys -a epicpewpew > epicpewpew.asc
```
everything works fine here

```
gpg --list-secret-keys --fingerprint epicpewpew 

```
output is as expected 

#### On standard user
```
gpg -import epicpewpew.asc
```
import would work fine but but once you type in
```
gpg --list-secret-key --fingerprint epicpewpew
```
the recently imported key (epicpewpew) would not appear and output from pubring.kbk would show that the imported key would be absent. 

```
gpg2 --import epicpewpew.asc
```
resolves the issue. Not a keybase issue per se but I thought it might be useful with some of the issues others are getting.

**Comment by zapu** [comment]
`gpg2` manages the keys a bit differently than `gpg`, with gpg-agent being non-optional; so usually the problem is related to Keybase using different `gpg` than the user is using (knowingly or not) and not finding the keys.

I'm glad you managed to solve your issue, thank you for using Keybase!

**Comment by BenjaminHCCarr** [comment]
The solution after much head banging, issue reading, and search for me was to use this:
`benc$ keybase config set gpg.command `which gpg1`
As you need gpg v1 and v2 seems to always fail... on OSX `gpg` is symlinked against `gpg2`

And THEN run:
`keybase pgp select`

**Comment by zapu** [comment]
I've been using Keybase against fairly recent gpg2 (compiled from source) on Linux and it seemed to work. Maybe something is different on OSX. Good to hear you got it working in the end!

**Comment by BenjaminHCCarr** [comment]
CANCEL THIS... it's not respecting:
`keybase config set gpg.command /usr/local/bin/gpg1`

---

```
ls -l /usr/local/bin/gpg1
lrwxr-xr-x  1 benc  admin  35 Jul 17 13:53 /usr/local/bin/gpg1 -> ../Cellar/gnupg@1.4/1.4.21/bin/gpg1
```

---

The solution after much head banging, issue reading, and search for me was to use this:
`benc$ keybase config set gpg.command 'which gpg1'` (you need backticks.... but markdown won't escape)
As you need gpg v1 and v2 seems to always fail... on OSX `gpg` is symlinked against `gpg2`

And THEN run:
`keybase pgp select`

**Comment by BenjaminHCCarr** [comment]
Mine are current but not working:
```
gpg1 --version
gpg (GnuPG) 1.4.21
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
gpg2 --version
gpg (GnuPG) 2.1.21
libgcrypt 1.7.8
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/benc/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
keybase --version
keybase version 1.0.24-20170619144856+91a6943
```

**Comment by zapu** [comment]
So `keybase pgp select` is not working? Can you do `keybase log send` after a failed attempt? Thank you.

**Comment by maxtaco** [comment]
might be that a service restart is needed in there too btw

**Comment by BenjaminHCCarr** [comment]
```
tyr:~ benc$ keybase config set gpg.command /usr/local/Cellar/gnupg@1.4/1.4.21/bin/gpg1
tyr:~ benc$ keybase log send 
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or ENTER to send): pgp.command not being respected
Enter feedback (or ENTER to send): 
```

------------
Success! Your log ID is:

  b42c991e35574b948139e11c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20b42c991e35574b948139e11c

Thanks!
------------

**Comment by BenjaminHCCarr** [comment]
No go on service restart (won't restart)
```
tyr:~/Desktop benc$ keybase help launchd restart
NAME:
   keybase launchd - Manage launchd

USAGE:
   keybase launchd <command> [arguments...]

COMMANDS:
   install	Install a launchd service
   uninstall	Uninstall a Keybase launchd service
   list		List Keybase launchd services
   status	Status for a Keybase launchd service
   start	Start a Keybase launchd service
   stop		Stop a Keybase launchd service
   restart	Restart a Keybase launchd service
   
tyr:~/Desktop benc$ keybase launchd restart
Error parsing command line arguments: Need to specify launchd label
tyr:~/Desktop benc$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or ENTER to send): 
```

------------
Success! Your log ID is:

  5cf6d27e098b09b9ded54e1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%205cf6d27e098b09b9ded54e1c

Thanks!
------------

**Comment by zapu** [comment]
Can you try `keybase ctl restart` for service restart?

**Comment by BenjaminHCCarr** [comment]
```
tyr:~/Desktop benc$ keybase ctl restart
▶ INFO Stopping Keybase app
▶ INFO Terminated Keybase [94141]
▶ INFO Removing /Users/benc/Library/LaunchAgents/keybase.service.plist
▶ INFO Waiting for keybase.service to exit...
▶ INFO Stopped keybase.service
▶ INFO Removing /Users/benc/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Waiting for keybase.kbfs to exit...
▶ INFO Stopped keybase.kbfs
▶ INFO Trying to unmount: /keybase
▶ INFO Uninstall mount: /keybase
▶ INFO Removing /Users/benc/Library/LaunchAgents/keybase.updater.plist
▶ INFO Waiting for keybase.updater to exit...
▶ INFO Stopped keybase.updater
▶ INFO Saving /Users/benc/Library/LaunchAgents/keybase.service.plist
▶ INFO Starting keybase.service
▶ INFO Waiting for keybase.service to be loaded...
▶ ERROR stat /keybase: no such file or directory
▶ INFO Saving /Users/benc/Library/LaunchAgents/keybase.updater.plist
▶ INFO Starting keybase.updater
▶ INFO Waiting for keybase.updater to be loaded...
▶ INFO Opening /Applications/Keybase.app
▶ ERROR stat /keybase: no such file or directory
```

**Comment by zapu** [comment]
Did you have any success in running Keybase at all? Can you talk to you using chat?

**Comment by BenjaminHCCarr** [comment]
I can talk to myself yes

I can write to @cjb, but I think he's at lunch

**Comment by epicpewpew** [comment]
Sooooooo umm Close the issue or leave it open?
