### ISSUE TITLE
New large logo covers controls at https://keybase.io/verify

### ISSUE THREAD

**Issue by weswigham** [keybase/keybase-issues#298]
![logo_coverage](https://f.cloud.github.com/assets/2932786/2464324/94e45f52-af95-11e3-926b-74da01e5d48d.png)

It gets a bit in the way like that, blocking the ability to click on the buttons beneath with its own click action.

Firefox version 27.0.1

**Comment by sbriskin** [comment]
I had the same problem while NoScript extension was active. After NoScript deactivation logo changed it's size to  normal.
