### ISSUE TITLE
Getting NaCl private key out of paper key?

### ISSUE THREAD

**Issue by io4** [keybase/keybase-issues#2982]
I found that the encoding is done using a wordlist ( https://github.com/keybase/client/blob/14968b1b5d4ed1d5862305f336c61a7d2c83d7ce/go/libkb/secwords.go )

I still dont find how the private key can be encoded in *only* 13 words, where each word can hold 11 bits (log2(2048)) (143 bits for 13 words, which AFAIK is less than the key length), or how the encoding/decoding is done.

**Comment by maxtaco** [comment]
This is a great question, we stretch the key using scrypt to save typing.  I think the key has about ~100 bytes of entropy and then we stretch pretty aggressively

More details [here](https://github.com/keybase/client/blob/master/go/engine/paperkey_gen.go#L90-L104) and deeper in the call tree.

**Comment by io4** [comment]
If I understood the code properly, the logic is:
You get 13 (143/log2(2048)) random words (where first 26 bits must be version and id) and then:
* Scrypt the result converted into bytes with C: 32768, R:8, P: 1 Len: 128
* Feed to passphrase_stream which takes from 64 to 96
* Give to NaCl as a seed to generate a key

**Comment by maxtaco** [comment]
Sorry for the cursory previous reply.  I think the full answer is this, as indicated by [this comment](https://github.com/keybase/client/blob/master/go/libkb/constants.go#L451-L464)

  * Pick 13 words out of BIP39
  * Use the first 2 for a public key identifier 
  * Limit the last word only 128 of the words from BIP39, which indicate this paper key is version1.

So you wind up with 143-22-4=117 bits of _secret_ entropy in the paper key. Which is then stretched with the parameters you indicate to make an EdDSA and NaCl key.
