### ISSUE TITLE
Chrome extension recognizes docs as a user

### ISSUE THREAD

**Issue by spotlightishere** [keybase/keybase-issues#2983]
When on a page such as https://keybase.io/docs/extension and opening the Chrome extension, the following may occur:
![Extension recognizes docs as a user](https://cloud.githubusercontent.com/assets/10055256/26516572/f94dcebc-424d-11e7-9a62-b413a4625ad1.png)

As `docs` is not a real user, an exception might want to be made for it.

**Comment by strib** [comment]
cc: @shazow

**Comment by shazow** [comment]
On it, thanks!

**Comment by shazow** [comment]
Fix will be included in the next release, v1.8.11+ (feel free to close this, I don't have permission).
