### ISSUE TITLE
Feature Request: Make GitHub Page proved when GitHub account proved

### ISSUE THREAD

**Issue by outloudvi** [keybase/keybase-issues#2986]
Lots of people prove their GitHub account and their GH Page (website) together. I think it would be convnient to prove GH Page from GH account when user wants.
What I mean is that, if a user has proved his GitHub account X, the request of proving X.github.io (if the user asks) could be done without extra confirmation.

**Comment by fiatjaf** [comment]
I think this would unnecessarily complicate the scraping-and-proving code while providing no very-good feature. If your page is already hosted at https://yourname.github.io/ then anyone looking at it will know who you are on GitHub and thus be satisfied with your GitHub verification.

**Comment by outloudvi** [comment]
@fiatjaf you are right, it does make the whole thing more complicated... It's a vaild confirmation for GitHub users who would know "your-name" owns "your-name.github.io".
Thank you :)
