### ISSUE TITLE
Re-provision the Same Device?

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#2990]
I run the `Huawei Nexus 6P` with PureNexus as a ROM. I just found out there's a new version available that I want to upgrade to. The only issue is it's cross version, which means a dirty flash isn't possible and I basically need to factory reset my phone.

Once that's all done and I reinstall Keybase I'll need to set it up as a new device which will add yet another orphaned device that I still use on my graph.

For example;

![rmwifbq](https://cloud.githubusercontent.com/assets/239193/26695019/580ccd26-46d7-11e7-9f32-dc4260c662d0.png)

All of the red circles are the _same device_ which needed to be re-provisioned for some reason or another. This seems bloated and wasteful.

Is there a way I would be able to log back in on my phone without having to provision it as a new device? Considering that it's really not?

**Comment by cjb** [comment]
We recommend that you just do the revoke/provision and ignore the aesthetics.

Since the device keys are just files, it should be possible to back them up and restore them across a device wipe, and if you did so your phone would still be the same device as far as Keybase knows.

But the reason for per-device keys is that we don't think keys should be copied or moved between devices -- it's a hassle and it introduces opportunities for keys to be stolen.  So I'd go with the revokes.

**Comment by Hexstream** [comment]
I'm about to upgrade my Debian OS version and the proposed solution (to revoke the device and reprovision it under a new name, even though it is physically and logically the same device) *greatly* offends my sense of aesthetics. I *do not* want to permanently generate all that useless clutter in the graph.

So, I really just need to transfer `/home/hexstream/.config/keybase/secretkeys.hexstream.mpack` to the new install, right? This is the entirety of the device's "identity"?

**Comment by maxtaco** [comment]
This isn't our intended flow. Definitely make a paper key before you attempt this. And also retain `config.json`.

**Comment by Hexstream** [comment]
> This isn't our intended flow.

I think that's a slightly suboptimal policy.
I'll probably open an issue about this soon, as I have some ideas.

> Definitely make a paper key before you attempt this.

I have two. :) (As I needed 3 "devices" to qualify for spacedrop.)

> And also retain `config.json`.

Right, I'll be sure to migrate both `config.json` and `secretkeys.hexstream.mpack`, then. Thanks.
