### ISSUE TITLE
Facebook Verification Post Fails

### ISSUE THREAD

**Issue by tglaeser** [keybase/keybase-issues#2992]
This issue is reproducible with account https://keybase.io/tamglaeser.

While posting from keybase to fb, a new post is created in fb but the request returns with HTTP return code 403. So it seems that the public post, while created, is somehow invalid. Validation of the post from keybase to fb later fails.

Also, from the fb settings page, I can tell that _Keybase_ was added to my fb _Apps_. I see that it has access to _Public profile (required)_.

So it seems that the error comes down to the communication between the keybase client and the keybase fb app.

Please let me know if I can provide any more info. Thanks.

**Comment by oconnor663** [comment]
Do the app permissions not include "Timeline posts"? If not, that's almost certainly what's causing the error, though I thought it gave me a different error message when I tried that case...

![image](https://cloud.githubusercontent.com/assets/860932/26786971/55947a06-49d6-11e7-9a57-1b54425b3dbf.png)

**Comment by greg** [comment]
I had the same issue 2 days ago, with all permissions enabled and the post set public. Have any updates been pushed since? If so, I can retry and update with details (let me know if there's anything specific you'd like to know).

**Comment by oconnor663** [comment]
@greg yes this looks like the same error: `{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"A4cfnkQOYxN"}}`

I don't see your proof posts, but is that just because you deleted them after the failure?

**Comment by greg** [comment]
@oconnor663 yes, I deleted them after failure (you can probably see that I made several attempts with the same error 😛)

**Comment by tglaeser** [comment]
> Do the app permissions not include "Timeline posts"?

The permission include _Timeline posts_ besides _Public profile_, just not marked as required, so I thought it is not relevant in this context.

**Comment by oconnor663** [comment]
I'll spend some time investigating this in the coming week, to see if I can repro.

**Comment by tglaeser** [comment]
@oconnor663 FYI, it looks like verification now succeeds. However Keybase doesn't seem to be able to retrieve the avatar from fb.

**Comment by oconnor663** [comment]
Thanks for the follow-up. The image scraping is a known problem, which we're working on this week.

**Comment by oconnor663** [comment]
@tglaeser this should be fixed now, though unfortunately you need to make a new Facebook proof to re-enable scraping. (It's actually the login flow that does it, not the proof, but currently making a proof is the only time we send you through that flow.)

**Comment by tglaeser** [comment]
Confirming that the reported issue is resolved as well as the avatar scraping. Please close the issue. Thanks.
