### ISSUE TITLE
[Desktop] Device > Add Device should show a QR code

### ISSUE THREAD

**Issue by dabura667** [keybase/keybase-issues#2997]
Currently Mobile app wants to scan a QR code to pair with desktop, but desktop only shows a place to type in a paper key and does not display a QR code.

Expected: Desktop should show a QR code

Workaround: terminal "keybase device add" shows a QR code on the terminal.

**Comment by malgorithms** [comment]
thanks - gonna close this because our newest version has this, even in the terminal. make sure to stay updated and you'll get it soon.

**Comment by dabura667** [comment]
Thanks
