### ISSUE TITLE
Which ciphers does keybase recognise?

### ISSUE THREAD

**Issue by techmagus** [keybase/keybase-issues#3006]
Is there a list of ciphers keybase recognise?

Encountered unknown cipher: 13, it seems that keybase doesn't recognise CAMELLIA256 (and probably anything CAMELLIA).

Will switch to AES256 for now, as a workaround.

**Comment by maxtaco** [comment]
hi, the Go OpenPGP libraries don't implement Camelia. It's pretty unpopular, so we didn't bother to implement it.

**Comment by techmagus** [comment]
Ah! Alright, all good. :) Thank you for the update!
