### ISSUE TITLE
changing username

### ISSUE THREAD

**Issue by jhonatsz** [keybase/keybase-issues#3009]
i have read that you  cant change username unless you nuke your account. just a follow up question though when I delete my account keybase prompting that  you cant use your prev name anymore. Does that refer to the username before that I would like to change?

**Comment by jhonatsz** [comment]
cc: @malgorithms

**Comment by malgorithms** [comment]
if you delete your account, you're allowed to signup again with the same email address but pick a new username. What you can't do is sign up again with the old username that you deleted. in other words, usernames aren't recycled. there are too many confusing UX issues around the security to allow that.

hope this answers your Q.

**Comment by jhonatsz** [comment]
@malgorithms yea thanks!
