### ISSUE TITLE
ERROR per user key bad box coverage (error 284) when provisioning new device

### ISSUE THREAD

**Issue by staktrace** [keybase/keybase-issues#3022]
I'm trying to add a new FreeBSD device. I installed the keybase client via `pkg add keybase` which installed version 1.0.21. I ran `keybase login staktrace` and followed the steps, using another device (OS X, running keybase client v1.0.25-20170715002410+acae5b06f) to provision it.

However, the FreeBSD device fails to complete the process successfully, this is the output I get:

```
$ keybase login staktrace
▶ WARNING Unknown signature type per_user_key @uid=77fe2ebc6fe85b0d25732f2c3d3f2b19, seq=6, link=c35267c5ec49bddc87b46ae2e1741471e6c34d803c222c69102502fdf45a55ca [tags:LU=gVmM5C7LZ6Ie]

The device you are currently using needs to be provisioned.
Which one of your existing devices would you like to use
to provision this new device?

       (device list redacted)

Choose a device: 2
Type this verification code into your other device:

	(code redacted)

If you are using the command line client on your other device, run this command:

	keybase device add

It will then prompt you for the verification code above.

▶ WARNING Unknown signature type per_user_key @uid=77fe2ebc6fe85b0d25732f2c3d3f2b19, seq=6, link=c35267c5ec49bddc87b46ae2e1741471e6c34d803c222c69102502fdf45a55ca [tags:LU=AhcscFgNWgFS]
Enter a public name for this device: seldon
▶ WARNING Unknown signature type per_user_key @uid=77fe2ebc6fe85b0d25732f2c3d3f2b19, seq=6, link=c35267c5ec49bddc87b46ae2e1741471e6c34d803c222c69102502fdf45a55ca [tags:LU=6PRQGgqJogH0]
▶ ERROR per user key bad box coverage (error 284)
```

The `keybase device add` command on the OS X machine also ends with the same "bad box coverage" error.

**Comment by maxtaco** [comment]
You need a newer client, can you upgrade?

**Comment by staktrace** [comment]
That's the newest version available through `pkg`. I tried building from source but ran into a compilation error:

```
# github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit
In file included from .gopath/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit/resinit_nix.go:13:
/usr/include/resolv.h:157:14: error: array has incomplete element type 'struct sockaddr_in'
                nsaddr_list[MAXNS];     /*%< address of name server */
                           ^
/usr/include/resolv.h:156:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in
               ^
/usr/include/resolv.h:171:18: error: field has incomplete type 'struct in_addr'
                struct in_addr  addr;
                                ^
/usr/include/resolv.h:171:10: note: forward declaration of 'struct in_addr'
                struct in_addr  addr;
                       ^
/usr/include/resolv.h:196:21: error: field has incomplete type 'struct sockaddr_in'
        struct sockaddr_in      sin;
                                ^
/usr/include/resolv.h:156:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in
               ^
3 errors generated.
```

It looks like the resinit_nix.go file was added recently so this might be a legitimate compilation failure and not just an artifact of me trying to build on FreeBSD / environment issues.

**Comment by maxtaco** [comment]
Cc: @oconnor663

**Comment by oconnor663** [comment]
@staktrace could you edit `resinig_nix.go` to include all the headers from the [FreeBSD man page on `res_init`](https://www.freebsd.org/cgi/man.cgi?query=res_init)? Right now we only include `resolv.h`, but we might want all of these:

```
     #include <sys/types.h>
     #include <netinet/in.h>
     #include <arpa/nameser.h>
     #include <resolv.h>
```

**Comment by staktrace** [comment]
@oconnor663 With that change it gives me a linker error:

```
# github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/resinit
/usr/bin/ld: cannot find -lresolv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Presumably because (according to the man page) res_init is in libc on FreeBSD. I've never done go programming before, can I ifdef out the link to libresolv on FreeBSD?

**Comment by staktrace** [comment]
Simply deleting the `LDFLAGS: -lresolv` line seems to work, and the build completes successfully. Presumably that will break on other platforms.

**Comment by staktrace** [comment]
... and the local build (which identifies itself as 1.0.26) works to add the FreeBSD device without any errors (which was my original problem).

**Comment by oconnor663** [comment]
Yes, I want to say `-lresolv` was required for darwin. We could split FreeBSD out into its own implementation for that file (or split darwin out, for that matter). I do wish I had a better understanding of why this is breaking, and whether we should expect it to break on all BSD's or just FreeBSD?

**Comment by oconnor663** [comment]
woops

**Comment by staktrace** [comment]
I don't have an OpenBSD install lying around so I can't test that unfortunately. However considering that Linux doesn't seem to need libresolv either, it might be better to split darwin out into a separate implementation that links libresolv.

**Comment by oconnor663** [comment]
Ok, let me whip something up :)

**Comment by oconnor663** [comment]
@staktrace, if you build from this PR, does everything work for you?

https://github.com/keybase/client/pull/7876

**Comment by staktrace** [comment]
Not on FreeBSD, you still need the extra include files you mentioned earlier:

     #include <sys/types.h>
     #include <netinet/in.h>
     #include <arpa/nameser.h>

**Comment by oconnor663** [comment]
@staktrace I've included them now, could you take another look.

**Comment by staktrace** [comment]
@oconnor663 Yup, builds now. Thanks!

**Comment by oconnor663** [comment]
(automatic close was incorrect)

**Comment by oconnor663** [comment]
@staktrace the build from master should have this fix now. Can you confirm?

**Comment by staktrace** [comment]
@oconnor663 Confirmed master builds and works as expected. Thanks!
