### ISSUE TITLE
"A previous version of Dokan Library is already installed." on update.

### ISSUE THREAD

**Issue by rendall** [keybase/keybase-issues#3030]
Keybase setup (after update) stops with a dialog box with this message:

"A previous version of Dokan Library 1.0.4.84 (x64) is already installed. Please uninstall the existing version first, reboot the system and start the setup again."

This is Windows 10.  

I think the expected behavior would be that the Keybase update uninstalls or updates this library.

**Comment by maxtaco** [comment]
@zanderz please take a look.

**Comment by zanderz** [comment]
@rendall Can you do a `keybase log send` at the Keybase Shell so we can see the installer logs? And/or do you know what version you upgraded from? Thanks.

**Comment by rendall** [comment]
Done!  Let me know if you need more info.  Happy to help.

**Comment by zanderz** [comment]
log ad280d5cebc6fc93d22a0c1c

**Comment by zanderz** [comment]
@rendall It looks like the updater thought a reboot was pending for several hours, in which case it displays the same upgrade prompt and re-launches the installer. I'm attempting to repro your case, but have you rebooted?

**Comment by zQueal** [comment]
I'm almost positive that I also ran into this issue before and it was the result of some type of Windows update which ensured Windows compatibility with a code signing key--or something to that effect.

I can't seem to find any threads I opened from it, but I'll keep looking and update you if I find the Windows Update I had to install to fix the issue.

**Comment by rendall** [comment]
I have not yet rebooted.  I was working on a thing, but I'm just about at
its end, so I can reboot it now.

I should say that after I started this issue, but before I sent the keybase
log, I did find and uninstall the Dokan library.  When keybase prompted me
again, I gave it the go-ahead, but it failed with a different error, the
error you're seeing.

I'll reboot now and send you the log again.

**Comment by zanderz** [comment]
You are saying that you uninstalled Dokan, then did Keybase update again? All the logs show Dokan already installed. Is there a chance that some other software has installed a copy of it?

This second log after rebooting - was there another update/installation attempt between rebooting and sending the log?

Basically, the dokan package thinks it is already installed if the file %windir%\system32\dokan1.sys is present. If you uninstall Dokan, then reboot, and find that file is still there, then there is some corruption in the Dokan package state. Is this the case?

**Comment by rendall** [comment]
I've now sent the second log.  I suppose it's *possible* that another
program installed Dokan?

My current version is now 1.0.26-20170724103609+b095a79 .  I ran "upd
check" and it appears to be up to date?  Hard to tell :)

**Comment by zanderz** [comment]
The updater log shows that the server is responding with the newer version, 1.0.27-20170802164224+83e6363, but it has stopped trying to install it and the log does not show why.

The log also shows that Dokan still thinks it needs to be rebooted.

Again, If you uninstall Dokan, then reboot, is `%windir%\system32\dokan1.sys` still present?

**Comment by rendall** [comment]
I'll check now.  Hold on.

**Comment by rendall** [comment]
%windir%\system32\dokan1.sys is not there.  This is after a reboot.

**Comment by rendall** [comment]
Well!  A sudden prompt to install the update!  Good news!
Then:
"A digitally signed driver is required."
Dokan Driver
Dokan Project
Windows blocked the installation of a digitally unsigned driver.  Uninstall
the program or device that uses the driver and check the publisher's
website for a digitally signed version of the driver.  [CLOSE]

Sending log shortly.

**Comment by rendall** [comment]
Interestingly enough, Keybase gave me a "successful install" message, and
then prompted for a reboot, which I just did.

**Comment by darknessgp** [comment]
Here's what I did that seems to have worked after getting the "A digitally signed driver is required." error... 

1. Uninstall Dokan Library
2. restart
3. go install latest x64 from dokan GitHub (https://github.com/dokan-dev/dokany/releases)
4. restart
5. uninstall Dokan Library
6. restart
7. run "upd check"

For some reason getting the dokan from GitHub on there first seems to cause Windows to accept the updated installer... Don't know why, but it worked for me.

**Comment by zanderz** [comment]
Sorry for the unsigned driver problems. The release that went out yesterday contains correctly signed ones.

**Comment by rendall** [comment]
Ok.  I followed @darknessgp instructions precisely and then sent another log.  From my end it appears that all is well.

Since I submitted this as a bug report and not a support ticket, I'll leave it up to you when to close it.  Happy to continue to help, if you need.  You can also let me know if you want me to close it.

Thanks!

**Comment by zanderz** [comment]
The drivers in current updates should be signed properly, getting them from Dokany should no longer be necessary. Please re-open if there are still problems.
