### ISSUE TITLE
So many issues I can't think of a proper title

### ISSUE THREAD

**Issue by exentio** [keybase/keybase-issues#3034]
Without dwelling too much:
1. The linux version of Keybase (but apparently it's the same for every operating system) launches on startup, and you have no control about it in the settings.  
I'm dead serious when I say that it scares me, because my `.config/openbox/autostart` file doesn't mention Keybase in any part of it, and there's no trace of it in .xsession.  
I had to search on the internet to find that it creates a `.desktop` file, and if you try to delete it, it's recreated by the program itself; instead you should uncomment the last line, which means you need to have an useless folder and an useless file in your `.config` just for the privilege of disabling Keybase's autostart.  
Please at least add a toggle for this.  
2. I don't need the chatting and filesystem function, but that's fine, some people may like it. 
 What I don't like is that I have no choice about leaving Keybase open and in my tray just because I may need the FS or the chat.  
Please, add a toggle for this, too.  
3. If I want to close the tray thing, I can't just right-click on it and close it by a menu, like every normal program; instead, I have to go to the bottom right of my screen, double click on the tray icon, go on the top right, click on the menu and close it. If you move the window, when it closes and you reopen it, it's again on the top.  
I'm getting bored, please fix this too.  
4. I don't know why, but you thought that if someone want the privilege to have its own profile pic, the best way to do it is installing your Electron app on a PC and creating a folder using your own file system. Of course, the CLI version can't do all this fancy stuff.  
Great idea, isn't it? No, it isn't. Please add an uploader to your website.  
5. The Android app keeps refreshing the status of every single thing linked to the account. 
 It's unnecessary, please fix this.  
6. I'd like you to think about this:  
```
ex@Inaba-Himeko ~> ps aux | grep keybase
ex        7336  3.0  0.2 697572 44524 pts/7    Sl   12:16   0:00 keybase -d --log-file=/home/ex/.cache/keybase/keybase.service.log service --auto-forked
ex        7337  0.9  0.2 695592 39688 pts/7    Sl   12:16   0:00 kbfsfuse -debug -log-to-file /keybase
ex        7338  4.6  0.6 1438296 108224 pts/7  Sl   12:16   0:00 /opt/keybase/Keybase
ex        7365  0.0  0.1 343464 31288 pts/7    S    12:16   0:00 /opt/keybase/Keybase --type=zygote --no-sandbox
ex        7385  4.3  0.5 1090956 96928 pts/7   Sl   12:16   0:00 /opt/keybase/Keybase --type=renderer --no-sandbox --primordial-pipe-token=4A9A656E54E0E171A89F4ED22A8FC2DF --lang=en-US --app-path=/opt/keybase/resources/app --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=4A9A656E54E0E171A89F4ED22A8FC2DF --renderer-client-id=3 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
ex        7387 12.5  0.7 1125888 118480 pts/7  Sl   12:16   0:01 /opt/keybase/Keybase --type=renderer --no-sandbox --primordial-pipe-token=61A19FBF6A70024623989956DA45D1B4 --lang=en-US --app-path=/opt/keybase/resources/app --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --service-request-channel-token=61A19FBF6A70024623989956DA45D1B4 --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
ex        7480  0.0  0.0  10792  2196 pts/7    S+   12:16   0:00 grep --color=auto keybase
```
Do you actually think it's normal? Yes? Here's a comparison:
```
ex@Inaba-Himeko ~> ps aux | grep telegram-desktop
ex        2584  2.2  0.8 1164588 131252 ?      Sl   11:18   1:16 telegram-desktop
ex        7548  0.0  0.0  10792  2180 pts/6    S+   12:17   0:00 grep --color=auto telegram-desktop
ex@Inaba-Himeko ~> ps aux | grep google-chrome-beta
ex        2609 14.0  2.1 1538452 344308 ?      Sl   11:19   8:03 /opt/google/chrome-beta/google-chrome-beta
ex        7602  0.0  0.0  10792  2260 pts/6    S+   12:17   0:00 grep --color=auto google-chrome-beta
ex@Inaba-Himeko ~> ps aux | grep cadence
ex        2224  0.2  0.3 313056 49972 ?        Sl   11:17   0:07 /usr/bin/python3 /usr/share/cadence/src/cadence.py --minimized
ex        7643  0.0  0.0  10792  2200 pts/6    S+   12:17   0:00 grep --color=auto cadence
ex@Inaba-Himeko ~> ps aux | grep pulseaudio
ex        2558  2.3  0.5 1498708 93264 ?       S<Ll 11:18   1:21 pulseaudio --start
ex        7684  0.0  0.0  10792  2240 pts/6    S    12:17   0:00 grep --color=auto pulseaudio
ex@Inaba-Himeko ~> ps aux | grep mpd
ex        2276  1.5  0.6 931848 112532 ?       SLsl 11:17   0:55 mpd
ex        7707  0.0  0.0  10792  2288 pts/6    S+   12:17   0:00 grep --color=auto mpd
ex@Inaba-Himeko ~> ps aux | grep deluge
ex        2231  0.8  0.4 946812 79520 ?        Sl   11:17   0:29 /usr/bin/python2 /usr/bin/deluge
ex        7734  0.0  0.0  10792  2196 pts/6    S+   12:17   0:00 grep --color=auto deluge
```

I don't know how you could fix this, but if you stop pretending that JavaScript can have good performance and start making native apps you may actually solve some of this.  
Please fix something.

**Comment by fiatjaf** [comment]
No one is pretending that JavaScript can have a good performance. No one has asserted Keybase was a lean ultra-optmized app. Your tone is very harsh. This is free software.

I'm not a Keybase developer or in anyway related to the Keybase team, but I'm very upset with your agressive commentaries.

**Comment by exentio** [comment]
I didn't really want to sound harsh, but these are stupid issues caused by horrible design choices, so I'm really pissed off because stuff like this usually happens with Electron apps: people started putting JS everywhere because it's easy and frameworks, disgracefully, allow you to, then they stop thinking, they do whatever comes in their mind, and start imposing stupid stuff to users. You don't need to say that your app has good performances and is optimized, that should the first thing you should do. I'm not pretending to have a super fast application, but I'm sure that something like Keybase shouldn't use the 2.3% of my 16 gigabytes of RAM, especially when you consider that Chrome itself uses the 2.1% with lots of open tabs. And the fact that this is free software is not an excuse.  
I didn't want to sound *that* aggressive, but apparently I did, because I'm as upset as you with the current state of software design and developing.

**Comment by kapolos** [comment]
@exentio Channel your anger in your coding efforts and create something you (and others) deem better. And the beauty of open source is that you don't have to start from scratch, you can adopt other people's work and mold it in your own creation. 

Rule of thumb:

* Pointing out issues -> great! 
* Ranting -> disrespectful to other people's efforts. That's why @fiatjaf got annoyed with your tone.

**Comment by exentio** [comment]
A rant is not necessarily disrespectful, if people rants about what you did, is because your work doesn't just have issues, but has also something stupid that makes people upset, something that you did out of free will. People can make mistakes, but there's a big difference between mistakes and pointless choices made just because "everyone does this too". Honestly, do you think that having to install an app just to get access to a filesystem and upload a profile picture, and denying you to toggle some stuff can be considered as just issues?  
People should stop getting triggered by rants, and think more about why does people rant

**Comment by kapolos** [comment]
Well, you're the one who got "triggered" (what an ugly word) and started ranting, so it's funny that you don't like counterpoints to your rant :)

As I said, the beauty of ope source is that you don't have to accept, approve and adapt other people's choices. You fork and make it just as you find perfect (which may or may not coincide with other people's view of what perfect is like).

**Comment by exentio** [comment]
I can't really see a counterpoint to my rant, whatever you mean with "counterpoint". I could just do a fork that works fine, it will probably have issues, and it's normal, but I'd at least give to the user the right of choice. The reason why I won't do it is because it's not something I use on a daily basis, probably I'm not the only one that doesn't need Keybase everyday, but that's the reason why they should avoid **forcing the user** (this is the key of my rant) to use their app just for basic stuff like setting a profile picture and uploading stuff in the filesystem, especially because they also made a C++ CLI version without these features

**Comment by exentio** [comment]
Ok, this is getting ridiculous.  
I received an email that said I received an encrypted message. I went to the keybase website, but I couldn't find the inbox from the home page. Fine.  
I go on my profile, but I still can't find it. I decide, then, to try on the senders' page, and I see the "Keybase Chat" button.  
I click on it, and it says I have to install an extension. Seriously? Why do I have to install an extension to use a chat?  
But it doesn't end here. I say "ok whatever, I just wanna know what they want from me" and install the extension. I go back to the page, I click to the button, and the extension asks me to install the Keybase app on my PC. I have to install an application just to see a chat message.  

I just don't know what to say. Please tell me this is just a joke.  

I remove the extension, because I uninstalled Keybase literally after I uploaded the profile picture, and then I take my phone because I still have the app.  
I click on the chat icon, tap on the sender, and then I see "secure connection established". Nothing else. And on the top there still was a badge telling me I have a message to read.  
I go back to the menu and open the chat another time, and so on for a few minutes, until the message appears. But this is fine, it's just a bug; instead, the stuff I said before is NOT fine.

**Comment by fiatjaf** [comment]
The chat is encrypted. The encryption key lives in your devices. There's no way to show the chat message without installing the app in one of your devices.

**Comment by fiatjaf** [comment]
Now I can agree with one point: I would rather just use the CLI app over the GUI. It is really slow and unnecessary.

**Comment by oconnor663** [comment]
Just answering a question from the top: If you want to disable autostart, read the comments in `~/.config/autostart/keybase_autostart.desktop`.

**Comment by exentio** [comment]
@fiatjaf Telegram uses encryption too, and works from the browser; Keybase keeps both keys on their server. What's the point?  
@oconnor663 as I said, it's not normal that I can't toggle the autostart from the app, and that I have a file to disable autostart, the standard is that you edit a file to **enable** it

**Comment by fiatjaf** [comment]
@exentio I believe you must understand the technologies underlying each different product before making these comparisons. You can do "encryption" in a lot of different ways, and that word is used with multiple different meanings. Telegram's encryption is totally different from Keybase's encryption.

It's also not "normal" that you have to enable autostart on an app. There are many examples of programs you haven't criticized that have autostart enabled from the time you install them. I believe you do have some of them running in your computer. Dropbox is an example you will recognize, Skype is another, not to mention many other programs that run as daemons and you haven't noticed.

**Comment by exentio** [comment]
While the technologies are different, that doesn't mean that you can't do the same with Keybase. If it's hard to implement, at least they could make it more obvious that you need the app, and give me the option to download the encrypted message, so I can decrypt it by myself.  
And, I don't use Dropbox, Skype doesn't autostart, the only stuff that autostarts in my PC are the ones I told the init system and the WM to launch. If you're talking about Windows then you got a point, but it should be clear that I'm talking about Linux

**Comment by fiatjaf** [comment]
If you install Apache2 from your package manager I bet it will be set to autostart by default. That happens in Ubuntu. It happens with dozens of other daemons when you install them with `apt` from the default repositories.

If you had created an issue "Let me download the message so I can decrypt it myself instead of running the app" that would be nicer. I guess there would be more chance that people would listen to you than what you've done here, writing hundreds of complaint lines with aggressive tone.

**Comment by exentio** [comment]
You're talking about a package manager that automatically installs "suggested" packages without asking the user if he wants to, this doesn't surprise me. I use Artix Linux and this problem doesn't exist, and neither does on a whole bunch of other distros.  

The reason why I didn't create just that issue is because I found 8 big problems, mostly caused by horrible design choices. I also said I don't want to sound aggressive but I'm honestly pissed off, if you get offended by annoyed people it's not my problem.  
I wish I didn't have these problems, but they exist, and while you're telling me that you find me rude, these problems still haven't been solved. You want my opinion? They like how they made their stuff and don't want to change anything.  
Tthe only reason why I'm still here is because there isn't a worth alternative to Keybase.

**Comment by fiatjaf** [comment]
I believe everybody would be happier if you left.
