### ISSUE TITLE
Change username or re-activate deleted account

### ISSUE THREAD

**Issue by walialu** [keybase/keybase-issues#3038]
I deleted an account with the username `walialu` and want my current username `emkae` to be either changed to `walialu`, the previously deleted account restored, or the previously deleted account"s name to be selectable again (I tried registering with the account name `walialu` again, and it does't work, because it was previously registered).

When I try to register with my previously deleted username, the page says this:

> username walialu is unavailable. Pick again or login if that's you.

When I try to login it says this:

> Error: Server failure: user deleted

I would like to have this username (again) :)

Can you help me with this, please?

**Comment by malgorithms** [comment]
sorry - this isn't something that we have the capacity to do at Keybase. deleted accounts can't be recovered and the usernames aren't freed up, for security reasons. 

wish I had a better answer!
