### ISSUE TITLE
Can't reset account after remove single device

### ISSUE THREAD

**Issue by haskel** [keybase/keybase-issues#3047]
Hi
I created account on laptop and then remove my single attached device, because can not found how to rename device.
As result, I can't login on my laptop app with error message "has been revoked, please log in again"
And can't login to android app with error message "Cannot add a new device when all existing devices are revoked. Reset your account on keybase.io"
But, I can't find how to reset my account on keybase.io, I rummaged the whole site, assure you
My account https://keybase.io/haskel

**Comment by fiatjaf** [comment]
If you've lost all your devices there's no way to prove you are you, but from the website you can reset your password (and your private key, by the way) and start adding people, chat groups and devices from zero, with the new private key.

**Comment by haskel** [comment]
Thx for your help @fiatjaf 
But I can't find how to reset my private key, there are no options to do it on web site, or using console.
I reset my password (private key was reset?) and after that tried to login in console, this error appears:
▶ ERROR Cannot add a new device when all existing devices are revoked. Reset your account on keybase.io.
I don't understand how to start adding devices from zero with the new private key... because I don't understand how to get new private key

**Comment by fiatjaf** [comment]
I've just gone to the website and used your name `haskel` in the "Recover account" feature (in the login window) and saw a message saying that a recovery email was sent.

**Comment by fiatjaf** [comment]
Oh, just realized that is the procedure for when you don't have access to your password also.
If you're logged to the website here's the button: https://screenshots.firefox.com/caWkTvUZphvjh3w4/keybase.io

**Comment by haskel** [comment]
@fiatjaf  
Yes, I know my password and can log in to website. Also recovering of account works perfectly and I can change password using email. But it does not solve the problem with the keys.
The option you show on screenshot is unavailable for me. How it looks on my side:
https://d26dzxoao6i3hh.cloudfront.net/items/1i0D242s3X1W0u2V1u3B/Image%202017-09-28%20at%202.49.00%20%D0%94%D0%9F.png?v=2b8e877f
I think, that my previous key binded to me but I can't delete this link using website or console
Also, I can't add new pgp key, this error appears when I try to sign public key: 
Code: 908
Name: KEY_NEED_REVOKE
Description: You need to delete your active key before uploading a new one
.
it seems to me that these problems have the same reason

**Comment by fiatjaf** [comment]
Ok, now I believe there is indeed a bug somewhere. I would bet it is a simple bug on the web interface, as it should be showing you the button to reset account, but it isn't.

I don't know if this is the same as "resetting", but you could try to call `https://keybase.io/docs/api/1.0/call/key/revoke` manually and see what happens if you're feeling super nerd.

**Comment by maxtaco** [comment]
@haskel  I reset your account. Seems like you revoked your last key back in June, and we've since fixed a bug that if you revoke your last key, your account is auto-reset.

**Comment by haskel** [comment]
@maxtaco , @fiatjaf very grateful!
It's work, thx

**Comment by FrUh** [comment]
Hi I have the same issue, could you you please also reset my account? https://keybase.io/fruh
