### ISSUE TITLE
You are not a member of this team after reset

### ISSUE THREAD

**Issue by der-Daniel** [keybase/keybase-issues#3049]
Hi,

after resetting my account, I was excluded from the teams. Since the names are unique, I can not create a team with the same name.
Can I somehow get access back to the team?

For Frodo.

**Comment by malgorithms** [comment]
if there are other admins/owners of the team, they can easily add you back in. As mentioned in the teams blog post, if you reset your account (or delete it) and are the last admin of a team, you lose control of it permanently. There's nothing keybase can do to steal it, so there's nothing it can do to reassign it. In that case you'll need to pick a new team name and start fresh.

**Comment by der-Daniel** [comment]
Dammit
