### ISSUE TITLE
Cannot Delete Channel in Team

### ISSUE THREAD

**Issue by maximvid** [keybase/keybase-issues#3052]
Hello, I cannot delete a channel I made in a team. I accidentally made the channel in question and the only thing I can do is leave it. I checked on the website and looked at previous issues and could not find a way to delete said channel. There is no way in the console to delete a channel, you can only delete a team or subteam.

**Comment by mlsteele** [comment]
Looks like there is `keybase chat delete-channel`. Is your client up to date?

**Comment by maximvid** [comment]
Yes, it is. I downloaded keybase half an hour ago using the latest installer on the site (windows version).
![image](https://user-images.githubusercontent.com/32107590/30609642-a9651f76-9d84-11e7-8d4d-94ba9678e242.png)

**Comment by mlsteele** [comment]
Ah you're right. `delete-channel` was just added yesterday and will be in the upcoming release.

**Comment by maximvid** [comment]
Ok, thank you!
