### ISSUE TITLE
paper key UX is too complicated to be practically usable

### ISSUE THREAD

**Issue by dch** [keybase/keybase-issues#3060]
```
▶ ERROR Bad passphrase: Not enough words entered for a paper key.  Please try again..
```

There's no information in the error message about how many words are expected, nor what constitutes an acceptable word --  I didn't find this on the website either, but it seems to be 13 according to the code.

I've spent the last 15 minutes unsuccessfully trying to find a set of words (i.e. actual words I could remember or write down for somebody else later to use) that satisfy your pedantic software.

Can you *please* consider making it usable by somebody who doesn't have access to whatever word list is embedded, and just allow (say) 13-20 words?

**Comment by skwerlman** [comment]
You should be able to generate a paperkey using the command `keybase paperkey`. Is this not working?

**Comment by dch** [comment]
for example at present I can't use:

slumlord, bellboy, watertight, immolated, spearmint, supercargo, tabletop, grapejuice, boardroom, skyscraper, practitioner, exculpatory, imaginary, harbourmaster, the, unstoppable, storm, meets, the, immovable, the, norse, gods, rise, yell, difficult, willing, epic, mandatory, passphrase, failure, requires, anticipatory, foreknowledge, recollection, through, justification, of, needless, and, mindless.

**Comment by dch** [comment]
@skwerlman thanks, but this mode doesn't work if you are in `keybase passphrase recover` mode.

**Comment by dch** [comment]
> ERROR Login required

these words are also "invalid":

Dae0n Xain9 av0Ae wieV2 eiJ8o Xeiy6 AeN6v Ex4oo Vei3A Uov7w Ooz3a agh6J caeG0 ahG2e Aec3y Si7oh Cu4Ye fo7To Afoh2 Ou9ei

I think it's clear the command should provide some indication of what an acceptable passphrase is.

**Comment by dch** [comment]
as are these:

auW2sohtia uuthaeQu8n ahTh0so7Ah Aigh0jebee eimoh1Jah2 wieth1eiX9 ohWeida4xo coh3joov7E EeWai8sush ieR1luaThi faiqu1ahGo yaeDoh2Wae Eed9wooghi eil2hoxaeP AiGaiDa3ae Aeyio9quah Shoyae9eeh ujaug9ao3H MohK1Iez7n zae5ooK4th

I'll stop here, I think my point has been made

**Comment by skwerlman** [comment]
If you're trying to recover your passphrase, then it's probably asking you for an _existing_ paperkey, not for you to make one yourself.

**Comment by dch** [comment]
erm didnt mean to close this.

**Comment by maxtaco** [comment]
You are at a prompt where you need to enter your paper key, not create paper key.  Keybase software creates paper keys with words chose from BIP-39

**Comment by dch** [comment]
thanks for the clarification @maxtaco perhaps that prompt can be improved with:

```
go/libkb/passphrase_helper.go:  arg.Prompt = fmt.Sprintf("Please enter an existing paper key for %s", username)
```
