### ISSUE TITLE
Keybase needs IRC-style action commands (/me)

### ISSUE THREAD

**Issue by DeepMac** [keybase/keybase-issues#3061]
Keybase chat badly needs "/me" or the equivalent in chats. Currently, while there is Emoji support (for Bob's sake), there is no way to do things like this:

joe: Good morning everyone.
bob: Hey
Alice: 'sup
frank waves

Should be a pretty trivial add.

**Comment by hardyoyo** [comment]
+1 plz

**Comment by ximinez** [comment]
It's never trivial. ;)

**Comment by samurai** [comment]
Is a chat client without "/me" really a chat client? 

+1 on this request

**Comment by DeepMac** [comment]
As of 2019-03-08 the Keybase client appears to have /me commands that do IRC-style emotes, so closing this request as fulfilled.

(1.5 years later.)
