### ISSUE TITLE
Is it possible to add a new first device

### ISSUE THREAD

**Issue by riverrun** [keybase/keybase-issues#3063]
I set up keybase a couple of days ago, but yesterday I installed a new distro (now using Ubuntu Linux), and so my computer is no longer recognized as the same device, and I cannot login to the command line app. I have the gpg keys -- and all the other 'proofs' (I can access my github and twitter accounts, for example).

Is it possible to add a new 'first' device, perhaps using the web interface, or do I need to start again from scratch?

**Comment by junderw** [comment]
Import the gpg keys, then run keybase login via terminal to provision using gpg.

**Comment by riverrun** [comment]
Thanks for your swift reply.

Could you tell me the command for importing the gpg keys?

**Comment by riverrun** [comment]
So when I try to login, I get this message:

"The device you are currently using needs to be provisioned.
Which one of your existing devices would you like to use
to provision this new device?

	1. [computer]	riverrun

Choose a device:"

The computer in the message is my old device, so I can't login.

I have the gpg keys on my current device. Is there a command to associate them with keybase?

**Comment by riverrun** [comment]
So I decided to reset my account as that seemed to be the only available option.

After resetting my account, I get this error when trying to send my gpg key:

Error in your post
-------------------

Code: 908
Name: KEY_NEED_REVOKE
Description: You need to delete your active key before uploading a new one

Any ideas?

**Comment by junderw** [comment]
Resetting your account only resets your device keys iirc. Your PGP keys in your local client should be intact.

**Comment by riverrun** [comment]
Closing this issue.

I managed to 'solve' it by running `keybase pgp gen` to generate a new key.
