### ISSUE TITLE
Can't create keybase team.

### ISSUE THREAD

**Issue by martinssipenko** [keybase/keybase-issues#3071]
Hi,

I've been trying to create keybase team using the following command and I get this error. The error itself is quite clear. However, I used to own this user (`kasko`) but I have deleted it and I was hoping I'll be able to create a team with such name.

Any help would be much appreciated.

```sh
keybase team create kasko
▶ ERROR there is a keybase user called `kasko` and we are currently not allowing team/user name conflicts. (code 2672)
```

**Comment by maxtaco** [comment]
Ah, we're not allowing that right now!  We probably won't in the future either. Sorry.

**Comment by martinssipenko** [comment]
:(
