### ISSUE TITLE
Reclaim dangling team names

### ISSUE THREAD

**Issue by dhruvio** [keybase/keybase-issues#3073]
I created a team with my keybase account, then reset my keys. I was the only member of the team, and, consequently, the only owner. I understand this means the team is "lost." However, I have noticed that `keybase team list-memberships` still shows me as the team's owner. Also, if I request access to the team, I get an email indicating the request. However, I am not able to add myself back to the team, as I reset the keys of my keybase account. This indicates that membership is done at the key-level.

If I don't have access to my old private key, that means no one will ever be able to use this team name. Would it be worthwhile to implement the following feature in keybase's back-end to help users/the community to reclaim lost team names?

> Recycle team names that are "dangling." Specifically, if someone creates a team, then resets their account, and the team has no other members or owners, you could deem that team as "deleted", and recycle its name for re-use. Perhaps it would be more secure if only the original owner could reclaim the name, as it would be necessary to know that the new owner is/was the legitimate owner of the key that created the team in the first place (before the key was deleted from the keybase account during the reset process).

**Comment by miclaus** [comment]
I have a similar issue, where I just joined Keybase, created two teams in the hype, after which I revoked my device. Unlike dhruvio, `keybase team list-memberships` doesn't show me as owner and I can also not reclaim the teams I've previously created.

**Comment by dhruvio** [comment]
Thank you!

**Comment by dhruvio** [comment]
Any news on this?

**Comment by maxtaco** [comment]
It is not currently on our road map. It is a lot of work. At some point we
will get along to it.

**Comment by miclaus** [comment]
@maxtaco in the meantime, could you at least consider disabling the
possibility of the last owner removing him/herself from the team ? –
this could be done in the UI and CLI and would also prevent #3088

**Comment by maxtaco** [comment]
It is already prevented.  But not in the case of a reset.  There is nothing
that can possibly done in that case.

**Comment by miclaus** [comment]
hmm, okay.. bummer.

**Comment by dhruvio** [comment]
Thanks, @maxtaco for the response. Appreciate the work you guys are doing, and Keybase is great.

**Comment by bahace** [comment]
Just checking for a status update on this one. I see 5 months ago it wasn’t on the roadmap yet. Is it on the roadmap now?

**Comment by dhruvio** [comment]
Any update?

**Comment by dhruvio** [comment]
Closing this due to non-activity. Seems unlikely this will be addressed post-Zoom acquisition too.
