### ISSUE TITLE
kbfs fails

### ISSUE THREAD

**Issue by Asternitix** [keybase/keybase-issues#3086]
Username: asternitix
Logged in: yes

Session: no session
is valid: yes
keys: unlocked

Key status:
stream: not cached
secret: stored
dev sig: cached
dev enc: cached
paper sig: not cached
paper enc: not cached
prompt: show
tsec: not cached

KBFS:
status: not running
version: 1.0.2-20171010160025+f71e33c2
log: /home/asternitx/.cache/keybase/keybase.kbfs.log

Service:
status: running
version: 1.0.34-20171010160025+8543c4734
log: /home/asternitx/.cache/keybase/keybase.service.log

Updater:
log: /home/asternitx/.cache/keybase/keybase.updater.log

Platform Information:
OS: linux
OS vers: Linux 3.8.11 x86_64-Debian GNU/Linux 9.2 (stretch)
Runtime: go1.9
Arch: amd64

Client:
version: 1.0.34-20171010160025+8543c4734

Desktop app:
status: not running
version:
log: /home/asternitx/.cache/keybase/Keybase.app.log

Config path: /home/asternitx/.config/keybase/config.json
Default user: asternitix
Other users:

command-line client:
keybase status [pid: 14189, version: 1.0.34-20171010160025+8543c4734]

▶ ERROR GetConversationForCLILocal error: error unboxing chat message: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with run_keybase command.

▶ ERROR GetConversationForCLILocal error: error unboxing chat message: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with run_keybase command.

▶ ERROR Unable to find conversation.
When considering aevan as a username or a list of usernames, received error: EOF.
When considering aevan as a team name, received error: Team "aevan" does not exist.

c93a4270dc0968d47ca2571c

**Comment by maxtaco** [comment]
▶ ERROR GetConversationForCLILocal error: error unboxing chat message:
Keybase services aren't running - KBFS client not found. On Linux you need
to start them after an update with run_keybase command.

**Comment by Asternitix** [comment]
after run_keybase the error persists.

**Comment by Asternitix** [comment]
▶ ERROR Unable to find conversation.
When considering aevan as a username or a list of usernames, received error: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with `run_keybase` command..
When considering aevan as a team name, received error: Team "aevan" does not exist

**Comment by maxtaco** [comment]
```40278 2017-10-12T16:57:10.604366-07:00 ▶ [DEBU kbfs start.go:35] 084 Mounting: "/keybase"
40279 2017-10-12T16:57:10.604393-07:00 ▶ [DEBU kbfs start.go:38] 085 Starting to mount the filesystem
40280 2017/10/12 16:57:10 mount helper error: fusermount: mountpoint is not empty
40281 2017/10/12 16:57:10 mount helper error: fusermount: if you are sure this is safe, use the 'no```

**Comment by maxtaco** [comment]
What is in `/keybase`?

**Comment by maxtaco** [comment]
seems like that directory is non-empty and therefore KBFS can't start up

**Comment by Asternitix** [comment]
ls /keybase/private/asternitix
alpha  beta  kbsecret

**Comment by Asternitix** [comment]
ls /keybase
private

**Comment by maxtaco** [comment]
You seem to be in an unexpected state.  Maybe one of our Linux specialists
can help out. Cc @oconnor663

**Comment by Asternitix** [comment]
the keybase update fixed the ui problem but the kbfs problem is still there

**Comment by Asternitix** [comment]
▶ ERROR Unable to find conversation.
When considering aevan as a username or a list of usernames, received error: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with `run_keybase` command..
When considering aevan as a team name, received error: Team "aevan" does not exist.

**Comment by Asternitix** [comment]
Username:      asternitix
Logged in:     yes

Device:
    name:      beta11
    ID:        2ac50cd30ed39ca4bec34a192190d518
    status:    active

Session:       no session
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    not cached
    secret:    stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached

KBFS:
    status:    not running
    version:   1.0.2-20171012160058+6cbbf247
    log:       /home/asternitx/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.34-20171012160058+c282fb227
    log:       /home/asternitx/.cache/keybase/keybase.service.log

Updater:
    log:       /home/asternitx/.cache/keybase/keybase.updater.log

Platform Information:
    OS:        linux
    OS vers:   Linux 3.8.11 x86_64-Debian GNU/Linux 9.2 (stretch)
    Runtime:   go1.9
    Arch:      amd64

Client:
    version:   1.0.34-20171012160058+c282fb227

Desktop app:
    status:    running
    version:   1.0.34-20171012160058+c282fb227
    log:       /home/asternitx/.cache/keybase/Keybase.app.log

Config path:   /home/asternitx/.config/keybase/config.json
Default user:  asternitix
Other users:   

command-line client:
    keybase status [pid: 25240, version: 1.0.34-20171012160058+c282fb227]

desktop:
    /opt/keybase/Keybase --type=renderer --no-sandbox --primordial-pipe-token=BEE5374ED8638C722DF85D0718071CC9 --lang=en-US --app-path=/opt/keybase/resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=1 --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=BEE5374ED8638C722DF85D0718071CC9 --renderer-client-id=5 --shared-files=v8_natives_data:100,v8_snapshot_data:101 [pid: 19372, version: 1.0.34-20171012160058+c282fb227, description: Main Renderer]

desktop helper:
    /opt/keybase/Keybase --type=renderer --no-sandbox --primordial-pipe-token=C7A1186E88DE1CD90A6614BB46EC0610 --lang=en-US --app-path=/opt/keybase/resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=1 --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=C7A1186E88DE1CD90A6614BB46EC0610 --renderer-client-id=3 --shared-files=v8_natives_data:100,v8_snapshot_data:101 [pid: 19369, version: 1.0.34-20171012160058+c282fb227, description: Menubar]

**Comment by maxtaco** [comment]
`keybase login`

**Comment by maxtaco** [comment]
Scratch that, you are logged in.

Cc: @jzila and @strib, this seems like a KBFS bug.

**Comment by strib** [comment]
If your local `/keybase` is non-empty, KBFS won't start.  It seems you may have accidentally created a directory structure under `/keybase` while you were playing around.  Maybe you did something like `mkdir -p /keybase/private/asternitix` and then made a few files in there?  If `/keybase` were a real KBFS mount, there would also be `/keybase/public` and `/keybase/team`.

You can double check with the `mount` command to see if anything is mounted at `/keybase`. If not, and if your current `/keybase` doesn't contain anything you care about, just do `rm -rf /keybase` and then re-run `run_keybase`.

**Comment by jzila** [comment]
If that's real KBFS data in `/keybase/private/asternitix`, then it's possible there's another KBFS instance running:
```
$ ps aux | grep kbfsfuse
```

Alternatively, it's possible that you accidentally copied in data to your actual filesystem, preventing KBFS from mounting.

However, none of this explains why chat is failing: a mount failure shouldn't stop KBFS from starting, and performing its role in KBFS services.

**Comment by jzila** [comment]
Ah, race with strib. @Asternitix: you can try strib's instructions to `rm -rf /keybase` and then `run_keybase` again.

**Comment by Asternitix** [comment]
the keybase ui is slow as molasses

**Comment by Asternitix** [comment]
232e9b53666862c5db30a51c

**Comment by Asternitix** [comment]
I reran run_keybase and /keybase is gone!

**Comment by jzila** [comment]
```
41309 2017-10-12T18:16:50.897741-07:00 ▶ [DEBU kbfs start.go:35] 081 Mounting: "/keybase"
41310 2017-10-12T18:16:50.899574-07:00 ▶ [DEBU kbfs start.go:38] 082 Starting to mount the filesystem
41311 2017-10-12T18:16:50.970742-07:00 ▶ [ERRO kbfs mount_interrupter.go:52] 083 Mounting the filesystem failed: stat /keybase: no such file or directory
41312 kbfsfuse error: (2) stat /keybase: no such file or directory
```

All right, I thought we create the directory for you, but it seems that on Linux it needs to exist.
either:
```
$ mkdir /keybase && run_keybase
```

or if that fails:
```
$ sudo mkdir /keybase && run_keybase
```

**Comment by Asternitix** [comment]
▶ ERROR Unable to find conversation.
When considering aevan as a username or a list of usernames, received error: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with `run_keybase` command..
When considering aevan as a team name, received error: Team "aevan" does not exist.
nope, it's still not working

**Comment by Asternitix** [comment]
ls /keybase

**Comment by jzila** [comment]
can you send a new log please?

**Comment by Asternitix** [comment]
9adcb5b8aaf45c65b5b6091c

**Comment by jzila** [comment]
```
42030 2017-10-12T18:37:30.762394-07:00 ▶ [DEBU kbfs start.go:35] 098 Mounting: "/keybase"
42031 2017-10-12T18:37:30.762429-07:00 ▶ [DEBU kbfs start.go:38] 099 Starting to mount the filesystem
42032 2017/10/12 18:37:30 mount helper error: fusermount: user has no write access to mountpoint /keybase
42033 2017/10/12 18:37:30 mount helper error: fusermount: user has no write access to mountpoint /keybase
42034 2017-10-12T18:37:30.773515-07:00 ▶ [ERRO kbfs mount_interrupter.go:52] 09a Mounting the filesystem failed: fusermount: exit status 1
42035 kbfsfuse error: (2) fusermount: exit status 1
```

OK I guess you used the `sudo` way:
```
$ sudo chmod 777 /keybase && run_keybase
```

That should get you there, @Asternitix :)

**Comment by Asternitix** [comment]
that was the only way to create a folder.

**Comment by Asternitix** [comment]
that fixed it. thanks!

**Comment by jzila** [comment]
Glad to hear it. Thanks for your patience!

**Comment by Asternitix** [comment]
you guys responded quickly! good job!

**Comment by Asternitix** [comment]
this restored the files that I didn't even know were missing, I definitely wrote files into the directory.

**Comment by Asternitix** [comment]
putting not to use sudo to move files in the Linux documentation should keep this problem from happening to other people.

**Comment by oconnor663** [comment]
Sorry for not jumping in here sooner. We run `mkdir /keybase && chmod 777 /keybase` as part of the package install, so that it runs as root. That way `run_keybase` can run with only user privileges.

**Comment by Asternitix** [comment]
fs and /keybase is broken again. how do I reset ~/.local/share/keybase/fs? also, how do I make a /keybase symlink, the last time I made one i broke it, then fixed it, and now it broke again

**Comment by Asternitix** [comment]
Username:      asternitix
Logged in:     yes

Device:
    name:      beta14
    ID:        d71448c744ee74cea5f37adddcf6f318
    status:    active

Session:       no session
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    not cached
    secret:    stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached

KBFS:
    status:    running
    version:   1.0.2-20180215171601+7c28f5e1
    log:       /home/asternitix/.cache/keybase/keybase.kbfs.log
    mount:     /home/asternitix/.local/share/keybase/fs

Service:
    status:    running
    version:   1.0.41-20180215171601+d30b2a39c7
    log:       /home/asternitix/.cache/keybase/keybase.service.log

Updater:
    log:       /home/asternitix/.cache/keybase/keybase.updater.log

Platform Information:
    OS:        linux
    OS vers:   Linux 3.8.11 x86_64-Debian GNU/Linux 9.3 (stretch)
    Runtime:   go1.9.2
    Arch:      amd64

Client:
    version:   1.0.41-20180215171601+d30b2a39c7

Desktop app:
    status:    not running
    version:   
    log:       /home/asternitix/.cache/keybase/Keybase.app.log

Config path:   /home/asternitix/.config/keybase/config.json
Default user:  asternitix
Other users:   

command-line client:
    keybase status [pid: 24541, version: 1.0.41-20180215171601+d30b2a39c7]

KBFS:
    kbfsfuse -debug -log-to-file /home/asternitix/.local/share/keybase/fs [pid: 24365, version: 1.0.2-20180215171601+7c28f5e1]

log id: 159a359debf79e7bc6ea7b1c

**Comment by strib** [comment]
@Asternitix the error is:

```
user has no write access to mountpoint $HOME/.local/share/keybase/fs
```

What are the permissions on that directory?

You can probably restore things with something like:

```sh
killall kbfsfuse
fusermount -u $HOME/.local/share/keybase/fs
rmdir $HOME/.local/share/keybase/fs
sudo rm /keybase
sudo ln -s /var/lib/keybase/mount1 /keybase
run_keybase
```

But I don't know how you would have gotten into a broken state to begin with.  Are you doing anything unusual in your setup?

**Comment by Asternitix** [comment]
I have kbsecret installed, also, how would I rebuild /keybase, since I deleted it while trying the previous method to try to fix it.

**Comment by Asternitix** [comment]
fusermount -u $HOME/.local/share/keybase/fs did not work. 
fusermount: entry for /home/asternitix/.local/share/keybase/fs not found in /etc/mtab

**Comment by strib** [comment]
> I have kbsecret installed. It writes its config to a folder in kbfs and uses it for storage.

Just follow the steps above.  If kbsecret created a `/keybase` directory, you might have to move/remove it manually.

> fusermount -u $HOME/.local/share/keybase/fs did not work.
> fusermount: entry for /home/asternitix/.local/share/keybase/fs not found in /etc/mtab

That's ok, you can ignore that.

**Comment by Asternitix** [comment]
would I use rm -rf if fs is not empty?

**Comment by strib** [comment]
> would I use rm -rf if fs is not empty?

It's probably safer to move it somewhere else with `mv`, just in case something wrote data in there that you need.

**Comment by Asternitix** [comment]
also, /keybase is already gone.

**Comment by Asternitix** [comment]
ls -l src/
total 4
drwxr-xr-x 3 asternitix asternitix 4096 Feb 15 11:30 private

**Comment by Asternitix** [comment]
yup that fixed it. thanks @strib
