### ISSUE TITLE
git: unable to clone

### ISSUE THREAD

**Issue by initbar** [keybase/keybase-issues#3091]
I've just provisioned a new Ubuntu 17.10 server - but I can't seem to git clone my private repositories. Here's the error log:

```
➜  ~ git clone keybase://private/initbar/config
Cloning into 'config'...
Initializing Keybase... done.
Syncing with Keybase... This device does not yet have read access to directory /keybase/private/initbar, log into Keybase from one of your other devices to grant access: b8b2d032a039fe31d0ff9c692e577216 is not readable by initbar (uid:0a8cc24fccabb387f5429f85424e6d19)
github.com/keybase/kbfs/libkbfs.isReadableOrError
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/md_util.go:74
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).getMaybeCreateRootNode
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:516
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).GetOrCreateRootNode
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:557
github.com/keybase/kbfs/libgit.getOrCreateRepoAndID
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libgit/repo.go:368
github.com/keybase/kbfs/libgit.GetRepoAndID
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libgit/repo.go:490
github.com/keybase/kbfs/kbfsgit.(*runner).initRepoIfNeeded
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:268
github.com/keybase/kbfs/kbfsgit.(*runner).handleList
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:567
github.com/keybase/kbfs/kbfsgit.(*runner).processCommand
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:1558
github.com/keybase/kbfs/kbfsgit.(*runner).processCommands.func1
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:1598
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
git-remote-keybase error: (1) This device does not yet have read access to directory /keybase/private/initbar, log into Keybase from one of your other devices to grant access: b8b2d032a039fe31d0ff9c692e577216 is not readable by initbar (uid:0a8cc24fccabb387f5429f85424e6d19)
github.com/keybase/kbfs/libkbfs.isReadableOrError
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/md_util.go:74
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).getMaybeCreateRootNode
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:516
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).GetOrCreateRootNode
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:557
github.com/keybase/kbfs/libgit.getOrCreateRepoAndID
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libgit/repo.go:368
github.com/keybase/kbfs/libgit.GetRepoAndID
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libgit/repo.go:490
github.com/keybase/kbfs/kbfsgit.(*runner).initRepoIfNeeded
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:268
github.com/keybase/kbfs/kbfsgit.(*runner).handleList
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:567
github.com/keybase/kbfs/kbfsgit.(*runner).processCommand
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:1558
github.com/keybase/kbfs/kbfsgit.(*runner).processCommands.func1
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsgit/runner.go:1598
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
```

## Environment
- Ubuntu Server 17.10 (x64)
- Keybase client:
  - Client:  1.0.34-20171020160100+8038da614
  - Service: 1.0.34-20171020160100+8038da614
- Git client:
  - Client: 2.14.1

## Steps to Reproduce
1. Setup a virtual machine with Ubuntu Server 17.10 (x64).
2. Login to Keybase client.
3. `git clone` a private repository.

**Comment by strib** [comment]
Hi @initbar: usually "This device does not yet have read access to directory" means that you need another of your keybase devices to come online and rekey the folder for you.  Is there another device online?  How did you provision this new device exactly?

**Comment by initbar** [comment]
Hello ~ The git repos were created under `c3cd65a66d41239234857e2a32f3ee35` device in https://keybase.io/initbar/devices. Due to a config issue, I had to delete the vm that logged in as `c3cd65a66d41239234857e2a32f3ee35` and create another device under the "paper" type `reason resemble`.

The current instance didn't get a chance to rekey from the `c3cd65a66d41239234857e2a32f3ee35` device.

**Comment by initbar** [comment]
Since rekeying did not take place, does this mean the repositories are forever lost (or computationally infeasible to recover)?

**Comment by strib** [comment]
No, it looks like the folder is still keyed for your paper key, `reason resemble`.  I don't know why the provisioning process didn't key it for your new device.  But you should be able to rekey it manually with `keybase rekey paper`, and then entering your full paper key.  Does that work?

**Comment by strib** [comment]
Also: did you provision the new device using the paper key, or with the old device `c3cd65a66d41239234857e2a32f3ee35` right before you revoked it?

**Comment by initbar** [comment]
I've provisioned the new device using the paper key - I was planning to revoke the `c3cd65a66d41239234857e2a32f3ee35 ` manually later.

**Comment by initbar** [comment]
I'll try the `keybase rekey paper` method ~

**Comment by strib** [comment]
Hmm, ok.  Usually provisioning via paper key should rekey your folders for you, not sure why that didn't happen.  (Maybe you restarted Keybase too quickly after provisioning or something?)  If you want to send logs with `keybase log send` I'd be happy to take a look.

**Comment by initbar** [comment]
Yup that fixed the problem - thank you !
