### ISSUE TITLE
ERROR openpgp: unsupported feature: nested signatures

### ISSUE THREAD

**Issue by palager** [keybase/keybase-issues#3097]
I continually get this error message on `keybase login`

```
$ keybase login palager
▶ ERROR openpgp: unsupported feature: nested signatures
$
```

But I have no idea what the problem is. I tried nuking everything and starting again to no avail. Please let me know if I can gather any more information to help figure this out.

my log id: f4b221370b3d10a1ff05fd1c

**Comment by maxtaco** [comment]
Looks like we can't support your PGP key.

Go to the website and reset your account.

**Comment by palager** [comment]
ok I reset my account by clicking "Reset my keys [...]"

I generated a new set of keys in a fairly vanilla way (previously I had a some yubikey subkeys, now I just have the SC key and an E subkey no other subkeys). I uploaded this new key, using the curl+gpg method.

I killed the running keybase, ran `keybase logout` (even though I wasn't logged in) and then tried `keybase login palager` but I'm still seeing the same message:
```
keybase login palager
▶ ERROR openpgp: unsupported feature: nested signatures
```

Then I tried "Reest my keys [...]" again, this time letting keybase generate keys via the web by clikcing "I need a keys". Again killed keybase on my machine, `keybase logout`, `keybase login palager`, still same thing. Any ideas what I can do?

**Comment by maxtaco** [comment]
@zapu any ideas on this one?  maybe the key is still being access as part of playing back the pre-reset sigchain

**Comment by zapu** [comment]
Looks like it, can't ID either.

**Comment by palager** [comment]
Still a problem for me. Is there any way to prune the old key out of the sigchain?

**Comment by maxtaco** [comment]
no, sorry... this bug got back-burnered, it's still in our worklist, but haven't gotten around to it yet, sorry.

**Comment by zapu** [comment]
It should be fixed now.

**Comment by palager** [comment]
Sorry for the delay. I did the "Reset my keys [...]" workflow again and can confirm it is now fixed. Thanks!
