### ISSUE TITLE
Any way to re-own a team of same account?

### ISSUE THREAD

**Issue by HuangFJ** [keybase/keybase-issues#3105]
I created my keybase account "j0n" and setup a device key first time I installed the client. Then I create a team. But, I uninstalled the client accidentally, so I lost the device key. Finally I reset my account and setup a new device. And I still can see the team, but it states I'm not part of it. Is there any way to re-own it?

**Comment by malgorithms** [comment]
Sorry, no. There's no way to recover a team when all the owner devices are lost, including due to an account reset. This is for security reasons. You'll have to pick a new team name.
