### ISSUE TITLE
Cannot add new device - Invalid name

### ISSUE THREAD

**Issue by AuHau** [keybase/keybase-issues#3109]
I installed Keybase on my laptop and when I logged in and wanted to name the device I was not able to find any name which would be accepted... 

I tried:

- adam-nb
- laptop_12312344412412
- laptop 1

For all of them I got the "Invalid device name" error.

What could be wrong?

**Comment by maxtaco** [comment]
Fixed [here](https://github.com/keybase/client/pull/9455), we're pushing a new build this morning.

**Comment by AuHau** [comment]
Awesome!

Thanks a lot :-)
