### ISSUE TITLE
Any way to login via pgp key? 

### ISSUE THREAD

**Issue by Ociramma** [keybase/keybase-issues#3117]
I have 2 signed devices - my phone with busted screen and my old laptop. I reinstalled os on my laptop and can't sing in to my account until I get screen replacement. Isn't there a way to sing in using my private pgp key and passphrase, because I have backup of both, but sadly no paper key. Or if I reset my account via website my git will also dissappear (because I need to download my code from git somehow)?

**Comment by maxtaco** [comment]
sadly no, we don't encrypt your keys for PGP key, so you'd lose secret information if the PGP key is all you have.

**Comment by Ociramma** [comment]
Eh, that's sad.. Definitely gonna make backup paper key when it'll change the screen on phone and will finally be able to approve new devices. Ok, thanks.
