### ISSUE TITLE
RPM repository not compatible with OpenSUSE

### ISSUE THREAD

**Issue by M-Pixel** [keybase/keybase-issues#3118]
After adding the repository to OpenSUSE, I'm able to install Keybase, but unable to refresh the repository and therefore unable to update the application. When trying to refresh the repository, I get the following error:

`Permission to access 'http://prerelease.keybase.io/rpm/x86_64/media.1/media' denied.`

See https://github.com/brave/browser-laptop/issues/8156

**Comment by maxtaco** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
@cjb is this the issue we saw a while back about OpenSUSE interpreting a 403 as a fatal error?

**Comment by oconnor663** [comment]
Here's another mention, but not the one where we discussed it: https://github.com/keybase/client/issues/7196

**Comment by oconnor663** [comment]
Found the discussion: https://github.com/keybase/keybase-issues/issues/2987

**Comment by oconnor663** [comment]
I've added public list permissions for the S3 bucket that backs this URL. I think that should fix the issue. Please let me know if you still see it.

**Comment by M-Pixel** [comment]
It looks like that fixed it. Thank you for the timely response!
