### ISSUE TITLE
Unable to open private and public folders due to revoked devices

### ISSUE THREAD

**Issue by PPDrengenX** [keybase/keybase-issues#3119]
Revoked old devices that where no longer in use and can't access private and public folders on a new device. Although when trying to open the public folder it says that this device does not have read access to the private folder.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkEq6AS0 vsoSZQvtti6Ukmh QgBP9B6ln4pIkA7 ikcyLeSNhZgqnxo 060jkHVeBVypDX6 vspWz4l3bekWepA akFamm11LS0oI49 cjT34EDjWdpqlHm Sbq7YADRC2RVaZo J2yNMbgpbiOZkMj 2e5Eo5FVqsoyHPA pihsYsWH1BkiIib 7qjpd4om5RCQPsm fgcu4O2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49opC RftRbFrH3FAICtA odRP00S3OdPMzJC G8L4AD80jxvTUtR 3NWESkxMGJ1Zdtb sLX0uskcJ7LmfBO EhfgOUnNXCwxUsO zQeKGi6ahq0NFL2 o193Xn0VhE4ndXn smxi9scmClEW9ov bAherEAI. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @PPDrengenX: I reset the private folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

Public folders almost never need a reset.  I can view your (empty) public folder just fine locally.  If you're still having problems with it after a restart, could you please do a `keybase log send` and post the resulting log ID here so I can see what's wrong?

**Comment by PPDrengenX** [comment]
Got it working. Seems like keybase did not like that a drive with the letter N already existed, so I had to change the drive letter so that keybase had the drive letter N to itself.
