### ISSUE TITLE
DNSSEC and DANE/TLSA?

### ISSUE THREAD

**Issue by andreaso** [keybase/keybase-issues#312]
For additional trust in https://keybase.io/, how about also applying DNSSEC as well as DANE/TLSA? While there are weaknesses in both the browser CA structure and the DNSSEC hierarchy at lest combined they make an impersonation harder.

**Comment by ptrf** [comment]
What is the progress on this one? .io has DS records, so signing the keybase zone should be fairly straight forward?

**Comment by JonLundy** [comment]
+1  Though it appears that keybase.io uses AWS route 53 which currently does not support DNSSEC.  :-(

**Comment by nunnun** [comment]
+1 for supporting DNSSEC.

**Comment by Bandie** [comment]
+1. I wannit naaau!

**Comment by PunKeel** [comment]
+1

**Comment by Bandie** [comment]
+1

**Comment by Bandie** [comment]
Bump?

**Comment by zhovner** [comment]
After so many years of DNSSEC existence, we can truly say that it has failed. 
There is no successful DNSSEC deployment by major players. Who used in real life?
