### ISSUE TITLE
there are a community forum / team, which data is stored where and server software are opensource?

### ISSUE THREAD

**Issue by sks7g** [keybase/keybase-issues#3121]
Hi, I'm new to KeybaseIO and just getting to know it. I like your development work, I think it's the right direction. I've already read a lot of things, but some of them are still unclear to me. It's hard for me to ask the questions here, I have many questions, questions that your website / documentation might answer, but English is not my native language. 

My first question is, is there a kind of forum where other users can interact?
Maybe a "team" under KeybaseIO, maybe also in German? 
(If allowed, I have set up a forum at http://keybase.boards.net/)

But the most important question for me at the moment....
Is there a schema, a documentation in detail, which data, how long are stored on the server? 

I know the signature chain, but what is actually stored in it? 
Where are the chat messages, the files KBFS / GIT saved?

Is the server software also OpenSource?
Is it planned to build a "server" mesh?
It thinks there is a great interest in owning your own server (including KBFS and GIT - file exchange, Virtual-/RootServer, NAS). Just a thought.....

Please be patient with me.
Erik

**Comment by jcalfee** [comment]
Partially Related: https://github.com/keybase/keybase-issues/issues/1304
