### ISSUE TITLE
API documentation issue

### ISSUE THREAD

**Issue by jrtapsell** [keybase/keybase-issues#3122]
In the docs on this page:
```https://keybase.io/docs/api/1.0/call/user/lookup``` [Link](https://keybase.io/docs/api/1.0/call/user/lookup)

It is mentioned that you can query by domain like so:
```https://keybase.io/_/api/1.0/user/lookup.json?domain=chriscoyne.com```[Link](https://keybase.io/_/api/1.0/user/lookup.json?domain=chriscoyne.com)
```{"status":{"code":0,"name":"OK"},"them":[]}```

Testing this seems to fail, even with the link provided later on as an example:
```https://keybase.io/_/api/1.0/user/lookup.json?domain=keybase.io&fields=basics```[Link](https://keybase.io/_/api/1.0/user/lookup.json?domain=keybase.io&fields=basics)
```{"status":{"code":0,"name":"OK"},"them":[]}```

It seems that the correct form is using `https` and `dns`, which give the following results for the test above:
```https://keybase.io/_/api/1.0/user/lookup.json?dns=keybase.io&fields=basics```[Link](https://keybase.io/_/api/1.0/user/lookup.json?dns=keybase.io&fields=basics)
```{"status":{"code":0,"name":"OK"},"them":[]}```

```https://keybase.io/_/api/1.0/user/lookup.json?https=keybase.io&fields=basics```[Link](https://keybase.io/_/api/1.0/user/lookup.json?https=keybase.io&fields=basics)
```{
   "status":{
      "code":0,
      "name":"OK"
   },
   "them":[
      {
         "id":"23260c2ce19420f97b58d7d95b68ca00",
         "basics":{
            "username":"chris",
            "ctime":1391653108,
            "mtime":1457530064,
            "id_version":345,
            "track_version":878,
            "last_id_change":1511747643,
            "username_cased":"chris",
            "status":0
         }
      },
      {
         "id":"dbb165b7879fe7b1174df73bed0b9500",
         "basics":{
            "username":"max",
            "ctime":1391657400,
            "mtime":1421074124,
            "id_version":192,
            "track_version":279,
            "last_id_change":1506102553,
            "username_cased":"max",
            "status":0
         }
      }
   ]
}
```

Is this an issue with the docs, or with the API?

**Comment by maxtaco** [comment]
I think it's a bug on the server-side, we can take a look. Thank you for the careful write-up

**Comment by jrtapsell** [comment]
The issue is demonstrated by this: https://jsfiddle.net/1b2065sm/

**Comment by malgorithms** [comment]
ok, this should be fixed. 

https://keybase.io/_/api/1.0/user/lookup.json?domain=chriscoyne.com&fields=basics,profile
