### ISSUE TITLE
Keybase claims my PGP key will be deleted, but it isn't.

### ISSUE THREAD

**Issue by jasikpark** [keybase/keybase-issues#3125]
In KeyBase Desktop on macOS, if I decide to change my password, the password update window has a notice that tells me that my PGP key will be deleted if I change my password, and that I will have to generate a new one. But my PGP key is still associated with my account.

I'm not sure what the correct behavior is, but it's definitely inconsistent.

**Comment by junderw** [comment]
ACK

This is a relic of the old web-only Keybase. Where the keybase account would directly sign in your PGP key... looking at your graph, your laptop signed your PGP key with NaCl keys... so your Keybase password is not related to your PGP key at all.

The type of account that WILL delete the PGP keys if you change the password has a graph like this:

https://keybase.io/sarahjeong/graph (keybase is directly connected to PGP with a blue arrow)

**Comment by jasikpark** [comment]
ok, thanks a lot! I was pretty sure that everything was ok when the key did not get deleted, but I half expected that policy to be a result of some security idea with PGP that I was not aware of. 

I feel like it might be good to add better documentation or onboarding to using PGP with keybase.
(I suppose that's why it's being built into the GUI)

What I really mean though, is adding to the articles explaining following and the signature chain, if there could be an article explaining advantages and pitfalls of PGP and how to get set up with PGP outside of Keybase.

**Comment by maxtaco** [comment]
I think what's happening here is that your server-synced PGP *private* key is getting deleted, since without the old password, it can't be decrypted and then re-encrypted with the new password. However, the *public* half of the key remains associated with your account.

**Comment by njm2112** [comment]
what happens if the PGP key *is* deleted? it seems that mine is deleted and now when i try to access my account through any of my devices, i receive a 202 error / `Unknown error: BAD_SESSION / Failure in verify PDPKA5`:

![Snip20200621_5](https://user-images.githubusercontent.com/10353532/85240312-be5fb180-b405-11ea-98d2-83d244882fc2.gif)

how can i regain access / login to my account?
