### ISSUE TITLE
Self chat to save messages, notes for personal use

### ISSUE THREAD

**Issue by mat-ale** [keybase/keybase-issues#3137]
Hi all,

I'd like to propose a feature:
simply a Telegram-like feature to save messages in the cloud (encrypted of course) maybe in a self personal chat (as Telegram does).
Here is the Telegram feature I talk about: https://telegram.org/blog/albums-saved-messages#saved-messages

Best regards

**Comment by zQueal** [comment]
This would be really nice. I use the telegram feature quite a bit. The only thing it's missing on the Telegram end is the ability to encrypt a chat to yourself.

Having Keybase fill this niche is a big 👍 from me.

**Comment by mat-ale** [comment]
@zQueal, yes the big problem is that self chat is not encrypted in Telegram. It would be very nice to have this in Keybase.

**Comment by nlevitt** [comment]
Seems to work for me...

**Comment by paulbruneau** [comment]
It works for you, @nlevitt? When I try to send myself a message in the Keybase Mac client, the message just disappears and is not in the chat window. I would like to see the same behavior that is in Slack where we can send ourselves messages.

**Comment by samandarr** [comment]
any updates on that?

**Comment by malgorithms** [comment]
yeah, you can send yourself a message in keybase chat. Just search for yourself from the chat compose button. Or do something like this from the terminal:

```
keybase chat send chris "hello to me"
```

**Comment by stephenconnolly1** [comment]
I couldn't start a convo in the Windows GUI client - wouldn't let me search for myself. but using the CLI worked fine and from there I'm GTG

**Comment by MisterY** [comment]
The Android client lists my account at the top, stating "send an encrypted message to yourself".
The same with the Linux GUI client.

**Comment by MisterY** [comment]
And now I can also confirm that the current Windows version does the same.
