### ISSUE TITLE
How to add trusted CA?

### ISSUE THREAD

**Issue by tclarke** [keybase/keybase-issues#3143]
I'm behind a corporate firewall that intercepts SSL connections for monitoring. I can't login to keybase (gui or client) because the firewall's certificate isn't recognized as a valid root cert even though it's in my system CA store (windows). How can I add a trusted CA cert that the keybase client will use? The specific error I get is:

`ERROR API network error: doRetry failed...https://api.keybase.io..... x509: certificate signed by unknown authority (code 1601)`

**Comment by zanderz** [comment]
We may need to look into honoring the system store, if we don't now. Meanwhile, if you don't mind trying this, it may help:
1. Export the firewall cert in DER encoded binary x509
2. Add the path to this cert to Keybase's settings:
  `keybase config set proxy_ca_certs [path to exported PEM]`

**Comment by zanderz** [comment]
I take it that worked?
Still researching this, but Golang's TLS implementation seems to not honor the system trusted CA pool:
https://golang.org/src/crypto/x509/cert_pool.go?s=730:770#L22

**Comment by tclarke** [comment]
Yes, that seems to have worked. I had a few issues with windows paths but I put the cert file in the same directory as config.json is it's working now.

**Comment by espoelstra** [comment]
See the comments on #14307 as there is still a bug in Golang causing issues, but there are a couple potential workarounds.
