### ISSUE TITLE
Feature: have the ability to zoom the interface

### ISSUE THREAD

**Issue by yannicka** [keybase/keybase-issues#3151]
It would be nice to have a setting to zoom the interface (choose between 80%, 90%, 100%, 110%, 120%, 130%, 140%, etc.). The setting would zoom the entire interface and not only the main panel. A shortcut to change the zoom could be <kbd>CTRL+wheel</kbd>.

An example: https://github.com/keybase/client/issues/8638#issuecomment-353155889.

**Comment by mhkeller** [comment]
@yannicka You can go to `Window > Zoom In` to zoom the interface. Does that satisfy the use case?

**Comment by yannicka** [comment]
Yes, perfect, thanks.
