### ISSUE TITLE
Web proof failing over HTTPS, works from cli

### ISSUE THREAD

**Issue by michaelpj** [keybase/keybase-issues#3154]
The keybase website tells me that my web proof at `www.michaelpj.com/.well-known/keybase.txt` is broken.

However:
```
# keybase id -s michaelpj
▶ INFO Identifying michaelpj
✔ public key fingerprint: 1467 08F4 9CF9 18E7 A179 FD2D C785 EF06 E1E7 13F3
✔ "michaelpj" on github: https://gist.github.com/bb0ee843ff17681f9ffd
✔ admin of michaelpj.com via HTTP: http://michaelpj.com/.well-known/keybase.txt
✔ "michaelpj" on facebook: https://facebook.com/10154913210037394_10154913212207394
✔ "mpeytonjones" on twitter: https://twitter.com/mpeytonjones/status/668128441082978304
```
works fine.

I do have a redirect from all HTTP addresses to the corresponding HTTPS addresses. Possibly that's interfering, although it appears to work fine with the cli.

**Comment by michaelpj** [comment]
Hm, I checked back on the website and it seems to be fine now. Not sure what happened there.

**Comment by maxtaco** [comment]
Thanks for the report, we fixed a bug in our scraper and reran the broken proofs...

**Comment by chrisparker787** [comment]
I swapped to https on my sites yesterday and now KB is reporting the proofs are broken. However, command line seems good:
chris@macbookpro-19 ~ % keybase id -s chrisparker
▶ INFO Identifying chrisparker
✔ public key fingerprint: FAE7 2864 7E02 B543 9A28 8D94 A126 BF6D 823B B40C
🚀  Stellar GCMXQQBQFZTNW4TI3HPU2XMYWWLOPNBLQ5MV2WDPOX727YWURFI4JIGI (chrisparker*keybase.io)
✔ admin of fourfax.co.uk via HTTPS: https://fourfax.co.uk/keybase.txt
✔ admin of daily-photo.net via HTTP: http://daily-photo.net/keybase.txt
✔ "chrispar" on twitter: https://twitter.com/chrispar/status/519484112554319873
✔ admin of chrisparker340.com via HTTP: http://chrisparker340.com/keybase.txt
✔ admin of mistralsailing.net via HTTP: http://mistralsailing.net/.well-known/keybase.txt
✔ admin of www.hang-out.co.uk via HTTP: http://www.hang-out.co.uk/keybase.txt

![Image 2020-12-31 at 11 39 14 am](https://user-images.githubusercontent.com/38974378/103406950-d8b8db80-4b5c-11eb-8835-a9cf632c271e.jpg)

How can I fix this?

Thanks!
