### ISSUE TITLE
git repos unusable

### ISSUE THREAD

**Issue by jshall** [keybase/keybase-issues#3156]
Both of my git repos are reporting something like:
```
PS> git fetch keybase://private/jshall/PowerShell
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Server: block does not exist
git-remote-keybase error: (1) Server: block does not exist
```

I've been able to clear this up a couple times by deleting and recreating the repo, but now it won't let me delete the repo.

**Comment by strib** [comment]
@jshall: sorry about this.  Can you please do a `keybase log send` and post the log ID here?  And can you please give some more context -- did they just stop working? When was the last time you used them successfully?

**Comment by jshall** [comment]
log id: 6031330474c4cd654f8d1c1c

**Comment by strib** [comment]
Ah from your log, it looks like this has been happening for at least over a month.  We had some problems like this around the time we first launched git in October, and we fixed them in a later release.  Is it possible the problem started around then?

**Comment by jshall** [comment]
Yes, it was in October that I first saw this issue.

**Comment by strib** [comment]
Ok got it.  Are you ok with losing all your personal git repos?  (You can always recreate them again after from local checkouts.)  If so, you can go into your private KBFS folder (in the K: on Windows) from a shell, and (if it's unix-like) do `rm -rf .kbfs_git`.  (Or the equivalent `rd` command on a more Windows-y terminal.)  That's a magic subdirectory that doesn't appear in directory listings but you should be able to remove it manually, I think.

**Comment by jshall** [comment]
I'm told it does not exist. (Windows 10, keybase version 1.0.38-20171220134249+a7fe25d)

**Comment by strib** [comment]
Can you `cd` into it, despite it not existing?  (I don't have a Windows box handy for testing, sorry.)

**Comment by jshall** [comment]
Nope.
```
K:\
PS> ls -Recurse -Force |% FullName
K:\private
K:\team
K:\public
K:\private\jshall
K:\private\jshall\New folder
K:\private\jshall\test.txt
K:\public\jshall
```
FYI: the -Force parameter means to include hidden files/folders

**Comment by strib** [comment]
This isn't a windows hidden folder, it's something KBFS specific.  We keep it out of directory listings completely.  Just try to cd into it.

**Comment by jshall** [comment]
```
K:\
PS> cd .kbfs_git
cd : Cannot find path 'K:\.kbfs_git' because it does not exist.
At line:1 char:1
+ cd .kbfs_git
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (K:\.kbfs_git:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand


K:\
PS> ls C:\Users\josh.hall\AppData\Local\Keybase\kbfsgit*


    Directory: C:\Users\josh.hall\AppData\Local\Keybase


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/11/2017     11:13                kbfsgit205458547
d-----       10/12/2017     18:28                kbfsgit206836211
d-----       10/10/2017     22:05                kbfsgit289253067
d-----       10/11/2017     11:13                kbfsgit338714799
d-----       10/11/2017     11:24                kbfsgit406326547
```
Is the later what we're after?

**Comment by strib** [comment]
Oh sorry, not `K:\.kbfs_git`, but the one in your personal folder: `cd K:\private\jshall\.kbfs_git`

**Comment by jshall** [comment]
```
PS> rm .kbfs_git -Recurse -Force
rm : Cannot remove item K:\private\jshall\.kbfs_git\powershell: The directory is not empty.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (powershell:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Cannot remove item
K:\private\jshall\.kbfs_git\.kbfs_deleted_repos\gitconfig012056199a693d7bf099b27344b13b7867dbd2682443cc22d4ea04300043e99622e50a-1513538329479339400\objects\pack: Access to the path
'pack' is denied.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (pack:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Cannot remove item K:\private\jshall\.kbfs_git\.kbfs_deleted_repos\gitconfig012056199a693d7bf099b27344b13b7867dbd2682443cc22d4ea04300043e99622e50a-1513538329479339400\objects:
The directory is not empty.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (objects:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Cannot remove item K:\private\jshall\.kbfs_git\.kbfs_deleted_repos\gitconfig012056199a693d7bf099b27344b13b7867dbd2682443cc22d4ea04300043e99622e50a-1513538329479339400: The
directory is not empty.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (gitconfig012056...538329479339400:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Cannot remove item K:\private\jshall\.kbfs_git\.kbfs_deleted_repos: The directory is not empty.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (.kbfs_deleted_repos:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Cannot remove item K:\private\jshall\.kbfs_git: The directory is not empty.
At line:1 char:1
+ rm .kbfs_git -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (K:\private\jshall\.kbfs_git:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by strib** [comment]
Did that fix the issue?  It looks like it got hung up on an old, previously-deleted repo.  But it might have succeeded in deleting your currently-active repos?

**Comment by jshall** [comment]
No, now a pull says the repo does not exist, so I ran `keybase git create powershell` got `ERROR  (code 2704)`, went to the UI and found:
![image](https://user-images.githubusercontent.com/6936909/34745799-baadac20-f55f-11e7-9822-1fb51b34b7c4.png)

log: d3829e786488bd3ecf5b741c

**Comment by strib** [comment]
Hmm, ok, how about this:

```
cd K:\private\jshall\.kbfs_git
ren powershell .kbfs_deleted_repos/powershell-client-3156
keybase git remove powershell
```

The last command might show an error, but I think it would do the right thing regardless.

**Comment by jshall** [comment]
Sort of. Now I have 3 powershell repos according to the GUI. I was able to fetch the blank repo and push from local, but when I goto another computer it's still broken, but the changes to .kbfs_git have been synced.

I wonder if the .kbfs_git folder is why I'm having trouble. I am using keybase/git to work with the same repo from multiple devices.

**Comment by strib** [comment]
The .kbfs_git folder is what powers the repo.  It's where we store the actual repos.

On the new computer, you're getting the same "block does not exist" error?  If you send new logs from both devices I can try to figure it out.

**Comment by jshall** [comment]
Well, PC1 was working until I tried fixing PC2...

PC1 log: 2deb41c3e262d2dbf410a41c  
PC2 log: 43a756ddfa86d622fa52961c

**Comment by strib** [comment]
Aiii, I see the problem now.  We have this clever thing that's trying to clean up your old deleted repos on every push, if there are any.  In your case, there are some, but they are massively busted because of that old bug, and we're letting that error propagate up to fail the whole git command.  Try this:

```
cd K:\private\jshall\.kbfs_git
ren .kbfs_deleted_repos .kbfs_broken_deleted_repos_20170109
```

I _think_ that should fix it for all devices.  Sorry for all the back-and-forth.

**Comment by jshall** [comment]
```
C:\Users\josh.hall\Documents\WindowsPowerShell
PS> pushd K:\private\jshall\.kbfs_git

K:\private\jshall\.kbfs_git
PS> mv .\.kbfs_deleted_repos\ .\.kbfs_broken_deleted_repos_20180109\
mv : Access to the path 'K:\private\jshall\.kbfs_git\.kbfs_deleted_repos\' is denied.
At line:1 char:1
+ mv .\.kbfs_deleted_repos\ .\.kbfs_broken_deleted_repos_20180109\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (K:\private\jsha..._deleted_repos\:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
```

**Comment by strib** [comment]
Oh sorry, that's my fault.  Arg.  Users aren't allow to create new entries that start with .kbfs.  Just do something like:

```
cd K:\private\jshall\.kbfs_git
ren .kbfs_deleted_repos kbfs_broken_deleted_repos_20170109
```

instead.  Sorry.

**Comment by jshall** [comment]
That gets me to here:
```
PS> git fetch keybase
Initializing Keybase... done.
Syncing with Keybase... worktree should be provided
git-remote-keybase error: (1) worktree should be provided
git-remote-keybase error: (1) worktree should be provided

C:\Users\josh.hall\Documents\WindowsPowerShell
PS> keybase git list
personal repos:
  PowerShell  keybase://private/jshall/PowerShell
  PowerShell  keybase://private/jshall/PowerShell
  PowerShell  keybase://private/jshall/PowerShell
  powershell  keybase://private/jshall/powershell
  gitconfig   keybase://private/jshall/gitconfig
  PowerShell  keybase://private/jshall/PowerShell
team repos:
```

**Comment by strib** [comment]
Can you please do another `keybase log send`?  I've never seen that before.  Maybe you need to `keybase git create` again?

(We can manually clean up those extra git entries once we get this part working.)

**Comment by jshall** [comment]
log: 0587686df02ff7dd8d6f301c

**Comment by strib** [comment]
It seems like that error would get generated when `.kbfs_git/powershell/config` somehow doesn't have `core.bare` set to `true`.  Maybe this happened due to some previous failure.  Maybe try another `keybase git remove powershell` and re-create?

**Comment by jshall** [comment]
OK, I can now fetch and push on both machines. The ID of the only working git repo is fa7cb1d719db8890fdda8aa14d0e342c (from K:\private\jshall\.kbfs_git\powershell\kbfs_config)

**Comment by strib** [comment]
Yay!

@oconnor663 can you please manually clean up the list of personal repos for `jshall`?  `fa7cb1d719db8890fdda8aa14d0e342c` is the only valid repo at this point.

**Comment by oconnor663** [comment]
Done.

**Comment by jshall** [comment]
Thanks!
