### ISSUE TITLE
Similar to #69 : Keybase (web & pc) shows as valid proof when proven account is gone yet proof still exists. Perhaps caused by peculiar looking sigchain seq num 10.

### ISSUE THREAD

**Issue by lemonforest** [keybase/keybase-issues#3166]
Figured I'd fiddle with tracking a suggested person so here's what I noticed;

Guinea pig person - https://keybase.io/mairin

Facebook account proof is still accessible.
 - https://www.facebook.com/mairindubh/posts/10100610566871066

Or maybe it's just suspicious looking sequence number 10? Payload with revoke but sig_type=2 and other proof identifiers not null. I haven't really looked around much but hinky is the word I'm going with.
 - https://keybase.io/mairin/sigchain#ec0c4999071a84600212774a6635c1eacacdd075da390954778c9a87934d33030f
- https://keybase.io/_/api/1.0/sig/get.json?uid=1e25e01342f946cdb810bc487247a119

**Comment by maxtaco** [comment]
Everything looks fine here to me. What do you mean “proven account is gone”?

**Comment by lemonforest** [comment]
Oh, sorry for wasting time :( 
Also, I missed that link; https://www.facebook.com/mairindubh

Returns as if the FB account is locked, deactivated, or nuked I'm guessing. Also no FB guru by any stretch of the imagination so I don't know if, since the keybase proof FB post references the  FB username to whom it belongs, the account is simply deactivated.

Where I'm going with this is not wanting to view proof as invalid if the user still has access to the account they have proven. Since some clients appear to show a proof in red as unreachable, I'm assuming the client queries and decides if a questionable proof is displayed or is not displayed.

Again, sorry to waste your time. Seems it's simply FB related in this event so I'll go away now.
