### ISSUE TITLE
Unable to verify twitter

### ISSUE THREAD

**Issue by chriscpritchard** [keybase/keybase-issues#3167]
Hi, I appear unable to verify twitter:
My post is [here](https://twitter.com/chriscpritchard/status/955795464611344386)

The error I get is: OK "chriscpritchard" on twitter failed: No server-given hint for sig=54542f6dc9e16aa89170cee51d02e4b3e059038af954f67dcc77a8deca6760190f (code=306)

**Comment by maxtaco** [comment]
@chriscpritchard seems like twitter just changed their clients and now `Keybase.io` is getting linked and URL-shortened.  We'll have to make slight adjustments on our side.

Which client are you using?

Cc: @oconnor663  and @mlsteele, we should make changes the regexes to accept `Verifying myself: I am foobar on (keybase.io|https://t.co/*)`

**Comment by chriscpritchard** [comment]
I'm using the windows command line client, tried verifying on android mobile and web too

**Comment by maxtaco** [comment]
PR up here: https://github.com/keybase/proofs/pull/92/files

**Comment by chriscpritchard** [comment]
Works on the website now!
