### ISSUE TITLE
git doesn't have access to keybase

### ISSUE THREAD

**Issue by taniki** [keybase/keybase-issues#3169]
From a fresh ubuntu install, I get this error when trying to clone a repo stored on a private keybase. I am logged in and have access to `/private`

```
git-remote-keybase error: (1) Keybase isn't running. Try `run_keybase`.
```

```
Platform Information:
    OS:        linux
    OS vers:   Linux 4.13.0-31-generic x86_64-Ubuntu 17.10
    Runtime:   go1.9.2
    Arch:      amd64
```

**Comment by maxtaco** [comment]
Did you run_keybase as root? You didn’t want to if you did.

**Comment by taniki** [comment]
@maxtaco Nope as normal user

**Comment by taniki** [comment]
log ID: d0f758145799637e17ab001c

**Comment by taniki** [comment]
Sorry. That was a very sad PEBCAK (:

**Comment by TinaRussell** [comment]
What was the issue? I’m having problems where a userspace cron job (run as me) returns the "Keybase isn't running. Try run_keybase" error even though Keybase is definitely running, and I have no problem when running the same commands from the command line or in a script run without cron. Maybe some environment variable needs to be set first, but I have no idea what that would be. I’ll file a new bug if this is a separate problem from the above.

**Comment by TinaRussell** [comment]
Nevermind, I figured it out. My instinct was right, my cron script didn’t have access to a key environment variable: $XDG_RUNTIME_DIR, without which git-remote-keybase couldn’t find the Keybase socket and thus assumed Keybase wasn’t running.
