### ISSUE TITLE
KeyBase account locked out

### ISSUE THREAD

**Issue by jwitko** [keybase/keybase-issues#3171]
A while back there was a bug in keybase new accounts that required users to reset the password on their account in order to be able to login from the app and use keybase.  I finally got around to doing this today and now when I try to login to the app I am met with the error:

`ERROR CODE 218 - Too many failures; giving up in method keybase.1.login.login`.

I have not tried to login at all in the past month.  Can someone help reset my account so its usable again?  

Edit:  Account name = `throtle`

**Comment by mlsteele** [comment]
Could you run `keybase log send`? Are you able to log on the website?

**Comment by jwitko** [comment]
Edited the initial post to contain account name.

@mlsteele I am able to login to the website, yes.  This is how I reset my password.

I executed the `keybase log send` you requested, the returned ID was `91b59cd1303e8cd7ebc8f31c`

**Comment by jwitko** [comment]
@mlsteele I figured it out.  I didn't need a password reset, I needed to do a full account reset wiping all my keys.
