### ISSUE TITLE
keybase chat delete-history suddenly stopped working

### ISSUE THREAD

**Issue by agsimeonov** [keybase/keybase-issues#3173]
The feature was running fine a few hours ago and then suddenly when I run ```keybase chat delete-history [conversation]``` I get the following error:

`ERROR error communicating with chat server: The delete-history feature is temporarily disabled. Should be back in a couple days.`

**Comment by mlsteele** [comment]
Yep. It's temporarily disabled to prevent people from running into [this bug](https://github.com/keybase/client/issues/10339).
