### ISSUE TITLE
Message decrypted without a valid password!

### ISSUE THREAD

**Issue by ToJen** [keybase/keybase-issues#3183]
I tried decrypting a message from my terminal and realised I forgot my password, so I closed the Keybase password dialog. After that, the message was decrypted with the following format:

```
me:/path/to/message$ keybase pgp decrypt -i message_file
▶ WARNING error unlocking key: Input canceled
Username,Password
user,brownies
.
.
.
```

Is this normal? The website didn't let me decrypt the message but my terminal did. 

@patrickxb @gabriel @cjb @jzila @songgao

**Comment by maxtaco** [comment]
What type of file is `message_file`?  Maybe it's just a sig?  `cat message_file | gpg --list-packets`

**Comment by ToJen** [comment]
It's just a regular text file I created to store a message I received. I think it was a signature because it had the message and the sender's keybase info.

**Comment by maxtaco** [comment]
that explains why your private key isn't really needed.  maybe it's some bug where we thought it was

**Comment by ToJen** [comment]
```
me:/path/to/message$ file message 
message: PGP message Public-Key Encrypted Session Key
```

**Comment by ToJen** [comment]
Thanks @maxtaco, closing this.
