### ISSUE TITLE
Keybase Graphical Bug - Cannot Open

### ISSUE THREAD

**Issue by bzadoroz** [keybase/keybase-issues#3186]
Cannot open Keybase app on Windows 10, nVIDIA 980 Ti even after repairing installation and rebooting PC. Something appears on taskbar (like the app icon) but the icon when right clicked shows nothing and Keybase cannot be opened.

**Comment by zanderz** [comment]
Please try https://prerelease.keybase.io/windows/Keybase_1.0.41-20180221184254%2B80361c9.386.exe

**Comment by zanderz** [comment]
We released a fix late last night, can you try it now? Either install the one linked to above or type "upd check" at the CLI. Thanks.

**Comment by bzadoroz** [comment]
Ah yep version 1.0.41-20180221184254+80361c9 fixes the issue. Thanks!
