### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by nhaupt** [keybase/keybase-issues#3187]
Hello,

Since this morning I have no more possibilities to log in from any devices.

Each time I start the windows application, it asks for my password and when I type it, I receive this message : 
![image](https://user-images.githubusercontent.com/36765618/36596263-5be0376c-18a5-11e8-93a2-331f7af0f53d.png)

And on Android, each time I launch the application, it crashs directly.

Do you have any ideas of what the problem could be ? Do you need more informations ?

Thank you in advance.

**Comment by maxtaco** [comment]
Update your android app?

@zanderz can you help fix the broken windows app?

**Comment by nhaupt** [comment]
It seems that I have already the last version (1.0.13).

I have a Google Pixel 2 with Android 8.1

**Comment by maxtaco** [comment]
That version is very very old.

**Comment by nhaupt** [comment]
First, tahnk you for your help. I appreciate your reactivity.

Can you just tell me how can I update my version ? When I go to Play Store, I do not have the button "update", only the button "open".

![image](https://user-images.githubusercontent.com/36765618/36597591-e3de08f2-18a9-11e8-8a6b-cd14f1ff968b.png)

**Comment by maxtaco** [comment]
@cjb / @cnojima do you guys have any ideas?

**Comment by nhaupt** [comment]
Hello !

Yesterday I was able to update both my Android & Windows App and now everything is working fine !
Thank you for your help !
