### ISSUE TITLE
Typo in keybase.pub

### ISSUE THREAD

**Issue by wilsonehusin** [keybase/keybase-issues#3191]
Nothing technical, just little typo of "provably" instead of "probably", probably.

Appears when browsing someone's directory in https://keybase.pub/

![image](https://user-images.githubusercontent.com/14004487/36652699-525727ac-1a7e-11e8-90e3-a620a7c9b273.png)

**Comment by songgao** [comment]
Thanks for the issue. It's not a typo though, but intended to mean you can cryptographically prove the identity, thus prove-able-ly, or provably.

**Comment by wilsonehusin** [comment]
ooh I get it now. sorry for the false alarm!
