### ISSUE TITLE
Cannot reset account

### ISSUE THREAD

**Issue by naturalshine** [keybase/keybase-issues#3193]
My gpg key expired some months ago, and I didn't update/change on keybase. I no longer have a copy of the key. I want do an "Identity Reset" for my account,  but the passphrase that I use to login to keybase isn't working to confirm the reset. I copy/paste my passphrase from a manager, so I don't think this is a PEBCAK. Any idea what's going on? Thanks. 

![screen shot 2018-02-26 at 14 10 08](https://user-images.githubusercontent.com/5373100/36672275-078a1384-1aff-11e8-8e78-38e7ee1b541e.png)
![screen shot 2018-02-26 at 14 10 28](https://user-images.githubusercontent.com/5373100/36672277-07a137b2-1aff-11e8-8a95-eaff6ea9c6d4.png)

**Comment by maxtaco** [comment]
Can you login with that passphrase?

**Comment by naturalshine** [comment]
Yes, that's what's so weird. I can login. I've reset my password a couple of times today, but I've definitely been trying to reset my identity with the appropriate pass. I can always login, but this step fails.

**Comment by naturalshine** [comment]
Ok, I just tried again, and now it's working. Must have been some weird bug, I'm not sure. Closing the issue.
