### ISSUE TITLE
Typo in webpage for a public file.

### ISSUE THREAD

**Issue by ArmandGrillet** [keybase/keybase-issues#3194]
Published [my first public file](https://keybase.pub/armandgrillet/Master_Thesis.pdf) and saw on its webpage:

> Who is also provably:

<img width="214" alt="screen shot 2018-02-27 a 23 11 08" src="https://user-images.githubusercontent.com/2117580/36758064-89ca86d4-1c13-11e8-8dc0-3a9c8cf40994.png">

The `v` of `provably` should be replaced by a `b`.

**Comment by mlsteele** [comment]
Thanks! We definitely appreciate the report. I'll point you to [yesterday's issue](https://github.com/keybase/keybase-issues/issues/3191) :)
