### ISSUE TITLE
Please update the Linux installation instructions for Arch Linux to acknowledge community/kbfs

### ISSUE THREAD

**Issue by eli-schwartz** [keybase/keybase-issues#3196]
https://keybase.io/docs/the_app/install_linux#arch-linux

As I've recently uploaded https://www.archlinux.org/packages/?name=kbfs it would be nice if users were made aware that this exists, rather than explicitly told it doesn't. :smile:

**Comment by oconnor663** [comment]
Sure thing, I'll correct the docs. At the same time, I worry the KBFS experience without the GUI is likely to be very rough. Especially when someone's proofs break for whatever reason, KBFS operations will tend to fail or block forever with no explanation. Normally the GUI would pop something up and give you a way to fix the problem.

**Comment by eli-schwartz** [comment]
That seems like something which users should be able to detect from `keybase status` and the logfiles. Maybe kbfs itself should log directly to stderr as well as the logfile in such a case, and it would be available in the journalctl output?

FWIW my proof hasn't broken in the past, and KBFS operations also haven't broken, so hopefully this shouldn't even matter in the common case!

Anyway, I'm not demanding you advise people to use it, I'm sure you'd prefer to warn people that without the GUI they will not get the full experience. ;)
And I plan to eventually package the GUI as well, but ideally I want to see keybase/client#10546 resolved first...

**Comment by oconnor663** [comment]
There is a magic file called (I think) `.kbfs_error` that can give you info about problems. But it's not really a Smooth And Polished Experience :)

**Comment by oconnor663** [comment]
This'll go up with the next server push.
