### ISSUE TITLE
Getting re-key notification after key reset

### ISSUE THREAD

**Issue by awnumar** [keybase/keybase-issues#3206]
After deleting and starting my account from scratch, the keybase client is giving me a notification that the conversation with myself needs a rekey. Clicking the rekey button however, does nothing.

A possibly related issue is that I received a bunch of emails telling me I had messages but the messages seem to not exist. The emails came after the account reset, and there weren't messages before the reset. Could this all be related to the deletion of the keys?

**Comment by maxtaco** [comment]
There's no way to rekey this conversation now.   I'm not sure what the UI plan is, but maybe we can mark that conversation as busted and be done with it.

cc: @mmaxim

**Comment by awnumar** [comment]
@maxtaco If the conversation is useless at the point of key deletion, it should really just disappear as if it never existed. As should everything else really, like for example I've noticed that I can't repeat device names even across keys.

**Comment by mmaxim** [comment]
You should be able to just create a new conversation with yourself, does that work?

**Comment by awnumar** [comment]
No luck, at least on my android device. Searching myself and then clicking on my name results in the search bar clearing and nothing else happening. I can still search and open chats with other people though.

**Comment by mmaxim** [comment]
Yeah you might need to do it from a desktop machine.

**Comment by awnumar** [comment]
Didn't work from my Linux system either.

![screenshot from 2018-03-13 16-17-34](https://user-images.githubusercontent.com/8942495/37354677-19e5d482-26da-11e8-8358-cfe9d6a423ff.png)

**Comment by mmaxim** [comment]
Try `keybase chat send <username> hi`' from CLI

**Comment by awnumar** [comment]
Yep, that's managed to work. I now have two conversations with myself in the UI though.

**Comment by mmaxim** [comment]
Once you get a release with this https://github.com/keybase/client/pull/10925 you should be back to normal
