### ISSUE TITLE
Can I recover my account without private key and email?

### ISSUE THREAD

**Issue by idealhack** [keybase/keybase-issues#3209]
Hello,

Not sure this is the right place, but I think my problem is similar to #2889, #2190, and #2911.

I'm [idealhack](https://keybase.io/idealhack) on Keybase. I joined in alpha on 6/20/14 and did't use Kyebase much. Recently I decide to tryout the new apps, but I found I have no password nor private key.

I tried to recover account, Keybase says email will be sent when I type in my username, but says no user found when I type in my email. So I guess my email was not associated with this account.

I still have access to my Twitter, GitHub and my website. How can I recover my account?

**Comment by idealhack** [comment]
@maxtaco Sorry to bother, could you help me with this?

**Comment by maxtaco** [comment]
you typo'ed your email address.  Try again with your gmail address, it should work.

**Comment by idealhack** [comment]
Thank you! I may reset my account now

**Comment by Aluanstelling** [comment]
Tenho acesso ao meu email e meu nome de usuário mas preciso redefinir a senha pra entrar na keybase help me please
