### ISSUE TITLE
How to verify followers?

### ISSUE THREAD

**Issue by Kixunil** [keybase/keybase-issues#3212]
Let's assume, I see on the web that A follows B. How do I *cryptographically* verify that using the client?

If I execute `keybase id B`, I see no such information.

**Comment by mlsteele** [comment]
```
# chris follows max.
$ keybase list-following chris | grep "^max$"
max
$ 
```

**Comment by Kixunil** [comment]
Ah, thanks, just to make sure: does it perform cryptographic verification too? It seemed surprisingly fast to me, that's why I'm asking. :)

**Comment by mlsteele** [comment]
Yep, it does! Glad it's fast :)
The follows are all stored on the follower's sigchain. And user sigchains are aggressively cached. So it's usually already done and saved the verification by the time you ask.

**Comment by Kixunil** [comment]
Great! Thanks for explaining!
