### ISSUE TITLE
Cannot list files stored in my team, KBFS on Ubuntu

### ISSUE THREAD

**Issue by dwhagar** [keybase/keybase-issues#3227]
I'm running Ubuntu 16.04 on an old Laptop that I wanted to use processing some files stored in my team's storage on Keybase.  However, the laptop is unable to list files.  Using the `ls` command just stalls out, entirely.  I did just dump several gigs of data from my other computer into the team storage, but my understanding was that the system would only stream data to any particular client accessing it on the fly and not require to download all of it?

Anyway, I'd like some help with figuring this out.

**Comment by strib** [comment]
Logs: 08585f0817eb18d4301c691c

Looking now.

**Comment by strib** [comment]
It seems like the network connection your client established to one of our servers (`bserver-0.kbfs.keybaseapi.com`) is blackholing traffic for some reason -- it appears to be connected, but we're not receiving any of the traffic, and your client is just hanging waiting for responses.

(This is only from looking at your Linux logs.  If you do a `keybase log send` from windows as well I can look at those too, it could be a different issue.)

Maybe it's just a rare random race that happened to you during startup.  On Linux, can you try running `run_keybase` again and seeing if that fixes the problem?  If the behavior remains, maybe there is some issue with your network?

**Comment by dwhagar** [comment]
Does your service block VPN users?  The Linux machine is behind a secure VPN, I know some services block those.  And I will run the same command on my windows machine in a few minutes, to send you the logs.  I have reboot the Linux machine twice, but I will attempt to run the run_keybase command again.

**Comment by strib** [comment]
We don't block VPN users.  But some VPNs do weird things with encrypted traffic that goes through them.

**Comment by dwhagar** [comment]
Well, the Windows machine is not on a VPN, and here is the ID for the logs:  31cde953ae6039eb5e21771c

Still having it unable to list files as well.  I will be attempting from a different network later today, in case it is my local network for some unknown reason.

**Comment by strib** [comment]
Yeah Windows seems to be in a similar situation, where the it's making requests to our block server and never getting an answer back.  I have no clue why.  I'm asking around internally to see if we made any network changes lately, and will update here if I learn anything interesting.

Yes, please try from a different network later today and let me know how it goes.  You said you uploaded a bunch of data successfully from another computer -- was that one on a different network?

**Comment by dwhagar** [comment]
The computer that did the uploads (or said it did) was on the same network as the others for one folder and then a different one for the other.  It can also access all files from any network.  It is a Mac running OSX El Capitan

**Comment by strib** [comment]
Turns out we had an internal DNS misconfiguration since last night.  Things should be working ok now. Does it look better for you?

**Comment by dwhagar** [comment]
It is, however, there is an interesting effect here.  It is uploading from the Mac all the changes that were not uploaded.  I assume this is the journal file.  Is there a way to stop this, since I added, removed, added, deleted, etc...  The directory in question should now be empty.  I will let it finish if that is required, but I'd prefer not to wait for it to resync all the changes.

**Comment by strib** [comment]
In theory we can stop your Keybase, clear out the journal directory manually, and restart it.  If it's important to you, I can help you do that.  But it's easiest just to wait -- the journal has to do things in order, even if you delete things later.

**Comment by dwhagar** [comment]
Nah I'll just let it finished.  Thank you.  I think the issue is closed.
