### ISSUE TITLE
keybase pgp export --secret asks for a passphrase but it doesnt use it

### ISSUE THREAD

**Issue by mcdallas** [keybase/keybase-issues#3237]
When I try `keybase pgp export --secret` it asks for a passphrase to protect the key but no matter what I enter the key is exported in the clear.

**Comment by maxtaco** [comment]
Thanks for the report ---- @zapu can you take a look?

**Comment by maxtaco** [comment]
@mcdallas  which version are you running?

**Comment by zapu** [comment]
@mcdallas I've just tried it on a fresh account and I couldn't confirm. Can you give us more info?

**Comment by mcdallas** [comment]
@zapu Sorry that was me messing up. The key was imported to my keychain without asking for a passphrase but turns out it was already there.
