### ISSUE TITLE
Identify device on OS reinstall

### ISSUE THREAD

**Issue by notlmn** [keybase/keybase-issues#3239]
Whenever I reinstall my OS, Keybase identifies the same computer as a new device, results in having a lot of devices revoked in the sig chain, and having to use a new name for the same device.

Wouldn't it be possible for Keybase to identify a device by its hardware rather than the software, provided another device as identifier or proof?

**Comment by maxtaco** [comment]
No.  Where could we store the private keys?

**Comment by notlmn** [comment]
Correct me if I'm wrong, but can they not be pushed to Keybase with `keybase pgp select`?

Or if a secondary device is used to identify, then copy the private keys over? Am I doing it right?

**Comment by maxtaco** [comment]
See [this post](https://keybase.io/blog/keybase-new-key-model) for how our new key model works.  In short, we want security to be way stronger than a password that someone can remember, so we need full-entropy random keys on each device you use. This works well for 99.99% of our users. In your case, I'd suggest a strategy of just copying out the needed files before you wipe, but I wouldn't suggest that to most users.

**Comment by notlmn** [comment]
For me it's about having to use my private keys on other computers, through Keybase.

Keybase works great for what I want but the only thing that bugs me is it recognizing the same physical computer as a different one on OS reinstall, and having to create a new device and revoke the older ones.

I only wanted a feature in Keybase that lets me do that, without having to create new devices. If it is not possible due to the architecture of Keybase, then its fine for me.

**Comment by notlmn** [comment]
Windows 10 1803 (17134.48)
keybase version 1.0.47-20180507180955+c06519b740
gpg (GnuPG) 2.2.5

**Comment by bbashy** [comment]
This will get very boring, very quickly. New install, new device name, and new item in the list.

Will start looking like https://keybase.io/chris/devices

**Comment by notlmn** [comment]
Well this is getting a little [frustrating](https://keybase.io/lmn/graph) already!

And this time, its a simple reinstall of KB not the complete OS (because KB app shows an update but never applies it for some reason).

**Comment by maxtaco** [comment]
Reinstalling should not require a reprovision of the device.

**Comment by notlmn** [comment]
Had to uninstall KB and remove all folders named `keybase` from the computer, because I was getting any of the following weird errors on `keybase login`.

* `ERROR login failed after passphrase verified`
* `ERROR Failed to load provisional device for user`
* `ERROR no key for <redacted-hash>`

And the KB client app stuck on __loading__ screen, like for more than an hour. So, had no way but to do a clean install (deleting all the folders should simulate this?).

**Comment by bbashy** [comment]
I've given up with keybase.

**Comment by maxtaco** [comment]
I can help debug if you ‘keybase log send’ but it sounds that by deleting
files etc you have pushed the app into an unexpected configuration.

What you guys are describing is 100% not the intended behavior. It is
definitely a bug. But it’s not a common bug or one that I have ever
reproduced. Believe it or not we spend an immense amount of effort on
exactly this flow: login and provisioning. There is a lot going on here
under the covers but it is our intent for it to work smoothly in all cases
(and there about 23 that we focus on).

Anyways if you want to ‘keybase log send’ I can spend some time combing
through the ashes.

**Comment by notlmn** [comment]
@maxtaco I believe you people are doing an amazing job at Keybase, FYI I still love it.

Just forget about the scenario where I deleted all the files, and focus on the OS re-installation part.

After login KB should _somehow_ recognize that I already have this physical machine in my device list and not think of it as a different machine on which I have never logged into and stop re-provisioning!

This whole re-provisioning process is just tiresome, the users graph becomes very large, and you'd run out of names for your PC!

Imaging people who use beta builds of Windows (or any OS) and switch (reinstall) very frequently.

**Comment by maxtaco** [comment]
Here is what “provisioning” means and what it must mean, more or less from
a cryptographic perespective: We place two very important files in your
settings directory.  One with your encrypted keys and one with your
configuration.  If you blow one or both of those files away, your device is
gone and there is nothing we can do to help.  This much is never going to
change. If your device appeared not to be provisioned but your settings
files are intact, then it’s a bug.

In 99.9% of these cases, the cause is that the user deleted these key files
either due to an os reinstall or housekeeping or something

Our security achitecture demands users store keys on local devices in such
a way that the server has no knowledge of the private keys.  Read our docs
for more details.

**Comment by rithvikvibhu** [comment]
As someone who clean installs Windows often (about once every 2 months), is there any way to copy these keys and config files, reinstall Keybase and avoid polluting the chain?

**Comment by junderw** [comment]
Yes. There is a way to backup those files. Basically, Keybase looks for those mpack files in those locations for the username you're trying to login with. If it doesn't exist, re-provision as new device.

```
* On Windows: C:\Users\YOURWINDOWSUSERNAME\AppData\Keybase\KEYBASEUSERNAME.mpack
* On Linux: $XDG_CONFIG_HOME/.config/keybase/secretkeys.$USER.mpack
* On OSX: $HOME/Library/Application\ Support/Keybase/secretkeys.$USER.mpack
```

**Comment by rithvikvibhu** [comment]
I see. Will try it out soon. Thanks @junderw!

**Comment by andrewrynhard** [comment]
@junderw Any idea which files for MacOS?

**Comment by notlmn** [comment]
@andrewrynhard I know the Keybase authors (or any cryptographer for that matter) won't like this way of moving files, but you should be able to search for `$USER.mpack` file using Spotlight or some other app.

**Comment by junderw** [comment]
> @junderw Any idea which files for MacOS?

Like I said:

```
* On OSX: $HOME/Library/Application\ Support/Keybase/secretkeys.$USER.mpack
```

**Comment by Destroyer** [comment]
I'm assuming the correct Windows path is 

    C:\Users\%USERNAME%\AppData\Local\Keybase\secretkeys.KEYBASEUSERNAME.mpack

as this is the only mpack file i was able to find

**Comment by rithvikvibhu** [comment]
That's the one.

**Comment by espoelstra** [comment]
Just a note for Linux, the `.config/` in the path is redundant, the `$XDG_CONFIG_HOME` already includes that directory as part of the path. I discovered this while trying to do `ls $XDG_CONFIG_HOME/.config/keybase/secretkeys.$USER.mpack` and getting an error with `.config/.config/` appearing in the path that was "missing".

So `$XDG_CONFIG_HOME/keybase/secretkeys.$USER.mpack` is the correct path if you are backing things up.

**Comment by mgokoffski** [comment]
Uninstall and reinstall keybase- terminal shows "Disconnected".  How can I reinstall it?

**Comment by notlmn** [comment]
Strictly speaking, this should not be done/possible. But I'm sure I can live the ever expanding device tree for now.
