### ISSUE TITLE
Can't reset my account

### ISSUE THREAD

**Issue by RyanZim** [keybase/keybase-issues#3247]
I stupidly messed up with my password manager, trying to set up my keybase account for the first time, and lost my password before I could login in the app. I've attempted to reset my account on the website, but I don't receive any reset email link. My keybase username is `ryanzim`.

**Comment by RyanZim** [comment]
@maxtaco ping?

**Comment by maxtaco** [comment]
send me an email at max@keybase.io

**Comment by RyanZim** [comment]
Resolved via email.
