### ISSUE TITLE
Can't add a new device using a desktop app

### ISSUE THREAD

**Issue by kenorb** [keybase/keybase-issues#3249]
I've got Keybase app on macOS. I had the suggestion to install Keybase on my phone.

I've installed Keybase on my iPhone (iOS) and I'm instructed to _Scan QR code_ by going to _Devices -> Add a new device_, however in my desktop app I don't see such menu.

On macOS app there is only Edit, Window and Help. I'm using Keybase Version 2.0.0

![img_7123](https://user-images.githubusercontent.com/266306/41107200-c12ee2ce-6a69-11e8-9f2c-fbe817556685.PNG)

**Comment by plttn** [comment]
On the blue bar on the left, the fifth icon down is the devices menu.

**Comment by kenorb** [comment]
Thanks, seems right, I thought it meant the _menu_.
