### ISSUE TITLE
Can't run after install in Linux Mint («/run/user/1000»: Permission denied)

### ISSUE THREAD

**Issue by dropestein** [keybase/keybase-issues#3254]
Hi! I'm having this problem and I couldn't find anything with Google about it. I don't know if this is a problem with keybase or something I'm doing wrong:

I'm following the instructions in https://keybase.io/docs/the_app/install_linux

This is what I get:

```
drope@drope-Lenovo-ideapad-310-14ISK ~ $ curl -O https://prerelease.keybase.io/keybase_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82.8M  100 82.8M    0     0  10.0M      0  0:00:08  0:00:08 --:--:-- 12.8M
```

```
drope@drope-Lenovo-ideapad-310-14ISK ~ $ sudo dpkg -i keybase_amd64.deb
Seleccionando el paquete keybase previamente no seleccionado.
(Leyendo la base de datos ... 280155 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar keybase_amd64.deb ...
Desempaquetando keybase (2.1.0-20180615162035.8625b772b1) ...
Configurando keybase (2.1.0-20180615162035.8625b772b1) ...
Procesando disparadores para gnome-menus (3.13.3-6ubuntu3.1) ...
Procesando disparadores para desktop-file-utils (0.22+linuxmint1) ...
Procesando disparadores para mime-support (3.59ubuntu1) ...
Procesando disparadores para hicolor-icon-theme (0.15-0ubuntu1) ...
```

```
drope@drope-Lenovo-ideapad-310-14ISK ~ $ sudo apt-get install -f
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 30 no actualizados.
```

```
drope@drope-Lenovo-ideapad-310-14ISK ~ $ run_keybase
Shutting down keybase service...
mkdir: no se puede crear el directorio «/run/user/1000»: Permiso denegado
```
I'm sorry for the language. The last message says that it can't create the directory and then it says "Permission denied"

Any ideas? If you need any other information, just tell me, please.

Thanks!

**Comment by junderw** [comment]
FYI you can preface your commands with LANG=EN and any messages from the command will come out in english.

**Comment by junderw** [comment]
My PC is in Japanese, so 
```
$ ls /tmp/sdghghdfhdfghdfhd/
ls: ディレクトリ '/tmp/sdghghdfhdfghdfhd/' を開くことが出来ません: 許可がありません

$ LANG=EN ls /tmp/sdghghdfhdfghdfhd/
ls: cannot open directory '/tmp/sdghghdfhdfghdfhd/': Permission denied
```

**Comment by dropestein** [comment]
Hi, junderw
Thanks for the sugestion! I didn't knew about that option. But... it didn't work :( 

```
LANG=en_US.UTF-8 sudo dpkg -i keybase_amd64.deb
[sudo] password for drope: 
Seleccionando el paquete keybase previamente no seleccionado.
(Leyendo la base de datos ... 280155 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar keybase_amd64.deb ...
Desempaquetando keybase (2.1.0-20180615162035.8625b772b1) ...
Configurando keybase (2.1.0-20180615162035.8625b772b1) ...
Procesando disparadores para gnome-menus (3.13.3-6ubuntu3.1) ...
Procesando disparadores para desktop-file-utils (0.22+linuxmint1) ...
Procesando disparadores para mime-support (3.59ubuntu1) ...
Procesando disparadores para hicolor-icon-theme (0.15-0ubuntu1) ...
```

**Comment by strib** [comment]
@dropestein we look up what directory to create a runtime subdirectory using the `$XDG_RUNTIME_DIR` environment variable.  In your case, it appears to be set to `/run/user/1000`, but that directory isn't set.  This is probably a problem with your configuration or distro, or maybe you are inheriting that variable from some other user you've su'd from?  Not really sure.  But either making that directory as root and chmod'ing it to the right user, or unsetting that environment variable, should work.

**Comment by dropestein** [comment]
That is exactly de problem, it seems. I'm logged in as my secondary user (non administrator) and first y used "su - drope" in the terminal ("drope" is my admin account). I just tried to do this using my admin account and it worked. And now I checked the `/run/user/1000` folder and, yes, it was property of my admin user.

First I tried just chmod'ing the "1000" folder, but it didn't work (it said thet some files "already existed" within the keybase folder). So I did the most reasonable and civilized thing I could think of: just removed the keybase folder completely :D... and now it works.

**Comment by zeph** [comment]
any follow up on this? having the same issue on `Devuan/Ceres` aka `Debian/Sid` Unstable 
`ii  keybase                                                     2.11.0-20181115195458.06d3f3f3c4      amd64        Keybase's command line client
`

**Comment by mambrus** [comment]
With the hint's here I managed to solve my case.

Scenario:

* A previously running installation stopped running. Keybase silently refuses to start.
* Staring using `run_keybase` from command-line tells me why. The same error message as in this issue i.e.
* The environment variable `$XDG_RUNTIME_DIR` mentioned by @strib *is* set, but contains a different directory than `keybase` tries to access.

This led me to believe that albeit `$XDG_RUNTIME_DIR` is used during during first time run on each new host/account, it's *not* used for consecutive runs. Trying out the hypothesis I did the following:

```bash
cd ~/.config
vim $(grep -r "/run/user/1001" * | \
   grep keybase | cut -f1 -d":" | uniq)
```
Using `vim`-scripting for each file, changing the directory to the correct one as follows:
`:% s/\/run\/user\/1001\/keybase\/kbfs/\/run\/user\/1000\/keybase\/kbfs/g`

In my case only two files needed editing. The one used only by keybase manually would probably be enough, i.e.:

* `~/.config/keybase/config.json`

Directories to suspect of keeping configurations/states are the ones used by your Desktop environment (in my case, vanilla `Ubuntu 18.04` out-of-the- box):
* `~/.config`
* `~/.cache`
* `~/.gconf`
* `~/.gnome`

The "right way" _(tm)_ would probably be to reinstall `Keybase`, but what would be the fun in that :-P _(Possible re-proofing e.t.c.? Maybe only/last device still connected to account?)_  

Hopefully this leads to some improvement as issue will surely re-occur when users manage/move their accounts `$HOME` directories around (for one reason or another), get their `UID` changed e.t.c.

Note to fellow users: If bold enough to follow these steps, **remember to backup directories first**.

**Comment by strib** [comment]
Thanks for the write-up!  I think the right way is to run `keybase config set mountdir` when you change your `$XDG_RUNTIME_DIR` or UID, or possibly for Keybase to notice that it has changed and do Something Smart.  But not sure when we'll get to that.

**Comment by zeph** [comment]
guys... still nothing... this is at every boot what I have to do...
gms@hagrid:~$ sudo mkdir /run/user/1000
gms@hagrid:~$ sudo chown gms:gms /run/user/1000/
gms@hagrid:~$ env KEYBASE_AUTOSTART=1 run_keybase
Shutting down keybase service...
Launching keybase service...
Mounting the file system...
Launching Keybase GUI...
Success!
```

**Comment by strib** [comment]
@zeph if your system isn't configured to create your runtime dir at startup, you should change the mountpoint to something that always exists, with "keybase" in the name.  Like this:

```sh
mkdir $HOME/keybase
keybase config set mountdir $HOME/keybase
run_keybase
```

It will still be available at `/keybase`.

**Comment by zeph** [comment]
@strib yeah that worked... but does it fix it for whoever does not have that path? i mean, I bet that is systemd related... i don't use a systemd based distro

**Comment by ziez456** [comment]
This fixed it for me

`sudo -u ""user"" bash`

**Comment by heronhaye** [comment]
We should have better logic for detecting if the systemd user manager is supported now, so that these workarounds shouldn't be necessary. Please make a new issue if you still have problems. Thanks!
