### ISSUE TITLE
Error provisioning while logging in

### ISSUE THREAD

**Issue by notlmn** [keybase/keybase-issues#3264]
![image](https://user-images.githubusercontent.com/37769974/42736734-becacd6c-8888-11e8-8930-5b6455313ece.png)

The device is already provisioned, but it auto logged out, and shows this error on login.

Happens the same if tried to login from console.

![image](https://user-images.githubusercontent.com/37769974/42736783-5e1521d8-8889-11e8-9c65-e2b19a2d11fa.png)

log id: `6256648a32ac043e0901af1c`

**Comment by maxtaco** [comment]
Here's the root problem:

```
Loaded SKB keyring: C:\Users\<your local username>\AppData\Local\Keybase\secretkeys.lmn.mpack -> ERROR: open C:\Users\<your local username>\AppData\Local\Keybase\secretkeys.lmn.mpack: The system cannot find the file specified
```

Your secret keyring cannot be found on your computer.  The file appears to be removed.  Did you clean out any data or manually remove this file?

**Comment by notlmn** [comment]
No I haven't touched any of Keybase files, I haven't even opened KB in a while.

The only thing I can remember doing is selecting to apply update for KB, which I think it never did!

**Comment by maxtaco** [comment]
@zanders any theories as to how that file might have disappeared?

**Comment by maxtaco** [comment]
@zanderz I meant!

**Comment by notlmn** [comment]
This just happened __again__.

It looks the files are removed on exit.

Log id: `4ed722085168e061f3b7981c`

**Comment by maxtaco** [comment]
weird, no one else has this complaint

**Comment by maxtaco** [comment]
Our app is certainly not removing those files, on exit, or at any other time. That would be madness from our perspective.  My guess that something else on your system is deleting it.  Anti-virus maybe?

You'd only notice it after a restart, since those keys are loaded into memory on app startup. It does not imply that they are deleted on exit, as you say.

**Comment by notlmn** [comment]
@maxtaco Can confirm that Keybase is deleting `secretkeys.$USER.mpack` file on opening the application.

And during this time if I copy the file into Keybase directory just before it reads the file, I managed to log back in.

And after a brief period of time, the file is deleted again 🤷‍♀️ (i'm still logged into Keybase app though). And you have to repeat the same cycle over again to log into the application.

The logs are not that helpful though, there is not line that points to deleting that file, but I've manually seen the file being deleted on opening Keybase.

`ea256c11ed423f297ef1661c` is the log id, if you want to dig into it. And I want to also say that this happens to me, and I haven't tested it on other Windows systems, the files are not deleted on Ubuntu though.

**Comment by maxtaco** [comment]
This still would be shocking to me. This is literally the only report of
this behavior.

**Comment by maxtaco** [comment]
@notlmn how did you conclude that our app is deleting that file, and not something else on your system?  My best guess is still that some other software on your computer is doing this.

**Comment by maxtaco** [comment]
Sure, that would be helpful. @zanderz can you take a look?

**Comment by zanderz** [comment]
It would be far more informative to get a [process monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) log. For example, mine shows Keybase opening the .mpack file read only and not writing or deleting it at startup.
![procexp_kb](https://user-images.githubusercontent.com/862397/47658761-c6901c80-db50-11e8-8d7d-45ebed256ec2.png)

**Comment by notlmn** [comment]
![image](https://user-images.githubusercontent.com/37769974/47660116-5c14c600-dbbc-11e8-8b83-0a639349eb17.png)

KD does actually delete the file for me (according to process monitor at least, look at the detail column)

---------------------

And if you want visual proof, here is the [YT link](https://youtu.be/SdgsyUPhpJo) (_Use CC for detailed info_)

**Comment by notlmn** [comment]
## Event properties
### Event
![image](https://user-images.githubusercontent.com/37769974/47660422-f70da000-dbbc-11e8-8e39-b52070e3651d.png)

### Process
![image](https://user-images.githubusercontent.com/37769974/47660465-0ee52400-dbbd-11e8-9b98-9414677a1f1e.png)


### Stack
![image](https://user-images.githubusercontent.com/37769974/47660396-ea894780-dbbc-11e8-90d8-363394a0e88e.png)

**Comment by zanderz** [comment]
Wow, thanks, that seems pretty conclusive. Can you do another log send so we can match with these screenshots?

**Comment by notlmn** [comment]
Sure, here you go: `6fdea44510e77453b3fce61c`

### Process Monitor log in CSV format
_Filtered on "Process Name" and "Path"_
```
"Time of Day","Process Name","PID","Operation","Path","Result","Detail"
"8:46:59.8689589 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"8:46:59.8690721 PM","keybase.exe","12860","QueryNetworkOpenInformationFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS","CreationTime: 2018-10-29 8:17:47 PM, LastAccessTime: 2018-10-29 8:17:51 PM, LastWriteTime: 2018-10-27 10:31:08 AM, ChangeTime: 2018-10-27 10:31:08 AM, AllocationSize: 1601-01-01 5:30:00 AM, EndOfFile: 1601-01-01 5:30:00 AM, FileAttributes: A"
"8:46:59.8690926 PM","keybase.exe","12860","CloseFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS",""
"8:46:59.8693310 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS","Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"8:46:59.8694726 PM","keybase.exe","12860","QueryAttributeTagFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS","Attributes: A, ReparseTag: 0x0"
"8:46:59.8695090 PM","keybase.exe","12860","SetDispositionInformationFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS","Delete: True"
"8:46:59.8695506 PM","keybase.exe","12860","CloseFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","SUCCESS",""
"8:47:01.2099867 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a"
"8:47:01.2104247 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"8:47:01.2140474 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a"
"8:47:01.2145128 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"8:47:02.9525583 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a"
"8:47:02.9528962 PM","keybase.exe","12860","CreateFile","C:\Users\ramlmn\AppData\Local\Keybase\secretkeys.lmn.mpack","NAME NOT FOUND","Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
```

**Comment by maxtaco** [comment]
I'm not so sure it's conclusive. @chrisnojima asks if this is the version of Windows that's incorrectly deleting files?  Also, for my benefit, which is the line that shows a delete happened?  I'm not sure about windows, but the way this works on Linux and macOS, if process `foo` opens `hi.txt`, then process `bar` deletes that file, the file will persist until `foo` exits.  This might be at play too.

**Comment by maxtaco** [comment]
And again, if this is our bug, it's a very very bad one that should be breaking lots of Keybase installs, and this is literally the only complaint we've had.

**Comment by chrisnojima** [comment]
can you try safe mode?

**Comment by zanderz** [comment]
Do you have any .exe or .mpack files in `%appdata%\Keybase`? A long time ago that was the default location for such files, but we switched it to `%localappdata%\Keybase`, and it is possible that the migration facility has a bug causing your problem.

**Comment by notlmn** [comment]
> And again, if this is our bug, it's a very very bad one that should be breaking lots of Keybase installs, and this is literally the only complaint we've had.

@maxtaco I understand that my case is the only one reporting this issue.

I'm not exactly a reverse engineer (not even close), but according to process monitor the delete operation was issued from Keybase binary itself.

It may be because there _might_ be some code in KB that checks if the file was created y KB itself, if even that was true, it should not delete the file in the relaunch too. 🤷‍♀️

-------------

@zanderz As mentioned in https://github.com/keybase/keybase-issues/issues/3239#issuecomment-403907869, I've been trying a clean install for each Keybase version release, so as this is the recent release, `%APPDATA%\Keybase` doesn't even exist, only `%APPDATA\Local\Keybase` exists.

_(Except for any registry values, at some point I event tried removing every registry value that says "Keybase")_

**Comment by zanderz** [comment]
What is your environment variable `APPDATA` set to? Usually it is something like `%USERPROFILE%\AppData\Roaming`. We seem to be making some assumptions about it that may not hold for you.

**Comment by notlmn** [comment]
As you can see it in the logs, I haven't changed the default variables
- `USERPROFILE -> C:\Users\ramlmn\AppData`
- `APPDATA -> C:\Users\ramlmn\AppData\Local`
- `LOCALAPPDATA -> C:\Users\ramlmn\AppData\Local`

`APPDATA` and `LOCALAPPDATA` are the same, and I have verified using Everything that no other directory exists on the file system named "Keybase" except for in `%APPDATA%`.

**Comment by zanderz** [comment]
Having APPDATA and LOCALAPPDATA set the same revealed a bug in our upgrading mechanism. APPDATA normally points to Roaming, not Local. We'll have a fix shortly.
Tracked internally with DESKTOP-8271

**Comment by zanderz** [comment]
@notlmn A preliminary version that should fix your issue can be found at https://prerelease.keybase.io/windows/Keybase_2.9.0-20181030071943%2B67297efb55.amd64.msi
This fix will be in a future release.

**Comment by notlmn** [comment]
This looks pretty stable now, thanks to everyone at Keybase. 🍻
