### ISSUE TITLE
Cannot recover deleted account

### ISSUE THREAD

**Issue by nynhex** [keybase/keybase-issues#3271]
I had deleted my account by mistake, looked for ways to recover it, no dice.  Sent and email to Max and asked to reset.  Yet I still cannot create a new account in KB client or even recover from the command line:

```
Your keybase username or email address: nynhex
▶ ERROR user "5b9c6dc5a3e86b4602ad62c4116ad019" deleted
```

**Comment by maxtaco** [comment]
deletes are forever, we warn you about this in bold scary letters.
