### ISSUE TITLE
Question regarding Keybase Passphrases

### ISSUE THREAD

**Issue by nambrot** [keybase/keybase-issues#3274]
Hey y'all,

I think I forgot my keybase passphrase. I understand that Keybase has a means of recovering my account if I still am logged in in at least one device (which luckily is the case), by updating a server mask with a new passphrase. However, I'm also reading https://keybase.io/docs/crypto/local-key-security, and I'm not entirely sure how that works since I am using exclusively OSX devices (macbooks and an iPhone). My interpretation of the docs would be that for these devices, you are not actually using the server-side mask that can update the keybase passphrase without knowing it. Do I actually have the means of effectively asserting control over my account with forgetting my passphrase?

**Comment by maxtaco** [comment]
It's not in that doc, but we also encrypt the client-half of your local-key-security for all of your devices during [device](https://github.com/keybase/client/blob/3055ff8f5d6196b8c95c16c693a5b0d7dd943b93/go/engine/kex2_provisionee.go#L565) [provisioning](https://github.com/keybase/client/blob/3055ff8f5d6196b8c95c16c693a5b0d7dd943b93/go/engine/device_keygen.go#L330). So if you have an unlocked device (or a paper key), you can recover that part of the key without knowing your passphrase.

**Comment by nambrot** [comment]
Thanks for your prompt response! If I understand correctly then, the recovery of my passphrase by resetting the passphrase and re-encryption of the client half of my local keys should effectively give me 100% control again, even if I'm logged out of my devices?

**Comment by maxtaco** [comment]
Yes, it should. But it requires one device key to be unlocked, so either one device that's online and logged in, or a paper key.

**Comment by nambrot** [comment]
Got it, just initiated the recovery! Thanks for your quick responses! A big fan, would love to catch a coffee/beer with y'all at some point!
