### ISSUE TITLE
DNSSEC and why it's not used for a trust platform's domain.

### ISSUE THREAD

**Issue by Leopere** [keybase/keybase-issues#3286]
![image](https://i.imgur.com/G5eMOcL.png)
Any idea why keybase isn't using DNSSEC to certify that DNS paths are accurate?  I realise that its not a 100% assertion of accurate connection with absolutely no chance of a MITM but still should see if you can't get that enabled.

**Comment by RogueScholar** [comment]
I've encountered this issue as a result of enabling DNSSEC validation on my system's DNS resolver. While I understand the fault was a result of a configuration change I made directly and thus constitutes an edge case, I'd like to think that DNSSEC is now a mature enough function of IP network traffic such that it warrants the time needed to implement on services like Keybase. Included are my environment details to assist in reproduction and debugging.

Hardware: Lenovo ThinkPad T420s (Intel Core i7 (2nd Gen.), 8GB RAM, 500GB SSD, 1000TX Ethernet)
Operating System: Kubuntu 18.10 "Cosmic Cuttlefish"
Network subsystem: systemd-networkd
DNS Resolver: systemd-resolved
Upstream DNS servers: Cloudflare (1.1.1.1/1.0.0.1)

```
$ systemd-resolve api-0.core.keybaseapi.com
resolve call failed: DNSSEC validation failed: failed-auxiliary
```

```
$ systemd-resolve core.keybaseapi.com
resolve call failed: 'core.keybaseapi.com' does not have any RR of the requested type
```

```
$ systemd-resolve keybaseapi.com
resolve call failed: 'keybaseapi.com' does not have any RR of the requested type
```

```
$ host -t dnskey api-0.core.keybaseapi.com 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53

api-0.core.keybaseapi.com has no DNSKEY record
```
