### ISSUE TITLE
Cannot log in; can my account be reset?

### ISSUE THREAD

**Issue by msvetkin** [keybase/keybase-issues#3288]
Hi,

I can not login or reset account after reopen application.

I tried to recovery password, but I had such error:

keybase passphrase recover
▶ ERROR No paper keys available

Can you reset my account?

**Comment by ahplummer** [comment]
Did you ever get this resolved?  I'm in this weird loop also.  
* Password is invalid
* Attempt to reset password
* Instructed to `keybase passphrase recover` 
* When doing that, some error `ERROR No paper keys available`
* Sent email to max@keybase.io
User is `ahplummer`

**Comment by msvetkin** [comment]
I sent an email and my account has been reset

**Comment by ahplummer** [comment]
Mine also.  Thanks Max!
