### ISSUE TITLE
ERROR CODE 501 - DB error in simpleFSStat

### ISSUE THREAD

**Issue by nealmcb** [keybase/keybase-issues#3295]
After setting up a team and a git repo, and then opening the gui app and going to Files/team, I got this error

> Error: ERROR CODE 501 - DB error in method keybase.1.SimpleFS.simpleFSStat at new s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:431706) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:432235 at d (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:432274) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:422753) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2890952 at e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2449101) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2449252 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2448881) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2449211) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2448415)

Running keybase version 2.8.0-20181023124437+06221a8264 on Ubuntu 18.04 LTS

**Comment by strib** [comment]
@nealmcb If you do a `keybase log send`, and post the resulting ID here, one of us can take a look.

**Comment by nealmcb** [comment]
Success! Your log ID is: 1ed9a37c0bfa6ea58b396e1c

**Comment by strib** [comment]
^ @maxtaco this error is coming from the API server, see for example this tag in the log: `SFSID=ebL7Mt9ufIxRXiMxjT4o7A`.

```
2018-10-31T12:40:53.133547-06:00 ▶ [DEBU keybase api.go:867] 754 - API call sig/multi error: DB error (error 501) [tags:SFSID=ebL7Mt9ufIxRXiMxjT4o7A,API=VDnS2uj5UXls]
```

**Comment by maxtaco** [comment]
we'll file a ticket, i don't know

**Comment by strib** [comment]
@nealmcb After some internal investigation (thanks @zapu!), we think this was a transient error that we shouldn't have shown you, but under the covers everything is correct now, so you shouldn't have issues going forward.  If there are still problems, please let us know!

**Comment by nealmcb** [comment]
It hasn't recurred, when I do the same thing. So I think you're right.
Thanks for the fast, easy, powerful bug review process!
