### ISSUE TITLE
XDG Base Directory Specification is not respected on GNU/Linux

### ISSUE THREAD

**Issue by azahi** [keybase/keybase-issues#3296]
It would be really nice for Keybase to respect freedesktop's [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)

For example, my XDG_CACHE_HOME is located on tmpfs but Keybase client creates ``~/.cache`` directory every time I use it.

**Comment by maxtaco** [comment]
This could be a regression, we do try to follow is.  Are you sure you're setting this variable before you start the keybase *service*?

**Comment by azahi** [comment]
@maxtaco 
Yes, I do have it declared in both shell and ``user-dirs.dirs``

Tried testing it with manually setting ``Environment=XDG_CACHE_HOME=/tmp/cache`` in the service file but ``~/.cache/keybase/keybase.service.log`` is still created.

**Comment by cjb** [comment]
@azahi That's surprising -- if you look at `run_keybase`, you can see it does:
```
start_background() {
  export KEYBASE_RUN_MODE="${KEYBASE_RUN_MODE:-prod}"
  export KEYBASE_DEBUG=1
  logdir="${XDG_CACHE_HOME:-$HOME/.cache}/keybase"
  mkdir -p "$logdir"
```
I wonder where it's getting lost.

**Comment by heronhaye** [comment]
@azahi Are you using systemd?

**Comment by azahi** [comment]
@heronhaye Yes.

**Comment by heronhaye** [comment]
@azahi I have fixes for `XDG_CACHE_HOME` and `XDG_DOWNLOAD_DIR` (for the gui). Were there more you noticed Keybase isn't respecting?
