### ISSUE TITLE
How do you feel about organizations signing up for a keybase.io account?

### ISSUE THREAD

**Issue by egrim** [keybase/keybase-issues#330]
Should I create a keybase account for my company?  Is there precedent for this?  Is it a good idea?

**Comment by tjfwalker** [comment]
> - inviting/revoking memberships (basically admins)
> - signing things on behalf of the organization
> - changing the organization key(s)
> - etc.

@malgorithms 2014 to (nearly) '18... been a while. What's the word here; is this stuff in the pipeline and, if so, is there an eta for it?
