### ISSUE TITLE
Keybase Pages serves .wasm files with an incorrect MIME type

### ISSUE THREAD

**Issue by Limeth** [keybase/keybase-issues#3324]
Hello, I'm using the Keybase Pages feature and I've ran into an issue. WebAssembly is an alternative to JavaScript and it requires the MIME type to be `application/wasm` to be directly executable, but it doesn't seem to be specified that way in the service that serves the files. See the link below for details.

https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#web-server-setup

The website with the issue is https://metaview.link/limeth, opening the browser console reveals the error.
(Don't get alarmed by the "WebAssembly not enabled." message, as that message is displayed when the WASM script isn't executed.)

Best regards.

**Comment by Limeth** [comment]
Any updates on this? It has been over two weeks and it seems like an easy thing to fix. :)

**Comment by maxtaco** [comment]
CC @songgao

**Comment by songgao** [comment]
@Limeth Sorry this slipped through. Will get it done today.

**Comment by songgao** [comment]
@Limeth OK it should give `application/wasm` for `.wasm` files now; let me know if it's still having issues!
