### ISSUE TITLE
keybase session ends after a while: working as intended?

### ISSUE THREAD

**Issue by sowbug** [keybase/keybase-issues#3325]
Ubuntu 18.04, x86 server running at home. I had an idea to do a [grandfather-father-son backup rotation](https://en.wikipedia.org/wiki/Backup_rotation_scheme) on an archive that I periodically store in my keybase directory. So I installed Keybase on the server, provisioned it, and then wrote a short cron job, running as me, that tries to do a daily rotation of `/keybase/private/sowbug/somedir` using [rotate-backups](https://pypi.org/project/rotate-backups/). It works great if I test it interactively or on a fast testing schedule, but the next day, when I check it, I see that the session is ended:

```
$ keybase status
Username:      sowbug
Logged in:     no
```

and more critically, KBFS isn't available anymore:

```
$ ls -l /keybase/private/sowbug
ls: cannot access '/keybase/private/sowbug': Permission denied
```

I can't tell whether this is working as intended. I know that on all the desktop machines I use, I stay logged into Keybase for months and months continuously, even if I restart or shut down a machine (suggesting that the login token is persistent). Why does this Ubuntu server behave differently from desktop machines?

**Comment by mlsteele** [comment]
It is supposed to stay logged in. Could you run ‘keybase log send’ and reply here with the log ID?

**Comment by sowbug** [comment]
d75644af9f9911418a80e61c. Let me know if you need anything else.

**Comment by sowbug** [comment]
Noticed this on an interactive terminal:

```
$ logout
▶ WARNING fixHeaders: session required, but error getting sessionArgs: Login required: no sessionArgs available since no login path worked [tags:FBOID=xxx,RSLV=xxx,API=xxx]
```

Did another `log send` in case it's interesting: 5756304e31681785e4ffab1c

**Comment by mlsteele** [comment]
Thanks that's is interesting. I see a bunch of `no space left on device` errors. Could be that Keybase can't write its login state if there's no space.

**Comment by sowbug** [comment]
Another issue reporting the same error message under apparently different conditions: https://github.com/keybase/client/issues/12876 I don't recognize anything helpful there.

And a casual browse of [the source code likely responsible for the message](https://github.com/keybase/kbfs/blob/master/vendor/github.com/keybase/client/go/libkb/api.go#L506) doesn't give me a hint what might be happening.

**Comment by mlsteele** [comment]
You're right those errors stopped a couple days ago. Latest is from `2019-01-08T06:18:07.596437Z`.

Does `keybase login` work?

**Comment by sowbug** [comment]
It does, and I was about to tell you that the problem happens every time I sign back out again, but on the Nth time I did it just now, the behavior was different.

- Consistent: signing out and signing back in again on the terminal ends up with a `Logged in:     no` on `keybase status`.

- Inconsistent: seeing the `fixHeaders` message spat out just as I'm signing out of the terminal. (sorry this is confusing, I'm using "of the terminal" to disambiguate ending my ssh session from the original problem of Keybase's session dying.)

- Inconsistent: the actual error message I see when doing an `ls -l /keybase/private/sowbug`. It seems to be correlated, though, with whether I saw `fixHeaders`. If I saw it, then the next sign-in says `ls: cannot access '/keybase/private/sowbug': Permission denied`. But if I didn't see it, then on next sign-in it's `ls: cannot access '/keybase/private/sowbug': Input/output error`. Using my powers of guessing, I wonder whether Keybase is trying to clean up on ssh session end, and whether it manages to print the error determines whether it cleanly set permissions on `/keybase` to give me a somewhat meaningful message when I try to access it (permission denied), or else got interrupted during cleanup, leaving us with an ickier i/o error.

**Comment by sowbug** [comment]
This was my fault! I'd written a defensive script in .bash_logout long ago that signed out of Keybase if the user was ending an ssh session. Then that script got copied through the miracle of automation to the new server. So yes, this absolutely was working as intended. Sorry for the wasted time!
