### ISSUE TITLE
[feature] dark theme for desktop app

### ISSUE THREAD

**Issue by ReK2Fernandez** [keybase/keybase-issues#3334]
Please for the love of ...<enter> add a dark theme to the desktop app before we all go blind :) :shipit:

**Comment by orgcontrib** [comment]
+1👍 A dark theme should be available for all apps/clients (desktop & mobile).

**Comment by VanillaScent** [comment]
Typing this while my eyes are hurting,
please add dark mode i promise we'll love you senpai

**Comment by Oxymoron290** [comment]
I agree, a dark theme is needed.
https://github.com/keybase/client/issues/7447

**Comment by HasEPhenix** [comment]
please add a dark mode. It would make my and others experience much better. Thanks!

**Comment by 00011100** [comment]
The white light is murdering my eyeballs. Please consider making this a thing!

**Comment by livejamie** [comment]
Should be a priority

**Comment by lazee** [comment]
https://keybase.io/jobs#frontend-dev :)

**Comment by shawnim** [comment]
As a visually impaired user, a dark theme and particularly one with high contrast between light text and dark background would be most helpful. A pointer to a config file where colors could be edited would also be useful. FYI, I am on the Linux desktop client. Thanks!

**Comment by leumasme** [comment]
how is this not a thing

**Comment by rebane2001** [comment]
I think the stellar airdrop thing they're doing is just them giving everyone $20 to shut up about the whole dark theme thing

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.

**Comment by glassdimly** [comment]
Released: https://github.com/keybase/client/issues/10016#issuecomment-540715543

**Comment by Oxymoron290** [comment]
Awesome!

**Comment by shawnim** [comment]
Thanks! This makes keybase much more usable for me.
