### ISSUE TITLE
Installing on Ubuntu yields an error calling for "--output <FILE>"

### ISSUE THREAD

**Issue by BradyDale** [keybase/keybase-issues#3338]
Following the instructions here:
https://keybase.io/docs/the_app/install_linux

On Ubuntu using an ASUS laptop. When I run the first commmand tho I get:

> Warning: Binary output can mess up your terminal. Use "--output -" to tell 
> Warning: curl to output it to your terminal anyway, or consider "--output 
> Warning: <FILE>" to save to a file.

I tried just adding "--output" to the end but it wanted me to designate a location. 

So I just typed in the path for my downloads folder and it worked from there.

Maybe the instructions on this page should be updated to tell people they might want to designate a location? Everything worked fine from there tho

**Comment by mlsteele** [comment]
Did you use the `-O` flag?
```curl -O https://prerelease.keybase.io/keybase_amd64.deb```

What version of Ubuntu? `lsb_release -a`
What version of curl `curl --version`

**Comment by BradyDale** [comment]
1. I did use the -0 flag. I entered it in just like the page on Linux on the Keybase site said (many times before I sorted out what I needed to do)

2. Version
>Description:	Ubuntu 18.04.1 LTS
>Release:	18.04
>Codename:	bionic

3. Curl version
>curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
>Release-Date: 2018-01-24


Let me know if you have any other q's! Happy to go look at whatever

**Comment by heronhaye** [comment]
What about the `-O` flag? (O as in Oscar)

**Comment by BradyDale** [comment]
I can't remember to be honest. I think I remember reading that as a zero
not an oh, to be honest, but I don't remember if I tried both or not

>

**Comment by mlsteele** [comment]
Better copy paste. Curl has both options but they do different things.

**Comment by BradyDale** [comment]
Cutting and pasting into the terminal doesn't work like it does everywhere
else and I can never remember how to use it, and I'm probably not alone.
Just a suggestion, but since you're likely getting a lot of people on here
who (like me) aren't great with the command line, perhaps it would be
better to use the long version of the command rather than short one, so
there's no ambiguity?

**Comment by mlsteele** [comment]
ctrl+shift+v might do the trick. Some terminals are like that. Thanks for the suggestion @heronhaye's on it.

**Comment by heronhaye** [comment]
@BradyDale Updated the site with long form flag. If Ctrl Shift V doesn't work, right click might. Thanks for the report and suggestion.
