### ISSUE TITLE
login with gpg key? 

### ISSUE THREAD

**Issue by tonymet** [keybase/keybase-issues#3339]
Recently a device was lost, and I was forced to reset.  I've since added a paper key, so lesson learned. 

Just curious, why not login with gpg private key?

**Comment by maxtaco** [comment]
GPG is really hard to support. There are many ways for users to configure their keys and subkeys improperly, for keys or subkeys to expire, or to use insufficient keysizes. It just seemed like a mess.  With NaCl keys, they just work, and there are no unexpected surprises.

**Comment by tonymet** [comment]
aah thanks for clarifying.  So the gpg support it added as another comm channel for old schoolers who want to chat via keybase or gpg+email?

**Comment by maxtaco** [comment]
Yeah, we support GPG key lookup, and some GPG operations via the Website and CLI.  But your [Per-User-Key](https://keybase.io/docs/teams/puk) is not encrypted for PGP

**Comment by orgcontrib** [comment]
Hey, what about [USB-Dongle Authentication](https://www.dongleauth.info/)?

**Comment by tonymet** [comment]
@orgcontrib i'm going to close this b/c it was a specific use case and I'd like to clean it up.  Feel free to open your issue separately.
