### ISSUE TITLE
New message contents display on MacOS lock screen

### ISSUE THREAD

**Issue by izcet** [keybase/keybase-issues#3348]
(originally reported in [this issue](https://github.com/keybase/client/issues/7269) in `keybase/client` by @kg4zow)

The _default behavior_ of the keybase app on MacOS is to display pop-up banner notifications when a new message is received, including sender and message contents. These banners also appear on the lock screen, which is a major privacy flaw. There is no in-app setting to opt-out of these notifications or prevent them from showing on the lock screen. A user must manually go to the MacOS `Settings > Notifications` and disable all notifications for the Keybase client.

I would argue the default behavior should be desktop notifications disabled, with an in-app setting to opt-in. From there, which content is displayed could be a setting (all content, display sender only, "you have mail"). 

At the very least, **displaying message contents and sender when the computer is locked is a huge flaw which should be addressed**.

**Comment by mlsteele** [comment]
There is a setting for message contents.
Settings > Notifications > Security > Display mobile plaintext notifications

**Comment by izcet** [comment]
Sorry for the late reply,
That toggle has no effect on messages appearing, screen unlocked or not. The only settings that seem to affect this behavior are in the MacOS system settings.
System Preferences > Notifications > (scroll down to) Keybase > None (and un-check toggles as necessary)

**Comment by mlsteele** [comment]
Gotcha, I misunderstood. The "mobile" setting affects only phones.

There's this option to uncheck "Show notifications on lock screen". Which is less of a big hammer than  "None". This way you can still get meaningful notifications when unlocked, but no private information when locked.
![image](https://user-images.githubusercontent.com/705646/54460747-d8114400-4740-11e9-9c9a-894702020896.png)

Thanks for bringing this up I'm personally definitely going to start using that for now. I think it would be nice to hide sender and contents but still get some opaque notification on the lock screen.

**Comment by joshblum** [comment]
closed via #17337
