### ISSUE TITLE
Broken link to KEX doc from KBFS crypto doc 

### ISSUE THREAD

**Issue by PaulCapron** [keybase/keybase-issues#3350]
On https://keybase.io/docs/crypto/kbfs §6.1 _Adding A New Device_, the link captioned “key exchange” is broken. 

It points to <s>https://keybase.io/docs/key-exchange</s>, which 404. 

It should point to **https://keybase.io/docs/crypto/key-exchange** instead.

**Comment by maxtaco** [comment]
Thanks, should be fixed.

**Comment by PaulCapron** [comment]
Yes, it is fixed indeed (from my machine). Thanks! 

And many thanks for Keybase, and especially KBFS, which is **great**!

**Comment by maxtaco** [comment]
You're most welcome!
