### ISSUE TITLE
Passphrase required each time the app is launched

### ISSUE THREAD

**Issue by m110** [keybase/keybase-issues#3357]
Hi,

I've reinstalled the Keybase app on my iPhone to clear stored cache. I've revoked the old device and added new. Everything went well, except now each time the app is closed, it asks me for the passphrase on launch. This is very annoying due to the length of my passphrase. Is this expected behavior or can I fix it somehow?

**Comment by maxtaco** [comment]
Second report of this we've had.  Can you send feedback from the app?  That'll give us logs we can look at.

**Comment by m110** [comment]
Seems to be fixed in latest version!
