### ISSUE TITLE
Huge data usage due to log files on Android

### ISSUE THREAD

**Issue by rebane2001** [keybase/keybase-issues#3359]
One day, I noticed that Keybase was taking up hundreds of megabytes of space on my phone   
After investigation, it turns out that the app stores `service.log` files in /data/data/io.keybase.ossifrage/files   
I had multiple logs taking up 128MB of space each, which is pretty terrible, since I don't have much room to spare on my phone   
  
I'd suggest these logs should be cleared after a certain filesize or time limit has been reached

**Comment by maxtaco** [comment]
cc @joshblum our latest release has GC of this data, which might need some tuning. But this problem is fixed or close to fixed, thanks!

**Comment by heronhaye** [comment]
Fixed in next release. Thanks for the report!
