### ISSUE TITLE
Documentation on /flip is broken, https://keybase.io/coin-flip doesn't exist

### ISSUE THREAD

**Issue by lilyball** [keybase/keybase-issues#3361]
The inline help on `/flip` points at https://keybase.io/coin-flip for documentation, except that URL just redirects back to https://keybase.io/.

**Comment by maxtaco** [comment]
thanks for catching that.  blog post going live soon!

**Comment by lilyball** [comment]
Wow, 29 seconds between me posting the issue and getting a response (based on timestamps). I am impressed!
