### ISSUE TITLE
The website says my Twitter proof failed but it is valid

### ISSUE THREAD

**Issue by kirelagin** [keybase/keybase-issues#3363]
The website is saying on [my profile](https://keybase.io/kirelagin) that the Twitter proof failed. Now that I checked my inbox I see that I got an email about this back in May but ignored it for some reason, but now I’d like to figure it out.

I am pretty sure that I have not touched anything since then and all other Keybase apps I have are saying that the proof is valid.

**Comment by kirelagin** [comment]
Now my Facebook proof is failing as well (again, failed on the website, ok in the CLI).

**Comment by kirelagin** [comment]
(likely related #3383)

**Comment by maxtaco** [comment]
Facebook has made things impossible for us. We're considering removing it altogether.

**Comment by kirelagin** [comment]
@maxtaco ok, I see, so this is a mass thing. Any idea about my Twitter proof though?

**Comment by maxtaco** [comment]
can't look into it, but 99% sure this is a mistake on your part. maybe you deleted the tweet or made your tweets private.

**Comment by kirelagin** [comment]
> and all other Keybase apps I have are saying that the proof is valid

**Comment by kirelagin** [comment]
Ok, it appears the macOS app is failing too, but the cli still says it is ok, even with `--skip-proof-cache`.

**Comment by kirelagin** [comment]
Huh, well, I don’t know what changed, but now both Facebook and Twitter are again green on the macOS app. But if, as you said, you can’t look into it, I guess there is nothing to be done here.
