### ISSUE TITLE
Bitcoin address: Invalid Address Format

### ISSUE THREAD

**Issue by peppe998e** [keybase/keybase-issues#3365]
My bitcoin address : 'bc1q0ef74j0muxnfff0h873pjcflp9g3mlau0ktwjl'
I use Keystore type: 'bip32'

I can't add my address...

**Comment by mlsteele** [comment]
Can you find your address on a blockchain explorer type site like this? https://www.blockchain.com/btc/address/1BtCWKzmZTmRdH63CZzJeVD1MUMSshniFo

**Comment by peppe998e** [comment]
> Can you find your address on a blockchain explorer type site like this? https://www.blockchain.com/btc/address/1BtCWKzmZTmRdH63CZzJeVD1MUMSshniFo

No, but I had generate it as segwit address in Electrum

**Comment by junderw** [comment]
keybase does not support bech32 native segwit addresses.

**Comment by peppe998e** [comment]
> keybase does not support bech32 native segwit addresses.

but it will, right?

**Comment by maxtaco** [comment]
We'll fix this, thanks for the bug report.
