### ISSUE TITLE
Rename root team

### ISSUE THREAD

**Issue by inkel** [keybase/keybase-issues#3371]
Hello, keybase team! First of all, thank you, **THANK YOU** for the awesome work you do.

The company I work for, [Citrusbyte](https://citrusbyte.com/), was just rebranded as [Theorem](https://theorem.co/?from=cb), and we would really like to rename or `citrusbyte` Keybase team to reflect this change, but using the CLI tells me that I cannot rename a root team. Is there a way to do this, or do I need to create a new team and re-add all the members?

Thanks again.

**Comment by maxtaco** [comment]
You're welcome! Sorry, we haven't build this feature yet, a manual copy is likely the best bet.

**Comment by inkel** [comment]
Bummer, but thank you for the quick response!
