### ISSUE TITLE
Support Multiple Keybase Accounts In Mobile Apps

### ISSUE THREAD

**Issue by compumike08** [keybase/keybase-issues#3384]
I have a personal Keybase account. At work, I also have a Keybase account solely for work use. My work does not want me to use the same Keybase account for both personal and work (we have contractual requirements that prohibit us from mixing employee personal accounts and work accounts). I have my personal Keybase on my phone, however I'd also like to put my work Keybase on my phone as well. Right now I can log out and log back in with a different account, but that can be problematic. I would suggest adding an account switcher feature to the mobile apps, similar to the one Google has on many of their apps. It allows you to be logged into multiple different accounts at the same time, and you just use the account switcher feature to toggle between which account you want to view in the app. It doesn't mix multiple accounts together (so you would never see, for example, files or chats from both accounts on the same screen at the same time). Rather, it allows you to quickly switch between which logged in account you want to use without having to log out and log back in. Since many companies have requirements which prohibit mixing work and personal accounts (although they do allow you to put work accounts on your personal phone), I think this would be a very popular feature.

**Comment by Mikaela** [comment]
I would close this as a duplicate of https://github.com/keybase/client/issues/8586 as it has a lot more :+1: 's.

**Comment by compumike08** [comment]
This was implemented.
