### ISSUE TITLE
Subteam owner has been transformed into writer

### ISSUE THREAD

**Issue by bcomito** [keybase/keybase-issues#3389]
Hi all, I created a subteam for the purposes of creating a series of subsubteams using a naming convention derived from the subteam.  The subteam itself was supposed to remain invisible and unused.  To illustrate, I created root.subteam so that I could use root.subteam.aaa and root.subteam.bbb but I did not want anyone to use root.subteam itself.  I was the only owner, and there were no admins or any other team members added.  There are admins to the one subsubteam that I have so far created.

Somehow, my team members have found the subteam and added themselves to it.  I want to remove them and make the subteam invisible again.  But I find that I am unexpectedly only a writer of the subteam, no longer the owner or even an admin.  And there is no owner or admin at all; every team member is a writer.

I told everyone to get out and stop using the subteam, but I'd like to clean house anyway to avoid any future confusion.

Thanks!

**Comment by malgorithms** [comment]
owners and admins have implied admin control over any subteams.

so for example, any owner or admin of `root` can add and remove people to `root.usa.marketing`. This is intended to work like other team management software. For example, in Google Suite, if you're an admin of your team, you can create a group called "interns" and manage its memberships, whether or not you're in it. You can add yourself to that group, or you can leave yourself out, but you still have control of it. In keybase that means admins have the keys to any subteams below them.

you can also delegate control to the members of that subteam. so for example, you could have:

- alice is an owner of root
- bob is an admin of root
- charlie is an admin of root.usa
- danika is an admin of root.usa.marketing
- bob is a "writer" in root.usa.marketing

in this scenario, all 4 of these people can see and control memberships in root.usa.marketing. including add themselves into it if they want. but only bob and danika are actually in the team, so only they will see the chats.

if you want subteams in your org that only you see, then you should be the only admin in root. or you can also make other top level teams, too.

**Comment by malgorithms** [comment]
note that while bob chooses to be a "writer" in root.usa.marketing, he has inherited administrative control and can upgrade himself to an "admin" if he likes.

**Comment by junderw** [comment]
1. If you are admin/owner of root you have admin powers in the whole tree of teams below root and you can see all of them.
2. If anyone else is admin of root, they will see all your subteams no matter how deep you go.

**Comment by malgorithms** [comment]
right. much more concise than my example. this is by design of course. admins control the tree under them.

if you want a complex org, then you can just have 1 or 2 owners at the top and then split into subteams appropriately.

acme -- just the CEO and CTO are owners/admins
acme.bod -- the board of directors
acme.legal -- lawyers and management
acme.public -- a team with some community admins
etc.
