### ISSUE TITLE
keybase chat: Can’t send to some Mastodon instances user

### ISSUE THREAD

**Issue by mayaeh** [keybase/keybase-issues#3392]
Unable to send messages to users of some Mastodon instances with the "keybase chat" command.

If the instance name contains a hyphen, the following error is returned:
```
$ keybase chat someone@in-hyphen-domain.example.com “hello”
▶ ERROR Invalid key-value identity: someone@in-hyphen-domain.example.com
```
(This domain name is an example.)

Environment:

```
$ keybase --version
keybase version 3.2.2-20190412030505+5262f90fd9
```
macOS Mojave 10.14.4

 EDIT: I changed `＠ (U+FF20)` to `@` .

**Comment by noellabo** [comment]
My account can not actually send it with the keybase command. If you need a test, please try it with my acct.

`keybase chat send noellabo@dtp-mstdn.jp "test"`

**Comment by rosylilly** [comment]
@mayaeh I guess your `@` is not wrong.

Your `＠` is a full-width at sign, code point is `U+FF20`. You should use `@` is ASCII, and code point is `U+0040`.

**Comment by rinsuki** [comment]
I think, `U+FF20` is not related to this problem.

```
~ $ keybase chat send noellabo@dtp-mstdn.jp
▶ ERROR Invalid key-value identity: noellabo@dtp-mstdn.jp
~ $ keybase chat send noellabo@mastodon.social
Creating a new PRIVATE CHAT conversation
^C▶ ERROR interrupted
~ $ keybase version
Client:  3.2.2-20190412030505+5262f90fd9
Service: 3.2.2-20190412030505+5262f90fd9
```

**Comment by mayaeh** [comment]
I made it "@" (U+FF20) to avoid being recognized as an email address.
I'm sorry I made a misunderstanding.

**Comment by xgess** [comment]
we'll take a look. thanks.

**Comment by heronhaye** [comment]
Will be fixed in the next release. Thanks for the report!
