### ISSUE TITLE
Need account reset

### ISSUE THREAD

**Issue by rwbaumg** [keybase/keybase-issues#3411]
So it looks like I'm in the "Can I reset my account?" club, as I created two Keybase accounts to start without understanding the username/email restrictions and am now in need of some help.

I've tried sending a number of e-mails to max@keybase.io (and max@keyba.se) but since I've not yet had a response I'm creating this issue to track my problem.

I have two accounts created for testing the service - one intended to be my primary account (attached to my private e-mail) and one for screwing around with (attached to my Gmail). In the process of setting these up I lost access to what I would like to be my primary account.

So I need help to solve the following two issues:
- Regain access to my Keybase account for rwb@0x19e.net (username 'rwb')
- Rename the rwb@0x19e.net account to 'rwbaumg' so my usernames are consistent across sites

Once that's done, I will transfer teams from my other account 'rbaumg' before most likely nuking the 'rbaumg' account.

My last question is this: if I nuke an account, can I then create a new account with a different username but the same e-mail, or is the e-mail attached to the nuked account then 'blacklisted' from future use?

**Comment by rwbaumg** [comment]
I'm closing this issue since it's now become clear to me that Keybase does not support account renames.

I was also lucky enough to find the dummy login for the test account I had created (using my primary email) which I had lost access to, so I'm now at least able to access my accounts.

I think it's unfortunate that the username/email restrictions are implemented the way they are - for a service designed to tie identities together it would seem an odd choice, as there are many circumstances under which one or both must be changed in order to continue making use of the service.

While I am not entirely satisfied, I no longer require administrative assistance so this issue is closed.

**Comment by heronhaye** [comment]
Depending on your mail server, you could use an e-mail like `rwb+keybase@0x19e.net` for your new Keybase account instead. See https://en.wikipedia.org/wiki/Email_address#Subaddressing.

**Comment by rwbaumg** [comment]
@heronhaye Thanks for the advice; I hadn't considered subaddresses, but
indeed own the mailserver (Postfix) and have it as an option (maybe the
best I've got so far). I would still like to see more official support,
though.
