### ISSUE TITLE
Option for window title bar on linux

### ISSUE THREAD

**Issue by maeveynot** [keybase/keybase-issues#3421]
Since an update a few weeks ago, the Keybase desktop app on Linux now tells the window manager to turn off all decorations and draws its own "title bar" (mostly blank space, with custom buttons on the right, what looks like where they would be on Windows, maybe).

I *really*, *really*, *really* dislike this. It's ugly, it's nonstandard, it trips me up every time I want to interact with the window because that's not where I have my window manager put buttons. In my opinion, it's bad accessibility.

Can you please add an option to go back to letting the window manager decorate the window normally and not wasting all that space, like it was before? Applications like Google Chrome have an option for this on Linux.

**Comment by heronhaye** [comment]
Resolved in next release: https://github.com/keybase/client/pull/17472. You can get it now if you download a [nightly](https://keybase.io/docs/linux-user-guide#nightly-builds).

**Comment by maeveynot** [comment]
Thanks!
