### ISSUE TITLE
keybase_autostart.desktop messages in syslog

### ISSUE THREAD

**Issue by jessedp** [keybase/keybase-issues#3423]
The logging from **keybase_autostart.desktop** is outputting ANSI to syslog. Obviously not a real problem, but annoying to run across nonetheless.

![screenshot of syslog](https://user-images.githubusercontent.com/77744/59162040-6aaf4e00-8ab8-11e9-9d33-4075355de4a9.png)

The system this comes from is:

```
xyz@nyx:/var/log$ uname -a
Linux nyx 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

xyz@nyx:/var/log$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:    18.04
Codename:   bionic

xyz@zyx:/var/log$ keybase version
Client:  4.0.0-20190508150240+6614a49937
Service: 4.0.0-20190508150240+6614a49937

```

**Comment by heronhaye** [comment]
Good point, we'll fix this for the next release. In the meantime, you could try setting `KEYBASE_NO_SQUIRREL=1` in the system environment before programs are autostarted.

**Comment by heronhaye** [comment]
Should be fixed.
