### ISSUE TITLE
Typo on webpage

### ISSUE THREAD

**Issue by gtallen1187** [keybase/keybase-issues#3425]
Looks like a small typo:

![image](https://user-images.githubusercontent.com/4712768/59316841-0641e980-8c86-11e9-9500-113e7bcd7a62.png)

**Comment by strib** [comment]
That's the word we meant to say.  Prove-ably.

**Comment by junderw** [comment]
If this was merged:

```
Keybase: we help you prove who you are.

Also Keybase: this guy is probably this account, not too sure.
```

**Comment by gtallen1187** [comment]
Makes sense, sorry for the confusion and for wasting people's time :frown:

Greg Allen
gtallen1187@gmail.com
+1-504-913-6002
