### ISSUE TITLE
Reset my account

### ISSUE THREAD

**Issue by ffej23** [keybase/keybase-issues#3431]
Hello, 

I am new to Keybase, and the app on my phone was having issues. In order to try and fix this, I uninstalled and reinstalled the app. I only had this installed in 1 location, and that would be on my phone that I uninstalled the app from. I am trying to reset my account, however my account passphrase is not being recognized. When I click to reset my passphrase, it says I am not allowed as I still have 1 active device (which is the phone that no longer has the app).

Can I have my passphrase reset, so that I can reset my account?

**Comment by mossy-nw** [comment]
@ffej23 if you go to `https://keybase.io` and select `Login` there is a `Recover account` link where you can enter your username/email to reset your account.

I would avoid using the keybase-issues forum for such individualized requests.

**Comment by ffej23** [comment]
I didn't want to post it here, however I was unsure where else to post it. I have just created the account, and now that I removed the app from my 1 registered device, I am not able to reset my account. The account password isn't being recognized, and I am unable to login. Therefore, I do not have the proper access to reset my account. At this point am I SOL?
