### ISSUE TITLE
How do you get the private key?

### ISSUE THREAD

**Issue by jnicklas** [keybase/keybase-issues#344]
I ran `keybase gen`, choosing not to push the private key to the server. However, I want to use the private key from multiple computers. How can I get the private key, and how do I transfer it to another computer?

**Comment by kumavis** [comment]
Sorry to tag onto this closed issue, but the solution is not working for me. I used keybase cli to generate a private key, and now i want to upload it. Not able to export it.

```json
{
  "status": {
    "configured": true,
    "logged_in": true
  },
  "user": {
    "name": "kumavis",
    "key": {
      "key_id": "31FFF62B72A3B8FF",
      "fingerprint": "BB51 BEDF C5B4 BA2F C2A1 38F5 31FF F62B 72A3 B8FF"
    },
    "proofs": {
      "twitter": "aerinonfire",
      "github": "kumavis",
      "generic_web_site": [
        "http://aaron.kumavis.me"
      ]
    }
  }
}
```
```
$ gpg --armor --export-secret-key 31FFF62B72A3B8FF
gpg: WARNING: nothing exported
```

**Comment by kumavis** [comment]
nevermind! it was a different problem -- my private key had been deleted.
