### ISSUE TITLE
Enable Keybase in Finder

### ISSUE THREAD

**Issue by dlumma** [keybase/keybase-issues#3445]
Hi There!

I have a personal laptop, an iphone and a work laptop. I'd like to be able to access my personal private files on my work laptop via keybase. However, my work laptop has carbon black defense installed which I believe regularly snapshots the filesystem. Will my personal private files be visible in plaintext and captured on my work computer is I enable keybase in finder?

If so, I don't want to go down this path and would love any suggestions/ pointers. Ideally, there would be a way to access personal private file content from the browser (eg like Dropbox, Google Drive, etc).

Thanks!
-Denali

**Comment by strib** [comment]
The Keybase flie system mounts as a network drive.  If this is Windows, it would be on the K: drive, not C:.  Probably your snapshot thing would ignore network drives but that's something you'd need to check, I'm not sure.

We don't have a secure way to let you see private files from a browser.

**Comment by dlumma** [comment]
Thanks for the response! I'm running OSX.

I'll presume that any application with root authorization will be able to access the network drive on OSX and gain visibility into the plaintext files there.

That said, I think that perhaps the git feature could work for my use case as it seems like files in keybase git are not cloned automatically into any location in Finder. The idea is that you would clone these repos from somewhere on the user's hard drive and interact with them via normal git commands. So I could decide to selectively clone only the repos I was comfortable with.

The plaintext representation of the git files in the keybase application are encrypted and would not be visible via a hard disk snapshot on a work laptop with keybase installed, correct?

**Comment by strib** [comment]
On OSX, it also uses a network mount drive.  And correct, if you don't clone the git repo locally, it won't be in plaintext anywhere on your disk.

**Comment by dlumma** [comment]
Thanks!
