### ISSUE TITLE
keybase.io tor hidden service not reachable

### ISSUE THREAD

**Issue by heini** [keybase/keybase-issues#3448]
Tor hidden service for keybase.io seems to be down a.t.m.

**Comment by heini** [comment]
Still not working. Anybody looking into this?

**Comment by maxtaco** [comment]
sorry about this, we'll take a look tomorrow.

**Comment by heronhaye** [comment]
@heini Does it work for you now?

**Comment by heini** [comment]
Sorry for the delay. Yes, it's working fine again.
