### ISSUE TITLE
Update links to nixpkgs in linux user guide

### ISSUE THREAD

**Issue by worldofpeace** [keybase/keybase-issues#3449]
The links labeled `(link)` are to packages expressions in the EOL 18.09 release.

![Screenshot from 2019-07-06 06 42 29](https://user-images.githubusercontent.com/28888242/60755139-43fe0d80-9fb9-11e9-9e98-59823451c79b.png)

The current release is `19.03`.

#### note that NixOS releases numbers are just dates YY-{03,09} 

@heronhaye

**Comment by heronhaye** [comment]
Should we point to master or the current release?

**Comment by worldofpeace** [comment]
The current release. It would be nice if github could give us a way to expose a link that would always be on the stable branch. Then there wouldn't be a hassle to update the links every 6 months.

**Comment by heronhaye** [comment]
Okay, links updated.
