### ISSUE TITLE
Forgot Password 

### ISSUE THREAD

**Issue by asingadireddy** [keybase/keybase-issues#3455]
I log out and when I taped my passphrase was not correct.
It says incorrect passphrase.
the key base is installed on WINDOWS. How can I recover my account? Thank you so much for your help.
In mail :
Someone - probably you - used the "Recover account" option on Keybase. 
Since you have active devices or paper keys, you can't reset your passphrase. The following devices still have access to your account and have the power to set a new passphrase or provision of another device: 
1.
2.
In case you don't remember, here's your Keybase username: XXXX. 
If you have lost all devices and paper keys, please contact max@keybase.io 

C:\WINDOWS\system32> key base passphrase recover
- ERROR Your account has no paper keys.
To change your forgotten passphrase you will need a device with unlocked keys.
Otherwise, an account reset will be required.
If you'd like to reset your account:  https://keybase.io/#account-reset

I have sent an email to max@keybase.io... Could anyone please look into this issue on priority bases.

**Comment by maxtaco** [comment]
Hello, I can reset your account, but it's a last-ditch recovery solution.

You'll lose all of your KBFS, git and chat data. You'll also lose all of
your followers, your proofs and who you are following (you can reestablish
these individually after the account reset).

Also, some users have reported UI bugs after an account reset.  We are
working to address these issues as fast as we can.

Please confirm it's OK to reset your account.

**Comment by asingadireddy** [comment]
Hi Maxwekk,

Please reset the account .

Thanks,
Anusha

**Comment by asingadireddy** [comment]
Hi Maxwekk,

Could you please reset the account ASAP.

Thanks,
Anusha


From: Anusha Singadi -X (asingadi - COLLABERA TECHNOLOGIES PVT LTD at Cisco)
Sent: Wednesday, July 17, 2019 10:34 AM
To: keybase/keybase-issues <reply@reply.github.com>; keybase/keybase-issues <keybase-issues@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [keybase/keybase-issues] Forgot Password (#3455)

Hi Maxwekk,

Please reset the account .

Thanks,
Anusha

**Comment by asingadireddy** [comment]
Hi Maxwell,

Could you please reset my account.

Thanks,
Anusha.

**Comment by maxtaco** [comment]
you need to email me
