### ISSUE TITLE
linux: gnome-keyring/KWallet alternatives for primary keyring store?

### ISSUE THREAD

**Issue by maxthomas** [keybase/keybase-issues#3460]
i had to provision a new linux device today and saw this warning:

```
▶ WARNING Failed to reach system keyring (primary store (system keyring): failed to open secretservice session: The name org.freedesktop.secrets was not provided by any .service files), falling back to secondary store (file-based secret store (see https://keybase.io/docs/crypto/local-key-security))
```

reading the link indicates some ostensible integration with `gnome-keyring` and `KWallet`; are there plans for any alternatives? i'm inside of an environment without either of those, just `gpg2`.

it seems that `docker` uses some combo of `pass` and `gpg2` to solve this with some additional software.. could this be easily pulled into keybase via configuration to provide similar functionality (if interesting)?

**Comment by heronhaye** [comment]
Sorry, we only support the [D-Bus Secret Service](https://specifications.freedesktop.org/secret-service/) protocol right now.

I'd suggest unchecking "remember passphrase" and then feeding some combination of `pass` and `gpg2` to `keybase login`.

**Comment by maxthomas** [comment]
ah okay, but any implementation of that protocol would be supported, right?

**Comment by heronhaye** [comment]
Yes, but I'm not aware of any other than gnome-keyring and KWallet.

**Comment by maxthomas** [comment]
ok, great. do you happen to know where in the source or configuration this is accessed, if i wanted to plug in a custom implementation?

**Comment by heronhaye** [comment]
If you want to implement Secret Service, there's no changes needed to the Keybase client. Just have your service running before you start Keybase.

**Comment by maxthomas** [comment]
got it. thanks for the information, i really appreciate it!

going to close for now, will follow up with separate issues. thanks again!
