### ISSUE TITLE
Mac Keybase widow cannot be hidden

### ISSUE THREAD

**Issue by dvhwgumby** [keybase/keybase-issues#3463]
Keybase on the mac doesn't obey the cmd-H "Hide" command.  The window stays stubbornly visible blocking what's under it unless you take your mouse and move it or minimize it.  This is so annoying that I have taken to exiting the app which makes it useless as a messenger.

**Comment by mlsteele** [comment]
Cmd-H hide works for me. What version of macos? Could you `keybase log send` to send app version information? Any other apps affected similarly on your machine, particularly electron based?

**Comment by dvhwgumby** [comment]
Miles, some additional info:

MacOS 10.14.6.

The system *thinks* KB is hidden: if I do "hide others" in the finder, finger then greys that option out (as if it believes all other apps have been hidden) yet the KB window is stubbornly there.  I can't share a screenshot for privacy reasons.

Which log?  I looked at some of them and they contain info about whom I've communicated with (a bit concerning actually) so I am reluctant to type that command without knowing which logs it will send.

**Comment by mlsteele** [comment]
Ok, the output of `keybase version` then.

Btw `keybase log send` explains a little and asks for confirmation
```
$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.
These logs don’t include your private keys, encrypted data or file names,
but they will include metadata Keybase normally can't read
(like file sizes and git repo names), for debugging purposes.
Continue sending logs to keybase.io? (type 'YES' to confirm):
```

**Comment by dvhwgumby** [comment]
Thanks.

keybase version
Client:  4.2.0-20190710181120+e7c0bdc4a2
Service: 4.2.0-20190710181120+e7c0bdc4a2

**Comment by waynew** [comment]
Do you have any other window management apps, like Divvy?

**Comment by dvhwgumby** [comment]
Now on 4.3.2-20190819174235+b1c5c7c912 the problem has resolved.
