### ISSUE TITLE
Install to Ubuntu/Debian with gdebi

### ISSUE THREAD

**Issue by jpaugh** [keybase/keybase-issues#3469]
Currently, the [install instructions for Ubuntu] & friends recommend putting your system into a broken state, and then using `apt-get install -f` to fix it after the fact. That could fail whenever the user has some weird configuration (e.g. forgot to enable the universe software channel in Ubuntu), requiring the user to manually uninstall the package before proceeding.

However, this risk is completely unnecessary. There's a program called [gdebi] that will install a `.deb` package along with all of its dependencies in one go, resolving all dependencies before attempting an install.

The new instructions (for 64bit) would be:

```
curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
sudo apt-get install gdebi
sudo gedebi keybase_amd64.deb
run_keybase
```
There's also the GUI variant, `gdebi-gtk` which is installed as part of the same package.

[gdebi]:https://packages.debian.org/buster/gdebi
[install instructions for Ubuntu]: https://keybase.io/docs/the_app/install_linux#ubuntu-debian-and-friends

**Comment by heronhaye** [comment]
Good point. What do you think about this new apt feature that seems to do the same thing with `apt install xxx.deb`? 

https://mvogt.wordpress.com/2015/11/30/apt-1-1-released/

**Comment by jpaugh** [comment]
Ooh! I haven't seen that before! That's even better, since it doesn't require installing another app, first. The one downside is that earlier versions of Ubuntu won't support the `apt` command. However, xenial (2016) does support it, so that's a good spread. I tested it, and copied my testing procedure below, for anyone who wants to confirm my results.

Since I already had `keybase` installed, I tested this with 

```
apt install --download-only docker.io
apt install '/var/cache/apt/archives/docker.io_18.09.7-0ubuntu1~18.04.3_amd64.deb'
docker run -d -p 8983:8983 solr
# After a few seconds
browse http://localhost:8983/
```

It successfully resolved the dependencies, and installed, and then http://localhost:8983 showed the `solr` configuration website, as expected.

**Comment by heronhaye** [comment]
Okay, we've updated the instructions at https://keybase.io/docs/the_app/install_linux to use `apt` instead. Thanks for the report!
