### ISSUE TITLE
build 4.3.0-20190812143918+f8de90a10f does not work for me

### ISSUE THREAD

**Issue by dvandok** [keybase/keybase-issues#3476]
Upgraded today and the GUI did not come up. Otherwise the software seems to run fine.

This is on Debian 9, x86_64. Package 
https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/keybase_4.3.0-20190812143918.f8de90a10f_amd64.deb

**Comment by heronhaye** [comment]
We should get a patch out later today for Debian. In the meantime, you can solve this by running `chmod u+s /opt/keybase/chrome-sandbox`.

**Comment by heronhaye** [comment]
Hi, this should be fixed if you upgrade to 4.3.1. Let me know if doesn't work, thanks.
