### ISSUE TITLE
Something bad happened (code 100) when adding email

### ISSUE THREAD

**Issue by waynew** [keybase/keybase-issues#3483]
Trying to add one of my other email addresses to my keybase account and I'm getting this:

    {"code":100,"desc":"Failed to purepack.unpack","name":"INPUT_ERROR"}

when I click on the validation link. I've tried several times, all to the same result.

**Comment by heronhaye** [comment]
What email client do you use? Can you try copy pasting the link instead of clicking on it? (Maybe look at the "plaintext email" as well).

**Comment by waynew** [comment]
Ahhhh... doh. The link was getting truncated by my terminal window 😛 That worked, thanks!
