### ISSUE TITLE
Failed to reach keyring?

### ISSUE THREAD

**Issue by BoyMechanicus** [keybase/keybase-issues#3495]
On arch server ```WARNING Failed to reach system keyring (primary store (system keyring): failed to open secretservice session: The name org.freedesktop.secrets was not provided by any .service files), falling back to secondary store (file-based secret store (see https://keybase.io/docs/crypto/local-key-security)). ```

How to fix?

**Comment by heronhaye** [comment]
It's not a error that will prevent you from using Keybase. But if you are worried about your local security, you can install something like Gnome Keyring and configure it to be unlocked before opening Keybase.
