### ISSUE TITLE
keybase crashes

### ISSUE THREAD

**Issue by Oxymoron290** [keybase/keybase-issues#3498]
A couple of days ago keybase started failing to load. it would just say something like starting... or similar. I decided to uninstall and reinstall and now it fails to launch entirely

```
Faulting application name: Keybase.exe, version: 4.4.0.0, time stamp: 0x5d2d59d0
Faulting module name: Keybase.exe, version: 4.4.0.0, time stamp: 0x5d2d59d0
Exception code: 0x80000003
Fault offset: 0x0000000000a960e1
Faulting process id: 0x2880
Faulting application start time: 0x01d56335b9751145
Faulting application path: C:\Users\TimSturm\AppData\Local\Keybase\Gui\Keybase.exe
Faulting module path: C:\Users\TimSturm\AppData\Local\Keybase\Gui\Keybase.exe
Report Id: 2aeaed84-b106-4594-bf26-cb44199090c5
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Oxymoron290** [comment]
Everyone in my office is affected by this

**Comment by maxtaco** [comment]
Thanks, we'll look into it. Are you all on Windows?

**Comment by maxtaco** [comment]
Also, if you could run `keybase log send` from the CLI that would help.

**Comment by maxtaco** [comment]
We looked around, this is the only such complaint we've received. Aggregate stats on Windows are all up. Anything unusual about your machines? Which versions of windows? Anti-virus or some other kernel module getting in the way?

**Comment by Oxymoron290** [comment]
All windows 10, I think we are using Kasaya, nothing out of the ordinary I would think. I will send the logs from all machines tomorrow @~9.30am cst and let you know

**Comment by Oxymoron290** [comment]
09619f3b4ee365ad697eec1c

**Comment by Oxymoron290** [comment]
well mine has just started randomly working this morning. A co-workers still isn't though. his log is 4f24e16d16a1c51b6a008a1c

**Comment by Oxymoron290** [comment]
Well now his is working after sending the log 🙄
