### ISSUE TITLE
xlm "total reserve" includes text saying "-1 XLM"

### ISSUE THREAD

**Issue by dholbert** [keybase/keybase-issues#3520]
In the wallet section of the keybase app (on Android and Linux), as of today's stellar drop, I see:
```
Total Reserve (account): 356.29 XLM
                             -1 XLM
```
Not sure what the -1 XLM is doing there but it seems like it might be a bug

**Comment by dholbert** [comment]
Screenshot (from Linux desktop app):
![image](https://user-images.githubusercontent.com/426803/64714431-77ef2680-d473-11e9-9562-9d3f175f93a7.png)

**Comment by mlsteele** [comment]
Accounts on Stellar have a minimum balance. An account cannot have between 0 and 1 XLM. There should be a question-mark icon next to the reserve with a link that explains it. Though unfortunately the FAQ it links to seems to have changed. Here's a fairly technical doc about it https://www.stellar.org/developers/guides/concepts/fees.html

It looks like this misunderstanding in part came up because you interpreted that line as wrapped
```
Total                    356.29
Reserve (account)        -1 XLM
Available to send        35somenumber
```

**Comment by dholbert** [comment]
Thanks! yeah, that sounds like it. Sorry for the noise.

> There should be a question-mark icon next to the reserve with a link that explains it

On linux (where I've just now launched the app), the question mark does have a helpful tooltip when I hover it.  On Android, the icon has no tooltip (not sure you can do tooltips on Android), and the doc it links to is not particularly helpful (it looks like a generic stellar.org FAQ, with the first question "Is the Stellar Development Foundation a nonprofit?")

**Comment by dholbert** [comment]
Looks like it links to https://www.stellar.org/community/faq#_Why_is_there_a_minimum_balance
and that `#_Why_is_there_a_minimum_balance` anchor must not exist because I don't get autoscrolled anywhere.

**Comment by dholbert** [comment]
(Also, that FAQ page doesn't include the string "reserve" at all, which was the first thing I searched for on that page when trying to understand what was going on when I only had the Android app on hand.)

**Comment by mlsteele** [comment]
Yep! Thanks for bringing this up. We'll update the link.

**Comment by dholbert** [comment]
thanks!
