### ISSUE TITLE
Cant connect github to my keybase ???

### ISSUE THREAD

**Issue by faz123786** [keybase/keybase-issues#3521]
Hi Trying to get my github connected to my keybase i have posted proof on a public gist but i get the following message "we couldn't find your proof. Please retry" 

Heres the link to my public gist post:

https://gist.github.com/faz123786/cb4704108ae97d7c98cc2e70cbc0e1c0

Hopefully someone can help me out because i have spent a few hours on this.......

**Comment by mlsteele** [comment]
Hi, I posted an answer in the other issue https://github.com/keybase/keybase-issues/issues/3505#issuecomment-530494500
