### ISSUE TITLE
Airdrop Transaction Failed: "Bad source account sequence number"

### ISSUE THREAD

**Issue by ECrownofFire** [keybase/keybase-issues#3535]
Self-explanatory, screenshot attached.

![image](https://user-images.githubusercontent.com/2103722/64835716-120ab800-d5b5-11e9-8321-995c3cff9405.png)

For copy-pasting, the transaction ID is `be8a1cc86fb6b1bf9970ba65e4ed7c595d3e96189d8c6c14f66f4b64bbfc1aa4`

**Comment by patrickxb** [comment]
A handful of the funding transactions failed the first time through.  Once we get through everything, we will go back through and try again, and it should be fine.

Sorry for the inconvenience.  Thanks for your patience.

**Comment by kamarov360** [comment]
I have same problem

**Comment by carme577** [comment]
Me too I have the same problem

**Comment by carme577** [comment]
![2019_11_18_15 00 07](https://user-images.githubusercontent.com/51461514/69134456-cba36f00-0ab7-11ea-9ff8-bc5981578834.jpg)

**Comment by manilevian** [comment]
I have the same problem, 
<img width="952" alt="Bildschirmfoto 2019-11-18 um 15 20 32" src="https://user-images.githubusercontent.com/55234866/69060083-099c8680-0a17-11ea-83a6-3eff0e79002f.png">

**Comment by manhlinhtran** [comment]
i have same
![photo_2019-11-21_02-12-55](https://user-images.githubusercontent.com/36313163/69269877-85a7f180-0c04-11ea-88f6-82bce6a7f54a.jpg)
