### ISSUE TITLE
Start device hierarchy from scratch

### ISSUE THREAD

**Issue by sylveon** [keybase/keybase-issues#3536]
I currently have two devices on my account, but login on these two devices has been lost for various reasons (my phone has been reset and I clean installed my PC).

I want to add more devices to be eligible for the XLM drop but I cannot do that as I have no paper key (should've added one, will be the first thing I do once I gain access back) or device to use for that. Is it possible to use my GPG key to sign a new paper key so that I can provision new devices, or to wipe all device/paper keys and start this from scratch (but not wipe the proofs I signed with my GPG key)?

**Comment by doRadiology** [comment]
*Exactly* the same issue here. Still have both devices, but have been reset. Can still log into keybase account online. Devices are both still registered there. But cannot register the app either device with the other to procede with the XLM drop.

**Comment by plttn** [comment]
I'm unaware of how resetting your account will interact with Drop 0, but if you go to your profile page and select the gear, there is the ability to completely reset your account.

**Comment by junderw** [comment]
full key reset, reprovision all your devices, MAKE A BACKUP PAPER KEY, then you're good for the airdrop

**Comment by sylveon** [comment]
I did that, and I can't access Drop 0 anymore. My (brand new) XLM wallet is empty and I am locked out of the spacedrop message:
![image](https://user-images.githubusercontent.com/6440374/64917947-f80fd780-d764-11e9-85df-1a2e62236ca2.png)

It's why I only wanted to restart the devices from scratch, and not the whole account. I still have my private GPG key so restarting only the devices instead of the whole account wouldn't have locked me out of previous conversation or deleted my wallet.

**Comment by plttn** [comment]
There's no way to restart devices. Your account is defined by your devices. In any case, in the next few days, Keybase staff should be going through Spacedrop's chats and accepting any chats where the user had to reset to claim Drop 0.

the PGP key had no way of creating a new device, so this was the least painful way to go about this process.

**Comment by doRadiology** [comment]
Followed the 'least' painful way and reset my account, revalided all devices and all proofs. Now indeed locked out of the airdrop as expected.

**Comment by plttn** [comment]
@doRadiology it'll take a bit of time, but soon Keybase staff will go through and reset the chats as I mentioned just above. In any case, you should be able to opt in in your wallet tab to make sure you're getting the October 15 drop.

**Comment by sylveon** [comment]
![image](https://user-images.githubusercontent.com/6440374/65379691-20825f00-dc9a-11e9-98c4-00b2704473a7.png)
Received this. RIP Drop 0 I guess.
