### ISSUE TITLE
Cannot scoll page to confirm linking Mastodon proof on mobile

### ISSUE THREAD

**Issue by victoriadrake** [keybase/keybase-issues#3540]
When attempting to link my mastodon.technology account in the mobile app (iOS), I'm able to search for and choose mastodon.social. I then am able to log in on the web page presented.

After logging in, I see a screen asking if I would like to authorize this cryptographic connection, and optionally toot about it. I cannot scroll on this page to find any confirmation button.

![IMG_9340](https://user-images.githubusercontent.com/24644237/64890961-b2f18580-d63e-11e9-9a02-9ec8fd59216f.jpeg)

The issue persists on Safari and Firefox iOS mobile browsers.

**Comment by mlsteele** [comment]
That's unfortunate, thanks for the heads up! Looks like an issue on mastodon.technology's site. Could you open this issue [over at the Mastodon repo](https://github.com/tootsuite/mastodon/)?

In the meantime maybe requesting the desktop site would work as a workaround.

**Comment by victoriadrake** [comment]
Ah. Thanks @mlsteele, I've posted the issue [over there](https://github.com/tootsuite/mastodon/issues/11838).
