### ISSUE TITLE
Can't use keybase via cli, android app or Linux GUI

### ISSUE THREAD

**Issue by nougad** [keybase/keybase-issues#3543]
I always get a `ChainLinkPrevHashMismatchError`:

```
$ keybase login 
Your keybase username: nougad
▶ ERROR Chain link prev hash mismatch error: Chain mismatch at seqno=3
```

```
$ keybase id nougad
▶ ERROR Chain link prev hash mismatch error: Chain mismatch at seqno=3
```

**Comment by maxtaco** [comment]
Interesting bug.  Back in 2014, we were ok with leading whitespace in signature payloads, and we've since made more restrictions. So a modern client won't reply your old sigchain.  We'll think about what to do here. Maybe we'll make an exception for this one sigchain link.

**Comment by maxtaco** [comment]
... If I get a spare minute today, I'll put in a workaround ... There might be other links in the database that are similar, so we should maybe do some queries to figure that out....

**Comment by nougad** [comment]
Thank you! It works now :)
