### ISSUE TITLE
Public files not found when accessed in browser

### ISSUE THREAD

**Issue by ejhusom** [keybase/keybase-issues#3550]
I can access all my files (both public and private) in my Keybase filesystem when browsing them on my computer (Ubuntu 18.04), but when I try to open them from keybase.pub/username, I only get "Not found. Sorry, but that file path is not legit. Jump back to the Keybase.pub site." The list of all my files is visible, but when I try to open individual files, they cannot be found.

This also means that when I try to access my website at username.keybase.pub, I only get "not found" there as well.

![Screenshot from 2019-09-16 21-31-47](https://user-images.githubusercontent.com/42419987/64987439-71c0d600-d8c9-11e9-9844-615e47a7b83a.png)

**Comment by Lucky225** [comment]
I'm seeing this as well, if you refresh a couple times it'll how up, refresh again and it's gone. Sounds like a replication issue of some sort.

**Comment by ejhusom** [comment]
Thanks, it works now!
