### ISSUE TITLE
Trying to use the service I registered for back in 2017, unable to do anything.

### ISSUE THREAD

**Issue by Kashalls** [keybase/keybase-issues#3578]
So, this is the only place I can seem to get help right now. I logged in today, my last time I logged in was in 2017. I am trying to install the keybase client but the only device on the account to activate has been scrapped and no longer is active. It requests me to reset the account but I can't due it being disabled. Effectively I am locked out of the account. I have no clue what to do. Any suggestions?

**Comment by Kashalls** [comment]
Also it prevents me from entering the Steller Space Drop but thats another thing to be mad about.

**Comment by junderw** [comment]
1. log in to the website
2. Reset all keys
3. Log in to a new device (the first device after a reset doesn't need another device)
4. Add new device menu -> Add Paper Key -> Save paper key somewhere safe.
5. Now next time you realize all your devices are scrapped just pull out your paper key and boom, no need to reset.

**Comment by Kashalls** [comment]
The issue would be that I signed up for the service and then haven't touched the thing in 2 years and I'm trying to get back into using it and I can't do anything so just tough luck for me right? Also you can't reset accounts they disabled it due to abuse.

**Comment by junderw** [comment]
> they disabled it due to abuse

Then wait for them to re-enable it.
