### ISSUE TITLE
Keybase iOS has a backdoor that signs proofs against my knowledge and consent

### ISSUE THREAD

**Issue by sneak** [keybase/keybase-issues#3583]
https://sneak.berlin/20190929/keybase-backdoor/

I don't want XLM shitcoins.  I don't want anyone to send me XLM shitcoins thinking I want them.  I don't hold any private keys for XLM shitcoins, despite what [my keybase profile](https://keybase.io/sneak) now fraudulently claims.

Somehow, on the 4th of February, [an attestation](https://keybase.io/sneak/sigchain#289375141b43421b024be60b0569cd701061fd37ca14f047e5d96a1bf8dacefe22) has found its way onto my profile, signed by one of my devices by the Keybase iOS client (keybase.io go client 2.13.2).  I did not want this signature generated with my keys.  Indeed, it happened without my knowledge or consent.

I am unable to revoke this from my keybase profile.

**Comment by Omeryl** [comment]
The official reply from Keybase:

https://github.com/keybase/client/issues/20022#issuecomment-536355032

@malgorithms Can we get this one closed too?
