### ISSUE TITLE
Web UI won't encrypt for my user account

### ISSUE THREAD

**Issue by lukechilds** [keybase/keybase-issues#3595]
If you go to this page: https://keybase.io/encrypt and put in my username (lukechilds), add a message and click the "Encrypt" button, you get the error:

>Error: Recipient does not have any active encryption keys.

I do have encryption keys, as well as manually added up to date PGP keys.

It also works ok on the CLI:

```
$ keybase pgp encrypt -m 'This is a test' lukechilds
-----BEGIN PGP MESSAGE-----
Comment: https://keybase.io/download
Version: Keybase Go 4.5.0 (darwin)

wcBMAwyRoi9h4GGpAQgAhBmeEloAFRhYNMVpU32cHHClme4RNYfg5SbaM4e2c3na
hCRyhsEnaMt32JEsl2aKW+lYZtVWkpoEzVuinLwYI2mkxa+WBzchHn68WGJf1fJ1
8+67v0eLouYuA1Qvxvq9opnMtL2a4QlXztRKoCV0/gILBSotkxEctYKBjCV3GBwP
2znIkXI+G0OT6hrfYM2zWq7cTYa9lIv540aGhPVECLHPVqokQf4oaXWDXdVdeQqe
DcL2WFErc0lyxm4pwraNiEhaAH6FBq7iAfuTERt7yZf9d82Rl6P/omwthSyHrvuF
8yGL5kozA2Cpv1MwJ8pUuGut7rj576U+kewR6QYMntLgAeTPx/TQTwifdO9kVDTy
o4ll4TXD4FPgteFgR+Bj4odv/TXg2eNlaOV8APwmEeCq4s8Yx6Dg3OG6YeBg5DS+
fkpc6Xw0lR/qRoi6qSjid+H4OuGTIQA=
=HMmz
-----END PGP MESSAGE-----
```

Although maybe the CLI test is bypassing Keybase and just using my local `gpg`.

**Comment by junderw** [comment]
Your PGP key has no subkey with an `E` flag.

```
pub   rsa2048 2016-04-19 [SC] [expires: 2020-07-25]
      EA9F04E561A1D10987E3E2E693D612A9D61C281A
uid           [ unknown] Luke Childs <lukechilds123@gmail.com>
```

You can only Sign and Certify with your pgp key.

**Comment by junderw** [comment]
(I got the pubkey from here: https://keybase.io/lukechilds/key.asc )

So maybe you need to update the pubkey using keybase pgp update?

**Comment by junderw** [comment]
```
$ gpg -r EA9F04E561A1D10987E3E2E693D612A9D61C281A --encrypt
gpg: EA9F04E561A1D10987E3E2E693D612A9D61C281A: skipped: Unusable public key
gpg: [stdin]: encryption failed: Unusable public key
```

**Comment by lukechilds** [comment]
Thanks for the help @junderw, I recently renewed the key so maybe I did something wrong?

This is what I have locally:

```
$ gpg --list-keys lukechilds
pub   rsa2048 2016-04-19 [SC] [expires: 2020-07-25]
      EA9F04E561A1D10987E3E2E693D612A9D61C281A
uid           [ultimate] Luke Childs <lukechilds123@gmail.com>
```

Yeah, I just tested encrypting directly with `gpg` and got the same error.

```
$ echo "test" | gpg -ear lukechilds
gpg: lukechilds: skipped: Unusable public key
gpg: [stdin]: encryption failed: Unusable public key
```

I think I followed this to renew my key: https://www.paulfurley.com/extend-pgp-key-expiry-with-gp

Any advice?

**Comment by junderw** [comment]
1. `gpg --edit-key --expert lukechilds`
2. `addkey`
3. `(6) RSA (encrypt only)`
4. `2048` (just matching your main key, whatevs)
5. `9m` (that's about the same time as your master key, you can calculate the exact number of days if you want)
6. `y` then `y` then enter your private key password to sign in the new key to your chain.

Then run the `keybase pgp update` command (I think)

**Comment by junderw** [comment]
ohhh don't forget `save` that last command is important. lol

**Comment by lukechilds** [comment]
Sorted, Thank you so much!

If you have the time, would you mind explaining a little about what went wrong?

Was the guide I followed incorrect?
Should I normally need to take this extra step when extending keys to enable encryption?

**Comment by lukechilds** [comment]
I can now see the sub key showing up with the `E` flag too:

```
gpg --list-keys lukechilds
pub   rsa2048 2016-04-19 [SC] [expires: 2020-07-25]
      EA9F04E561A1D10987E3E2E693D612A9D61C281A
uid           [ultimate] Luke Childs <lukechilds123@gmail.com>
sub   rsa2048 2019-10-09 [E] [expires: 2020-07-05]
```

**Comment by junderw** [comment]
In general, I think the default key config is a main key with `SC` enabled and a sub key with `E` enabled.

GPG is hard to explain... and hard to use... ughhh...

BUT THAT'S WHY KEYBASE CAME ALONG `B-D`

**Comment by lukechilds** [comment]
Lol figured as much, thanks!
