### ISSUE TITLE
Crash when renaming channels from the app

### ISSUE THREAD

**Issue by Hexstream** [keybase/keybase-issues#3615]
Whenever I renamed a channel via the app in the recent past it basically froze the app and I would have to restart it. It did actually carry out the rename, fortunately. This time around I used the CLI to rename multiple channels without problems.

I'm using keybase 4.6.0-20191010154240+134c2d892b on 64-bit Debian 10.

uname -a: Linux dynamorph 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

I'm using the official keybase_amd64.deb from [your download page](https://keybase.io/docs/the_app/install_linux).

Please let me know how I can help further...

**Comment by heronhaye** [comment]
Can you send feedback in the settings tab?

**Comment by Hexstream** [comment]
I can no longer reproduce this crash. I'm not sure how I triggered it the first 2 times around. I guess I'll close this, then. I'll be sure to send feedback with logs from the app if I ever trigger this again.
