### ISSUE TITLE
Unable to delete account. Error: Account deletion failsafe was not disengaged. This is a bug!

### ISSUE THREAD

**Issue by ratika-ipg** [keybase/keybase-issues#3620]
While deleting account completely, getting following error.
`Error: Account deletion failsafe was not disengaged. This is a bug! at Ql (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3280691) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1602009 at A (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1602110) at T (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1600020) at k (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1600797) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1602744 at A (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1602767) at T (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1600020) at p (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1599687) at M (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1603731)`

**Environment :-** 
MacOS High Sierra 10.13.6
Keybase Version 4.7.0-20191021032428+67d9526320

**Comment by heronhaye** [comment]
Should be fixed if you update to 4.7.2. Sorry about that!
