### ISSUE TITLE
Update links to nixpkgs in linux user guide

### ISSUE THREAD

**Issue by worldofpeace** [keybase/keybase-issues#3622]
Same as https://github.com/keybase/keybase-issues/issues/3449.

However we've redesigned our package search and it's very usable now.

Here are permalinks to the latest released versions, option links don't need to be changed.
* https://nixos.org/nixos/packages.html?attr=kbfs&channel=nixos-19.09 (kbfs)
* https://nixos.org/nixos/packages.html?attr=keybase&channel=nixos-19.09 (keybase)
* https://nixos.org/nixos/packages.html?attr=keybase-gui&channel=nixos-19.09 (keybase-gui)

Latest release is 19.09, as seen in the links.

cc @heronhaye

**Comment by heronhaye** [comment]
Will update. Those pages seem very slow to load the info though (+30 seconds but it does work eventually).

**Comment by worldofpeace** [comment]
> Will update. Those pages seem very slow to load the info though (+30 seconds but it does work eventually).

Interesting, it was less than a second for me. Perhaps there's some sort of offline cache that needs to be formed.

**Comment by heronhaye** [comment]
Should be updated now. Seems to be loading for me quickly today as well. Thanks!

**Comment by worldofpeace** [comment]
Hmm, it seems to say `Distribution Nix` while technically that's just the tool NixOS uses.
Can this be corrected to `NixOS`?

**Comment by heronhaye** [comment]
Fixed
