### ISSUE TITLE
I can't reset my account

### ISSUE THREAD

**Issue by luigibarbato** [keybase/keybase-issues#3623]
Having lost access to my devices, I am trying to reset my account using the reset procedure.
There are **two problems** that I encounter during the procedure (**which cause it to fail**):

1. if I enter my password the system throws the exception:  _"current session cannot access this endpoint on locked down account"_

2.  if I do not enter the account, I will not receive any instructions email

**Comment by zapu** [comment]
Hey, thanks for reaching out.

Are you trying to reset account on the website or using the Keybase client?

**Comment by luigibarbato** [comment]
> Hey, thanks for reaching out.
> 
> Are you trying to reset account on the website or using the Keybase client?

Hey, thank you fro the reply :)

I tried with Windows and Android Keybase clients and Website too

**Comment by zapu** [comment]
Is this your account and your devices https://keybase.io/luigibarbato/devices ?

Is there a chance you still have that paper key somewhere?

**Comment by luigibarbato** [comment]
> Is this your account and your devices https://keybase.io/luigibarbato/devices ?
> 
> Is there a chance you still have that paper key somewhere?

Yeah, it's my account.

Unfortunately I can no longer recover it, so I wanted to reset my account

**Comment by heronhaye** [comment]
@luigibarbato 
Did you previously select the "Forbid account changes from the website" setting in the app? Unfortunately, this means you won't be able to reset your account. See the documentation at https://keybase.io/docs/lockdown/index.

**Comment by luigibarbato** [comment]
> @luigibarbato
> Did you previously select the "Forbid account changes from the website" setting in the app? Unfortunately, this means you won't be able to reset your account. See the documentation at https://keybase.io/docs/lockdown/index.

It's not possible to delete the account? it will be a zombie account forever?

**Comment by heronhaye** [comment]
Yes.
