### ISSUE TITLE
Account reset.

### ISSUE THREAD

**Issue by dylanaraps** [keybase/keybase-issues#3628]
Hello,

I would like to reset my keybase account.

- I no longer have access to my registered device(s).
- I no longer have access to my paper keys.

I created the account a few years ago(?) and I no longer have access nor *have* my registered devices. I have also had numerous house moves and subsequently lost my paper keys.

I sent an email to max@keybase.io on the 4th of October about an account reset but have not received a reply. I sent the email as per recommendation in an older issue exactly like this one on this tracker.

Account resets through the website seem to be totally gone now and my support email (*possibly sent to the wrong place*) has been ignored. 

Any help is appreciated.

My email is: dylan.araps@gmail.com
My keybase account is: https://keybase.io/dyl

**Comment by mlsteele** [comment]
Hi Dylan. Account resets have recently become more automated. Sorry your previous request seems to have fallen through the cracks. Now if you open the app on mobile or desktop (not the website) and attempt to log in, you should be able to start the reset process. After starting the process there will be a 7 day cooldown after which you'll be able to reset.

Starting a reset looks like this now:

![image](https://user-images.githubusercontent.com/705646/67687642-027ddd80-f96f-11e9-9c6d-a42f5d5f9e3a.png)


![image](https://user-images.githubusercontent.com/705646/67687600-f134d100-f96e-11e9-8e6c-3753b984abc3.png)

**Comment by dylanaraps** [comment]
Hello, thanks for replying.

I don't have the means to run the GUI application as my system is incompatible with it. I *can* run the CLI application just fine though. I also do not own a phone and therefore cannot run/install the mobile application. 

What are my options in this situation? Is a reset from your side of the fence possible? Does your guide above also apply to the CLI client?

**Comment by heronhaye** [comment]
@dylanaraps, two options.

1) In the CLI, try to run `keybase login <yourusername>`, and then select "Don't have any of these" when it asks you to provision

2) On the website keybase.io, log out, click the log in modal, and then click "Forgot your password" (even if you haven't). You'll be able to enter the reset process here as well.

**Comment by dylanaraps** [comment]
Lovely, thank you!

>  Account reset has been started

**Comment by moi04b** [comment]
> 
> 
> Hi Dylan. Account resets have recently become more automated. Sorry your previous request seems to have fallen through the cracks. Now if you open the app on mobile or desktop (not the website) and attempt to log in, you should be able to start the reset process. After starting the process there will be a 7 day cooldown after which you'll be able to reset.
> 
> Starting a reset looks like this now:
> 
> ![image](https://user-images.githubusercontent.com/705646/67687642-027ddd80-f96f-11e9-9c6d-a42f5d5f9e3a.png)
> 
> ![image](https://user-images.githubusercontent.com/705646/67687600-f134d100-f96e-11e9-8e6c-3753b984abc3.png)

Hi, if I reset my keybase account, I can't see if I received my lumens? or is my account deleted?
