### ISSUE TITLE
Can't log back into Keybase

### ISSUE THREAD

**Issue by EtruscanSage** [keybase/keybase-issues#3638]
So, this is the second time this has happened.
I took a screenshot of the secret code and made sure to make no mistake in the creation of the password, yet regardless of that, I am unable to log in, as I will receive these three error messages:

When I use the secret code:

> server rejected session; is your device revoked? Error code: BAD_SESSION in method keybase.1.login.login

Or:

> Wrong secret phrase. Please try again.

When I use the password:

> Unknown error: BAD_SESSION Failure to verify PDPKA5

It is here that I have to point out that I've got minimal programming experience, half of which I've already forgotten, so please go easy on me.

As far as I was able to gather, there was something about a back-up key that I should have retrieved in order for the server to recognise my device again, which I didn't know, but this cannot be the only error, I literally took a screenshot of the secret phrase, and made sure to not screw up the password, yet somehow they're both wrong?

I'd be very grateful for some help.

**Comment by mlsteele** [comment]
What's your keybase username?

**Comment by EtruscanSage** [comment]
It is "FruitsAndIce34R".
