### ISSUE TITLE
Old Device Reformatted No backup keys to restore account

### ISSUE THREAD

**Issue by eagles051387** [keybase/keybase-issues#3639]
Hi Guys,

I have my account in lockdown mode and i since reformatted the pc that had my keybase account setup on it. what can i do to remove that pc and setup a different machine or two on my account. I also am unable to delete my account due to lockdown mode :( Please help

**Comment by heronhaye** [comment]
Sorry, [lockdown mode](https://keybase.io/docs/lockdown/index) is a security feature. If you've enabled it, there's no way to reset or delete your account without a valid device.
