### ISSUE TITLE
Can't write to chat despite "Reader" permission

### ISSUE THREAD

**Issue by jlevon** [keybase/keybase-issues#3642]
This used to work until trying to today. I cannot post to a team chat, even though I'm lited as a Reader which should be high enough permission.

I get:

Unable to send, not high enough team role to post in this conversation.

I can still read previous chat.

Happens with 4.7.2-20191028173732.6fc2e969b4 on Ubuntu and today's nightly.

**Comment by heronhaye** [comment]
Send feedback in the app please.

**Comment by jlevon** [comment]
Looks like keybase changed the defaults such that you now have to modify chat permissions to allow readers. Docs still say reader is enough for chat.
