### ISSUE TITLE
Stellar airdrop and changing email addresses and user names. 

### ISSUE THREAD

**Issue by mpaujnpr01** [keybase/keybase-issues#3648]
Hi folks,
I used an email address to create my account and then from what I can see I can't change either of those due to security concerns. 
Now, I want to create a new account, because I want to transition to a more generic name / email address that is more portable. 
But, I have concerns... with the wallet, the anti-gaming, and being shadow-banned from stellar airdrop.
So, do I go create a new account, and accidentally get 'joined' into stellar airdrop and get shadow banned for "gaming the airdrop" (not interested) and lose my current XLM and place in line? 
Or, do I go create a new account, and somehow I've got a way to ensure that I won't be auto-joined to stellar airdrop? 
Thoughts anyone?

**Comment by heronhaye** [comment]
You can change your email address in the account section of the Settings tab in the desktop app, or in the account section of the hamburger tab in the mobile app (delete the existing one and add a new one).

Unfortunately you cannot change your Keybase username. 

You won't be autoenrolled into the airdrop unless you explicitly opt in in the Wallet tab.
