### ISSUE TITLE
It is November 15 and I did not receive any XLM from airdrop. I registered successfully on September 10

### ISSUE THREAD

**Issue by crypto666** [keybase/keybase-issues#3657]
I don't understand! I registered on keybase on September 10 and in the same day my account GAFGT6C6DSUX2ZNI4TK73OLQ46GRCFJU5GT4ZOFQQL3XLM6L55TZIWYV was approved for XLM airdrop following everything they asked. Is November 15 and I GOT NOTHING! Anyone knows why?
![Capture](https://user-images.githubusercontent.com/36092925/68983137-4413e280-07cf-11ea-9706-aac9ffc8ea8d.GIF)
![Capture2](https://user-images.githubusercontent.com/36092925/68983138-45450f80-07cf-11ea-94ca-0599b301f8ed.GIF)

**Comment by Zero-1729** [comment]
It takes time to distribute the airdrop to each participant, as they explicitly stated [here](https://keybase.io/a/i/r/d/r/o/p/spacedrop2019):

> "... @spacedrop is delivering Lumens right now to registrants. It will take a few days, as @spacedrop builds an encrypted conversation on Keybase with each recipient."

So you would just have to be patient. As long as you are registered you should receive your lumens in the coming days.

**Comment by crypto666** [comment]
Thank you so very much

**Comment by crypto666** [comment]
It worked!:-)
