### ISSUE TITLE
How i can cancel a transfer

### ISSUE THREAD

**Issue by apj8** [keybase/keybase-issues#3659]
I just send some xlm without writing the memo id, so i lost all. How can i cancel that transfer?

**Comment by hexandcube** [comment]
Unfortunetly, there's no way to cancel XLM transfer.

**Comment by apj8** [comment]
What can i do?

**Comment by ksovrela0** [comment]
Can u send your xlm address?

**Comment by apj8** [comment]
Address: GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37
Memo ID: 3262590507

**Comment by ksovrela0** [comment]
No your keybase XLM address

**Comment by apj8** [comment]
GCMECZIPEUNOWFNNC4F6ZDEBWB5YRSRS5SC237F3EZMGIR2Z36FME4DD

**Comment by ksovrela0** [comment]
Unfortunately, If XLM were sent without memo id, they lost
