### ISSUE TITLE
airdrop problem

### ISSUE THREAD

**Issue by lik24n** [keybase/keybase-issues#3664]
hello, I contact you because I do not receive airdrop. I registered before November 15 and I received nothing. yet I am registered on keybase with my phone and on the airdrop. :(
![Screenshot_20191117-104724](https://user-images.githubusercontent.com/56511523/69005882-5bb2ae80-0928-11ea-887a-e719817e570e.png)
![Screenshot_20191117-104739](https://user-images.githubusercontent.com/56511523/69005883-5bb2ae80-0928-11ea-96f9-70958bf126a2.png)

**Comment by Zero-1729** [comment]
Related to #3657 & #3653. 

See my comments [here](https://github.com/keybase/keybase-issues/issues/3657#issuecomment-554592457) and [here](https://github.com/keybase/keybase-issues/issues/3653#issuecomment-554813456).

**Comment by lik24n** [comment]
thanks you and sorry ^^
