### ISSUE TITLE
Problem with Spacedrop

### ISSUE THREAD

**Issue by Lewies** [keybase/keybase-issues#3665]
I  didn't get my spacedrop - why not?!

Please Note: I registered LONG before NOV-15 (even Oct-15) 

Please look into this. thank you.

my stellar id/address is:

GDO2Q3K3AHOVBRSGZSHIJ4RLGIRUSX5DD5PABULK5RWDWU5TFGPQC56U

![Spacedrop problem](https://user-images.githubusercontent.com/4226769/69006278-7b040880-0935-11ea-944c-bf6fb93f1a0e.jpg)

**Comment by hexandcube** [comment]
Are you still in Airdrop? 

> Spacedrop bot is delivering Lumens right now to registrants. It will take a few days, as spacedrop builds an encrypted conversation on Keybase with each recipient. [You can watch the balance drain to see how far along it is.](https://stellar.expert/explorer/public/account/GDV4KECLSZLKRVH4ZTWVAS4I3W2LPAPV66ADFFUZKGIVOTK6GMKGJT53) - keybase.io/airdrop

**Comment by Lewies** [comment]
Thanks for your reply... I STILL haven't received my coins.
AND, Yes - I'm STILL, IN the spacedrop...

**Comment by Zero-1729** [comment]
Related to #3657 & #3653.

See my comments [here](https://github.com/keybase/keybase-issues/issues/3657#issuecomment-554592457) and [here](https://github.com/keybase/keybase-issues/issues/3653#issuecomment-554813456).

**Comment by GlobusV** [comment]
Hello.  I'm generally shocked at how they are allowed to participate.  How can this be, first it gives out three green jackdaws and then they write that participation is refused.  So tell me how the account is verified by typing.  In short, the administration doesn’t move at all no matter how much I write to them in a personal or chat room, they don’t even bother to answer, what can I say about eliminating the error.  Guys if anyone knows, explain what they do there

**Comment by Zero-1729** [comment]
Check [these](https://github.com/keybase/keybase-issues/issues/3662#issuecomment-555138400) [comments](https://github.com/keybase/keybase-issues/issues/3656#issuecomment-555066945) for workarounds.

Still, with no official word from either team (Keybase or Stellar), we are only able to speculate on the actual cause of the problem(s). For some the fixes above work, yet, others who verified their account with numbers from their cell carrier and not third party, virtual or VoIP numbers still face this problem.

**Comment by Aldekein** [comment]
I verified my Github in April 2018, now I press "See if you qualify" and it replies "You are qualified to join!", but after I press "Become a lucky airdropee" I get "You are not qualified to join" message, OMG. Linked the Verizon US number and still fails :-/

**Comment by LennertVA** [comment]
Don't bother asking. This whole airdrop thing smells like a massive recruitment scam - make a lot of noise for it, boost your install base tenfold, don't give anything out at all, and gamble on it that a portion of those who joined will keep the client installed.

The unofficial statement of "they have anti-spam measures that aren't documented, you must be using a VoIP number/bad country/insertrandomnonsense" that you can read left an right is bollocks, of course. There's countless reports of valid, bog standard, non spam users being excluded. Coincidentally all "new" users. Issues about it get closed and locked for comments, without further ado.

Just accept that they never intended to give out anything to those who weren't in from the very beginning. Not a great start for a company that wanted to build on trust.
