### ISSUE TITLE
How to reset password using private key and email address?

### ISSUE THREAD

**Issue by xlfe** [keybase/keybase-issues#3666]
Is it possible to reset my password with my email address and PGP private key? It seems all I can do on the web interface is to reset my account (which I'd like to avoid)

Any advice appreciated.

**Comment by hexandcube** [comment]
You can reset your password in the Keybase app.
![Keybase app screenshot](https://user-images.githubusercontent.com/41151156/69009425-4dc75280-0955-11ea-854b-31344078cecf.png)

 If you've lost all your devices/paper keys (or never installed a keybase app), all you can do is to reset your account 😕

**Comment by xlfe** [comment]
Ok thanks
