### ISSUE TITLE
Wallet assets suddenly zero

### ISSUE THREAD

**Issue by smotron** [keybase/keybase-issues#3671]
Is it a bug that according to keybase I have suddenly 0 XLM in the wallet? I was already part of the first airdrop and therefore I already had >350 XLMs in the wallet, now it's zero.

Address: GBRCHQHS4KYXZWR2MFWM7XRXDVU7PJCKGLJNR5YPEFJAKFWS4YJQWTXJ

**Comment by moadibfr** [comment]
Same here, address us GCFLQLUNPN44VHHSA4AZREZ6XAPGQBJ3LWAJFCRNRPE5DV4XPDUAF3KA (also seems like I didn't get the 2nd airdop don't know if related)
I tried logging out and back in on mobile/desktop, my wallet totally disappeared, when I try to add it back it don't do anything...

**Comment by smotron** [comment]
In my case the problem was resolved.

**Comment by moadibfr** [comment]
For me too, I got infos from keybasefriends on keybase. (and the airdrop was not finished)
