### ISSUE TITLE
Error selecting PGP key stored in Trezor T

### ISSUE THREAD

**Issue by valar999** [keybase/keybase-issues#3677]
Hello,

I'm trying to register a pgp key stored in Trezor but I get this error:
```
$ keybase pgp select
[...]
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    2048R   C98102DF399B1B15             <...>
Choose a key: 1
▶ ERROR key generation error: GPG error: exit status 2
```

Info:
```
$ keybase version   
Client:  5.0.0-20191114182642+f73f97dac6
Service: 5.0.0-20191114182642+f73f97dac6
$ gpg --version
gpg (GnuPG) 2.2.17
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/alex/.gnupg/trezor
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
$ gpg -K
/Users/alex/.gnupg/trezor/pubring.kbx
-------------------------------------
sec   nistp256 2019-11-19 [SC]
      84B6F87B1AFDB3AE8B7D85C6F5147C372470B3BC
uid           [ultimate] <...>
ssb   nistp256 2019-11-19 [E]
```

**Comment by valar999** [comment]
Seems like keybase don't use GNUPGHOME environment variable. To get not default keyring location.

**Comment by maxtaco** [comment]
What @valar999 says isn't true. Do a `keybase log send` and we can take a look. Is your pinentry set up properly? That's usually the issue.  Try `export GPG_TTY=$(tty)` as a first thing

**Comment by valar999** [comment]
I've sent logs (id=346a3724c3e4d8ec70fd0a1c).

Please consider following output:
```
$ gpg -K
/Users/alex/.gnupg/trezor/pubring.kbx
-------------------------------------
sec   nistp256 2019-11-19 [SC]
      84B6F87B1AFDB3AE8B7D85C6F5147C372470B3BC
uid           [ultimate] Oleksiy Pyltsov <valar999@gmail.com>
ssb   nistp256 2019-11-19 [E]

$ keybase pgp select
[...]
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    2048R   C98102DF399B1B15             Oleksiy Pyltsov <alex@minerall.io>
```

I think there is no need to set GPG_TTY, because I confirm actions directly on Trezor-T device. No passwords or confirmations on host.

**Comment by maxtaco** [comment]
Is it possible the keybase daemon process doesn't have the environment variable set? I'm not sure how the daemon process is launched in your configuration

**Comment by valar999** [comment]
Yes, it is possible. I will check it. Thanks.

**Comment by valar999** [comment]
I use Mac OS. Try to change `~/Library/LaunchAgents/keybase.service.plist` but it was rewritten after restart. What is a proper way to add env var to keybase service?

**Comment by maxtaco** [comment]
Maybe this works? https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

**Comment by valar999** [comment]
Yes, this solve the problem. Thank you.
