### ISSUE TITLE
Different following counts between web and CLI

### ISSUE THREAD

**Issue by jmeridth** [keybase/keybase-issues#3678]
CLI version: `keybase version 5.0.0-20191114182642+f73f97dac6`

My profile shows I'm following people (via the web UI) that the CLI says I am not.  When I try to unfollow them in CLI I receive this error:

```
$ keybase unfollow [username]
> ERROR Unfollow error: You are not tracking [username]
```

The website says I'm following 23.  According to `keybase list-following` I'm following 11 (as expected).

My username is `jmeridth` on keybase, please message me there to discuss directly if you need an example username.

If this is a known issue, please let me know.  I looked but didn't find any that were open. (#632 was closed and from 2014)

Thank you for your assistance.

**Comment by heronhaye** [comment]
Looks like a bug. We're looking into it, thanks for reporting!

**Comment by heronhaye** [comment]
Should be better now. However, you'll notice the CLI doesn't filter one user that you've followed who has subsequently reset their account.
