### ISSUE TITLE
I qualified but I am not accepted? Help?

### ISSUE THREAD

**Issue by GirlWithAnInkHeart** [keybase/keybase-issues#3685]
I qualified with all 3 requirements, but I'm still not getting approved for the Airdrop.
Is this because I live in Canada? I added an American phone number though.
Help please.

**Comment by GirlWithAnInkHeart** [comment]
Is there a way to contact them to ask about getting approved?

**Comment by gabrielortizoo** [comment]
The same happens to me. At the beginning I was able to qualify for the airdrop without any problem but I retired by mistake. Now that I try to enter again, it doesn't let me, despite qualifying in the 3 requirements.
I'm from Spain.

**Comment by gabrielortizoo** [comment]
You can't participate in the airdrop because you are from Canada. In the website say: "Canada is excluded due to our inability to verify Canadian phone numbers were not purchased at scale."

https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

**Comment by diego66NEK** [comment]
yo califique me acepto ,,medio la bienvenida y luego se me ocurrio enlasar mi GitHub,,y ya no me deja calificar para el  Airdrop.

**Comment by LennertVA** [comment]
See https://github.com/keybase/keybase-issues/issues/3665#issuecomment-557441355.
