### ISSUE TITLE
"Qualified to join" but cannot join Airdrop

### ISSUE THREAD

**Issue by dpieski** [keybase/keybase-issues#3691]
I have all three with green checks and am told I am qualified to join.
I click "Become a lucky airdropee"
I am told "Sorry, you are not qualified to join."

I have multiple devices and multiple papers saved. My phone is a US major carrier number. I'm not event attempting it through my VPN. 

Is there a reason why? What can I do to fix this?

**Comment by LennertVA** [comment]
See https://github.com/keybase/keybase-issues/issues/3665#issuecomment-557441355.
