### ISSUE TITLE
Airdrop: All boxes checked but not qualified

### ISSUE THREAD

**Issue by kevinLee2015** [keybase/keybase-issues#3692]
![image](https://user-images.githubusercontent.com/13792755/69395677-d7db3680-0d1a-11ea-9145-8b5dd279fb97.png)

![image](https://user-images.githubusercontent.com/13792755/69395717-f3ded800-0d1a-11ea-8684-1a8a98fffa71.png)

Can you tell me why? Thank you!

**Comment by LennertVA** [comment]
See https://github.com/keybase/keybase-issues/issues/3665#issuecomment-557441355.

**Comment by kevinLee2015** [comment]
@LennertVA 
Can you have a look at my phone number? I'm using a real phone number from New Zealand.  I'm not a spam user!

**Comment by LennertVA** [comment]
Oh, I bet. Neither am I, nor most if not all of the many, many other people reporting the exact same issue here. But as I said before, I don't think anyone with a "new" keybase account was ever going to get anything.

**Comment by kevinLee2015** [comment]
please define what is a “new” keybase account？I got proof that the github account i used to register is five years old.-------- 原始邮件 --------主题：Re: [keybase/keybase-issues] Airdrop: All boxes checked but not qualified (#3692)发件人：Lennert Van Alboom 收件人：keybase/keybase-issues 抄送：kevinLee2015 ,Author Oh, I bet. Neither am I, nor most if not all of the many, many other people reporting the exact same issue here. But as I said before, I don't think anyone with a "new" keybase account was ever going to get anything.

**Comment by kevinLee2015** [comment]
First, you say my phone number not valid,then you say I'm a new account,why don't you look into my account and give me a real reason?Is it because XLM airdrop is a scam? If so, looking forward to seeing the value of XLM return to zero.-------- 原始邮件 --------主题：Re: [keybase/keybase-issues] Airdrop: All boxes checked but not qualified (#3692)发件人：Lennert Van Alboom 收件人：keybase/keybase-issues 抄送：kevinLee2015 ,Author Oh, I bet. Neither am I, nor most if not all of the many, many other people reporting the exact same issue here. But as I said before, I don't think anyone with a "new" keybase account was ever going to get anything.
