### ISSUE TITLE
Move Keybase accounts

### ISSUE THREAD

**Issue by mberasategi** [keybase/keybase-issues#3695]
I've read #2842 regarding the change of the username, so I created a new account with the desired username. However I also know that usernames of deleted accounts do not become available again, so I don't want to delete my current account.

Now the problem is I can't add my keys to the new account because they are already in use by the old account. I guess I should just revoke them from the old account, but I'm afraid to do so because I haven't found any documentation on whether it is possible to add those public/private keys to a different account or they go revoked _everywhere_ and _forever_...

So my question is, can I revoke keys in one account and then add them to another?

Thanks!

**Comment by heronhaye** [comment]
Yes, if you `keybase pgp drop` the key, you can add it to another account.
