### ISSUE TITLE
The reset account process is broken

### ISSUE THREAD

**Issue by jbriard** [keybase/keybase-issues#3697]
Hello,

I started the reset process 10 day ago, I say "Yes" in the email to start the recovery.
I waited patiently and now, the waiting period is over, but I still cant reset my account.

I get this message : 
"_Check back in **-331472** seconds

The reset has been initiated. For security reasons, nothing will happen in the next -**331472 seconds**. We will notify you once you can proceed with the reset, unless you'd like to cancel the reset. "_

I'm pretty sure the minus time is not OK.

**Comment by heronhaye** [comment]
Thanks, we're looking into it.

**Comment by heronhaye** [comment]
Sorry about that. You should've gotten an email with the correct text now. Does it work for you?

**Comment by jbriard** [comment]
Yes perfect
