### ISSUE TITLE
Chat names and images for individuals and groups not displaying

### ISSUE THREAD

**Issue by blockloop** [keybase/keybase-issues#3724]
![image](https://user-images.githubusercontent.com/3022496/69967872-e07ff980-14de-11ea-8b7b-3c72056c787e.png)
Individual messages and group chats do not display images or names in either dark or light mode on Linux. If I press CTRL+R to reload the page they flash briefly but disappear. However, team threads display the team logo and team name correctly. 

I'm on Manjaro Linux with i3

```
$ yay -Q | grep -i keybase
keybase 4.7.2-1
keybase-gui 4.7.2-1
```

**Comment by heronhaye** [comment]
Please update to keybase 5.0.0 and if it still happens, send feedback in the settings app. Thanks.
