### ISSUE TITLE
Opening Keybase app with audio playing while connected to bluetooth causes audio to pause

### ISSUE THREAD

**Issue by txmoose** [keybase/keybase-issues#3743]
Howdy,

I've noticed this weekend that audio will pause when connected to a bluetooth audio device and the keybase app launches.  I've confirmed this behavior with Pocket Casts, Spotify, and Pandora.  I am on a fully upated Pixel 3 XL, stock.

Please let me know what other logs are needed.

Thanks!

**Comment by joshblum** [comment]
fixed via #22080
