### ISSUE TITLE
Files won't sync/does not exist when online - teammate and history claim files exist

### ISSUE THREAD

**Issue by maiyuki** [keybase/keybase-issues#3747]
There is a file uploaded by my teammate that I need to get access to. It is not visible in my local files or in the app. I see a pink icon with an arrow pointing up next to `Files` in the app menu that usually is not there.

- I do have storage left in my pc to sync
- I tried `keybase fs sync enable <path>` and `keybase fs sync show <path>` and the output is `Status: sync not yet started` and it stays like that
- I checked `keybase fs history <path>` and the file has been uploaded
- Have logged in and out

Have tried to google for a solution but no luck. Running out of ideas here. Help?

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

Ideally, first you can run `keybase fs set-debug-level 2` first and then disable/re-enable the syncing, and let it run for a few minutes before you send the log.  (After you send the log, you can set the debug level back down to 0.)

**Comment by maiyuki** [comment]
I removed keybase and all its directories and files on my computer, revoked device and reinstalled. Now everything is syncing again. Thank you for your reply.
