### ISSUE TITLE
GUI startup fails with non-root install, looks for /opt/keybase/Keybase 

### ISSUE THREAD

**Issue by ftrader** [keybase/keybase-issues#3775]
I've installed keybase on Linux x86_64 as a non-root user with some hassle, and am able to use command line functions, but I'd really like to move to GUI for chat.
However, a final obstacle presented itself:

`run_keybase` fails to open the GUI, and `/home/user/.cache/keybase/Keybase.app.log` seems to give the reason:

`/home/user/keybase/usr/bin/run_keybase: line 123: /opt/keybase/Keybase: No such file or directory`

So it looks like the path is hard coded in the GUI. Is there any way to work around this using env vars or symlinking?
I could not find any helpful documentation or other reports on this problem.

The best solution would of course be to program the GUI to fall back to looking for path in user's folder, like the other tools do.

Thanks for any tips.

**Comment by heronhaye** [comment]
If there's a binary called `Keybase` in your `$PATH`, `run_keybase` will use that.
