### ISSUE TITLE
not receiving recovery email

### ISSUE THREAD

**Issue by brunj7** [keybase/keybase-issues#3790]
Hi,

My laptop crashed and I am now on a new machine now. It seems I can not remember my password either  :( 

I have tried many times to reset it but I do not receive the recovery email for some reason.

In other words, I am in a dead-end here. Help!  same username as here.

**Comment by heronhaye** [comment]
Hi, according to our records, you did not provide either a email address or phone number when you signed up for your account. Since you also forgot your password, it's not possible to reset your account. Sorry.

**Comment by brunj7** [comment]
okay... can you at least delete this account then?
