### ISSUE TITLE
Keybase randomly logged out on device and won't accept password. 

### ISSUE THREAD

**Issue by gablondell** [keybase/keybase-issues#3796]
I've run into a bit of a snag in which I can't get back into my account. 

I'm currently on the device that I've had Keybase on from the beginning and I came back to notice that my account was logged out one day randomly. When trying to log back in, it didn't accept my password. I'm not sure where/if I saved the paper key but could use a hand recovering the account to avoid having to restore it. Please let me know if there is anything I can do to restore the account without losing the history.

Thank you!

**Comment by mlsteele** [comment]
Hi @gablondell. What's the Keybase username? Could you send a log? `keybase log send` on the command line if you're on a computer.

**Comment by gablondell** [comment]
Hey Miles,

Username is gblondell and the log ID = f63980015df1522715a5b21c.

Thanks!

**Comment by mlsteele** [comment]
Keybase can't access an entry in your macos keychain. The entry is derived from your password and used to encrypt your device keys, which are basically what you need to get into the account. It looks like you [don't have a paper key](https://keybase.io/gblondell/devices) so don't bother trying that.

The logs show that logging in automatically last worked on 2019-12-18 and first failed on 2020-01-07. Do you remember doing any macos upgrades or anything that could be related in or shortly before that time? (I hope it's ok that I've shared those dates on github, if you'd rather communicate that kind of info via email or another keybase account lmk).

If you open up Keychain Access (/Applications/Utilities/Keychain Access.app) and search for "keybase", do you see any entries? A screenshot of that Keychain Access search would be great, if it doesn't have private info.

In Keychain Access, is the "login" keychain in the top left locked? Try right clicking and locking and unlocking "login". Also try rebooting your machine.

**Comment by gablondell** [comment]
Hey Miles,

Thanks for looking into this. I've decided I'll just reset the account.

Have a great day,
Garrett

**Comment by mlsteele** [comment]
Ok. I would recommend creating a paper key or a second device after resetting. In case your machine has keychain problems in the future.
