### ISSUE TITLE
Not receiving password account reset email (password reset email has been received)

### ISSUE THREAD

**Issue by 13dimitar** [keybase/keybase-issues#3799]
Hi, I've logged out from my computer and it seems I've forgotten my password. I've received successfully a password reset email, but I can't follow up on it as I've logged out of my computer (the only device where I've keybase set up). I'm trying to do an account reset, however I'm not received an email about it. Please advise.

**Comment by heronhaye** [comment]
What is your Keybase username?

**Comment by 13dimitar** [comment]
13dimitar

**Comment by heronhaye** [comment]
Did you get an email about 6 hours ago? It should have said your reset will start in 3 days. Maybe your spam folder?

**Comment by 13dimitar** [comment]
@heronhaye yes, I've received it. I guess this means that account reset has been triggered, which means we can close my issue.
