### ISSUE TITLE
Account reset

### ISSUE THREAD

**Issue by fmkbrwrs** [keybase/keybase-issues#3800]
Hello,

Last year I created a keybase account but I would like to reset it.
Because I no longer have access to my registered device and the access to my paper keys.
Account reset through the app seem not working. I got the notification "Current session cannot access this endpoint on locked down account".
My keybase username is: fmkbrwrs

Any help is appreciated.

**Comment by heronhaye** [comment]
Accounts in lockdown mode cannot reset: https://keybase.io/docs/lockdown/index/.

**Comment by fmkbrwrs** [comment]
Thnx for your reaction. The link isn't working.
Because my email is also used for this account, i can't create a new account.
Is there no other possibility to reset or delete the account?

**Comment by heronhaye** [comment]
Sorry, fixed the link.

You don't need an email address to make a new account. But if you want to add your old one, you can use a plus address. For example, if your old email was alice@example.com, enter alice+keybase@example.com. Most email providers support this.
