### ISSUE TITLE
Recovering or deleting my account

### ISSUE THREAD

**Issue by brunj7** [keybase/keybase-issues#3802]
Hi,

Following-up on #3790. If you can not recover my account due to lack of email or phone, is it at least possible to delete it? As you can imaging, it is problematic that my connections are sending me messages that I can not access...

Thank you for helping me to resolve this

**Comment by heronhaye** [comment]
Unfortunately not, since there's no way for you to prove the account is yours. For your next account, please add an email address or phone number and either add a second device or make a paper key.
