### ISSUE TITLE
Public Roadmap

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#383]
I think many, if not a lot of people are forgetting that the release of `keybase` is meant as a developer preview by way of selective public pre-alpha and are suggesting __major__ features that simply aren't possible with two devs so early in the development lifecycle. I think it would do a ton of good to have a publicly viewable and maintainable roadmap to see what has already been decided is in the best interest of `keybase` for the future.

**Comment by JohnTheodore** [comment]
When I googled for keybase roadmap, this is the top link. Is there going to be a public roadmap? I'm most interested in the timeline for the android app.

**Comment by zQueal** [comment]
I don't think a public road map will become a thing. Either the devs just don't want to deal with it, or they don't want to put anything down on paper in hopes of working on what they want to work on without having to commit to a public ledger.

Either way, the android app is in the works, but currently in private alpha right now only to Keybase developers. I've been told it's not ready for testing yet.
