### ISSUE TITLE
'user/lookup.json' with the corresponding key_fingerprint returns 0/OK with blank them field

### ISSUE THREAD

**Issue by eyougo** [keybase/keybase-issues#3835]
The api 'user/lookup.json' with usernames return normal result, for example:
https://keybase.io/_/api/1.0/user/lookup.json?usernames=okextest001

but  'user/lookup.json' with the corresponding key_fingerprint returns 0/OK with blank them field, is there some issue?

https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint=1171791eccf6b3d3df07d0f5406c257e090e70aa

**Comment by malgorithms** [comment]
hi thanks for this @eyougo - should be fixed now. thanks.
