### ISSUE TITLE
searching for users by public PGP key fails on keybase.io for saltpack users

### ISSUE THREAD

**Issue by anapsix** [keybase/keybase-issues#3838]
Searching for user profiles by their public PGP key fingerprint on Keybase.io isn not working for some users.

Keybase site search is using `https://keybase.io/_/api/1.0/user/user_search.json?q=somequery` endpoint to lookup user profiles from site's search box (does not appear to be documented in [user lookup API doc](https://keybase.io/docs/api/1.0/call/user/lookup)).

As suggested by @kf5grd, this probably affects only newish users, who signed-up after the switch from PGP to saltpack was made
> my guess would be that the differences you're seeing are caused by the fact that you signed up for keybase back in 2015 when the service actually relied on, and required pgp keys, but @mjwwbmd signed up in august of last year, and prior to that time keybase stopped using pgp for encryption. keybase now uses saltpack instead, but still allows you to have your pgp key on your profile to make a statement that it is indeed your key

## Steps to reproduce
1. visit https://keybase.io
2. open Network tab of browser's "Developer Tools"
2. input `481B5B9FF5846C764AF2F6BD663CF88F0C3B28E5` into "search box"
3. observe "Sorry, no matches" message
4. notice call to `https://keybase.io/_/api/1.0/user/user_search.json?q=481B5B9FF5846C764AF2F6BD663CF88F0C3B28E5&num_wanted=20`, and it's response
5. now input `B416D3911B1D1AA0D47D5F4E5E93F7F309CAC1B2` into "search box"
6. congrats, you found a profile by public PGP key
7. notice call to `https://keybase.io/_/api/1.0/user/user_search.json?q=B416D3911B1D1AA0D47D5F4E5E93F7F309CAC1B2&num_wanted=20`, and it's response

**Comment by malgorithms** [comment]
we're doing some changes to the site search, so this hopefully will be fixed soon.

meantime, if you're asking not because of site results, but because you want to use the API, note that "searching" which is fuzzy (and undocumented) isn't as good as a direct "lookup". This endpoint should get both people:

https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint=481B5B9FF5846C764AF2F6BD663CF88F0C3B28E5

https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint= B416D3911B1D1AA0D47D5F4E5E93F7F309CAC1B2

**Comment by anapsix** [comment]
yep, thanks @malgorithms
I used to rely on `https://keybase.io/_/api/1.0/user/autocomplete.json?q=${fingerprint}`, discovered an issue when tried switching to `https://keybase.io/_/api/1.0/user/user_search.json?q=${finderprint}`, and ended up using `https://keybase.io/_/api/1.0/user/lookup.json?key_fingerprint=${finderprint}`

**Comment by malgorithms** [comment]
this is fixed, thanks!
