### ISSUE TITLE
Could not delete multi-user repos

### ISSUE THREAD

**Issue by nzt** [keybase/keybase-issues#3842]
Hi there! Could you tell me how to delete git repository shared with kbpbot, i.e., I'd like to delete keybase://private/masaya,kbpbot/foobar.git

**Comment by mlsteele** [comment]
There's a "Delete repo" button in the git tab of the app. Or, from the command line `keybase git delete`.

**Comment by nzt** [comment]
Thank you.
I could not do that. here is actual behavior.

```bash
❯ git clone keybase://private/masaya,kbpbot/docs
Cloning into 'docs'...
Initializing Keybase... done.
Syncing with Keybase... done.
Counting: 3.12 MB... done.
Cryptographic cloning: (100.00%) 3.12/3.12 MB... done.

❯ keybase git delete -f keybase://private/masaya,kbpbot/docs
▶ WARNING Git repo doesn't exist. Deleting metadata anyway.
▶ ERROR can't find repo named "keybase://private/masaya,kbpbot/docs"

❯ keybase git delete -f private/masaya,kbpbot/docs 
▶ WARNING Git repo doesn't exist. Deleting metadata anyway.
▶ ERROR can't find repo named "private/masaya,kbpbot/docs"

❯ keybase git delete -f /private/masaya,kbpbot/docs
▶ WARNING Git repo doesn't exist. Deleting metadata anyway.
▶ ERROR can't find repo named "/private/masaya,kbpbot/docs"

❯ keybase git delete -f masaya,kbpbot/docs
▶ WARNING Git repo doesn't exist. Deleting metadata anyway.
▶ ERROR can't find repo named "masaya,kbpbot/docs"

```

**Comment by nzt** [comment]
Moreover,  this repository is not appeared in `keybase git list`.
I would not like to show this result because the output of this command includes my private repositories.

**Comment by mlsteele** [comment]
Gotcha, I see it too. There's some disconnect between the filesystem and `git list` for git repos in multi-user folders. Thanks for the report.

**Comment by strib** [comment]
Yeah we don't support deleting multi-user repos through the normal ways.  (The Keybase Pages doc should really mention that, sorry.)  If you're really sure you don't need it anymore, you can delete it directly with a command like this:

```
keybase rm -r /keybase/private/masaya,kbpbot/.kbfs_git/docs
```

**Comment by nzt** [comment]
@mlsteele Yes. I request you `keybase git list` includes multi-user folders to find the git repos I created.
@strib Thank you, I success to delete my repositories. Would you mind to update The Keybase Pages doc?

**Comment by strib** [comment]
I made an internal ticket to update that Pages doc.

We have no current plans to add multi-user repos to our app, either in the GUI or the CLI, because there are UX issues that need to be explored first, and they aren't high priority at the moment, sorry.

To avoid this in the future, it might be best to use a team/subteam with kbpbot as a reader.  We'll recommend that more in the updated doc.

**Comment by nzt** [comment]
I see. Thank you.

I will close this issue after the update of Keybase Pages doc.

**Comment by nzt** [comment]
Oops, I closed now. I expecte the update will be done.

**Comment by jodrizzle** [comment]
I got it working using the following syntax:
` keybase git delete <repo_name> --team=<team_name>`
Note, you need to be admin, not just a Writer.
