### ISSUE TITLE
Question/Suggestion: MacOS Finder Integration

### ISSUE THREAD

**Issue by einichi** [keybase/keybase-issues#3845]
I already have FUSE installed, but Keybase is prompting me to install it anyway. Will this install a second FUSE kext or will it detect the existing FUSE and just enable the integration?

Would be nice to have an option to proceed without installing FUSE via the Keybase app.

**Comment by strib** [comment]
@einichi Keybase depends on a specific version of fuse, and we can't rely on whichever version you have installed locally.  Sorry for the inconvenience.

**Comment by einichi** [comment]
Understood. That possibility did cross my mind. Thanks for the confirmation.
