### ISSUE TITLE
Undelete account?

### ISSUE THREAD

**Issue by sudoforge** [keybase/keybase-issues#3859]
As of 2014, it appeared that Keybase was unable to undelete accounts. Is this still the case? I use the `sudoforge` moniker almost everywhere online, and would like my username cleared up on Keybase, as a current team uses it for communication.

**Comment by sudoforge** [comment]
Bump.

**Comment by malgorithms** [comment]
it's not possible. Wish I had a better answer for you, but we're unlikely to change this any time soon.
