### ISSUE TITLE
Forgot password, account not linked to email

### ISSUE THREAD

**Issue by wayofthepie** [keybase/keybase-issues#3862]
I set up an account yesterday and cannot remember the password I set/generated for it, also I don't seem to have properly linked it to my email - I must have forgotten to verify it, as no email I have is associated to the account :thinking: I set this up on a live linux distro, so I've lost the device. Is there anyway to recover this account? It is also wayofthepie. I have the PGP key linked to the account, and I have linked the account to this github also. Thanks.

**Comment by pranabdas** [comment]
As far as I know, if you have lost your password and devices, there is no way you can get into your account. Only option is to reset your account, which you can initiate from **Forgot Password** button in the login page. This will delete everything including the keys, teams, verifications. It will generate new key/sig, so you are a whole new person/account.

**Comment by wayofthepie** [comment]
Thanks! That's also impossible in my case as I have no email linked to the account :smile: it was a ridiculous set of events. I have since created a second account anyway. Still strange though that its possible to get an account into this state.

**Comment by pranabdas** [comment]
You mean, it's possible to get an account without an email address? So the previous account you mentioned [wayofthepie](https://keybase.io/wayofthepie) has no way to reach? By the way, you can generate **paper** code, which is treated as a device. It would be helpful, in case you lose Keybase access in all your devices again.

**Comment by wayofthepie** [comment]
> You mean, it's possible to get an account without an email address? So the previous account you mentioned [wayofthepie](https://keybase.io/wayofthepie) has no way to reach? By the way, you can generate **paper** code, which is treated as a device. It would be helpful, in case you lose Keybase access from all your devices again.

Yes, the way I set up the account initially was with a device, but that device was a live linux distro, and I never linked the account to any email or other device before rebooting. I have a paper code for the new account thanks. 

I guess the main question this issue raises is - I can prove I own this account, because I still have the PGP key associated with it and own the accounts I linked to it so is it possible to reset the account in any other way given I have no email or device linked to it.

**Comment by pranabdas** [comment]
I see. But I am afraid Keybase currently has no protocol to reset password this way other than device access (which includes paper key). Won't trusting communication via email or social account be flawed? Keybase does not know your private key, it keeps encrypted blob (that also only if you have chosen to upload). Encrypted using your password which is lost.

**Comment by wayofthepie** [comment]
Sure, what I was thinking is that I could sign something with my private key of which the public key is linked to the account. This would verify I own that key and also the account, and if there was a way to reset this should be enough proof I own the account. As you say though, there may not be anyway to reset the account outside of email or a device.
