### ISSUE TITLE
Keybase in Ubuntu WSL2 won't accept my password

### ISSUE THREAD

**Issue by osioke** [keybase/keybase-issues#3865]
While trying to create a new GPG key using `keybase pgp gen --multi`, passwords generated from 1Password, I enter to encrypt the keys return the error:

`▶ ERROR Bad password: Invalid password. Server rejected login attempt..`

Maybe related to #2096 and I tried @maxtaco solution mentioned there and it didn't work.

EDIT: Log ID: c254ee26447dd7b26d1ab91c

**Comment by maxtaco** [comment]
Can you use the same username/password to log onto the keybase.io website?

**Comment by osioke** [comment]
I could, but that wouldn't be good practice reusing the password?

**Comment by osioke** [comment]
> Can you use the same username/password to log onto the keybase.io website?

Wait, do you mean, I should re-use my keybase.io website login details for this PGP key or try to use the password I used for this PGP key on the keybase website?

I have tried different password combinations and also tried a plain normal password, none worked.

**Comment by maxtaco** [comment]
I think the error you got was Keybase's server's rejecting your passphrase login attempt. You don't need to reuse this password for your GPG keyring if you don't want to

**Comment by osioke** [comment]
Okay, cool @maxtaco, why the rejection though? The passwords were valid.

**Comment by osioke** [comment]
I made an error here, Keybase was asking for my Keybase password, but I kept entering my preferred password 🙈 Sorry!
