### ISSUE TITLE
KBFS - files uploaded not appearing on other computers/mobile

### ISSUE THREAD

**Issue by kellytrinh** [keybase/keybase-issues#3866]
I've got a few devices running keybase.   2 windows and 1 linux and android mobile

uploaded a set of files on windows box.  the 'uploading xxx files. time remaining xxx' is gone now and app doesn't look like doing anything

however on the other devices (other windows, linux and mobile) the uploaded files don't appear.  

I've restarted all the various devices several times and things don't change.

<<edit>> after restarting the original windows box - after a while the uploading bar appears again - so problem uploading so that explains why other devices can't see

however still do have problem - the "Encrypting and updating" seems stuck in a loop with 9s remaining dropping down to 5s and then back to 9s and repeating forever.

**Comment by strib** [comment]
Please do `keybase log send` from the windows box and post the log ID here, and someone can take a look.

**Comment by kellytrinh** [comment]
Hi - maybe related to the problem above but when I try to issue that command, after entering feedback, I get a long pause and then 

"- ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by strib** [comment]
Maybe try to send the logs a few times, it might work once.

**Comment by kellytrinh** [comment]
Worked after a few attempts just now.  log ID is "4869dfc04d67dbed4c1ca71c"

Thanks for all the assistance.

**Comment by strib** [comment]
It looks like that device is stuck in conflict mode.  I'm on vacation right now and can't really look at why that is, but you can try fixing it a couple ways.

Easy way, if it works:
* Run this command from a terminal:
```
keybase fs clear-conflicts /keybase/private/kellytrinh
```

If that gives an error, try this process instead:
* If there's anything in the folder that hasn't been uploaded yet, and that you can recover from somewhere else, copy it out of KBFS and onto your local disk somewhere.
* Completely shut down Keybase and KBFS.
* Find the directory `AppData\Local\Keybase\kbfs_journal\v1\0120bccd1b91ead89a1c868f4cd7ecaccd6b-239e3ca8253a418d` under your local user's home directory.
* Rename that directory to something else, like `239e3ca8253a418d.bkp`.
* Then restart Keybase/KBFS.

At that point, you should be seeing the server's view of the folder, and you can try copying your data in again.

**Comment by kellytrinh** [comment]
Hey there

The "Easy Way" worked.  Thanks for taking time away from vacation to look into this.

That solved the issue and everything appears well in all the boxes now; I am going to close this ticket.

As a suggestion for future - if it is too hard to auto detect this case then perhaps put into User Intereface a button to clear conflicts?

Do take care during vacation in these COVID times and thanks again for help

**Comment by strib** [comment]
We do usually have it in the user interface -- it will show an orange badge for the folder and give you a button to click to resolve the conflict.  I don't know why that didn't work for you, sorry!

Take care too!

**Comment by kellytrinh** [comment]
Problem recurred again and ended up with the same fix to resolve,

I noticed that in the Appdata folder that there there appears to be quite a few folders named "kbfs_conflict_disk_cache909836966" (90 folders in total with different numbers at end) - I suppose safe to delete those as well?

**Comment by ibnunowshad** [comment]
> It looks like that device is stuck in conflict mode. I'm on vacation right now and can't really look at why that is, but you can try fixing it a couple ways.
> 
> Easy way, if it works:
> 
>     * Run this command from a terminal:
> 
> 
> ```
> keybase fs clear-conflicts /keybase/private/kellytrinh
> ```
> 
> If that gives an error, try this process instead:
> 
>     * If there's anything in the folder that hasn't been uploaded yet, and that you can recover from somewhere else, copy it out of KBFS and onto your local disk somewhere.
> 
>     * Completely shut down Keybase and KBFS.
> 
>     * Find the directory `AppData\Local\Keybase\kbfs_journal\v1\0120bccd1b91ead89a1c868f4cd7ecaccd6b-239e3ca8253a418d` under your local user's home directory.
> 
>     * Rename that directory to something else, like `239e3ca8253a418d.bkp`.
> 
>     * Then restart Keybase/KBFS.
> 
> 
> At that point, you should be seeing the server's view of the folder, and you can try copying your data in again.

Is this solution work in MacOS?
