### ISSUE TITLE
Unable to log in on web

### ISSUE THREAD

**Issue by tmm** [keybase/keybase-issues#3870]
When I try to log in, I am redirected to [my page](https://keybase.io/meagher), but not authenticated. The navigation bar still says "Login"

**Comment by heronhaye** [comment]
Did you click the "Open in keybase.io" button in the app? Can you send feedback in the app with logs?

**Comment by tmm** [comment]
I don't have the app. I'm trying to log in on the website.

**Comment by dem1tris** [comment]
Can't log in neither via login/password nor by button on PC. Button works on Android.

**Comment by tmm** [comment]
Still doesn't work on the web fwiw, but I was able to login through the app so closing this so it doesn't (annoyingly) show up on my GitHub dashboard forever.

**Comment by categoryshell** [comment]
Same problem here, can;t login. Using Firefox
