### ISSUE TITLE
command line login fails with ERROR EOF

### ISSUE THREAD

**Issue by digininja** [keybase/keybase-issues#3874]
I've just setup a new account, verified the email address and logged into it through the Linux GUI and web site. From this, I know the account is working and I've got the correct credentials.

I've created the account to use with a different Linux user from the command line only, when I try to login from the command line as that user I get this:

```
$ keybase login
Your keybase username: xxx
▶ ERROR EOF
```

Passing the user name on the command line doesn't help

```
$ keybase login xxx
Failed to reach user-level systemd daemon.
▶ INFO Starting background server with pid=6514
▶ ERROR EOF
```

I've checked and there are no other keybase processes running.

```
$ ps aux | grep keybase
xxxx      6216  0.0  0.0  21532  1116 pts/3    S+   09:39   0:00 grep --color=auto keyba
```

Doing a look up on my main account works fine but confirms that I'm not logged in:

```
$ keybase id digininja
▶ INFO Identifying digininja
✔ public key fingerprint: 79D0 248B 504B 5B30 6911 7DEF D671 D402 E447 F6DB
▶ WARNING error getting user/card for 37a66ab8a79fe46d5807f55ba50ea619: Login required: no sessionArgs available since no login path worked
 [tags:ENG=w-MsB2EjzRNR,ID2=5h__ERY2hibL]
▶ INFO Could not get usercard, so skipping displaying stellar chain link: Login required: no sessionArgs available since no login path worked. [tags:ENG=w-MsB2EjzRNR,ID2=5h__ERY2hibL]
```

I'm running the latest version on Ubuntu:

```
$ keybase version
Client:  5.3.1-20200320154633+3e235215b3
```

What am I missing or what has gone wrong?

**Comment by digininja** [comment]
Just found this issue may be in the wrong place, but here is the log ID:

a549330faa60978a5634221c

**Comment by digininja** [comment]
Running strace on the login, I see a lot of things like this:

```
openat(AT_FDCWD, "/home/xxx/.config/keybase/config.json", O_RDONLY|O_CLOEXEC) = 7
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2287214784, u64=140632401387712}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc0006b2cc4) = -1 EPERM (Operation not permitted)
read(7, "{\n    \"mountdir\": \"/home/xxx/.con"..., 4096) = 107
```

The file is there and writeable by the logged in user.

```
$ ls /home/xxx/.config/keybase/config.json  -al
-rw------- 1 xxx xxx 107 Apr 15 09:26 /home/xxx/.config/keybase/config.json
```

**Comment by digininja** [comment]
I've just tried this on a second machine and got the same result.

**Comment by maxtaco** [comment]
cc @heronhaye I think this is fixed in the next release...

**Comment by digininja** [comment]
Perfect. How long till the is out?

**Comment by maxtaco** [comment]
This week, we hope!

**Comment by heronhaye** [comment]
@digininja Try the nightly: https://keybase.io/docs/linux-user-guide#nightly-builds.

**Comment by heronhaye** [comment]
By the way, are you running on any sort of special configuration? WSL? Via `su` in a SSH session?

**Comment by digininja** [comment]
I've mostly been trying it with su from a login prompt but also tried it
once from the prompt of a normally logged in user, but that user already
had an account registered and logged in so I didn't trust the results when
that one failed.

**Comment by digininja** [comment]
And I'm not in any rush to get it working so happy to wait for a release,
but if it would help your debugging I'm happy to try a nightly build.

**Comment by heronhaye** [comment]
Got it. If you have time it'd be nice to make sure the current code is OK so we don't push out another buggy release, but no problem if not. Le me know if you have any issues with the nightly.

**Comment by digininja** [comment]
Will do.

**Comment by digininja** [comment]
Nightly gets closer, but when trying to use paper key I get this error:

https://github.com/keybase/keybase-issues/issues/3875

**Comment by digininja** [comment]
pinentry problem fixed and the nightly build logs in OK.

**Comment by heronhaye** [comment]
Great, glad it's working. Let us know if you have any more issues!

**Comment by digininja** [comment]
One more quick question, how do I go back to the normal distro build when
it comes out? Do I just uninstall then reinstall from the repo?

**Comment by heronhaye** [comment]
You should just be able to `apt-get update; apt-get upgrade keybase` when the release is out.

**Comment by digininja** [comment]
Great thanks, I'll work out if it doesn't just work.
