### ISSUE TITLE
My Token Was Revoked?

### ISSUE THREAD

**Issue by Daniihh** [keybase/keybase-issues#3888]
My Keybase account's token was either revoked or went bad. My account was not deleted or terminated, as I have not gotten an email from Keybase about any account termination. Somehow I've entered a limbo state.

Issue Description
-----------------------
Keybase boots up very slow. Typically taking minutes to start. When it starts, the only thing I can see is old chat messages (chat messages before this issue started) and old cached pictures. Attempting to fetch messages from the server fails, sending messages fails, everything that requires communicating to the server fails with the message `ERROR CODE 202 - server rejected session; is your device revoked?`. This is not possible though, I never revoked any of my devices or deleted my account. Even weirder is that the `Crypto` tab still works, I can sign stuff and encrypt, although it fails to include myself in the recipients. The worse part about this is: *this has happened across all my devices*... that I have immediate access to anyways, which is very alarming. Clicking on the `Open keybase.io in web browser` button in `Your account` takes me to https://keybase.io/, but it reports `Bad token`. Logging in on https://keybase.io/ just redirects me to my account, and does not login. I've sent my logs once, I think it worked anyways, and I even had my friend reach out to `chris` on Keybase, no response just yet so I thought I'd make this issue here. I hope my Keybase account isn't corrupted or anything.

Who I Am
-------------
I am [daniihh](https://keybase.io/daniihh) on Keybase and it is [cryptographically proven](https://gist.github.com/Daniihh/c6d2094dcdc764fca16a9f7126df9241).

**Comment by ValdikSS** [comment]
Sorry for writing in your issue, I have a different one, but it may be related to some recent changes which caused your and mine issues.

My public PGP key disappeared from the web interface several days ago, without any notice, and encryption dialog (https://keybase.io/encrypt) states I don't have a public key. I did not use keybase software at least in a month, and haven't logged into the web interface too.
As I can see right now, the web interface doesn't show your public key for your account as well, and encryption page also says `Error: Cannot find a public key for 'daniihh'`, just as with mine account.

I've removed (`keybase pgp drop`) the key from my account but could not update it due to (probably unrelated) error:
```
▶ ERROR key generation error: no valid primary key self-signature or key(s) have expired (Skipping signature by another issuer: 20c183f83dba0e63 != 5cd7202eef88f772) (error 905)
```
Signature from 20c183f83dba0e63 of my key 5cd7202eef88f772 is valid and old, and caused no issues with GPG.

**Comment by theredidenttechie** [comment]
> My Keybase account's token was either revoked or went bad. My account was not deleted or terminated, as I have not gotten an email from Keybase about any account termination. Somehow I've entered a limbo state.
> 
> ## Issue Description
> Keybase boots up very slow. Typically taking minutes to start. When it starts, the only thing I can see is old chat messages (chat messages before this issue started) and old cached pictures. Attempting to fetch messages from the server fails, sending messages fails, everything that requires communicating to the server fails with the message `ERROR CODE 202 - server rejected session; is your device revoked?`. This is not possible though, I never revoked any of my devices or deleted my account. Even weirder is that the `Crypto` tab still works, I can sign stuff and encrypt, although it fails to include myself in the recipients. The worse part about this is: _this has happened across all my devices_... that I have immediate access to anyways, which is very alarming. Clicking on the `Open keybase.io in web browser` button in `Your account` takes me to https://keybase.io/, but it reports `Bad token`. Logging in on https://keybase.io/ just redirects me to my account, and does not login. I've sent my logs once, I think it worked anyways, and I even had my friend reach out to `chris` on Keybase, no response just yet so I thought I'd make this issue here. I hope my Keybase account isn't corrupted or anything.
> 
> ## Who I Am
> I am [daniihh](https://keybase.io/daniihh) on Keybase and it is [cryptographically proven](https://gist.github.com/Daniihh/c6d2094dcdc764fca16a9f7126df9241).

I have this exact issue, and have been trying to find a solution for over a week now.

**Comment by BrianitContracting** [comment]
I think I have the same problem... Can't get in on any of my devices.

Very worrying as I have a good bit of XLM in the wallet that I can't get access to.

**Comment by plainhavoc** [comment]
I have the same issue, but not really sure how to fix this. I see no interface to add / change keys at the login, and unable to log in on any device. I do not even see where to use the paper key to recover.
