### ISSUE TITLE
Incorrect Lisp-related information while verifying HN accounts

### ISSUE THREAD

**Issue by phoe** [keybase/keybase-issues#3889]
During the process of verifying my HN account on my keybase.io profile, I am greeted with the following comment:

> Also, HN has a weapons cache. It's called LISP. LISP programmers like even their users to be immutable, so don't be surprised if it takes a few hours for the car of your cdr to merge with the cdr of our car.

![Zrzut ekranu z 2020-04-26 19-24-17](https://user-images.githubusercontent.com/15045546/80314736-88ca8d80-87f3-11ea-9716-d647a8348248.png)

The part "LISP programmers like even their users to be immutable" might be an attempt at a joke for making fun of Lisp and HN, but it's false and demeaning towards the Lisp family of languages. In addition, the tone of that joke shows lack of professionalism from Keybase's side.

Not only Lisp dialects have had mutability since time immemorial and not only the modern dialects of Common Lisp, Scheme, and Racket continue to offer mutability as a standard part of the language; the dialect Common Lisp, which I personally utilize daily, is a multi-paradigm language which allows the programmer to freely use linear, structured, and object-oriented programming paradigms by default, all of which *require* mutability for sane functioning.

In addition, LISP spelled in all capitals refers to the dialect of the language that has not been used since the 1970s. It is therefore weird to see a language dialect dead for over five decades being referred to as a secret weapon of an online service launched in 2007.

---------

Related proofs from CL/Scheme/Racket REPLs:

Common Lisp:
```lisp
* (defvar x 5)
X
* (setf x 42)
42
* x
42
```

Scheme:
```scheme
1 ]=> (define x 5)
;Value: x

1 ]=> (set! x 42)
;Value: 5

1 ]=> x
;Value: 42
```

Racket:

```racket
> (define x 5)
> (set! x 42)
> x
42
```

(For completeness: the Clojure and Shen dialects of Lisp purposefully enforce a more pure-ish and functional programming paradigm by default.)

`</rant>`

**Comment by malgorithms** [comment]
hi, yes, definitely just humor about lisp.  I still remember fondly writing a lisp interpreter long ago, and the joy of some early lisp programming. Probably the most ah-ha moments I've ever had programming.

Most lisp fans respond positively to the humor, so we'll probably keep it. But I'll note your disapproval. thanks for the thoughtful note.

**Comment by phoe** [comment]
Sure, thanks for the answer. It's just sad for me to spend energy and time actually going against the "Lisp is a meme" mainstream idea by fixing and straightening the misinformation surrounding Lisp dialects - only to then see a Keybase joke that does something in the completely opposite direction.

**Comment by theckman** [comment]
Why do you feel it's your personal crusade? Might you feel better just letting it roll off your shoulders, and correcting things that are harmful to the ecosystem and its users?

**Comment by phoe** [comment]
@theckman it's been a longer topic spanning for years, and I've actually been thinking of writing a longer blogpost about the issue.

Summary: a lot of people, including some prominent faces in the programming world in general, have been writing about Lisp as secret sauce, silver bullet, source of programming enlightenment, yadda yadda; basically a set of mystic-sounding buzzwords that, other than causing some people to indeed try Lisp, have left a lot of people confused and amused by the wording - or just plain angry and disappointed at the false marketing that I consider the above hyperboles to be.

I don't feel it's a personal crusade of mine, I just think that there's a voice missing in the above issue that treats Lisp as a programming language that it is like many others, rather than the secret-sauce-meme that it unfortunately became and, IMO, doesn't deserve to be.

But then again, it's blogpost material. I'll link it for context here when it - eventually - gets written.

**Comment by theckman** [comment]
I think there's also the consideration that to become enlightened you need to think differently. It's easy to try something to get some promised benefit from it, but there are many things that take more investment than trying for a year to get the true benefit.

I think that especially applies to languages that are more functional in nature, when lots of folks come from more procedural-like languages. They need to invest in breaking their long-built mental model to work with the system and not against it.

That isn't to say there shouldn't be concerns with how that is conveyed. You should be realistic when sharing the benefits. So I think it's a two way street, and those who get angry have a responsibility to reflect on their expectations and how they tried to meet them. Trying for 6 months or 1 year might not be long enough to get what you were sold.

Looking forward to seeing it!

**Comment by phoe** [comment]
Sure, that's correct. I can see the benefits of the above comments that follow the "any publicity is good publicity" rule. In addition, the more-functional-in-approach Lisp dialects certainly follow the "breaking the long-built mental model" scheme* that you mention, and so does Common Lisp, since it mixes programming paradigms (including functional one) rather freely.

Still, after seeing the effects of the aforementioned hyperbolization of Lisp in the long run, I'm not convinced that its execution went well, and I will write about it someday. Thanks for the discussion, I'll post it here when I'm done.

*pun intended

**Comment by geoff-nixon** [comment]
> @theckman it's been a longer topic spanning for years, and I've actually been thinking of writing a longer blogpost about the issue.
> 
> Summary: a lot of people, including some prominent faces in the programming world in general, have been writing about Lisp as secret sauce, silver bullet, source of programming enlightenment, yadda yadda; basically a set of mystic-sounding buzzwords that, other than causing some people to indeed try Lisp, have left a lot of people confused and amused by the wording - or just plain angry and disappointed at the false marketing that I consider the above hyperboles to be.
> 
> I don't feel it's a personal crusade of mine, I just think that there's a voice missing in the above issue that treats Lisp as a programming language that it is like many others, rather than the secret-sauce-meme that it unfortunately became and, IMO, doesn't deserve to be.

@theckman I too would really like to see such a post. Also, FWIW:

- I am (was) **fully** guilty of being one of those people who treat Lisp as a meme, without knowing two-bits about it.
- It was my Googling the very same Keybase joke that led me to finding this issue, reading your comments, and well, having to eat some humble pie, recognize my own prejudices, and perhaps even invest some time trying to understand/learn it. But you're absolutely right, it's all the things you've mentioned that's put be off for so long. I really hope you do write something to that effect.

So perhaps it should indeed stay?

P.S. Is the name [Sibilant](https://www.flynntix.org/images/Flynn/FA1617/Fall16/LouisPrior(AngelsinAmerica).pdf)[s](https://en.wikipedia.org/wiki/Sibilant#Tongue_shape) already taken (in re: projects, in the world of Lisp)? I imagine it would be, but never hurts to ask. ;)

**Comment by phoe** [comment]
Hey! Thanks for reminding me about it. :smile: Adding it back to my TODO list.

PS: I don't think so, I don't remember any Lisp-related project with that name - why do you ask, other than for the obvious pun?

**Comment by geoff-nixon** [comment]
The obvious pun 😊... and potential name for a project. I always find it most useful when learning a new language/paradigm/anything really, to have an end or project in mind (rather than just complete exercises / "homework"). 

So I were convinced to actually do something with Lisp, I'd probably name it that. 😉
