### ISSUE TITLE
Error checking destination account balance: stellar network error (error 218)

### ISSUE THREAD

**Issue by almccann** [keybase/keybase-issues#3934]
Cannot send from the wallet due to the following error.

![Screen Shot 2020-08-04 at 6 06 20 pm](https://user-images.githubusercontent.com/905696/89270021-197bf980-d67e-11ea-9568-92679c1f59a2.png)

**Comment by almccann** [comment]
The above version is version 4.6.0-20191010081014,134c2d892b.

After upgradeing to version 5.5.0-20200526170801+139bb348af (5.5.0-20200526170801+139bb348af) the wallet is completely inaccessible (spinning wheels).

**Comment by jkamma** [comment]
1. Go to Keybase Wallet settings and copy Secret Key
2. Download Solar Wallet > https://solarwallet.io/
3. Add account > Import Account in Solar Wallet (restore account from backup use Secret Key from Keybase Wallet)
4. Transfer your XLM :)

**Comment by thecobra666** [comment]
@jkamma this doesn't work. The wallet is unable to load and thus doesn't open the settings to download the secret key.

**Comment by jkamma** [comment]
@thecobra666 but this is completely different thing. :) @almccann got access to his wallet.

**Comment by thecobra666** [comment]
> @thecobra666 but this is completely different thing. :) @almccann got access to his wallet.

Not anymore. "After upgradeing to version 5.5.0-20200526170801+139bb348af (5.5.0-20200526170801+139bb348af) **the wallet is completely inaccessible (spinning wheels)."** This is the same problem I'm having. You can open the wallet, but nothing loads it keeps spinning.

**Comment by jkamma** [comment]
@thecobra666 ok you are right. I noticed he has access (image). Yesterday I've got the same problem, but I had access to my secret key. So in my case this solution helped. But without access to Secret key my proposed solution doesn't work.

**Comment by chindraba-work** [comment]
The CLI might offer either the solution or clues to the problem.

 `keybase wallet export <public_key>` should give you the secret key on your terminal.

It's possible that the Stellar network is still not right and the client is freezing while trying to get data from it.

**Comment by almccann** [comment]
Thanks @chindraba-work 

I ended up gaining access to the secret key and account using `keybase wallet export` and using another wallet.
