### ISSUE TITLE
Stellar scam bot

### ISSUE THREAD

**Issue by sylveon** [keybase/keybase-issues#3936]
I've received a message from a scam bot asking for money. I don't see an in-app option to report profiles so I will report here:

![image](https://user-images.githubusercontent.com/6440374/89824134-a44a7180-db20-11ea-8794-2799fe3e4541.png)

![](https://yiff.forsale/VoluminousWarlikeMantyke)

**Comment by chindraba-work** [comment]
@sylveon It the first image you posted, click on the three-dot button next to the chat button. In that menu click on block and you get a few options, on of which includes "report". That should do what you need.

**Comment by sylveon** [comment]
Thank you... It should probably be made more evident
