### ISSUE TITLE
https://henrydenhengst.keybase.io/ the issuer certificate has expired

### ISSUE THREAD

**Issue by henrydenhengst** [keybase/keybase-issues#3965]
Mijn public website https://henrydenhengst.keybase.io/ does not open up in a browser due to ..........

The certificate issuer’s certificate has expired. Check your system date and time.

HTTP Strict Transport Security: true

HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----

**Comment by haukened** [comment]
This because your personal domain is https://henrydenhengst.keybase.pub/

Feel free to close.
