### ISSUE TITLE
Github Domain Verification 

### ISSUE THREAD

**Issue by CemKiraz** [keybase/keybase-issues#4003]
Trying to verify the github domain I created the dns record but "There was an error verifying this DNS record" I get this error. Help

**Comment by kf5grd** [comment]
Can you be more clear about what you're trying to do? If you're trying to prove your github account, that can't be done with a dns record. If you're trying to prove your domain, that has nothing to do with github.

**Comment by CemKiraz** [comment]
> Can you be more clear about what you're trying to do? If you're trying to prove your github account, that can't be done with a dns record. If you're trying to prove your domain, that has nothing to do with github.

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain i've done all the steps in this doc, but it says there is an error in the dns record

**Comment by kf5grd** [comment]
Ah ok. It sounds like you're in the wrong place then. You opened an issue on the Keybase client, but you're following the steps to verify your domain with github, not keybase. If you're intending to verify/prove your domain on keybase, follow the steps in the app on your profile page.

**Comment by CemKiraz** [comment]
thank u for your help.
