### ISSUE TITLE
"Out of space" error message

### ISSUE THREAD

**Issue by 3arabawy** [keybase/keybase-issues#4021]
<img width="343" alt="Screen Shot 2021-04-19 at 11 51 28 AM" src="https://user-images.githubusercontent.com/62758108/115217627-fdce5b80-a105-11eb-8f8e-b7b12d500f9a.png">

I keep getting this error message since yesterday. I don't understand why. But for sure I'm not out of storage space. 
Can anyone help?

**Comment by virtadpt** [comment]
[What happened?  What did you see??](https://xkcd.com/979/)
