### ISSUE TITLE
PGP key lost from web interface but still visible/available/usable from commandline

### ISSUE THREAD

**Issue by frntn** [keybase/keybase-issues#4088]
# Mail notification

I just received a mail from keybase because my mastodon.social proof just broke.
It actually doesn't broke so I though the URL may have changed in a way their bot is not aware yet : https://mastodon.social/web/@frntn/103478843319915448

# PGP key from web interface

But I then saw my PGP key is not displayed in keybase web interface.
The only proposed action is "add a PGP key"
![image](https://user-images.githubusercontent.com/437946/145088122-b1a4046d-02c8-49f3-a8f8-44f1024a1e0f.png)
![image](https://user-images.githubusercontent.com/437946/145088299-88dcb131-eb3b-46d0-8ab7-c8f7b45d12c4.png)

Much more of a concern is the missing downloadable public key : https://keybase.io/frntn/pgp_keys.asc
![image](https://user-images.githubusercontent.com/437946/145088882-8755f67a-0691-4d01-ae35-ccb45252bda5.png)

# PGP key from commandline

I wanted to import my pubkey from web interface but it seems that's not possible anymore
![image](https://user-images.githubusercontent.com/437946/145089372-2bf0a1f1-dec2-484b-970a-fa14ef9b59c8.png)

So I installed keybase on my laptop 
After successful ```keybase login``` I tried to ```keybase pgp select``` but got the following error 
```
$ keybase pgp select
▶ ERROR You already have a PGP key registered (CE46 FE45 3E9E 935C A68C 81D0 D385 289F A809 234F)
Specify the `--multi` flag to override this check
```

So I try to understand which key has been retrieved in keybase keyring after logging in, and it turns out I got my actual PGP key
```
$ keybase pgp list
Keybase Key ID:  01011d7d3f1ac8b54f926b37abdc73199dbfd227a8581585e803d20dc91b6413afa10a
PGP Fingerprint: ce46fe453e9e935ca68c81d0d385289fa809234f
PGP Identities:
   Matthieu Fronton <m@tthieu.fr>
```

# The issue

✔️ Seems like the commandline retrieve my PGP key as I would have expected
❌ Seems like the web interface does not retrieve my PGP key
❌ Seems like the job to check mastodon.social proof fails to retrieve and validate my proof (may be related ?)

```
$ keybase whoami
frntn

$ keybase id frntn
▶ INFO Identifying frntn
✔ public key fingerprint: CE46 FE45 3E9E 935C A68C 81D0 D385 289F A809 234F
🚀  Stellar GB35UENV67BH6VCSTUQNUPVIX73C62PD3KM4JNQS3G7L2QOXECYKUXI6 (frntn*keybase.io)
✔ admin of DNS zone m.tthieu.fr: found TXT entry keybase-site-verification=n9HdhCiQE_NuJ5Le3T6cE3jDRpNlhwS9bS9FxwQTsxE
✔ admin of DNS zone ma.tthieu.fr: found TXT entry keybase-site-verification=Mc420DNBG_Coim6nLm1RDM59A_QPqjdnGa0E6ZSIL3o
✔ "frntn" on github: https://gist.github.com/87f1ec99d666c1f31eeec9f6f7e042d8
✔ "frntn" on twitter: https://twitter.com/frntn/status/776034777765974016
✔ "frntn" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/52q89a/my_keybase_proof_redditfrntn_keybasefrntn/
✔ "frntn" on mastodon.social failed: 404 Not Found (code=240)
```

**Comment by frntn** [comment]
May be similar to #4027

**Comment by zerodogg** [comment]
I also just experienced this. Removing and re-adding as described in https://github.com/keybase/keybase-issues/issues/3960#issuecomment-753982093 solved it

**Comment by frntn** [comment]
Closing this issue as duplicate of #3960 
The remove+readd worked out as stated
