### ISSUE TITLE
Retina Favicon

### ISSUE THREAD

**Issue by lgarron** [keybase/keybase-issues#410]
This just requires adding a 32px version to the favicon. Very easy to make:

    convert "current-16px-favicon.ico" "32-px-favicon.png" "new-favicon.ico"

I've created one here, if you'd like to use it:
<https://www.garron.net/temp/keybase-favicon.ico>
![screenshot 2014-03-28 03 43 25](https://cloud.githubusercontent.com/assets/248078/2548609/d5fe4666-b665-11e3-9440-4c5e780f5916.png)

**Comment by gene1wood** [comment]
Here is a suite of high resolution favicon images and the code to add to the page to use them (the code is also in the zip. These are all based off this [high-res keybase logo](view-source:https://keybase.io/images/icons/logo-no-text.png). Just load these static images into the website and update the page's code to reference them in the header.

[keybase-favicons.zip](https://github.com/keybase/keybase-issues/files/379099/keybase-favicons.zip)

```
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="favicon-128.png" sizes="128x128" />
<meta name="application-name" content="&nbsp;"/>
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="mstile-310x310.png" />
```

**Comment by lgarron** [comment]
> These are all based off this high-res keybase logo.

If they're all scaled versions of the same source, it should be okay to just include one large touch icon, right?

**Comment by gene1wood** [comment]
@lgarron It [sounds like](http://realfavicongenerator.net/faq) they (the multiple precomposed touch images) are needed. I'm no expert on this and was figuring the site that generates these (This [realfavicongenerator.net site](http://realfavicongenerator.net/)) knows what they're talking about but if you background on the apple-touch stuff feel free to tweak the zip file and html and use a subset.

**Comment by lgarron** [comment]
> @lgarron It sounds like they (the multiple precomposed touch images) are needed.

"Needed" is a strong word. A lot of the listed icons are for different cases where letting the browser downscale is fine unless you want special pixel-perfect snapping at medium resolutions.

**Comment by lgarron** [comment]
In any case, it looks like the current favicon.ico is 96x96
