### ISSUE TITLE
Keybase.pub is down, has been for days

### ISSUE THREAD

**Issue by insanityisfree** [keybase/keybase-issues#4123]
Since the official account hasn't even tweeted in two years, I don't think this is going anywhere, but I might as well say that the site is down. I promoted this app a lot, only to see it bought out and basically had development deactivate. Maybe this is just the final aspect of the deathrattle.

**Comment by Sanaki** [comment]
Came looking for the same thing. Is there any indication of how long it's been down? Was just notified by someone who needed access to files there. I have hundreds if not thousands of links to update if this is permanent.

**Comment by insanityisfree** [comment]
> Came looking for the same thing. Is there any indication of how long it's been down? Was just notified by someone who needed access to files there. I have hundreds if not thousands of links to update if this is permanent.

LOL no - looks like I'm the first to bring up an issue about this. Hope it's solved soon - I use these to hold some pretty bad people accountable. Fortunately i have my own site, if need be, but it's mad unprofessional LOL.

**Comment by Lucky225** [comment]
paging @songgao-zoom

**Comment by saizai** [comment]
Keybase is also now sending emails about this, because it broke its own proof check.

```
From: Keybase <notify@keybase.io>
To: keybase@s.ai
Subject: your web (saizai.keybase.pub) proof just broke
Mime-Version: 1.0
Content-Type: text/html

Uh-oh, [saizai](https://keybase.io/saizai?a=redacted), your previously-proven web identity https://saizai.keybase.pub just broke. We've been checking it repeatedly, and it's not working from our perspective.

If you deleted a public proof, remember that proofs must stay public so anyone can trust you without trusting the Keybase.io server.

Here are your options: you can (a) revoke the proof, (b) replace it, or (c) ask us to keep trying. All this can be done from the Keybase app or website.

Thanks! -Keybase
```

**Comment by insanityisfree** [comment]
> Keybase is also now sending emails about this, because it broke its own proof check.

HAHAHA yo... ever since they sold to Zoom and started banning certain communities, it's been rolling downhill. Why take care of your app or push updates if your core audience leaves? Pathetic TBH.

**Comment by Sanaki** [comment]
Looks like it's back up now.

**Comment by Lucky225** [comment]
This issue has once again re-emerged due to wildcard SSL cert expiring yesterday cc @songgao @songgao-zoom
