### ISSUE TITLE
User Profile Picture won't changing with RPC error.

### ISSUE THREAD

**Issue by Senarin** [keybase/keybase-issues#4136]
I tried to change my profile picture, but not changed with server error.
The error occurs both in keybase.io web and Keybase app (desktop and mobile).

On keybase.io web, the error message shows `Sorry, your upload didn't work.` and the browser console shows message including `Error: Server failure: RPC error 200: Error: could not load original image from source`.
![Error screen 1](https://user-images.githubusercontent.com/3144858/176646087-e2c91414-ff2b-41e0-acf1-edf5c5c2683f.png)
![Error screen 2](https://user-images.githubusercontent.com/3144858/176644743-4267161b-69f7-4138-9606-76133736c472.png)

On desktop app, the message shows `This image format is not supported.` on mobile app (Android), it does so.
![Error screen 3](https://user-images.githubusercontent.com/3144858/176645567-099db62d-8819-4939-9f7a-69505937de53.png)

I don't know clearly whether this error is the server's momentary issue or the server code's bug, but this issue needs to be fixed.

**Comment by notNotDaniel** [comment]
I am also experiencing this issue.

**Comment by neuweltgeld** [comment]
same issue here

**Comment by R-K-H** [comment]
Same

**Comment by lauraweindorf** [comment]
same issue for me as well 😭

**Comment by xthample** [comment]
same how to fix

**Comment by iamzenigma** [comment]
Yep, same!

**Comment by ninjapentester** [comment]
Same here.

**Comment by kadrkn** [comment]
![Screenshot_2022-07-03-01-31-30-74_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/37466919/177017920-b3efe0d1-4c33-4145-b79c-0e28c408fc3d.jpg)

i can't solve this problem 🤨

**Comment by xthample** [comment]
![Screenshot_2022-07-03-18-55-17-987_com android chrome](https://user-images.githubusercontent.com/106523041/177038421-bf048e66-57ef-43c2-9c84-5eb68ed91da8.jpg)



Finally I can change the picture

**Comment by R-K-H** [comment]
This seems resolved.
