### ISSUE TITLE
Account recovery - No user, No email

### ISSUE THREAD

**Issue by Soulcrack3107** [keybase/keybase-issues#4142]
Hello everyone, I hope you can help me, I created a Keybase account on September 12, 2019, but I only saved two paper keys, I have no email or saved user, I don't remember either. I would like to recover that account since I must have the airdrop that caused a stir at that time of Stellar. Can I get that account back? Thanks in advance

**Comment by heronhaye** [comment]
Hi, first, ensure your paper keys are 13 words long. Then post *only the first two words* of the paper keys here (this is the public identifier, the other 11 words are secret key material that you should not post publicly). After this, I can look up your username for you.

**Comment by Soulcrack3107** [comment]
Hello friend, you would really help me a lot, yes, the paper keys have 13 words each, the first: (mushroom, summer,...) and the second begins like this: (purity, tone,...)

**Comment by Soulcrack3107** [comment]
> Hi, first, ensure your paper keys are 13 words long. Then post _only the first two words_ of the paper keys here (this is the public identifier, the other 11 words are secret key material that you should not post publicly). After this, I can look up your username for you.

:(

**Comment by heronhaye** [comment]
Hey, sorry about the delay. Your username is `Elmetalero15`. Good luck!

**Comment by Soulcrack3107** [comment]
Thanks my friend!
