### ISSUE TITLE
Account locked

### ISSUE THREAD

**Issue by ssadasivuni** [keybase/keybase-issues#4143]
Hi team, My laptop had hardware issues and lost all app data along with it. I cannot login to the keybase app anymore since the hardware got replaced and had to re-install keybase. My paper key was revoked and I cannot reset my account or delete the old device. I need your help to either unlock my account, reset my account or delete the old device, so I can add a new device and start using keybase with the same username. @heronhaye @maxtaco can you help? Thanks in advance

**Comment by heronhaye** [comment]
Why can't you reset the account? Do you have an email or phone registered?

**Comment by ssadasivuni** [comment]
Hi @heronhaye, I am unable to reset the account since my account is in lockdown mode. I do have an email associated with my account. 

![image](https://user-images.githubusercontent.com/100512415/184695530-feaaa5f0-5b18-4fc9-882a-9aa2c2db9f78.png)
![image](https://user-images.githubusercontent.com/100512415/184695685-529b199a-f403-462d-a761-9a744e582468.png)

**Comment by heronhaye** [comment]
As indicated in the user interface, the purpose of lockdown mode is to prevent an attacker who stole your password or email account from resetting your Keybase account, and implies that the account will be inaccessible if all devices and paper keys are lost.

**Comment by ssadasivuni** [comment]
Thanks @heronhaye. Well so, no way to recover/reset this account you mean and create a new account instead?

**Comment by heronhaye** [comment]
Yes. We recommend making a paper key or two and keeping it safe, and not enabling lockdown mode if you're worried about losing all of your devices and paper keys.
