### ISSUE TITLE
Right-click -> copy link

### ISSUE THREAD

**Issue by sean-dowd-nttd** [keybase/keybase-issues#4191]
Right-clicking on a link doesn't support "Copy Link" and only selects whatever word is under the cursor.  This makes selecting a link to copy into a specific browser window/profile tedious.

**Comment by GwynethLlewelyn** [comment]
Oh... weird. I've just tried it out under macOS Big Sur 11.7.9  — and it works. Aye, it _does_ select the word under the cursor _first_, but the right-click correctly copies the URL (and not just the selected word) into the clipboard.

What OS are you running?

**Comment by sean-dowd-nttd** [comment]
It (KB 6.2.1-20230724165206+e6160f1b9e) seems to be working now.  I'm on Ventura 13.4.1, not sure what caused issue earlier.

**Comment by GwynethLlewelyn** [comment]
I forgot to mention that I was using a prerelease 6.2.1 version. Maybe you still had the previous stable version — I haven't checked that one! — but, anyway, I'd say the issue is now moot, if 6.2.1 works :)
