### ISSUE TITLE
cannot send any message today

### ISSUE THREAD

**Issue by Revelation14-712** [keybase/keybase-issues#4220]
Hi,

This app was working fine for a long time, but just now, nobody who are in my group can send any message, always show red warning, it says: This message failed to send: Api network error

Please check the attachment with this report.

<img width="504" alt="Snipaste_2024-01-01_01-08-04" src="https://github.com/keybase/keybase-issues/assets/125941698/4b1700c6-ac26-46a7-a3a6-b8e422be5781">

So, is there any way to solve this issue? 

Thank you!

Ruth

**Comment by simonforget** [comment]
The SSL certificate itself is not expired. It might be related to the issuing certificate.

I hope that someone at Keybase will see this and act upon soon.

**Comment by danlafreniere** [comment]
Same problem for me; thanks for posting 🍻

**Comment by crap2023** [comment]
Keybase can't send messages it says is offline :) what a crap :)

**Comment by crap2023** [comment]
ohh check the redit post, this is dead  what a crap, cert is run out 12.31.2023 and looks like they need to make a new version of the app whjt a shit.
