### ISSUE TITLE
Expired SSL certificate for keybaseapi.com

### ISSUE THREAD

**Issue by sudoWright** [keybase/keybase-issues#4225]
ERROR CODE 1601 – API network error: doRetry failed, attempts: 3, timeout 5.324s, last err: Get "https://api-0.core.keybaseapi.com/_/api/1.0/home.json?num_people=100&record_visit=0": x509: certificate signed by unknown authority in method keybase.1.home.homeGetScreen

**Comment by peterwilli** [comment]
I get the a  similar problem

```
keybase login
▶ ERROR API network error: Get "https://api-0.core.keybaseapi.com/_/api/1.0/getsalt.json?email_or_username=peterwilli&pdpka_login=1": tls: failed to verify certificate: x509: certificate signed by unknown authority (code 1601)
```

**Comment by hairv** [comment]
Hello,
same for me.

**Comment by RafaelFerreiraTVD** [comment]
Hello, same for me! 👆

**Comment by daveyarwood** [comment]
Duplicate of https://github.com/keybase/keybase-issues/issues/4219. The issue has been identified and fixed in the latest Keybase client version.

**Comment by RafaelFerreiraTVD** [comment]
Forgot to say that the update fixed the issue.

**Comment by sudoWright** [comment]
This cert has been renewed—closing issue. New iOS and macOS client updates successfully.
