### ISSUE TITLE
Keybase.io SSL cert expired on Jun 8, 2024

### ISSUE THREAD

**Issue by yzl3014** [keybase/keybase-issues#4268]
The SSL cert has expired and my browser keeps reminding me of this.

![](https://github.com/keybase/keybase-issues/assets/79385954/53abb78c-450e-44fe-87de-2da3fca3e09b)

**Comment by reiyua** [comment]
![image](https://github.com/user-attachments/assets/9d011104-ad0b-4e4a-aa9e-e0b287928a98)
Seems to be fixed now...
