### ISSUE TITLE
Uploading private Key Error: Error: unknown cipher: 2

### ISSUE THREAD

**Issue by plaetzchen** [keybase/keybase-issues#442]
Hi,

Tried to upload a private key (made with GPGTools on Mac) and got this error "Error: Error: unknown cipher: 2" and I could not save anything.

Philip

**Comment by RulerOf** [comment]
Working on CentOS 6.8 with gpg version 2.0.14, the re-keying process is:

`gpg --s2k-cipher-algo <name> --edit-key <keyid>`

Then run the `passwd` command in the gpg CLI, and supply old/new passwords. Then re-export.

A list of algorithms and a longer explanation is available on the gpg mailing list here: https://lists.gnupg.org/pipermail/gnupg-users/2010-October/039737.html
