### ISSUE TITLE
Interactive approval is needed

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#512]
```
C:\>echo Testing | keybase encrypt zQueal
info: ...checking identity proofs
ok public key fingerprint: 7B5A C030 0E2C 74FD 355C CC81 B1DA 56DC B73E 8516
ok "zqueal" on twitter: https://twitter.com/zqueal/status/449697262059663360
ok "Xanza" on github: https://gist.github.com/9845524
warn: Interactive approval is needed
warn: Bailing out; proofs were not accepted
error: operation was canceled
```

Keybase really just doesn't like streaming under windows. See #510 and #511 

This could probably be avoided by adding a `-y` option to automatically answer yes to interactive prompts, but that's not really smart.

**Comment by adriaanm** [comment]
I'm having the same issue with users that I've successfully encrypted messages for before.

**Comment by earldouglas** [comment]
+1

**Comment by zQueal** [comment]
This is still an issue. 

    USAGE:
       keybase pgp encrypt [command options] <usernames...>
    
    DESCRIPTION:
       If encrypting with signatures, "keybase pgp encrypt" requires an
       imported PGP private key, and accesses the local Keybase keyring when producing
       the signature.
    
    OPTIONS:
       -b, --binary         Output in binary (rather than ASCII/armored).
       -i, --infile         Specify an input file.
       -k, --key            Specify a key to use (otherwise most recent PGP key is used).
       -l, --local          Only track locally, don't send a statement to the server.
       -m, --message        Provide the message on the command line.
       --no-self            Don't encrypt for self.
       -o, --outfile        Specify an outfile (stdout by default).
       -s, --sign           Sign in addition to encrypting.
       --skip-track         Don't track.
       -y                   Approve remote tracking without prompting.

We have an option to approve remote tracking without prompting, but not one to answer yes to all prompts -- specifically;

    Is this the {username} you wanted? [Y/n]

Until such a time that we have this, this is probably going to stay broken.

**Comment by earldouglas** [comment]
I was able to fix this simply by updating my version of keybase from 0.7.8 to 0.8.25.

**Comment by zQueal** [comment]
λ keybase --version
    keybase version 1.0.6-1

    λ echo testing | keybase pgp encrypt zQueal
    - INFO Generating tracking statement for zqueal
    OK public key fingerprint: 7B5A C030 0E2C 74FD 355C CC81 B1DA 56DC B73E 8516
    BTC bitcoin 12csNifta955YUAT7kBC9Dh47bW1Ueieo7
    OK "zqueal" on twitter: https://twitter.com/zqueal/status/449697262059663360 [cached 2015-12-23 21:48:21 EST]
    OK "Xanza" on hackernews: https://news.ycombinator.com/user?id=Xanza [cached 2015-12-23 21:48:23 EST]
    OK "zqueal" on coinbase: https://coinbase.com/zqueal/public-key [cached 2015-12-23 21:48:22 EST]
    OK "zQueal" on github: https://gist.github.com/1fa438d29795ac9476ea [cached 2015-12-23 21:48:22 EST]
    OK admin of DNS zone queal.net: found TXT entry keybase-site-verification=ckK1iVirIRJjyVZ7JU5Fzb94AF1peZCpTFBZJhJ8MAQ [cached 2015-12-23 21:48:21 EST]
    
    Is this the zqueal you wanted? [Y/n] Is this the zqueal you wanted? [Y/n] - ERROR input canceled
