### ISSUE TITLE
Importing keybase private key to gpg

### ISSUE THREAD

**Issue by sfraim** [keybase/keybase-issues#54]
I generated my public/private key pair on keygen.io and then chose not to host the private key, encrypting it and storing it locally. I have since received some messages but I can't import my key into gpg:

I tried to import the private key into gpg unsuccessfully (gpg --allow-secret-key-import --import private.key) with what I believe are the appropriate headers

-----BEGIN PGP PRIVATE KEY BLOCK-----
Version: Keybase OpenPGP JS 0.0.1

<key>
-----END PGP PRIVATE KEY BLOCK-----

I'm getting gpg: packet(1) with unknown version 98

I also tried just hosting the key, but am getting the same error message from the website.

I tried doing the same with a newly created key pair and am getting the same issues, not sure what I'm doing wrong.

I.e. how can I take the private key from keybase and later decide to host it?

**Comment by sbrl** [comment]
@maxtaco How can I obtain my decrypted private key? I can't find anything on the internet on how to decrypt my private key.

**Comment by zQueal** [comment]
@sbrl 

![xefn4s](https://cloud.githubusercontent.com/assets/239193/12028566/35eba9d0-ada7-11e5-902e-54e1705468bc.png)

**Comment by sbrl** [comment]
@zQueal That exports my encrypted private key. I was getting a strange error when attempting to import into gpg, but it seems to have resolved itself now.
