### ISSUE TITLE
how to set which GPG key to use?

### ISSUE THREAD

**Issue by kjetilho** [keybase/keybase-issues#577]
I've been having a lot of problems getting up to speed, e.g., my old key could not be used for encryption(!), just signing ("Usage: S" in output from gpg --edit).  So I created a new key using keybase, but keybase still wanted to use my old key, even though I had updated default-key in gpg.conf.  I finally deleted that key from my public and secret keyrings

 : [kjetilho@zeppo ~]; keybase prove web
 error: You don't have a local secret key!
 : [kjetilho@zeppo ~]; keybase push --update
 info: Updating both remote key with local version
 error: `gpg` exited with code 2
 warn: gpg: error reading key: secret key not available

"gpg --sign" works just fine and uses the key set by default-key.  I'm stumped...

**Comment by kevinSuttle** [comment]
@maxtaco This doesn't work anymore. 
`error: this API endpoint no longer supported; use nuke.json instead (error #238)` 

See context in https://github.com/keybase/keybase-issues/issues/1819

**Comment by maxtaco** [comment]
We need to push a new update to the node client to change the endpoint it
hits, but we'll also be phasing out this client in favor of our new Go
client.

In the mean time, you can use the Web site to reset your account

**Comment by kevinSuttle** [comment]
I tried both the Node and Go clients. FYI.
