### ISSUE TITLE
Feature Request: Support API lookup by email address

### ISSUE THREAD

**Issue by tobiasviehweger** [keybase/keybase-issues#590]
I think keybase is great and has a lot potential, if integrations will be in place.
That said, I would really like the possibility to lookup users by email address, which would allow nearly transparent integration in sending emails. I'm imagining something like this (using MS Outlook as an example).
1. User installs some keybase app and all contacts in the address book are looked up on keybase. Public keys are stored locally and invalidated after a certain amount of time (Maybe a revocation web hook would be ideal)
2. When an email is about to be sent, the app checks for recipients with known public keys and encrypts the mail in the background accordingly.

One caveat could be that the mail must be sent as a copy to these recipients, which possibly messes up email threads with many recipients.

Do you see any security issues with something like this? Keep up the good work!

Tobi (keybase.io/mnkypete)

**Comment by jelhan** [comment]
I didn't understand the problem concerning 2. I think one key point wasn't take into consideration: I know who I want to send an email. I don't want to know if the person owns a specific keybase.io account. I just want to be sure that I got the correct OpenPGP key of a specific person.

I'm not using keybase.io yet but OpenPGP encryption with thunderbird and enigmail a lot. Perhaps I misunderstood something around keybase.io. I though it's just another way to verify that I got a someones correct public key like web of trust, keys in dns records etc.

Therefore I like to lookup keybase.io for a key id or search for an email address in uploaded public key uids like I could do on pgp public key servers. If at least one record was found I could verify the key by connected social network accounts. If I know that the person I like to send my mail to uses this social network account, I could trust the public key. Of course I have to verify this myself when importing the key and setting the trust level.

I think an API endpoint therefore would allow enigmail and other clients to integration with keybase.io looking up keys and helping users to verify them if verification by web of trust key, keys in dns records etc. is not possible.
