### ISSUE TITLE
Twitter account verification fails if account is protected/private

### ISSUE THREAD

**Issue by AltJ** [keybase/keybase-issues#661]
Allow users to be verified with a protected twitter feed.  I imagine it would require keybase's account used on twitter for verification to request to follow the user-to-be-verified and for the user to allow them to follow.

I had to make my twitter account unprotected in order for the verification to pass and to let it be verified in the future.

**Comment by xaviex** [comment]
Maybe this could be possible for people who really want it, im the account bio, that is public to all users

**Comment by rolandog** [comment]
I agree with @xaviex , perhaps pasting in the bio should be enough?
