### ISSUE TITLE
Allow non-alphabetic characters in user names

### ISSUE THREAD

**Issue by dag-erling** [keybase/keybase-issues#757]
Please allow at least hyphens and periods in user names.

**Comment by lfairy** [comment]
> Just now I did a scan of my twitter feed, and I saw 4 different users with underscores in their twitter usernames, and none with hyphens.

Twitter [doesn't allow hyphens in usernames](https://support.twitter.com/articles/101299), so this is a moot point. I agree with the rest of your reasoning though.
