### ISSUE TITLE
Invitation code is not working

### ISSUE THREAD

**Issue by mnishihan** [keybase/keybase-issues#847]
I've received an invitation email from Keybase.io notify@keybase.io with invitation link and code specified. I've followed the link, but the page says:

Accept an Invitation
But wait! You are not at a valid invitation page. That leaves you with 2 options:

```
enter a code manually
request an invitation
```

Then I tried "enter a code manually" option and that says "Invalid invitation code"

I've tried the command line tool as well to signup using the sent invitation code and it also throws

error: Bad invitation code '***************************' given

Is invitation functionality down or somehow the invitation is expired??

**Comment by dorfsmay** [comment]
You should make that clear on the "Cancel & reclaim" button. I did the exact same thing, I thought it'd be easier to Cancel & reclaim and then send them a new invite...
