### ISSUE TITLE
question: where are the pgp keys stored locally

### ISSUE THREAD

**Issue by chrishough** [keybase/keybase-issues#925]
I have a ton of public and private keys on my workstation and I was curious as to where keybase stores the key it generates? Let's say I wanted to uninstall keygen, or rebuild the key b/c my workstation was hacked and I wanted to be sure it was purged.

**Comment by mashirozx** [comment]
> Yes, totally different.
> 
> ~/.gnupg
> On Aug 6, 2014 6:01 PM, "Chris Hough" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > so the gpg keys are stored differently than traditional ssh keys in ~/.ssh
> > so where can you find those files in osx?
> > —
> > Reply to this email directly or view it on GitHub
> > [#925 (comment)](https://github.com/keybase/keybase-issues/issues/925#issuecomment-51403769)
> > .

hello, but which one is the PGP public key?
```
ubuntu@ubuntu:~/.gnupg$ l
private-keys-v1.d/  pubring.kbx  pubring.kbx~  trustdb.gpg
```

I mean like the one like we got on keybase.io web page:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

xsFNBF5Y2KQBEADS1WABEdOR4fcCooJWFORJcs+jF1j7YNC5v2tHgBz9XvYZmzfL
...
J3E/na/lTh531bs4Weo9pt2xoZxCbjWmVxsU3NJbQ6GGMx0IFD5LyHskw7Bs7OZQ
lzzD68/UPXniCLs=
=VjDJ
-----END PGP PUBLIC KEY BLOCK-----
```
