### ISSUE TITLE
Instructions for Coinbase need clarification

### ISSUE THREAD

**Issue by LokiTM** [keybase/keybase-issues#935]
I had a coinbase account, but had not set up a seller page. It was not at all clear in the documentation where I should be pasting the text block. Because I had not set up the page yet, the suggested URL did not exist.

**Comment by HughGlaser** [comment]
Re-open?
The next screen says:
Please post the below text on Coinbase's Keybase page, exactly as it appears.
I couldn't find a "Keybase page" - I spent a while looking, and eventually found there was a "EDIT PUBLIC KEY" link on my public page when logged in.
SO some more clarification/correction of the text would be great.

**Comment by coolaj86** [comment]
I don't know if this update made it in, but I completely did the wrong thing.

For those not in the know:

1) Go to https://www.coinbase.com/settings (to disambiguate between the 2 or 3 different settings buttons in various sections)
2) Scroll down to "Payment Page"
3) Add username
4) Save

**UPDATE**: It's there, I just didn't see it until I went back and hit "replace". Odd...

**Comment by duanev** [comment]
The last intellectual jump is where the coinbase popup asks for Public Key, we apparently are supposed to paste in the entire json text from keybase.  Not quite *completely* obvious as the key is clearly much less ...

**Comment by p1nwheel** [comment]
Did something or maybe I am losing it. Could not find where to change public key in coinbase.

**Comment by Diti** [comment]
Same here. I need to replace an old proof with a new one, but it editing the public key page seems not possible.

**Comment by abliss** [comment]
Keybase commandline app does not tell me to create a username, and even after doing so, I can't figure out how to paste the proof. There's a "caption" textbox but it's limited to 200 chars.
