### ISSUE TITLE
Failing to verify hackernews account

### ISSUE THREAD

**Issue by scarytom** [keybase/keybase-issues#956]
I've made two attempts to verify my hacker news account with keybase now.  Whereas it seems likely that I'm doing something wrong, I'm struggling to see what, and would appreciate some assistance.

https://keybase.io/scarytom
https://news.ycombinator.com/user?id=scarytom

**Comment by zellyn** [comment]
Appears to still be broken…

**Comment by gabipurcaru** [comment]
Still failing: https://news.ycombinator.com/user?id=gabipurcaru

**Comment by maxtaco** [comment]
@gabipurcaru Looks like the API is broken for you.  There's not much we can do about it:

https://hacker-news.firebaseio.com/v0/user/gabipurcaru/about.json

This API has caused countless headaches, but it's out of our control

**Comment by zellyn** [comment]
What is that? Why not scrape my profile page?

**Comment by zellyn** [comment]
I believe this is fixed now. I just verified my hn account in under five minutes.

FWIW, @maxtaco, a simple email to hn@ycombinator.com resulted in a prompt and friendly conversation, and now they believe it to be fixed.

**Comment by maxtaco** [comment]
That's great, thanks @zellyn!  I sent a friendly email to my contact over there, but didn't hear back. But thanks getting through.

Related: #2031, #2040, #2041, etc!

**Comment by maxtaco** [comment]
Also @zellyn we're not allowed to scrape the HN HTML page, they don't want us to, so we're using their preferred API instead.
