### ISSUE TITLE
Add Bitbucket Support

### ISSUE THREAD

**Issue by RyanMarcus** [keybase/keybase-issues#97]
Some of us poor hackers, who are too attached to Mercurial, don't use GitHub for their development.

It might be useful to many users to be able to prove/connect their bitbucket accounts. For example, mine is here: https://bitbucket.org/RyanMarcus

**Comment by AJNOURI** [comment]
Please provide support for wordpress.com public hosting

**Comment by brwnrclse** [comment]
Hey all, Bitbucket seems to have public snippets that operate similarily to Github's Gists. 

Here's a sample keybase markdown file I've created.

https://bitbucket.org/snippets/brwnrclse/eAzxx
