### ISSUE TITLE
Unable to use command line version of Keybase on windows 

### ISSUE THREAD

**Issue by jcroy** [keybase/keybase-issues#992]
when I try to install keybase with node I get (npm should be run outside of the node repl, in your normal shell.) I tried running the install code in the terminal - am i missing some a program? (New to command line and dont know any coding language.

**Comment by lez** [comment]
jcroy can you suggest what the solution was to this problem?

**Comment by oconnor663** [comment]
@lez [this comment](https://github.com/keybase/keybase-issues/issues/992#issuecomment-54730804) was the solution.
